// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../geometry ../Viewpoint ../core/Error ../core/Logger ../core/maybe ../core/promiseUtils ../core/screenUtils ../core/watchUtils ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/has ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/subclass ../geometry/support/webMercatorUtils ../layers/support/TileInfo ./PopupView ./View ./ViewAnimation ./2d/AnimationManager ./2d/FrameTask ./2d/layerViewModuleImportUtils ./2d/MapViewConstraints ./2d/PaddedViewState ./2d/tiling/PagedTileQueue ./2d/tiling/TileInfoView ./2d/tiling/TileKey ./2d/tiling/TileQueue ./2d/tiling/TileStrategy ./2d/viewpointUtils ./2d/layers/features/support/TileStore ./2d/support/Timeline ../geometry/Point ../geometry/Extent ../geometry/SpatialReference".split(" "),
function(w,e,d,x,A,H,y,B,I,J,f,V,W,X,K,z,L,M,N,O,P,Q,C,D,R,Y,S,Z,aa,ba,n,T,E,r,F,U){const p=H.getLogger("esri.views.MapView");d=function(t){function u(a){var b=t.call(this,a)||this;b._stationaryTimer=null;b.frameTask=new Q(w._assertThisInitialized(b));b.featuresTilingScheme=null;b.fullOpacity=1;b.graphicsView=null;b.initialExtent=null;b.map=null;b.labelManager=null;b.renderingOptions={samplingMode:"dynamic",edgeLabelsVisible:!0,labelsAnimationTime:125,labelCollisionsEnabled:!0};b.resizeAlign="center";
b.supportsGround=!1;b.timeline=new E.Timeline;b.type="2d";b.constraints=new D;b.padding={top:0,right:0,bottom:0,left:0};const c=b.handles,g=()=>b.notifyChange("updating");c.add([b.watch("viewpoint",()=>{b._lastStationaryEventTimestamp=performance.now();b._flipStationary(160)},!0),b.on("resize",h=>b._resizeHandler(h)),b.watch("animationManager.animation",h=>{b.animation=h}),b.allLayerViews.on("change",()=>{g();c.remove("map-view-base-layerViewsUpdating");c.add(b.allLayerViews.map(h=>h.watch("updating",
g)),"map-view-base-layerViewsUpdating")})],"map-view-base");return b}w._inheritsLoose(u,t);var k=u.prototype;k.destroy=function(){this.destroyed||(this._set("preconditionsReady",!1),this._gotoTask=this.frameTask=null)};k.goTo=function(a,b){if(a)return this.animation&&(this.animation=null),this._createAnimation(),J.whenTrueOnce(this,"ready",b&&b.signal).then(()=>{const c={animate:!0,...b},g=n.createAsync(a,this);this.animation.update(g);this._gotoTask={};return c.animate?this._gotoAnimated(g,c):this._gotoImmediate(g,
c)});p.error("#goTo()","target cannot be null or undefined")};k.hitTest=function(a){return Promise.reject("Should be implemented by subclasses")};k.popupHitTest=function(a){return this.hitTest(a).then(b=>({...b,mapPoint:this.toMap(a)}))};k.toMap=function(a){if(!this.ready)return null;const [b,c]=this.state.toMap([0,0],[a.x,a.y]);return new r({x:b,y:c,spatialReference:this.spatialReference})};k.toScreen=function(a){if(!this.ready)return null;a=this._normalizeInput(a);a=[a.x,a.y];this.state.toScreen(a,
a);return I.createScreenPoint(a[0],a[1])};k.pixelSizeAt=function(){return this.ready?this.state.resolution:(p.error("#pixelSizeAt()","Map view cannot be used before it is ready"),null)};k.requestUpdate=function(){this.ready&&this.frameTask.requestUpdate()};k.getDefaultSpatialReference=function(){var a,b,c;return this.map&&"initialViewProperties"in this.map&&(null==(a=this.map)?void 0:null==(b=a.initialViewProperties)?void 0:b.spatialReference)||(null==(c=this.defaultsFromMap)?void 0:c.spatialReference)||
null};k.getSpatialReferenceSupport=function({layer:a}){return a||this._get("ready")?{}:null!==this._getDefaultViewpoint()?{}:null};k.importLayerView=function(a){return C.layerView2DImporter.importLayerView(a)};k.hasLayerViewModule=function(a){return C.layerView2DImporter.hasLayerViewModule(a)};k._createAnimation=function(){if(!this.animation||this.animation.done)this.animation=new O;return this.animation};k._cancellableGoTo=function(a,b,c){const g=()=>a===this._gotoTask,h=c.then(()=>{g()&&(this.animation=
null)}).catch(l=>{g()&&(this.animation=null,b.done||(b.stop(),this.frameTask.animationInProgress=!1));throw l;}),m=new Promise(l=>l(h));b.when().catch(()=>{g()&&m.cancel&&m.cancel()});return m};k._gotoImmediate=function(a,b){const c=this._gotoTask,g=this.animation;a=a.then(h=>{B.throwIfAborted(b);if(c!==this._gotoTask)throw new A("view:goto-interrupted","Goto was interrupted");this.viewpoint=g.target=h;g.finish()});return this._cancellableGoTo(c,g,a)};k._gotoAnimated=function(a,b){const c=this._gotoTask,
g=this.animation;a=a.then(h=>{B.throwIfAborted(b);if(c!==this._gotoTask)throw new A("view:goto-interrupted","Goto was interrupted");g.update(h);this.animationManager.animate(g,this.viewpoint,b);return g.when().then(()=>{},()=>{})});return this._cancellableGoTo(c,g,a)};k._resizeHandler=function(a){const b=this.state;if(b){var c=this.state.paddedViewState.viewpoint,g=this.state.paddedViewState.size.concat();b.size=[a.width,a.height];n.resize(c,c,g,this.state.paddedViewState.size,this.resizeAlign);c=
this.constraints.constrain(c,null);this.state.viewpoint=c}};k._startup=function(){const a=this._getDefaultViewpoint();this.constraints.view=this;this.constraints.fit(a);this._set("animationManager",new P({view:this}));this._set("state",new R({padding:this._get("padding"),size:this.size,viewpoint:a}));this._set("featuresTilingScheme",new S(L.create({spatialReference:this.spatialReference,size:512,numLODs:36})));this._set("ready",!0);this.frameTask&&this.frameTask.start()};k._teardown=function(){this.frameTask&&
this.frameTask.stop();this._set("ready",!1);this._stationaryTimer&&(clearTimeout(this._stationaryTimer),this._stationaryTimer=null);const {center:[a,b],spatialReference:c,rotation:g,scale:h}=this.state.paddedViewState,m=new r({x:a,y:b,spatialReference:c});this._set("viewpoint",null);this._set("extent",null);this._set("center",m);this._set("zoom",-1);this._set("rotation",g);this._set("scale",h);this._set("spatialReference",c);this.constraints.view=null;this.animationManager.destroy();this._set("animationManager",
null);this._set("state",null);this.animation=null};k._flipStationary=function(a){return null!==this._stationaryTimer?this._stationaryTimer:this._stationaryTimer=setTimeout(()=>{this._stationaryTimer=null;const b=performance.now()-this._lastStationaryEventTimestamp;160>b&&(this._stationaryTimer=this._flipStationary(b))},a)};k._normalizeInput=function(a,b=this.spatialReference){const c=a&&a.targetGeometry||a;return b?c?b.equals(c.spatialReference)?a:z.canProject(c,b)?a&&"esri.Viewpoint"===a.declaredClass?
(a.targetGeometry=z.project(c,b),a):z.project(c,b):null:null:a};k._getDefaultViewpoint=function(){var a=this.constraints,b=this._get("zoom"),c=this._get("scale"),g=this._normalizeInput(this._get("center")),h=this._normalizeInput(this._get("extent")),m=this._get("rotation"),l=this._normalizeInput(this._get("viewpoint"));a.effectiveLODs?-1!==b&&(c=a.zoomToScale(b)):b=-1;let G=null;var v=null;b=0;a=l&&l.rotation;var q=l&&l.targetGeometry;y.isSome(q)&&("extent"===q.type?G=q:"point"===q.type&&(v=q,b=l.scale));
l=this._normalizeInput(this.get("map.initialViewProperties.viewpoint.targetGeometry.extent"));q=this._normalizeInput(this.initialExtent);h=h||G||l||q;g=g||v||h&&h.center;v=this.get("map.initialViewProperties.viewpoint.scale");c=c||b||v||h&&n.extentToScale(h,this.size);b=this.get("map.initialViewProperties.viewpoint.rotation");return g&&c?new x({targetGeometry:g,scale:c,rotation:m||a||b||0}):null};w._createClass(u,[{key:"_defaultsFromMapSettings",get:function(){return{required:{tileInfo:!0,heightModelInfo:!1,
extent:!1}}}},{key:"animation",set:function(a){var b=this._get("animation");a!==b&&(b&&b.stop(),!a||a.isFulfilled()?this._set("animation",null):(this._set("animation",a),this.frameTask.animationInProgress=!0,b=()=>{a===this._get("animation")&&(this._set("animation",null),this.frameTask.requestFrame());this.frameTask.animationInProgress=!1},a.when(b,b)))}},{key:"center",get:function(){if(!this.ready)return this._get("center");const {center:a,spatialReference:b}=this.state.paddedViewState;return new r({x:a[0],
y:a[1],spatialReference:b})},set:function(a){if(null!=a)if(this._normalizeInput(a))if(this.ready){var b=this.viewpoint;n.centerAt(b,b,a);this.viewpoint=b}else this._set("center",a),this.notifyChange("initialExtentRequired");else p.error("#center",`incompatible spatialReference ${JSON.stringify(a.spatialReference)} with view's spatialReference ${JSON.stringify(this.spatialReference)}`)}},{key:"constraints",set:function(a){const b=this._get("constraints");b&&(this.handles.remove("map-view-base-constraints"),
b.destroy());this._set("constraints",a);a&&(a.view=this,this.ready&&(this.state.viewpoint=a.fit(this.state.paddedViewState.viewpoint)),this.handles.add(a.on("update",()=>{this.ready&&this.state&&(this.state.viewpoint=a.fit(this.state.paddedViewState.viewpoint))}),"map-view-base-constraints"))}},{key:"extent",get:function(){return this.ready?this.state.paddedViewState.extent.clone():this._get("extent")},set:function(a){if(null!=a){var b=this._normalizeInput(a);b?b.width&&b.height?this.ready?(a=this.viewpoint,
n.setExtent(a,a,b,this.size,{constraints:this.constraints}),this.viewpoint=a):(this._set("extent",b),this._set("center",null),this._set("viewpoint",null),this._set("scale",0),this._set("zoom",-1),this.notifyChange("initialExtentRequired")):p.error("#extent","invalid extent size"):p.error("#center",`incompatible spatialReference ${JSON.stringify(a.spatialReference)} with view's spatialReference ${JSON.stringify(this.spatialReference)}`)}}},{key:"graphicsTileStore",get:function(){return new T(this.featuresTilingScheme)}},
{key:"initialExtentRequired",get:function(){const a=this._normalizeInput(this.center),b=this._normalizeInput(this.viewpoint),c=this._normalizeInput(this.extent),{scale:g,constraints:h}=this;let m=this.zoom;if(this.get("map.initialViewProperties.viewpoint")||c)return!1;h.effectiveLODs||(m=-1);return a&&(0!==g||-1!==m)||b&&y.isSome(b.targetGeometry)&&("extent"===b.targetGeometry.type||b.scale)?!1:!0}},{key:"padding",get:function(){return this.ready?this.state.padding:this._get("padding")},set:function(a){this.ready?
(this.state.padding=a,this._set("padding",this.state.padding)):this._set("padding",a)}},{key:"resolution",get:function(){return this.state?this.state.resolution:0}},{key:"rotation",get:function(){return this.ready?this.state.rotation:this._get("rotation")},set:function(a){if(!isNaN(a))if(this.ready){var b=this.viewpoint;n.rotateTo(b,b,a);this.viewpoint=b}else this._set("rotation",a)}},{key:"scale",get:function(){return this.ready?this.state.scale:this._get("scale")},set:function(a){if(a&&!isNaN(a))if(this.ready){var b=
this.viewpoint;n.scaleTo(b,b,a);this.viewpoint=b}else{this._set("scale",a);this._set("zoom",-1);if(a=this._get("extent"))this._set("extent",null),this._set("center",a.center);this.notifyChange("initialExtentRequired")}}},{key:"stationary",get:function(){return!this.animation&&!this.navigating&&!this._get("resizing")&&!this._stationaryTimer}},{key:"updating",get:function(){return!this.destroyed&&(!0===this.get("layerViewManager.updating")||!0===this.get("labelManager.updating")||!0===this.get("graphicsView.updating")||
this.allLayerViews.some(a=>!a.destroyed&&!("layerViews"in a)&&!0===a.updating))}},{key:"viewpoint",get:function(){if(!this.ready)return this._get("viewpoint");const a=this.state.paddedViewState;return a&&a.viewpoint.clone()},set:function(a){if(null!=a){var b=this._normalizeInput(a);b?this.ready?(a=new x({targetGeometry:new r,scale:0,rotation:0}),n.copy(a,b),this.constraints.constrain(a,this.state.paddedViewState.viewpoint),this.state.viewpoint=a,this.frameTask.requestFrame(),this._set("viewpoint",
a)):(this._set("viewpoint",b),this._set("extent",null),this._set("center",null),this._set("zoom",-1),this._set("scale",0),this.notifyChange("initialExtentRequired")):!a.scale||isNaN(a.scale)?p.error("#viewpoint",`invalid scale value of ${a.scale}`):y.isNone(a.targetGeometry)?p.error("#viewpoint","geometry not defined"):p.error("#viewpoint",`incompatible spatialReference ${JSON.stringify(a.targetGeometry.spatialReference)} with view's spatialReference ${JSON.stringify(this.spatialReference)}`)}}},
{key:"zoom",get:function(){return this.ready?this.constraints.scaleToZoom(this.scale):this._get("zoom")},set:function(a){if(null!=a){if(!this.ready){this.notifyChange("initialExtentRequired");this._set("zoom",a);this._set("scale",0);var b=this._get("extent");b&&(this._set("extent",null),this._set("center",b.center))}this.constraints.effectiveLODs&&(b=this.viewpoint,n.scaleTo(b,b,this.constraints.zoomToScale(a)),this.viewpoint=b,this._set("zoom",this.constraints.scaleToZoom(this.scale)))}}}]);return u}(M.PopupView(N));
e.__decorate([f.property()],d.prototype,"_stationaryTimer",void 0);e.__decorate([f.property()],d.prototype,"_defaultsFromMapSettings",null);e.__decorate([f.property()],d.prototype,"animation",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"animationManager",void 0);e.__decorate([f.property({value:null,type:r,dependsOn:["state.id","ready"]})],d.prototype,"center",null);e.__decorate([f.property({type:D})],d.prototype,"constraints",null);e.__decorate([f.property({value:null,type:F,dependsOn:["state.id",
"ready"]})],d.prototype,"extent",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"featuresTilingScheme",void 0);e.__decorate([f.property()],d.prototype,"fullOpacity",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"graphicsTileStore",null);e.__decorate([f.property()],d.prototype,"graphicsView",void 0);e.__decorate([f.property({type:F})],d.prototype,"initialExtent",void 0);e.__decorate([f.property({dependsOn:["map.initialViewProperties?.viewpoint","constraints.effectiveLODs",
"spatialReference"]})],d.prototype,"initialExtentRequired",null);e.__decorate([f.property()],d.prototype,"map",void 0);e.__decorate([f.property()],d.prototype,"labelManager",void 0);e.__decorate([f.property({value:{top:0,right:0,bottom:0,left:0},cast:t=>({top:0,right:0,bottom:0,left:0,...t})})],d.prototype,"padding",null);e.__decorate([f.property({type:Object})],d.prototype,"renderingOptions",void 0);e.__decorate([f.property()],d.prototype,"resizeAlign",void 0);e.__decorate([f.property({readOnly:!0,
dependsOn:["state.id"]})],d.prototype,"resolution",null);e.__decorate([f.property({value:0,type:Number,dependsOn:["state.id","ready"]})],d.prototype,"rotation",null);e.__decorate([f.property({value:0,type:Number,dependsOn:["state.id","ready"]})],d.prototype,"scale",null);e.__decorate([f.property({type:U,dependsOn:["map.initialViewProperties?.spatialReference","defaultsFromMap.ready"]})],d.prototype,"spatialReference",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"state",void 0);e.__decorate([f.property({dependsOn:["animation",
"navigating","resizing","_stationaryTimer"]})],d.prototype,"stationary",null);e.__decorate([f.property({readOnly:!0})],d.prototype,"supportsGround",void 0);e.__decorate([f.property({type:E.Timeline,readOnly:!0})],d.prototype,"timeline",void 0);e.__decorate([f.property({readOnly:!0})],d.prototype,"type",void 0);e.__decorate([f.property({readOnly:!0,dependsOn:["layerViewManager.updating","labelManager.updating","graphicsView?.updating"]})],d.prototype,"updating",null);e.__decorate([f.property({value:null,
type:x,dependsOn:["state.id","ready"]})],d.prototype,"viewpoint",null);e.__decorate([f.property({value:-1,dependsOn:["state.id"]})],d.prototype,"zoom",null);return d=e.__decorate([K.subclass("esri.views.MapViewBase")],d)});