// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Error ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/urlUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/support/zscale ./StreamConnection".split(" "),function(f,n,v,k,A,
q,x,B,y,F,G,H,C,D,E){const h=A.getLogger("esri.layers.graphics.sources.connections.WebSocketConnection");f.ReadyState=void 0;(function(g){g[g.CONNECTING=0]="CONNECTING";g[g.OPEN=1]="OPEN";g[g.CLOSING=2]="CLOSING";g[g.CLOSED=3]="CLOSED"})(f.ReadyState||(f.ReadyState={}));f.WebSocketConnection=function(g){function r(c){var b=g.call(this)||this;b.errorString=null;const {geometryType:d,spatialReference:a,sourceSpatialReference:e}=c;b._config=c;b._featureZScaler=D.getGeometryZScaler(d,e,a);b._open();return b}
n._inheritsLoose(r,g);var l=r.prototype;l._open=function(){var c=n._asyncToGenerator(function*(){yield this._tryCreateWebSocket();this.destroyed||(yield this._handshake())});return function(){return c.apply(this,arguments)}}();l.destroy=function(){q.isSome(this._websocket)&&(this._websocket.onopen=null,this._websocket.onclose=null,this._websocket.onerror=null,this._websocket.onmessage=null,this._websocket.close());this._websocket=null};l._tryCreateWebSocket=function(){var c=n._asyncToGenerator(function*(b=
this._config.source.path,d=1E3,a=0){try{if(!this.destroyed){var e=B.addQueryParameters(b,this._config.customParameters);this._websocket=yield this._createWebSocket(e);this.notifyChange("connectionStatus")}}catch(p){if(e=d/1E3,this._config.maxReconnectionAttempts&&a>=this._config.maxReconnectionAttempts)h.error(new k("websocket-connection","Exceeded maxReconnectionAttempts attempts. No further attempts will be made")),this.destroy();else return h.error(new k("websocket-connection",`Failed to connect. Attempting to reconnect in ${e}s`,
p)),yield x.after(d),this._tryCreateWebSocket(b,Math.min(1.5*d,1E3*this._config.maxReconnectionInterval),a+1)}});return function(){return c.apply(this,arguments)}}();l._createWebSocket=function(c){return new Promise((b,d)=>{const a=new WebSocket(c);a.onopen=()=>{a.onopen=null;this.destroyed?(a.onclose=null,a.close()):(a.onclose=e=>this._onClose(e),a.onerror=e=>this._onError(e),a.onmessage=e=>this._onMessage(e),b(a))};a.onclose=e=>{a.onopen=a.onclose=null;d(e)}})};l._handshake=function(){var c=n._asyncToGenerator(function*(b=
1E4){const d=this._websocket;if(!q.isNone(d)){var a=x.createResolver(),e=d.onmessage,{filter:p,outFields:w,spatialReference:t}=this._config;a.timeout(b);d.onmessage=u=>{var z;let m=null;try{m=JSON.parse(u.data)}catch(I){}m&&"object"===typeof m||(h.error(new k("websocket-connection","Protocol violation. Handshake failed - malformed message",u.data)),a.reject(),this.destroy());(null==(z=m.spatialReference)?void 0:z.wkid)!==(null==t?void 0:t.wkid)&&(h.error(new k("websocket-connection",`Protocol violation. Handshake failed - expected wkid of ${t.wkid}`,
u.data)),a.reject(),this.destroy());"json"!==m.format&&(h.error(new k("websocket-connection","Protocol violation. Handshake failed - format is not set",u.data)),a.reject(),this.destroy());p&&m.filter!==p&&h.error(new k("websocket-connection","Tried to set filter, but server doesn't support it"));w&&m.outFields!==w&&h.error(new k("websocket-connection","Tried to set outFields, but server doesn't support it"));d.onmessage=e;a.resolve()};d.send(JSON.stringify({filter:p,outFields:w,format:"json",spatialReference:{wkid:t.wkid}}));
return a.promise}});return function(){return c.apply(this,arguments)}}();l._onMessage=function(c){try{const b=JSON.parse(c.data);if("featureResult"!==b.type)throw new k("websocket-connection","Protocol violation - Expected to find message of type 'featureResult'",b);for(const d of b.features)q.isSome(this._featureZScaler)&&this._featureZScaler(d.geometry),this.onFeature(d)}catch(b){h.error(new k("websocket-connection","Failed to parse message",b)),this.destroy()}};l._onError=function(c){this._set("errorString",
"Encountered an error over WebSocket connection");h.error("websocket-connection","Encountered an error over WebSocket connection")};l._onClose=function(c){this._websocket=null;this.notifyChange("connectionStatus");1E3!==c.code&&h.error("websocket-connection",`WebSocket closed unexpectedly with error code ${c.code}`);this.destroyed||this._open()};n._createClass(r,[{key:"connectionStatus",get:function(){if(q.isNone(this._websocket))return"disconnected";switch(this._websocket.readyState){case f.ReadyState.CONNECTING:case f.ReadyState.OPEN:return"connected";
case f.ReadyState.CLOSING:case f.ReadyState.CLOSED:return"disconnected"}}}]);return r}(E);v.__decorate([y.property()],f.WebSocketConnection.prototype,"connectionStatus",null);v.__decorate([y.property()],f.WebSocketConnection.prototype,"errorString",void 0);f.WebSocketConnection=v.__decorate([C.subclass("esri.layers.graphics.sources.connections.WebSocketConnection")],f.WebSocketConnection);Object.defineProperty(f,"__esModule",{value:!0})});