// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Collection ../../../core/has ../../../core/Error ../../../core/maybe ../../../core/promiseUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/decorators/subclass ./LayerView3D ../../layers/LayerView".split(" "),function(k,r,h,v,f,t,l,u,m,w,x,y){const p=n=>Object.freeze({__proto__:null,default:n});f=function(n){function q(a){a=n.call(this,a)||this;a.type="analysis-3d";
a.allAnalysisViews=new v;a._creatingViewCount=0;a._analysisViewCreationTasks=new Map;a._analysisModules={"area-measurement":{module:null},"direct-line-measurement":{module:null},"line-of-sight":{module:null},slice:{module:null}};return a}r._inheritsLoose(q,n);var g=q.prototype;g.initialize=function(){for(const a of this.layer.analyses)this._createAnalysisView(a);this.handles.add([this.layer.analyses.on("after-add",a=>{this._createAnalysisView(a.item)}),this.layer.analyses.on("after-remove",a=>{var b=
this.allAnalysisViews.removeAt(this.allAnalysisViews.findIndex(c=>c.analysis===a.item));l.isSome(b)&&b.destroy();b=this._analysisViewCreationTasks.get(a.item);l.isSome(b)&&(b.abort(),this._analysisViewCreationTasks.delete(a.item))})],"analysis-view-handles")};g.destroy=function(){this.handles.remove("analysis-view-handles");this.allAnalysisViews.drain(a=>a.destroy());this._analysisViewCreationTasks.clear();this._creatingViewCount=0};g.whenAnalysisView=function(a){const b=this._analysisViewCreationTasks.get(a);
if(l.isSome(b))return b.promise;a=new t("layerview:no-analysisview-for-analysis","The analysis has not been added to the AnalysisLayer of this layer view",{analysis:a});return Promise.reject(a)};g.isUpdating=function(){return 0!==this._creatingViewCount||this.allAnalysisViews.some(a=>a.updating)};g._createAnalysisView=function(a){this._analysisViewCreationTasks.set(a,u.createTask(b=>this._createAnalysisViewPromise(a,b)))};g._createAnalysisViewPromise=function(){var a=r._asyncToGenerator(function*(b,
c){this._creatingViewCount+=1;var d=b.type,e=this._analysisModules[d];l.isNone(e.module)&&(d=yield this._loadAnalysisModule(d),e.module=d);e=new e.module.default({analysis:b,view:this.view,parent:this});yield e.when();--this._creatingViewCount;if(u.isAborted(c))throw e.destroy(),new t("layerview:no-analysisview-for-analysis","The analysis has not been added to the AnalysisLayer of this layer view",{analysis:b});this.allAnalysisViews.add(e);return e});return function(b,c){return a.apply(this,arguments)}}();
g._loadAnalysisModule=function(a){switch(a){case "area-measurement":return new Promise((b,c)=>k(["../analysis/AreaMeasurement/AreaMeasurementView3D"],d=>b(p(d)),c));case "direct-line-measurement":return new Promise((b,c)=>k(["../analysis/DirectLineMeasurement/DirectLineMeasurementView3D"],d=>b(p(d)),c));case "line-of-sight":return new Promise((b,c)=>k(["../analysis/LineOfSight/LineOfSightView3D"],d=>b(p(d)),c));case "slice":return new Promise((b,c)=>k(["../analysis/Slice/SliceView3D"],d=>b(p(d)),
c));default:return null}};return q}(x.LayerView3D(y));h.__decorate([m.property()],f.prototype,"type",void 0);h.__decorate([m.property()],f.prototype,"layer",void 0);h.__decorate([m.property()],f.prototype,"allAnalysisViews",void 0);h.__decorate([m.property()],f.prototype,"_creatingViewCount",void 0);return f=h.__decorate([w.subclass("esri.views.3d.layers.AnalysisLayerView3D")],f)});