// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/asyncUtils ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../geometry/Extent ../../../geometry/support/aaBoundingRect ./LayerView3D ./support/overlayImageUtils ./support/projectExtentUtils ../support/debugFlags ../webgl-engine/lib/RenderGeometry ../webgl-engine/lib/Texture ../webgl-engine/materials/ImageMaterial ../../layers/LayerView ../../layers/RefreshableLayerView".split(" "),
function(l,r,C,D,u,k,F,v,n,S,T,G,E,m,H,x,I,J,K,L,M,N,O){const y=D.getLogger("esri.views.3d.layers.DynamicLayerView3D");n=function(z){function A(){var a=z.apply(this,arguments)||this;a.drapeSourceType=0;a.updatePolicy=1;a.fullExtentInLocalViewSpatialReference=null;a.maximumDataResolution=null;a._images=[];a._extents=[];a._overlays=[];a.updateWhenStationary=!0;a.refreshDebounced=k.debounce(function(){var c=l._asyncToGenerator(function*(b){a.destroyed||(yield a._doRefresh(b).catch(e=>{k.isAbortError(e)||
D.getLogger(a.declaredClass).error(e)}))});return function(b){return c.apply(this,arguments)}}(),2E3);return a}l._inheritsLoose(A,z);var g=A.prototype;g.initialize=function(){this.addResolvingPromise(I.toViewIfLocal(this).then(a=>this._set("fullExtentInLocalViewSpatialReference",a)));this.updatingHandles.add(this,"suspended",()=>this._suspendedChangeHandler());this.handles.add(this.view.resourceController.scheduler.registerIdleStateCallbacks(()=>{this._isScaleRangeActive()&&this.notifyChange("suspended")},
()=>{}));this._isScaleRangeLayer()&&this.updatingHandles.add(this.layer,"scaleRangeId",()=>this.notifyChange("suspended"))};g.destroy=function(){this.clear()};g.setDrapingExtent=function(a,c){this._spatialReference=c;a.forEach(b=>{this._overlays[b.index]=b;this._updateImageExtent(b)})};g._updateImageExtent=function(a){const c=this._clippedExtent(a.extent,P);if(!u.isNone(c)){var b=x.computeImageExportSize(a.extent,c,a.resolution),e=a.pixelRatio*this.view.pixelRatio;if("imageMaxWidth"in this.layer||
"imageMaxHeight"in this.layer){var h=this.layer.imageMaxWidth,d=this.layer.imageMaxHeight;if(b.width>h){const f=h/b.width;b.height=Math.floor(b.height*f);b.width=h;e*=f}b.height>d&&(h=d/b.height,b.width=Math.floor(b.width*h),b.height=d,e*=h)}d=this._extents[a.index];d&&m.equals(d.extent,c)&&this._imageSizeEquals(c,d.imageSize,b)||(this._extents[a.index]={extent:m.create(c),imageSize:b,pixelRatio:e},this.suspended||this._fetch(a.index).catch(f=>{k.isAbortError(f)||y.error(f)}))}};g.clear=function(){for(let a=
0;a<this._images.length;a++)this._clearImage(a)};g.doRefresh=function(){var a=l._asyncToGenerator(function*(){return this._doRefresh()});return function(){return a.apply(this,arguments)}}();g._doRefresh=function(){var a=l._asyncToGenerator(function*(c){if(!this.suspended){var b=[];for(let e=0;e<this._extents.length;e++)this._extents[e]&&b.push(this._fetch(e,c));yield k.eachAlways(b)}});return function(c){return a.apply(this,arguments)}}();g.canResume=function(){if(!z.prototype.canResume.call(this))return!1;
if(this._isScaleRangeLayer()){const {minScale:a,maxScale:c}=this.layer;if(0<a||0<c){const b=this.view.scale;if(b<c||0<a&&b>a)return!1}}return!0};g.isUpdating=function(){return this._images.some(a=>!!a.loadingPromise)};g.processResult=function(){var a=l._asyncToGenerator(function*(c,b,e){if(b instanceof HTMLImageElement||b instanceof HTMLCanvasElement)c.image=b});return function(c,b,e){return a.apply(this,arguments)}}();g.findExtentInfoAt=function(a){for(const c of this._extents){const b=c.extent;
if((new E(b[0],b[1],b[2],b[3],this._spatialReference)).contains(a))return c}return null};g.getFetchOptions=function(){};g.redraw=function(){var a=l._asyncToGenerator(function*(c,b){var e=this;yield C.forEach(this._images,function(){var h=l._asyncToGenerator(function*(d,f){d&&(yield c(d,b),yield e._createStageObjects(f,d.image,b))});return function(d,f){return h.apply(this,arguments)}}())});return function(c,b){return a.apply(this,arguments)}}();g._imageSizeEquals=function(a,c,b){if(!this.maximumDataResolution)return!1;
const e=m.width(a)/this.maximumDataResolution.x;a=m.height(a)/this.maximumDataResolution.y;a=Math.abs(a/c.height-a/b.height);const h=J.TESTS_DISABLE_OPTIMIZATIONS?0:1.5;return Math.abs(e/c.width-e/b.width)<=h&&a<=h};g._fetch=function(){var a=l._asyncToGenerator(function*(c,b){var e=this;if(!this.suspended){var h=this._extents[c],d=h.extent;this._images[c]||(this._images[c]={texture:null,material:null,renderGeometry:null,loadingPromise:null,loadingAbortController:null,image:null,pixelData:null,renderExtent:m.create(d)});
var f=this._images[c];f.loadingAbortController&&(f.loadingAbortController.abort(),f.loadingAbortController=null);var q=new E(d[0],d[1],d[2],d[3],this._spatialReference);if(0===q.width||0===q.height)this._clearImage(c);else{var B=new AbortController;f.loadingAbortController=B;k.onAbort(b,()=>B.abort());var t=B.signal,w=this._waitFetchReady(t).then(()=>{const p={requestAsImageElement:!0,pixelRatio:this._overlays[c].pixelRatio,...this.getFetchOptions(),signal:t},{height:Q,width:R}=h.imageSize;return this.layer.fetchImage(q,
R,Q,p)}).then(p=>{if(k.isAborted(t))throw y.warnOnce("A call to fetchImage resolved even though the request was aborted. fetchImage should not resolve if options.signal.aborted is true."),k.createAbortError();return this.processResult(f,p)}).then(()=>m.copy(f.renderExtent,d));f.loadingPromise=w;k.always(w,()=>{w===f.loadingPromise&&(f.loadingPromise=null,f.loadingAbortController=null)});this.notifyChange("updating");yield w.then(l._asyncToGenerator(function*(){if(t.aborted)throw k.createAbortError();
yield e._createStageObjects(c,f.image,t);e.notifyChange("updating")})).catch(p=>{p&&!k.isAbortError(p)&&y.error(p);this.notifyChange("updating");throw p;})}}});return function(c,b){return a.apply(this,arguments)}}();g._clearImage=function(a){if(a=this._images[a]){u.isSome(a.renderGeometry)&&(this.view.basemapTerrain.overlayManager.renderer.removeGeometries([a.renderGeometry],this,2),a.renderGeometry=null);const c=this.view._stage;c.remove(a.texture);a.texture=null;c.remove(a.material);a.material=
null;a.loadingAbortController&&(a.loadingAbortController.abort(),a.loadingAbortController=null);a.loadingPromise=null;a.image=null;a.pixelData=null}};g._createStageObjects=function(){var a=l._asyncToGenerator(function*(c,b,e){const h=this.view._stage,d=this._images[c],f=this.view.basemapTerrain.overlayManager.renderer,q=()=>{h.remove(d.texture);d.texture=null;u.isSome(d.renderGeometry)&&(f.removeGeometries([d.renderGeometry],this,2),d.renderGeometry=null)};if(b){b=new L.Texture(b,{width:b.width,height:b.height,
preMultiplyAlpha:!0,wrap:{s:33071,t:33071}});yield C.result(this._images[0===c?1:0].loadingPromise);k.throwIfAborted(e);if(0===c)e=x.createGeometryForExtent(d.renderExtent);else{e=this._images[0].renderExtent;if(!e){q();return}e=x.createOuterImageGeometry(e,d.renderExtent)}q();h.add(b);h.loadSynchronous(b);d.texture=b;u.isNone(d.material)?(d.material=new M.ImageMaterial({transparent:!0,textureId:b.id}),h.add(d.material)):d.material.setParameters({textureId:b.id});d.renderGeometry=new K.RenderGeometry(e,
d.material);d.renderGeometry.origin=this._overlays[c].renderLocalOrigin;f.addGeometries([d.renderGeometry],this,2)}else q(),h.remove(d.material),d.material=null});return function(c,b,e){return a.apply(this,arguments)}}();g._isScaleRangeLayer=function(){return"minScale"in this.layer&&"maxScale"in this.layer};g._isScaleRangeActive=function(){return this._isScaleRangeLayer()?0<this.layer.minScale||0<this.layer.maxScale:!1};g._clippedExtent=function(a,c){if("local"!==this.view.viewingMode)return m.copy(c,
a);const b=this.view.basemapTerrain;return b.ready?m.intersection(a,b.extent,c):m.copy(c,a)};g._suspendedChangeHandler=function(){this.suspended?this.clear():this.refreshDebounced()};g._waitFetchReady=function(){var a=l._asyncToGenerator(function*(c){yield F.whenOnce(this.view,"stationary",c);k.throwIfAborted(c)});return function(c){return a.apply(this,arguments)}}();return A}(O.RefreshableLayerView(H.LayerView3D(N)));r.__decorate([v.property()],n.prototype,"layer",void 0);r.__decorate([v.property()],
n.prototype,"suspended",void 0);r.__decorate([v.property({readOnly:!0})],n.prototype,"fullExtentInLocalViewSpatialReference",void 0);r.__decorate([v.property()],n.prototype,"updating",void 0);n=r.__decorate([G.subclass("esri.views.3d.layers.DynamicLayerView3D")],n);const P=m.create();return n});