// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Error ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../2d/engine/vectorTiles/SchemaHelper ../../2d/engine/vectorTiles/TileHandler3D ../../2d/engine/vectorTiles/VTLPainter3D ../../2d/engine/vectorTiles/style/StyleRepository ./LayerView3D ./TiledLayerView3D ../terrain/terrainUtils ../../layers/LayerView".split(" "),
function(q,e,D,m,E,F,g,d,P,Q,G,H,t,u,v,I,J,K,L){d=function(w){function n(){var a=w.apply(this,arguments)||this;a.type="vector-tile-3d";return a}q._inheritsLoose(n,w);var r=n.prototype;r.initialize=function(){if(m.isNone(this.layer.fullExtent))this.addResolvingPromise(Promise.reject(new D("vectortilelayerview:full-extent-undefined","This layer view's layer does not define a fullExtent.")));else{var a=this._getTileInfoSupportError(K.test.force512VTL?this.layer.tileInfo:this.layer.compatibleTileInfo256,
this.layer.fullExtent);if(a)return this.addResolvingPromise(Promise.reject(a));var {basemapTerrain:h,spatialReference:p,pixelRatio:k}=this.view;a=F.whenTrueOnce(this.view,"basemapTerrain.tilingSchemeLocked").then(()=>{var b=h.tilingScheme,c=b.pixelSize;this.schemaHelper=new H(c,p.isGeographic);c=256===c?this.layer.compatibleTileInfo256:this.view.spatialReference.isGeographic?this.layer.compatibleTileInfo512:this.layer.tileInfo;if(b=this._getTileInfoCompatibilityError(c,b))throw b;this._set("tileInfo",
c)});this._tileHandlerController=new AbortController;var l=this.view.resourceController;this._memCache=l.memoryController.newCache(this.layer.uid,b=>{b.release()});var {style:f}=this.layer.currentStyleInfo;f=new v(f);var x=h.mapTileRequester;this._tileHandler=new t(this.layer,f,k,this._memCache,x);var y=this._tileHandlerController.signal,z=b=>l.schedule(b);f=this._tileHandler.start({signal:y,schedule:z});var A=this._tileHandler.spriteMosaic;A.then(b=>{!E.isAborted(y)&&this._tileHandler&&(this.painter=
new u(b,this._tileHandler.glyphMosaic))});f.then(()=>this._tileHandlerController=null);var C=()=>{this._tileHandlerController&&this._tileHandlerController.abort();this._tileHandlerController=new AbortController;this._memCache.clear();var {style:b}=this.layer.currentStyleInfo;b=new v(b);const c=new t(this.layer,b,k,this._memCache,x);b=c.start({signal:this._tileHandlerController.signal,schedule:z});const M=c.spriteMosaic;b.then(()=>this._tileHandlerController=null);this.updatingHandles.addPromise(Promise.all([b,
M]).then(([,N])=>{const O=this._tileHandler,B=this.painter;this.painter=new u(N,c.glyphMosaic);this._tileHandler=c;this.emit("data-changed");O.destroy();B&&B.dispose()}))};this.updatingHandles.add(this,"layer.currentStyleInfo",C);this.updatingHandles.add(this,"view.pixelRatio",C);a=Promise.all([a,f,A]);this.addResolvingPromise(a)}};r.destroy=function(){this.painter=m.disposeMaybe(this.painter);this._tileHandlerController&&(this._tileHandlerController.abort(),this._tileHandlerController=null);m.destroyMaybe(this._tileHandler);
this._memCache=m.destroyMaybe(this._memCache);this._tileHandler=null};r.fetchTile=function(){var a=q._asyncToGenerator(function*(h,p,k,l){return this._tileHandler.getVectorTile(h,p,k,l)});return function(h,p,k,l){return a.apply(this,arguments)}}();q._createClass(n,[{key:"dataLevelRange",get:function(){var a=this.tileInfo.lods;a=this.levelRangeFromScaleRange(a[0].scale,a[a.length-1].scale);1===a.minLevel&&256===this.tileInfo.size[0]&&(a.minLevel=0);return a}}]);return n}(J.TiledLayerView3D(I.LayerView3D(L)));
e.__decorate([g.property({aliasOf:"layer.fullExtent"})],d.prototype,"fullExtent",void 0);e.__decorate([g.property()],d.prototype,"layer",void 0);e.__decorate([g.property()],d.prototype,"tileInfo",void 0);e.__decorate([g.property()],d.prototype,"dataLevelRange",null);e.__decorate([g.property()],d.prototype,"updatingProgressValue",void 0);return d=e.__decorate([G.subclass("esri.views.3d.layers.VectorTileLayerView3D")],d)});