// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../core/promiseUtils ../../../../geometry/support/aaBoundingRect ./decluttering/SymbolFader ../webgl/enums ../webgl/RenderableTile ../webgl/TileContainer ../../tiling/TileCoverage ../../tiling/TileKey".split(" "),function(B,C,n,G,D,H,p,I,y,J,K){function E(f,q){if(f){const d=f.getLayoutProperty("visibility");if(!d||1!==d.getValue()&&(void 0===f.minzoom||f.minzoom<q+1E-6)&&(void 0===f.maxzoom||f.maxzoom>=q-
1E-6))return!0}return!1}y=function(f){function q(a){a=f.call(this,a)||this;a._backgroundTiles=[];a._pointToCallbacks=new Map;return a}C._inheritsLoose(q,f);var d=q.prototype;d.destroy=function(){this.removeAllChildren();this._spriteMosaic&&(this._spriteMosaic.dispose(),this._spriteMosaic=null);this._glyphMosaic&&(this._glyphMosaic.dispose(),this._glyphMosaic=null);n.isSome(this._symbolFader)&&(this._symbolFader.clear(),this._symbolFader=null);this._styleRepository=null;this._backgroundTiles=[];this._pointToCallbacks.clear()};
d.setStyleResources=function(a,b,c){this._spriteMosaic=a;this._glyphMosaic=b;this._styleRepository=c;n.isNone(this._symbolFader)&&(a=new H.SymbolFader(this._styleRepository,this.children),a.on("fade-start",()=>{this.emit("fade-start");this.requestRender()}),a.on("fade-complete",()=>{this.emit("fade-complete");this.requestRender()}),this._symbolFader=a);n.unwrap(this._symbolFader).styleRepository=c};d.deleteStyleLayers=function(a){n.isSome(this._symbolFader)&&this._symbolFader.deleteStyleLayers(a)};
d.hitTest=function(){var a=C._asyncToGenerator(function*(b){const c=G.createResolver();this._pointToCallbacks.set(b,c);this.requestRender();return c.promise});return function(b){return a.apply(this,arguments)}}();d.enterTileInvalidation=function(){for(const a of this.children)a.invalidating=!0};d.createRenderParams=function(a){return{...f.prototype.createRenderParams.call(this,a),renderPass:null,styleLayer:null,styleLayerUID:-1,glyphMosaic:this._glyphMosaic,spriteMosaic:this._spriteMosaic,hasClipping:!!this._clippingInfos}};
d.doRender=function(a){!this.visible||a.drawPhase!==p.WGLDrawPhase.MAP&&a.drawPhase!==p.WGLDrawPhase.DEBUG||void 0===this._spriteMosaic||f.prototype.doRender.call(this,a)};d.addChild=function(a){f.prototype.addChild.call(this,a);n.isSome(this._symbolFader)?this._symbolFader.addTile(a):a.decluttered=!0;this.requestRender();return a};d.removeChild=function(a){n.isSome(this._symbolFader)&&this._symbolFader.removeTile(a);this.requestRender();return f.prototype.removeChild.call(this,a)};d.renderChildren=
function(a){const {drawPhase:b}=a;if(b===p.WGLDrawPhase.DEBUG)f.prototype.renderChildren.call(this,a);else if(this._doRender(a),0<this._pointToCallbacks.size){a.drawPhase=p.WGLDrawPhase.HITTEST;const c=a.painter.effects.hittest;c.bind(a);this._doRender(a);c.draw(a,this._pointToCallbacks);c.unbind(a);a.drawPhase=b}};d.removeAllChildren=function(){for(let a=0;a<this.children.length;a++){const b=this.children[a];n.isSome(this._symbolFader)&&this._symbolFader.removeTile(b);b.dispose()}f.prototype.removeAllChildren.call(this)};
d.getStencilTarget=function(){return this.children.filter(a=>a.neededForCoverage&&a.hasData())};d.restartDeclutter=function(){n.isSome(this._symbolFader)&&this._symbolFader.restartDeclutter()};d._doRender=function(a){const {context:b}=a;var c=this._styleRepository;if(c){var l=c.layers,e=!0;a.drawPhase===p.WGLDrawPhase.HITTEST&&(e=!1);0<c.backgroundBucketIds.length&&(a.renderPass="background",this._renderBackgroundLayers(a,c.backgroundBucketIds));f.prototype.renderChildren.call(this,a);a.drawPhase===
p.WGLDrawPhase.MAP&&this._fade(a.displayLevel,a.state);if((c=this.children.filter(h=>h.visible&&h.hasData()))&&0!==c.length){for(var g of c)g.triangleCount=0;b.setStencilWriteMask(0);b.setColorMask(!0,!0,!0,!0);b.setStencilOp(7680,7680,7681);b.setStencilTestEnabled(!0);b.setBlendingEnabled(!1);b.setDepthTestEnabled(!0);b.setDepthWriteEnabled(!0);b.setDepthFunction(515);b.setClearDepth(1);b.clear(b.gl.DEPTH_BUFFER_BIT);a.renderPass="opaque";for(g=l.length-1;0<=g;g--)this._renderStyleLayer(l[g],a,c);
b.setDepthWriteEnabled(!1);b.setBlendingEnabled(e);b.setBlendFunctionSeparate(1,771,1,771);a.renderPass="translucent";for(e=0;e<l.length;e++)this._renderStyleLayer(l[e],a,c);b.setDepthTestEnabled(!1);a.renderPass="symbol";for(e=0;e<l.length;e++)this._renderStyleLayer(l[e],a,c)}b.bindVAO();b.setStencilTestEnabled(!0);b.setBlendingEnabled(!0)}};d._fade=function(a,b){n.isSome(this._symbolFader)&&(this._symbolFader.update(a,b)||this.requestRender())};d._renderStyleLayer=function(a,b,c){const {painter:l,
renderPass:e}=b;if(void 0!==a){var g=a.getLayoutProperty("visibility");if(!g||1!==g.getValue()){switch(a.type){case 0:return;case 1:if("opaque"!==e&&"translucent"!==b.renderPass)return;var h="vtlFill";break;case 2:if("translucent"!==e)return;h="vtlLine";break;case 4:if("symbol"!==e)return;h="vtlCircle";break;case 3:if("symbol"!==e)return;h="vtlSymbol"}c=3===a.type?c.filter(m=>m.decluttered):c.filter(m=>m.neededForCoverage);if("vtlSymbol"!==h&&(g=b.displayLevel,0===c.length||void 0!==a.minzoom&&a.minzoom>=
g+1E-6||void 0!==a.maxzoom&&a.maxzoom<g-1E-6))return;g=a.uid;b.styleLayerUID=g;b.styleLayer=a;for(const m of c)if(m.layerData.has(g)){l.renderObjects(b,c,h);break}}}};d._renderBackgroundLayers=function(a,b){const {context:c,displayLevel:l,painter:e,state:g}=a,h=this._styleRepository;var m=!1;for(var u of b)if(0===h.getLayerById(u).type&&E(h.getLayerById(u),l)){m=!0;break}if(m){m=this._tileInfoView.getTileCoverage(a.state,0,"smallest");var {spans:L,lodInfo:v}=m,{level:w}=v,z=D.create();u=[];if(this._renderPasses){var r=
this._renderPasses[0];n.isSome(this._clippingInfos)&&(r.brushes[0].prepareState(a,this._clippingInfos[0]),r.brushes[0].drawMany(a,this._clippingInfos))}r=this._backgroundTiles;var A=0;for(const {row:x,colFrom:M,colTo:N}of L)for(let t=M;t<=N;t++){if(A<r.length){var k=r[A];k.key.set(w,x,v.normalizeCol(t),v.getWorldForColumn(t));this._tileInfoView.getTileBounds(z,k.key,!1);k.x=z[0];k.y=z[3]}else{k=new K(w,x,v.normalizeCol(t),v.getWorldForColumn(t));const F=this._tileInfoView.getTileBounds(D.create(),
k);k=new I.RenderableTile(k,F[0],F[3],512,512,4096,4096);r.push(k)}k.setTransform(g,this._tileInfoView.getTileResolution(k.key));u.push(k);A++}c.setStencilWriteMask(0);c.setColorMask(!0,!0,!0,!0);c.setStencilOp(7680,7680,7681);c.setStencilFunction(514,0,255);w=!0;a.drawPhase===p.WGLDrawPhase.HITTEST&&(w=!1);c.setStencilTestEnabled(w);for(const x of b)b=h.getLayerById(x),0===b.type&&E(b,l)&&(a.styleLayerUID=b.uid,a.styleLayer=b,e.renderObjects(a,u,"vtlBackground"));J.pool.release(m)}};return q}(y.default);
B.VectorTileContainer=y;Object.defineProperty(B,"__esModule",{value:!0})});