// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Accessor ../../core/has ../../core/lang ../../core/Logger ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ./parser ./utils".split(" "),function(n,x,k,g,A,q,B,l,E,C,D,y){function u(c){c=D.parse(c)||[];var e=(e=c[0])?"type"in e:!1;return e?[{scale:-1,effects:c}]:c}function v(c,e,h){var a,b,d,f;return null!=(a=c[0])&&a.effects&&null!=
(b=e[0])&&b.effects?(-1===(null==(d=c[0])?void 0:d.scale)||-1===(null==(f=e[0])?void 0:f.scale))&&(1<c.length||1<e.length)&&0>=h?!1:y.canInterpolateEffects(c[0].effects,e[0].effects):!0}function z(c,e,h){var a,b;const d=c.length>e.length?c:e;c=c.length>e.length?e:c;const f=c[c.length-1];e=null!=(a=null==f?void 0:f.scale)?a:h;a=null!=(b=null==f?void 0:f.effects)?b:[];for(b=c.length;b<d.length;b++)c.push({scale:e,effects:[...a]});for(b=0;b<d.length;b++)c[b].scale=-1===c[b].scale?h:c[b].scale,d[b].scale=
-1===d[b].scale?h:d[b].scale,y.normalizeEffects(c[b].effects,d[b].effects)}g=function(c){function e(a){a=c.call(this,a)||this;a._from=null;a._to=null;a._final=null;a._current=[];a._time=0;a.duration=A("mapview-transitions-duration");a.effects=[];return a}x._inheritsLoose(e,c);var h=e.prototype;h.canTransitionTo=function(a){try{return 0<this.scale&&v(this._current,u(a),this.scale)}catch{return!1}};h.transitionStep=function(a,b){this._applyTimeTransition(a);this._updateForScale(b)};h.end=function(){this._applyTimeTransition(this.duration)};
h._transitionTo=function(a){0<this.scale&&v(this._current,a,this.scale)?(this._final=a,this._to=q.clone(a),z(this._current,this._to,this.scale),this._from=q.clone(this._current),this._time=0):(this._from=this._to=this._final=null,this._current=a);this._set("effects",this._current[0]?q.clone(this._current[0].effects):[])};h._applyTimeTransition=function(a){if(this._to&&this._from&&this._current&&this._final){this._time+=a;a=Math.min(1,this._time/this.duration);for(let d=0;d<this._current.length;d++){const f=
this._current[d],p=this._from[d],m=this._to[d];var b=p.scale;f.scale=b+(m.scale-b)*a;for(b=0;b<f.effects.length;b++)f.effects[b].interpolate(p.effects[b],m.effects[b],a)}1===a&&(this._current=this._final,this._set("effects",this._current[0]?q.clone(this._current[0].effects):[]),this._from=this._to=this._final=null)}};h._updateForScale=function(a){this._set("scale",a);if(0!==this._current.length){var b=this._current,d=this._current.length-1,f,p=1;if(1===b.length||a>=b[0].scale)var m=f=b[0].effects;
else if(a<=b[d].scale)m=f=b[d].effects;else for(let r=0;r<d;r++){const t=b[r],w=b[r+1];if(t.scale>=a&&w.scale<=a){p=(a-t.scale)/(w.scale-t.scale);f=t.effects;m=w.effects;break}}for(a=0;a<this.effects.length;a++)this.effects[a].interpolate(f[a],m[a],p)}};x._createClass(e,[{key:"effect",set:function(a){const b=this._get("effect");a=a||"";if(b!==a){this._set("effect",a);try{this._transitionTo(u(a))}catch(d){this._transitionTo([]),B.getLogger(this.declaredClass).warn("Invalid Effect",{effect:a,error:d})}}}},
{key:"hasEffects",get:function(){return this.transitioning||!!this.effects.length}},{key:"scale",set:function(a){this._updateForScale(a)}},{key:"transitioning",get:function(){return null!==this._to}}]);return e}(g);k.__decorate([l.property()],g.prototype,"_to",void 0);k.__decorate([l.property()],g.prototype,"duration",void 0);k.__decorate([l.property({value:""})],g.prototype,"effect",null);k.__decorate([l.property({readOnly:!0})],g.prototype,"effects",void 0);k.__decorate([l.property({readOnly:!0})],
g.prototype,"hasEffects",null);k.__decorate([l.property({value:0})],g.prototype,"scale",null);k.__decorate([l.property({readOnly:!0})],g.prototype,"transitioning",null);g=k.__decorate([C.subclass("esri.layers.effects.EffectView")],g);n.canInterpolateEffectStops=v;n.convertEffectToStops=u;n.default=g;n.normalizeEffectStops=z;Object.defineProperty(n,"__esModule",{value:!0})});