// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../webgl/BufferObject ../../../webgl/FramebufferObject ../../../../core/has ../../../webgl/checkWebGLError ../../../webgl/enums ../../../../chunks/builtins ../../../webgl/Renderbuffer ../../../webgl/Texture ../../../webgl/VertexArrayObject ../brushes ../vectorTiles/shaders/VTLMaterialManager ./BitBlitRenderer ./enums ./MaterialManager ./TextureManager ./effects/AnimationEffect ./effects/BlendEffect ./effects/FeatureEffect ./effects/HighlightEffect ./effects/HittestEffect ./effects/post-processing/EffectManager ./painter/RenderPass".split(" "),
function(v,m,I,r,J,K,L,M,w,N,O,l,x,y,g,z,A,B,C,t,D,E,F,G){function u(n,e,a,c){return n!==g.WGLDrawPhase.HIGHLIGHT&&(1!==c||m.isSome(e)&&"normal"!==e||m.isSome(a)&&0<a.length)}const H={[g.WGLGeometryType.FILL]:l.brushes.fill,[g.WGLGeometryType.LINE]:l.brushes.line,[g.WGLGeometryType.MARKER]:l.brushes.marker,[g.WGLGeometryType.TEXT]:l.brushes.text};return function(){function n(a,c,b){this.context=a;this._blitRenderer=new y.BitBlitRenderer;this._brushCache=new Map;this._vtlMaterialManager=new x;this._blendEffect=
new C.BlendEffect;this.effects={highlight:new D,hittest:new E.HittestEffect,integrate:new B.AnimationEffect,insideEffect:new t.FeatureEffect("inside"),outsideEffect:new t.FeatureEffect("outside")};this.materialManager=new z(a);this.textureManager=new A(c,b);this._effectsManager=new F.EffectManager(c)}var e=n.prototype;e.getRenderTarget=function(){return this._renderTarget};e.setRenderTarget=function(a){this._renderTarget=a};e.getFbos=function(a,c){if(a!==this._lastWidth||c!==this._lastHeight){this._lastWidth=
a;this._lastHeight=c;if(this._fbos){for(var b in this._fbos)this._fbos[b].resize(a,c);return this._fbos}b={target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,wrapMode:33071,width:a,height:c};const d={colorTarget:0,depthStencilTarget:3};this._stencilBuf=a=new w(this.context,{width:a,height:c,internalFormat:34041});this._fbos={output:new r(this.context,d,b,a),blend:new r(this.context,d,b,a),effect0:new r(this.context,d,b,a)}}return this._fbos};e.getSharedStencilBuffer=function(){return this._stencilBuf};
e.beforeRenderLayers=function(a,c=null){const {width:b,height:d}=a.getViewport();this._prevFBO=a.getBoundFramebufferObject();const f=this.getFbos(b,d);a.bindFramebuffer(f.output);a.setColorMask(!0,!0,!0,!0);a.setDepthWriteEnabled(!0);if(m.isSome(c)){const {r:p,g:h,b:k,a:q}=c.color;a.setClearColor(q*p/255,q*h/255,q*k/255,q)}else a.setClearColor(0,0,0,0);a.setClearDepth(1);a.clear(a.gl.COLOR_BUFFER_BIT|a.gl.DEPTH_BUFFER_BIT);a.setDepthWriteEnabled(!1)};e.beforeRenderLayer=function(a,c,b){const {context:d,
blendMode:f,effects:p,requireFBO:h,drawPhase:k}=a;h||u(k,f,p,b)?(d.bindFramebuffer(this._fbos.blend),d.setColorMask(!0,!0,!0,!0),d.setClearColor(0,0,0,0),d.setDepthWriteEnabled(!0),d.setClearDepth(1),d.clear(d.gl.COLOR_BUFFER_BIT|d.gl.DEPTH_BUFFER_BIT),d.setDepthWriteEnabled(!1)):(a=this._getOutputFBO(),d.bindFramebuffer(a));d.setDepthWriteEnabled(!1);d.setDepthTestEnabled(!1);d.setStencilTestEnabled(!0);d.setClearStencil(c);d.setStencilWriteMask(255);d.clear(d.gl.STENCIL_BUFFER_BIT)};e.compositeLayer=
function(a,c){const {context:b,blendMode:d,effects:f,requireFBO:p,drawPhase:h}=a;if(p||u(h,d,f,c)){m.isSome(f)&&0<f.length&&h===g.WGLDrawPhase.MAP&&this._applyEffects(a,f);var k=this._getOutputFBO();b.bindFramebuffer(k);b.setStencilTestEnabled(!1);b.setStencilWriteMask(0);b.setBlendingEnabled(!0);b.setBlendFunctionSeparate(1,771,1,771);b.setColorMask(!0,!0,!0,!0);k=m.isNone(d)||h===g.WGLDrawPhase.HIGHLIGHT?"normal":d;this._blendEffect.draw(a,this._fbos.blend.colorTexture,9728,k,c)}};e.renderLayers=
function(a){a.bindFramebuffer(this._prevFBO);if(this._fbos){var c=this._getOutputFBO();a.setStencilTestEnabled(!1);a.setStencilWriteMask(0);this.blitTexture(a,c.colorTexture,9728)}};e.dispose=function(){this.materialManager.dispose();this.textureManager.dispose();this._blitRenderer&&(this._blitRenderer.dispose(),this._blitRenderer=null);this._brushCache&&(this._brushCache.forEach(a=>a.dispose()),this._brushCache.clear(),this._brushCache=null);if(this._fbos)for(const a in this._fbos)this._fbos[a]&&
this._fbos[a].dispose();if(this.effects)for(const a in this.effects)this.effects[a]&&this.effects[a].dispose();this._effectsManager.dispose();this._vtlMaterialManager&&(this._vtlMaterialManager.dispose(),this._vtlMaterialManager=null);this._prevFBO=null};e.getGeometryBrush=function(a){a=H[a];let c=this._brushCache.get(a);void 0===c&&(c=new a,this._brushCache.set(a,c));return this._brushCache.get(a)};e.renderObject=function(a,c,b,d){b=l.brushes[b];if(!b)return null;let f=this._brushCache.get(b);void 0===
f&&(f=new b,this._brushCache.set(b,f));f.prepareState(a,c,d);f.draw(a,c,d)};e.renderObjects=function(a,c,b,d){b=l.brushes[b];if(!b)return null;let f=this._brushCache.get(b);void 0===f&&(f=new b,this._brushCache.set(b,f));f.drawMany(a,c,d)};e.registerRenderPass=function(a){const c=a.brushes.map(b=>{this._brushCache.has(b)||this._brushCache.set(b,new b);return this._brushCache.get(b)});return new G(c,a)};e.setHighlightOptions=function(a){this.effects.highlight.setHighlightOptions(a)};e.blitTexture=
function(a,c,b,d=1){a.setBlendingEnabled(!0);a.setBlendFunctionSeparate(1,771,1,771);a.setColorMask(!0,!0,!0,!0);this._blitRenderer.render(a,c,b,d)};e.getPostProcessingEffects=function(a){return this._effectsManager.getPostProcessingEffects(a)};e._getOutputFBO=function(){return null!=this._renderTarget?this._renderTarget:this._fbos.output};e._applyEffects=function(a,c){const {context:b}=a;c=this._effectsManager.getPostProcessingEffects(c);for(const {postProcessingEffect:d,effect:f}of c)b.bindFramebuffer(this._fbos.blend),
d.draw(a,this._fbos.blend,f)};v._createClass(n,[{key:"vectorTilesMaterialManager",get:function(){return this._vtlMaterialManager}}]);return n}()});