// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../core/maybe ./checkWebGLError ./enums ./InstanceCounter ./renderState ./Texture ./WebGLDriverTest ./capabilities/isWebGL2Context ./capabilities/load".split(" "),function(q,u,h,k,n,v,w,x,y,r,z){function m(g,e,a,c){e?c!==e&&g.bindBuffer(a,e.glName):g.bindBuffer(a,null);return e}function t(g,e){switch(g){case 0:return 2*e;case 4:return e/3;case 5:return e-2;case 6:return e-2;default:return 0}}let A=function(){function g(a,c){this.gl=a;this.instanceCounter=
new v.InstanceCounter;this._blendEnabled=!1;this._blendColorState={r:0,g:0,b:0,a:0};this._blendFunctionState={srcRGB:1,dstRGB:0,srcAlpha:1,dstAlpha:0};this._blendEquationState={mode:32774,modeAlpha:32774};this._colorMaskState={r:!0,g:!0,b:!0,a:!0};this._polygonCullingEnabled=!1;this._cullFace=1029;this._frontFace=2305;this._scissorTestEnabled=!1;this._scissorRect={x:0,y:0,width:0,height:0};this._depthTestEnabled=!1;this._depthFunction=513;this._clearDepth=1;this._depthWriteEnabled=!0;this._depthRange=
{zNear:0,zFar:1};this._viewport=null;this._polygonOffsetFillEnabled=this._stencilTestEnabled=!1;this._polygonOffset=[0,0];this._stencilFunction={face:1032,func:519,ref:0,mask:1};this._clearStencil=0;this._stencilWriteMask=1;this._stencilOperation={face:1032,fail:7680,zFail:7680,zPass:7680};this._clearColor={r:0,g:0,b:0,a:0};this._activeRenderbuffer=this._activeFramebuffer=this._activeIndexBuffer=this._activeVertexBuffer=this._activeShaderProgram=null;this._activeTextureUnit=0;this._textureUnitMap=
[];this._numOfTriangles=this._numOfDrawCalls=0;this.webglVersion=r(a)?"webgl2":"webgl";"webgl"===this.webglVersion&&this.gl.getExtension("OES_element_index_uint");this._capabilities=z.loadCapabilities(a,c);this._parameters=this._loadParameters(c);a=this.gl.getParameter(this.gl.VIEWPORT);this._viewport={x:a[0],y:a[1],width:a[2],height:a[3]};this._stateTracker=new w.StateTracker({setBlending:b=>{b?(this.setBlendingEnabled(!0),this.setBlendEquationSeparate(b.opRgb,b.opAlpha),this.setBlendFunctionSeparate(b.srcRgb,
b.dstRgb,b.srcAlpha,b.dstAlpha),b=b.color,this.setBlendColor(b.r,b.g,b.b,b.a)):this.setBlendingEnabled(!1)},setCulling:b=>{b?(this.setFaceCullingEnabled(!0),this.setCullFace(b.face),this.setFrontFace(b.mode)):this.setFaceCullingEnabled(!1)},setPolygonOffset:b=>{b?(this.setPolygonOffsetFillEnabled(!0),this.setPolygonOffset(b.factor,b.units)):this.setPolygonOffsetFillEnabled(!1)},setDepthTest:b=>{b?(this.setDepthTestEnabled(!0),this.setDepthFunction(b.func)):this.setDepthTestEnabled(!1)},setStencilTest:b=>
{if(b){this.setStencilTestEnabled(!0);const f=b.function;this.setStencilFunction(f.func,f.ref,f.mask);b=b.operation;this.setStencilOp(b.fail,b.zFail,b.zPass)}else this.setStencilTestEnabled(!1)},setDepthWrite:b=>{b?(this.setDepthWriteEnabled(!0),this.setDepthRange(b.zNear,b.zFar)):this.setDepthWriteEnabled(!1)},setColorWrite:b=>{b?this.setColorMask(b.r,b.g,b.b,b.a):this.setColorMask(!1,!1,!1,!1)},setStencilWrite:b=>{b?this.setStencilWriteMask(b.mask):this.setStencilWriteMask(0)}});this.enforceState();
this.driverTest=new y.WebGLDriverTest(this)}var e=g.prototype;e.dispose=function(){this.bindVAO(null);this.unbindBuffer(34962);this.unbindBuffer(34963);this._textureUnitMap.length=0;k.webglDebugEnabled()&&this.instanceCounter.printResourceCount()};e.setPipelineState=function(a){this._stateTracker.setPipeline(a)};e.setBlendingEnabled=function(a){this._blendEnabled!==a&&(!0===a?this.gl.enable(this.gl.BLEND):this.gl.disable(this.gl.BLEND),this._blendEnabled=a,this._stateTracker.invalidateBlending())};
e.externalProgramUpdate=function(){var a;null==(a=this._activeShaderProgram)?void 0:a.stop();this._activeShaderProgram=null};e.externalTextureUnitUpdate=function(a,c){for(let b=0;b<a.length;++b)this._textureUnitMap[a[b]]=null;0<=c&&(this._activeTextureUnit=c)};e.externalVertexArrayObjectUpdate=function(){const a=this.capabilities.vao;a&&(a.bindVertexArray(null),this._activeVertexArrayObject=null);this._activeIndexBuffer=this._activeVertexBuffer=null};e.externalVertexBufferUpdate=function(){this._activeVertexBuffer=
null};e.externalIndexBufferUpdate=function(){this._activeIndexBuffer=null};e.setBlendColor=function(a,c,b,f){if(a!==this._blendColorState.r||c!==this._blendColorState.g||b!==this._blendColorState.b||f!==this._blendColorState.a)this.gl.blendColor(a,c,b,f),this._blendColorState.r=a,this._blendColorState.g=c,this._blendColorState.b=b,this._blendColorState.a=f,this._stateTracker.invalidateBlending()};e.setBlendFunction=function(a,c){if(a!==this._blendFunctionState.srcRGB||c!==this._blendFunctionState.dstRGB)this.gl.blendFunc(a,
c),this._blendFunctionState.srcRGB=a,this._blendFunctionState.srcAlpha=a,this._blendFunctionState.dstRGB=c,this._blendFunctionState.dstAlpha=c,this._stateTracker.invalidateBlending()};e.setBlendFunctionSeparate=function(a,c,b,f){if(this._blendFunctionState.srcRGB!==a||this._blendFunctionState.srcAlpha!==b||this._blendFunctionState.dstRGB!==c||this._blendFunctionState.dstAlpha!==f)this.gl.blendFuncSeparate(a,c,b,f),this._blendFunctionState.srcRGB=a,this._blendFunctionState.srcAlpha=b,this._blendFunctionState.dstRGB=
c,this._blendFunctionState.dstAlpha=f,this._stateTracker.invalidateBlending()};e.setBlendEquation=function(a){this._blendEquationState.mode!==a&&(this.gl.blendEquation(a),this._blendEquationState.mode=a,this._blendEquationState.modeAlpha=a,this._stateTracker.invalidateBlending())};e.setBlendEquationSeparate=function(a,c){if(this._blendEquationState.mode!==a||this._blendEquationState.modeAlpha!==c)this.gl.blendEquationSeparate(a,c),this._blendEquationState.mode=a,this._blendEquationState.modeAlpha=
c,this._stateTracker.invalidateBlending()};e.setColorMask=function(a,c,b,f){if(this._colorMaskState.r!==a||this._colorMaskState.g!==c||this._colorMaskState.b!==b||this._colorMaskState.a!==f)this.gl.colorMask(a,c,b,f),this._colorMaskState.r=a,this._colorMaskState.g=c,this._colorMaskState.b=b,this._colorMaskState.a=f,this._stateTracker.invalidateColorWrite()};e.setClearColor=function(a,c,b,f){if(this._clearColor.r!==a||this._clearColor.g!==c||this._clearColor.b!==b||this._clearColor.a!==f)this.gl.clearColor(a,
c,b,f),this._clearColor.r=a,this._clearColor.g=c,this._clearColor.b=b,this._clearColor.a=f};e.setFaceCullingEnabled=function(a){this._polygonCullingEnabled!==a&&(!0===a?this.gl.enable(this.gl.CULL_FACE):this.gl.disable(this.gl.CULL_FACE),this._polygonCullingEnabled=a,this._stateTracker.invalidateCulling())};e.setPolygonOffsetFillEnabled=function(a){this._polygonOffsetFillEnabled!==a&&(!0===a?this.gl.enable(this.gl.POLYGON_OFFSET_FILL):this.gl.disable(this.gl.POLYGON_OFFSET_FILL),this._polygonOffsetFillEnabled=
a,this._stateTracker.invalidatePolygonOffset())};e.setPolygonOffset=function(a,c){if(this._polygonOffset[0]!==a||this._polygonOffset[1]!==c)this._polygonOffset[0]=a,this._polygonOffset[1]=c,this.gl.polygonOffset(a,c),this._stateTracker.invalidatePolygonOffset()};e.setCullFace=function(a){this._cullFace!==a&&(this.gl.cullFace(a),this._cullFace=a,this._stateTracker.invalidateCulling())};e.setFrontFace=function(a){this._frontFace!==a&&(this.gl.frontFace(a),this._frontFace=a,this._stateTracker.invalidateCulling())};
e.setScissorTestEnabled=function(a){this._scissorTestEnabled!==a&&(!0===a?this.gl.enable(this.gl.SCISSOR_TEST):this.gl.disable(this.gl.SCISSOR_TEST),this._scissorTestEnabled=a)};e.setScissorRect=function(a,c,b,f){if(this._scissorRect.x!==a||this._scissorRect.y!==c||this._scissorRect.width!==b||this._scissorRect.height!==f)this.gl.scissor(a,c,b,f),this._scissorRect.x=a,this._scissorRect.y=c,this._scissorRect.width=b,this._scissorRect.height=f};e.setDepthTestEnabled=function(a){this._depthTestEnabled!==
a&&(!0===a?this.gl.enable(this.gl.DEPTH_TEST):this.gl.disable(this.gl.DEPTH_TEST),this._depthTestEnabled=a,this._stateTracker.invalidateDepthTest())};e.setClearDepth=function(a){this._clearDepth!==a&&(this.gl.clearDepth(a),this._clearDepth=a)};e.setDepthFunction=function(a){this._depthFunction!==a&&(this.gl.depthFunc(a),this._depthFunction=a,this._stateTracker.invalidateDepthTest())};e.setDepthWriteEnabled=function(a){this._depthWriteEnabled!==a&&(this.gl.depthMask(a),this._depthWriteEnabled=a,this._stateTracker.invalidateDepthWrite())};
e.setDepthRange=function(a,c){if(this._depthRange.zNear!==a||this._depthRange.zFar!==c)this.gl.depthRange(a,c),this._depthRange.zNear=a,this._depthRange.zFar=c,this._stateTracker.invalidateDepthWrite()};e.setStencilTestEnabled=function(a){this._stencilTestEnabled!==a&&(!0===a?this.gl.enable(this.gl.STENCIL_TEST):this.gl.disable(this.gl.STENCIL_TEST),this._stencilTestEnabled=a,this._stateTracker.invalidateStencilTest())};e.setClearStencil=function(a){a!==this._clearStencil&&(this.gl.clearStencil(a),
this._clearStencil=a)};e.setStencilFunction=function(a,c,b){if(this._stencilFunction.func!==a||this._stencilFunction.ref!==c||this._stencilFunction.mask!==b)this.gl.stencilFunc(a,c,b),this._stencilFunction.face=1032,this._stencilFunction.func=a,this._stencilFunction.ref=c,this._stencilFunction.mask=b,this._stateTracker.invalidateStencilTest()};e.setStencilFunctionSeparate=function(a,c,b,f){if(this._stencilFunction.face!==a||this._stencilFunction.func!==c||this._stencilFunction.ref!==b||this._stencilFunction.mask!==
f)this.gl.stencilFuncSeparate(a,c,b,f),this._stencilFunction.face=a,this._stencilFunction.func=c,this._stencilFunction.ref=b,this._stencilFunction.mask=f,this._stateTracker.invalidateStencilTest()};e.setStencilWriteMask=function(a){this._stencilWriteMask!==a&&(this.gl.stencilMask(a),this._stencilWriteMask=a,this._stateTracker.invalidateStencilWrite())};e.setStencilOp=function(a,c,b){if(this._stencilOperation.fail!==a||this._stencilOperation.zFail!==c||this._stencilOperation.zPass!==b)this.gl.stencilOp(a,
c,b),this._stencilOperation.face=1032,this._stencilOperation.fail=a,this._stencilOperation.zFail=c,this._stencilOperation.zPass=b,this._stateTracker.invalidateStencilTest()};e.setStencilOpSeparate=function(a,c,b,f){if(this._stencilOperation.face!==a||this._stencilOperation.fail!==c||this._stencilOperation.zFail!==b||this._stencilOperation.zPass!==f)this.gl.stencilOpSeparate(a,c,b,f),this._stencilOperation.face=a,this._stencilOperation.face=a,this._stencilOperation.fail=c,this._stencilOperation.zFail=
b,this._stencilOperation.zPass=f,this._stateTracker.invalidateStencilTest()};e.setActiveTexture=function(a,c=!1){const b=this._activeTextureUnit;0<=a&&(c||a!==this._activeTextureUnit)&&(this.gl.activeTexture(n.BASE_TEXTURE_UNIT+a),this._activeTextureUnit=a);return b};e.clear=function(a){a&&this.gl.clear(a)};e.clearSafe=function(a,c=255){a&&(a&16384&&this.setColorMask(!0,!0,!0,!0),a&256&&this.setDepthWriteEnabled(!0),a&1024&&this.setStencilWriteMask(c),this.gl.clear(a))};e.drawArrays=function(a,c,
b){k.webglDebugEnabled()&&(this._numOfDrawCalls++,this._numOfTriangles+=t(a,b));this.gl.drawArrays(a,c,b)};e.drawElements=function(a,c,b,f){k.webglDebugEnabled()&&(this._numOfDrawCalls++,this._numOfTriangles+=t(a,c));this.gl.drawElements(a,c,b,f)};e.logIno=function(){k.webglDebugEnabled()&&console.log(`DrawCalls: ${this._numOfDrawCalls}, Triangles: ${this._numOfTriangles}`)};e.setViewport=function(a,c,b,f){b=Math.max(Math.round(b),1);f=Math.max(Math.round(f),1);const d=this._viewport;if(d.x!==a||
d.y!==c||d.width!==b||d.height!==f)d.x=a,d.y=c,d.width=b,d.height=f,this.gl.viewport(a,c,b,f)};e.getViewport=function(){return{x:this._viewport.x,y:this._viewport.y,width:this._viewport.width,height:this._viewport.height}};e.useProgram=function(a){var c,b;this._activeShaderProgram!==a&&(null==(c=this._activeShaderProgram)?void 0:c.stop(),this._activeShaderProgram=a,this.gl.useProgram(null!=(b=null==a?void 0:a.glName)?b:null))};e.bindTexture=function(a,c,b=!1){(c>=this.parameters.maxTextureImageUnits||
0>c)&&console.error("Input texture unit is out of range of available units!");const f=this._textureUnitMap[c];if(h.isNone(a)||null==a.glName)return h.isSome(f)&&(this.setActiveTexture(c,b),this.gl.bindTexture(f.descriptor.target,null)),this._textureUnitMap[c]=null,f;if(!b&&f===a)return a.isDirty&&(this.setActiveTexture(c,b),a.applyChanges()),f;this.setActiveTexture(c,b);this.gl.bindTexture(a.descriptor.target,a.glName);a.applyChanges();this._textureUnitMap[c]=a;return f};e.unbindTextureAllUnits=function(a){for(let c=
0;c<this.parameters.maxTextureImageUnits;c++)this._textureUnitMap[c]===a&&(this.bindTexture(null,c),this._textureUnitMap[c]=null)};e.bindFramebuffer=function(a,c=!1,b=3553){if(h.isNone(a))this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,null),this._activeFramebuffer=null;else if(c||this._activeFramebuffer!==a)a.initializeAndBind(b),this._activeFramebuffer=a};e.bindBuffer=function(a){a&&(34962===a.bufferType?this._activeVertexBuffer=m(this.gl,a,a.bufferType,this._activeVertexBuffer):this._activeIndexBuffer=
m(this.gl,a,a.bufferType,this._activeIndexBuffer))};e.bindRenderbuffer=function(a){const c=this.gl;a||(c.bindRenderbuffer(c.RENDERBUFFER,null),this._activeRenderbuffer=null);this._activeRenderbuffer!==a&&(c.bindRenderbuffer(c.RENDERBUFFER,a.glName),this._activeRenderbuffer=a)};e.unbindBuffer=function(a){34962===a?this._activeVertexBuffer=m(this.gl,null,a,this._activeVertexBuffer):this._activeIndexBuffer=m(this.gl,null,a,this._activeIndexBuffer)};e.bindVAO=function(a=null){h.isNone(a)?this._activeVertexArrayObject&&
(this._activeVertexArrayObject.unbind(),this._activeVertexArrayObject=null):this._activeVertexArrayObject!==a&&(a.bind(),this._activeVertexArrayObject=a)};e.getBoundFramebufferObject=function(){return this._activeFramebuffer};e.getBoundVAO=function(){return this._activeVertexArrayObject};e.resetState=function(){this.useProgram(null);this.bindVAO(null);this.bindFramebuffer(null);this.unbindBuffer(34962);this.unbindBuffer(34963);for(let a=0;a<this.parameters.maxTextureImageUnits;++a)this.bindTexture(null,
a);this.setBlendingEnabled(!1);this.setBlendFunction(1,0);this.setBlendEquation(32774);this.setBlendColor(0,0,0,0);this.setFaceCullingEnabled(!1);this.setCullFace(1029);this.setFrontFace(2305);this.setPolygonOffsetFillEnabled(!1);this.setPolygonOffset(0,0);this.setScissorTestEnabled(!1);this.setScissorRect(0,0,this.gl.canvas.width,this.gl.canvas.height);this.setDepthTestEnabled(!1);this.setDepthFunction(513);this.setDepthRange(0,1);this.setStencilTestEnabled(!1);this.setStencilFunction(519,0,0);this.setStencilOp(7680,
7680,7680);this.setClearColor(0,0,0,0);this.setClearDepth(1);this.setClearStencil(0);this.setColorMask(!0,!0,!0,!0);this.setStencilWriteMask(4294967295);this.setDepthWriteEnabled(!0);this.setViewport(0,0,this.gl.canvas.width,this.gl.canvas.height)};e.enforceState=function(){var a,c,b,f;const d=this.gl;var l=this.capabilities.vao;l&&l.bindVertexArray(null);for(let p=0;p<this.parameters.maxVertexAttributes;p++)d.disableVertexAttribArray(p);this._activeVertexBuffer?d.bindBuffer(this._activeVertexBuffer.bufferType,
this._activeVertexBuffer.glName):d.bindBuffer(34962,null);this._activeIndexBuffer?d.bindBuffer(this._activeIndexBuffer.bufferType,this._activeIndexBuffer.glName):d.bindBuffer(34963,null);if(l&&this._activeVertexArrayObject){if(l=this._activeVertexArrayObject)this._activeVertexArrayObject.unbind(),this._activeVertexArrayObject=null;this.bindVAO(l)}d.bindFramebuffer(d.FRAMEBUFFER,null!=(a=null==(c=this._activeFramebuffer)?void 0:c.glName)?a:null);d.useProgram(null!=(b=null==(f=this._activeShaderProgram)?
void 0:f.glName)?b:null);d.blendColor(this._blendColorState.r,this._blendColorState.g,this._blendColorState.b,this._blendColorState.a);d.bindRenderbuffer(d.RENDERBUFFER,this._activeRenderbuffer?this._activeRenderbuffer.glName:null);!0===this._blendEnabled?d.enable(this.gl.BLEND):d.disable(this.gl.BLEND);d.blendEquationSeparate(this._blendEquationState.mode,this._blendEquationState.modeAlpha);d.blendFuncSeparate(this._blendFunctionState.srcRGB,this._blendFunctionState.dstRGB,this._blendFunctionState.srcAlpha,
this._blendFunctionState.dstAlpha);d.clearColor(this._clearColor.r,this._clearColor.g,this._clearColor.b,this._clearColor.a);d.clearDepth(this._clearDepth);d.clearStencil(this._clearStencil);d.colorMask(this._colorMaskState.r,this._colorMaskState.g,this._colorMaskState.b,this._colorMaskState.a);d.cullFace(this._cullFace);d.depthFunc(this._depthFunction);d.depthRange(this._depthRange.zNear,this._depthRange.zFar);!0===this._depthTestEnabled?d.enable(d.DEPTH_TEST):d.disable(d.DEPTH_TEST);d.depthMask(this._depthWriteEnabled);
d.frontFace(this._frontFace);d.lineWidth(1);!0===this._polygonCullingEnabled?d.enable(d.CULL_FACE):d.disable(d.CULL_FACE);d.polygonOffset(this._polygonOffset[0],this._polygonOffset[1]);!0===this._polygonOffsetFillEnabled?d.enable(d.POLYGON_OFFSET_FILL):d.disable(d.POLYGON_OFFSET_FILL);d.scissor(this._scissorRect.x,this._scissorRect.y,this._scissorRect.width,this._scissorRect.height);!0===this._scissorTestEnabled?d.enable(d.SCISSOR_TEST):d.disable(d.SCISSOR_TEST);d.stencilFunc(this._stencilFunction.func,
this._stencilFunction.ref,this._stencilFunction.mask);d.stencilOpSeparate(this._stencilOperation.face,this._stencilOperation.fail,this._stencilOperation.zFail,this._stencilOperation.zPass);!0===this._stencilTestEnabled?d.enable(d.STENCIL_TEST):d.disable(d.STENCIL_TEST);d.stencilMask(this._stencilWriteMask);for(a=0;a<this.parameters.maxTextureImageUnits;a++)d.activeTexture(n.BASE_TEXTURE_UNIT+a),d.bindTexture(3553,null),d.bindTexture(34067,null),r(d)&&d.bindTexture(32879,null),c=this._textureUnitMap[a],
h.isSome(c)&&d.bindTexture(c.descriptor.target,c.glName);d.activeTexture(n.BASE_TEXTURE_UNIT+this._activeTextureUnit);d.viewport(this._viewport.x,this._viewport.y,this._viewport.width,this._viewport.height);k.webglDebugEnabled()&&(this._numOfTriangles=this._numOfDrawCalls=0)};e._loadParameters=function(a){var c;const b=this.capabilities.textureFilterAnisotropic;a=null!=(c=a.maxAnisotropy)?c:Infinity;c={versionString:this.gl.getParameter(this.gl.VERSION),maxVertexTextureImageUnits:this.gl.getParameter(this.gl.MAX_VERTEX_TEXTURE_IMAGE_UNITS),
maxVertexAttributes:this.gl.getParameter(this.gl.MAX_VERTEX_ATTRIBS),maxMaxAnisotropy:b?Math.min(this.gl.getParameter(b.MAX_TEXTURE_MAX_ANISOTROPY),a):1,maxTextureImageUnits:this.gl.getParameter(this.gl.MAX_TEXTURE_IMAGE_UNITS),maxTextureSize:this.gl.getParameter(this.gl.MAX_TEXTURE_SIZE)};x.TEXTURE_UNIT_FOR_UPDATES=c.maxTextureImageUnits-1;return c};u._createClass(g,[{key:"contextAttributes",get:function(){return this.gl.getContextAttributes()}},{key:"parameters",get:function(){return this._parameters}},
{key:"capabilities",get:function(){return this._capabilities}}]);return g}();q.RenderingContext=A;Object.defineProperty(q,"__esModule",{value:!0})});