// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../intl ../../../core/Handles ../../../core/screenUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../symbols/support/svgUtils ../../../symbols/support/utils ../../Widget ./support/relationshipUtils ./support/univariateUtils ../support/styleUtils ../../support/Heading ../../support/decorators/accessibleHandler ../../support/decorators/messageBundle ../../../core/Logger ../../support/jsxFactory ../../support/widgetUtils ../../../intl/substitute".split(" "),
function(I,t,r,J,B,u,Q,R,S,K,L,C,M,N,q,p,z,O,D,T,e,U,P){const w=window.devicePixelRatio;r=function(E){function A(a,c){a=E.call(this,a,c)||this;a._handles=new J;a._hasIndicators=!1;a._selectedSectionName=null;a._sectionNames=[];a._sectionMap=new Map;a.activeLayerInfos=null;a.headingLevel=3;a.layout="stack";a.messages=null;a.messagesCommon=null;a.type="card";a.view=null;return a}I._inheritsLoose(A,E);var m=A.prototype;m.initialize=function(){this.own([this.watch("activeLayerInfos",a=>{this._handles.removeAll();
this._watchForSectionChanges(a)})])};m.destroy=function(){this._handles.destroy();this._handles=null};m.render=function(){this._hasIndicators="auto"===this.layout&&768>=this.view.container.clientWidth||"stack"===this.layout;var a=this.activeLayerInfos;a=a&&a.toArray().map(b=>this._renderLegendForLayer(b)).filter(b=>!!b);this._hasIndicators?this._selectedSectionName&&-1!==this._sectionNames.indexOf(this._selectedSectionName)||(this._selectedSectionName=this._sectionNames&&this._sectionNames[0]):this._selectedSectionName=
null;const c=this._sectionNames.length;var d=this._sectionNames.map((b,h)=>{h=P.substitute(this.messagesCommon.pagination.pageText,{index:h+1,total:c});return e.tsx("div",{key:b,role:"tab",id:b,"aria-label":h,"aria-controls":`${b}-panel`,"aria-selected":(this._selectedSectionName===b).toString(),tabIndex:this._selectedSectionName===b?0:-1,title:h,onclick:this._selectSection,onkeydown:this._focusSection,bind:this,class:this.classes("esri-legend--card__carousel-indicator",{["esri-legend--card__carousel-indicator--activated"]:this._selectedSectionName===
b}),"data-section-name":b})});d=this._hasIndicators&&1<c?e.tsx("div",{class:"esri-legend--card__carousel-indicator-container",key:"carousel-navigation",role:"tablist"},d):null;a=this._hasIndicators?this._sectionMap.get(this._selectedSectionName):a&&a.length?a:null;return e.tsx("div",{class:this.classes("esri-legend--card",{["esri-legend--stacked"]:this._hasIndicators})},a?a:e.tsx("div",{class:"esri-legend--card__message"},this.messages.noLegend),d)};m._selectSection=function(a){if(a=a.target.getAttribute("data-section-name"))this._selectedSectionName=
a};m._focusSection=function(a){switch(a.key){case "ArrowLeft":case "ArrowRight":this._switchSectionOnArrowPress(a);break;case "Enter":case " ":this._selectSection(a)}};m._switchSectionOnArrowPress=function(a){const c=a.key,d="ArrowLeft"===c?-1:1;a=a.target.getAttribute("data-section-name");a=this._sectionNames.indexOf(a);const b=this._sectionNames;let h=null;-1!==a&&(b[a+d]?h=document.getElementById(b[a+d]):"ArrowLeft"===c?h=document.getElementById(b[b.length-1]):"ArrowRight"===c&&(h=document.getElementById(b[0])),
h&&h.focus())};m._watchForSectionChanges=function(a){this._generateSectionNames();a&&(a.forEach(c=>{const d=`activeLayerInfo-${c.layer.uid}-version-change`;this._handles.remove(d);this._watchForSectionChanges(c.children);this._handles.add(c.watch("version",()=>this._generateSectionNames()),d)}),this._handles.remove("activeLayerInfos-collection-change"),this._handles.add(a.on("change",()=>this._watchForSectionChanges(a)),"activeLayerInfos-collection-change"))};m._generateSectionNames=function(){this._sectionNames.length=
0;this._selectedSectionName=null;this.activeLayerInfos&&this.activeLayerInfos.forEach(this._generateSectionNamesForActiveLayerInfo,this)};m._getSectionName=function(a,c,d){return`${this.id}${a.uid}-type-${c.type}-${d}`};m._generateSectionNamesForActiveLayerInfo=function(a){a.children.forEach(this._generateSectionNamesForActiveLayerInfo,this);a.legendElements&&a.legendElements.forEach((c,d)=>{this._sectionNames.push(this._getSectionName(a.layer,c,d))})};m._renderLegendForLayer=function(a){if(!a.ready)return null;
if(a.children.length){var c=a.children.map(d=>this._renderLegendForLayer(d)).toArray();return e.tsx("div",{key:a.layer.uid,class:this.classes("esri-legend--card__service","esri-legend--card__group-layer")},e.tsx("div",{class:"esri-legend--card__service-caption-container"},a.title),c)}{if((c=a.legendElements)&&!c.length)return null;const d=c.some(b=>"relationship-ramp"===b.type);c=c.map((b,h)=>this._renderLegendForElement(b,a,h,d)).filter(b=>!!b);return c.length?e.tsx("div",{key:a.layer.uid,class:this.classes("esri-legend--card__service",
{["esri-legend--card__group-layer-child"]:!!a.parent})},e.tsx("div",{class:"esri-legend--card__service-caption-container"},e.tsx("div",{class:"esri-legend--card__service-caption-text"},a.title)),e.tsx("div",{class:"esri-legend--card__service-content"},c)):null}};m._renderLegendForElement=function(a,c,d,b=!1){var h="color-ramp"===a.type,k="opacity-ramp"===a.type,g="size-ramp"===a.type;const l=c.layer;var f=null;"string"===typeof a.title?f=a.title:a.title&&(f=a.title,h=p.getTitle(this.messages,f,h||
k),f=f.title?`${f.title} (${h})`:h);d=this._getSectionName(l,a,d);h=this._hasIndicators?e.tsx("div",null,e.tsx(z.Heading,{level:this.headingLevel,class:"esri-legend--card__carousel-title"},c.title),e.tsx(z.Heading,{level:this.headingLevel+1,class:"esri-legend--card__layer-caption"},f)):f?e.tsx(z.Heading,{level:this.headingLevel,class:"esri-legend--card__layer-caption"},f):null;f=c.effectList;k=null;"symbol-table"===a.type?(g=a.infos.map((n,v)=>this._renderLegendForElementInfo(n,c,a.legendType,v)).filter(n=>
!!n),g.length&&(k=e.tsx("div",{class:this.classes({["esri-legend--card__label-container"]:!(g[0].properties.classes&&g[0].properties.classes["esri-legend--card__symbol-row"])&&!b,["esri-legend--card__relationship-label-container"]:b})},g))):"color-ramp"===a.type||"opacity-ramp"===a.type||"heatmap-ramp"===a.type?k=this._renderLegendForRamp(a,l.opacity,f):g?k=this._renderSizeRamp(a,l.opacity):"relationship-ramp"===a.type?k=N.renderRelationshipRamp(a,this.id,l.opacity,f):"univariate-above-and-below-ramp"===
a.type?k=this._renderUnivariateAboveAndBelowRamp(a,l.opacity,f):"univariate-color-size-ramp"===a.type&&(k=this._renderUnivariateColorSizeRamp(a,l.opacity,f));if(!k)return null;b=e.tsx("div",{key:d,class:"esri-legend--card__section",id:`${d}-panel`,role:"tabpanel","aria-labelledby":d,tabIndex:0},[h,k]);this._sectionMap.set(d,b);return b};m._renderUnivariateAboveAndBelowRamp=function(a,c,d){const {sizeRampElement:b,colorRampElement:h}=q.getUnivariateAboveAndBelowRampElements(a,c,"horizontal");if(!b)return null;
a=q.getUnivariateSizeRampSize(b,"full",!0,"horizontal");var k=q.getUnivariateColorRampSize(b,"above",!0,"horizontal"),g=q.getUnivariateColorRampSize(b,"below",!0,"horizontal");k=q.getUnivariateColorRampPreview(h,{width:k,height:12,rampAlignment:"horizontal",opacity:c,type:"above",effectList:d});c=q.getUnivariateColorRampPreview(h,{width:g,height:12,rampAlignment:"horizontal",opacity:c,type:"below",effectList:d});g=q.getUnivariateColorRampMargin(b,"card");d=b.infos.map(f=>f.label);const l=d.length-
1;d=d.map((f,n)=>0===n||n===l?e.tsx("div",{key:n},f):null);g={marginTop:"3px",marginLeft:`${g}px`,display:"flex"};a={width:`${a}px`,display:"flex",flexDirection:"row",justifyContent:"space-between"};return e.tsx("div",{class:"esri-legend--card__layer-row",key:"size-ramp-preview",styles:{display:"flex",flexDirection:"column"}},e.tsx("div",{class:this.classes("esri-legend--card__symbol-container","esri-legend__size-ramp--horizontal"),styles:{display:"flex",flexDirection:"row"}},b.infos.map((f,n)=>e.tsx("div",
{key:n,class:"esri-legend--card__symbol",bind:f.preview,afterCreate:p.attachToNode}))),k?e.tsx("div",{class:"esri-univariate-above-and-below-ramp__color--card",styles:g,key:"color-ramp-preview"},e.tsx("div",{bind:k,afterCreate:p.attachToNode}),e.tsx("div",{bind:c,afterCreate:p.attachToNode})):null,e.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--info"},e.tsx("div",{class:"esri-legend__ramp-labels",styles:a},d)))};m._renderUnivariateColorSizeRamp=function(a,c,d){const {sizeRampElement:b,
colorRampElement:h}=q.getUnivariateColorSizeRampElements(a,"horizontal");if(!b)return null;a=q.getUnivariateSizeRampSize(b,"full",!1,"horizontal");var k=q.getUnivariateColorRampSize(b,"full",!1,"horizontal");c=q.getUnivariateColorRampPreview(h,{width:k,height:12,rampAlignment:"horizontal",opacity:c,type:"full",effectList:d});k=q.getUnivariateColorRampMargin(b,"card");const g=b.infos.length-1;d=b.infos.map((l,f)=>0===f||f===g?e.tsx("div",{key:f},l.label):null);k={marginTop:"3px",marginLeft:`${k}px`,
display:"flex"};a={width:`${a}px`,display:"flex",flexDirection:"row",justifyContent:"space-between"};return e.tsx("div",{class:"esri-legend--card__layer-row",key:"size-ramp-preview",styles:{display:"flex",flexDirection:"column"}},e.tsx("div",{class:this.classes("esri-legend--card__symbol-container","esri-legend__size-ramp--horizontal"),styles:{display:"flex",flexDirection:"row"}},b.infos.map((l,f)=>e.tsx("div",{key:f,class:"esri-legend--card__symbol",bind:l.preview,afterCreate:p.attachToNode}))),
e.tsx("div",{class:"esri-univariate-above-and-below-ramp__color--card",styles:k,key:"color-ramp-preview"},e.tsx("div",{bind:c,afterCreate:p.attachToNode})),e.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--info"},e.tsx("div",{class:"esri-legend__ramp-labels",styles:a},d)))};m._renderLegendForElementInfo=function(a,c,d,b){var h=c.layer;if(a.type)return this._renderLegendForElement(a,c,b);d=p.isImageryStretchedLegend(h,d);if(a.preview){var k;if(!a.symbol||-1===a.symbol.type.indexOf("simple-fill")){if(!a.label)return e.tsx("div",
{key:b,bind:a.preview,afterCreate:p.attachToNode});c={["esri-legend--card__symbol-cell"]:this._hasIndicators};return e.tsx("div",{key:b,class:this.classes("esri-legend--card__layer-row",{["esri-legend--card__symbol-row"]:this._hasIndicators})},e.tsx("div",{class:this.classes(c),bind:a.preview,afterCreate:p.attachToNode}),e.tsx("div",{class:this.classes("esri-legend--card__image-label",{["esri-legend--card__label-cell"]:this._hasIndicators})},p.getTitle(this.messages,a.label,!1)||""))}let l=d=255,
f=255,n=0,v=255,x=255,y=255,F=0;const G=a.symbol.color&&a.symbol.color.a,H=a.symbol.outline&&a.symbol.outline.color&&a.symbol.outline.color.a;G&&(d=a.symbol.color.r,l=a.symbol.color.g,f=a.symbol.color.b,n=a.symbol.color.a*h.opacity);H&&(v=a.symbol.outline.color.r,x=a.symbol.outline.color.g,y=a.symbol.outline.color.b,F=a.symbol.outline.color.a*h.opacity);var g=(h=null!=(g=null==(k=a.symbol.color)?void 0:k.isBright)?g:!0)?"rgba(255, 255, 255, .6)":"rgba(0, 0, 0, .6)";c={background:G?`rgba(${d}, ${l}, ${f}, ${n})`:
"none",color:h?"black":"white",textShadow:`-1px -1px 0 ${g},\n                                              1px -1px 0 ${g},\n                                              -1px 1px 0 ${g},\n                                              1px 1px 0 ${g}`,border:H?`1px solid rgba(${v}, ${x}, ${y}, ${F})`:"none",filter:C.getCSSFilterFromEffectList(c.effectList)};return e.tsx("div",{key:b,class:"esri-legend--card__layer-row"},e.tsx("div",{class:"esri-legend--card__label-element",styles:c}," ",a.label," "))}if(a.src)return c=
this._renderImage(a,h,d),e.tsx("div",{key:b,class:"esri-legend--card__layer-row"},c,e.tsx("div",{class:"esri-legend--card__image-label"},a.label||""))};m._renderImage=function(a,c,d){const {label:b,src:h,opacity:k}=a;d={["esri-legend--card__imagery-layer-image--stretched"]:d,["esri-legend--card__symbol"]:!d};c={opacity:`${null!=k?k:c.opacity}`};return e.tsx("img",{alt:p.getTitle(this.messages,b,!1),src:h,border:0,width:a.width,height:a.height,class:this.classes(d),styles:c})};m._renderSizeRampLines=
function(a){a=a.infos;var c=a[0],d=a[a.length-1],b=c.symbol;a=this._hasIndicators;c=B.pt2px(c.size+c.outlineSize)*w;d=B.pt2px(d.size+d.outlineSize)*w;const h=a?c:c+50*w,k=a?c/2+50*w:c;var g;b?-1<b.type.indexOf("3d")?(g=b.symbolLayers&&b.symbolLayers.length)?(g=b.symbolLayers.getItemAt(g-1).get("resource.primitive"),g="triangle"===g||"cone"===g||"tetrahedron"===g):g=void 0:g="triangle"===b.style:g=void 0;if(b)if(-1<b.type.indexOf("3d")){var l=b.symbolLayers&&b.symbolLayers.length;l?(b=b.symbolLayers.getItemAt(l-
1),b=b.resource&&b.resource.primitive,b="circle"===b||"cross"===b||"kite"===b||"sphere"===b||"cube"===b||"diamond"===b):b=void 0}else b=b.style,b="circle"===b||"diamond"===b||"cross"===b;else b=void 0;l=document.createElement("canvas");l.width=h;l.height=k;l.style.width=`${l.width/w}px`;l.style.height=`${l.height/w}px`;const f=l.getContext("2d");if(a){f.beginPath();var n=h/2-d/2;f.moveTo(0,0);f.lineTo(n,k);n=h/2+d/2;f.moveTo(h,0);f.lineTo(n,k)}else f.beginPath(),f.moveTo(0,k/2-d/2),f.lineTo(h,0),
f.moveTo(0,k/2+d/2),f.lineTo(h,k);f.strokeStyle="#ddd";f.stroke();return e.tsx("div",{bind:l,afterCreate:p.attachToNode,styles:a?{display:"flex",marginTop:`-${g?0:b?c/2:0}px`,marginBottom:`-${g?d:b?d/2:0}px`}:{display:"flex",marginRight:`-${g?0:b?c/2:0}px`,marginLeft:`-${g?0:b?d/2:0}px`}})};m._renderSizeRamp=function(a,c){var d=a.infos;const b=d[0].label,h=d[d.length-1].label;let k=d[0].preview;d=d[d.length-1].preview;const g=this._hasIndicators,l={"flex-direction":g?"column":"row-reverse"};k&&(k=
k.cloneNode(!0),k.style.display="flex");d&&(d=d.cloneNode(!0),d.style.display="flex");c={opacity:null!=c?`${c}`:""};return e.tsx("div",{class:this.classes("esri-legend--card__layer-row",{["esri-legend--card__size-ramp-row"]:g})},e.tsx("div",{class:"esri-legend--card__ramp-label"},g?b:h),e.tsx("div",{class:"esri-legend--card__size-ramp-container",styles:l},e.tsx("div",{bind:k,afterCreate:p.attachToNode,class:"esri-legend--card__size-ramp-preview",styles:c}),this._renderSizeRampLines(a),e.tsx("div",
{bind:d,afterCreate:p.attachToNode,class:"esri-legend--card__size-ramp-container",styles:c})),e.tsx("div",{class:"esri-legend--card__ramp-label"},g?h:b))};m._renderLegendForRamp=function(a,c,d){var b=a.infos;const h="heatmap-ramp"===a.type,k=b.length-1;var g=2<k&&!h?25*k:100,l=g+20;const f=b.slice(0).reverse();f.forEach((x,y)=>{x.offset=h?x.ratio:y/k});const n=f.length-1;a=(a=0!==f.length%2&&f[f.length/2|0])&&e.tsx("div",{class:"esri-legend--card__interval-separators-container"},e.tsx("div",{class:"esri-legend--card__interval-separator"},
"|"),e.tsx("div",{class:"esri-legend--card__ramp-label"},a.label));const v=b[b.length-1].label;b=b[0].label;g=L.renderSVG([[{shape:{type:"path",path:"M0 12.5 L10 0 L10 25 Z"},fill:f[0].color,stroke:{width:0}},{shape:{type:"rect",x:10,y:0,width:g,height:25},fill:{type:"linear",x1:10,y1:0,x2:g+10,y2:0,colors:f},stroke:{width:0}},{shape:{type:"path",path:`M${g+10} 0 L${l} ${12.5} L${g+10} ${25} Z`},fill:f[n].color,stroke:{width:0}}]],l,25);({messages:l}=this);c={filter:C.getCSSFilterFromEffectList(d),
opacity:null==c?null:`${c}`};return e.tsx("div",{class:"esri-legend--card__layer-row"},e.tsx("div",{class:"esri-legend--card__ramp-label"},h?l[v]:v),e.tsx("div",{class:"esri-legend--card__symbol-container"},e.tsx("div",{styles:c},g),a),e.tsx("div",{class:"esri-legend--card__ramp-label"},h?l[b]:b))};return A}(M);t.__decorate([u.property()],r.prototype,"activeLayerInfos",void 0);t.__decorate([u.property()],r.prototype,"headingLevel",void 0);t.__decorate([u.property()],r.prototype,"layout",void 0);t.__decorate([u.property(),
D.messageBundle("esri/widgets/Legend/t9n/Legend")],r.prototype,"messages",void 0);t.__decorate([u.property(),D.messageBundle("esri/t9n/common")],r.prototype,"messagesCommon",void 0);t.__decorate([u.property({readOnly:!0})],r.prototype,"type",void 0);t.__decorate([u.property()],r.prototype,"view",void 0);t.__decorate([O.accessibleHandler()],r.prototype,"_selectSection",null);return r=t.__decorate([K.subclass("esri.widgets.Legend.styles.Card")],r)});