// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/shading/MultipassTerrainTest.glsl ../core/shaderLibrary/util/View.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/DefaultVertexAttributeLocations ../lib/OrderIndependentTransparency ../lib/Program ../lib/StencilUtils ../../../../chunks/ImageMaterial.glsl ../../../webgl/renderState".split(" "),
function(v,p,t,g,w,x,u,e,m,f,y,n,z,q,A,l){m=function(k){function h(){return k.apply(this,arguments)||this}t._inheritsLoose(h,k);var a=h.prototype;a.initializeProgram=function(b){var c=h.shader.get();const d=this.configuration;c=c.build({output:d.output,slicePlaneEnabled:d.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,OITEnabled:0===d.transparencyPassType,multipassTerrainEnabled:d.multipassTerrainEnabled,cullAboveGround:d.cullAboveGround});return new z.Program(b.rctx,
c,y.Default3D)};a.bindPass=function(b,c){u.bindProjectionMatrix(this.program,c.camera.projectionMatrix);this.program.setUniform1f("opacity",b.opacity);c.multipassTerrainEnabled&&(this.program.setUniform2fv("cameraNearFar",c.camera.nearFar),this.program.setUniform2fv("inverseViewport",c.inverseViewport),x.bindMultipassTerrainTexture(this.program,c))};a.bindDraw=function(b){u.bindView(this.program,b);w.bindSliceUniformsWithOrigin(this.program,this.configuration,b);this.program.rebindTextures()};a.setPipelineState=
function(b,c){const d=this.configuration,r=3===b,B=2===b;return l.makePipelineState({blending:0!==d.output&&7!==d.output||!d.transparent?null:r?C:n.OITBlending(b),culling:l.cullingParams(d.cullFace),depthTest:{func:n.OITDepthTest(b)},depthWrite:r?d.writeDepth&&l.defaultDepthWriteParams:n.OITDepthWrite(b),colorWrite:l.defaultColorWriteParams,stencilWrite:d.sceneHasOcludees?q.stencilWriteMaskOn:null,stencilTest:d.sceneHasOcludees?c?q.stencilToolMaskBaseParams:q.stencilBaseAllZerosParams:null,polygonOffset:r||
B?null:n.getOITPolygonOffset(d.enableOffset)})};a.initializePipeline=function(){this._occludeePipelineState=this.setPipelineState(this.configuration.transparencyPassType,!0);return this.setPipelineState(this.configuration.transparencyPassType,!1)};a.getPipelineState=function(b,c){return c?this._occludeePipelineState:k.prototype.getPipelineState.call(this,b,c)};return h}(m.ShaderTechnique);m.shader=new e.ReloadableShaderModule(A.ImageMaterialShader,()=>new Promise((k,h)=>v(["./ImageMaterial.glsl"],
k,h)));const C=l.simpleBlendingParams(1,771);e=function(k){function h(){var a=k.apply(this,arguments)||this;a.output=0;a.cullFace=0;a.slicePlaneEnabled=!1;a.transparent=!1;a.enableOffset=!0;a.writeDepth=!0;a.sceneHasOcludees=!1;a.transparencyPassType=3;a.multipassTerrainEnabled=!1;a.cullAboveGround=!1;return a}t._inheritsLoose(h,k);return h}(f.ShaderTechniqueConfiguration);g.__decorate([f.parameter({count:8})],e.prototype,"output",void 0);g.__decorate([f.parameter({count:3})],e.prototype,"cullFace",
void 0);g.__decorate([f.parameter()],e.prototype,"slicePlaneEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"transparent",void 0);g.__decorate([f.parameter()],e.prototype,"enableOffset",void 0);g.__decorate([f.parameter()],e.prototype,"writeDepth",void 0);g.__decorate([f.parameter()],e.prototype,"sceneHasOcludees",void 0);g.__decorate([f.parameter({count:4})],e.prototype,"transparencyPassType",void 0);g.__decorate([f.parameter()],e.prototype,"multipassTerrainEnabled",void 0);g.__decorate([f.parameter()],
e.prototype,"cullAboveGround",void 0);p.ImageMaterialTechnique=m;p.ImageMaterialTechniqueConfiguration=e;Object.defineProperty(p,"__esModule",{value:!0})});