// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/maybe ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/output/OutputHighlight.glsl ../core/shaderLibrary/util/View.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/DefaultVertexAttributeLocations ../lib/Program ../lib/StencilUtils ../../../../chunks/NativeLine.glsl ../../../webgl/renderState".split(" "),
function(w,p,q,h,v,x,y,r,e,m,f,z,A,n,B,l){m=function(k){function g(a,b,c){b=k.call(this,a,b,c)||this;b.stipplePattern=null;b.stippleTextureBind=null;b.stippleTextureRepository=a.stippleTextureRepository;return b}q._inheritsLoose(g,k);var d=g.prototype;d.initializeProgram=function(a){var b=g.shader.get();const c=this.configuration;b=b.build({output:c.output,attributeColor:c.vertexColors,slicePlaneEnabled:c.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,draped:c.draped,
stippleEnabled:this.stippleEnabled,stippleOffColorEnabled:c.stippleOffColorEnabled,stippleRequiresClamp:!1,stippleScaleWithLineWidth:!1,stipplePreferContinuous:c.stipplePreferContinuous});return new A.Program(a.rctx,b,z.Default3D)};d.dispose=function(){k.prototype.dispose.call(this);this.stippleTextureRepository.release(this.stipplePattern);this.stippleTextureBind=this.stipplePattern=null};d.bindPass=function(a,b){r.bindProjectionMatrix(this.program,b.camera.projectionMatrix);if(this.stipplePattern!==
a.stipplePattern){const c=a.stipplePattern;this.stippleTextureBind=this.stippleTextureRepository.swap(this.stipplePattern,c);this.stipplePattern=c}if(this.stippleEnabled){const {pixelSize:c,sdfNormalizer:t,pixels:u}=v.isSome(this.stippleTextureBind)?this.stippleTextureBind(this.program):{pixelSize:1,sdfNormalizer:1,pixels:1};this.program.setUniform1f("stipplePatternSDFNormalizer",t);this.program.setUniform1f("stipplePatternTextureSize",u);this.program.setUniform1f("stipplePatternPixelSize",c);this.program.setUniform1f("stipplePatternPixelSizeInv",
1/c);this.program.setUniform1f("pixelRatio",b.camera.pixelRatio);this.configuration.draped?this.program.setUniform1f("worldToScreenRatio",1/b.screenToPCSRatio):this.program.setUniform1f("worldToScreenPerDistanceRatio",1/b.camera.perScreenPixelRatio);this.program.setUniform2f("ndcToPixel",b.camera.fullViewport[2]/2,b.camera.fullViewport[3]/2)}this.program.setUniform4fv("constantColor",a.color);this.program.setUniform1f("alphaCoverage",Math.min(1,a.width*b.camera.pixelRatio));this.configuration.stippleOffColorEnabled&&
(a=v.unwrap(a.stippleOffColor),this.program.setUniform4f("stippleOffColor",a[0],a[1],a[2],3<a.length?a[3]:1));4===this.configuration.output&&y.bindOutputHighlight(this.program,b)};d.bindDraw=function(a){r.bindView(this.program,a);this.stippleEnabled&&!this.configuration.draped&&r.bindCameraPosition(this.program,a.origin,a.camera.viewInverseTransposeMatrix);x.bindSliceUniformsWithOrigin(this.program,this.configuration,a);this.program.rebindTextures()};d.initializePipeline=function(){const a=this.configuration,
b=l.separateBlendingParams(770,1,771,771),c=(t,u=null,C=null)=>l.makePipelineState({blending:u,depthTest:n.depthCompareLess,depthWrite:C,colorWrite:l.defaultColorWriteParams,stencilWrite:a.sceneHasOcludees?n.stencilWriteMaskOn:null,stencilTest:a.sceneHasOcludees?t?n.stencilToolMaskBaseParams:n.stencilBaseAllZerosParams:null});return 0===a.output?(this._occludeePipelineState=c(!0,a.transparent||this.stippleEnabled?b:null,l.defaultDepthWriteParams),c(!1,a.transparent||this.stippleEnabled?b:null,l.defaultDepthWriteParams)):
c(!1)};d.getPipelineState=function(a,b){return b?this._occludeePipelineState:k.prototype.getPipelineState.call(this,a,b)};q._createClass(g,[{key:"stippleEnabled",get:function(){return this.configuration.stippleEnabled&&4!==this.configuration.output}},{key:"primitiveType",get:function(){return 1}}]);return g}(m.ShaderTechnique);m.shader=new e.ReloadableShaderModule(B.NativeLineShader,()=>new Promise((k,g)=>w(["./NativeLine.glsl"],k,g)));e=function(k){function g(){var d=k.apply(this,arguments)||this;
d.output=0;d.slicePlaneEnabled=!1;d.vertexColors=!1;d.transparent=!1;d.draped=!1;d.stippleEnabled=!1;d.stippleOffColorEnabled=!1;d.stipplePreferContinuous=!0;d.sceneHasOcludees=!1;return d}q._inheritsLoose(g,k);return g}(f.ShaderTechniqueConfiguration);h.__decorate([f.parameter({count:8})],e.prototype,"output",void 0);h.__decorate([f.parameter()],e.prototype,"slicePlaneEnabled",void 0);h.__decorate([f.parameter()],e.prototype,"vertexColors",void 0);h.__decorate([f.parameter()],e.prototype,"transparent",
void 0);h.__decorate([f.parameter()],e.prototype,"draped",void 0);h.__decorate([f.parameter()],e.prototype,"stippleEnabled",void 0);h.__decorate([f.parameter()],e.prototype,"stippleOffColorEnabled",void 0);h.__decorate([f.parameter()],e.prototype,"stipplePreferContinuous",void 0);h.__decorate([f.parameter()],e.prototype,"sceneHasOcludees",void 0);p.NativeLineTechnique=m;p.NativeLineTechniqueConfiguration=e;Object.defineProperty(p,"__esModule",{value:!0})});