// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/output/OutputHighlight.glsl ../core/shaderLibrary/shading/MultipassTerrainTest.glsl ../core/shaderLibrary/util/View.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/OrderIndependentTransparency ../lib/Program ../lib/StencilUtils ../../../../chunks/Pattern.glsl ../../../webgl/renderState".split(" "),
function(w,m,u,g,x,y,z,q,d,n,e,l,A,r,B,p){n=function(k){function h(){return k.apply(this,arguments)||this}u._inheritsLoose(h,k);var a=h.prototype;a.initializeProgram=function(f){var b=h.shader.get();const c=this.configuration;b=b.build({output:c.output,attributeColor:c.vertexColors,slicePlaneEnabled:c.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,style:c.style,patternSpacing:c.patternSpacing,lineWidth:c.lineWidth,draped:c.draped,OITEnabled:0===c.transparencyPassType,
multipassTerrainEnabled:c.multipassTerrainEnabled,cullAboveGround:c.cullAboveGround});return new A.Program(f.rctx,b,v)};a.bindPass=function(f,b){q.bindProjectionMatrix(this.program,b.camera.projectionMatrix);this.program.setUniform4fv("matColor",f.color);this.configuration.draped?(this.program.setUniform1f("worldToScreenRatio",1/b.screenToPCSRatio),this.program.setUniform1f("texelSize",1/b.camera.pixelRatio)):this.program.setUniform1f("worldToScreenPerDistanceRatio",1/b.camera.perScreenPixelRatio);
4===this.configuration.output&&y.bindOutputHighlight(this.program,b);(1===this.configuration.output||b.multipassTerrainEnabled)&&this.program.setUniform2fv("cameraNearFar",b.camera.nearFar);b.multipassTerrainEnabled&&(this.program.setUniform2fv("inverseViewport",b.inverseViewport),z.bindMultipassTerrainTexture(this.program,b))};a.bindDraw=function(f){q.bindView(this.program,f);q.bindCameraPosition(this.program,f.origin,f.camera.viewInverseTransposeMatrix);x.bindSliceUniformsWithOrigin(this.program,
this.configuration,f);this.program.rebindTextures()};a.setPipelineState=function(f,b){const c=this.configuration,t=3===f,C=2===f;return p.makePipelineState({blending:0===c.output||7===c.output?t?l.blendingDefault:l.OITBlending(f):null,culling:p.cullingParams(c.cullFace),depthTest:{func:l.OITDepthTest(f)},depthWrite:t?c.writeDepth&&p.defaultDepthWriteParams:l.OITDepthWrite(f),colorWrite:p.defaultColorWriteParams,stencilWrite:c.sceneHasOcludees?r.stencilWriteMaskOn:null,stencilTest:c.sceneHasOcludees?
b?r.stencilToolMaskBaseParams:r.stencilBaseAllZerosParams:null,polygonOffset:t||C?c.polygonOffset&&D:l.getOITPolygonOffset(c.enableOffset)})};a.initializePipeline=function(){this._occludeePipelineState=this.setPipelineState(this.configuration.transparencyPassType,!0);return this.setPipelineState(this.configuration.transparencyPassType,!1)};a.getPipelineState=function(f,b){return b?this._occludeePipelineState:k.prototype.getPipelineState.call(this,f,b)};return h}(n.ShaderTechnique);n.shader=new d.ReloadableShaderModule(B.PatternShader,
()=>new Promise((k,h)=>w(["./Pattern.glsl"],k,h)));const D={factor:1,units:1};d=function(k){function h(){var a=k.apply(this,arguments)||this;a.output=0;a.cullFace=0;a.slicePlaneEnabled=!1;a.vertexColors=!1;a.polygonOffset=!1;a.writeDepth=!0;a.sceneHasOcludees=!1;a.enableOffset=!0;a.transparencyPassType=3;a.multipassTerrainEnabled=!1;a.cullAboveGround=!1;return a}u._inheritsLoose(h,k);return h}(e.ShaderTechniqueConfiguration);g.__decorate([e.parameter({count:8})],d.prototype,"output",void 0);g.__decorate([e.parameter({count:3})],
d.prototype,"cullFace",void 0);g.__decorate([e.parameter()],d.prototype,"slicePlaneEnabled",void 0);g.__decorate([e.parameter()],d.prototype,"vertexColors",void 0);g.__decorate([e.parameter()],d.prototype,"polygonOffset",void 0);g.__decorate([e.parameter()],d.prototype,"writeDepth",void 0);g.__decorate([e.parameter()],d.prototype,"sceneHasOcludees",void 0);g.__decorate([e.parameter({count:6})],d.prototype,"style",void 0);g.__decorate([e.parameter()],d.prototype,"patternSpacing",void 0);g.__decorate([e.parameter()],
d.prototype,"lineWidth",void 0);g.__decorate([e.parameter()],d.prototype,"enableOffset",void 0);g.__decorate([e.parameter()],d.prototype,"draped",void 0);g.__decorate([e.parameter({count:4})],d.prototype,"transparencyPassType",void 0);g.__decorate([e.parameter()],d.prototype,"multipassTerrainEnabled",void 0);g.__decorate([e.parameter()],d.prototype,"cullAboveGround",void 0);const v=new Map([["position",0],["color",3],["uvMapSpace",4],["boundingRect",5]]);m.PatternTechnique=n;m.PatternTechniqueConfiguration=
d;m.patternVertexAttributeLocations=v;Object.defineProperty(m,"__esModule",{value:!0})});