// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../chunks/Terrain.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/DefaultVertexAttributeLocations ../lib/Program ../lib/StencilUtils ../../../webgl/renderState".split(" "),function(q,n,p,e,b,r,m,c,t,u,v,l){m=function(k){function g(){var h=k.apply(this,arguments)||this;h.useStencil=!1;return h}
p._inheritsLoose(g,k);var a=g.prototype;a.initializeProgram=function(h){var f=g.shader.get();const d=this.configuration;f=f.build({overlayMode:d.overlayMode,output:d.output,viewingMode:h.viewingMode,slicePlaneEnabled:d.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,textureFadingEnabled:d.textureFadingEnabled&&!d.renderOccluded,hasBackgroundColor:d.hasBackgroundColor,useGrid:d.useGrid,receiveShadows:d.receiveShadows&&!d.renderOccluded,receiveAmbientOcclusion:!1,atmosphere:d.atmosphere,
tileBorders:d.tileBorders,screenSizePerspective:d.screenSizePerspective,pbrMode:0,ssrEnabled:d.ssrEnabled,highStepCount:!1});return new u.Program(h.rctx,f,t.Default3D)};a.initializePipeline=function(){this._stencilPipelineState=this.createPipeline(!0);return this.createPipeline(!1)};a.createPipeline=function(h){const f=this.configuration,d=f.backfaceCullingEnabled&&!f.renderOccluded;return l.makePipelineState({blending:f.renderOccluded?l.simpleBlendingParams(1,771):null,culling:d&&l.backFaceCullingParams,
depthTest:!f.renderOccluded&&{func:513},depthWrite:!f.renderOccluded&&l.defaultDepthWriteParams,colorWrite:l.defaultColorWriteParams,stencilTest:h?v.renderWhenBitIsNotSet(1):null})};a.getPipelineState=function(h,f){return this.useStencil?this._stencilPipelineState:k.prototype.getPipelineState.call(this,h,f)};return g}(m.ShaderTechnique);m.shader=new r.ReloadableShaderModule(b.TerrainShader,()=>new Promise((k,g)=>q(["../core/shaderLibrary/terrain/Terrain.glsl"],k,g)));b=function(k){function g(){var a=
k.apply(this,arguments)||this;a.output=0;a.overlayMode=0;a.atmosphere=!1;a.receiveShadows=!1;a.slicePlaneEnabled=!1;a.backfaceCullingEnabled=!1;a.stencilEnabled=!1;a.textureFadingEnabled=!1;a.hasBackgroundColor=!1;a.useGrid=!1;a.renderOccluded=!1;a.ssrEnabled=!1;a.tileBorders=!1;a.screenSizePerspective=!1;return a}p._inheritsLoose(g,k);return g}(c.ShaderTechniqueConfiguration);e.__decorate([c.parameter({count:8})],b.prototype,"output",void 0);e.__decorate([c.parameter({count:3})],b.prototype,"overlayMode",
void 0);e.__decorate([c.parameter()],b.prototype,"atmosphere",void 0);e.__decorate([c.parameter()],b.prototype,"receiveShadows",void 0);e.__decorate([c.parameter()],b.prototype,"slicePlaneEnabled",void 0);e.__decorate([c.parameter()],b.prototype,"backfaceCullingEnabled",void 0);e.__decorate([c.parameter()],b.prototype,"stencilEnabled",void 0);e.__decorate([c.parameter()],b.prototype,"textureFadingEnabled",void 0);e.__decorate([c.parameter()],b.prototype,"hasBackgroundColor",void 0);e.__decorate([c.parameter()],
b.prototype,"useGrid",void 0);e.__decorate([c.parameter()],b.prototype,"renderOccluded",void 0);e.__decorate([c.parameter()],b.prototype,"ssrEnabled",void 0);e.__decorate([c.parameter()],b.prototype,"tileBorders",void 0);e.__decorate([c.parameter()],b.prototype,"screenSizePerspective",void 0);n.TerrainTechnique=m;n.TerrainTechniqueConfiguration=b;Object.defineProperty(n,"__esModule",{value:!0})});