// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["require","exports","../chunks/_rollupPluginBabelHelpers","./locale"],function(c,h,k,l){function e(){e=k._asyncToGenerator(function*(a=l.getLocale()){const b=(yield(new Promise((d,m)=>c(["../chunks/moment"],d,m))).then(d=>d.moment)).default;a=a.toLowerCase();let g=f.has(a);if(!g){const d=a.split("-");1<d.length&&f.has(d[0])&&(a=d[0],g=!0)}g?yield f.get(a)():a="en";a!==b.locale()&&b.locale(a);return b});return e.apply(this,arguments)}const f=new Map([["ar",()=>(new Promise((a,b)=>c(["../chunks/ar"],
a,b))).then(a=>a.ar)],["ar-dz",()=>(new Promise((a,b)=>c(["../chunks/ar-dz"],a,b))).then(a=>a.arDz)],["ar-kw",()=>(new Promise((a,b)=>c(["../chunks/ar-kw"],a,b))).then(a=>a.arKw)],["ar-ly",()=>(new Promise((a,b)=>c(["../chunks/ar-ly"],a,b))).then(a=>a.arLy)],["ar-ma",()=>(new Promise((a,b)=>c(["../chunks/ar-ma"],a,b))).then(a=>a.arMa)],["ar-sa",()=>(new Promise((a,b)=>c(["../chunks/ar-sa"],a,b))).then(a=>a.arSa)],["ar-tn",()=>(new Promise((a,b)=>c(["../chunks/ar-tn"],a,b))).then(a=>a.arTn)],["bg",
()=>(new Promise((a,b)=>c(["../chunks/bg"],a,b))).then(a=>a.bg)],["bs",()=>(new Promise((a,b)=>c(["../chunks/bs"],a,b))).then(a=>a.bs)],["ca",()=>(new Promise((a,b)=>c(["../chunks/ca"],a,b))).then(a=>a.ca)],["cs",()=>(new Promise((a,b)=>c(["../chunks/cs"],a,b))).then(a=>a.cs)],["da",()=>(new Promise((a,b)=>c(["../chunks/da"],a,b))).then(a=>a.da)],["de",()=>(new Promise((a,b)=>c(["../chunks/de"],a,b))).then(a=>a.de)],["de-at",()=>(new Promise((a,b)=>c(["../chunks/de-at"],a,b))).then(a=>a.deAt)],["de-ch",
()=>(new Promise((a,b)=>c(["../chunks/de-ch"],a,b))).then(a=>a.deCh)],["el",()=>(new Promise((a,b)=>c(["../chunks/el"],a,b))).then(a=>a.el)],["en-au",()=>(new Promise((a,b)=>c(["../chunks/en-au"],a,b))).then(a=>a.enAu)],["en-ca",()=>(new Promise((a,b)=>c(["../chunks/en-ca"],a,b))).then(a=>a.enCa)],["en-gb",()=>(new Promise((a,b)=>c(["../chunks/en-gb"],a,b))).then(a=>a.enGb)],["en-ie",()=>(new Promise((a,b)=>c(["../chunks/en-ie"],a,b))).then(a=>a.enIe)],["en-il",()=>(new Promise((a,b)=>c(["../chunks/en-il"],
a,b))).then(a=>a.enIl)],["en-in",()=>(new Promise((a,b)=>c(["../chunks/en-in"],a,b))).then(a=>a.enIn)],["en-nz",()=>(new Promise((a,b)=>c(["../chunks/en-nz"],a,b))).then(a=>a.enNz)],["en-sg",()=>(new Promise((a,b)=>c(["../chunks/en-sg"],a,b))).then(a=>a.enSg)],["es",()=>(new Promise((a,b)=>c(["../chunks/es"],a,b))).then(a=>a.es)],["es-do",()=>(new Promise((a,b)=>c(["../chunks/es-do"],a,b))).then(a=>a.esDo)],["es-mx",()=>(new Promise((a,b)=>c(["../chunks/es-mx"],a,b))).then(a=>a.esMx)],["es-us",()=>
(new Promise((a,b)=>c(["../chunks/es-us"],a,b))).then(a=>a.esUs)],["et",()=>(new Promise((a,b)=>c(["../chunks/et"],a,b))).then(a=>a.et)],["fi",()=>(new Promise((a,b)=>c(["../chunks/fi"],a,b))).then(a=>a.fi)],["fr",()=>(new Promise((a,b)=>c(["../chunks/fr"],a,b))).then(a=>a.fr)],["fr-ca",()=>(new Promise((a,b)=>c(["../chunks/fr-ca"],a,b))).then(a=>a.frCa)],["fr-ch",()=>(new Promise((a,b)=>c(["../chunks/fr-ch"],a,b))).then(a=>a.frCh)],["he",()=>(new Promise((a,b)=>c(["../chunks/he"],a,b))).then(a=>
a.he)],["hr",()=>(new Promise((a,b)=>c(["../chunks/hr"],a,b))).then(a=>a.hr)],["hu",()=>(new Promise((a,b)=>c(["../chunks/hu"],a,b))).then(a=>a.hu)],["id",()=>(new Promise((a,b)=>c(["../chunks/id"],a,b))).then(a=>a.id)],["it",()=>(new Promise((a,b)=>c(["../chunks/it"],a,b))).then(a=>a.it)],["it-ch",()=>(new Promise((a,b)=>c(["../chunks/it-ch"],a,b))).then(a=>a.itCh)],["ja",()=>(new Promise((a,b)=>c(["../chunks/ja"],a,b))).then(a=>a.ja)],["ko",()=>(new Promise((a,b)=>c(["../chunks/ko"],a,b))).then(a=>
a.ko)],["lt",()=>(new Promise((a,b)=>c(["../chunks/lt"],a,b))).then(a=>a.lt)],["lv",()=>(new Promise((a,b)=>c(["../chunks/lv"],a,b))).then(a=>a.lv)],["nb",()=>(new Promise((a,b)=>c(["../chunks/nb"],a,b))).then(a=>a.nb)],["nl",()=>(new Promise((a,b)=>c(["../chunks/nl"],a,b))).then(a=>a.nl)],["nl-be",()=>(new Promise((a,b)=>c(["../chunks/nl-be"],a,b))).then(a=>a.nlBe)],["pl",()=>(new Promise((a,b)=>c(["../chunks/pl"],a,b))).then(a=>a.pl)],["pt",()=>(new Promise((a,b)=>c(["../chunks/pt"],a,b))).then(a=>
a.pt)],["pt-br",()=>(new Promise((a,b)=>c(["../chunks/pt-br"],a,b))).then(a=>a.ptBr)],["ro",()=>(new Promise((a,b)=>c(["../chunks/ro"],a,b))).then(a=>a.ro)],["ru",()=>(new Promise((a,b)=>c(["../chunks/ru"],a,b))).then(a=>a.ru)],["sk",()=>(new Promise((a,b)=>c(["../chunks/sk"],a,b))).then(a=>a.sk)],["sl",()=>(new Promise((a,b)=>c(["../chunks/sl"],a,b))).then(a=>a.sl)],["sr",()=>(new Promise((a,b)=>c(["../chunks/sr"],a,b))).then(a=>a.sr)],["sr-cyrl",()=>(new Promise((a,b)=>c(["../chunks/sr-cyrl"],a,
b))).then(a=>a.srCyrl)],["sv",()=>(new Promise((a,b)=>c(["../chunks/sv"],a,b))).then(a=>a.sv)],["th",()=>(new Promise((a,b)=>c(["../chunks/th"],a,b))).then(a=>a.th)],["tr",()=>(new Promise((a,b)=>c(["../chunks/tr"],a,b))).then(a=>a.tr)],["uk",()=>(new Promise((a,b)=>c(["../chunks/uk"],a,b))).then(a=>a.uk)],["vi",()=>(new Promise((a,b)=>c(["../chunks/vi"],a,b))).then(a=>a.vi)],["zh-cn",()=>(new Promise((a,b)=>c(["../chunks/zh-cn"],a,b))).then(a=>a.zhCn)],["zh-hk",()=>(new Promise((a,b)=>c(["../chunks/zh-hk"],
a,b))).then(a=>a.zhHk)],["zh-mo",()=>(new Promise((a,b)=>c(["../chunks/zh-mo"],a,b))).then(a=>a.zhMo)],["zh-tw",()=>(new Promise((a,b)=>c(["../chunks/zh-tw"],a,b))).then(a=>a.zhTw)]]);h.loadMoment=function(){return e.apply(this,arguments)};Object.defineProperty(h,"__esModule",{value:!0})});