// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4 ../../../../chunks/vec4f64 ../../../../geometry/support/ray ./IntersectorInterfaces ./intersectorUtils ./verticalOffsetUtils ../materials/renderers/utils".split(" "),function(v,C,e,G,D,f,p,I,J,h,K,L,E,M){function H(d){return new r(d)}let P=function(){function d(a){this.options=new K.IntersectorOptions;
this._results=new N;this.transform=new E.IntersectorTransform;this.tolerance=1E-5;this.verticalOffset=null;this._ray=h.create();this._rayEnd=p.create();this._rayBeginTransformed=p.create();this._rayEndTransformed=p.create();this.viewingMode=null==a?1:a}var c=d.prototype;c.reset=function(a,b,m){this.resetWithRay(h.fromPoints(a,b,this._ray),m)};c.resetWithRay=function(a,b){this.camera=b;a!==this._ray&&h.copy(a,this._ray);0!==this.options.verticalOffset?2===this.viewingMode?this._ray.origin[2]-=this.options.verticalOffset:
this.verticalOffset=this.options.verticalOffset:this.verticalOffset=null;f.add(this._rayEnd,this._ray.origin,this._ray.direction);this._results.init(this._ray)};c.intersect=function(a=null,b,m,q,n){this.point=b;this.filterPredicate=q;this.tolerance=null==m?1E-5:m;b=E.getVerticalOffsetObject3D(this.verticalOffset);if(e.isSome(a)&&0<a.length){const k=n?g=>{n(g)&&this.intersectObject(g)}:g=>{this.intersectObject(g)};for(const g of a)a=g.getSpatialQueryAccelerator&&g.getSpatialQueryAccelerator(),e.isSome(a)?
(e.isSome(b)?a.forEachAlongRayWithVerticalOffset(this._ray.origin,this._ray.direction,k,b):a.forEachAlongRay(this._ray.origin,this._ray.direction,k),this.options.selectionMode&&this.options.hud&&a.forEachDegenerateObject(k)):g.objects.forAll(w=>k(w))}this.sortResults()};c.intersectObject=function(a){const b=a.geometryRecords;if(b){var m=a.transformation,q=E.getVerticalOffsetObject3D(this.verticalOffset);for(const n of b){const {geometry:k,material:g,instanceParameters:w}=n;if(M.isInstanceHidden(w))continue;
const x=k.id;this.transform.setAndInvalidateLazyTransforms(m,n.getShaderTransformation());f.transformMat4(this._rayBeginTransformed,this.rayBegin,this.transform.inverse);f.transformMat4(this._rayEndTransformed,this.rayEnd,this.transform.inverse);const F=this.transform.transform;e.isSome(q)&&(q.objectTransform=this.transform);g.intersect(k,w,this.transform.transform,this,this._rayBeginTransformed,this._rayEndTransformed,(l,y,z,A,t,O)=>{0<=l&&(!e.isSome(this.filterPredicate)||this.filterPredicate(this._ray.origin,
this._rayEnd,l))&&(A?(null==this._results.hud.dist||l<this._results.hud.dist)&&this._results.hud.set(1,{object:a,geometryId:x,triangleNr:z,center:O},l,y,D.IDENTITY,t):((null==this._results.min.drapedLayerOrder||t>=this._results.min.drapedLayerOrder)&&(null==this._results.min.dist||l<this._results.min.dist)&&this._results.min.set(0,{object:a,geometryId:x,triangleNr:z},l,y,F,t),0!==this.options.store&&(null==this._results.max.drapedLayerOrder||t<this._results.max.drapedLayerOrder)&&(null==this._results.max.dist||
l>this._results.max.dist)&&this._results.max.set(0,{object:a,geometryId:x,triangleNr:z},l,y,F,t),2===this.options.store&&(A=H(this._ray),A.set(0,{object:a,geometryId:x,triangleNr:z},l,y,F),this._results.all.push(A))))},n.shaderTransformation)}}};c.sortResults=function(){this._results.all.sort((a,b)=>a.dist!==b.dist?e.unwrapOr(a.dist,0)-e.unwrapOr(b.dist,0):a.drapedLayerOrder!==b.drapedLayerOrder?e.unwrapOr(a.drapedLayerOrder,Number.MAX_VALUE)-e.unwrapOr(b.drapedLayerOrder,Number.MAX_VALUE):e.unwrapOr(b.drapedLayerGraphicOrder,
Number.MIN_VALUE)-e.unwrapOr(a.drapedLayerGraphicOrder,Number.MIN_VALUE))};C._createClass(d,[{key:"results",get:function(){return this._results}},{key:"ray",get:function(){return this._ray}},{key:"rayBegin",get:function(){return this._ray.origin}},{key:"rayEnd",get:function(){return this._rayEnd}}]);return d}(),N=function(){function d(){this._min=new r(h.create());this._max=new r(h.create());this._hud=new r(h.create());this._ground=new r(h.create())}d.prototype.init=function(c){this._min.init(c);
this._max.init(c);this._hud.init(c);this._ground.init(c);this.all=[]};C._createClass(d,[{key:"min",get:function(){return this._min}},{key:"max",get:function(){return this._max}},{key:"hud",get:function(){return this._hud}},{key:"ground",get:function(){return this._ground}}]);return d}(),r=function(){function d(a){this.intersector=0;this.normal=p.create();this.transformation=D.create();this._ray=h.create();this.init(a)}var c=d.prototype;c.getIntersectionPoint=function(a){if(!L.isValidIntersectorResult(this))return!1;
f.scale(B,this.ray.direction,this.dist);f.add(a,this.ray.origin,B);return!0};c.getTransformedNormal=function(a){f.copy(u,this.normal);u[3]=0;I.transformMat4(u,u,this.transformation);f.copy(a,u);return f.normalize(a,a)};c.init=function(a){this.drapedLayerGraphicOrder=this.drapedLayerOrder=this.target=this.dist=null;this.intersector=0;h.copy(a,this._ray)};c.set=function(a,b,m,q,n,k,g){this.intersector=a;this.dist=m;f.copy(this.normal,e.unwrapOr(q,p.UNIT_Z));G.copy(this.transformation,e.unwrapOr(n,D.IDENTITY));
this.target=b;this.drapedLayerOrder=k;this.drapedLayerGraphicOrder=g};c.copy=function(a){h.copy(a.ray,this._ray);this.intersector=a.intersector;this.dist=a.dist;this.target=a.target;this.drapedLayerOrder=a.drapedLayerOrder;this.drapedLayerGraphicOrder=a.drapedLayerGraphicOrder;f.copy(this.normal,a.normal);G.copy(this.transformation,a.transformation)};C._createClass(d,[{key:"ray",get:function(){return this._ray}},{key:"distanceInRenderSpace",get:function(){return e.isSome(this.dist)?(f.scale(B,this.ray.direction,
this.dist),f.length(B)):null}}]);return d}();const B=p.create(),u=J.create();v.DEFAULT_TOLERANCE=1E-5;v.newIntersector=function(d){return new P(d)};v.newIntersectorResult=H;Object.defineProperty(v,"__esModule",{value:!0})});