// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/MapUtils ../../../../core/maybe ../../../../core/uid ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ./GeometryRecord ./Util".split(" "),function(w,t,n,x,u,B,y,E,F,G,C,z,v){n=function(A){function r(a){a=A.call(this,a)||this;a._residentGeomRecords=
new Map;a._dirtyGeomRecords=new Map;a.dirty=!1;return a}w._inheritsLoose(r,A);var d=r.prototype;d.commit=function(a){this.dirty=!1;this._dirtyGeomRecords.forEach((b,c)=>this.commitLayer(c,a))};d.commitLayer=function(a,b){const c=this._dirtyGeomRecords.get(a);c&&(c.forEach((l,f)=>{const h=this._ensureGeomRecord(a,f);l.forEach((e,m)=>{var k=e[0],g=e[1],p=e[2];e=!1;if(g&2){var q=h.get(m);if(q){q=q[1];if(p&4){const D=this.model.getObject(f);this.model.updateRenderGeometryTransformation(D,k,q)&&(e=!0)}e||
b.updates.push({renderGeometry:q,updateType:p})}else v.assert(!1,"ModelDirtySet.getAddRemoveListFilteredByLayers: invalid update")}if(g&4||e)(p=h.get(m))?(b.removes.push(p[1]),h.delete(m),p[0].disposed&&z.GeometryRecord.pool.release(p[0])):4===g&&v.assert(!1,"ModelDirtySet.getAddRemoveListFilteredByLayers: invalid remove");if(g&1||e)g=this.model.getObject(f),u.isSome(g)&&(g=this.model.getRenderGeometry(g,k),k=[k,g],b.adds.push(g),h.set(m,k))});0===h.size&&this._residentGeomRecords.get(a).delete(f)}),
0===this._residentGeomRecords.get(a).size&&this._residentGeomRecords.delete(a),this._dirtyGeomRecords.delete(a))};d.getResidentRenderGeometries=function(a,b){(a=this._residentGeomRecords.get(a))&&a.forEach(c=>c.forEach(l=>b.push(l[1])))};d._objectStateChanged=function(a,b){for(const c of b.geometryRecords)this._updateOrCreateDirtyRecord(b,c,null,2,0,0,2,5,a)};d.visibilityChanged=function(a){this._objectStateChanged(1,a)};d.highlightChanged=function(a){this._objectStateChanged(8,a)};d.occlusionChanged=
function(a){this._objectStateChanged(16,a)};d.vertexAttrsUpdated=function(a){this._updateOrCreateDirtyRecord(a.object,a.record,null,2,0,0,2,5,2)};d.layerAdded=function(a){a.objects.forAll(b=>this._layerObjectAdded(a,b))};d.layerRemoved=function(a){a.objects.forAll(b=>this._layerObjectRemoved(a,b))};d.layerObjectAdded=function(a){this._layerObjectAdded(a.layer,a.object)};d._layerObjectAdded=function(a,b){a=a.id;for(const c of b.geometryRecords)this._objectGeometryAdded(b,c,a)};d.layerObjectRemoved=
function(a){this._layerObjectRemoved(a.layer,a.object)};d.layerObjectsAdded=function(a){for(const b of a.objects)this._layerObjectAdded(a.layer,b)};d.layerObjectsRemoved=function(a){for(const b of a.objects)this._layerObjectRemoved(a.layer,b)};d._layerObjectRemoved=function(a,b){a=a.id;for(const c of b.geometryRecords)this._objectGeometryRemoved(b,c,a)};d.shaderTransformationChanged=function(a){(a=this._residentGeomRecords.get(a.id))&&a.forEach((b,c)=>{(c=this.model.getObject(c))&&c.hasVolativeTransformation()&&
b.forEach(l=>{l[1].shaderTransformationChanged()})})};d.objectTransformation=function(a){const b=this._getParentLayerId(a);this._ensureGeomRecord(b,a.id).forEach(c=>{this._updateOrCreateDirtyRecord(a,c[0],b,2,0,0,2,5,4)})};d.objectGeometryAdded=function(a){this._objectGeometryAdded(a.object,a.record)};d._objectGeometryAdded=function(a,b,c=null){this._updateOrCreateDirtyRecord(a,b,c,1,4,0,0,0)};d.objectGeometryRemoved=function(a){this._objectGeometryRemoved(a.object,a.record)};d._objectGeometryRemoved=
function(a,b,c=null){this._updateOrCreateDirtyRecord(a,b,c,4,1,2,0,0)};d._updateOrCreateDirtyRecord=function(a,b,c,l,f,h,e,m,k){c=u.unwrapOr(c,this._getParentLayerId(a));const g=b.id;a=this._ensureDirtyRecord(c,a.id);(c=a.get(g))?(b=c[1],b&f?(a.delete(g),c[0].disposed&&z.GeometryRecord.pool.release(c[0])):b&h?(c[1]=l,c[2]=k):b&e?c[2]|=k:b&m||v.assert(!1,"ModelDirtySet.objectGeometryAdded: inconsistent state")):a.set(g,[b,l,k]);this.dirty=this._hasDirtyGeometryRecords};d._ensureGeomRecord=function(a,
b){let c=this._residentGeomRecords.get(a);c||(c=new Map,this._residentGeomRecords.set(a,c));a=c.get(b);a||(a=new Map,c.set(b,a));return a};d._ensureDirtyRecord=function(a,b){let c=this._dirtyGeomRecords.get(a);c||(c=new Map,this._dirtyGeomRecords.set(a,c));a=c.get(b);a||(a=new Map,c.set(b,a));return a};d._getParentLayerId=function(a){return u.isSome(a.parentLayer)?a.parentLayer.id:B.NullUID};d.formatDebugInfo=function(){const a=["ADD","UPD",void 0,"REM"];let b="";this._dirtyGeomRecords.forEach((c,
l)=>{c.forEach((f,h)=>{0<b.length&&(b+="\n");b+=l+"."+h;const e=[];f.forEach(m=>{const k=m[1];e[k]||(e[k]=[]);e[k].push(m[0].geometry.id)});for(f=0;f<e.length;f++)if(e[f])for(b+=" "+a[f-1]+": ",h=0;h<e[f].length;h++)b+=e[f][h]+", "})});return b};w._createClass(r,[{key:"_hasDirtyGeometryRecords",get:function(){return x.someMap(this._dirtyGeomRecords,a=>x.someMap(a,b=>b&&0<b.size))}},{key:"test",get:function(){const a=this;return{get residentLayerCount(){return a._residentGeomRecords.size},get residentObjectCount(){return Array.from(a._residentGeomRecords.values()).reduce((b,
c)=>b+c.size,0)}}}}]);return r}(n);t.__decorate([y.property({constructOnly:!0})],n.prototype,"model",void 0);t.__decorate([y.property()],n.prototype,"dirty",void 0);return n=t.__decorate([C.subclass("esri.views.3d.webgl-engine.lib.ModelDirtySet")],n)});