// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/maybe ../../definitions ../../enums ../../number ../../TurboLine ../../materialKey/MaterialKey ./templateUtils".split(" "),function(v,r,w,x,m,y,q,z){const A=(c,n,l)=>(g,a,b,h,d,e,k,f,p,t,u)=>{b=m.i1616to32(u,Math.ceil(16*c._halfWidth));k=m.i8888to32(Math.round(16*k),Math.round(16*f),Math.round(16*p),Math.round(16*t));d=m.i8888to32(16*d,16*e,0,c._bitset);e=c.out;e.vertexBounds(g,a,n,l);e.vertexWrite(m.i1616to32(8*g,8*
a));e.vertexWrite(c.id);e.vertexWrite(c._fillColor);e.vertexWrite(k);e.vertexWrite(b);e.vertexWrite(c._tl);e.vertexWrite(c._br);e.vertexWrite(d);e.vertexWrite(m.i1616to32(Math.ceil(16*c._halfReferenceWidth),0));e.vertexWrite(c.minMaxZoom);e.vertexEnd();return c.offset+c.vertexCount++},B=(c,n,l)=>(g,a,b,h,d,e,k,f,p,t,u)=>{b=m.i8888to32(0,0,16*c._halfWidth,16*c._halfReferenceWidth);k=m.i8888to32(16*k+128,16*f+128,16*p+128,16*t+128);f=c.out;p=c._bitset<<24|c.id;f.vertexBounds(g,a,n,l);f.vertexWrite(m.i1616to32(8*
g,8*a));f.vertexWrite(p);f.vertexWrite(c._fillColor);c.key.simple||(f.vertexWrite(0),f.vertexWrite(0));f.vertexWrite(b);f.vertexWrite(k);c.key.simple||f.vertexWrite(c.minMaxZoom);f.vertexEnd();return c.offset+c.vertexCount++},C=c=>(n,l,g)=>{const a=c.out;a.indexWrite(n);a.indexWrite(l);a.indexWrite(g);c.indexCount+=3};return c=>function(n){function l(...a){a=n.call(this,...a)||this;a.tessellationProperties={};a._tessellationOptions={halfWidth:0,pixelCoordRatio:1,offset:0};a.geometryType=x.WGLGeometryType.LINE;
return a}v._inheritsLoose(l,n);var g=l.prototype;g.writeGeometry=function(a,b,h,d){this._writeGeometry(a,b,h,d)};g._initializeTessellator=function(a){var b=q.LineMaterialKey.load(this._materialKey);const h=q.FillMaterialKey.load(this._materialKey);var d=this._tessellationOptions;b=b.vvSizeFieldStops||b.vvSizeMinMaxValue||b.vvSizeScaleStops||b.vvSizeUnitValue;a=this.tessellationProperties._halfWidth<w.THIN_LINE_HALF_WIDTH_THRESHOLD&&!a&&!b;this.tessellationProperties.minMaxZoom=this._minMaxZoom;d.wrapDistance=
65535;d.textured=this._isDashed||this._hasPattern;d.offset=this.tessellationProperties.offset;d.halfWidth=this.tessellationProperties._halfWidth;d=a?0:1;this._lineTessellator=new y.LineTessellation((h.outlinedFill?B:A)(this.tessellationProperties,d,d),C(this.tessellationProperties),a)};g._write=function(a,b,h){const d="esriGeometryPoint"===b.geometryType;a.recordStart(b.getDisplayId(),this._materialKey,this.geometryType,d);this._writeGeometry(a,b,h,d);a.recordEnd()};g._writeGeometry=function(a,b,
h,d){h=null!=h?h:b.readLegacyGeometryForDisplay();d=this._getLines(h,d);r.isNone(d)||this._writeVertices(a,b,d)};g._getLines=function(a,b){if(r.isNone(a))return null;a=a.paths||a.rings;return r.isNone(a)?null:z.clipLinesMarshall(a,b?256:16)};g._writeVertices=function(a,b,h){const d=b.getDisplayId(),e=a.vertexCount(),k=this.tessellationProperties;b=this._tessellationOptions;k.out=a;k.id=d;k.indexCount=0;k.vertexCount=0;k.offset=e;b.capType=this._capType;b.joinType=this._joinType;a=q.FillMaterialKey.load(this._materialKey);
this.tessellationProperties.key=a.outlinedFill?a:q.LineMaterialKey.load(this._materialKey);for(const {line:f,start:p}of h)b.initialDistance=p%65535,this._lineTessellator.tessellate(f,b)};return l}(c)});