// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/maybe ../../../../../../core/screenUtils ../../../../../../layers/graphics/featureConversionUtils ../../../../../../symbols/cim/placements/CIMMarkerPlacementHelper ../../definitions ../../enums ../../number ../../materialKey/MaterialKey ./shapingUtils".split(" "),function(v,l,w,p,x,y,z,m,q,A){return B=>function(r){function n(...a){a=r.call(this,...a)||this;a._isCIM=!1;a._vertexBoundsScale=1;a.geometryType=z.WGLGeometryType.TEXT;
a._aux=m.i8888to32(0,0,a._referenceSize,a._bitset);return a}v._inheritsLoose(n,r);var k=n.prototype;k.bindTextInfo=function(a,c){this._shapingInfo=a&&a.length?l.andThen(a,d=>A.shapeGlyphs(d,c,{scale:this._scale,angle:this._angle,xOffset:this._xOffset,yOffset:this._yOffset,hAlign:this._xAlignD,vAlign:this._yAlignD,maxLineWidth:Math.max(32,Math.min(this._lineWidth,512)),lineHeight:y.MAGIC_LABEL_LINE_HEIGHT*Math.max(.25,Math.min(this._lineHeight,4)),decoration:this._decoration,isCIM:this._isCIM})):null};
k._write=function(a,c,d){const b=c.getDisplayId();this._writeGeometry(a,c,b,d)};k._writeGeometry=function(a,c,d,b){const f=this._shapingInfo;if(!l.isNone(f)){if(l.isSome(this._textPlacement))return c=null!=b?b:c.readLegacyGeometryForDisplay(),this._writePlacedText(a,d,c,f);c=b?p.deltaDecodeGeometry(p.convertFromGeometry(b),2):"esriGeometryPolygon"===c.geometryType?c.readCentroid():c.readGeometryForDisplay();if(!l.isNone(c)){if(c.isPoint){const [e,g]=c.coords;return!a.hasAggregates&&a.hasPixelBufferEnabled&&
(0>e||512<=e||0>g||512<=g)?void 0:this._writeGlyphs(a,d,{x:e,y:g},f)}c.forEachVertex((e,g)=>this._writeGlyphs(a,d,{x:e,y:g},f))}}};k._writePlacedText=function(a,c,d,b){var f=l.unwrap(this._textPlacement);if(d=x.CIMMarkerPlacementHelper.getPlacement(d,f,w.pt2px(1)))for(var e=d.next();null!=e;){f=e.getAngle();b.setRotation(f);const g=e.tx;e=e.ty;0>g||512<=g||0>e||512<=e||(this._writeGlyphs(a,c,{x:g,y:e},b),b.setRotation(-f));e=d.next()}};k._writeGlyphs=function(a,c,d,b){const f=q.MaterialKeyBase.load(this._materialKey),
e=m.i1616to32(Math.round(8*d.x),Math.round(8*d.y)),g=this._vertexBoundsScale,h=b.bounds,t=2*Math.max(h.width,h.height);for(const u of b.glyphs)f.textureBinding=u.textureBinding,a.recordStart(c,f.data,this.geometryType,!0),a.vertexBounds(d.x+h.x+this._xOffset,d.y+h.y-this._yOffset,t*g,t*g),this._writeVertices(a,c,e,u),a.recordEnd()};k._writeGlyph=function(a,c,d,b,f){var e=q.MaterialKeyBase.load(this._materialKey);const g=m.i1616to32(Math.round(8*d),Math.round(8*b));e.textureBinding=f.textureBinding;
a.recordStart(c,e.data,this.geometryType,!0);e=f.bounds;const h=this._vertexBoundsScale;a.vertexBounds(d+e.x*h,b+e.y*h,e.width*h,e.height*h);this._writeVertices(a,c,g,f);a.recordEnd()};k._writeVertices=function(a,c,d,b){const f=a.vertexCount();this._writeVertexCommon(a,c,d,b);a.vertexWrite(b.offsets.upperLeft);a.vertexWrite(b.texcoords.upperLeft);a.vertexEnd();this._writeVertexCommon(a,c,d,b);a.vertexWrite(b.offsets.upperRight);a.vertexWrite(b.texcoords.upperRight);a.vertexEnd();this._writeVertexCommon(a,
c,d,b);a.vertexWrite(b.offsets.lowerLeft);a.vertexWrite(b.texcoords.lowerLeft);a.vertexEnd();this._writeVertexCommon(a,c,d,b);a.vertexWrite(b.offsets.lowerRight);a.vertexWrite(b.texcoords.lowerRight);a.vertexEnd();a.indexWrite(f+0);a.indexWrite(f+1);a.indexWrite(f+2);a.indexWrite(f+1);a.indexWrite(f+3);a.indexWrite(f+2)};k._writeVertexCommon=function(a,c,d,b){b=this._color;const f=this._haloColor,e=m.i8888to32(0,0,this._referenceSize,this._bitset),g=m.i8888to32(0,0,this._size,this._haloSize);a.vertexWrite(d);
a.vertexWrite(c);a.vertexWrite(b);a.vertexWrite(f);a.vertexWrite(g);a.vertexWrite(e);a.vertexWrite(this._minMaxZoom)};return n}(B)});