// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/maybe ../../../../../../core/screenUtils ../../../../../../chunks/mat2df32 ../../../../../../chunks/vec2f32 ../../color ../../definitions ../../number ../../materialKey/MaterialKey ./util ./WGLBaseMarkerTemplate ./WGLMeshTemplate".split(" "),function(F,G,m,H,I,w,p,t,J,u,K,L){return function(E){function q(a,b,l,e,h,d,k,f,n,y,z,A,B,C,g,D,x,v,r,M,N,O,P){var c=E.call(this)||this;c.angle=e;c.height=k;c.width=d;c.xOffset=
b*r;c.yOffset=l*r;c._markerPlacement=M;c._effects=N;c._anchorX=.5-(.5+D)*g.width/g.width;c._anchorY=.5-(.5+x)*g.height/g.height;c._minMaxZoom=t.i1616to32(Math.round(O*p.MIN_MAX_ZOOM_PRECISION_FACTOR),Math.round(P*p.MIN_MAX_ZOOM_PRECISION_FACTOR));b=(1===C?p.BITSET_MARKER_ALIGNMENT_MAP:p.BITSET_MARKER_ALIGNMENT_SCREEN)|(z?p.BITSET_GENERIC_LOCK_COLOR:0)|(B?p.BITSET_MARKER_OUTLINE_ALLOW_COLOR_OVERRIDE:0)|(A?p.BITSET_MARKER_SCALE_SYMBOLS_PROPORTIONALLY:0);l=g&&g.sdf;a=J.MarkerMaterialKey.load(a);a.sdf=
l;a.pattern=!0;a.textureBinding=g.textureBinding;c._materialKey=a.data;c._fillColor=h;c._outlineColor=n;c._sizeOutlineWidth=t.i8888to32(Math.round(Math.min(Math.sqrt(128*d),255)),Math.round(Math.min(Math.sqrt(128*k),255)),Math.round(Math.min(Math.sqrt(128*y),255)),Math.round(Math.min(Math.sqrt(128*f),255)));h=g.rect.x+p.SPRITE_PADDING;f=g.rect.y+p.SPRITE_PADDING;n=h+g.width;g=f+g.height;c._offsets.xUpperLeft=h;c._offsets.yUpperLeft=f;c._offsets.xUpperRight=n;c._offsets.yUpperRight=f;c._offsets.xBottomLeft=
h;c._offsets.yBottomLeft=g;c._offsets.xBottomRight=n;c._offsets.yBottomRight=g;c._texUpperLeft=t.i1616to32(h,f);c._texUpperRight=t.i1616to32(n,f);c._texBottomLeft=t.i1616to32(h,g);c._texBottomRight=t.i1616to32(n,g);d=d*v*r;k=k*v*r;c._bitestAndDistRatio=t.i1616to32(b,Math.round(64*v));c._computedWidth=d;c._computedHeight=k;d=I.create();k=H.create();c._applyTransformation(k,d);return c}F._inheritsLoose(q,E);q.fromCIMMarker=function(a,b,l){const e=a.size,h=(b&&b.width||1)/(b&&b.height||1)*a.scaleX;var d=
a.scaleSymbolsProportionally&&a.frameHeight?e/a.frameHeight:1;let k=w.premultiplyAlphaRGBA(a.color);const f=w.premultiplyAlphaRGBA(a.outlineColor),n=m.pt2px(e),y=n*h,z=m.pt2px(a.offsetX||0),A=m.pt2px(a.offsetY||0);d*=m.pt2px(a.outlineWidth||0);const B=a.alignment||0,C=m.pt2px(a.referenceSize),[g,D]=u.getMinMaxZoom(a.scaleInfo,l);b.sdf||0!==k||(k=-1);l=a.rotation||0;a.rotateClockwise||(l=-l);let x=0,v=0;const r=a.anchorPoint;r&&(a.isAbsoluteAnchorPoint?e&&(x=-r.x/(e*h),v=r.y/e):(x=r.x,v=r.y));b=new q(a.materialKey,
z,A,l,k,y,n,C,f,d,a.colorLocked,a.scaleSymbolsProportionally,!1,B,b,x,v,a.sizeRatio,G.unwrapOr(a.scaleFactor,1),a.markerPlacement,a.effects,g,D);b._vertexBoundsScaleX=a.maxVVSize?a.maxVVSize/y:1;b._vertexBoundsScaleY=a.maxVVSize?a.maxVVSize/n:1;return b};q.fromPictureMarker=function(a,b){const l=Math.round(m.pt2px(a.width)),e=Math.round(m.pt2px(a.height)),h=p.PICTURE_FILL_COLOR,d=Math.round(m.pt2px(a.xoffset||0)),k=Math.round(m.pt2px(a.yoffset||0));b=new q(a.materialKey,d,k,a.angle,h,l,e,e,0,0,!1,
!1,!1,0,b,0,0,1,1,null,null,u.DEFAULT_MIN_ZOOM,u.DEFAULT_MAX_ZOOM);b._vertexBoundsScaleX=a.maxVVSize?a.maxVVSize/a.width:1;b._vertexBoundsScaleY=a.maxVVSize?a.maxVVSize/a.height:1;return b};q.fromSimpleMarker=function(a,b){const l=w.premultiplyAlphaRGBAArray(a.color),e=Math.round(m.pt2px(a.size)),h=Math.round(m.pt2px(a.xoffset||0)),d=Math.round(m.pt2px(a.yoffset||0)),k=a.style;var f=a.outline;const n=(f&&f.color&&w.premultiplyAlphaRGBAArray(f.color))|0;f=(f&&f.width&&Math.round(m.pt2px(f.width)))|
0;b=new q(a.materialKey,h,d,a.angle,l,e,e,e,n,f,!1,!1,"esriSMSCross"===k||"esriSMSX"===k,0,b,0,0,1.96875,1,null,null,u.DEFAULT_MIN_ZOOM,u.DEFAULT_MAX_ZOOM);b.boundsType="esriSMSCircle"===k?"circle":"square";b._vertexBoundsScaleX=a.maxVVSize?a.maxVVSize/a.size:1;b._vertexBoundsScaleY=a.maxVVSize?a.maxVVSize/a.size:1;return b};q.fromLineSymbolMarker=function(a,b){const l=w.premultiplyAlphaRGBAArray(a.color),e=Math.round(m.pt2px(6*a.lineWidth)),h="cross"===a.style||"x"===a.style;switch(a.placement){case "begin-end":var d=
"Both";break;case "begin":d="JustBegin";break;case "end":d="JustEnd";break;default:d="None"}d={type:"CIMMarkerPlacementAtExtremities",angleToLine:!0,offset:0,extremityPlacement:d,offsetAlongLine:0};b=new q(a.materialKey,0,0,0,l,e,e,e/6,l,h?Math.round(m.pt2px(a.lineWidth)):0,!1,!1,h,1,b,0,0,1.96875,1,d,null,u.DEFAULT_MIN_ZOOM,u.DEFAULT_MAX_ZOOM);b.boundsType="circle"===a.style?"circle":"square";return b};return q}(K(L))});