// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/Error ../../../../../../core/Logger ../../../../../../core/promiseUtils ../../../../../../symbols/support/defaultsJSON ../../enums ../../materialKey/MaterialKey ./WGLDynamicFillTemplate ./WGLDynamicLineTemplate ./WGLDynamicMarkerTemplate ./WGLDynamicTextTemplate ./WGLFillTemplate ./WGLLineTemplate ./WGLMarkerTemplate ./WGLTextTemplate ../../util/Lock ../../util/Result ../../../../layers/features/textUtils ../../../../layers/support/cimSymbolUtils".split(" "),
function(n,g,F,q,G,l,u,v,H,I,J,K,w,x,r,y,z,k,L,t){function m(h,e){const b=h.length;h.push(null);e.then(a=>h[b]=a);return h}function A(h){return!!(h&1)}const f=q.getLogger("esri.views.2d.engine.webgl.mesh.templates.WGLTemplateStore"),B=[];q={isOutline:!1,isOutlinedFill:!1,placement:null,stride:{fill:"default"},vvFlags:0};const C={...l.errorPointSymbolJSON,hash:JSON.stringify(l.errorPointSymbolJSON),materialKey:v.createMaterialKey(u.WGLGeometryType.MARKER,q)},D={...l.errorPolylineSymbolJSON,hash:JSON.stringify(l.errorPolylineSymbolJSON),
materialKey:v.createMaterialKey(u.WGLGeometryType.LINE,q)},E={...l.errorPolygonSymbolJSON,hash:JSON.stringify(l.errorPolygonSymbolJSON),materialKey:v.createMaterialKey(u.WGLGeometryType.FILL,q)};l=function(){function h(b,a){this._templateIdCounter=this._idCounter=1;this._idToTemplateGroup=new Map;this._symbolToTemplate=new Map;this._fetchQueue=[];this._idToResolver=new Map;this._cimTemplateCache=new Map;this._cimAnalyses=[];this._lock=new z.default;this._fetchResource=b;this._tileInfo=a}var e=h.prototype;
e.createTemplateGroup=function(b,a){this._initErrorTemplates();const c=b.hash;if(this._symbolToTemplate.has(c))return this._symbolToTemplate.get(c);const d=[];a&&this._createMeshTemplates(d,a,!0);this._createMeshTemplates(d,b,!1);b=this._createGroupId("expanded-cim"===b.type&&M(b));this._idToTemplateGroup.set(b,d);this._symbolToTemplate.set(c,b);return b};e.getTemplateGroup=function(b){return this._idToTemplateGroup.has(b)?this._idToTemplateGroup.get(b):B};e.getDynamicTemplateGroup=function(b){if(!this._idToTemplateGroup.has(b))return B;
A(b)||f.error("mapview-template-store",`Id ${b} does not refer to a dynamic template`);return this._idToTemplateGroup.get(b)};e.getMosaicItem=function(b,a){const c=this._createTemplateId(),d=new Promise(p=>this._idToResolver.set(c,p));this._fetchQueue.push({symbol:b,id:c,glyphIds:a});return d};e.finalize=function(b){return this._fetchQueue.length||this._lock.isHeld()?z.withLock(this._lock,this._fetchAllQueuedResources.bind(this),b):Promise.resolve()};e._initErrorTemplates=function(){this._errorTemplates||
(this._errorTemplates={fill:this._createMeshTemplates([],E,!1),marker:this._createMeshTemplates([],C,!1),line:this._createMeshTemplates([],D,!1)})};e._fetchAllQueuedResources=function(b){if(!this._fetchQueue.length)return Promise.resolve();const a=this._fetchQueue,c=this._cimAnalyses;this._fetchQueue=[];this._cimAnalyses=[];return Promise.all(c).then(()=>this._fetchResource(a,b).then(d=>{for(const {id:p,mosaicItem:N}of d)this._idToResolver.get(p)(N),this._idToResolver.delete(p)})).catch(d=>{G.isAbortError(d)?
this._fetchQueue=this._fetchQueue.concat(a):"worker:port-closed"!==d.name&&f.error(new F("mapview-template-store","Unable to fetch requested texture resources",d))})};e._createGroupId=function(b){return this._idCounter++<<1|(b?1:0)};e._createTemplateId=function(){return this._templateIdCounter++};e._createSMS=function(){var b=g._asyncToGenerator(function*(a){const {spriteMosaicItem:c}=yield this.getMosaicItem(a);return k.ok(c,f)?r.fromSimpleMarker(a,c):this._markerError});return function(a){return b.apply(this,
arguments)}}();e._createPMS=function(){var b=g._asyncToGenerator(function*(a){const {spriteMosaicItem:c}=yield this.getMosaicItem(a);return k.ok(c,f)?r.fromPictureMarker(a,c):this._markerError});return function(a){return b.apply(this,arguments)}}();e._createSFS=function(){var b=g._asyncToGenerator(function*(a,c){const {spriteMosaicItem:d}=yield this.getMosaicItem(a);return k.ok(d,f)?w.fromSimpleFill(a,d,c):this._fillError});return function(a,c){return b.apply(this,arguments)}}();e._createPFS=function(){var b=
g._asyncToGenerator(function*(a,c){const {spriteMosaicItem:d}=yield this.getMosaicItem(a);return k.ok(d,f)?w.fromPictureFill(a,d,c):this._fillError});return function(a,c){return b.apply(this,arguments)}}();e._createSLS=function(){var b=g._asyncToGenerator(function*(a,c){({spriteMosaicItem:c}=yield this.getMosaicItem(a));return k.ok(c,f)?x.fromSimpleLine(a,c):this._lineError});return function(a,c){return b.apply(this,arguments)}}();e._createLMS=function(){var b=g._asyncToGenerator(function*(a){const {spriteMosaicItem:c}=
yield this.getMosaicItem(a);return k.ok(c,f)?r.fromLineSymbolMarker(a,c):this._markerError});return function(a){return b.apply(this,arguments)}}();e._createTS=function(){var b=g._asyncToGenerator(function*(a){const {glyphMosaicItems:c}=yield this.getMosaicItem(a);return y.fromText(a,c)});return function(a){return b.apply(this,arguments)}}();e._createCIMText=function(){var b=g._asyncToGenerator(function*(a){const {glyphMosaicItems:c}=yield this.getMosaicItem(t.cimLayerToRasterizationInfo(a),L.codepoints(a.text));
return k.ok(c,f)?y.fromCIMText(a,c,this._tileInfo):this._textError});return function(a){return b.apply(this,arguments)}}();e._createCIMFill=function(){var b=g._asyncToGenerator(function*(a){const {spriteMosaicItem:c}=yield this.getMosaicItem(t.cimLayerToRasterizationInfo(a));return k.ok(c,f)?w.fromCIMFill(a,c,this._tileInfo):this._fillError});return function(a){return b.apply(this,arguments)}}();e._createCIMLine=function(){var b=g._asyncToGenerator(function*(a){const {spriteMosaicItem:c}=yield this.getMosaicItem(t.cimLayerToRasterizationInfo(a));
return k.ok(c,f)?x.fromCIMLine(a,c,this._tileInfo):this._lineError});return function(a){return b.apply(this,arguments)}}();e._createCIMMarker=function(){var b=g._asyncToGenerator(function*(a){const {spriteMosaicItem:c}=yield this.getMosaicItem(t.cimLayerToRasterizationInfo(a));return k.ok(c,f)?r.fromCIMMarker(a,c,this._tileInfo):this._markerError});return function(a){return b.apply(this,arguments)}}();e._createCIM=function(){var b=g._asyncToGenerator(function*(a){const c=a.templateHash;if(this._cimTemplateCache.has(c))return this._cimTemplateCache.get(c);
let d;switch(a.type){case "marker":d=this._createCIMMarker(a);break;case "line":d=this._createCIMLine(a);break;case "fill":d=this._createCIMFill(a);break;case "text":d=this._createCIMText(a)}d.then(p=>this._cimTemplateCache.set(c,p));return d});return function(a){return b.apply(this,arguments)}}();e._createDynamicCIM=function(b){const a=b.templateHash;if(this._cimTemplateCache.has(a))return this._cimTemplateCache.get(a);let c;switch(b.type){case "marker":c=J.fromCIMMarker(b,this._tileInfo);break;
case "line":c=I.fromCIMLine(b,this._tileInfo);break;case "fill":c=H.fromCIMFill(b,this._tileInfo);break;case "text":c=K.fromCIMText(b,this._tileInfo)}this._cimTemplateCache.set(a,c);return c};e._createPrimitiveMeshTemplates=function(b,a,c){switch(a.type){case "esriSMS":return m(b,this._createSMS(a));case "esriPMS":return m(b,this._createPMS(a));case "esriSFS":return m(b,this._createSFS(a,c));case "line-marker":return m(b,this._createLMS(a));case "esriPFS":return m(b,this._createPFS(a,c));case "esriSLS":return m(b,
this._createSLS(a,!1));case "esriTS":return m(b,this._createTS(a));default:return f.error("Unable to create mesh template for unknown symbol type {: $ }{symbol.type}"),b}};e._createMeshTemplates=function(b,a,c){if(-1!==a.type.indexOf("3d"))return f.error("3D symbols are not supported with MapView"),b;if("expanded-cim"===a.type){for(const d of a.layers)"function"===typeof d.materialHash?b.push(this._createDynamicCIM(d)):m(b,this._createCIM(d));return b}if("composite-symbol"===a.type){for(const d of a.layers)this._createPrimitiveMeshTemplates(b,
d,c);return b}return"cim"===a.type||"label"===a.type||"web-style"===a.type?b:this._createPrimitiveMeshTemplates(b,a,c)};g._createClass(h,[{key:"_markerError",get:function(){return this._errorTemplates.marker[0]}},{key:"_fillError",get:function(){return this._errorTemplates.fill[0]}},{key:"_lineError",get:function(){return this._errorTemplates.line[0]}},{key:"_textError",get:function(){return this._errorTemplates.line[0]}}]);return h}();const M=h=>{if(!h.layers)return!1;for(const e of h.layers)if("function"===
typeof e.materialHash)return!0;return!1};n.WGLTemplateStore=l;n.errorPointSchema2D=C;n.errorPolygonSchema2D=E;n.errorPolylineSchema2D=D;n.isDynamicId=A;Object.defineProperty(n,"__esModule",{value:!0})});