// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../core/BidiText ../../core/Logger ../../core/maybe ../../core/ObjectPool ../../core/screenUtils ../../geometry/support/aaBoundingRect ../../geometry/support/boundsUtils ../../geometry/support/jsonUtils ./CIMEffects ./CIMOperators ./CIMPlacements ./CIMResourceManager ./Rect ./TextRasterizer ../../views/2d/engine/webgl/alignmentUtils ../../views/2d/engine/webgl/definitions ../../views/2d/engine/webgl/mesh/templates/shapingUtils".split(" "),
function(r,B,K,w,A,L,M,C,N,n,O,D,P,Q,R,E,u,F,S){const t=Math.PI/180,T=w.getLogger("esri.symbols.cim.CIMSymbolDrawHelper");let v=function(){function l(b){this._t=b}l.createIdentity=function(){return new l([1,0,0,0,1,0])};var k=l.prototype;k.clone=function(){return new l(this._t.slice())};k.transform=function(b){const a=this._t;return[a[0]*b[0]+a[1]*b[1]+a[2],a[3]*b[0]+a[4]*b[1]+a[5]]};l.createScale=function(b,a){return new l([b,0,0,0,a,0])};k.scale=function(b,a){const c=this._t;c[0]*=b;c[1]*=b;c[2]*=
b;c[3]*=a;c[4]*=a;c[5]*=a;return this};k.scaleRatio=function(){return Math.sqrt(this._t[0]*this._t[0]+this._t[1]*this._t[1])};l.createTranslate=function(b,a){return new l([0,0,b,0,0,a])};k.translate=function(b,a){const c=this._t;c[2]+=b;c[5]+=a;return this};l.createRotate=function(b){const a=Math.cos(b);b=Math.sin(b);return new l([a,-b,0,b,a,0])};k.rotate=function(b){return l.multiply(this,l.createRotate(b),this)};l.multiply=function(b,a,c){b=b._t;a=a._t;const d=b[1]*a[0]+b[4]*a[1],e=b[2]*a[0]+b[5]*
a[1]+a[2],f=b[0]*a[3]+b[3]*a[4],g=b[1]*a[3]+b[4]*a[4],h=b[2]*a[3]+b[5]*a[4]+a[5],m=c._t;m[0]=b[0]*a[0]+b[3]*a[1];m[1]=d;m[2]=e;m[3]=f;m[4]=g;m[5]=h;return c};k.invert=function(){const b=this._t;let a=b[0]*b[4]-b[1]*b[3];if(0===a)return new l([0,0,0,0,0,0]);a=1/a;return new l([b[4]*a,-b[1]*a,(b[1]*b[5]-b[2]*b[4])*a,-b[3]*a,b[0]*a,(b[2]*b[3]-b[0]*b[5])*a])};return l}();w=function(){function l(b,a){this._transfos=[];this._sizeTransfos=[];this._geomUnitsPerPoint=1;this._flippedYs=!1;this._placementPool=
new L(P.Placement,null,null,100);this._earlyReturn=!1;this._mapRotation=0;this._resourceManager=b||new Q;this._transfos.push(a||v.createIdentity());this._sizeTransfos.push(a?a.scaleRatio():1)}var k=l.prototype;k.setTransform=function(b,a){this._transfos=[b||v.createIdentity()];this._sizeTransfos=[a?a:b?b.scaleRatio():1]};k.setGeomUnitsPerPoint=function(b){this._geomUnitsPerPoint=b};k.setFlippedYs=function(b){this._flippedYs=b};k.transformPt=function(b){return this._transfos[this._transfos.length-
1].transform(b)};k.transformSize=function(b){return b*this._sizeTransfos[this._sizeTransfos.length-1]};k.reverseTransformPt=function(b){return this._transfos[this._transfos.length-1].invert().transform(b)};k.reverseTransformSize=function(b){return b/this._sizeTransfos[this._sizeTransfos.length-1]};k.geomUnitsPerPoint=function(){return this.isEmbedded()?1:this._geomUnitsPerPoint};k.flippedYs=function(){return this.isEmbedded()?!1:this._flippedYs};k.isEmbedded=function(){return 1<this._transfos.length};
k.back=function(){return this._transfos[this._transfos.length-1]};k.push=function(b,a){a=a?b.scaleRatio():1;v.multiply(b,this.back(),b);this._transfos.push(b);this._sizeTransfos.push(this._sizeTransfos[this._sizeTransfos.length-1]*a)};k.pop=function(){this._transfos.splice(-1,1);this._sizeTransfos.splice(-1,1)};k.drawSymbol=function(b,a){if(b)switch(b.type){case "CIMPointSymbol":case "CIMLineSymbol":case "CIMPolygonSymbol":this.drawMultiLayerSymbol(b,a);break;case "CIMTextSymbol":this.drawTextSymbol(b,
a)}};k.drawMultiLayerSymbol=function(b,a){if(b){var c=b.symbolLayers;if(c)if((b=b.effects)&&0<b.length){if(a=this.executeEffects(b,a))for(b=a.next();b;)this.drawSymbolLayers(c,b),b=a.next()}else this.drawSymbolLayers(c,a)}};k.executeEffects=function(b,a){a=new O.SimpleGeometryCursor(a);for(const c of b)(b=D.getEffectOperator(c))&&(a=b.execute(a,c,this.geomUnitsPerPoint(),this.flippedYs()));return a};k.drawSymbolLayers=function(b,a){let c=b.length;for(;c--;){const e=b[c];if(e&&!1!==e.enable){var d=
e.effects;if(d&&0<d.length){if(d=this.executeEffects(d,a)){let f=null;for(;(f=d.next())&&(this.drawSymbolLayer(e,f),!this._earlyReturn););}}else this.drawSymbolLayer(e,a);if(this._earlyReturn)break}}};k.drawSymbolLayer=function(b,a){switch(b.type){case "CIMSolidFill":this.drawSolidFill(a,b.color);break;case "CIMHatchFill":this.drawHatchFill(a,b);break;case "CIMPictureFill":this.drawPictureFill(a,b);break;case "CIMGradientFill":this.drawGradientFill(a,b);break;case "CIMSolidStroke":this.drawSolidStroke(a,
b.color,b.width,b.capStyle,b.joinStyle,b.miterLimit);break;case "CIMPictureStroke":this.drawPictureStroke(a,b);break;case "CIMGradientStroke":this.drawGradientStroke(a,b);break;case "CIMCharacterMarker":case "CIMPictureMarker":case "CIMVectorMarker":this.drawMarkerLayer(b,a)}};k.drawHatchFill=function(b,a){const c=this._buildHatchPolyline(a,b,this.geomUnitsPerPoint());c&&(this.pushClipPath(b),this.drawMultiLayerSymbol(a.lineSymbol,c),this.popClipPath())};k.drawPictureFill=function(b,a){};k.drawGradientFill=
function(b,a){};k.drawPictureStroke=function(b,a){};k.drawGradientStroke=function(b,a){};k.drawMarkerLayer=function(b,a){var c=b.markerPlacement;if(c){const e=D.getPlacementOperator(c);if(e){var d="CIMMarkerPlacementInsidePolygon"===c.type;d&&this.pushClipPath(a);if(a=e.execute(a,c,this.geomUnitsPerPoint()))for(c=null;(c=a.next())&&(this.drawMarker(b,c),!this._earlyReturn););d&&this.popClipPath()}}else{c=this._placementPool.acquire();if(n.isPoint(a))c.tx=a.x,c.ty=a.y,this.drawMarker(b,c);else for(d of a.points)if(c.tx=
d[0],c.ty=d[1],this.drawMarker(b,c),this._earlyReturn)break;this._placementPool.release(c)}};k.drawMarker=function(b,a){switch(b.type){case "CIMCharacterMarker":case "CIMPictureMarker":this.drawPictureMarker(b,a);break;case "CIMVectorMarker":this.drawVectorMarker(b,a)}};k.drawPictureMarker=function(b,a){var c,d,e,f,g;if(b){var h=this._resourceManager.getResource(b.url),m=null!=(c=b.size)?c:10;if(!(A.isNone(h)||0>=m)&&(c=h.width,h=h.height,c&&h)){h=c/h;c=null!=(d=b.scaleX)?d:1;d=v.createIdentity();
var q=b.anchorPoint;if(q){let p=q.x;q=q.y;"Absolute"!==b.anchorPointUnits&&(p*=m*h*c,q*=m);d.translate(-p,-q)}h=null!=(e=b.rotation)?e:0;b.rotateClockwise&&(h=-h);this._mapRotation&&(h+=this._mapRotation);h&&d.rotate(h*t);e=null!=(f=b.offsetX)?f:0;f=null!=(g=b.offsetY)?g:0;if(e||f)this._mapRotation&&(h=t*this._mapRotation,g=Math.cos(h),h=Math.sin(h),c=e*h+f*g,e=e*g-f*h,f=c),d.translate(e,f);g=this.geomUnitsPerPoint();1!==g&&d.scale(g,g);(g=a.getAngle())&&d.rotate(g);d.translate(a.tx,a.ty);this.push(d,
!1);this.drawImage(b.url,m,b.scaleX);this.pop()}}};k.drawVectorMarker=function(b,a){var c,d,e,f;if(b){var g=b.markerGraphics;if(g){var h=null!=(c=b.size)?c:10,m=(c=b.frame)?c.ymax-c.ymin:0;m=h&&m?h/m:1;h=v.createIdentity();c&&h.translate(.5*-(c.xmax+c.xmin),.5*-(c.ymax+c.ymin));var q=b.anchorPoint;if(q){let p=q.x;q=q.y;"Absolute"!==b.anchorPointUnits?c&&(p*=c.xmax-c.xmin,q*=c.ymax-c.ymin):(p/=m,q/=m);h.translate(-p,-q)}1!==m&&h.scale(m,m);c=null!=(d=b.rotation)?d:0;b.rotateClockwise&&(c=-c);this._mapRotation&&
(c+=this._mapRotation);c&&h.rotate(c*t);d=null!=(e=b.offsetX)?e:0;e=null!=(f=b.offsetY)?f:0;if(d||e)this._mapRotation&&(c=t*this._mapRotation,f=Math.cos(c),c=Math.sin(c),m=d*c+e*f,d=d*f-e*c,e=m),h.translate(d,e);f=this.geomUnitsPerPoint();1!==f&&h.scale(f,f);(f=a.getAngle())&&h.rotate(f);h.translate(a.tx,a.ty);this.push(h,b.scaleSymbolsProportionally);for(const p of g)if(p&&p.symbol&&p.geometry||T.error("Invalid marker graphic",p),this.drawSymbol(p.symbol,p.geometry),this._earlyReturn)break;this.pop()}}};
k.drawTextSymbol=function(b,a){var c,d,e,f;if(b&&n.isPoint(a)&&!(0>=(null!=(c=b.height)?c:10))){c=v.createIdentity();var g=null!=(d=b.angle)?d:0;(g=-g)&&c.rotate(g*t);d=null!=(e=b.offsetX)?e:0;e=null!=(f=b.offsetY)?f:0;(d||e)&&c.translate(d,e);f=this.geomUnitsPerPoint();1!==f&&c.scale(f,f);c.translate(a.x,a.y);this.push(c,!1);this.drawText(b);this.pop()}};k._buildHatchPolyline=function(b,a,c){var d=(void 0!==b.separation?b.separation:4)*c,e=void 0!==b.rotation?b.rotation:0;if(0===d)return null;0>
d&&(d=-d);for(var f=0,g=.5*d;f>g;)f-=d;for(;f<-g;)f+=d;f=C.create();N.getBoundsXY(f,a);f[0]-=g;f[1]-=g;f[2]+=g;f[3]+=g;for(var h=[[f[0],f[1]],[f[0],f[3]],[f[2],f[3]],[f[2],f[1]]];180<e;)e-=180;for(;0>e;)e+=180;g=Math.cos(e*t);var m=Math.sin(e*t);e=-d*m;a=d*g;f=(void 0!==b.offsetX?b.offsetX*c:0)*m-(void 0!==b.offsetY?b.offsetY*c:0)*g;let q;var p=b=Number.MAX_VALUE;q=c=-Number.MAX_VALUE;for(var x of h){var y=x[0];const G=x[1];h=g*y+m*G;y=-m*y+g*G;p=Math.min(p,h);b=Math.min(b,y);q=Math.max(q,h);c=Math.max(c,
y)}b=Math.floor(b/d)*d;x=g*p-m*b-e*f/d;p=m*p+g*b-a*f/d;h=g*q-m*b-e*f/d;f=m*q+g*b-a*f/d;d=1+Math.round((c-b)/d);g=[];for(m=0;m<d;m++)x+=e,p+=a,h+=e,f+=a,g.push([[x,p],[h,f]]);return{paths:g}};return l}();let U=function(l){function k(a,c){a=l.call(this,a,c)||this;a.reset();return a}B._inheritsLoose(k,l);var b=k.prototype;b.reset=function(){this._xmin=this._ymin=Infinity;this._xmax=this._ymax=-Infinity;this._clipCount=0};b.envelope=function(){return new R(this._xmin,this._ymin,this._xmax-this._xmin,
this._ymax-this._ymin)};b.bounds=function(){return C.fromValues(this._xmin,this._ymin,this._xmax,this._ymax)};b.drawSolidFill=function(a){!a||0<this._clipCount||(n.isPolygon(a)?this._processPath(a.rings,0):n.isPolyline(a)?this._processPath(a.paths,0):n.isExtent(a)?(a=z(a))&&this._processPath(a.rings,0):console.error("drawSolidFill Unexpected geometry type!"))};b.drawSolidStroke=function(a,c,d){!a||0<this._clipCount||(c=.5*this.transformSize(d),n.isPolygon(a)?this._processPath(a.rings,c):n.isPolyline(a)?
this._processPath(a.paths,c):n.isExtent(a)?(a=z(a))&&this._processPath(a.rings,c):console.error("drawSolidStroke unexpected geometry type!"))};b.pushClipPath=function(a){this.drawSolidFill(a);++this._clipCount};b.popClipPath=function(){--this._clipCount};b.drawImage=function(a,c,d){let e=d*c,f=c;a=this._resourceManager.getResource(a);!c&&A.isSome(a)&&(e=d*a.width,f=a.height);this._merge(this.transformPt([-e/2,-f/2]),0);this._merge(this.transformPt([-e/2,f/2]),0);this._merge(this.transformPt([e/2,
-f/2]),0);this._merge(this.transformPt([e/2,f/2]),0)};b.drawText=function(a){this._textRasterizer||(this._textRasterizer=new E.TextRasterizer)};b._processPath=function(a,c){if(a)for(const d of a)if(a=d?d.length:0,1<a){this._merge(this.transformPt(d[0]),c);for(let e=1;e<a;++e)this._merge(this.transformPt(d[e]),c)}};b._merge=function(a,c){a[0]-c<this._xmin&&(this._xmin=a[0]-c);a[0]+c>this._xmax&&(this._xmax=a[0]+c);a[1]-c<this._ymin&&(this._ymin=a[1]-c);a[1]+c>this._ymax&&(this._ymax=a[1]+c)};return k}(w),
V=function(l){function k(){var a=l.apply(this,arguments)||this;a._searchPoint=[0,0];a._searchDistPoint=0;return a}B._inheritsLoose(k,l);var b=k.prototype;b.hitTest=function(a,c,d,e,f,g){g*=M.pt2px(1);this.setTransform();this.setGeomUnitsPerPoint(g);this._searchPoint=[(a[0]+a[2])/2,(a[1]+a[3])/2];this._searchDistPoint=(a[2]-a[0])/2/g;this._textInfo=e;this._mapRotation=c&&("CIMPointSymbol"===c.type&&"Map"!==c.angleAlignment||"CIMTextSymbol"===c.type)?f:0;this._earlyReturn=!1;this.drawSymbol(c,d);return this._earlyReturn};
b.drawSolidFill=function(a,c){this._hitTestFill(a)};b.drawHatchFill=function(a,c){this._hitTestFill(a)};b.drawPictureFill=function(a,c){this._hitTestFill(a)};b.drawGradientFill=function(a,c){this._hitTestFill(a)};b.drawSolidStroke=function(a,c,d,e,f,g){this._hitTestStroke(a,d)};b.drawPictureStroke=function(a,c){this._hitTestStroke(a,c.width)};b.drawGradientStroke=function(a,c){this._hitTestStroke(a,c.width)};b.pushClipPath=function(a){};b.popClipPath=function(){};b.drawImage=function(a,c,d){a=this._resourceManager.getResource(a);
if(!A.isNone(a)&&0!==a.height&&0!==c){c*=this.geomUnitsPerPoint();d=a.width/a.height*d*c;a=this.reverseTransformPt(this._searchPoint);var e=this._searchDistPoint;Math.abs(a[0])<d/2+e&&Math.abs(a[1])<c/2+e&&(this._earlyReturn=!0)}};b.drawText=function(a){var c,d,e=this._textInfo;if(e&&(e=e.get(a))){var {text:f,mosaicItem:g}=e;if(g&&0!==g.glyphMosaicItems.length){e=null!=(c=a.height)?c:10;c=H(a.lineGapType,null!=(d=a.lineGap)?d:0,e);d=K.bidiText(f)[1];a=S.shapeGlyphs(g.glyphMosaicItems,d,{scale:e/F.GLYPH_SIZE,
angle:0,xOffset:0,yOffset:0,hAlign:I(a.horizontalAlignment),vAlign:J(a.verticalAlignment),maxLineWidth:512,lineHeight:F.MAGIC_LABEL_LINE_HEIGHT*Math.max(.25,Math.min(c||1,4)),decoration:a.font.decoration||"none",isCIM:!0});c=this.reverseTransformPt(this._searchPoint);d=c[0];c=c[1];for(const h of a.glyphs)if(d>h.xTopLeft&&d<h.xBottomRight&&c>-h.yBottomRight&&c<-h.yTopLeft){this._earlyReturn=!0;break}}}};b._hitTestFill=function(a){let c=null;if(n.isExtent(a))c=[[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,
a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]]];else if(n.isPolygon(a))c=a.rings;else if(n.isPolyline(a))c=a.paths;else return;a=this.reverseTransformPt(this._searchPoint);this._pointInPolygon(a,c)&&(this._earlyReturn=!0);const d=this.reverseTransformSize(this._searchDistPoint)*this.geomUnitsPerPoint();this._nearLine(a,c,d)&&(this._earlyReturn=!0)};b._hitTestStroke=function(a,c){let d=null;if(n.isExtent(a))d=[[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]]];else if(n.isPolygon(a))d=
a.rings;else if(n.isPolyline(a))d=a.paths;else return;a=this.reverseTransformPt(this._searchPoint);c*=this.geomUnitsPerPoint();const e=this.reverseTransformSize(this._searchDistPoint)*this.geomUnitsPerPoint();this._nearLine(a,d,c/2+e)&&(this._earlyReturn=!0)};b._pointInPolygon=function(a,c){let d=0;for(const e of c){c=e.length;for(let f=1;f<c;++f){const g=e[f-1],h=e[f];g[1]>a[1]!==h[1]>a[1]&&(0<(h[0]-g[0])*(a[1]-g[1])-(h[1]-g[1])*(a[0]-g[0])?d++:d--)}}return 0!==d};b._nearLine=function(a,c,d){for(const f of c){c=
f.length;for(let g=1;g<c;++g){var e=f[g-1];const h=f[g];let m=(h[0]-e[0])*(h[0]-e[0])+(h[1]-e[1])*(h[1]-e[1]);if(0!==m&&(m=Math.sqrt(m),Math.abs(((h[0]-e[0])*(a[1]-e[1])-(h[1]-e[1])*(a[0]-e[0]))/m)<d&&(e=((h[0]-e[0])*(a[0]-e[0])+(h[1]-e[1])*(a[1]-e[1]))/m,e>-d&&e<m+d)))return!0}}return!1};return k}(w),W=function(l){function k(a,c,d){c=l.call(this,c,d)||this;c._ctx=a;return c}B._inheritsLoose(k,l);var b=k.prototype;b.drawSolidFill=function(a,c){if(a){if(n.isPolygon(a))this._buildPath(a.rings,!0);else if(n.isPolyline(a))this._buildPath(a.paths,
!0);else if(n.isExtent(a))this._buildPath(z(a).rings,!0);else if(n.isMultipoint(a))console.log("CanvasDrawHelper.drawSolidFill - No implementation!");else return;a=this._ctx;a.fillStyle="string"===typeof c?c:"rgba("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+","+c[3]/255+")";a.fill("evenodd")}};b.drawSolidStroke=function(a,c,d,e,f,g){if(a&&c&&0!==d){if(n.isPolygon(a))this._buildPath(a.rings,!0);else if(n.isPolyline(a))this._buildPath(a.paths,!1);else if(n.isExtent(a))this._buildPath(z(a).rings,
!0);else{console.log("CanvasDrawHelper.drawSolidStroke isn't implemented!");return}a=this._ctx;a.strokeStyle="string"===typeof c?c:"rgba("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+","+c[3]/255+")";a.lineWidth=this.transformSize(d)+.5;this._setCapStyle(e);this._setJoinStyle(f);a.miterLimit=g;a.stroke()}};b.pushClipPath=function(a){this._ctx.save();if(n.isPolygon(a))this._buildPath(a.rings,!0);else if(n.isPolyline(a))this._buildPath(a.paths,!0);else if(n.isExtent(a))this._buildPath(z(a).rings,
!0);else return;this._ctx.clip("evenodd")};b.popClipPath=function(){this._ctx.restore()};b.drawImage=function(a,c,d){a=this._resourceManager.getResource(a);if(!A.isNone(a)){var e=this._ctx,f=e.canvas.width;e=e.canvas.height;var g=a.width/a.height*d*c,h=d*c;c||(g=d*a.width,h=d*a.height);this._ctx.drawImage(a,0,0,a.width,a.height,0,0,Math.min(this.transformSize(g),f),Math.min(this.transformSize(h),e))}};b.drawText=function(a){this._textRasterizer||(this._textRasterizer=new E.TextRasterizer)};b._buildPath=
function(a,c){const d=this._ctx;d.beginPath();if(a)for(const e of a)if(a=e?e.length:0,1<a){let f=this.transformPt(e[0]);d.moveTo(f[0],f[1]);for(let g=1;g<a;++g)f=this.transformPt(e[g]),d.lineTo(f[0],f[1]);c&&d.closePath()}};b._setCapStyle=function(a){switch(a){case "Butt":this._ctx.lineCap="butt";break;case "Round":this._ctx.lineCap="round";break;case "Square":this._ctx.lineCap="square"}};b._setJoinStyle=function(a){switch(a){case "Bevel":this._ctx.lineJoin="bevel";break;case "Round":this._ctx.lineJoin=
"round";break;case "Miter":this._ctx.lineJoin="miter"}};return k}(w);const z=l=>l?{spatialReference:l.spatialReference,rings:[[[l.xmin,l.ymin],[l.xmin,l.ymax],[l.xmax,l.ymax],[l.xmax,l.ymin],[l.xmin,l.ymin]]]}:null,I=l=>{switch(l){case "Left":return u.HAlign.Left;case "Right":return u.HAlign.Right;case "Center":case "Justify":return u.HAlign.Center}},J=l=>{switch(l){case "Top":return u.VAlign.Top;case "Center":return u.VAlign.Center;case "Bottom":return u.VAlign.Bottom;case "Baseline":return u.VAlign.Baseline}},
H=(l,k,b)=>{switch(l){case "ExtraLeading":return 1+k/b;case "Multiple":return k;case "Exact":return k/b}};r.CIMSymbolDrawHelper=w;r.C_DEG_TO_RAD=t;r.CanvasDrawHelper=W;r.EnvDrawHelper=U;r.HittestDrawHelper=V;r.Transformation=v;r.horizontalAlignment2HAlign=I;r.lineGapType2LineHeight=H;r.verticalAlignment2VAlign=J;Object.defineProperty(r,"__esModule",{value:!0})});