// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","../../core/floatRGBA","../../geometry/support/jsonUtils","./Rect"],function(z,D,E,F){function B(b){if(!b)return null;switch(b.type){case "CIMPointSymbol":var a=b.symbolLayers;if(!a||1!==a.length)break;return B(a[0]);case "CIMVectorMarker":b=b.markerGraphics;if(!b||1!==b.length)break;var c=b[0];if(!c)break;b=c.geometry;if(!b)break;c=c.symbol;if(!c||"CIMPolygonSymbol"!==c.type&&"CIMLineSymbol"!==c.type||null!=(a=c.symbolLayers)&&a.some(f=>!!f.effects))break;return{geom:b,asFill:"CIMPolygonSymbol"===
c.type};case "sdf":return{geom:b.geom,asFill:b.asFill}}return null}function C(b){let a=Infinity,c=-Infinity,f=Infinity,d=-Infinity;for(const e of b)for(const h of e)h[0]<a&&(a=h[0]),h[0]>c&&(c=h[0]),h[1]<f&&(f=h[1]),h[1]>d&&(d=h[1]);return[a,f,c,d]}z.buildSDF=function(b){var a=b.geom;var c=a?a.rings?a.rings:a.paths?a.paths:void 0!==a.xmin&&void 0!==a.ymin&&void 0!==a.xmax&&void 0!==a.ymax?[[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]]]:null:null;a=Infinity;var f=
-Infinity;var d=Infinity,e=-Infinity;for(var h of c)for(var n of h)n[0]<a&&(a=n[0]),n[0]>f&&(f=n[0]),n[1]<d&&(d=n[1]),n[1]>e&&(e=n[1]);f=new F(a,d,f-a,e-d);d=64/Math.max(f.width,f.height);h=Math.round(f.width*d)+62;n=Math.round(f.height*d)+62;a=[];for(var l of c)if(l&&1<l.length){c=[];for(var k of l){let [t,u]=k;t-=f.x;u-=f.y;t*=d;u*=d;t+=30.5;u+=30.5;b.asFill?c.push([t,u]):c.push([Math.round(t),Math.round(u)])}b.asFill&&(e=c.length-1,c[0][0]===c[e][0]&&c[0][1]===c[e][1]||c.push(c[0]));a.push(c)}var m;
l=h*n;k=Array(l);for(c=0;c<l;++c)k[c]=962;for(m of a)for(c=m.length,f=1;f<c;++f){d=m[f-1];e=m[f];var r=void 0,p=void 0;d[0]<e[0]?(r=d[0],p=e[0]):(r=e[0],p=d[0]);var g=void 0,y=void 0;d[1]<e[1]?(g=d[1],y=e[1]):(g=e[1],y=d[1]);var v=Math.floor(r)-31;p=Math.floor(p)+31;g=Math.floor(g)-31;y=Math.floor(y)+31;0>v&&(v=0);p>h&&(p=h);0>g&&(g=0);y>n&&(y=n);r=e[0]-d[0];const t=e[1]-d[1],u=r*r+t*t;for(;v<p;v++)for(let A=g;A<y;A++){var q=(v-d[0])*r+(A-d[1])*t,w=void 0;0>q?(w=d[0],q=d[1]):q>u?(w=e[0],q=e[1]):(q/=
u,w=d[0]+q*r,q=d[1]+q*t);w=(v-w)*(v-w)+(A-q)*(A-q);q=(n-A-1)*h+v;w<k[q]&&(k[q]=w)}}for(m=0;m<l;++m)k[m]=Math.sqrt(k[m]);m=k;if(b.asFill)for(var x of a)for(b=x.length,a=1;a<b;++a)for(l=x[a-1],k=x[a],l[0]<k[0]?(c=l[0],f=k[0]):(c=k[0],f=l[0]),l[1]<k[1]?(e=l[1],d=k[1]):(e=k[1],d=l[1]),c=Math.floor(c),f=Math.floor(f)+1,e=Math.floor(e),d=Math.floor(d)+1,31>c&&(c=31),f>h-31&&(f=h-31),31>e&&(e=31),d>n-31&&(d=n-31);e<d;++e)if(l[1]>e!==k[1]>e){p=(n-e-1)*h;for(g=c;g<f;++g)g<(k[0]-l[0])*(e-l[1])/(k[1]-l[1])+
l[0]&&(m[p+g]=-m[p+g]);for(g=31;g<c;++g)m[p+g]=-m[p+g]}x=m.length;b=new Uint8Array(4*x);for(a=0;a<x;++a)D.packFloatRGBA(.5-m[a]/62,b,4*a);x=b;return[x,h,n]};z.getExtent=function(b){return b?b.rings?C(b.rings):b.paths?C(b.paths):E.isExtent(b)?[b.xmin,b.ymin,b.xmax,b.ymax]:null:null};z.getSDFInfo=B;z.getSDFMetrics=function(b,a,c,f,d){const [e,h,n,l]=b;if(n<e||l<h)return[0,0,0];var k=n-e,m=l-h;b=64/Math.max(k,m);k=Math.round(k*b);m=Math.round(m*b)+62;let r=1;a&&(r=m/b/(a.ymax-a.ymin));let p=0,g=0;f&&
(d?a&&c&&0<a.ymax-a.ymin&&(p=f.x/((a.xmax-a.xmin)/(a.ymax-a.ymin)*c),g=f.y/c):(p=f.x,g=f.y));p=.5*(a.xmax+a.xmin)+p*(a.xmax-a.xmin);g=.5*(a.ymax+a.ymin)+g*(a.ymax-a.ymin);p=(p-e)*b+31;g=(g-h)*b+31;return[r,p/(k+62)-.5,-(g/m-.5)]};z.getSDFSymbol=function(b){b=b.markerGraphics;if(!b||1!==b.length)return null;b=b[0];if(!b)return null;b=b.symbol;return!b||"CIMPolygonSymbol"!==b.type&&"CIMLineSymbol"!==b.type?null:b};Object.defineProperty(z,"__esModule",{value:!0})});