// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/clock ../../../../../core/Handles ../../../../../core/maybe ../../../../../core/scheduling ../../../../../core/screenUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/arrayUtils ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/mat4 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../chunks/boundedPlane ../../../../../geometry/support/plane ../../../../../geometry/support/ray ../../../../../geometry/support/vectorStacks ../../manipulatorUtils ./sliceToolConfig ./sliceToolUtils ./images/Factory ../../editingTools/dragEventPipeline3D ../../../support/geometryUtils/ray ../../../webgl-engine/lib/Intersector ../../../../interactive/dragEventPipeline ../../../../interactive/InteractiveToolBase ../../../../support/screenUtils ../../../../../widgets/Slice/SlicePlane".split(" "),
function(E,q,J,G,d,K,z,r,p,U,V,L,A,l,B,g,t,M,n,N,m,k,H,C,O,P,D,Q,x,R){function I(u,w,e,a){e=k.createShiftPlane(e,g.normal(a),u.direction,t.create());a=B.create();return t.intersectRay(e,u,a)?{type:"shift",creatingPointerId:w,hasBeenDragged:!1,shiftPlane:e,depth:0,startPoint:a}:null}function F(u){return"mouse"!==u.pointerType||0===u.button}p=function(u){function w(a){var b=u.call(this,a)||this;b.clock=J.default;b._previewPlaneOpacity=1;b.analysisView=null;b.layersMode="none";b.tiltEnabled=!1;b.shiftManipulator=
null;b.rotateHeadingManipulator=null;b.rotateTiltManipulator=null;b.resizeManipulators=null;b.disableEngineLayers=!1;b._handles=new G;b._viewHandles=new G;b._frameTask=null;b._prevPointerMoveTimeout=null;b._previewPlaneGridVisualElement=null;b._previewPlaneOutlineVisualElement=null;b._startPlane=g.create();b._previewPlane=null;b._activeKeyModifiers={};b._lastCursorPosition=z.createScreenPoint();b._resizeHandles=[{direction:[1,0]},{direction:[1,1]},{direction:[0,1]},{direction:[-1,1]},{direction:[-1,
0]},{direction:[-1,-1]},{direction:[0,-1]},{direction:[1,-1]}];b._intersector=P.newIntersector(a.view.state.viewingMode);b._intersector.options.store=0;return b}E._inheritsLoose(w,u);var e=w.prototype;e.onAttach=function(){this.created&&this.visible&&this._updateManipulators()};e.initialize=function(){this._initialize()};e._initialize=function(){var a=E._asyncToGenerator(function*(){var b=()=>{if("creating"===this.toolState||"created"===this.toolState)throw Error("Unexpected toolState");return!this.destroyed};
if(b()&&(this.analysisView=yield this.view.whenAnalysisView(this.analysis),b())){if(null==this.analysis)throw Error("SliceTool requires valid model, but null was provided.");if(d.isNone(this.analysisView.analysisViewData))throw Error("expected internal object to be defined.");this.analysisViewData=this.analysisView.analysisViewData;this.rotateHeadingImage=H.getRotateHeadingTexture(this.view.toolViewManager.textures);this.rotateTiltImage=H.getTiltRotateTexture(this.view.toolViewManager.textures);b=
this.watch("state",f=>{switch(f){case "ready":case "slicing":this.finishToolCreation();break;case "sliced":this.complete()}},!0);"sliced"===this.state?this.complete():this.startToolCreation();this._handles.add([b,this.view.state.watch("camera",()=>this._onCameraChange())]);var c=f=>{this.updateManipulatorsInteractive(f);f.grabbing||(d.isSome(this.analysisViewData.plane)&&g.copy(this.analysisViewData.plane,this._startPlane),this.inputState=null)};this.shiftManipulator=k.createShiftManipulator(this.view);
this.manipulators.add(this.shiftManipulator);this.shiftManipulator.events.on("grab-changed",f=>{this._onShiftGrab(f);c(this.shiftManipulator)});this._handles.add(this._createShiftDragPipeline(this.shiftManipulator));this.rotateHeadingManipulator=k.createRotateManipulator(this.view,this.rotateHeadingImage.texture);this.manipulators.add(this.rotateHeadingManipulator);this.rotateHeadingManipulator.events.on("grab-changed",f=>{this._onRotateHeadingGrab(f);c(this.rotateHeadingManipulator)});this._handles.add(this._createRotateHeadingDragPipeline(this.rotateHeadingManipulator));
this.rotateTiltManipulator=k.createRotateManipulator(this.view,this.rotateTiltImage.texture);this.manipulators.add(this.rotateTiltManipulator);this.rotateTiltManipulator.events.on("grab-changed",f=>{this._onRotateTiltGrab(f);c(this.rotateTiltManipulator)});this._handles.add(this._createRotateTiltDragPipeline(this.rotateTiltManipulator));this.resizeManipulators=this._resizeHandles.map((f,h)=>{const v=k.createResizeManipulator(this.view,f);v.events.on("grab-changed",y=>{this._onResizeGrab(y,h);c(v)});
this._handles.add(this._createResizeDragPipeline(v));return v});this.manipulators.addMany(this.resizeManipulators);this._previewPlaneGridVisualElement=k.createGridVisualElement(this.view);this._previewPlaneOutlineVisualElement=k.createOutlineVisualElement(this.view);this._previewPlaneOutlineVisualElement.width=m.PLANE_PREVIEW_OUTLINE_WIDTH;this._handles.add(this.analysisViewData.watch("plane",()=>this._updateManipulators(),!0));this._updateManipulators();this._updateVisibility(this.visible)}});return function(){return a.apply(this,
arguments)}}();e.destroy=function(){"pending"===this.toolState?(this._handles=d.destroyMaybe(this._handles),this._viewHandles=d.destroyMaybe(this._viewHandles)):(this.rotateHeadingImage.release(),this.rotateTiltImage.release(),this.attached&&this.detach(),this._handles=d.destroyMaybe(this._handles),this._viewHandles=d.destroyMaybe(this._viewHandles),this._removeFrameTask(),this._clearPointerMoveTimeout(),this._previewPlaneOutlineVisualElement=d.destroyMaybe(this._previewPlaneOutlineVisualElement),
this._previewPlaneGridVisualElement=d.destroyMaybe(this._previewPlaneGridVisualElement))};e.enterExcludeLayerMode=function(){d.isNone(this.analysisViewData.plane)||(this._set("layersMode","exclude"),this.active||(this.view.activeTool=this))};e.exitExcludeLayerMode=function(){d.isNone(this.analysisViewData.plane)||(this._set("layersMode","none"),this.active&&(this.view.activeTool=null))};e.onDeactivate=function(){this._updateMouseCursor();this._set("layersMode","none");this._updatePreviewPlane(null)};
e.onDetach=function(){this.created&&this._set("layersMode","none")};e.onShow=function(){this._updateVisibility(!0)};e.onHide=function(){this._updateVisibility(!1)};e._updateVisibility=function(a){this.analysis.visible=a;this.created&&(this._updateMouseCursor(),this._updateManipulators(),a||this._clearPointerMoveTimeout())};e.onInputEvent=function(a){switch(a.type){case "pointer-drag":if(!F(a))break;this._isPlacingSlicePlane?this._onClickPlacePlane(a)&&(a.stopPropagation(),this._updateMouseCursor()):
this._onPointerDrag(a)&&a.stopPropagation();break;case "pointer-move":this._onPointerMove(a);this._updateMouseCursor();break;case "pointer-up":this._onPointerUp(a)&&a.stopPropagation();break;case "immediate-click":if(!F(a))break;this._onClickPlacePlane(a)&&(a.stopPropagation(),this._updateMouseCursor());break;case "click":if(!F(a))break;this._onClickExcludeLayer(a)&&a.stopPropagation();break;case "drag":this.inputState&&a.stopPropagation();break;case "key-down":this._onKeyDown(a)&&a.stopPropagation();
break;case "key-up":this._onKeyUp(a)&&a.stopPropagation()}};e.onEditableChange=function(){this.analysisView&&(this.analysisView.editable=this.editable)};e._onPointerDrag=function(a){const b=this.inputState;if(a.pointerId===this._creatingPointerId&&d.isSome(b)&&"shift"===b.type){const c=x.createScreenPointFromEvent(a);this.shiftManipulator.events.emit("drag",{action:b.hasBeenDragged?"update":"start",pointerType:a.pointerType,start:c,screenPoint:c});return b.hasBeenDragged=!0}return!1};e._onPointerMove=
function(a){this._lastCursorPosition.x=a.x;this._lastCursorPosition.y=a.y;this._resetPointerMoveTimeout();"touch"!==a.pointerType&&this._updatePreviewPlane(x.createScreenPointFromEvent(a),this._activeKeyModifiers)};e._onCameraChange=function(){this._updatePreviewPlane(this._lastCursorPosition,this._activeKeyModifiers);this._updateManipulators()};e._onPointerUp=function(a){return a.pointerId===this._creatingPointerId&&d.isSome(this.analysisViewData.plane)?(a=x.createScreenPointFromEvent(a),this.shiftManipulator.events.emit("drag",
{action:"end",start:a,screenPoint:a}),g.copy(this.analysisViewData.plane,this._startPlane),this.inputState=null,!0):!1};e._onClickPlacePlane=function(a){if("exclude"===this.layersMode)return!1;if(this._isPlacingSlicePlane){var b=x.createScreenPointFromEvent(a);const c=g.create();if(this._pickPlane(b,!1,this._activeKeyModifiers,c))return g.copy(c,this._startPlane),this.analysis.shape=k.planeToShape(c,this.view,this.view.spatialReference,new R),"pointer-drag"===a.type&&(b=this._calculatePickRay(b),
this.inputState=I(b,a.pointerId,c.origin,c)),!0}return!1};e._onClickExcludeLayer=function(a){if("exclude"!==this.layersMode||!this.created)return!1;this.view.hitTest(x.createScreenPointFromEvent(a)).then(b=>{b.results.length?(b=(b=b.results[0])&&b.graphic)&&(b=b.sourceLayer||b.layer)&&this.analysis.excludedLayers.push(b):b.ground.layer?this.analysis.excludedLayers.push(b.ground.layer):this.analysis.excludeGroundSurface=!0});this._set("layersMode","none");this.active&&(this.view.activeTool=null);return!0};
e._onKeyDown=function(a){return a.key===m.forceVerticalModifier||a.key===m.forceHorizontalModifier?(this._activeKeyModifiers[a.key]=!0,d.isSome(this._previewPlane)&&this._updatePreviewPlane(this._lastCursorPosition,this._activeKeyModifiers),!0):!1};e._onKeyUp=function(a){return a.key!==m.forceVerticalModifier&&a.key!==m.forceHorizontalModifier||!this._activeKeyModifiers[a.key]?!1:(delete this._activeKeyModifiers[a.key],d.isSome(this._previewPlane)&&this._updatePreviewPlane(this._lastCursorPosition,
this._activeKeyModifiers),!0)};e._onShiftGrab=function(a){"start"!==a.action||d.isNone(this.analysisViewData.plane)||(a=this._calculatePickRay(a.screenPoint),g.copy(this.analysisViewData.plane,this._startPlane),this.inputState=I(a,null,this.shiftManipulator.renderLocation,this.analysisViewData.plane))};e._createShiftDragPipeline=function(a){return D.createManipulatorDragEventPipeline(a,(b,c,f)=>{b=this.inputState;if(!d.isNone(b)&&"shift"===b.type){var h=d.isSome(this.analysisViewData.plane)?g.copy(this.analysisViewData.plane,
g.create()):null;c.next(C.screenToRenderPlane(this.view,b.shiftPlane)).next(this._shiftDragAdjustSensitivity(b)).next(this._shiftDragUpdatePlane(b));f.next(()=>{d.isSome(h)&&this._updateBoundedPlane(h)})}})};e._shiftDragAdjustSensitivity=function(a){return b=>{if(d.isNone(this.analysisViewData.plane))return null;const c=Math.min((1-Math.abs(l.dot(g.normal(this.analysisViewData.plane),b.ray.direction)/l.length(b.ray.direction)))/.001,1),f=-t.signedDistance(this._startPlane.plane,b.renderEnd),h=-t.signedDistance(this._startPlane.plane,
a.startPoint);a.depth=a.depth*(1-c)+f*c-h;return b}};e._shiftDragUpdatePlane=function(a){return()=>{if(!d.isNone(this.analysisViewData.plane)){var b=l.copy(n.sv3d.get(),this._startPlane.origin),c=l.copy(n.sv3d.get(),g.normal(this._startPlane));l.scale(c,c,-a.depth);l.add(c,c,b);b=g.fromValues(c,this.analysisViewData.plane.basis1,this.analysisViewData.plane.basis2,g.create());this._updateBoundedPlane(b)}}};e._onRotateHeadingGrab=function(a){if("start"===a.action&&!d.isNone(this.analysisViewData.plane)){var b=
k.createRotatePlane(this.analysisViewData.plane,this.view.renderCoordsHelper,1,t.create());a=this._calculatePickRay(a.screenPoint);var c=B.create();t.intersectRay(b,a,c)&&(g.copy(this.analysisViewData.plane,this._startPlane),this.inputState={type:"rotate",rotatePlane:b,startPoint:c})}};e._createRotateHeadingDragPipeline=function(a){return D.createManipulatorDragEventPipeline(a,(b,c,f)=>{b=this.inputState;if(!d.isNone(b)&&"rotate"===b.type){var h=d.isSome(this.analysisViewData.plane)?g.copy(this.analysisViewData.plane,
g.create()):null;c.next(C.screenToRenderPlane(this.view,b.rotatePlane)).next(this._rotateDragRenderPlaneToRotate(b)).next(this._rotateDragUpdatePlaneFromRotate());f.next(()=>{d.isSome(h)&&this._updateBoundedPlane(h)})}})};e._onRotateTiltGrab=function(a){if("start"===a.action&&!d.isNone(this.analysisViewData.plane)){var b=k.createRotatePlane(this.analysisViewData.plane,this.view.renderCoordsHelper,2,t.create());a=this._calculatePickRay(a.screenPoint);var c=B.create();t.intersectRay(b,a,c)&&(g.copy(this.analysisViewData.plane,
this._startPlane),this.inputState={type:"rotate",rotatePlane:b,startPoint:c})}};e._createRotateTiltDragPipeline=function(a){return D.createManipulatorDragEventPipeline(a,(b,c,f)=>{b=this.inputState;if(!d.isNone(b)&&"rotate"===b.type){var h=d.isSome(this.analysisViewData.plane)?g.copy(this.analysisViewData.plane,g.create()):null;c.next(C.screenToRenderPlane(this.view,b.rotatePlane)).next(this._rotateDragRenderPlaneToRotate(b)).next(this._rotateDragUpdatePlaneFromRotate());f.next(()=>{d.isSome(h)&&
this._updateBoundedPlane(h)})}})};e._rotateDragRenderPlaneToRotate=function(a){return b=>{if(d.isNone(this.analysisViewData.plane))return null;const c=t.normal(a.rotatePlane),f=N.calculateInputRotationTransform(a.startPoint,b.renderEnd,this.analysisViewData.plane.origin,c);return{...b,rotateAxis:c,rotateAngle:f}}};e._rotateDragUpdatePlaneFromRotate=function(){return a=>{if(!d.isNone(this.analysisViewData.plane)){var b=A.identity(n.sm4d.get());A.rotate(b,b,a.rotateAngle,a.rotateAxis);a=l.transformMat4(n.sv3d.get(),
this._startPlane.basis1,b);b=l.transformMat4(n.sv3d.get(),this._startPlane.basis2,b);b=g.fromValues(this.analysisViewData.plane.origin,a,b,g.create());this._updateBoundedPlane(b)}}};e._onResizeGrab=function(a,b){if("start"===a.action&&!d.isNone(this.analysisViewData.plane)){a=this._calculatePickRay(a.screenPoint);var c=n.sv3d.get();t.intersectRay(this.analysisViewData.plane.plane,a,c)&&(g.copy(this.analysisViewData.plane,this._startPlane),this.inputState={type:"resize",activeHandleIdx:b,startPoint:B.clone(c)})}};
e._createResizeDragPipeline=function(a){return D.createManipulatorDragEventPipeline(a,(b,c,f)=>{b=this.inputState;if(!d.isNone(b)&&"resize"===b.type&&!d.isNone(this.analysisViewData.plane)){var h=g.copy(this.analysisViewData.plane,g.create());c.next(C.screenToRenderPlane(this.view,this.analysisViewData.plane.plane)).next(this._resizeDragUpdatePlane(b));f.next(()=>{this._updateBoundedPlane(h)})}})};e._resizeDragUpdatePlane=function(a){return b=>{d.isNone(this.analysisViewData.plane)||(b=k.resizePlane(this._resizeHandles[a.activeHandleIdx],
a.startPoint,b.renderEnd,this.view.state.camera,this._startPlane,g.copy(this.analysisViewData.plane)),this._updateBoundedPlane(b))}};e._updateBoundedPlane=function(a){const b=this.analysisViewData;if(d.isSome(b))b.plane=a;else throw Error("valid internal object expected");};e._updatePreviewPlane=function(a,b={}){let c=this._previewPlane;this._previewPlane=null;if(d.isNone(a))this._removeFrameTask(),this._updateManipulators();else{if(!this.analysisViewData.plane&&this.active){const f=d.isSome(c)?c:
g.create();c=d.isSome(c)?g.copy(c,S):null;this._pickPlane(a,!0,b,f)&&(a=m.PREVIEW_FADE_DOT_THRESHOLD,b=!1,d.isSome(c)&&(b=l.dot(c.plane,f.plane)<a||l.dot(l.normalize(n.sv3d.get(),c.basis1),l.normalize(n.sv3d.get(),f.basis1))<a),b&&(this._previewPlaneOpacity=0),this._previewPlane=f)}d.isSome(this._previewPlane)&&d.isNone(this._frameTask)&&0===this._previewPlaneOpacity?this._frameTask=K.addFrameTask({update:({deltaTime:f})=>{this._previewPlaneOpacity=Math.min(this._previewPlaneOpacity+f/(1E3*m.PREVIEW_FADE_DURATION_SECONDS),
1);this._updateManipulators();1===this._previewPlaneOpacity&&this._removeFrameTask()}}):d.isNone(this._previewPlane)&&d.isSome(this._frameTask)?this._removeFrameTask():d.isSome(this._previewPlane)&&this._updateManipulators()}};e._removeFrameTask=function(){this._frameTask=d.removeMaybe(this._frameTask)};e._calculatePickRay=function(a){const b=M.create();a=z.screenPointObjectToArray(a,T);O.fromScreen(this.view.state.camera,a,b);l.normalize(b.direction,b.direction);return b};e._pickMinResult=function(a){a=
z.screenPointObjectToArray(a,n.sv2d.get());this.view.sceneIntersectionHelper.intersectToolIntersectorScreen(a,this._intersector);return this._intersector.results.min};e._pickPlane=function(a,b,c,f){var h=this._pickMinResult(a);a=n.sv3d.get();if(!h.getIntersectionPoint(a))return!1;h=h.getTransformedNormal(n.sv3d.get());const v=this.view.state.camera;0<l.dot(h,v.viewForward)&&l.scale(h,h,-1);const y=k.calculatePlaneHalfSize(a,v);b=(b?1:-1)*y*m.INITIAL_DEPTH_OFFSET_FRAC;b=l.scale(n.sv3d.get(),h,b);l.add(b,
b,a);a=this.tiltEnabled?3:0;k.createPlane(b,h,y,y,v,c[m.forceVerticalModifier]?2:c[m.forceHorizontalModifier]?1:a,this.view.renderCoordsHelper,f);return!0};e._updateMouseCursor=function(){this._set("cursor",null);this._isPlacingSlicePlane||"exclude"===this.layersMode?this._set("cursor","crosshair"):d.isSome(this._creatingPointerId)&&this._set("cursor","grabbing")};e._clearPointerMoveTimeout=function(){this._prevPointerMoveTimeout=d.removeMaybe(this._prevPointerMoveTimeout)};e._resetPointerMoveTimeout=
function(){this._clearPointerMoveTimeout();this.shiftManipulator.state|=k.DidPointerMoveRecentlyFlag;this.rotateHeadingManipulator.state|=k.DidPointerMoveRecentlyFlag;this.rotateTiltManipulator.state|=k.DidPointerMoveRecentlyFlag;this._prevPointerMoveTimeout=this.clock.setTimeout(()=>{this.shiftManipulator.state&=~k.DidPointerMoveRecentlyFlag;this.rotateHeadingManipulator.state&=~k.DidPointerMoveRecentlyFlag;this.rotateTiltManipulator.state&=~k.DidPointerMoveRecentlyFlag},m.POINTER_MOVE_TIMER_MS)};
e._updateManipulators=function(){if(!this.disableEngineLayers){var a=null,b=!1;if(d.isSome(this.analysisViewData.plane))a=this.analysisViewData.plane,b=!1;else if(d.isSome(this._previewPlane))a=this._previewPlane,b=!0;else{this.shiftManipulator.available=!1;this.rotateHeadingManipulator.available=!1;this.rotateTiltManipulator.available=!1;this.resizeManipulators.forEach(f=>f.available=!1);this._previewPlaneOutlineVisualElement.visible=!1;this._previewPlaneGridVisualElement.visible=!1;return}var c=
k.calculateBoundedPlaneTranslateRotate(a,n.sm4d.get());b?(this.shiftManipulator.available=!1,this.rotateHeadingManipulator.available=!1,this.rotateTiltManipulator.available=!1,this.resizeManipulators.forEach(f=>f.available=!1),this._previewPlaneOutlineVisualElement.visible=!0,this._previewPlaneGridVisualElement.visible=!0):(this.shiftManipulator.available=!0,this.rotateHeadingManipulator.available=!0,this.rotateTiltManipulator.available=this.tiltEnabled,this.resizeManipulators.forEach(f=>f.available=
!0),k.updateShiftRestartHandle(this.shiftManipulator,c,a,this.view.state.camera),k.updateRotateHeadingHandle(this.rotateHeadingManipulator,c,a,this.view.renderCoordsHelper),k.updateRotateTiltHandle(this.rotateTiltManipulator,c,a),this.resizeManipulators.forEach((f,h)=>k.updateResizeHandle(f,this._resizeHandles[h],c,a)),this._previewPlaneOutlineVisualElement.visible=!1,this._previewPlaneGridVisualElement.visible=!1);b=l.set(n.sv3d.get(),l.length(a.basis1),l.length(a.basis2),1);b=A.fromScaling(n.sm4d.get(),
b);b=A.multiply(b,c,b);this._previewPlaneOutlineVisualElement.transform=b;this._previewPlaneGridVisualElement.transform=b;this._updateMaterials()}};e._updateMaterials=function(){this._previewPlaneOutlineVisualElement.color=[m.PLANE_OUTLINE_COLOR[0],m.PLANE_OUTLINE_COLOR[1],m.PLANE_OUTLINE_COLOR[2],m.PLANE_OUTLINE_COLOR[3]*this._previewPlaneOpacity];this._previewPlaneGridVisualElement.backgroundColor=[m.PLANE_BACKGROUND_COLOR[0],m.PLANE_BACKGROUND_COLOR[1],m.PLANE_BACKGROUND_COLOR[2],m.PLANE_BACKGROUND_COLOR[3]*
this._previewPlaneOpacity];this._previewPlaneGridVisualElement.gridColor=[0,0,0,0]};e.updateManipulatorsInteractive=function(a){a.grabbing?(this.shiftManipulator.interactive=this.shiftManipulator===a,this.rotateHeadingManipulator.interactive=this.rotateHeadingManipulator===a,this.rotateTiltManipulator.interactive=this.rotateTiltManipulator===a,this.resizeManipulators.forEach(b=>{b.interactive=b===a})):(this.shiftManipulator.interactive=!0,this.rotateHeadingManipulator.interactive=!0,this.rotateTiltManipulator.interactive=
!0,this.resizeManipulators.forEach(b=>{b.interactive=!0}))};e.testData=function(){return{plane:d.isSome(this.analysisViewData.plane)?this.analysisViewData.plane:null}};E._createClass(w,[{key:"state",get:function(){const a=!!this.analysisViewData.plane,b=!!this.inputState;return a?a&&b?"slicing":a&&!b?"sliced":"ready":"ready"}},{key:"cursor",get:function(){return this._get("cursor")}},{key:"analysis",set:function(a){if(null==a)throw Error("SliceTool requires valid model, but null was provided.");this._handles.remove("analysis");
this._set("analysis",a)}},{key:"inputState",get:function(){return this._get("inputState")},set:function(a){this._set("inputState",a);this.analysisView.showGrid=d.isSome(a)&&"resize"===a.type;this._updateMaterials()}},{key:"_isPlacingSlicePlane",get:function(){return!this.inputState&&!this.analysisViewData.plane&&this.active}},{key:"_creatingPointerId",get:function(){return d.isSome(this.inputState)&&"shift"===this.inputState.type?this.inputState.creatingPointerId:null}}]);return w}(Q.InteractiveToolBase);
q.__decorate([r.property()],p.prototype,"clock",void 0);q.__decorate([r.property({constructOnly:!0})],p.prototype,"view",void 0);q.__decorate([r.property()],p.prototype,"analysisView",void 0);q.__decorate([r.property()],p.prototype,"analysisViewData",void 0);q.__decorate([r.property({readOnly:!0})],p.prototype,"state",null);q.__decorate([r.property({readOnly:!0,value:null})],p.prototype,"cursor",null);q.__decorate([r.property()],p.prototype,"analysis",null);q.__decorate([r.property({readOnly:!0})],
p.prototype,"layersMode",void 0);q.__decorate([r.property({aliasOf:"analysis.tiltEnabled"})],p.prototype,"tiltEnabled",void 0);q.__decorate([r.property({value:null})],p.prototype,"inputState",null);p=q.__decorate([L.subclass("esri.views.3d.interactive.analysisTools.slice.SliceTool")],p);const S=g.create(),T=z.createScreenPointArray();return p});