// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../popup/FieldInfo ../../../popup/content/support/ChartMediaInfoValueSeries ../support/featureUtils ../support/relatedFeatureUtils".split(" "),function(A,m,h,n,F,G,H,C,D,E,l,x){h=function(B){function y(a){a=B.call(this,
a)||this;a.activeMediaInfoIndex=0;a.attributes=null;a.description=null;a.fieldInfoMap=null;a.formattedAttributes=null;a.expressionAttributes=null;a.layer=null;a.mediaInfos=null;a.popupTemplate=null;a.relatedInfos=null;a.title=null;return a}A._inheritsLoose(y,B);var r=y.prototype;r.setActiveMedia=function(a){this._setContentElementMedia(a)};r.next=function(){this._pageContentElementMedia(1)};r.previous=function(){this._pageContentElementMedia(-1)};r._setContentElementMedia=function(a){const {formattedMediaInfoCount:c}=
this;this.activeMediaInfoIndex=(a+c)%c};r._pageContentElementMedia=function(a){const {activeMediaInfoIndex:c}=this;this._setContentElementMedia(c+a)};r._formatMediaInfos=function(){const {attributes:a,mediaInfos:c,formattedAttributes:d,expressionAttributes:k,fieldInfoMap:e,layer:f}=this;return null==c?void 0:c.map(b=>{b=null==b?void 0:b.clone();if(!b)return null;b.title=l.substituteFieldsInLinksAndAttributes({attributes:a,fieldInfoMap:e,globalAttributes:d,expressionAttributes:k,layer:f,text:b.title});
b.caption=l.substituteFieldsInLinksAndAttributes({attributes:a,fieldInfoMap:e,globalAttributes:d,expressionAttributes:k,layer:f,text:b.caption});b.altText=l.substituteFieldsInLinksAndAttributes({attributes:a,fieldInfoMap:e,globalAttributes:d,expressionAttributes:k,layer:f,text:b.altText});if("image"===b.type){var {value:p}=b;this._setImageValue({value:p,formattedAttributes:d,layer:f});return b.value.sourceURL?b:void 0}return"pie-chart"===b.type||"line-chart"===b.type||"column-chart"===b.type||"bar-chart"===
b.type?({value:p}=b,this._setChartValue({value:p,chartType:b.type,attributes:a,formattedAttributes:d,layer:f}),b):null}).filter(Boolean)};r._setImageValue=function(a){const {fieldInfoMap:c}=this,{value:d,formattedAttributes:k,layer:e}=a,{linkURL:f,sourceURL:b}=d;b&&(a=l.fixTokens(b,e),d.sourceURL=l.substituteAttributes({formattedAttributes:k,template:a,fieldInfoMap:c}));f&&(a=l.fixTokens(f,e),d.linkURL=l.substituteAttributes({formattedAttributes:k,template:a,fieldInfoMap:c}))};r._setChartValue=function(a){const {value:c,
attributes:d,formattedAttributes:k,chartType:e,layer:f}=a,{popupTemplate:b,relatedInfos:p}=this,{fields:q,normalizeField:v}=c;c.fields=l.getFixedFieldNames(q,f);v&&(c.normalizeField=l.getFixedFieldName(v,f));if(q.some(g=>!!(null!=k[g]||l.isRelatedField(g)&&p.size))){var u=null==b?void 0:b.fieldInfos;q.forEach(g=>{l.isRelatedField(g)?c.series=[...c.series,...this._getRelatedChartInfos({fieldInfos:u,fieldName:g,formattedAttributes:k,chartType:e,value:c})]:(g=this._getChartOption({value:c,attributes:d,
chartType:e,formattedAttributes:k,fieldName:g,fieldInfos:u}),c.series.push(g))})}};r._getRelatedChartInfos=function(a){var c;const {fieldInfos:d,fieldName:k,formattedAttributes:e,chartType:f,value:b}=a,p=[];a=x.getRelatedFieldInfo(k);const {layerId:q,fieldName:v}=a;a=null==(c=this.relatedInfos)?void 0:c.get(q.toString());if(!a)return p;const {relatedFeatures:u,relation:g}=a;if(!g||!u)return p;({cardinality:c}=g);u.forEach(z=>{const {attributes:t}=z;t&&Object.keys(t).forEach(w=>{w===v&&p.push(this._getChartOption({value:b,
attributes:t,formattedAttributes:e,fieldName:k,chartType:f,relatedFieldName:w,fieldInfos:d}))})});return"one-to-many"===c||"many-to-many"===c?p:[p[0]]};r._getTooltip=function({label:a,value:c,chartType:d}){return"pie-chart"===d?a:`${a}: ${c}`};r._getChartOption=function(a){const {value:c,attributes:d,formattedAttributes:k,fieldName:e,relatedFieldName:f,fieldInfos:b,chartType:p}=a;var {layer:q}=this;const {normalizeField:v,tooltipField:u}=c;var g=v?l.isRelatedField(v)?d[x.getRelatedFieldInfo(v).fieldName]:
d[v]:null;a=f&&void 0!==d[f]?d[f]:void 0!==d[e]?d[e]:k[e];const z=void 0===a?null:a&&g?a/g:a;a=new E({value:z});if(l.isRelatedField(e)){var t=x.getRelatedFieldInfo(e);var w=x.getRelatedFieldInfo(u);w=w?w.fieldName:null;q=l.formatValueToFieldInfo(z,{fieldInfos:b,fieldName:f,layer:q,preventPlacesFormatting:!!g});t=t?t.label||t.fieldName:f;a.tooltip=this._getTooltip({label:w&&void 0!==d[w]?d[w]:t,value:q,chartType:p});return a}g=l.getFieldInfo(b,e);q=l.getFixedFieldName(e,q);g=u&&void 0!==k[u]?k[u]:
l.getFieldInfoLabel(g||new D({fieldName:q}),null==(t=this.popupTemplate)?void 0:t.expressionInfos);a.tooltip=this._getTooltip({label:g,value:k[q],chartType:p});return a};A._createClass(y,[{key:"activeMediaInfo",get:function(){return this.formattedMediaInfos[this.activeMediaInfoIndex]||null}},{key:"formattedMediaInfos",get:function(){return this._formatMediaInfos()||[]}},{key:"formattedMediaInfoCount",get:function(){return this.formattedMediaInfos.length}}]);return y}(h);m.__decorate([n.property()],
h.prototype,"activeMediaInfoIndex",void 0);m.__decorate([n.property({readOnly:!0})],h.prototype,"activeMediaInfo",null);m.__decorate([n.property()],h.prototype,"attributes",void 0);m.__decorate([n.property()],h.prototype,"description",void 0);m.__decorate([n.property()],h.prototype,"fieldInfoMap",void 0);m.__decorate([n.property()],h.prototype,"formattedAttributes",void 0);m.__decorate([n.property()],h.prototype,"expressionAttributes",void 0);m.__decorate([n.property({readOnly:!0})],h.prototype,"formattedMediaInfos",
null);m.__decorate([n.property()],h.prototype,"layer",void 0);m.__decorate([n.property({readOnly:!0})],h.prototype,"formattedMediaInfoCount",null);m.__decorate([n.property()],h.prototype,"mediaInfos",void 0);m.__decorate([n.property()],h.prototype,"popupTemplate",void 0);m.__decorate([n.property()],h.prototype,"relatedInfos",void 0);m.__decorate([n.property()],h.prototype,"title",void 0);return h=m.__decorate([C.subclass("esri.widgets.Feature.FeatureMedia.FeatureMediaViewModel")],h)});