// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/reader ../../core/accessorSupport/decorators/subclass ./DirectionsFeature ./FeatureSet ../../geometry/Extent ../../geometry/SpatialReference ../../geometry/Polyline ../../geometry/Point".split(" "),function(y,e,c,C,l,K,L,M,D,E,z,F,G,H,w,I){c=
function(A){function u(a){a=A.call(this,a)||this;a.extent=null;a.features=null;a.geometryType="polyline";a.routeId=null;a.routeName=null;a.totalDriveTime=null;a.totalLength=null;a.totalTime=null;return a}y._inheritsLoose(u,A);var x=u.prototype;x.readFeatures=function(a,f){var g;if(!a)return[];const r=(f=null!=(g=f.summary.envelope.spatialReference)?g:f.spatialReference)&&H.fromJSON(f);return a.map(p=>{var t,d,h=this._decompressGeometry(p.compressedGeometry);h=new w({...h,spatialReference:r});const v=
null!=(t=null==(d=p.events)?void 0:d.map(b=>{const {arriveTimeUTC:m,ETA:q,point:{x:k,y:n,z:B},strings:J}=b;return new z({geometry:new I({x:k,y:n,z:B,hasZ:void 0!==B,spatialReference:r}),attributes:{ETA:q,arriveTimeUTC:m},strings:J})}))?t:[];return new z({attributes:p.attributes,events:v,geometry:h,strings:p.strings})})};x._decompressGeometry=function(a){let f=0,g=0,r=0,p=0;const t=[];let d,h,v,b=0,m=0,q=0;(a=a.match(/((\+|\-)[^\+\-\|]+|\|)/g))||(a=[]);if(0===parseInt(a[b],32)){b=2;var k=parseInt(a[b],
32);b++;d=parseInt(a[b],32);b++;k&1&&(m=a.indexOf("|")+1,h=parseInt(a[m],32),m++);k&2&&(q=a.indexOf("|",m)+1,v=parseInt(a[q],32),q++)}else d=parseInt(a[b],32),b++;for(;b<a.length&&"|"!==a[b];){k=parseInt(a[b],32)+f;b++;f=k;var n=parseInt(a[b],32)+g;b++;g=n;k=[k/d,n/d];m&&(n=parseInt(a[m],32)+r,m++,r=n,k.push(n/h));q&&(n=parseInt(a[q],32)+p,q++,p=n,k.push(n/v));t.push(k)}return{paths:[t],hasZ:0<m,hasM:0<q}};x._mergePolylinesToSinglePath=function(a,f){if(0===a.length)return new w({spatialReference:f});
const g=[];for(const d of a)for(const h of d.paths)g.push(...h);const r=[];g.forEach((d,h)=>{0!==h&&d[0]===g[h-1][0]&&d[1]===g[h-1][1]||r.push(d)});const {hasM:p,hasZ:t}=a[0];return new w({hasM:p,hasZ:t,paths:[r],spatialReference:f})};y._createClass(u,[{key:"mergedGeometry",get:function(){if(!this.features)return null;const a=this.features.map(({geometry:g})=>C.unwrap(g)),f=this.get("extent.spatialReference");return this._mergePolylinesToSinglePath(a,f)}},{key:"strings",get:function(){return this.features.map(({strings:a})=>
a)}}]);return u}(F);e.__decorate([l.property({type:G,json:{read:{source:"summary.envelope"}}})],c.prototype,"extent",void 0);e.__decorate([l.property()],c.prototype,"features",void 0);e.__decorate([D.reader("features")],c.prototype,"readFeatures",null);e.__decorate([l.property()],c.prototype,"geometryType",void 0);e.__decorate([l.property({readOnly:!0})],c.prototype,"mergedGeometry",null);e.__decorate([l.property()],c.prototype,"routeId",void 0);e.__decorate([l.property()],c.prototype,"routeName",
void 0);e.__decorate([l.property({value:null,readOnly:!0})],c.prototype,"strings",null);e.__decorate([l.property({json:{read:{source:"summary.totalDriveTime"}}})],c.prototype,"totalDriveTime",void 0);e.__decorate([l.property({json:{read:{source:"summary.totalLength"}}})],c.prototype,"totalLength",void 0);e.__decorate([l.property({json:{read:{source:"summary.totalTime"}}})],c.prototype,"totalTime",void 0);return c=e.__decorate([E.subclass("esri.rest.support.DirectionsFeatureSet")],c)});