// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","../../core/screenUtils","../../renderers/visualVariables/support/visualVariableUtils"],function(c,m,n){function p(a){return a&&"blendMode"in a&&"effect"in a}function q(a){return a&&"esri.views.2d.layers.GroupLayerView2D"===a.declaredClass}c.applyVisualVariables=function(a,d){const {graphic:f,renderer:b,symbol:g}=d;d=g.type;if("text"!==d&&"shield-label-symbol"!==d&&"visualVariables"in b&&b.visualVariables){var e=b.getVisualVariablesForType("size"),l=b.getVisualVariablesForType("color"),
k=b.getVisualVariablesForType("opacity"),h=b.getVisualVariablesForType("rotation");e=e[0];l=l[0];k=k[0];h=h[0];e&&(e=n.getSize(e,f,{shape:"simple-marker"===d?g.style:null}),null!=e&&("simple-marker"===d?a.size=m.px2pt(e):"picture-marker"===d?(a.width=m.px2pt(e),a.height=m.px2pt(e)):"simple-line"===d?a.width=m.px2pt(e):a.outline&&(a.outline.width=m.px2pt(e))));l&&((e=n.getColor(l,f))&&"simple-marker"===d||"simple-line"===d||"simple-fill"===d)&&(a.color=e?e.toJSON():void 0);k&&(d=n.getOpacity(k,f),
null!=d&&a.color&&(a.color[3]=Math.round(255*d)));h&&(a.angle=-n.getRotationAngle(b,f))}};c.createMultipointLayer=function(){return{layerDefinition:{name:"multipointLayer",geometryType:"esriGeometryMultipoint",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryMultipoint",features:[]}}};c.createPointLayer=function(){return{layerDefinition:{name:"pointLayer",geometryType:"esriGeometryPoint",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryPoint",features:[]}}};c.createPolygonLayer=
function(){return{layerDefinition:{name:"polygonLayer",geometryType:"esriGeometryPolygon",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryPolygon",features:[]}}};c.createPolylineLayer=function(){return{layerDefinition:{name:"polylineLayer",geometryType:"esriGeometryPolyline",drawingInfo:{renderer:null}},featureSet:{geometryType:"esriGeometryPolyline",features:[]}}};c.getContextBoundingBox=function(a,d=15){const f=a.canvas.width;var b=a.canvas.height;a=a.getImageData(0,0,f,b).data;
let g,e,l,k,h;g=b;a:for(;g--;)for(b=f;b--;)if(a[4*(f*g+b)+3]>d){h=g;break a}if(!h)return null;b=f;a:for(;b--;)for(g=h+1;g--;)if(a[4*(f*g+b)+3]>d){k=b;break a}b=0;a:for(;b<=k;++b)for(g=h+1;g--;)if(a[4*(f*g+b)+3]>d){e=b;break a}g=0;a:for(;g<=h;++g)for(b=e;b<=k;++b)if(a[4*(f*g+b)+3]>d){l=g;break a}return{x:e,y:l,width:k-e,height:h-l}};c.getVisibleLayerViews=function(a,d){const f=a.allLayerViews.items;if(d===a.scale)return f.filter(b=>!b.suspended);a=[];for(const b of f)if(!q(b.parent)||a.includes(b.parent))!b.visible||
d&&"isVisibleAtScale"in b&&!b.isVisibleAtScale(d)||a.push(b);return a};c.isBingMapsLayer=function(a){return a&&"bing-maps"===a.type};c.isBlendLayer=p;c.isCSVLayer=function(a){return a&&"csv"===a.type};c.isFeatureLayer=function(a){return a&&"feature"===a.type};c.isGeoJSONLayer=function(a){return a&&"geojson"===a.type};c.isGraphicsLayer=function(a){return a&&"graphics"===a.type};c.isGroupLayer=function(a){return a&&"group"===a.type};c.isImageryLayer=function(a){return a&&"imagery"===a.type};c.isImageryTileLayer=
function(a){return a&&"imagery-tile"===a.type};c.isKMLLayer=function(a){return a&&"kml"===a.type};c.isMapImageLayer=function(a){return a&&"map-image"===a.type};c.isMapNotesLayer=function(a){return a&&"map-notes"===a.type};c.isOpenStreetMapLayer=function(a){return a&&"open-street-map"===a.type};c.isScreenshotRequired=function(a){const d=a.layer;if(p(d)){const f=d.blendMode;if((!f||"normal"===f)&&(d.effect||"featureEffect"in a&&a.featureEffect))return!0}return!1};c.isStreamLayer=function(a){return a&&
"stream"===a.type};c.isTileLayer=function(a){return a&&"tile"===a.type};c.isVectorTileLayer=function(a){return a&&"vector-tile"===a.type};c.isWMSLayer=function(a){return a&&"wms"===a.type};c.isWMTSLayer=function(a){return a&&"wmts"===a.type};c.isWebTileLayer=function(a){return a&&"web-tile"===a.type};Object.defineProperty(c,"__esModule",{value:!0})});