// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../intl ../../core/Accessor ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../layers/support/CodedValueDomain ../../layers/support/Domain ../../layers/support/InheritedDomain ../../layers/support/RangeDomain ../../layers/support/domainUtils ../../layers/support/fieldUtils ../../intl/substitute".split(" "),
function(u,d,c,A,e,E,F,G,B,C,H,I,J,q,h,v){const w={type:"number"},x={type:"number",intlOptions:{notation:"scientific"}},y={type:"date",intlOptions:{day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"numeric",second:"numeric"}};c=function(z){function r(a){a=z.call(this,a)||this;a.arcade=null;a.config=null;a.feature=null;a.field=null;a.initialFeature=null;a.layer=null;a.description=null;a.editorType=null;a.error=null;a.format=null;a.group=null;a.hint=null;a.messages=null;a.name=null;
return a}u._inheritsLoose(r,z);var p=r.prototype;p._isDomainCompatible=function(a){const {field:b}=this;if("coded-value"===(null==a?void 0:a.type)){const f=typeof a.codedValues[0].code;if("string"===f&&h.isStringField(b)||"number"===f&&h.isNumericField(b))return!0}return"range"===(null==a?void 0:a.type)&&h.isNumericField(b)||h.isDateField(b)?!0:!1};p._validate=function(){const {domain:a,field:b,initialFeature:f,minLength:l,required:k,type:n,valid:m,value:g}=this,t=k&&null===g,D=void 0!==m;return!t&&
f.getAttribute(b.name)===g&&D?null:"text"===n&&-1<l&&"string"===typeof g&&g.length<l?"length-validation-error::too-short":a?null!==g||k?q.validateDomainValue(a,g):null:t?h.TypeValidationError.INVALID_TYPE:h.validateFieldValue(b,g)};p._shownByDefault=function(){var a;const b=null==(a=this.field)?void 0:a.type;return"oid"!==b&&"global-id"!==b&&!this._isGeometryField()};p._isEditorField=function(){return-1<h.getFeatureEditFields(this.layer).indexOf(this.name)};p._isGeometryField=function(){return-1<
h.getFeatureGeometryFields(this.layer).indexOf(this.name)};p._toErrorMessage=function(){const {domain:a,field:b,messages:f,minLength:l,value:k,required:n,type:m}=this;var g=this.error;return n&&null===k?f.validationErrors.cannotBeNull:g===q.DomainValidationError.VALUE_OUT_OF_RANGE||g===h.NumericRangeValidationError.OUT_OF_RANGE?(g=q.getDomainRange(a)||h.getFieldRange(b),v.substitute(f.validationErrors.outsideRange,g,{format:{max:"date"===m?y:g.isInteger?w:x,min:"date"===m?y:g.isInteger?w:x}})):g===
q.DomainValidationError.INVALID_CODED_VALUE?f.validationErrors.invalidCodedValue:g===h.TypeValidationError.INVALID_TYPE?f.validationErrors.invalidType:"length-validation-error::too-short"===g?v.substitute(f.validationErrors.tooShort,{min:l}):null};u._createClass(r,[{key:"compiledFunc",get:function(){var a;const {arcade:b}=this;return b&&b.arcadeUtils.createFunction(null==(a=this.config)?void 0:a.visibilityExpression)}},{key:"compiledRequiredFunc",get:function(){var a;const {arcade:b}=this;return b&&
b.arcadeUtils.createFunction(null==(a=this.config)?void 0:a.requiredExpression)}},{key:"evaluatedRequirement",get:function(){const a=this.compiledRequiredFunc;if(!a)return null;const {arcade:b}=this;return b.arcadeUtils.executeFunction(a,b.arcadeUtils.createExecContext(this.feature))}},{key:"evaluatedVisibility",get:function(){const a=this.compiledFunc;if(!a)return null;const {arcade:b}=this;return b.arcadeUtils.executeFunction(a,b.arcadeUtils.createExecContext(this.feature))}},{key:"domain",get:function(){var a,
b,{typeIdField:f}=this.layer;const l=f===this.name;var k=null==(a=this.field)?void 0:a.domain;if(l&&!k)return new C({name:"__internal-type-based-coded-value-domain__",codedValues:this.layer.types.map(({id:n,name:m})=>({code:n,name:m}))});({feature:a}=this);f=f&&this.layer.getFieldDomain(this.name,{feature:a})||k;k=null==(b=this.config)?void 0:b.domain;return this._isDomainCompatible(k)?k:f}},{key:"editable",get:function(){var a,b;const {config:f,field:l,layer:k,name:n}=this,m=k.capabilities.operations.supportsEditing&&
l.editable,g=null==(a=k.popupTemplate)?void 0:null==(b=a.fieldInfos)?void 0:b.find(({fieldName:t})=>t===n);a=f?!1!==f.editable:!1!==(null==g?void 0:g.isEditable);return m&&a}},{key:"errorMessage",get:function(){return this._toErrorMessage()}},{key:"includeTime",get:function(){var a;const b=null==(a=this.config)?void 0:a.includeTime;return void 0===b?!0:b}},{key:"label",get:function(){var a;return(null==(a=this.config)?void 0:a.label)||this.field.alias||this.field.name}},{key:"maxLength",get:function(){var a,
b;if("date"===this.type)return-1;const f=null==(a=this.field)?void 0:a.length;a=null==(b=this.config)?void 0:b.maxLength;return!isNaN(a)&&-1<=a&&(-1===f||a<=f)?a:f}},{key:"minLength",get:function(){var a,b;if("date"===this.type)return-1;const f=null==(a=this.field)?void 0:a.length;a=null==(b=this.config)?void 0:b.minLength;return!isNaN(a)&&-1<=a&&(-1===f||a<=f)?a:-1}},{key:"required",get:function(){var a,b;return this.editable?null!=(a=this.field)&&a.nullable?"boolean"===typeof this.evaluatedRequirement?
this.evaluatedRequirement:!0===(null==(b=this.config)?void 0:b.required):!0:!1}},{key:"type",get:function(){const {field:a}=this;return h.isNumericField(a)?"number":h.isStringField(a)?"text":h.isDateField(a)?"date":"unsupported"}},{key:"valid",get:function(){const a=this.editable?this._validate():null;this._set("error",a);return null===a}},{key:"value",get:function(){return this._get("value")},set:function(a){this.notifyChange("evaluatedVisibility");this._set("value",a)}},{key:"visible",get:function(){return this._isEditorField()?
!1:"boolean"===typeof this.evaluatedVisibility?this.evaluatedVisibility:!!this.config||this._shownByDefault()}}]);return r}(A);d.__decorate([e.property()],c.prototype,"arcade",void 0);d.__decorate([e.property()],c.prototype,"compiledFunc",null);d.__decorate([e.property()],c.prototype,"compiledRequiredFunc",null);d.__decorate([e.property()],c.prototype,"config",void 0);d.__decorate([e.property()],c.prototype,"evaluatedRequirement",null);d.__decorate([e.property()],c.prototype,"evaluatedVisibility",
null);d.__decorate([e.property()],c.prototype,"feature",void 0);d.__decorate([e.property()],c.prototype,"field",void 0);d.__decorate([e.property()],c.prototype,"initialFeature",void 0);d.__decorate([e.property()],c.prototype,"layer",void 0);d.__decorate([e.property({aliasOf:"config.description"})],c.prototype,"description",void 0);d.__decorate([e.property()],c.prototype,"domain",null);d.__decorate([e.property()],c.prototype,"editable",null);d.__decorate([e.property({aliasOf:"config.editorType"})],
c.prototype,"editorType",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"error",void 0);d.__decorate([e.property({dependsOn:["error","messages","value"]})],c.prototype,"errorMessage",null);d.__decorate([e.property({aliasOf:"config.format"})],c.prototype,"format",void 0);d.__decorate([e.property()],c.prototype,"group",void 0);d.__decorate([e.property({aliasOf:"config.hint"})],c.prototype,"hint",void 0);d.__decorate([e.property()],c.prototype,"includeTime",null);d.__decorate([e.property()],
c.prototype,"label",null);d.__decorate([e.property()],c.prototype,"maxLength",null);d.__decorate([e.property()],c.prototype,"minLength",null);d.__decorate([e.property()],c.prototype,"messages",void 0);d.__decorate([e.property({aliasOf:"field.name"})],c.prototype,"name",void 0);d.__decorate([e.property()],c.prototype,"required",null);d.__decorate([e.property()],c.prototype,"type",null);d.__decorate([e.property()],c.prototype,"valid",null);d.__decorate([e.property({value:null})],c.prototype,"value",
null);d.__decorate([e.property()],c.prototype,"visible",null);return c=d.__decorate([B.subclass("esri.widgets.FeatureForm.InputField")],c)});