// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/Error ../../../../../core/Logger ../../../../../core/LRUCache ../../../../../support/arcadeOnDemand ../../../../../symbols/cim/utils ../../../arcade/callExpressionWithFeature ../../../layers/support/cimSymbolUtils".split(" "),function(E,t,n,K,L,M,N,O,P,r){function F(k,f,g,b){return y.apply(this,arguments)}function y(){y=n._asyncToGenerator(function*(k,f,g,b){switch(k.type){case "simple":return v.fromBasicRenderer(k,
f,g,b);case "map":return G.fromUVRenderer(k,f,g,b);case "interval":return H.fromCBRenderer(k,f,g,b);case "dictionary":return I.fromDictionaryRenderer(k,f,g,b);case "subtype":return J.fromSubtypes(k,f,g,b)}});return y.apply(this,arguments)}function Q(k,f){return z.apply(this,arguments)}function z(){z=n._asyncToGenerator(function*(k,f){const g=k||1;if("number"===typeof g)return(a,d,c)=>g;const b=yield N.createRendererExpression(g,f.spatialReference,f.fields);return(a,d,c)=>P(b,a,{$view:c},f.geometryType,
d)||1});return z.apply(this,arguments)}function R(){return A.apply(this,arguments)}function A(){A=n._asyncToGenerator(function*(){B||(B=new Promise((k,f)=>E(["../../../layers/features/schemaUtils"],k,f)));return B});return A.apply(this,arguments)}const C=L.getLogger("esri/views/2d/engine/webgl/util/Matcher");let v=function(){function k(){this.type="feature";this._defaultResult=null}k.fromBasicRenderer=function(){var g=n._asyncToGenerator(function*(b,a,d,c){const e=new k;b.symbol&&(b=yield r.expandSymbol(b.symbol,
d,c),a=a.createTemplateGroup(b,null),e.setDefault(a));return e});return function(b,a,d,c){return g.apply(this,arguments)}}();var f=k.prototype;f.size=function(){return 1};f.getDefault=function(){return this._defaultResult};f.setDefault=function(g){this._defaultResult=g};f.match=function(g,b,a,d,c){return this.getDefault()};f.analyze=function(){var g=n._asyncToGenerator(function*(b,a,d,c,e,h){return null});return function(b,a,d,c,e,h){return g.apply(this,arguments)}}();return k}(),J=function(k){function f(g,
b){var a=k.call(this)||this;a._subMatchers=g;a._subtypeField=b;return a}n._inheritsLoose(f,k);f.fromSubtypes=function(){var g=n._asyncToGenerator(function*(b,a,d,c){const e=new Map,h=[];for(const l in b.renderers){const q=parseInt(l,10),p=F(b.renderers[l],a,d,c).then(m=>e.set(q,m));h.push(p)}yield Promise.all(h);return new f(e,b.subtypeField)});return function(b,a,d,c){return g.apply(this,arguments)}}();f.prototype.match=function(g,b,a,d,c){var e=b.readAttribute(this._subtypeField);return(e=this._subMatchers.get(e))?
e.match(g,b,a,d,c):null};return f}(v),H=function(k){function f(b,a,d,c){var e=k.call(this)||this;e.type="interval";e._intervals=[];e._isMaxInclusive=a;e._fieldIndex=c;e._field=b;e._normalizationInfo=d;return e}n._inheritsLoose(f,k);f.fromCBRenderer=function(){var b=n._asyncToGenerator(function*(a,d,c,e){const {isMaxInclusive:h,normalizationField:l,normalizationTotal:q,normalizationType:p}=a,m=new f(a.field,h,{normalizationField:l,normalizationTotal:q,normalizationType:p},a.fieldIndex),u=yield r.expandSymbol(a.backgroundFillSymbol,
c,e);yield Promise.all(a.intervals.map(function(){var w=n._asyncToGenerator(function*(x){var D=yield r.expandSymbol(x.symbol,c,e);D=yield d.createTemplateGroup(D,u);m.add({min:x.min,max:x.max},D)});return function(x){return w.apply(this,arguments)}}()));if(a=yield r.expandSymbol(a.defaultSymbol,c,e))a=yield d.createTemplateGroup(a,u),m.setDefault(a);return m});return function(a,d,c,e){return b.apply(this,arguments)}}();var g=f.prototype;g.add=function(b,a){this._intervals.push({interval:b,result:a});
this._intervals.sort((d,c)=>d.interval.min-c.interval.min)};g.size=function(){return k.prototype.size.call(this)+this._intervals.length};g.match=function(b,a,d,c,e){if(null==this._fieldIndex&&!this._field)return this.getDefault();b=null!=this._fieldIndex?a.getComputedNumericAtIndex(this._fieldIndex):this._getValueFromField(a);if(!b&&(null===b||void 0===b||isNaN(b)))return this.getDefault();for(a=0;a<this._intervals.length;a++){const {interval:h,result:l}=this._intervals[a];d=this._isMaxInclusive?
b<=h.max:b<h.max;if(b>=h.min&&d)return l}return this.getDefault()};g._needsNormalization=function(){const b=this._normalizationInfo;return b&&(b.normalizationField||b.normalizationTotal||b.normalizationType)};g._getValueFromField=function(b){const a=b.readAttribute(this._field);if(!this._needsNormalization()||null==a)return a;const {normalizationField:d,normalizationTotal:c,normalizationType:e}=this._normalizationInfo;b=!!d&&b.readAttribute(d);if(e)switch(e){case "esriNormalizeByField":return(b||
void 0)&&a/b;case "esriNormalizeByLog":return Math.log(a)*Math.LOG10E;case "esriNormalizeByPercentOfTotal":return a/c*100;default:C.error(`Found unknown normalization type: ${e}`)}else C.error("Normalization is required, but no type was set!")};return f}(v),G=function(k){function f(b,a,d){var c=k.call(this)||this;c.type="map";c._nullResult=null;c._resultsMap=new Map;c._fieldsIndex=d;c._fields=b;c._seperator=a||"";return c}n._inheritsLoose(f,k);f.fromUVRenderer=function(){var b=n._asyncToGenerator(function*(a,
d,c,e){const h=a.fieldDelimiter,l=[a.field];a.field2&&l.push(a.field2);a.field3&&l.push(a.field3);const q=yield r.expandSymbol(a.backgroundFillSymbol,c,e),p=new f(l,h,a.fieldIndex);yield Promise.all(a.map.map(function(){var m=n._asyncToGenerator(function*(u){var w=yield r.expandSymbol(u.symbol,c,e);w=yield d.createTemplateGroup(w,q);"\x3cNull\x3e"===u.value?p.setNullResult(w):p.add(u.value,w)});return function(u){return m.apply(this,arguments)}}()));if(a=yield r.expandSymbol(a.defaultSymbol,c,e))a=
yield d.createTemplateGroup(a,q),p.setDefault(a);return p});return function(a,d,c,e){return b.apply(this,arguments)}}();var g=f.prototype;g.setNullResult=function(b){this._nullResult=b};g.add=function(b,a){this._resultsMap.set(b.toString(),a)};g.size=function(){return k.prototype.size.call(this)+this._resultsMap.size};g.match=function(b,a,d,c,e){if(null==this._fieldsIndex&&!this._fields)return this.getDefault();b=null!=this._fieldsIndex?a.getComputedStringAtIndex(this._fieldsIndex):this._getValueFromFields(a);
if(null!==this._nullResult&&(null==b||""===b||"\x3cNull\x3e"===b))return this._nullResult;if(!b&&null==b)return this.getDefault();b=b.toString();return this._resultsMap.has(b)?this._resultsMap.get(b):this.getDefault()};g._getValueFromFields=function(b){const a=[];for(const d of this._fields){const c=b.readAttribute(d);null==c||""===c?a.push("\x3cNull\x3e"):a.push(c)}return a.join(this._seperator)};return f}(v),B,I=function(k){function f(b,a,d,c,e){var h=k.call(this)||this;h.type="dictionary";h._groupIdCache=
new M(100);h._renderer=b;h._fieldMap=b.fieldMap;h._symbolFields=b.getSymbolFields();h._templates=a;h._info=d;h._scaleFn=c;h._schemaUtilsModule=e;return h}n._inheritsLoose(f,k);f.fromDictionaryRenderer=function(){var b=n._asyncToGenerator(function*(a,d,c,e){const [{default:h},l]=yield Promise.all([new Promise((q,p)=>E(["../../../../../renderers/DictionaryRenderer"],m=>q(Object.freeze({__proto__:null,default:m})),p)),R()]);a=h.fromJSON(a.renderer);yield a.fetchResources({spatialReference:c.spatialReference,
fields:c.fields});e=yield Q(a.scaleExpression,c);return new f(a,d,c,e,l)});return function(a,d,c,e){return b.apply(this,arguments)}}();var g=f.prototype;g._analyzeFeature=function(){var b=n._asyncToGenerator(function*(a,d,c,e,h){a=a.readLegacyFeature();const l=this._scaleFn(a,c,e);c=this._attributeHash(a)+"-"+l;const q=this._groupIdCache.get(c);if(q)return q;e=yield this._renderer.getSymbolAsync(a,{...e,spatialReference:this._info.spatialReference,abortOptions:h,fields:this._info.fields});e=this._schemaUtilsModule.createSymbolSchema(e,
this._renderer);d=r.expandSymbol(e,this._info,d,h).then(p=>{if("expanded-cim"!==p.type)return C.error(new K("mapview-bad-type",`Found unexpected type ${p.type} in dictionary response`)),null;p.hash+="-"+l;for(const m of p.layers)m.scaleFactor=l,m.templateHash+="-"+l,"text"===m.type&&"string"===typeof m.text&&-1<m.text.indexOf("[")&&(m.text=O.createLabelOverrideFunction(this._fieldMap,m.text,m.cim.textCase));return this._templates.createTemplateGroup(p,null)});this._groupIdCache.put(c,d,1);return d});
return function(a,d,c,e,h){return b.apply(this,arguments)}}();g.analyze=function(){var b=n._asyncToGenerator(function*(a,d,c,e,h,l){a=d.getCursor();for(d=[];a.next();)d.push(this._analyzeFeature(a,c,e,h,l));return Promise.all(d)});return function(a,d,c,e,h,l){return b.apply(this,arguments)}}();g.match=function(b,a,d,c,e){return null};g._attributeHash=function(b){let a="";for(const d of this._symbolFields){const c=this._fieldMap[d];c&&(a+=b.attributes[c]+"-")}return a};return f}(v);t.DictionaryMatcher=
I;t.FeatureMatcher=v;t.IntervalMatcher=H;t.MapMatcher=G;t.SubtypeMatcher=J;t.createMatcher=F;Object.defineProperty(t,"__esModule",{value:!0})});