// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../intl ../../request ../../core/Collection ../../core/deprecate ../../core/Error ../../core/Handles ../../core/lang ../../core/Loadable ../../core/Logger ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../portal/Portal ../../rest/geoprocessor/execute ../../rest/geoprocessor/GPOptions ../../core/has ../../geometry/support/normalizeUtils ../../layers/support/Field ../../layers/support/MapImage ../../core/urlUtils ../../core/unitUtils ../../rest/support/DataFile ../../rest/support/FeatureSet ../../rest/support/LinearUnit ../../rest/support/ParameterValue ../../rest/support/RasterData ../../rest/support/JobInfo ../../rest/print ../../rest/support/fileFormat ../../rest/support/layoutTemplate ../../rest/support/PrintParameters ../../rest/support/PrintTemplate ./CustomTemplate ../../intl/date".split(" "),
function(r,h,f,F,G,H,x,I,J,K,L,M,k,U,N,z,O,V,W,X,Y,Z,aa,ba,ca,da,ea,fa,ha,ia,P,A,y,Q,R,B,C){function S(p){p.layoutOptions||(p.layoutOptions={});p.layoutOptions.customTextElements||(p.layoutOptions.customTextElements=[]);p.layoutOptions.customTextElements.find(v=>"date"in v)||({customTextElements:p}=p.layoutOptions,p.push({date:C.formatDate(Date.now(),C.convertDateFormatToIntlOptions("short-date"))}))}const D=G.ofType(B);f=function(p){function v(a){a=p.call(this,a)||this;a._handles=new I;a.allowedFormats=
"all";a.allowedLayouts="all";a.defaultTemplates=new D;a.extraParameters=null;a.includeDefaultTemplates=!0;a.effectivePrintServiceUrl=null;a.error=null;a.portal=z.getDefault();a.printServiceUrl=null;a.templatesInfo=null;a.updateDelay=1E3;a.view=null;a.templateCustomTextElements=null;a.print=a.print.bind(r._assertThisInitialized(a));return a}r._inheritsLoose(v,p);var t=v.prototype;t.destroy=function(){this._handles.destroy();this.view=this._handles=null};t.load=function(){var a=r._asyncToGenerator(function*(c){this.addResolvingPromise(this._loadResources(c).catch(e=>
this.error=e));return this});return function(c){return a.apply(this,arguments)}}();t.print=function(){var a=r._asyncToGenerator(function*(c){const {view:e,extraParameters:g,updateDelay:l}=this;if(!e)throw new x("print:view-required","view is not set");S(c);c=new Q({view:e,template:c,extraParameters:g,updateDelay:l});try{return yield P.execute(this.effectivePrintServiceUrl,c)}catch(d){throw new x("print:export-error","An error occurred while exporting the web map.",{error:d});}});return function(c){return a.apply(this,
arguments)}}();t.toPrintTemplate=function({attributionEnabled:a,author:c,copyright:e,customTextElements:g,dpi:l,forceFeatureAttributes:d,format:b,height:q,layout:m,legendEnabled:u,title:n,scale:w,scaleEnabled:T,width:E}){a=new R({attributionVisible:a,layoutOptions:{authorText:c||"",copyrightText:e||"",customTextElements:g,titleText:n||""},forceFeatureAttributes:d,format:b,layout:m,scalePreserved:T,outScale:w});E&&(a.exportOptions.width=E);q&&(a.exportOptions.height=q);l&&(a.exportOptions.dpi=l);u||
(a.layoutOptions.legendLayers=[]);return a};t._loadResources=function(){var a=r._asyncToGenerator(function*(c){let e=[];var {printServiceUrl:g}=this;if(!g){var l;if(this.destroyed)return;({portal:g}=this);try{yield g.load(c)}catch(b){throw new x("print:could-not-load-portal","Cannot load print resource information from portal",{url:this.effectivePrintServiceUrl});}if(g=null==(l=g.helperServices)?void 0:l.printTask){var d;this._set("effectivePrintServiceUrl",g.url);e=(null!=(d=null==g?void 0:g.templates)?
d:[]).map(b=>B.fromJSON(b))}}0<e.length&&this.defaultTemplates.addMany(e);if(-1===this.effectivePrintServiceUrl.toLowerCase().split("/").indexOf("gpserver"))throw new x("print:invalid-print-service-url","Can't fetch print templates information from provided URL",{url:this.effectivePrintServiceUrl});this._serviceTemplateCustomTextElements=yield this._getTemplateToCustomTextElements(c);yield this._loadServiceDescription(c)});return function(c){return a.apply(this,arguments)}}();t._loadServiceDescription=
function(){var a=r._asyncToGenerator(function*(c){c=yield this._getPrintTemplatesFromService(c);this._set("templatesInfo",c)});return function(c){return a.apply(this,arguments)}}();t._getTemplateToCustomTextElements=function(){var a=r._asyncToGenerator(function*(c){const e={};try{const g=this.effectivePrintServiceUrl.replace(/(\/GPServer\/).+/i,"$1Get%20Layout%20Templates%20Info"),{results:[l]}=yield O.execute(g,null,null,M.unwrap(c));l.value.forEach(({layoutTemplate:d,layoutOptions:{customTextElements:b}})=>
e[y.fromJSON(d)]=b)}catch(g){}return Object.freeze(e)});return function(c){return a.apply(this,arguments)}}();t._getPrintTemplatesFromService=function(){var a=r._asyncToGenerator(function*(c){return F(this.effectivePrintServiceUrl,{...c,query:{f:"json"},timeout:6E4}).then(e=>{e=e&&e.data;let g=null,l=null;(e&&e.parameters).forEach(d=>{var b=d.choiceList&&d.choiceList.slice(),q;b&&b.length&&d.defaultValue&&(q=b.indexOf(d.defaultValue));-1<q&&(b.splice(q,1),b.unshift(d.defaultValue));q=(m,u)=>{const n=
"all"===u?m:m.filter(w=>-1<u.indexOf(w));return 0===n.length?m:n};if("Format"===d.name)b=q(b.map(A.fromJSON),this.allowedFormats),d=A.fromJSON(d.defaultValue),g={defaultValue:b.includes(d)?d:b[0],choiceList:b};else if("Layout_Template"===d.name){b=b.filter(n=>"map_only"!==n.toLowerCase());let m,u;b.some((n,w)=>{n=n.toLowerCase();if(-1<n.indexOf("letter")&&-1<n.indexOf("landscape"))return m=w,!0;-1<n.indexOf("a4")&&-1<n.indexOf("landscape")&&(m=w);return!1});m&&(u=b[m],b.splice(m,1),b.unshift(u));
b=q(b.map(y.fromJSON),this.allowedLayouts);d=y.fromJSON(d.defaultValue);l={defaultValue:b.includes(d)?d:b[0],choiceList:b}}});this.error=null;return{format:g,layout:l}}).catch(e=>{throw new x("print:unavailable-service-info","Can't fetch templates info from service",{error:e});})});return function(c){return a.apply(this,arguments)}}();r._createClass(v,[{key:"effectiveTemplateCustomTextElements",get:function(){if(!this._serviceTemplateCustomTextElements)return{};const a=J.clone(this._serviceTemplateCustomTextElements);
this.templateCustomTextElements&&Object.keys(this.templateCustomTextElements).forEach(c=>{const e=a[c];if(e){const g=this.templateCustomTextElements[c];e.forEach(l=>{const [d]=Object.entries(l)[0];g.find(b=>{const [q,m]=Object.entries(b)[0];d===q&&(l[d]=m)})})}});return Object.freeze(a)}},{key:"state",get:function(){return"loading"===this.loadStatus?"initializing":this.error||"failed"===this.loadStatus?"error":this.get("view.ready")&&"loaded"===this.loadStatus?"ready":"disabled"}},{key:"scaleEnabled",
set:function(a){H.deprecatedProperty(L.getLogger(this.declaredClass),"scaleEnabled",{version:"4.22"});this.set("scaleEnabled",a)}}]);return v}(K);h.__decorate([k.property()],f.prototype,"_serviceTemplateCustomTextElements",void 0);h.__decorate([k.property()],f.prototype,"allowedFormats",void 0);h.__decorate([k.property()],f.prototype,"allowedLayouts",void 0);h.__decorate([k.property({type:D})],f.prototype,"defaultTemplates",void 0);h.__decorate([k.property()],f.prototype,"extraParameters",void 0);
h.__decorate([k.property()],f.prototype,"includeDefaultTemplates",void 0);h.__decorate([k.property({aliasOf:{source:"printServiceUrl",overridable:!0},readOnly:!0})],f.prototype,"effectivePrintServiceUrl",void 0);h.__decorate([k.property()],f.prototype,"effectiveTemplateCustomTextElements",null);h.__decorate([k.property()],f.prototype,"error",void 0);h.__decorate([k.property({type:z})],f.prototype,"portal",void 0);h.__decorate([k.property()],f.prototype,"printServiceUrl",void 0);h.__decorate([k.property({readOnly:!0})],
f.prototype,"state",null);h.__decorate([k.property()],f.prototype,"scaleEnabled",null);h.__decorate([k.property({readOnly:!0})],f.prototype,"templatesInfo",void 0);h.__decorate([k.property()],f.prototype,"updateDelay",void 0);h.__decorate([k.property()],f.prototype,"view",void 0);h.__decorate([k.property()],f.prototype,"templateCustomTextElements",void 0);return f=h.__decorate([N.subclass("esri.widgets.Print.PrintViewModel")],f)});