// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/deprecate ../../core/lang ../../core/Logger ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../tasks/Locator ./SearchSource ./support/locatorUtils".split(" "),function(e,c,m,n,a,d,w,t,u,v,p){var h;const q=a.getLogger("esri.widgets.Search.LocatorSearchSource");a=h=function(r){function f(g){var b=r.call(this,g)||this;b.apiKey=null;b.categories=
null;b.countryCode=null;b.defaultZoomScale=null;b.localSearchDisabled=!1;b.locationType=null;b.name="";b.placeholder="";b.searchTemplate="";b.singleLineFieldName=null;b.suggestionsEnabled=null;b.url=null;b.zoomScale=null;b.getResults=(k,l)=>p.getResults({source:e._assertThisInitialized(b),...k},l);b.getSuggestions=(k,l)=>p.getSuggestions({source:e._assertThisInitialized(b),...k},l);return b}e._inheritsLoose(f,r);f.prototype.clone=function(){return new h({apiKey:this.apiKey,autoNavigate:this.autoNavigate,
filter:this.filter,maxResults:this.maxResults,maxSuggestions:this.maxSuggestions,minSuggestCharacters:this.minSuggestCharacters,outFields:this.outFields?n.clone(this.outFields):null,placeholder:this.placeholder,popupEnabled:this.popupEnabled,prefix:this.prefix,resultGraphicEnabled:this.resultGraphicEnabled,resultSymbol:this.resultSymbol?this.resultSymbol.clone():null,suggestionsEnabled:this.suggestionsEnabled,suffix:this.suffix,withinViewEnabled:this.withinViewEnabled,categories:this.categories?n.clone(this.categories):
null,countryCode:this.countryCode,locationType:this.locationType,locator:this.locator,searchTemplate:this.searchTemplate,singleLineFieldName:this.singleLineFieldName,zoomScale:this.zoomScale})};e._createClass(f,[{key:"locator",get:function(){m.deprecatedProperty(q,"locator",{replacement:"url",version:"4.22"});return this._get("locator")},set:function(g){m.deprecatedProperty(q,"locator",{replacement:"url",version:"4.22"});this._set("url",g.url);this._set("locator",g)}}]);return f}(v);c.__decorate([d.property()],
a.prototype,"apiKey",void 0);c.__decorate([d.property()],a.prototype,"categories",void 0);c.__decorate([d.property()],a.prototype,"countryCode",void 0);c.__decorate([d.property({json:{write:!0}})],a.prototype,"defaultZoomScale",void 0);c.__decorate([d.property()],a.prototype,"localSearchDisabled",void 0);c.__decorate([d.property({type:u,json:{read:!1,write:!1}})],a.prototype,"locator",null);c.__decorate([d.property()],a.prototype,"locationType",void 0);c.__decorate([d.property({json:{write:!0}})],
a.prototype,"name",void 0);c.__decorate([d.property({json:{write:!0}})],a.prototype,"placeholder",void 0);c.__decorate([d.property()],a.prototype,"searchTemplate",void 0);c.__decorate([d.property({json:{write:!0}})],a.prototype,"singleLineFieldName",void 0);c.__decorate([d.property({json:{read:{source:"suggest"},write:{target:"suggest"}}})],a.prototype,"suggestionsEnabled",void 0);c.__decorate([d.property({json:{write:!0}})],a.prototype,"url",void 0);c.__decorate([d.property({json:{write:!0}})],a.prototype,
"zoomScale",void 0);return a=h=c.__decorate([t.subclass("esri.widgets.Search.LocatorSearchSource")],a)});