// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/mat3 ../../../../chunks/mat3f32 ../../../../chunks/vec2f32 ../../../../chunks/vec3f32 ../../../../geometry/support/normalizeUtils ../../../webgl/BufferObject ../../../webgl/FramebufferObject ../../../webgl/Program ../../../webgl/enums ../../../webgl/Texture ../../../webgl/VertexArrayObject ../../engine/DisplayObject ../../engine/webgl/Utils".split(" "),function(w,n,r,x,y,z,t,I,A,J,K,B,C,D){const E=Math.PI/180,u=()=>D.createProgramDescriptor("bounds",
{geometry:[{location:0,name:"a_position",count:2,type:5126}]});return function(v){function p(c){var a=v.call(this)||this;a._dvsMat3=r.create();a._localOrigin={x:0,y:0};a._getBounds=c;return a}w._inheritsLoose(p,v);var m=p.prototype;m.destroy=function(){this._vao&&(this._vao.dispose(!0),this._indexBuffer=this._vertexBuffer=this._vao=null);this._program&&(this._program.dispose(),this._program=null)};m.doRender=function(c){const {context:a}=c,h=this._getBounds();1>h.length||(this._createShaderProgram(a),
this._updateMatricesAndLocalOrigin(c),this._updateBufferData(a,h),a.setBlendingEnabled(!0),a.setDepthTestEnabled(!1),a.setStencilWriteMask(0),a.setStencilTestEnabled(!1),a.setBlendFunction(1,771),a.setColorMask(!0,!0,!0,!0),c=this._program,a.bindVAO(this._vao),a.useProgram(c),c.setUniformMatrix3fv("u_dvsMat3",this._dvsMat3),a.gl.lineWidth(1),a.drawElements(1,8*h.length,5125,0),a.bindVAO())};m._createTransforms=function(){return{dvs:r.create()}};m._createShaderProgram=function(c){this._program||(this._program=
new A.Program(c,"precision highp float;\n        uniform mat3 u_dvsMat3;\n\n        attribute vec2 a_position;\n\n        void main() {\n          mediump vec3 pos \x3d u_dvsMat3 * vec3(a_position, 1.0);\n          gl_Position \x3d vec4(pos.xy, 0.0, 1.0);\n        }","precision mediump float;\n      void main() {\n        gl_FragColor \x3d vec4(0.75, 0.0, 0.0, 0.75);\n      }",u().attributes))};m._updateMatricesAndLocalOrigin=function(c){var {state:a}=c;const {displayMat3:h,size:k,resolution:d,pixelRatio:e,
rotation:b,viewpoint:f}=a;c=E*b;const {x:g,y:F}=f.targetGeometry;a=z.normalizeMapX(g,a.spatialReference);this._localOrigin.x=a;this._localOrigin.y=F;a=e*k[0];const q=e*k[1],G=d*a,H=d*q,l=n.identity(this._dvsMat3);n.multiply(l,l,h);n.translate(l,l,x.fromValues(a/2,q/2));n.scale(l,l,y.fromValues(k[0]/G,-q/H,1));n.rotate(l,l,-c)};m._updateBufferData=function(c,a){const {x:h,y:k}=this._localOrigin,d=new Float32Array(8*a.length),e=new Uint32Array(8*a.length);let b=0,f=0;for(const g of a)g&&(d[2*b]=g[0]-
h,d[2*b+1]=g[1]-k,d[2*b+2]=g[0]-h,d[2*b+3]=g[3]-k,d[2*b+4]=g[2]-h,d[2*b+5]=g[3]-k,d[2*b+6]=g[2]-h,d[2*b+7]=g[1]-k,e[f+0]=b+0,e[f+1]=b+3,e[f+2]=b+3,e[f+3]=b+2,e[f+4]=b+2,e[f+5]=b+1,e[f+6]=b+1,e[f+7]=b+0,b+=4,f+=8);this._vertexBuffer?this._vertexBuffer.setData(d.buffer):this._vertexBuffer=t.createVertex(c,35048,d.buffer);this._indexBuffer?this._indexBuffer.setData(e):this._indexBuffer=t.createIndex(c,35048,e);this._vao||(a=u(),this._vao=new B(c,a.attributes,a.bufferLayouts,{geometry:this._vertexBuffer},
this._indexBuffer))};return p}(C.DisplayObject)});