// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/has ../../../../../../core/maybe ../../../../../../core/promiseUtils ../../../../../../geometry/libtess ../../DisplayId ../templates/WGLLabelTemplate ../templates/WGLMarkerTemplate ../templates/WGLTemplateStore".split(" "),function(v,r,w,p,x,z,A,y,B,q){w=function(){function t(c,a,b){this._loadPromise=z.loadLibtess();this._geometryType=c;this._idField=a;this._templateStore=b}var n=t.prototype;n.update=function(c,
a){p.isSome(c.mesh.labels)&&(this._labelTemplates=this._createLabelTemplates(c.mesh.labels,a));this._schema=c};n._createLabelTemplates=function(c,a){const b=new Map;if("simple"===c.type){for(var e of c.classes)c=y.fromLabelClass(e,a),b.set(e.index,c);return b}for(const g in c.classes){e=c.classes[g];for(const d of e)e=y.fromLabelClass(d,a),b.set(d.index,e)}return b};n.analyze=function(){var c=r._asyncToGenerator(function*(a,b,e,g,d,f,l){if(!x.isAborted(l)){var h;"dictionary"===e.type&&(h=yield e.analyze(this._idField,
a.copy(),b,d,f,l));for(b=0;a.next();){var k=void 0;k=h?h[b++]:p.isSome(g)&&A.isAggregateId(a.getDisplayId())&&1!==a.readAttribute("cluster_count")?g.match(this._idField,a,this._geometryType,d,f):e.match(this._idField,a,this._geometryType,d,f);a.setGroupId(k);if(q.isDynamicId(k)){k=this._templateStore.getDynamicTemplateGroup(k);for(const m of k)m&&m.analyze&&m.analyze(this._templateStore,a,d,f)}}yield this._loadPromise;return this._templateStore.finalize(l)}});return function(a,b,e,g,d,f,l){return c.apply(this,
arguments)}}();n.analyzeGraphics=function(){var c=r._asyncToGenerator(function*(a,b,e,g,d,f){if(!x.isAborted(f)){a=a.getCursor();for(e&&(yield e.analyze(this._idField,a.copy(),b,g,d,f));a.next();){b=a.getGroupId();if(null==b||-1===b)b=e.match(this._idField,a,a.geometryType,g,d),a.setGroupId(b);if(q.isDynamicId(b)){const l=this._templateStore.getDynamicTemplateGroup(b);for(const h of l)h&&h.analyze&&h.analyze(this._templateStore,a,g,d)}a.setGroupId(b)}yield this._loadPromise;return this._templateStore.finalize(f)}});
return function(a,b,e,g,d,f){return c.apply(this,arguments)}}();n.writeGraphic=function(c,a,b){const e=a.getGroupId(),g=a.getDisplayId(),d=this._templateStore.getTemplateGroup(e);c.featureStart(a.insertAfter,0);if(null!=g){if(q.isDynamicId(e))for(const f of d)f&&f.bindFeature(a,null,null);if(d){for(const f of d)f&&f.write(c,a,b);c.featureEnd()}}};n.writeCursor=function(c,a,b,e,g,d){const f=a.getGroupId(),l=a.getDisplayId(),h=this._templateStore.getTemplateGroup(f),k=this._schema.mesh.sortKey;let m=
0;p.isSome(k)&&(m=null!=k.fieldIndex?a.getComputedNumericAtIndex(k.fieldIndex):null!=k.field?a.readAttribute(k.field):a.readAttribute(this._idField),m*="asc"===k.order?1:-1);c.featureStart(0,null==m||isNaN(m)?0:m);if(null!=l&&h){if(q.isDynamicId(f))for(const u of h)u.bindFeature(a,b,e);for(const u of h)u.write(c,a,g);p.isSome(d)&&c.hasRecords&&(b=d&&this._findLabelRef(h),this._writeLabels(c,a,d,b,g));c.featureEnd()}};n._findLabelRef=function(c){for(const a of c)if(a instanceof B)return a;return null};
n._writeLabels=function(c,a,b,e,g){for(const d of b)if(p.isSome(d)&&d){const {glyphs:f,rtl:l,index:h}=d;b=this._labelTemplates.get(h);b.setZoomLevel(g);b.bindReferenceTemplate(e);b.bindTextInfo(f,l);b.write(c,a,null)}};r._createClass(t,[{key:"templates",get:function(){return this._templateStore}}]);return t}();v.WGLMeshFactory=w;Object.defineProperty(v,"__esModule",{value:!0})});