// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../chunks/_rollupPluginBabelHelpers ../geometry ../request ../core/maybe ../geometry/support/normalizeUtils ./utils ./support/ImageAngleResult ./support/ImageIdentifyResult ./support/ImageSampleResult ./support/ImagePixelLocationResult ../geometry/SpatialReference".split(" "),function(h,k,J,l,m,q,g,D,E,F,G,z){function A(b){const a=null==b?void 0:b.time;if(a&&(null!=a.start||null!=a.end)){const c=[];null!=a.start&&c.push(a.start);null!=a.end&&-1===c.indexOf(a.end)&&c.push(a.end);b.time=
c.join(",")}}function B(b,a,c){return r.apply(this,arguments)}function r(){r=k._asyncToGenerator(function*(b,a,c){b=g.parseUrl(b);var d=yield q.normalizeCentralMeridian(a.geometry?[a.geometry]:[]);a=a.toJSON();A(a);d=d&&d[0];m.isSome(d)&&(a.geometry=d.toJSON());b=g.encode({...b.query,f:"json",...a});return g.asValidOptions(b,c)});return r.apply(this,arguments)}function t(){t=k._asyncToGenerator(function*(b,a,c){var d,e=a.toJSON();m.isSome(e.angleName)&&(e.angleName=e.angleName.join(","));m.isSome(a.point)&&
null!=(d=a.point.spatialReference)&&d.imageCoordinateSystem&&(e.point.spatialReference=n(a.point.spatialReference));m.isSome(a.spatialReference)&&a.spatialReference.imageCoordinateSystem&&(e.spatialReference=C(a.spatialReference));b=g.parseUrl(b);e=g.encode({...b.query,f:"json",...e});c=g.asValidOptions(e,c);({data:c}=yield l(`${b.path}/computeAngles`,c));c.spatialReference=c.spatialReference?null!=c.spatialReference.geodataXform?new z({wkid:0,imageCoordinateSystem:c.spatialReference}):z.fromJSON(c.spatialReference):
null;"NaN"===c.north&&(c.north=null);"NaN"===c.up&&(c.up=null);return new D(c)});return t.apply(this,arguments)}function u(){u=k._asyncToGenerator(function*(b,a,c){var d=a.toJSON();({geometries:a}=a);for(let f=0;f<a.length;f++){var e;null!=(e=a[f].spatialReference)&&e.imageCoordinateSystem&&(d.geometries.geometries[f].spatialReference=n(a[f].spatialReference))}b=g.parseUrl(b);d=g.encode({...b.query,f:"json",...d});c=g.asValidOptions(d,c);({data:c}=yield l(`${b.path}/computePixelLocation`,c));return G.fromJSON(c)});
return u.apply(this,arguments)}function v(){v=k._asyncToGenerator(function*(b,a,c){a=yield B(b,a,c);b=g.parseUrl(b);({data:b}=yield l(`${b.path}/computeStatisticsHistograms`,a));({statistics:a}=b);null!=a&&a.length&&a.forEach(d=>{d.avg=d.mean;d.stddev=d.standardDeviation});return{statistics:a,histograms:b.histograms}});return v.apply(this,arguments)}function w(){w=k._asyncToGenerator(function*(b,a,c){a=yield B(b,a,c);b=g.parseUrl(b);({data:b}=yield l(`${b.path}/computeHistograms`,a));return{histograms:b.histograms}});
return w.apply(this,arguments)}function x(){x=k._asyncToGenerator(function*(b,a,c){var d,e,f=a.toJSON();A(f);null!=(d=f.outFields)&&d.length&&(f.outFields=f.outFields.join(","));a=yield q.normalizeCentralMeridian(a.geometry);a=null==a?void 0:a[0];m.isSome(a)&&(f.geometry=a.toJSON());b=g.parseUrl(b);f=g.encode({...b.query,f:"json",...f});c=g.asValidOptions(f,c);({data:c}=yield l(`${b.path}/getSamples`,c));c=null==c?void 0:null==(e=c.samples)?void 0:e.map(p=>{const I="NaN"===p.value||""===p.value?null:
p.value.split(" ").map(H=>Number(H));return{...p,pixelValue:I}});return F.fromJSON({samples:c})});return x.apply(this,arguments)}function y(){y=k._asyncToGenerator(function*(b,a,c){const d=g.parseUrl(b);return q.normalizeCentralMeridian(a.geometry?[a.geometry]:[]).then(e=>{var f=a.toJSON();e=e&&e[0];m.isSome(e)&&(f.geometry=JSON.stringify(e.toJSON()));f=g.encode({...d.query,f:"json",...f});f=g.asValidOptions(f,c);return l(d.path+"/identify",f)}).then(e=>E.fromJSON(e.data))});return y.apply(this,arguments)}
function n(b){const {imageCoordinateSystem:a}=b;if(a){const {id:c,referenceServiceName:d}=a;return null!=c?d?{icsid:c,icsns:d}:{icsid:c}:{ics:a}}return b.toJSON()}function C(b,a){b=n(b);const {icsid:c,icsns:d,wkid:e}=b;return null!=c?null==d||null!=a&&a.toLowerCase().includes("/"+d.toLowerCase()+"/")?`0:${c}`:JSON.stringify(b):e?e.toString():JSON.stringify(b)}h.computeAngles=function(b,a,c){return t.apply(this,arguments)};h.computeHistograms=function(b,a,c){return w.apply(this,arguments)};h.computePixelSpaceLocations=
function(b,a,c){return u.apply(this,arguments)};h.computeStatisticsHistograms=function(b,a,c){return v.apply(this,arguments)};h.getImageSpatialReferenceJSON=n;h.getImageSpatialReferenceQueryParameter=C;h.getSamples=function(b,a,c){return x.apply(this,arguments)};h.identify=function(b,a,c){return y.apply(this,arguments)};Object.defineProperty(h,"__esModule",{value:!0})});