// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/mat3f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../support/buffer/InterleavedLayout ../core/shaderLibrary/util/AlphaDiscard.glsl ../lib/GLMaterialTexture ../lib/Material ../lib/OrderIndependentTransparency ../lib/verticalOffsetUtils ./internal/bufferWriterUtils ./internal/MaterialUtil ../shaders/DefaultMaterialTechnique ../shaders/RealisticTreeTechnique".split(" "),function(q,u,F,h,m,v,G,H,w,I,J,K,x,y,L){function z(f){let e=
v.newLayout();e=f.instancedDoublePrecision?e.vec3f("modelOriginHi").vec3f("modelOriginLo").mat3f("model").mat3f("modelNormal"):e.mat4f("model").mat4f("modelNormal");f.instanced&&-1<f.instanced.indexOf("color")&&(e=e.vec4f("instanceColor"));f.instanced&&-1<f.instanced.indexOf("featureAttribute")&&(e=e.vec4f("instanceFeatureAttribute"));return e}let T=function(f){function e(a){var b=f.call(this,a,M)||this;b.supportsEdges=!0;b.techniqueConfig=new y.DefaultMaterialTechniqueConfiguration;{var c=b.parameters;
const k=c.textureId||c.normalTextureId||c.metallicRoughnessTextureId||c.emissiveTextureId||c.occlusionTextureId,g=v.newLayout().vec3f("position").vec3f("normal");c.vertexTangents&&g.vec4f("tangent");k&&g.vec2f("uv0");c.vertexColors&&g.vec4u8("color");c.symbolColors&&g.vec4u8("symbolColor");c=g}b.vertexBufferLayout=c;b.instanceBufferLayout=a.instanced?z(b.parameters):null;return b}u._inheritsLoose(e,f);var d=e.prototype;d.isVisibleInPass=function(a){return 4===a||6===a||7===a?this.parameters.castShadows:
!0};d.isVisible=function(){var a=this.parameters;if(!f.prototype.isVisible.call(this)||0===a.layerOpacity)return!1;var b=a.instanced;const c=a.vertexColors,k=a.symbolColors;b=!!b&&-1<b.indexOf("color");const g=a.vvColorEnabled,l="replace"===a.colorMixMode,n=0<a.opacity;a=a.externalColor&&0<a.externalColor[3];return c&&(b||g||k)?l?!0:n:c?l?a:n:b||g||k?l?!0:n:l?a:n};d.getTechniqueConfig=function(a,b){this.techniqueConfig.output=a;this.techniqueConfig.hasNormalTexture=!!this.parameters.normalTextureId;
this.techniqueConfig.hasColorTexture=!!this.parameters.textureId;this.techniqueConfig.vertexTangents=this.parameters.vertexTangents;this.techniqueConfig.instanced=!!this.parameters.instanced;this.techniqueConfig.instancedDoublePrecision=this.parameters.instancedDoublePrecision;this.techniqueConfig.vvSize=this.parameters.vvSizeEnabled;this.techniqueConfig.verticalOffset=null!==this.parameters.verticalOffset;this.techniqueConfig.screenSizePerspective=null!==this.parameters.screenSizePerspective;this.techniqueConfig.slicePlaneEnabled=
this.parameters.slicePlaneEnabled;this.techniqueConfig.sliceHighlightDisabled=this.parameters.sliceHighlightDisabled;this.techniqueConfig.alphaDiscardMode=this.parameters.textureAlphaMode;this.techniqueConfig.normalsTypeDerivate="screenDerivative"===this.parameters.normals?!0:!1;this.techniqueConfig.transparent=this.parameters.transparent;this.techniqueConfig.writeDepth=this.parameters.writeDepth;this.techniqueConfig.sceneHasOcludees=this.parameters.sceneHasOcludees;this.techniqueConfig.cullFace=
this.parameters.slicePlaneEnabled?0:this.parameters.cullFace;this.techniqueConfig.multipassTerrainEnabled=b.multipassTerrainEnabled;this.techniqueConfig.cullAboveGround=b.cullAboveGround;if(0===a||7===a)this.techniqueConfig.vertexColors=this.parameters.vertexColors,this.techniqueConfig.symbolColors=this.parameters.symbolColors,this.techniqueConfig.doubleSidedMode=this.parameters.treeRendering?2:this.parameters.doubleSided&&"normal"===this.parameters.doubleSidedType?1:this.parameters.doubleSided&&
"winding-order"===this.parameters.doubleSidedType?2:0,this.techniqueConfig.instancedColor=!!this.parameters.instanced&&-1<this.parameters.instanced.indexOf("color"),this.techniqueConfig.receiveShadows=this.parameters.receiveShadows&&this.parameters.shadowMappingEnabled,this.techniqueConfig.receiveAmbientOcclusion=b.ssaoEnabled?this.parameters.receiveSSAO:!1,this.techniqueConfig.vvColor=this.parameters.vvColorEnabled,this.techniqueConfig.textureAlphaPremultiplied=!!this.parameters.textureAlphaPremultiplied,
this.techniqueConfig.usePBR=this.parameters.usePBR,this.techniqueConfig.hasMetalnessAndRoughnessTexture=!!this.parameters.metallicRoughnessTextureId,this.techniqueConfig.hasEmissionTexture=!!this.parameters.emissiveTextureId,this.techniqueConfig.hasOcclusionTexture=!!this.parameters.occlusionTextureId,this.techniqueConfig.offsetBackfaces=!(!this.parameters.transparent||!this.parameters.offsetTransparentBackfaces),this.techniqueConfig.isSchematic=this.parameters.usePBR&&this.parameters.isSchematic,
this.techniqueConfig.transparencyPassType=b.transparencyPassType,this.techniqueConfig.enableOffset=b.camera.relativeElevation<I.OITPolygonOffsetLimit;return this.techniqueConfig};d.intersect=function(a,b,c,k,g,l,n){if(null!==this.parameters.verticalOffset){const A=k.camera;h.set(r,c[12],c[13],c[14]);c=null;switch(k.viewingMode){case 1:c=h.normalize(B,r);break;case 2:c=h.copy(B,N)}let C=0;if(null!==this.parameters.verticalOffset){var p=h.subtract(O,r,A.eye);const D=h.length(p);p=h.scale(p,p,1/D);let E=
null;this.parameters.screenSizePerspective&&(E=h.dot(c,p));C+=x.verticalOffsetAtDistance(A,D,this.parameters.verticalOffset,E,this.parameters.screenSizePerspective)}h.scale(c,c,C);h.transformMat3(t,c,k.transform.inverseRotation);g=h.subtract(P,g,t);l=h.subtract(Q,l,t)}x.intersectTriangleGeometry(a,b,k,g,l,J.getVerticalOffsetObject3D(k.verticalOffset),n)};d.requiresSlot=function(a){return a===(this.parameters.transparent?this.parameters.writeDepth?4:7:2)||20===a};d.createGLMaterial=function(a){return 0===
a.output||7===a.output||1===a.output||2===a.output||3===a.output||4===a.output?new R(a):null};d.createBufferWriter=function(){return new S(this.vertexBufferLayout,this.instanceBufferLayout)};return e}(w.Material),R=function(f){function e(a){return f.call(this,{...a,...a.material.parameters})||this}u._inheritsLoose(e,f);var d=e.prototype;d.updateParameters=function(a){const b=this._material.parameters;this.updateTexture(b.textureId);return this.ensureTechnique(b.treeRendering?L.RealisticTreeTechnique:
y.DefaultMaterialTechnique,a)};d._updateShadowState=function(a){a.shadowMappingEnabled!==this._material.parameters.shadowMappingEnabled&&this._material.setParameters({shadowMappingEnabled:a.shadowMappingEnabled})};d._updateOccludeeState=function(a){a.hasOccludees!==this._material.parameters.sceneHasOcludees&&this._material.setParameters({sceneHasOcludees:a.hasOccludees})};d.beginSlot=function(a){if(0===this._output||7===this._output)this._updateShadowState(a),this._updateOccludeeState(a);return this.updateParameters(a)};
d.bind=function(a,b){b.bindPass(this._material.parameters,a);this.bindTextures(b.program)};return e}(H);const M={textureId:void 0,initTextureTransparent:!1,isSchematic:!1,usePBR:!1,normalTextureId:void 0,vertexTangents:!1,occlusionTextureId:void 0,emissiveTextureId:void 0,metallicRoughnessTextureId:void 0,emissiveFactor:[0,0,0],mrrFactors:[0,1,.5],ambient:[.2,.2,.2],diffuse:[.8,.8,.8],externalColor:[1,1,1,1],colorMixMode:"multiply",opacity:1,layerOpacity:1,vertexColors:!1,symbolColors:!1,doubleSided:!1,
doubleSidedType:"normal",cullFace:2,instanced:void 0,instancedDoublePrecision:!1,normals:"default",receiveSSAO:!0,receiveShadows:!0,castShadows:!0,shadowMappingEnabled:!1,verticalOffset:null,screenSizePerspective:null,slicePlaneEnabled:!1,sliceHighlightDisabled:!1,offsetTransparentBackfaces:!1,vvSizeEnabled:!1,vvSizeMinSize:[1,1,1],vvSizeMaxSize:[100,100,100],vvSizeOffset:[0,0,0],vvSizeFactor:[1,1,1],vvSizeValue:[1,1,1],vvColorEnabled:!1,vvColorValues:[0,0,0,0,0,0,0,0],vvColorColors:[1,0,0,0,1,0,
0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],vvSymbolAnchor:[0,0,0],vvSymbolRotationMatrix:F.create(),transparent:!1,writeDepth:!0,textureAlphaMode:0,textureAlphaCutoff:G.defaultMaskAlphaCutoff,textureAlphaPremultiplied:!1,sceneHasOcludees:!1,...w.materialParametersDefaults};let S=function(){function f(d,a){this.vertexBufferLayout=d;this.instanceBufferLayout=a}var e=f.prototype;e.allocate=function(d){return this.vertexBufferLayout.createBuffer(d)};e.elementCount=function(d){return d.indices.get("position").length};
e.write=function(d,a,b,c){K.writeDefaultAttributes(a,this.vertexBufferLayout,d.transformation,d.invTranspTransformation,b,c)};return f}();const P=m.create(),Q=m.create(),N=m.fromValues(0,0,1),B=m.create(),t=m.create(),r=m.create(),O=m.create();q.DefaultMaterial=T;q.getInstanceBufferLayout=z;Object.defineProperty(q,"__esModule",{value:!0})});