// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/mathUtils ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/mat3 ../../../../chunks/mat3f64 ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec2 ../../../../chunks/vec2f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../core/libs/gl-matrix-2/types/mat4 ../../../../geometry/support/aaBoundingRect ../../support/buffer/InterleavedLayout ../lib/geometryDataUtils ../lib/GLMaterials ../lib/GLMaterialTexture ../lib/Material ../lib/screenSizePerspectiveUtils ../lib/Util ./internal/bufferWriterUtils ./internal/MaterialUtil ./renderers/utils ../../../../chunks/HUDMaterial.glsl ../shaders/HUDMaterialTechnique".split(" "),
function(Q,K,ca,I,da,R,S,ea,T,fa,U,h,D,ha,ia,ja,ka,la,ma,V,J,na,G,oa,pa,W,L){function qa(q,n,f,a=ra){fa.copy(a,q.anchorPos);a[0]*=-n[0];a[1]*=-n[1];a[0]+=q.screenOffset[0]*f;a[1]+=q.screenOffset[1]*f;return a}function X(q,n,f,a,b,d,c,g){n=n-b-(0<g[0]?a[0]*g[0]:0);let e=n+a[0]+2*b;f=f-b-(0<g[1]?a[1]*g[1]:0);b=f+a[1]+2*b;c.textureIsSignedDistanceField&&(c=c.distanceFieldBoundingBox,n+=a[0]*c[0],f+=a[1]*c[1],e-=a[0]*(1-c[2]),b-=a[1]*(1-c[3]),n-=d,e+=d,f-=d,b+=d);return q[0]>n&&q[0]<e&&q[1]>f&&q[1]<b}
let ya=function(q){function n(a){a=q.call(this,a,sa)||this;a.techniqueConfig=new L.HUDMaterialTechniqueConfiguration;return a}K._inheritsLoose(n,q);var f=n.prototype;f.getTechniqueConfig=function(a,b){this.techniqueConfig.output=a;this.techniqueConfig.slicePlaneEnabled=this.parameters.slicePlaneEnabled;this.techniqueConfig.verticalOffset=!!this.parameters.verticalOffset;this.techniqueConfig.screenSizePerspective=!!this.parameters.screenSizePerspective;this.techniqueConfig.screenCenterOffsetUnitsEnabled=
"screen"===this.parameters.centerOffsetUnits?1:0;this.techniqueConfig.polygonOffsetEnabled=this.parameters.polygonOffset;this.techniqueConfig.isDraped=this.parameters.isDraped;this.techniqueConfig.occlusionTestEnabled=this.parameters.occlusionTest;this.techniqueConfig.pixelSnappingEnabled=this.parameters.pixelSnappingEnabled;this.techniqueConfig.sdf=this.parameters.textureIsSignedDistanceField;this.techniqueConfig.vvSize=!!this.parameters.vvSizeEnabled;this.techniqueConfig.vvColor=!!this.parameters.vvColorEnabled;
0===a&&(this.techniqueConfig.debugDrawBorder=!!this.parameters.debugDrawBorder);4===a&&(this.techniqueConfig.binaryHighlightOcclusion=this.parameters.binaryHighlightOcclusion);this.techniqueConfig.depthEnabled=this.parameters.depthEnabled;this.techniqueConfig.transparencyPassType=b.transparencyPassType;this.techniqueConfig.multipassGeometryEnabled=b.multipassGeometryEnabled;this.techniqueConfig.multipassTerrainEnabled=b.multipassTerrainEnabled;this.techniqueConfig.cullAboveGround=b.cullAboveGround;
return this.techniqueConfig};f.intersect=function(a,b,d,c,g,e,p,l,k){I.isSome(k)?this.intersectDrapedHudGeometry(a,e,p,l,k):this.intersectHudGeometry(a,b,d,c,p,l)};f.intersectDrapedHudGeometry=function(a,b,d,c,g){const e=a.vertexAttributes.get("position"),p=a.vertexAttributes.get("size"),l=this.parameters,k=W.calculateAnchorPosForRendering(l);let u=1;var v=1;I.isSome(c)&&(v=c(Y),u=v[0],v=v[5]);u*=a.screenToWorldRatio;v*=a.screenToWorldRatio;c=2*a.screenToWorldRatio;for(let z=0;z<e.data.length/e.size;z++){var r=
z*e.size;const A=e.data[r];r=e.data[r+1];const w=z*p.size;B[0]=p.data[w]*u;B[1]=p.data[w+1]*v;let m;l.textureIsSignedDistanceField&&(m=l.outlineSize*a.screenToWorldRatio/2);X(b,A,r,B,c,m,l,k)&&d(g.dist,g.normal,-1,!0)}};f.intersectHudGeometry=function(a,b,d,c,g,e){if(c.options.selectionMode&&c.options.hud&&!pa.isInstanceHidden(b)){b=this.parameters;var p=1,l=1;R.fromMat4(M,d);if(I.isSome(e)){l=e(Y);p=l[0];l=l[5];{e=M;var k=e[0],u=e[1],v=e[2],r=e[3],z=e[4],A=e[5],w=e[6],m=e[7],x=e[8],C=1/Math.sqrt(k*
k+u*u+v*v);const F=1/Math.sqrt(r*r+z*z+A*A),N=1/Math.sqrt(w*w+m*m+x*x);e[0]=k*C;e[1]=u*C;e[2]=v*C;e[3]=r*F;e[4]=z*F;e[5]=A*F;e[6]=w*N;e[7]=m*N;e[8]=x*N}}e=a.vertexAttributes.get("position");k=a.vertexAttributes.get("size");u=a.vertexAttributes.get("normal");a=a.vertexAttributes.get("auxpos1");na.assert(3<=e.size);v=c.point;r=c.camera;z=W.calculateAnchorPosForRendering(b);p*=r.pixelRatio;l*=r.pixelRatio;A="screen"===this.parameters.centerOffsetUnits;for(w=0;w<e.data.length/e.size;w++)if(m=w*e.size,
h.set(t,e.data[m],e.data[m+1],e.data[m+2]),h.transformMat4(t,t,d),m=w*k.size,B[0]=k.data[m]*p,B[1]=k.data[m+1]*l,h.transformMat4(t,t,r.viewMatrix),m=w*a.size,h.set(y,a.data[m+0],a.data[m+1],a.data[m+2]),A||(t[0]+=y[0],t[1]+=y[1],0!==y[2]&&(m=y[2],h.normalize(y,t),h.subtract(t,t,h.scale(y,y,m)))),m=w*u.size,h.set(H,u.data[m],u.data[m+1],u.data[m+2]),this.normalAndViewAngle(H,M,r,O),this.applyVerticalOffsetTransformationView(t,O,r,P),r.applyProjection(t,E),-1<E[0]){m=Math.floor(E[0])+this.parameters.screenOffset[0];
x=Math.floor(E[1])+this.parameters.screenOffset[1];A&&(m+=y[0],0!==y[1]&&(x+=J.applyScaleFactor(y[1],P.factorAlignment)));J.applyPrecomputedScaleFactor(B,P.factor,B);C=1*r.pixelRatio;let F;b.textureIsSignedDistanceField&&(F=b.outlineSize*r.pixelRatio/2);X(v,m,x,B,C,F,b,z)&&(x=c.ray,h.transformMat4(Z,t,ea.invert(ta,r.viewMatrix)),E[0]=v[0],E[1]=v[1],r.unprojectFromRenderScreen(E,t)&&(m=D.create(),h.copy(m,x.direction),C=1/h.length(m),h.scale(m,m,C),x=h.distance(x.origin,t)*C,g(x,m,-1,!0,1,Z)))}}};
f.computeAttachmentOrigin=function(a,b){var d=a.vertexAttributes;if(!d)return!1;d=d.get("position");a=a.indices.get("position");return ka.computeAttachmentOriginPoints(d,a,b)};f.createBufferWriter=function(){return new ua(this)};f.normalAndViewAngle=function(a,b,d,c){ha.isMat4(b)&&(b=R.fromMat4(va,b));h.transformMat3(c.normal,a,b);h.transformMat4(c.normal,c.normal,d.viewInverseTransposeMatrix);c.cosAngle=h.dot(aa,wa);return c};f.updateScaleInfo=function(a,b,d){const c=this.parameters;c.screenSizePerspective?
J.precomputeScaleFactor(d,b,c.screenSizePerspective,a.factor):(a.factor.scale=1,a.factor.factor=0,a.factor.minPixelSize=0,a.factor.paddingPixels=0);c.screenSizePerspectiveAlignment?J.precomputeScaleFactor(d,b,c.screenSizePerspectiveAlignment,a.factorAlignment):(a.factorAlignment.factor=a.factor.factor,a.factorAlignment.scale=a.factor.scale,a.factorAlignment.minPixelSize=a.factor.minPixelSize,a.factorAlignment.paddingPixels=a.factor.paddingPixels)};f.applyShaderOffsetsView=function(a,b,d,c,g,e,p){b=
this.normalAndViewAngle(b,d,g,O);this.applyVerticalGroundOffsetView(a,b,g,p);this.applyVerticalOffsetTransformationView(p,b,g,e);this.applyPolygonOffsetView(p,b,c[3],g,p);this.applyCenterOffsetView(p,c,p);return p};f.applyShaderOffsetsNDC=function(a,b,d,c,g){this.applyCenterOffsetNDC(a,b,d,c);I.isSome(g)&&h.copy(g,c);this.applyPolygonOffsetNDC(c,b,d,c);return c};f.applyPolygonOffsetView=function(a,b,d,c,g){var e=c.aboveGround?1:-1;d=Math.sign(d);0===d&&(d=e);e*=d;if(0>=this.parameters.shaderPolygonOffset)return h.copy(g,
a);b=ca.clamp(Math.abs(b.cosAngle),.01,1);c=1-Math.sqrt(1-b*b)/b/c.viewport[2];0<e?h.scale(g,a,c):h.scale(g,a,1/c);return g};f.applyVerticalGroundOffsetView=function(a,b,d,c){const g=h.length(a),e=d.aboveGround?1:-1;d=.5*d.computeRenderPixelSizeAtDist(g);b=h.scale(t,b.normal,e*d);h.add(c,a,b);return c};f.applyVerticalOffsetTransformationView=function(a,b,d,c){const g=this.parameters;if(!g.verticalOffset||!g.verticalOffset.screenLength){if(g.screenSizePerspective||g.screenSizePerspectiveAlignment){var e=
h.length(a);this.updateScaleInfo(c,e,b.cosAngle)}else c.factor.scale=1,c.factorAlignment.scale=1;return a}e=h.length(a);d=oa.verticalOffsetAtDistance(d,e,g.verticalOffset,b.cosAngle,g.screenSizePerspectiveAlignment||g.screenSizePerspective);this.updateScaleInfo(c,e,b.cosAngle);h.scale(b.normal,b.normal,d);return h.add(a,a,b.normal)};f.applyCenterOffsetView=function(a,b,d){const c="screen"!==this.parameters.centerOffsetUnits;d!==a&&h.copy(d,a);c&&(d[0]+=b[0],d[1]+=b[1],b[2]&&(h.normalize(H,d),h.add(d,
d,h.scale(H,H,b[2]))));return d};f.applyCenterOffsetNDC=function(a,b,d,c){const g="screen"!==this.parameters.centerOffsetUnits;c!==a&&h.copy(c,a);g||(c[0]+=b[0]/d.fullWidth*2,c[1]+=b[1]/d.fullHeight*2);return c};f.applyPolygonOffsetNDC=function(a,b,d,c){const g=this.parameters.shaderPolygonOffset;a!==c&&h.copy(c,a);g&&(a=d.aboveGround?1:-1,c[2]-=(a*Math.sign(b[3])||a)*g);return c};f.requiresSlot=function(a,b){b=la.outputFromPass(b);if(0===b||7===b){if(20===a)return!0;b=this.parameters.drawInSecondSlot?
17:16;return this.parameters.occlusionTest?11===a||a===b:a===b}return a===(this.parameters.drawInSecondSlot?17:16)||20===a};f.createGLMaterial=function(a){return 0===a.output||7===a.output?new xa(a):4===a.output?new ba(a):null};f.calculateRelativeScreenBounds=function(a,b,d=ia.create()){qa(this.parameters,a,b,d);d[2]=d[0]+a[0];d[3]=d[1]+a[1];return d};return n}(V.Material),ba=function(q){function n(a){return q.call(this,{...a,...a.material.parameters})||this}K._inheritsLoose(n,q);var f=n.prototype;
f.updateParameters=function(a){this.updateTexture(this._material.parameters.textureId);return this.selectProgram(a)};f.selectProgram=function(a){return this.ensureTechnique(L.HUDMaterialTechnique,a)};f.beginSlot=function(a){return this.updateParameters(a)};f.bind=function(a,b){this.bindTextures(b.program);this.bindTextureScale(b.program);b.bindPass(this._material.parameters,a)};return n}(ma),xa=function(q){function n(){return q.apply(this,arguments)||this}K._inheritsLoose(n,q);var f=n.prototype;f.isOcclusionSlot=
function(a){return 11===a.slot&&this._material.parameters.occlusionTest&&(0===this._output||7===this._output)};f.selectProgram=function(a){return this.ensureTechnique(L.HUDMaterialTechnique,a,this.isOcclusionSlot(a)?6:this._output)};f.bind=function(a,b){this.isOcclusionSlot(a)||(this.bindTextures(b.program),this.bindTextureScale(b.program));b.bindPass(this._material.parameters,a)};return n}(ba);const P={factor:{scale:0,factor:0,minPixelSize:0,paddingPixels:0},factorAlignment:{scale:0,factor:0,minPixelSize:0,
paddingPixels:0}},ra=U.create(),t=D.create(),H=D.create(),E=da.createRenderScreenPointArray3(),aa=D.create(),Z=D.create(),M=S.create(),va=S.create(),ta=T.create(),y=D.create(),O={normal:aa,cosAngle:0},Y=T.create(),B=[0,0],wa=D.fromValues(0,0,1),sa={texCoordScale:[1,1],occlusionTest:!0,binaryHighlightOcclusion:!0,drawInSecondSlot:!1,color:[1,1,1,1],outlineColor:[1,1,1,1],outlineSize:0,textureIsSignedDistanceField:!1,distanceFieldBoundingBox:null,vvSizeEnabled:!1,vvSizeMinSize:[1,1,1],vvSizeMaxSize:[100,
100,100],vvSizeOffset:[0,0,0],vvSizeFactor:[1,1,1],vvColorEnabled:!1,vvColorValues:[0,0,0,0,0,0,0,0],vvColorColors:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],screenOffset:[0,0],verticalOffset:null,screenSizePerspective:null,screenSizePerspectiveAlignment:null,slicePlaneEnabled:!1,anchorPos:U.fromValues(.5,.5),shaderPolygonOffset:1E-5,polygonOffset:!1,textureId:null,centerOffsetUnits:"world",depthEnabled:!0,pixelSnappingEnabled:!0,debugDrawBorder:!1,isDraped:!1,...V.materialParametersDefaults},
za=ja.newLayout().vec3f("position").vec3f("normal").vec2f("uv0").vec4u8("color").vec2f("size").vec4f("auxpos1").vec4f("auxpos2");let ua=function(){function q(f){this.material=f;this.vertexBufferLayout=za}var n=q.prototype;n.allocate=function(f){return this.vertexBufferLayout.createBuffer(f)};n.elementCount=function(f){return 6*f.indices.get("position").length};n.write=function(f,a,b,d){G.writePosition(a.indices.get("position"),a.vertexAttributes.get("position").data,f.transformation,b.position,d,
6);G.writeNormal(a.indices.get("normal"),a.vertexAttributes.get("normal").data,f.invTranspTransformation,b.normal,d,6);var c=a.vertexAttributes.get("uv0").data;if(null==c||4>c.length){c=this.material.parameters;var g=f=0;var e=c.texCoordScale[0];c=c.texCoordScale[1]}else f=c[0],g=c[1],e=c[2],c=c[3];e=Math.min(1.99999,e+1);c=Math.min(1.99999,c+1);var p=a.indices.get("position").length,l=b.uv0,k=d;for(var u=0;u<p;++u)l.set(k,0,f),l.set(k,1,g),k+=1,l.set(k,0,e),l.set(k,1,g),k+=1,l.set(k,0,e),l.set(k,
1,c),k+=1,l.set(k,0,e),l.set(k,1,c),k+=1,l.set(k,0,f),l.set(k,1,c),k+=1,l.set(k,0,f),l.set(k,1,g),k+=1;G.writeColor(a.indices.get("color"),a.vertexAttributes.get("color").data,4,b.color,d,6);f=a.indices.get("size");g=a.vertexAttributes.get("size").data;e=f.length;c=b.size;p=d;for(l=0;l<e;++l){k=g[2*f[l]];u=g[2*f[l]+1];for(let v=0;6>v;++v)c.set(p,0,k),c.set(p,1,u),p+=1}a.indices.get("auxpos1")&&a.vertexAttributes.get("auxpos1")&&G.writeBufferVec4(a.indices.get("auxpos1"),a.vertexAttributes.get("auxpos1").data,
b.auxpos1,d,6);a.indices.get("auxpos2")&&a.vertexAttributes.get("auxpos2")&&G.writeBufferVec4(a.indices.get("auxpos2"),a.vertexAttributes.get("auxpos2").data,b.auxpos2,d,6)};return q}();Q.HUDMaterial=ya;Object.defineProperty(Q,"__esModule",{value:!0})});