// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/mathUtils ../../../../core/maybe ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/buffer/BufferView ../../support/buffer/InterleavedLayout ../lib/geometryDataUtils ../lib/GLMaterial ../lib/Material ../lib/PathGeometry ../lib/Util ./PathTechnique ./VisualVariableMaterialParameters ./internal/bufferWriterUtils ./internal/MaterialUtil".split(" "),function(r,t,u,v,B,C,D,E,F,w,G,p,q,H,x,I){const J=p.assert;
p=function(h){function g(a){a=h.call(this,a,K)||this;a.supportsEdges=!0;a._vertexAttributeLocations=q.pathVertexAttributeLocations;a.techniqueConfig=new q.PathTechniqueConfiguration;a.vertexBufferLayout=g.getVertexBufferLayout(a.parameters);return a}t._inheritsLoose(g,h);var b=g.prototype;b.getTechniqueConfig=function(a,c){this.techniqueConfig.output=a;this.techniqueConfig.vvSize=this.parameters.vvSizeEnabled;this.techniqueConfig.vvColor=this.parameters.vvColorEnabled;this.techniqueConfig.vvOpacity=
this.parameters.vvOpacityEnabled;this.techniqueConfig.slicePlaneEnabled=this.parameters.slicePlaneEnabled;this.techniqueConfig.transparent=this.parameters.transparent;this.techniqueConfig.sceneHasOcludees=this.parameters.sceneHasOcludees;if(0===a||7===a)this.techniqueConfig.doubleSidedMode=this.parameters.doubleSided&&"normal"===this.parameters.doubleSidedType?1:this.parameters.doubleSided&&"winding-order"===this.parameters.doubleSidedType?2:0,this.techniqueConfig.receiveShadows=this.parameters.receiveShadows,
this.techniqueConfig.receiveSSAO=c.ssaoEnabled?this.parameters.receiveSSAO:!1;this.techniqueConfig.transparencyPassType=c.transparencyPassType;this.techniqueConfig.multipassTerrainEnabled=c.multipassTerrainEnabled;this.techniqueConfig.cullAboveGround=c.cullAboveGround;return this.techniqueConfig};b.getPassParameters=function(){return this.parameters};b.isVisibleInPass=function(a){return 4===a||6===a||7===a?this.parameters.castShadows:!0};b.isVisible=function(){const a=this.parameters;return h.prototype.isVisible.call(this)?
0<a.opacity:!1};b.intersect=function(a,c,e,k,f,l,n){if(G.isPathGeometry(a)){c=a.path;e=[this.parameters.size[0],this.parameters.size[1]];if(this.parameters.vvSizeEnabled){var d=this.parameters.vvSizeOffset,m=this.parameters.vvSizeFactor;const y=this.parameters.vvSizeMinSize,z=this.parameters.vvSizeMaxSize,A=c.sizeAttributeValue;e[0]*=u.clamp(d[0]+A*m[0],y[0],z[0]);e[1]*=u.clamp(d[2]+A*m[2],y[2],z[2])}d=Math.max(e[0],e[1]);a=a.boundingInfo;v.isNone(a)?this._intersectTriangles(c,e,f,l,n):(a=B.fromValues(a.bbMin[0]-
d,a.bbMin[1]-d,a.bbMin[2]-d,a.bbMax[0]+d,a.bbMax[1]+d,a.bbMax[2]+d),d=[l[0]-f[0],l[1]-f[1],l[2]-f[2]],m=Math.sqrt(d[0]*d[0]+d[1]*d[1]+d[2]*d[2]),I.intersectAabbInvDir(a,f,[m/d[0],m/d[1],m/d[2]],k.tolerance)&&this._intersectTriangles(c,e,f,l,n))}};b._intersectTriangles=function(a,c,e,k,f){a.baked.size&&a.baked.size[0]===c[0]&&a.baked.size[1]===c[1]||a.baked.bake(c);a.baked.intersect(e,k,f)};b.computeAttachmentOrigin=function(a,c){a=a.vertexAttributes;if(!a)return null;a=a.get("position");return E.computeAttachmentOriginLines(a,
null,!1,c)};b.createBufferWriter=function(){return new L(this.vertexBufferLayout)};b.requiresSlot=function(a){return a===(this.parameters.transparent?4:2)||20===a};b.createGLMaterial=function(a){return 0===a.output||7===a.output||1===a.output||2===a.output||4===a.output||3===a.output&&this.parameters.castShadows?new M(a):null};g.getVertexBufferLayout=function(a){let c=D.newLayout().vec3f("position").vec4f("profileRight").vec4f("profileUp").vec4f("profileVertexAndNormal");if(a.vvColorEnabled||a.vvSizeEnabled||
a.vvOpacityEnabled)c=c.vec4f("featureValue");return c};return g}(w.Material);let M=function(h){function g(){return h.apply(this,arguments)||this}t._inheritsLoose(g,h);var b=g.prototype;b.updateParameters=function(a){return this.ensureTechnique(q.PathTechnique,a)};b._updateOccludeeState=function(a){a.hasOccludees!==this._material.parameters.sceneHasOcludees&&this._material.setParameters({sceneHasOcludees:a.hasOccludees})};b._updateShadowState=function(a){(v.isNone(this.technique)||a.shadowMappingEnabled!==
this.technique.configuration.receiveShadows)&&this._material.setParameters({receiveShadows:a.shadowMappingEnabled})};b.beginSlot=function(a){if(0===this._output||7===this._output)this._updateShadowState(a),this._updateOccludeeState(a);return this.updateParameters(a)};b.bind=function(a,c){c.bindPass(this._material.getPassParameters(),a)};return g}(F);const K={size:[1,1,1],ambient:[.2,.2,.2],diffuse:[.8,.8,.8],specular:[0,0,0],opacity:1,doubleSided:!1,doubleSidedType:"normal",receiveSSAO:!0,receiveShadows:!1,
castShadows:!0,slicePlaneEnabled:!1,transparent:!1,sceneHasOcludees:!1,...H.Default,...w.materialParametersDefaults};let L=function(){function h(b){this.vertexBufferLayout=b}var g=h.prototype;g.allocate=function(b){return this.vertexBufferLayout.createBuffer(b)};g.elementCount=function(b){return b.indices.get("position").length};g.write=function(b,a,c,e){const k=f=>{if(a.vertexAttributes.has(f)){const l=a.vertexAttributes.get(f),n=a.indices.get(f);J(4===l.size);const d=c.getField(f,C.BufferViewVec4f);
if(d)x.writeBufferVec4(n,l.data,d,e);else throw Error("unable to acquire view for "+f);}};k("profileRight");k("profileUp");k("profileVertexAndNormal");this.vertexBufferLayout.hasField("featureValue")&&k("featureValue");x.writeDefaultAttributes(a,this.vertexBufferLayout,b.transformation,b.invTranspTransformation,c,e)};return h}();r.PathMaterial=p;Object.defineProperty(r,"__esModule",{value:!0})});