// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../geometry/support/buffer/BufferView ../../support/buffer/InterleavedLayout ../lib/GLMaterial ../lib/GLMaterials ../lib/Material ../lib/OrderIndependentTransparency ../lib/Util ./internal/bufferWriterUtils ./internal/DefaultBufferWriter ./internal/MaterialUtil ../shaders/PatternTechnique".split(" "),function(y,r,n,A,B,C,z,D,p,t,E,F,u){let J=function(m){function l(a){a=m.call(this,a,G)||this;a.supportsEdges=!0;a._vertexAttributeLocations=
u.patternVertexAttributeLocations;a.techniqueConfig=new u.PatternTechniqueConfiguration;return a}r._inheritsLoose(l,m);var f=l.prototype;f.getTechniqueConfig=function(a,b){this.techniqueConfig.output=a;this.techniqueConfig.cullFace=this.parameters.cullFace;this.techniqueConfig.vertexColors=this.parameters.vertexColors;this.techniqueConfig.slicePlaneEnabled=this.parameters.slicePlaneEnabled;this.techniqueConfig.polygonOffset=this.parameters.polygonOffset;this.techniqueConfig.writeDepth=this.parameters.writeDepth;
this.techniqueConfig.style=this.parameters.style;this.techniqueConfig.patternSpacing=this.parameters.patternSpacing;this.techniqueConfig.lineWidth=this.parameters.lineWidth;this.techniqueConfig.draped=this.parameters.draped;this.techniqueConfig.transparencyPassType=b.transparencyPassType;this.techniqueConfig.enableOffset=b.camera.relativeElevation<D.OITPolygonOffsetLimit;this.techniqueConfig.multipassTerrainEnabled=b.multipassTerrainEnabled;this.techniqueConfig.cullAboveGround=b.cullAboveGround;return this.techniqueConfig};
f.getPassParameters=function(){return this.parameters};f.intersect=function(a,b,c,k,d,g,e){F.intersectTriangleGeometry(a,b,k,d,g,void 0,e)};f.requiresSlot=function(a,b){return 20===a?!0:4===C.outputFromPass(b)?2===a:a===(this.parameters.writeDepth?4:7)};f.createGLMaterial=function(a){return 0===a.output||7===a.output||4===a.output||1===a.output&&this.parameters.writeLinearDepth?new H(a):null};f.createBufferWriter=function(){const a=A.newLayout().vec3f("position").vec4u8("color").vec4f("uvMapSpace");
this.parameters.draped||a.mat3f("boundingRect");return new I(a)};return l}(z.Material),H=function(m){function l(){return m.apply(this,arguments)||this}r._inheritsLoose(l,m);var f=l.prototype;f.updateParameters=function(a){return this.ensureTechnique(u.PatternTechnique,a)};f._updateOccludeeState=function(a){a.hasOccludees!==this._material.parameters.sceneHasOcludees&&this._material.setParameters({sceneHasOcludees:a.hasOccludees})};f.beginSlot=function(a){0!==this._output&&7!==this._output||this._updateOccludeeState(a);
return this.updateParameters(a)};f.bind=function(a,b){b.bindPass(this._material.getPassParameters(),a)};return l}(B),I=function(m){function l(){return m.apply(this,arguments)||this}r._inheritsLoose(l,m);var f=l.prototype;f.write=function(a,b,c,k){for(const g of this.vertexBufferLayout.fieldNames){const e=b.vertexAttributes.get(g),h=b.indices.get(g);if(e&&h)switch(g){case "position":p.assert(3===e.size);var d=c.getField(g,n.BufferViewVec3f);d&&t.writePosition(h,e.data,a.transformation,d,k);break;case "color":p.assert(3===
e.size||4===e.size);(d=c.getField(g,n.BufferViewVec4u8))&&t.writeColor(h,e.data,e.size,d,k);break;case "uvMapSpace":p.assert(4===e.size);(d=c.getField(g,n.BufferViewVec4f))&&t.writeBufferVec4(h,e.data,d,k);break;case "boundingRect":p.assert(9===e.size),(d=c.getField(g,n.BufferViewMat3f))&&this.writeBoundingRect(h,e.data,a.transformation,d,k)}}};f.writeBoundingRect=function(a,b,c,k,d){const g=k.typedBuffer;k=k.typedBufferStride;const e=a.length;d*=k;for(let v=0;v<e;++v){const q=9*a[v];var h=b[q];const w=
b[q+1],x=b[q+2];g[d]=c[0]*h+c[4]*w+c[8]*x+c[12];g[d+1]=c[1]*h+c[5]*w+c[9]*x+c[13];g[d+2]=c[2]*h+c[6]*w+c[10]*x+c[14];for(h=3;9>h;++h)g[d+h]=b[q+h];d+=k}};return l}(E.DefaultBufferWriter);const G={color:[1,1,1,1],writeDepth:!0,writeLinearDepth:!1,vertexColors:!1,polygonOffset:!1,slicePlaneEnabled:!1,cullFace:0,sceneHasOcludees:!1,style:2,patternSpacing:10,lineWidth:1,draped:!0,...z.materialParametersDefaults};y.PatternMaterial=J;Object.defineProperty(y,"__esModule",{value:!0})});