// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/Logger ../../../../core/mathUtils ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/vec2 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/support/lineSegment ../../../../geometry/support/plane ../../support/buffer/InterleavedLayout ../lib/geometryDataUtils ../lib/GLMaterial ../lib/GLMaterials ../lib/Material ../lib/Util ./VisualVariableMaterialParameters ./renderers/utils ../../../../chunks/RibbonLine.glsl ../shaders/RibbonLineTechnique".split(" "),
function(da,ea,T,U,Q,N,ma,g,B,J,u,na,oa,pa,qa,fa,ra,sa,ta,ua,V){function ha(D,w,b,a,c){for(let k=0;k<c;k++)b[a++]=D[w++];return a}function W(D,w,b){w=w.get("position").data;b=b?b.get("position"):null;return D.isClosed?b?2<b.length:6<w.length:!1}const va=T.getLogger("esri.views.3d.webgl-engine.materials.RibbonLineMaterial");T=function(D){function w(a){a=D.call(this,a,wa)||this;a._vertexAttributeLocations=V.ribbonVertexAttributeLocations;a.techniqueConfig=new V.RibbonLineTechniqueConfiguration;a.layout=
a.createLayout();return a}ea._inheritsLoose(w,D);var b=w.prototype;b.isClosed=function(a,c){return this.parameters.isClosed?c?2<c.length:6<a.length:!1};b.dispose=function(){};b.getPassParameters=function(){return this.parameters};b.getTechniqueConfig=function(a,c){this.techniqueConfig.output=a;this.techniqueConfig.draped=20===c.slot;a=Q.isSome(this.parameters.stipplePattern);this.techniqueConfig.stippleEnabled=a;this.techniqueConfig.stippleOffColorEnabled=a&&Q.isSome(this.parameters.stippleOffColor);
this.techniqueConfig.stippleScaleWithLineWidth=a&&this.parameters.stippleScaleWithLineWidth;this.techniqueConfig.stipplePreferContinuous=a&&this.parameters.stipplePreferContinuous;this.techniqueConfig.slicePlaneEnabled=this.parameters.slicePlaneEnabled;this.techniqueConfig.sceneHasOcludees=this.parameters.sceneHasOcludees;this.techniqueConfig.roundJoins="round"===this.parameters.join;this.techniqueConfig.roundCaps=2===this.parameters.cap;this.techniqueConfig.transparent=this.parameters.transparent;
this.techniqueConfig.polygonOffset=this.parameters.polygonOffset;this.techniqueConfig.writeDepth=this.parameters.writeDepth;this.techniqueConfig.vvColor=this.parameters.vvColorEnabled;this.techniqueConfig.vvOpacity=this.parameters.vvOpacityEnabled;this.techniqueConfig.vvSize=this.parameters.vvSizeEnabled;this.techniqueConfig.innerColorEnabled=0<this.parameters.innerWidth&&Q.isSome(this.parameters.innerColor);this.techniqueConfig.falloffEnabled=0<this.parameters.falloff;this.techniqueConfig.occluder=
8===this.parameters.renderOccluded;this.techniqueConfig.transparencyPassType=c.transparencyPassType;this.techniqueConfig.multipassTerrainEnabled=c.multipassTerrainEnabled;this.techniqueConfig.cullAboveGround=c.cullAboveGround;return this.techniqueConfig};b.intersect=function(a,c,k,l,m,e,d,f,h){Q.isSome(h)?this.intersectDrapedLineGeometry(a,l,h,e,d):this.intersectLineGeometry(a,c,k,l,d)};b.intersectDrapedLineGeometry=function(a,c,k,l,m){if(c.options.selectionMode){c=a.vertexAttributes.get("position").data;
var e=a.vertexAttributes.get("size"),d=this.parameters.width;this.parameters.vvSizeEnabled?(e=a.vertexAttributes.get("sizeFeatureAttribute").data[0],d*=U.clamp(this.parameters.vvSizeOffset[0]+e*this.parameters.vvSizeFactor[0],this.parameters.vvSizeMinSize[0],this.parameters.vvSizeMaxSize[0])):e&&(d*=e.data[0]);e=l[0];l=l[1];a=(d/2+4)*a.screenToWorldRatio;d=Number.MAX_VALUE;var f=0;for(let C=0;C<c.length-5;C+=3){var h=c[C],t=c[C+1],E=e-h,n=l-t;h=c[C+3]-h;t=c[C+4]-t;const R=U.clamp((h*E+t*n)/(h*h+t*
t),0,1);E=h*R-E;n=t*R-n;n=E*E+n*n;n<d&&(d=n,f=C/3)}d<a*a&&m(k.dist,k.normal,f,!1)}};b.intersectLineGeometry=function(a,c,k,l,m){if(l.options.selectionMode&&!ta.isInstanceHidden(c))if(ra.isTranslationMatrix(k)){var e=a.vertexAttributes,d=e.get("position").data;c=this.parameters.width;if(this.parameters.vvSizeEnabled){var f=e.get("sizeFeatureAttribute").data[0];c*=U.clamp(this.parameters.vvSizeOffset[0]+f*this.parameters.vvSizeFactor[0],this.parameters.vvSizeMinSize[0],this.parameters.vvSizeMaxSize[0])}else e.has("size")&&
(c*=e.get("size").data[0]);var h=l.camera,t=xa;ma.copy(t,l.point);f=c*h.pixelRatio/2+4*h.pixelRatio;g.set(S[0],t[0]-f,t[1]+f,0);g.set(S[1],t[0]+f,t[1]+f,0);g.set(S[2],t[0]+f,t[1]-f,0);g.set(S[3],t[0]-f,t[1]-f,0);for(c=0;4>c;c++)if(!h.unprojectFromRenderScreen(S[c],H[c]))return;u.fromPoints(h.eye,H[0],H[1],X);u.fromPoints(h.eye,H[1],H[2],Y);u.fromPoints(h.eye,H[2],H[3],Z);u.fromPoints(h.eye,H[3],H[0],aa);var E=Number.MAX_VALUE;c=0;a=W(this.parameters,e,a.indices)?d.length-2:d.length-5;for(e=0;e<a;e+=
3){y[0]=d[e]+k[12];y[1]=d[e+1]+k[13];y[2]=d[e+2]+k[14];var n=(e+3)%d.length;z[0]=d[n]+k[12];z[1]=d[n+1]+k[13];z[2]=d[n+2]+k[14];if(!(0>u.signedDistance(X,y)&&0>u.signedDistance(X,z)||0>u.signedDistance(Y,y)&&0>u.signedDistance(Y,z)||0>u.signedDistance(Z,y)&&0>u.signedDistance(Z,z)||0>u.signedDistance(aa,y)&&0>u.signedDistance(aa,z))){h.projectToRenderScreen(y,K);h.projectToRenderScreen(z,L);if(0>K[2]&&0<L[2])g.subtract(F,y,z),n=h.frustum,n=-u.signedDistance(n[4],y)/g.dot(F,u.normal(n[4])),g.scale(F,
F,n),g.add(y,y,F),h.projectToRenderScreen(y,K);else if(0<K[2]&&0>L[2])g.subtract(F,z,y),n=h.frustum,n=-u.signedDistance(n[4],z)/g.dot(F,u.normal(n[4])),g.scale(F,F,n),g.add(z,z,F),h.projectToRenderScreen(z,L);else if(0>K[2]&&0>L[2])continue;K[2]=0;L[2]=0;n=J.distance2(J.fromPoints(K,L,ia),t);n<E&&(E=n,g.copy(ja,y),g.copy(ka,z),c=e/3)}}k=l.rayBegin;l=l.rayEnd;E<f*f&&(d=Number.MAX_VALUE,J.closestLineSegmentPoint(J.fromPoints(ja,ka,ia),J.fromPoints(k,l,ya),M)&&(g.subtract(M,M,k),d=g.length(M),g.scale(M,
M,1/d),d/=g.distance(k,l)),m(d,M,c,!1))}else va.error("intersection assumes a translation-only matrix")};b.computeAttachmentOrigin=function(a,c){const k=a.vertexAttributes;if(!k)return null;a=a.indices;const l=k.get("position");return oa.computeAttachmentOriginLines(l,a?a.get("position"):null,a&&W(this.parameters,k,a),c)};b.createLayout=function(){const a=na.newLayout().vec3f("position").f32("subdivisionFactor").vec2f("uv0").vec3f("auxpos1").vec3f("auxpos2");this.parameters.vvSizeEnabled?a.f32("sizeFeatureAttribute"):
a.f32("size");this.parameters.vvColorEnabled?a.f32("colorFeatureAttribute"):a.vec4f("color");this.parameters.vvOpacityEnabled&&a.f32("opacityFeatureAttribute");return a};b.createBufferWriter=function(){return new za(this.layout,this.parameters)};b.requiresSlot=function(a,c){if(20===a)return!0;if(8===this.parameters.renderOccluded)return 2===a||9===a||10===a;c=qa.outputFromPass(c);return 0===c||7===c?a===(this.parameters.writeDepth?4:7):2===a};b.createGLMaterial=function(a){return 0===a.output||7===
a.output||4===a.output||1===a.output?new Aa(a):null};b.validateParameters=function(a){"miter"!==a.join&&(a.miterLimit=0);this.requiresTransparent(a)&&(a.transparent=!0)};b.requiresTransparent=function(a){return!!(1>(a.color&&a.color[3])||0<a.innerWidth&&this.colorRequiresTransparent(a.innerColor)||a.stipplePattern&&this.colorRequiresTransparent(a.stippleOffColor)||0<a.falloff)};b.colorRequiresTransparent=function(a){return Q.isSome(a)&&1>a[3]&&0<a[3]};return w}(fa.Material);let Aa=function(D){function w(){return D.apply(this,
arguments)||this}ea._inheritsLoose(w,D);var b=w.prototype;b.updateParameters=function(a){return this.ensureTechnique(V.RibbonLineTechnique,a)};b._updateOccludeeState=function(a){a.hasOccludees!==this._material.parameters.sceneHasOcludees&&this._material.setParameters({sceneHasOcludees:a.hasOccludees})};b.beginSlot=function(a){0!==this._output&&7!==this._output||this._updateOccludeeState(a);return this.updateParameters(a)};b.bind=function(a,c){c.bindPass(this._material.getPassParameters(),a)};return w}(pa);
const wa={width:0,color:[1,1,1,1],join:"miter",cap:0,miterLimit:5,writeDepth:!0,polygonOffset:!1,stipplePattern:null,stippleOffColor:null,stippleScaleWithLineWidth:!1,stipplePreferContinuous:!0,slicePlaneEnabled:!1,vvFastUpdate:!1,transparent:!1,isClosed:!1,falloff:0,innerWidth:0,innerColor:null,sceneHasOcludees:!1,...fa.materialParametersDefaults,...sa.Default};let za=function(){function D(b,a){this.parameters=a;this.numJoinSubdivisions=0;this.vertexBufferLayout=b;b=a.stipplePattern?1:0;switch(this.parameters.join){case "miter":case "bevel":this.numJoinSubdivisions=
b;break;case "round":this.numJoinSubdivisions=ua.NUM_ROUND_JOIN_SUBDIVISIONS+b}}var w=D.prototype;w.isClosed=function(b){return W(this.parameters,b.vertexAttributes,b.indices)};w.numCapSubdivisions=function(b){if(this.isClosed(b))return 0;switch(this.parameters.cap){case 1:case 2:return 1;default:return 0}};w.allocate=function(b){return this.vertexBufferLayout.createBuffer(b)};w.elementCount=function(b){var a=2*this.numCapSubdivisions(b)+2,c=b.indices.get("position").length/2+1;const k=this.isClosed(b);
a=k?2:2*a;var l=k?0:1;c=k?c:c-1;if(b.vertexAttributes.has("subdivisions"))for(b=b.vertexAttributes.get("subdivisions").data;l<c;++l)a+=4+2*b[l];else a+=(c-l)*(2*this.numJoinSubdivisions+4);return a+2};w.write=function(b,a,c,k){var l;const m=Ba,e=Ca,d=Da;var f=a.vertexAttributes.get("position").data,h=a.indices&&a.indices.get("position");const t=null==(l=a.vertexAttributes.get("distanceToStart"))?void 0:l.data;l=this.numCapSubdivisions(a);h&&h.length!==2*(f.length/3-1)&&console.warn("RibbonLineMaterial does not support indices");
h=null;a.vertexAttributes.has("subdivisions")&&(h=a.vertexAttributes.get("subdivisions").data);let E=1,n=0;this.parameters.vvSizeEnabled?n=a.vertexAttributes.get("sizeFeatureAttribute").data[0]:a.vertexAttributes.has("size")&&(E=a.vertexAttributes.get("size").data[0]);let C=[1,1,1,1],R=0;this.parameters.vvColorEnabled?R=a.vertexAttributes.get("colorFeatureAttribute").data[0]:a.vertexAttributes.has("color")&&(C=a.vertexAttributes.get("color").data);let la=0;this.parameters.vvOpacityEnabled&&(la=a.vertexAttributes.get("opacityFeatureAttribute").data[0]);
const ba=f.length/3;b=b.transformation;const q=new Float32Array(c.buffer);c=this.vertexBufferLayout.stride/4;let p=k*c;k=p;let v=0;const x=(r,G,I,Ea,Fa,Ga,Ha)=>{q[p++]=G[0];q[p++]=G[1];q[p++]=G[2];q[p++]=Ea;q[p++]=Ha;q[p++]=Fa;q[p++]=r[0];q[p++]=r[1];q[p++]=r[2];q[p++]=I[0];q[p++]=I[1];q[p++]=I[2];this.parameters.vvSizeEnabled?q[p++]=n:q[p++]=E;this.parameters.vvColorEnabled?q[p++]=R:(r=Math.min(4*Ga,C.length-4),q[p++]=C[r+0],q[p++]=C[r+1],q[p++]=C[r+2],q[p++]=C[r+3]);this.parameters.vvOpacityEnabled&&
(q[p++]=la)};p+=c;g.set(e,f[0],f[1],f[2]);b&&g.transformMat4(e,e,b);if(a=this.isClosed(a)){var A=f.length-3;g.set(m,f[A],f[A+1],f[A+2]);b&&g.transformMat4(m,m,b)}else{g.copy(m,e);g.set(d,f[3],f[4],f[5]);b&&g.transformMat4(d,d,b);for(A=0;A<l;++A){var O=1-A/l;x(m,e,d,O,-4,0,v);x(m,e,d,O,4,0,v)}x(m,e,d,0,-4,0,v);x(m,e,d,0,4,0,v);g.copy(m,e);g.copy(e,d)}O=a?0:1;A=a?ba:ba-1;const ca=t?(r,G,I)=>v=t[I]:(r,G,I)=>v+=g.distance(r,G);for(let r=O;r<A;r++){var P=(r+1)%ba*3;g.set(d,f[P+0],f[P+1],f[P+2]);b&&g.transformMat4(d,
d,b);ca(m,e,r);x(m,e,d,0,-1,r,v);x(m,e,d,0,1,r,v);P=h?h[r]:this.numJoinSubdivisions;for(let G=0;G<P;++G){const I=(G+1)/(P+1);x(m,e,d,I,-1,r,v);x(m,e,d,I,1,r,v)}x(m,e,d,1,-2,r,v);x(m,e,d,1,2,r,v);g.copy(m,e);g.copy(e,d)}if(a)g.set(d,f[3],f[4],f[5]),b&&g.transformMat4(d,d,b),v=ca(m,e,A),x(m,e,d,0,-1,O,v),x(m,e,d,0,1,O,v);else for(v=ca(m,e,A),x(m,e,d,0,-5,A,v),x(m,e,d,0,5,A,v),f=0;f<l;++f)h=(f+1)/l,x(m,e,d,h,-5,A,v),x(m,e,d,h,5,A,v);ha(q,k+c,q,k,c);p=ha(q,p-c,q,p,c)};return D}();const y=B.create(),z=
B.create(),F=B.create(),M=B.create(),xa=B.create(),K=N.createRenderScreenPointArray3(),L=N.createRenderScreenPointArray3(),ja=B.create(),ka=B.create(),ia=J.create(),ya=J.create(),Ba=B.create(),Ca=B.create(),Da=B.create(),S=[N.createRenderScreenPointArray3(),N.createRenderScreenPointArray3(),N.createRenderScreenPointArray3(),N.createRenderScreenPointArray3()],H=[B.create(),B.create(),B.create(),B.create()],X=u.create(),Y=u.create(),Z=u.create(),aa=u.create();da.RibbonLineMaterial=T;Object.defineProperty(da,
"__esModule",{value:!0})});