// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../geometry ../../../../core/Error ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/mat4f64 ../../../../chunks/vec4 ../../../../chunks/vec4f64 ../../../../geometry/support/aaBoundingBox ../../../../renderers/support/renderingInfoUtils ./ElevationAligners ./elevationAlignmentUtils ./ElevationContext ./Graphics3DDrapedGraphicLayer ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayer ./lineUtils ../support/FastSymbolUpdates ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/materials/lineStippleUtils ../../webgl-engine/materials/RibbonLineMaterial ../../../../geometry/Extent ../../../../geometry/Polygon".split(" "),
function(y,z,u,E,k,q,F,G,H,l,I,J,m,K,L,M,v,w,B,N,O,P,C,Q,R){const S=["polyline","polygon","extent"];u=function(A){function r(a,b,c,d){a=A.call(this,a,b,c,d)||this;a._uniformSize=1;return a}z._inheritsLoose(r,A);var e=r.prototype;e.doLoad=function(){var a=z._asyncToGenerator(function*(){this._vvConvertOptions={modelSize:[1,1,1],symbolSize:[1,1,1],unitInMeters:1,transformation:{anchor:[0,0,0],scale:[1,1,1],rotation:[0,0,0]},supportedTypes:{size:!0,color:!0,opacity:!0,rotation:!1}};this._fastUpdates=
this._context.renderer&&this._context.renderer.visualVariables&&0<this._context.renderer.visualVariables.length?B.initFastSymbolUpdatesState(this._context.renderer,this._vvConvertOptions):{enabled:!1};if(!this._drivenProperties.size){const b=null!=this.symbolLayer.size?this.symbolLayer.size:q.px2pt(1);if(0>b)throw new E("graphics3dlinesymbollayer:invalid-size","Symbol sizes may not be negative values");this._uniformSize=b}});return function(){return a.apply(this,arguments)}}();e.getMaterialParameters=
function(a){var b=k.get(this.symbolLayer,"material","color");b=this._getCombinedOpacityAndColor(b);this._patternHidesLine&&(b[3]=0);const c=b[3];a={width:1,color:b,polygonOffset:!0,join:this.symbolLayer.join||"miter",cap:w.parseCapType(this.symbolLayer.cap||"butt"),transparent:1>c||this.needsDrivenTransparentPass,slicePlaneEnabled:this._context.slicePlaneEnabled,isClosed:a,stipplePattern:P.getStipplePatternForLinePattern(this.symbolLayer.pattern),stippleScaleWithLineWidth:!0};this._drivenProperties.size?
this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size&&(a.width=q.pt2px(1)):(b=null!=this.symbolLayer.size?this.symbolLayer.size:q.px2pt(1),a.width=q.pt2px(b));return this._fastUpdates&&this._fastUpdates.visualVariables?{...a,...this._fastUpdates.materialParameters}:a};e.destroy=function(){A.prototype.destroy.call(this);this._context.stage.remove(this._lineMaterial);this._lineMaterial=null;this._context.stage.remove(this._ringMaterial);this._ringMaterial=null};e.getDrivenSize=function(a){return this._drivenProperties.size&&
a.size?q.pt2px(I.getDriverAxisSizeValueAny(a.size)):1};e.getSizeFeatureAttributeData=function(a){return this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size?v.getAttributeValue(this._fastUpdates.visualVariables.size.field,a):null};e.getDrivenColor=function(a){const b=H.fromValues(1,1,1,1);this._drivenProperties.color&&a.color&&(b[0]=a.color[0],b[1]=a.color[1],b[2]=a.color[2],0<a.color.length&&(b[3]=a.color[3]));this._drivenProperties.opacity&&a.opacity&&(b[3]=a.opacity);return b};e.getColorFeatureAttributeData=
function(a){return this._fastUpdates.enabled&&this._fastUpdates.visualVariables.color?v.getAttributeValue(this._fastUpdates.visualVariables.color.field,a):null};e.getOpacityFeatureAttributeData=function(a){return this._fastUpdates.enabled&&this._fastUpdates.visualVariables.opacity?v.getAttributeValue(this._fastUpdates.visualVariables.opacity.field,a):null};e.createGraphics3DGraphic=function(a){const b=a.graphic;if(!this._validateGeometry(b.geometry,S,this.symbolLayer.type))return null;const c=this.setGraphicElevationContext(b,
new K.ElevationContext);this.ensureDrapedStatus("on-the-ground"===c.mode);return this.draped?this._createAsOverlay(a,this._context.layer.uid):this._createAs3DShape(a,c,b.uid)};e.applyRendererDiff=function(a,b){for(const c in a.diff)switch(c){case "visualVariables":if(B.updateFastSymbolUpdatesState(this._fastUpdates,b,this._vvConvertOptions))k.isSome(this._lineMaterial)&&this._lineMaterial.setParameters(this._fastUpdates.materialParameters),k.isSome(this._ringMaterial)&&this._ringMaterial.setParameters(this._fastUpdates.materialParameters);
else return 0;break;default:return 0}return 2};e.layerOpacityChanged=function(){k.isSome(this._lineMaterial)&&this.updateMaterialLayerOpacity(this._lineMaterial);k.isSome(this._ringMaterial)&&this.updateMaterialLayerOpacity(this._ringMaterial);return!0};e.updateMaterialLayerOpacity=function(a){const b=a.parameters.color;var c=k.get(this.symbolLayer,"material","color");c=this._patternHidesLine?0:this._getCombinedOpacity(c);a.setParameters({color:[b[0],b[1],b[2],c],transparent:1>c||this.needsDrivenTransparentPass})};
e.layerElevationInfoChanged=function(a,b,c){const d=this._elevationContext.mode;c=m.elevationModeChangeUpdateType(r.elevationModeChangeTypes,c,d);if(c!==m.SymbolUpdateType.UPDATE)return c;const g=m.needsElevationUpdates2D(d);return this.updateGraphics3DGraphicElevationInfo(a,b,()=>g)};e.slicePlaneEnabledChanged=function(){k.isSome(this._lineMaterial)&&this._lineMaterial.setParameters({slicePlaneEnabled:this._context.slicePlaneEnabled});k.isSome(this._ringMaterial)&&this._ringMaterial.setParameters({slicePlaneEnabled:this._context.slicePlaneEnabled});
return!0};e.physicalBasedRenderingChanged=function(){return!0};e.pixelRatioChanged=function(){return!0};e._getGeometryAsPolygonOrPolyline=function(a){switch(a.type){case "extent":if(a instanceof Q)return R.fromExtent(a);break;case "polygon":case "polyline":return a}return null};e._createAs3DShape=function(a,b,c){const d=this._getGeometryAsPolygonOrPolyline(a.graphic.geometry);var g="polygon"===d.type?d.rings:d.paths,h=[];const t=[],f=[],p=l.create(),n=w.geometryToRenderInfo(d,this._context.elevationProvider,
this._context.renderCoordsHelper,b);this._logGeometryCreationWarnings(n,g,"polygon"===d.type?"rings":"paths","LineSymbol3DLayer");for(g=0;g<n.lines.length;g++){const {position:x,mapPosition:D}=n.lines[g];if(k.isSome(this._context.clippingExtent)&&(l.empty(p),l.expandWithBuffer(p,D),!l.intersectsClippingArea(p,this._context.clippingExtent)))continue;const T=this._createGeometry(a,x,D,d.type,1);h.push(T);t.push("polygon"===d.type?this.ringMaterial:this.lineMaterial);f.push(F.IDENTITY)}if(0===h.length)return null;
a=new N.Object3D({geometries:h,materials:t,transformations:f,castShadow:!1,metadata:{layerUid:this._context.layer.uid,graphicUid:c}});h=new M.Graphics3DObject3DGraphicLayer(this,a,h,null,null,J.perVertexElevationAligner,b);h.alignedSampledElevation=n.sampledElevation;h.needsElevationUpdates=m.needsElevationUpdates2D(b.mode);return h};e._createGeometry=function(a,b,c,d,g){const h=this._fastUpdates.enabled&&this._fastUpdates.visualVariables.color;return w.createGeometry({overlayInfo:0===g?{spatialReference:this._context.overlaySR,
renderCoordsHelper:this._context.renderCoordsHelper}:null,removeDuplicateStartEnd:"polygon"===d?1:0,uniformSize:this._uniformSize,attributeData:{position:b,mapPosition:c,size:this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size?null:this.getDrivenSize(a.renderingInfo),color:h?null:this.getDrivenColor(a.renderingInfo),sizeFeature:this.getSizeFeatureAttributeData(a.graphic),colorFeature:this.getColorFeatureAttributeData(a.graphic),opacityFeature:this.getOpacityFeatureAttributeData(a.graphic)}})};
e._createAsOverlay=function(a,b){const c=a.graphic,d=this._getGeometryAsPolygonOrPolyline(c.geometry);var g="polygon"===d.type?d.rings:d.paths;const h="polygon"===d.type?this.ringMaterial:this.lineMaterial;h.renderPriority=this._renderPriority;const t=[],f=l.create(),p=l.empty(),n=w.geometryToRenderInfoDraped(d,this._context.overlaySR);this._logGeometryCreationWarnings(n,g,"polygon"===d.type?"rings":"paths","LineSymbol3DLayer");for(const x of n.lines)l.empty(f),l.expandWithBuffer(f,x.position),l.intersectsClippingArea(f,
this._context.clippingExtent)&&(l.expandWithAABB(p,f),g=this._createGeometry(a,x.position,null,d.type,0),g=new O.RenderGeometry(g,h,b,c.uid),G.set(g.boundingSphere,.5*(f[0]+f[3]),.5*(f[1]+f[4]),0,.5*Math.sqrt((f[3]-f[0])*(f[3]-f[0])+(f[4]-f[1])*(f[4]-f[1]))),t.push(g));return new L(this,t,p)};z._createClass(r,[{key:"lineMaterial",get:function(){k.isNone(this._lineMaterial)&&(this._lineMaterial=new C.RibbonLineMaterial(this.getMaterialParameters(!1)),this._context.stage.add(this._lineMaterial));return this._lineMaterial}},
{key:"ringMaterial",get:function(){k.isNone(this._ringMaterial)&&(this._ringMaterial=new C.RibbonLineMaterial(this.getMaterialParameters(!0)),this._context.stage.add(this._ringMaterial));return this._ringMaterial}},{key:"_patternHidesLine",get:function(){const a=this.symbolLayer.pattern;return k.isSome(a)&&"style"===a.type&&"none"===a.style}}]);return r}(v.Graphics3DSymbolLayer);u.elevationModeChangeTypes={definedChanged:m.SymbolUpdateType.RECREATE,staysOnTheGround:m.SymbolUpdateType.NONE,onTheGroundChanged:m.SymbolUpdateType.RECREATE};
y.Graphics3DLineSymbolLayer=u;y.default=u;Object.defineProperty(y,"__esModule",{value:!0})});