// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/Error ../../../../core/mathUtils ../../../../core/maybe ../../../../chunks/mat2 ../../../../chunks/vec2 ../../../../chunks/vec2f64 ../../../../chunks/vec3 ../../../../chunks/vec3f32 ../../../../chunks/vec3f64 ../../../../geometry/projection ../../../../geometry/support/aaBoundingBox ../../../../layers/graphics/dehydratedFeatures ./elevationAlignmentUtils ./ElevationContext ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayer ./graphicUtils ../support/FastSymbolUpdates ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/PathGeometry ../../webgl-engine/lib/pathGeometryUtils ../../webgl-engine/materials/DefaultMaterial ../../webgl-engine/materials/PathMaterial".split(" "),
function(B,N,aa,H,C,ba,O,ca,n,P,Q,R,F,S,D,da,ea,G,T,U,fa,V,k,ha,ia){function W(f,w,l){switch(w){case "world":for(const a of f.vertices)n.add(y,a.pos,f.offset),l.worldUpAtPosition(y,v),a.setFrameFromUpVector(v),a.computeRotationAxisAndAngleFromUpVector();break;case "path":n.add(y,f.vertices[0].pos,f.offset);l.worldUpAtPosition(y,v);k.computeMinimumRotationTangentFrame(f,v);for(const a of f.vertices)f=Math.sign(n.dot(a.frame.right,a.vRight)),n.cross(a.rotationFrame.up,a.vRight,a.vLeft),n.scale(a.rotationFrame.up,
a.rotationFrame.up,f),n.normalize(a.rotationFrame.up,a.rotationFrame.up),w=n.dot(a.rotationFrame.up,a.frame.up),l=n.dot(a.rotationFrame.up,a.frame.right),n.scale(y,a.frame.up,-l),n.scale(X,a.frame.right,w),n.add(y,y,X),n.normalize(a.rotationFrame.right,y),k.vertexSpaceToProfileSpace(a.rotationRight,a.frame,a.rotationFrame.right),n.negate(y,a.vLeft),a.rotationAngle=-f*(Math.PI-H.acosClamped(n.dot(y,a.vRight))),0<Math.abs(a.rotationAngle)&&(f=H.reciprocalClamped(Math.cos(.5*a.rotationAngle)),ba.set(a.miterStretch,
1+(f-1)*a.rotationRight[0]*a.rotationRight[0],(f-1)*a.rotationRight[0]*a.rotationRight[1],(f-1)*a.rotationRight[0]*a.rotationRight[1],1+(f-1)*a.rotationRight[1]*a.rotationRight[1])),a.maxStretchDistance=Math.abs(Math.min(a.vLeftLength,a.vRightLength)*H.reciprocalClamped(Math.cos(.5*(Math.PI-a.rotationAngle))))}}function Y(f,w,l){switch(f){case "symbol-value":return l;case "proportional":return w;default:return f}}function ja(f,w,l,a){f=f.stageObject;const b=f.geometryRecords;var h=0;ka.spatialReference=
a.spatialReference;for(const r of b){const p=r.geometry;if(!V.isPathGeometry(p))continue;const z=p.path,A=z.builder.path;Z.spatialReference=p.geometrySR;{var c=A;var g=w,d=l,x=a;let m=0;for(const e of c.vertices)D.evaluateElevationInfoAtPoint(e.posES,d,g,x,I),m+=I.sampledElevation,n.add(v,e.pos,c.offset),x.setAltitude(v,I.z),n.subtract(e.pos,v,c.offset);c.updatePathVertexInformation();c=m/c.vertices.length}h+=c;"world"!==p.upVectorAlignment&&W(A,p.upVectorAlignment,a);z.onPathChanged();p.invalidateBoundingInfo();
f.geometryVertexAttrsUpdated(r)}return h/b.length}const la=["polyline"];let oa=function(f){function w(a,b,h,c){a=f.call(this,a,b,h,c)||this;a._intrinsicSize=ca.fromValues(1,1);a.upVectorAlignment="path";a.stencilWidth=.1;a.ensureDrapedStatus(!1);return a}N._inheritsLoose(w,f);var l=w.prototype;l.doLoad=function(){var a=N._asyncToGenerator(function*(){const b=C.isSome(this.symbolLayer.width)?this.symbolLayer.width:this.symbolLayer.height,h=C.isSome(this.symbolLayer.height)?this.symbolLayer.height:
b;this._vvConvertOptions={modelSize:[1,1,1],symbolSize:[b,1,h],unitInMeters:this._context.renderCoordsHelper.unitInMeters,transformation:{anchor:[0,0,0],scale:[1,1,1],rotation:[0,0,0]},supportedTypes:{size:!0,color:!0,opacity:!0,rotation:!1}};this._fastUpdates=this._context.renderer&&this._context.renderer.visualVariables&&0<this._context.renderer.visualVariables.length?U.initFastSymbolUpdatesState(this._context.renderer,this._vvConvertOptions):{enabled:!1};var c=this.symbolLayer.anchor||"center";
this.upVectorAlignment="path";"heading"===this.symbolLayer.profileRotation&&(this.upVectorAlignment="world");var g=this.symbolLayer.profile||"circle";switch(g){default:this._profile=k.Profile.circle(10);break;case "quad":this._profile=k.Profile.rect()}var d=[0,0];"center"!==c&&(d={left:[.5,0],right:[-.5,0],top:[0,-.5],bottom:[0,.5]}[c],this._profile.translate(d[0],d[1]));switch(this.symbolLayer.join||"simple"){case "round":this._extruder=new k.MiterExtruder(0,3);break;case "bevel":this._extruder=
new k.MiterExtruder(0,1);break;case "miter":this._extruder=new k.MiterExtruder(.8*Math.PI,1);break;default:this._extruder=new k.SimpleExtruder}c=this.symbolLayer.cap||"butt";switch(c){case "none":this._startCap=new k.NoCapBuilder;this._endCap=new k.NoCapBuilder;break;default:this._startCap=new k.TriangulationCapBuilder(this._profile,0);this._endCap=new k.TriangulationCapBuilder(this._profile,0,!0);break;case "square":this._startCap=new k.TriangulationCapBuilder(this._profile,-.5);this._endCap=new k.TriangulationCapBuilder(this._profile,
.5,!0);break;case "round":g="quad"===g?!0:!1,this._startCap=new k.RoundCapBuilder({profile:this._profile,flip:!1,breakNormals:g,subdivisions:3}),this._endCap=new k.RoundCapBuilder({profile:this._profile,flip:!0,breakNormals:g,subdivisions:3})}g=C.get(this.symbolLayer,"material","color");d=this._getCombinedOpacityAndColor(g);g=Q.fromArray(d);d=d[3];const x=1>d||this.needsDrivenTransparentPass;c={diffuse:g,ambient:g,opacity:d,transparent:x,vertexColors:!1,slicePlaneEnabled:this._context.slicePlaneEnabled,
castShadows:this.symbolLayer.castShadows,cullFace:x||"none"===c?0:2,offsetTransparentBackfaces:!0};if(!this._drivenProperties.size&&(O.set(this._intrinsicSize,b,h),!T.isValidSize(this._intrinsicSize[0])||!T.isValidSize(this._intrinsicSize[1])))throw new aa("graphics3dpathsymbollayer:invalid-size","Symbol sizes may not be negative values");this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size||O.scale(this._intrinsicSize,this._intrinsicSize,1/this._context.renderCoordsHelper.unitInMeters);
this._fastUpdates.enabled?(Object.assign(c,this._fastUpdates.materialParameters,{size:[this._intrinsicSize[0],this._intrinsicSize[1],0]}),this._material=new ia.PathMaterial(c)):(c.vertexColors=this._drivenProperties.color||this._drivenProperties.opacity,this._material=new ha.DefaultMaterial(c));this._material.setParameters({usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!0});this._context.stage.add(this._material)});return function(){return a.apply(this,arguments)}}();l.destroy=function(){f.prototype.destroy.call(this);
this._context.stage.remove(this._material);this._material=null};l.createGraphics3DGraphic=function(a){const b=a.graphic;if(!this._validateGeometry(b.geometry,la,this.symbolLayer.type))return null;const h=this.setGraphicElevationContext(b,new da.ElevationContext);return this._createAs3DShape(b,a.renderingInfo,h,b.uid)};l.layerOpacityChanged=function(){var a=C.get(this.symbolLayer,"material","color");a=this._getCombinedOpacity(a);this._material.setParameters({opacity:a,transparent:1>a||this.needsDrivenTransparentPass});
return!0};l.layerElevationInfoChanged=function(a,b){return this.updateGraphics3DGraphicElevationInfo(a,b,D.needsElevationUpdates3D)};l.slicePlaneEnabledChanged=function(){this._material.setParameters({slicePlaneEnabled:this._context.slicePlaneEnabled});return!0};l.physicalBasedRenderingChanged=function(){this._material.setParameters({usePBR:this._context.physicalBasedRenderingEnabled,isSchematic:!0});return!0};l.pixelRatioChanged=function(){return!0};l.applyRendererDiff=function(a,b){for(const h in a.diff)switch(h){case "visualVariables":if(U.updateFastSymbolUpdatesState(this._fastUpdates,
b,this._vvConvertOptions))this._material.setParameters(this._fastUpdates.materialParameters);else return 0;break;default:return 0}return 2};l.getVertexData=function(a){let b=0;const h=a.paths,c=[],g=a.spatialReference,d=this._context.elevationProvider.spatialReference,x=this._context.renderCoordsHelper.spatialReference;for(var r of h)b+=r.length;r=new Float64Array(3*b);const p=new Float64Array(3*b),z=new Float64Array(3*b);let A=0;for(const m of h){c.push({index:A,numVertices:m.length});for(const e of m)r[A++]=
e[0],r[A++]=e[1],r[A++]=a.hasZ?e[2]:0}a=!0;g.equals(d)?this._copyVertices(r,0,p,0,b):a=R.projectBuffer(r,g,0,p,d,0,b);d.equals(x)?this._copyVertices(p,0,z,0,b):R.projectBuffer(p,d,0,z,x,0,b);return{pathVertexDataInfos:c,vertexDataGS:r,vertexDataES:p,vertexDataRS:z,projectionSuccess:a,terrainElevation:0}};l._copyVertices=function(a,b,h,c,g){b*=3;c*=3;for(let d=0;d<g;++d)h[c++]=a[b++],h[c++]=a[b++],h[c++]=a[b++]};l._createAs3DShape=function(a,b,h,c){var g=a.geometry,d=[];const x=[],r=[],p=g.spatialReference,
z=F.create(),A=this._context.renderCoordsHelper;Z.spatialReference=p;const m=this.getVertexData(g);if(!m.projectionSuccess)return this.logger.warn("PathSymbol3DLayer geometry failed to be created (failed to project geometry to view spatial reference)"),null;if(0<m.pathVertexDataInfos.length){for(g=0;g<m.pathVertexDataInfos.length;++g){var e=m.pathVertexDataInfos[g],q=e.index;e=e.numVertices;if(2>e)continue;if(C.isSome(this._context.clippingExtent)&&(F.empty(z),F.expandWithBuffer(z,m.vertexDataES,
3*q,e),!F.intersectsClippingArea(z,this._context.clippingExtent)))continue;var t=[];for(var u=q;u<q+3*e;){const J=u++,K=u++,L=u++,E=new k.PathVertex;n.set(E.posGS,m.vertexDataGS[J],m.vertexDataGS[K],m.vertexDataGS[L]);n.set(E.posES,m.vertexDataES[J],m.vertexDataES[K],m.vertexDataES[L]);const ma=D.evaluateElevationAlignmentAtPoint(E.posES,this._context.elevationProvider,h,A);n.set(v,m.vertexDataRS[J],m.vertexDataRS[K],m.vertexDataRS[L]);A.setAltitude(v,ma);n.set(E.pos,v[0],v[1],v[2]);t.push(E)}q=new k.Path(t);
W(q,this.upVectorAlignment,this._context.renderCoordsHelper);q=new k.Builder(q,this._profile,this._extruder,this._startCap,this._endCap);e=null;this._fastUpdates.enabled?(u=this._fastUpdates.visualVariables,e=u.size?G.getAttributeValue(u.size.field,a):0,t=u.color?G.getAttributeValue(u.color.field,a):0,u=u.opacity?G.getAttributeValue(u.opacity.field,a):0,e=new k.FastUpdatePathGeometry(q,e,t,u)):(e=[this._intrinsicSize[0],this._intrinsicSize[1]],this._drivenProperties.size&&(e[0]*=Y(b.size[0],"symbol-value"===
b.size[2]?this.symbolLayer.height||0:b.size[2],this.symbolLayer.width||0),e[1]*=Y(b.size[2],"symbol-value"===b.size[0]?this.symbolLayer.width||0:b.size[0],this.symbolLayer.height||0)),t=null,this._drivenProperties.color&&(t=b.color),this._drivenProperties.opacity&&null!=b.opacity&&(t=t?[t[0],t[1],t[2],b.opacity]:[1,1,1,b.opacity]),q=new k.StaticPathGeometry(q),q.bake(e),t&&q.bakeVertexColors(t),e=q);const {vertexAttributes:M,indices:na}=e.createGeometryData();q=new V.PathGeometry(M,na,e,p,this.upVectorAlignment,
this.stencilWidth);d.push(q);x.push(this._material);r.push(e.xform)}if(0<d.length)return a=new fa.Object3D({geometries:d,materials:x,transformations:r,metadata:{layerUid:this._context.layer.uid,graphicUid:c}}),d=new ea.Graphics3DObject3DGraphicLayer(this,a,d,null,null,ja,h),d.alignedSampledElevation=m.terrainElevation,d.needsElevationUpdates=D.needsElevationUpdates3D(h.mode),d}else 0!==g.paths.length&&g.paths.some(M=>0<M.length)||this.logger.warn("PathSymbol3DLayer geometry failed to be created (no paths were defined)");
return null};return w}(G.Graphics3DSymbolLayer);const ka=S.makeDehydratedPoint(0,0,0,null),Z=S.makeDehydratedPoint(0,0,0,null),v=Q.create(),y=P.create(),X=P.create(),I=new D.SampleElevationInfo;B.Graphics3DPathSymbolLayer=oa;B.NUM_CIRCLE_PROFILE_SUBDIVISIONS=10;B.NUM_ROUND_CAP_EXTRUSION_SUBDIVISIONS=3;B.NUM_ROUND_JOIN_SUBDIVISIONS=3;Object.defineProperty(B,"__esModule",{value:!0})});