// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../Color ../../../../symbols ../../../../core/asyncUtils ../../../../core/has ../../../../core/Error ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/screenUtils ../../../../core/urlUtils ../../../../chunks/mat4f64 ../../../../chunks/vec2f64 ../../../../chunks/vec3f64 ../../../../chunks/vec4 ../../../../chunks/vec4f64 ../../../../geometry/projection ../../../../geometry/support/aaBoundingBox ../../../../support/arcadeOnDemand ../../../../symbols/support/IconSymbol3DLayerResource ../../../../symbols/support/utils ../../../2d/arcade/callExpressionWithFeature ./constants ./ElevationAligners ./elevationAlignmentUtils ./ElevationContext ./Graphics3DDrapedGraphicLayer ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayer ./graphicUtils ./pointUtils ./sdfPrimitives ../support/FastSymbolUpdates ../../terrain/OverlayRenderer ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/lib/Texture ../../webgl-engine/materials/HUDMaterial ../../../../symbols/CIMSymbol".split(" "),
function(M,A,w,N,u,O,P,B,n,C,v,G,Q,D,r,R,H,S,T,U,V,W,X,Y,Z,p,aa,ba,ca,da,x,E,t,y,ea,I,fa,J,K,ha){function F(q){return n.isSome(q)?"cross"===q||"x"===q:!1}const ia=Q.create(),L=r.fromValues(0,0,1),ja=[.25,.25,.75,.75];u=function(q){function z(a,c,b,d){a=q.call(this,a,c,b,d)||this;a._cimLayers=null;a._cimSymbolMaterials=new Map;a._cimSymbolTextures=new Map;a._cimMaterialParametersInfo=null;a._cimRequiredFields=null;a._cimScaleFactorOrFunction=null;a._size=null;a._symbolTextureRatio=1;a._outlineSize=
0;a._elevationOptions={supportsOffsetAdjustment:!0,supportsOnTheGround:!0};return a}w._inheritsLoose(z,q);var f=z.prototype;f.getCachedSize=function(){return{size:this._getIconSize()}};f.doLoad=function(){var a=w._asyncToGenerator(function*(c){this._validateOrThrow();const b=this._prepareMaterialParameters();var d=this._getPrimitive();if(n.isSome(d))this._prepareResourcesPrimitive(b,d);else{d=W.getIconHref(this.symbol,this.symbolLayer);const e=G.dataComponents(d);e&&"application/json"===e.mediaType?
yield this._prepareResourcesCIM(b,JSON.parse(e.data),c):yield this._prepareResourcesHref(b,d,c)}});return function(c){return a.apply(this,arguments)}}();f._validateOrThrow=function(){if(!this._drivenProperties.size){var a=x.validateSymbolLayerSize(this._getIconSize());if(a)throw new B("graphics3diconsymbollayer:invalid-size",a);}};f._getIconSize=function(){var a=this.symbolLayer;a=Math.round(null!=a.size?v.pt2px(a.size):16);return this._drivenProperties.size?Math.max(a,64):a};f._generateTextureCIM=
function(a){const c=this._getGraphicHash(a);let b=""===c?null:this._cimSymbolTextures.get(c);b||(a=this._context.sharedResources.cimSymbolRasterizer.rasterizeCIMSymbol(this._cimLayers,a,"esriGeometryPoint",{scaleFactor:this._cimScaleFactorOrFunction},null,null),this._cimMaterialParametersInfo.anchorPos=this._getAnchorPos("relative",a.anchorPosition),b=new J.Texture(a.imageData,{width:a.imageData.width,height:a.imageData.height,powerOfTwoResizeMode:2}),this._cimSymbolTextures.set(c,b),this._context.stage.add(b));
return b};f._computeSize=function(a,c){a=a.width/a.height;return 1<a?[c,Math.round(c/a)]:[Math.round(c*a),c]};f._prepareMaterialParameters=function(){const a={anchorPos:this._getAnchorPos(this.symbolLayer.anchor,this.symbolLayer.anchorPosition)},c=this.symbol;if(c&&"point-3d"===c.type&&c.hasVisibleVerticalOffset()){const {screenLength:b,minWorldLength:d,maxWorldLength:e}=c.verticalOffset;a.verticalOffset={screenLength:v.pt2px(b),minWorldLength:d||0,maxWorldLength:null!=e?e:Infinity}}this._context.screenSizePerspectiveEnabled&&
(a.screenSizePerspective=this._context.sharedResources.screenSizePerspectiveSettings);a.occlusionTest=!0;a.slicePlaneEnabled=this._context.slicePlaneEnabled;return a};f._prepareResourcesPrimitive=function(a,c){var b=this._getOutlineSize();if(F(c)&&0===b)throw Error("Nothing to render");this._outlineSize=b;a.color=this._getFillColor();a.outlineColor=this._getOutlineColor();a.outlineSize=this._outlineSize;b=this._context.sharedResources.textures.fromData(c,()=>{switch(c){case "circle":var d=t.createCircle(128,
64);break;case "square":d=t.createSquare(128,64);break;case "kite":d=t.createKite(128,64);break;case "cross":d=t.createCross(128,64);break;case "x":d=t.createX(128,64);break;case "triangle":d=t.createTriangle(128,64)}return d=new J.Texture(d,{mipmap:!1,wrap:{s:33071,t:33071},width:128,height:128,components:4,noUnpackFlip:!0})});this._texture=b.texture;this._releaseTexture=b;a.textureIsSignedDistanceField=!0;a.distanceFieldBoundingBox=ja;a.textureId=this._texture.id;b=this._getIconSize();this._size=
[b,b];this._symbolTextureRatio=2;this._createMaterialAndAddToStage(a,this._context.stage)};f._prepareResourcesHref=function(){var a=w._asyncToGenerator(function*(c,b,d){if(!P("esri-canvas-svg-support")&&G.isSVG(b))throw new B("graphics3diconsymbollayer:unsupported-image-format","IconSymbol3DLayer failed to load (SVG symbols are not supported in IE11)");this._outlineSize=this._getOutlineSize();c.color=this._getFillColor();c.outlineColor=this._getOutlineColor();c.outlineSize=this._outlineSize;c.textureIsSignedDistanceField=
!1;const e=this._getIconSize();d=yield O.result(this._context.sharedResources.textures.fromUrl(b,e*this._context.layerView.view.pixelRatio,{signal:d}));if(!1===d.ok)throw C.throwIfAbortError(d.error),new B("graphics3diconsymbollayer:request-failed",`Failed to load (Request for icon resource failed: ${b})`);this._releaseTexture=d.value;b=d.value.texture;this._size=this._computeSize(b.params,e);c.textureId=b.id;this._createMaterialAndAddToStage(c,this._context.stage)});return function(c,b,d){return a.apply(this,
arguments)}}();f._prepareResourcesCIM=function(){var a=w._asyncToGenerator(function*(c,b,d){b=new ha({data:b});if(!this._context.sharedResources.cimSymbolRasterizer){var e=(yield new Promise((k,l)=>M(["../../../../symbols/cim/CIMSymbolRasterizer"],k,l))).CIMSymbolRasterizer;C.throwIfAborted(d);this._context.sharedResources.cimSymbolRasterizer||(this._context.sharedResources.cimSymbolRasterizer=new e(this._context.renderCoordsHelper.spatialReference,!0))}e=this._context.layer.fields?this._context.layer.fields.map(k=>
k.toJSON()):null;this._cimLayers=yield this._context.sharedResources.cimSymbolRasterizer.analyzeCIMSymbol(b,e,this._context.renderer&&"dictionary"===this._context.renderer.type?this._context.renderer.fieldMap:null,"esriGeometryPoint",{signal:d});let g;if(this._context.renderer&&"dictionary"===this._context.renderer.type&&this._context.renderer.scaleExpression)if(b=this._context.renderer,isNaN(b.scaleExpression)){const k=yield U.createRendererExpression(b.scaleExpression,this._context.layer.spatialReference,
e);g=(l,ka,la)=>{l=X(k,l,{$view:la},"esriGeometryPoint",ka);return null!==l?l:1}}else var h=Number(b.scaleExpression);this._cimScaleFactorOrFunction=h||g||1;h=this._context.renderer?yield this._context.renderer.getRequiredFields(this._context.layer.fieldsIndex):[];C.throwIfAborted(d);const m=this._context.layer.fieldsIndex;this._cimRequiredFields=h.map(k=>m.get(k).name);this._cimMaterialParametersInfo=c;this._cimMaterialParametersInfo.color=this._getFillColor();this._cimMaterialParametersInfo.outlineColor=
[0,0,0,0];this._cimMaterialParametersInfo.outlineSize=0;this._cimMaterialParametersInfo.textureIsSignedDistanceField=!1});return function(c,b,d){return a.apply(this,arguments)}}();f._getPrimitive=function(){return this.symbolLayer.resource&&this.symbolLayer.resource.href?null:this.symbolLayer.resource&&this.symbolLayer.resource.primitive||V.defaultPrimitive};f._getOutlineSize=function(){var a=0;a=this.symbolLayer;if(n.isSome(a.outline)&&null!=a.outline.size)return Math.max(v.pt2px(a.outline.size),
0);a=this._getPrimitive();a=F(a)?1.5:0;return Math.max(a,0)};f._getOutlineColor=function(){const a=this._getLayerOpacity(),c=n.get(this.symbolLayer,"outline","color");if(n.isSome(c)){const b=N.toUnitRGB(c);return[b[0],b[1],b[2],c.a*a]}return[0,0,0,0]};f._getFillColor=function(){if(F(this._getPrimitive()))return Y.TRANSPARENT_UNIT;const a=n.isNone(this._getPrimitive()),c=n.get(this.symbolLayer,"material","color");return this._getCombinedOpacityAndColor(c,{hasIntrinsicColor:a})};f._getAnchorPos=function(a,
c){return"relative"===a?D.fromValues((c.x||0)+.5,-(c.y||0)+.5):a in x.namedAnchorToHUDMaterialAnchorPos?x.namedAnchorToHUDMaterialAnchorPos[a]:x.namedAnchorToHUDMaterialAnchorPos.center};f._createMaterialAndAddToStage=function(a,c){this._fastUpdates=this._cimLayers?{enabled:!1}:y.initFastSymbolUpdatesState(this._context.renderer,this._fastVisualVariableConvertOptions());this._fastUpdates.enabled&&Object.assign(a,this._fastUpdates.materialParameters);if(this._cimLayers){let b=this._cimSymbolMaterials.get(a.textureId);
b||(b=new K.HUDMaterial(a),this._cimSymbolMaterials.set(a.textureId,b),c.add(b));return b}this._material=new K.HUDMaterial(a);c.add(this._material);return this._material};f._setDrapingDependentMaterialParameters=function(){this.draped&&(this._forEachMaterial(a=>{a.setParameters({verticalOffset:null,screenSizePerspective:null,occlusionTest:!1,slicePlaneEnabled:!1,shaderPolygonOffset:0,isDraped:this.draped})}),this.layerOpacityChanged())};f.destroy=function(){q.prototype.destroy.call(this);this._forEachMaterial(a=>
this._context.stage.remove(a));this._material=null;this._cimSymbolMaterials.clear();this._cimSymbolTextures.forEach(a=>this._context.stage.remove(a));this._cimSymbolTextures.clear();this._releaseTexture=n.releaseMaybe(this._releaseTexture)};f._getScaleFactor=function(a,c){if(this._drivenProperties.size&&a.size){for(let b=0;3>b;b++){const d=a.size[b];d&&"symbol-value"!==d&&"proportional"!==d&&(a.size[b]=v.pt2px(d))}if("symbol-value"===a.size[0])return 1;if(isFinite(+a.size[0]))return+a.size[0]/c;if(isFinite(+a.size[2]))return+a.size[2]/
c}return 1};f.createGraphics3DGraphic=function(a){const c=a.graphic;if(!this._validateGeometry(c.geometry))return null;let b;if(this._cimLayers){if(!this._cimLayers.length)return null;var d=this._generateTextureCIM(c);b=this._createMaterialAndAddToStage({textureId:d.id,...this._cimMaterialParametersInfo},this._context.stage);var e=[d.params.width,d.params.height]}else e=this._size,b=n.unwrap(this._material);d=E.placePointOnGeometry(c.geometry);if(n.isNone(d))return this.logger.warn(`unsupported geometry type for icon symbol: ${c.geometry.type}`),
null;var g=a.renderingInfo;const h=this._getVertexOpacityAndColor(g);let m=1;this._fastUpdates.enabled&&this._fastUpdates.visualVariables.size||(m=this._getScaleFactor(g,e[0]>e[1]?e[0]:e[1]));m*=this._symbolTextureRatio;e=[e[0]*m,e[1]*m];g=this.setGraphicElevationContext(c,new aa.ElevationContext);this.ensureDrapedStatus("on-the-ground"===g.mode)&&this._setDrapingDependentMaterialParameters();return this.draped?this._createAsOverlay(c,d,b,h,e,a.layer.uid):this._createAs3DShape(c,d,b,h,e,g,c.uid)};
f.layerOpacityChanged=function(){const a=this._getFillColor(),c=this._getOutlineColor();this._forEachMaterial(b=>{b.setParameters({color:a});b.setParameters({outlineColor:c})});return!0};f.layerElevationInfoChanged=function(a,c,b){const d=this._elevationContext.mode;b=p.elevationModeChangeUpdateType(z.elevationModeChangeTypes,b,d);if(b!==p.SymbolUpdateType.UPDATE)return b;const e=p.needsElevationUpdates2D(d)||"absolute-height"===d;return this.updateGraphics3DGraphicElevationInfo(a,c,()=>e)};f.slicePlaneEnabledChanged=
function(){this.draped||this._forEachMaterial(a=>{a.setParameters({slicePlaneEnabled:this._context.slicePlaneEnabled})});return!0};f.physicalBasedRenderingChanged=function(){return!0};f.pixelRatioChanged=function(){return this._getPrimitive()?!0:!1};f.applyRendererDiff=function(a,c){for(const b in a.diff)switch(b){case "visualVariables":if(y.updateFastSymbolUpdatesState(this._fastUpdates,c,this._fastVisualVariableConvertOptions()))n.isSome(this._material)&&this._material.setParameters(this._fastUpdates.materialParameters);
else return 0;break;default:return 0}return 2};f._defaultElevationInfoNoZ=function(){return ma};f._createAs3DShape=function(a,c,b,d,e,g,h){const m=this.getFastUpdateAttrValues(a);a=m?l=>y.evaluateModelTransform(this._fastUpdates.materialParameters,m,l):null;d=[I.createPointGeometry(L,null,d,e,na,null,m)];h=E.createStageObjectForHUD(this._context,c,d,[b],g,this._context.layer.uid,h,a);if(null===h)return null;const k=new ca.Graphics3DObject3DGraphicLayer(this,h.object,d,null,null,Z.perObjectElevationAligner,
g);k.alignedSampledElevation=h.sampledElevation;k.needsElevationUpdates=p.needsElevationUpdates2D(g.mode)||"absolute-height"===g.mode;k.getScreenSize=this._createScreenSizeGetter(e,a);k.calculateRelativeScreenBounds=l=>b.calculateRelativeScreenBounds(k.getScreenSize(),1,l);E.extendPointGraphicElevationContext(k,c,this._context.elevationProvider);return k};f._createAsOverlay=function(a,c,b,d,e,g){b.renderPriority=this._renderPriority;const h=H.create();S.projectPointToVector(c,h,this._context.overlaySR);
h[2]=ea.DRAPED_Z;c=this._context.clippingExtent;if(n.isSome(c)&&!T.containsPoint(c,h))return null;const m=this.getFastUpdateAttrValues(a);c=m?l=>y.evaluateModelTransform(this._fastUpdates.materialParameters,m,l):null;d=I.createPointGeometry(L,h,d,e,null,null,m);a=new fa.RenderGeometry(d,b,g,a.uid);h[3]=0;R.copy(a.boundingSphere,h);a.calculateShaderTransformation=c;const k=new ba(this,[a],null);k.getScreenSize=this._createScreenSizeGetter(e,c);k.calculateRelativeScreenBounds=l=>b.calculateRelativeScreenBounds(k.getScreenSize(),
1,l);return k};f._createScreenSizeGetter=function(a,c){const b=this._outlineSize+2;if(this._fastUpdates.enabled){const d=a[0]/this._symbolTextureRatio,e=a[1]/this._symbolTextureRatio;return(g=D.create())=>{const h=c(ia);g[0]=h[0]*d+b;g[1]=h[5]*e+b;return g}}{const d=a[0]/this._symbolTextureRatio+b,e=a[1]/this._symbolTextureRatio+b;return(g=D.create())=>{g[0]=d;g[1]=e;return g}}};f._fastVisualVariableConvertOptions=function(){var a=this._size[0]>this._size[1]?this._size[0]:this._size[1];const c=r.fromValues(a,
a,a),b=v.px2pt(1);a*=b;a=r.fromValues(a,a,a);return{modelSize:c,symbolSize:a,unitInMeters:b,transformation:{anchor:r.ZEROS,scale:r.ONES,rotation:r.ZEROS}}};f._getGraphicHash=function(a){let c="";for(const b of this._cimRequiredFields)c+=b+a.attributes[b];return c};f._forEachMaterial=function(a){n.isSome(this._material)&&a(this._material);this._cimSymbolMaterials.forEach(a)};return z}(da.Graphics3DSymbolLayer);u.PRIMITIVE_SIZE=[64,64];u.elevationModeChangeTypes={definedChanged:p.SymbolUpdateType.UPDATE,
staysOnTheGround:p.SymbolUpdateType.NONE,onTheGroundChanged:p.SymbolUpdateType.RECREATE};const ma={mode:"relative-to-ground",offset:0},na=H.fromValues(0,0,0,1);A.Graphics3DIconSymbolLayer=u;A.default=u;Object.defineProperty(A,"__esModule",{value:!0})});