// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/has ../../../../core/mathUtils ../../../../core/maybe ../../../../core/typedArrayUtil ../../../../chunks/vec2 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/projection ../../../../geometry/projectionEllipsoid ../../../../geometry/support/triangulationUtils ./constants ./elevationAlignmentUtils ../../terrain/OverlayRenderer ../../webgl-engine/lib/Geometry".split(" "),function(r,I,y,m,z,A,p,u,v,B,w,C,D,E,F){function x(a,e,f){const c=[];for(const {index:d,
count:b}of a){if(1>=b)continue;a=3*d;const h=a+3*b;c.push({position:e.subarray(a,h),mapPosition:f?f.subarray(a,h):void 0})}return c}const t=u.create(),q=u.create(),G=4/Math.PI;r.createGeometry=function(a){const e=[],f=[];{const {attributeData:{position:l},removeDuplicateStartEnd:H}=a;var c=l.length;c=(c=l[0]===l[c-3]&&l[1]===l[c-2]&&l[2]===l[c-1])&&1===H;var d=l.length/3-(c?1:0),b=new Uint32Array(2*(d-1)),h=c?z.slice(l,0,l.length-3):l,k=0;for(var g=0;g<d-1;g++)b[k++]=g,b[k++]=g+1;f.push(["position",
{size:3,data:h,exclusive:c}]);e.push(["position",b])}c=f[0][1].data;d=new Uint16Array(e[0][1].length);b=a.attributeData.mapPosition;m.isNone(b)||(e.push(["mapPos",e[0][1]]),f.push(["mapPos",{size:3,data:b}]));m.isSome(a.attributeData.colorFeature)||(f.push(["color",{size:4,data:m.unwrapOr(a.attributeData.color,C.WHITE_UNIT)}]),e.push(["color",d]));m.isSome(a.attributeData.sizeFeature)||(f.push(["size",{size:1,data:[m.unwrapOr(a.attributeData.size,1)]}]),e.push(["size",d]));b=a.attributeData.colorFeature;
m.isNone(b)||(f.push(["colorFeatureAttribute",{size:1,data:new Float32Array([b])}]),e.push(["color",d]));b=a.attributeData.sizeFeature;m.isNone(b)||(f.push(["sizeFeatureAttribute",{size:1,data:new Float32Array([b])}]),e.push(["sizeFeatureAttribute",d]));b=a.attributeData.opacityFeature;m.isNone(b)||(f.push(["opacityFeatureAttribute",{size:1,data:new Float32Array([b])}]),e.push(["opacityFeatureAttribute",d]));if("round"===a.join){d=c.length/3;b=new Float32Array(d);p.set(t,0,0,0);h=m.unwrapOr(a.uniformSize,
1);for(k=-1;k<d;++k){g=0>k?d+k:k;var n=(k+1)%d;p.set(q,c[3*n]-c[3*g],c[3*n+1]-c[3*g+1],c[3*n+2]-c[3*g+2]);p.normalize(q,q);0<=k&&(g=(Math.PI-y.acosClamped(p.dot(t,q)))*G*(1.863798+-2.0062872/(1+h/18.2313)**.8856294),b[k]=Math.max(Math.floor(g),0));p.scale(t,q,-1)}f.push(["subdivisions",{size:1,data:b}]);e.push(["subdivisions",e[0][1]])}if(!m.isNone(a.overlayInfo)&&1===a.overlayInfo.renderCoordsHelper.viewingMode&&a.overlayInfo.spatialReference.isGeographic){d=new Float64Array(c.length);a=B.getReferenceEllipsoid(a.overlayInfo.spatialReference);
for(b=0;b<d.length;b+=3)v.lonLatToWebMercatorComparable(c,b,d,b,a);a=c.length/3;c=new Float32Array(a+1);b=t;h=q;g=k=0;p.set(b,d[g++],d[g++],d[g++]);c[0]=0;for(n=1;n<a+1;++n)n===a&&(g=0),p.set(h,d[g++],d[g++],d[g++]),k+=A.dist(b,h),c[n]=k,[b,h]=[h,b];f.push(["distanceToStart",{size:1,data:c}]);e.push(["distanceToStart",e[0][1]])}return new F.Geometry(f,e,2)};r.geometryToRenderInfo=function(a,e,f,c){const {position:d,outlines:b}=w.pathsToTriangulationInfo("polygon"===a.type?a.rings:a.paths,a.hasZ,"polygon"===
a.type?1:0),h=new Float64Array(d.length);a=D.applyPerVertexElevationAlignment(d,a.spatialReference,0,h,0,d,0,d.length/3,e,f,c);e=null!=a;return{lines:e?x(b,d,h):[],projectionSuccess:e,sampledElevation:a}};r.geometryToRenderInfoDraped=function(a,e){const {position:f,outlines:c}=w.pathsToTriangulationInfo("polygon"===a.type?a.rings:a.paths,!1,"polygon"===a.type?1:0);a=v.projectBuffer(f,a.spatialReference,0,f,e,0,f.length/3);for(e=2;e<f.length;e+=3)f[e]=E.DRAPED_Z;return{lines:a?x(c,f):[],projectionSuccess:a}};
r.parseCapType=function(a){switch(a){case "butt":return 0;case "square":return 1;case "round":return 2;default:return null}};Object.defineProperty(r,"__esModule",{value:!0})});