// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../analysis/LineOfSight ../../analysis/LineOfSightTarget ../../core/Collection ../../core/collectionUtils ../../core/Handles ../../core/handleUtils ../../core/Logger ../../core/maybe ../../core/reactiveUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../views/3d/interactive/analysisTools/lineOfSight/LineOfSightTool ./LineOfSightTarget ../support/InteractiveToolViewModel".split(" "),
function(l,h,x,y,e,r,z,A,B,f,t,C,k,H,I,J,D,E,u,F){const G=B.getLogger("esri.widgets.LineOfSight.LineOfSightViewModel"),n=e.ofType(u);e=function(v){function m(a){a=v.call(this,a)||this;a.logger=G;a.supportedViewType="3d";a.unsupportedErrorMessage="LineOfSightViewModel is only supported in 3D views.";a.handles=new z;a._vmTargetsToConnection=new Map;a._analysisTargetsToConnection=new Map;a.ready=!1;a.analysis=new x;a.analysisView=null;a.observer=null;return a}l._inheritsLoose(m,v);var c=m.prototype;
c.initialize=function(){this.handles.add([this.targets.on("after-add",a=>this._onViewModelTargetAdded(a.item)),this.targets.on("after-remove",a=>this._onViewModelTargetRemoved(a.item)),this.analysis.targets.on("after-add",a=>this._onAnalysisTargetAdded(a.item)),this.analysis.targets.on("after-remove",a=>this._onAnalysisTargetRemoved(a.item))])};c.destroy=function(){this._analysisTargetsToConnection.forEach(a=>a.remove());this.handles=f.destroyMaybe(this.handles)};c.start=function(){var a=l._asyncToGenerator(function*(){this.ready||
(yield C.whenTrueOnce(this,"ready"));return this.createTool()});return function(){return a.apply(this,arguments)}}();c.clear=function(){this.removeTool();this.observer=null;this.targets.removeAll()};c.continue=function(){f.isSome(this.tool)&&this.tool.continue()};c.stop=function(){f.isSome(this.tool)&&this.tool.stop()};c.createToolParams=function(){return{toolConstructor:E.LineOfSightTool,constructorArguments:()=>({analysis:this.analysis})}};c.onConnectToAnalysisView=function(){var a=l._asyncToGenerator(function*(b){this.analysisView=
b;this.ready=!0;this.handles.add([this.analysisView.on("result-changed",d=>{const g=this._analysisTargetsToConnection.get(d.target);f.isSome(d.result)?(g.viewModelTarget.intersectedGraphic=d.result.intersectedGraphic,g.viewModelTarget.intersectedLocation=f.unwrap(d.result.intersectedLocation),g.viewModelTarget.visible=d.result.visible):(g.viewModelTarget.intersectedGraphic=null,g.viewModelTarget.intersectedLocation=null,g.viewModelTarget.visible=void 0)})],"view")});return function(b){return a.apply(this,
arguments)}}();c.onDisconnectFromAnalysisView=function(){this.ready=!1;null!=this.handles&&this.handles.remove("view");this.analysisView=null};c._onViewModelTargetAdded=function(a){if(!this._vmTargetsToConnection.get(a)){var b=new y({location:a.location});this._connectViewModelWithAnalysisTarget(a,b);this.analysis.targets.add(b)}};c._onViewModelTargetRemoved=function(a){if(a=this._vmTargetsToConnection.get(a))a.remove(),this.analysis.targets.remove(a.analysisTarget)};c._onAnalysisTargetAdded=function(a){if(!this._analysisTargetsToConnection.get(a)){var b=
new u({location:f.applySome(a.location,d=>d.clone())});this._connectViewModelWithAnalysisTarget(b,a);this.targets.add(b)}};c._onAnalysisTargetRemoved=function(a){if(a=this._analysisTargetsToConnection.get(a))a.remove(),this.targets.remove(a.viewModelTarget)};c._connectViewModelWithAnalysisTarget=function(a,b){let d=!1;const g=A.handlesGroup([t.react(()=>b.location,p=>{d||(d=!0,a.location=f.applySome(p,q=>q.clone()),d=!1)},{sync:!0}),t.react(()=>a.location,p=>{d||(d=!0,b.location=f.applySome(p,q=>
q.clone()),d=!1)},{sync:!0})]),w={analysisTarget:b,viewModelTarget:a,remove:()=>{g.remove();this._vmTargetsToConnection.delete(a);this._analysisTargetsToConnection.delete(b)}};this._vmTargetsToConnection.set(a,w);this._analysisTargetsToConnection.set(b,w)};l._createClass(m,[{key:"state",get:function(){return this.disabled||!this.ready?"disabled":f.isNone(this.tool)||"pending"===this.tool.toolState?"ready":this.tool.state}},{key:"targets",get:function(){return this._get("targets")||new n},set:function(a){this._set("targets",
r.referenceSetter(a,this.targets,n))}},{key:"testInfo",get:function(){return{getAnalysisTargetFromViewModelTarget:a=>f.applySome(this._vmTargetsToConnection.get(a),b=>b.analysisTarget)}}}]);return m}(F.InteractiveToolViewModel);h.__decorate([k.property({readOnly:!0})],e.prototype,"state",null);h.__decorate([k.property()],e.prototype,"ready",void 0);h.__decorate([k.property()],e.prototype,"analysis",void 0);h.__decorate([k.property()],e.prototype,"analysisView",void 0);h.__decorate([k.property({aliasOf:"analysis.observer"})],
e.prototype,"observer",void 0);h.__decorate([k.property({type:n,cast:r.castForReferenceSetter,nonNullable:!0})],e.prototype,"targets",null);return e=h.__decorate([D.subclass("esri.widgets.lineOfSight.LineOfSightViewModel")],e)});