// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../analysis/AreaMeasurement ../../core/Logger ../../core/maybe ../../core/unitUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../properties/defaultUnit ../../views/3d/interactive/measurementTools/areaMeasurement3D/AreaMeasurement3DTool ../support/InteractiveToolViewModel".split(" "),function(l,d,r,
b,h,m,e,y,z,A,t,u,v,w){const x=b.getLogger("esri.widgets.AreaMeasurement3D.AreaMeasurement3DViewModel");b=function(p){function k(a){a=p.call(this,a)||this;a.logger=x;a.supportedViewType="3d";a.unsupportedErrorMessage="AreaMeasurement3DViewModel is only supported in 3D views.";a._userUnitOptions=null;a._userUnit=null;a.ready=!1;a.analysis=new r;return a}l._inheritsLoose(k,p);var f=k.prototype;f.initialize=function(){this.analysis.unit=this.unit};f.start=function(){return this.createTool()};f.clear=
function(){this.removeTool()};f.createToolParams=function(){return{toolConstructor:v}};f._findSelectableUnit=function(a,c){const g=this.unitOptions;return-1!==g.indexOf(a)?a:h.isSome(c)?this._findSelectableUnit(c):g[0]};f._filteredOrAllUnits=function(a){if(h.isNone(a))return m.measurementAreaUnits.slice();a=a.filter(c=>-1!==m.measurementAreaUnits.indexOf(c));return 0===a.length?m.measurementAreaUnits.slice():a};f.onConnectToAnalysisView=function(){var a=l._asyncToGenerator(function*(){h.isSome(this.view)&&
this.view.ready&&(this.ready=!0)});return function(){return a.apply(this,arguments)}}();f.onDisconnectFromAnalysisView=function(){this.ready=!1};l._createClass(k,[{key:"state",get:function(){return this.disabled?"disabled":h.isNone(this.tool)?"ready":this.tool.state}},{key:"measurement",get:function(){if(h.isNone(this.tool)||this.disabled||this.tool.destroyed||"pending"===this.tool.toolState)return null;var a=this.tool.measurementView;if("pending"===a.state||"destroyed"===a.state)return null;a=a.analysisVisualization;
var c=a.viewData,g=c.measurementData;const n=c.validMeasurement;c="euclidean"===c.mode;const q=(g=0===(c?g.intersectingSegments:g.geodesicIntersectingSegments).size)?n?"available":"unavailable":"invalid";return{mode:c?"euclidean":"geodesic",area:{text:g&&n?a.areaLabel:null,state:q},perimeterLength:{text:g&&n?a.perimeterLengthLabel:null,state:q}}}},{key:"unitOptions",get:function(){return this._filteredOrAllUnits(this._userUnitOptions)},set:function(a){this._userUnitOptions=a;this._set("unitOptions",
this._filteredOrAllUnits(this._userUnitOptions))}},{key:"unit",get:function(){return h.isSome(this._userUnit)?this._userUnit=this._findSelectableUnit(this._userUnit,this.defaultUnit):this._findSelectableUnit(this.defaultUnit)},set:function(a){this._userUnit=a?this._findSelectableUnit(a,this._userUnit):null;this.analysis.unit=this._userUnit}}]);return k}(w.InteractiveToolViewModel);d.__decorate([e.property()],b.prototype,"_userUnit",void 0);d.__decorate([e.property()],b.prototype,"ready",void 0);d.__decorate([e.property({readOnly:!0})],
b.prototype,"state",null);d.__decorate([e.property({readOnly:!0})],b.prototype,"measurement",null);d.__decorate([e.property(u.defaultUnitPropertyMetadata)],b.prototype,"defaultUnit",void 0);d.__decorate([e.property()],b.prototype,"unitOptions",null);d.__decorate([e.property()],b.prototype,"unit",null);d.__decorate([e.property()],b.prototype,"analysis",void 0);return b=d.__decorate([t.subclass("esri.widgets.AreaMeasurement3D.AreaMeasurement3DViewModel")],b)});