// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../geometry ../../../../core/HandleOwner ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/Point ../../../../layers/support/PixelBlock ../../../../layers/support/TileInfo ../../../../layers/support/rasterDatasets/RawBlockCache ../../../../layers/support/rasterFunctions/pixelUtils ../../../../layers/support/rasterFunctions/rasterProjectionHelper ../../tiling/PagedTileQueue ../../tiling/TileInfoView ../../tiling/TileKey ../../tiling/TileQueue ../../tiling/TileStrategy ../../../webgl/capabilities ../../../../geometry/Extent".split(" "),
function(g,l,h,M,y,z,r,n,k,N,O,P,A,B,C,D,m,E,F,Q,G,R,H,u,I,J){const K=[0,0],v=z.getLogger("esri.views.2d.layers.ImageryTileLayerView2D");g.BaseImageryTileSubView2D=function(w){function p(){var a=w.apply(this,arguments)||this;a._emptyTilePixelBlock=null;a._tileStrategy=null;a._tileInfoView=null;a._fetchQueue=null;a._blockCacheRegistryUrl=null;a._blockCacheRegistryId=null;a._srcResolutions=null;a.previousLOD=null;a._needBlockCacheUpdate=!1;a._globalSymbolizerParams=null;a._symbolizerParams=null;a._abortController=
null;a._isCustomTilingScheme=!1;a._globalUpdateRequested=!1;a.container=null;a.layer=null;a.redrawOrRefetch=n.debounce((b,c)=>!a.previousLOD||a.layerView.suspended?Promise.resolve():b?a.doRefresh():a._redrawImage(c));return a}l._inheritsLoose(p,w);var e=p.prototype;e.update=function(a){this._fetchQueue.pause();this._fetchQueue.state=a.state;this._tileStrategy.update(a);this._fetchQueue.resume();const {extent:b,resolution:c,scale:f}=a.state;a=this._tileInfoView.getClosestInfoForScale(f);if(this.layer.raster){var d;
if(!this.useProgressiveUpdate||this._needBlockCacheUpdate){const q=this._srcResolutions[a.level],t=b.toJSON?b:J.fromJSON(b);m.update(this._blockCacheRegistryUrl,this._blockCacheRegistryId,t,c,q,this.layer.raster.ioConfig.sampling)}this._needBlockCacheUpdate=!1;(null==(d=this.previousLOD)?void 0:d.level)!==a.level&&(this.previousLOD=a,null==this._symbolizerParams||this.layerView.hasTilingEffects||this._updateSymbolizerParams(),this._tileStrategy.updateCacheSize(0))}};e.moveEnd=function(){if(this.layerView.hasTilingEffects||
!this.useProgressiveUpdate)this._abortController&&this._abortController.abort(),this._abortController=new AbortController,0===this._fetchQueue.length&&this._redrawImage(this._abortController.signal).then(()=>{this._globalUpdateRequested=!1;this.layerView.requestUpdate()});const a=this._getCacheSize(this.useProgressiveUpdate);this._tileStrategy.updateCacheSize(a);this.layerView.requestUpdate()};e.attach=function(){I().supportsTextureFloat||(this.useWebGLForProcessing=!1);this._initializeTileInfo();
this._tileInfoView=new G(this.layerView.tileInfo,this.layerView.fullExtent);var a=this._computeFetchConcurrency();this._fetchQueue=new H({tileInfoView:this._tileInfoView,concurrency:a,process:(b,c)=>this._fetchTile1(b,c)});a=this._getCacheSize(this.useProgressiveUpdate);this._tileStrategy=new u({cachePolicy:"purge",acquireTile:b=>this.acquireTile(b),releaseTile:b=>this.releaseTile(b),cacheSize:a,tileInfoView:this._tileInfoView});this._updateBlockCacheRegistry()};e.acquireTile=function(a){a=this.container.createTile(a);
this._enqueueTileFetch(a);this.layerView.requestUpdate();this._needBlockCacheUpdate=!0;this._globalUpdateRequested=this.layerView.hasTilingEffects||!this.useProgressiveUpdate;return a};e.releaseTile=function(a){this._fetchQueue.abort(a.key.id);this.container.removeChild(a);a.once("detach",()=>{a.destroy();this.layerView.requestUpdate()});this.layerView.requestUpdate()};e.uninstall=function(){this._tileStrategy.destroy();this._fetchQueue.clear();this.container.removeAllChildren();this._fetchQueue=
this._tileStrategy=this._tileInfoView=null;this.notifyChange("updating");m.unregister(this._blockCacheRegistryUrl,this._blockCacheRegistryId)};e.createEmptyTilePixelBlock=function(a=null){const b=null==a||a.join(",")===this._tileInfoView.tileInfo.size.join(",");if(b&&r.isSome(this._emptyTilePixelBlock))return this._emptyTilePixelBlock;a=a||this._tileInfoView.tileInfo.size;const [c,f]=a;a=new C({width:c,height:f,pixels:[new Uint8Array(c*f)],mask:new Uint8Array(c*f),pixelType:"u8"});b&&(this._emptyTilePixelBlock=
a);return a};e._fetchTile1=function(a,b){b=!r.isNone(b)&&b.signal;const c=this.canUseWebGLForProcessing();b={allowPartialFill:!0,datumTransformation:this.layerView.datumTransformation,interpolation:c?"nearest":this.layer.interpolation,registryId:this._blockCacheRegistryId,requestRawData:c,signal:r.unwrap(b),srcResolution:this._srcResolutions[a.level],timeExtent:this.layerView.timeExtent,tileInfo:this.layerView.tileInfo};return this.fetchTile(a,b)};e._getCacheSize=function(a){return a?40:0};e._initializeTileInfo=
function(){var a=this.layerView.view.spatialReference;const b=new B({x:this.layerView.fullExtent.xmin,y:this.layerView.fullExtent.ymax,spatialReference:a}),{scales:c,srcResolutions:f,isCustomTilingScheme:d}=F.computeProjectedScales(this.layer.rasterInfo,a);a=D.create({spatialReference:a,size:512,scales:c});if(0===a.origin.x||a.origin.x>b.x)a.origin=b;this._isCustomTilingScheme=d;this.layerView.set("tileInfo",a);this._srcResolutions=null!=f?f:[]};e._computeFetchConcurrency=function(){var {blockBoundary:a}=
this.layer.rasterInfo.storageInfo;a=a[a.length-1];return 64<(a.maxCol-a.minCol+1)*(a.maxRow-a.minRow+1)?2:10};e._enqueueTileFetch=function(){var a=l._asyncToGenerator(function*(b,c){if(!this._fetchQueue.has(b.key.id)){try{const f=yield this._fetchQueue.push(b.key);this.notifyChange("updating");const {bandIds:d}=this.layer;let q=!this.useProgressiveUpdate||this.layerView.hasTilingEffects&&!this._globalSymbolizerParams;if(this._globalUpdateRequested&&!this.layerView.moving&&0===this._fetchQueue.length){q=
!1;try{yield this._redrawImage(this._abortController&&this._abortController.signal)}catch(x){n.isAbortError(x)&&v.error(x)}this._globalUpdateRequested=!1}!this.canUseWebGLForProcessing()&&"rasterVF"!==this.type||this.layerView.hasTilingEffects||null!=this._symbolizerParams||this._updateSymbolizerParams();const t=this._tileInfoView.getTileCoords(K,b.key),L=this._tileInfoView.getTileResolution(b.key);yield this.updateTileSource(b,{source:f,symbolizerParams:this._symbolizerParams,globalSymbolizerParams:this._globalSymbolizerParams,
suspended:q,bandIds:d,coords:t,resolution:L});b.once("attach",()=>this.layerView.requestUpdate());this.container.addChild(b)}catch(f){n.isAbortError(f)||v.error(f)}this.layerView.requestUpdate()}});return function(b,c){return a.apply(this,arguments)}}();e._redrawImage=function(){var a=l._asyncToGenerator(function*(b){var c=this;0!==this.container.children.length&&(yield this.updatingHandles.addPromise(this.layer.updateRenderer()),this.layerView.hasTilingEffects?yield this._updateGlobalSymbolizerParams(b):
(this._updateSymbolizerParams(),this._globalSymbolizerParams=null),b=this.container.children.map(function(){var f=l._asyncToGenerator(function*(d){return c.updateTileSymbolizerParameters(d,{local:c._symbolizerParams,global:c._globalSymbolizerParams})});return function(d){return f.apply(this,arguments)}}()),yield n.eachAlways(b),this.container.requestRender())});return function(b){return a.apply(this,arguments)}}();e._updateGlobalSymbolizerParams=function(){var a=l._asyncToGenerator(function*(b){(b=
yield this.layer.fetchPixels(this.layerView.view.extent,this.layerView.view.width,this.layerView.view.height,{srcResolution:this._srcResolutions[this.previousLOD.level],registryId:this._blockCacheRegistryId,signal:b}))&&b.pixelBlock&&(b=this.layer.symbolizer.generateWebGLParameters({pixelBlock:E.extractBands(b.pixelBlock,this.layer.bandIds),isGCS:this.layerView.view.spatialReference.isGeographic,resolution:{x:this.previousLOD.resolution,y:this.previousLOD.resolution},bandIds:this.layer.bandIds}),
!this.canUseWebGLForProcessing()&&b&&"stretch"===b.type&&this.layer.renderer&&"raster-stretch"===this.layer.renderer.type&&(b.factor=b.factor.map(c=>255*c),b.outMin=Math.round(255*b.outMin),b.outMax=Math.round(255*b.outMax)),this._globalSymbolizerParams=b)});return function(b){return a.apply(this,arguments)}}();e._updateSymbolizerParams=function(){this._symbolizerParams=this.layer.symbolizer.generateWebGLParameters({pixelBlock:null,isGCS:this.layerView.view.spatialReference.isGeographic,resolution:{x:this.previousLOD.resolution,
y:this.previousLOD.resolution},bandIds:this.layer.bandIds})};e._updateBlockCacheRegistry=function(a=!1){const {url:b,rasterInfo:c,raster:f}=this.layer;var {multidimensionalDefinition:d}=this.layer.normalizeRasterFetchOptions({multidimensionalDefinition:this.layer.multidimensionalDefinition,timeExtent:this.layerView.timeExtent});d=null!=c&&c.multidimensionalInfo?f.getSliceIndex(d):null;d=m.getRasterId(b,d);d!==this._blockCacheRegistryUrl&&(null!=this._blockCacheRegistryUrl&&m.unregister(this._blockCacheRegistryUrl,
this._blockCacheRegistryId),this._blockCacheRegistryId=m.register(d,this.layer.raster.rasterInfo),a&&(a=this._tileInfoView.getClosestInfoForScale(this.layerView.view.scale),m.update(d,this._blockCacheRegistryId,this.layerView.view.extent,this.layerView.view.resolution,this._srcResolutions[a.level],this.layer.raster.ioConfig.sampling)),this._blockCacheRegistryUrl=d)};e.doRefresh=function(){var a=l._asyncToGenerator(function*(){yield this.updatingHandles.addPromise(this.layer.updateRenderer());this.layerView.hasTilingEffects||
this._updateSymbolizerParams();this._updateBlockCacheRegistry(!0);this._fetchQueue.reset();this.notifyChange("updating");const b=[];this._tileStrategy.tiles.forEach(c=>b.push(this._enqueueTileFetch(c)));yield n.eachAlways(b)});return function(){return a.apply(this,arguments)}}();l._createClass(p,[{key:"useWebGLForProcessing",get:function(){var a;return null!=(a=this._get("useWebGLForProcessing"))?a:!0},set:function(a){this._set("useWebGLForProcessing",a)}},{key:"useProgressiveUpdate",get:function(){return null==
this._get("useProgressiveUpdate")?!0:this._get("useProgressiveUpdate")},set:function(a){if(this._tileStrategy&&this.useProgressiveUpdate!==a){this._tileStrategy.destroy();this.container.removeAllChildren();const b=this._getCacheSize(a);this._tileStrategy=new u({cachePolicy:"purge",acquireTile:c=>this.acquireTile(c),releaseTile:c=>this.releaseTile(c),cacheSize:b,tileInfoView:this._tileInfoView});this._set("useProgressiveUpdate",a);this.layerView.requestUpdate()}}},{key:"updating",get:function(){return 0<
this._fetchQueue.length||this._globalUpdateRequested||!(!this.updatingHandles||!this.updatingHandles.updating)}}]);return p}(y.HandleOwner);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"_globalUpdateRequested",void 0);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"container",void 0);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"layer",void 0);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"layerView",void 0);h.__decorate([k.property()],
g.BaseImageryTileSubView2D.prototype,"type",void 0);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"useWebGLForProcessing",null);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"useProgressiveUpdate",null);h.__decorate([k.property()],g.BaseImageryTileSubView2D.prototype,"updating",null);g.BaseImageryTileSubView2D=h.__decorate([A.subclass("esri.views.2d.layers.imagery.BaseImageryTileSubView2D")],g.BaseImageryTileSubView2D);Object.defineProperty(g,"__esModule",{value:!0})});