// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../Graphic ../../../../request ../../../../core/Accessor ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/enumeration ../../../../core/accessorSupport/decorators/subclass ../../../../geometry/Extent ../../../../layers/support/rasterFunctions/rasterProjectionHelper ../../../../layers/support/rasterFunctions/vectorFieldUtils ../../../../support/GraphicsCollection ../../engine/Container ../graphics/GraphicContainer ../graphics/GraphicsView2D".split(" "),
function(n,h,C,D,f,E,x,y,m,R,S,T,F,G,z,H,I,J,K,L,M){const N=E.getLogger("esri.views.2d.layers.imagery.ImageryGraphicsView2D");f=function(A){function p(){var a=A.apply(this,arguments)||this;a.attached=!1;a.container=new K.Container;a.updateRequested=!1;a._graphicsView=null;a._projectFullExtentPromise=null;a._dataParameters={exportParametersVersion:0,extents:[],tileResolution:0,time:"",isOceanStyle:!1,isOceanographic:!1};a.type="Graphics";a._graphics=new J.GraphicsCollection;a._updateGraphics=y.debounce(function(){var g=
n._asyncToGenerator(function*(k,b){if(k.stationary){var c=k.state;c=new z({xmin:c.extent.xmin,ymin:c.extent.ymin,xmax:c.extent.xmax,ymax:c.extent.ymax,spatialReference:c.spatialReference});var [q,r]=k.state.size,d={};d.timeExtent=a.timeExtent;d.requestAsImageElement=!1;d.signal=b;null==a._projectFullExtentPromise&&(a._projectFullExtentPromise=a._getProjectedFullExtent(c.spatialReference));b="vector-field"===a.layer.renderer.type?a.layer.renderer.symbolTileSize:50;var l=yield a._projectFullExtentPromise,
{extent:t,resolution:O,width:P,height:Q}=I.snapImageToSymbolTile(c,q,r,b,l);c=yield a.layer.fetchImage(t,P,Q,d);d=a.layer.renderer;if("vector-field"===d.type){b=c.pixelData.pixelBlock;l=d.sizeVariables[0];!x.isSome(b)||l.minDataValue&&l.maxDataValue||(l.minDataValue=b.statistics[0].minValue,l.maxDataValue=b.statistics[0].maxValue);a._pixelData={extent:t,pixelBlock:b};const B=t.clone().normalize();b={exportParametersVersion:a.layer.exportImageServiceParameters.version,extents:B,tileResolution:O,time:JSON.stringify(a.timeExtent||
""),isOceanStyle:"flow-to"===d.flowRepresentation,isOceanographic:"ocean-current-kn"===d.style||"ocean-current-m"===d.style};const u=a._canReuseVectorFieldData(b)?a._dataParameters.extents:[];c=yield d.getGraphicsFromPixelData(c.pixelData,"vector-uv"===a.layer.rasterInfo.dataType,u);u.length?(d=a._graphics.items.filter(v=>x.isSome(v.geometry)&&u.some(w=>w.intersects(v.geometry))&&!B.some(w=>w.intersects(v.geometry))),a._graphics.removeMany(d),a._graphics.addMany(c)):a._graphics.set("items",c);a._graphicsView.update(k);
a._dataParameters=b}}});return function(k,b){return g.apply(this,arguments)}}());return a}n._inheritsLoose(p,A);var e=p.prototype;e.destroy=function(){this.attached&&(this.detach(),this.attached=!1);this.updateRequested=!1};e.update=function(a){this._updateGraphics(a).catch(g=>{y.isAbortError(g)||N.error(g)})};e.hitTest=function(a){return new C({attributes:{},geometry:a.clone(),layer:this.layer})};e.attach=function(){this._graphicsView=new M({view:this.view,graphics:this._graphics,requestUpdateCallback:()=>
this.requestUpdate(),container:new L(this.view.featuresTilingScheme)});this.attached=!0};e.detach=function(){this._graphics.destroy();this._graphicsView.destroy();this.container.removeChild(this._graphicsView.container);this._graphicsView=null};e.install=function(a){this.container.addChild(this._graphicsView.container);a.addChild(this.container)};e.uninstall=function(a){this.container.removeChild(this._graphicsView.container);a.removeChild(this.container)};e.isUpdating=function(){return this._graphicsView.updating||
this.updateRequested};e.getPixelData=function(){return this.updating?null:this._pixelData};e.redraw=function(){};e.requestUpdate=function(){this.updateRequested||(this.updateRequested=!0,this.view.requestUpdate())};e._getProjectedFullExtent=function(){var a=n._asyncToGenerator(function*(g){try{return yield H.projectExtent(this.layer.fullExtent,g)}catch(k){try{const b=(yield D(this.layer.url,{query:{option:"footprints",outSR:g.wkid||JSON.stringify(g.toJSON()),f:"json"}})).data.featureCollection.layers[0].layerDefinition.extent;
return b?z.fromJSON(b):null}catch{return null}}});return function(g){return a.apply(this,arguments)}}();e._canReuseVectorFieldData=function(a){const g=this._dataParameters.exportParametersVersion===a.exportParametersVersion,k=this._dataParameters.time===a.time,b=.01>Math.abs(this._dataParameters.tileResolution-a.tileResolution)/a.tileResolution,c=this._dataParameters.extents.some(d=>a.extents.some(l=>d.intersects(l))),q=this._dataParameters.isOceanStyle===a.isOceanStyle,r=this._dataParameters.isOceanographic===
a.isOceanographic;return g&&k&&b&&c&&q&&r};n._createClass(p,[{key:"updating",get:function(){return!this.attached||this.isUpdating()}}]);return p}(f);h.__decorate([m.property()],f.prototype,"attached",void 0);h.__decorate([m.property()],f.prototype,"container",void 0);h.__decorate([m.property()],f.prototype,"layer",void 0);h.__decorate([m.property()],f.prototype,"timeExtent",void 0);h.__decorate([m.property()],f.prototype,"view",void 0);h.__decorate([m.property()],f.prototype,"updateRequested",void 0);
h.__decorate([m.property()],f.prototype,"updating",null);h.__decorate([F.enumeration({graphics:"Graphics"})],f.prototype,"type",void 0);return f=h.__decorate([G.subclass("esri.views.2d.layers.imagery.ImageryGraphicsView2D")],f)});