// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../analysis/DirectLineMeasurement ../../core/Logger ../../core/maybe ../../core/unitUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../properties/defaultUnit ../../views/3d/interactive/measurementTools/directLineMeasurement3D/DirectLineMeasurement3DTool ../support/InteractiveToolViewModel".split(" "),
function(n,d,q,c,g,m,e,x,y,z,r,t,u,v){const w=c.getLogger("esri.widgets.DirectLineMeasurement3D.DirectLineMeasurement3DViewModel");c=function(p){function k(a){a=p.call(this,a)||this;a.logger=w;a.supportedViewType="3d";a.unsupportedErrorMessage="DirectLineMeasurement3DViewModel is only supported in 3D views.";a._userUnitOptions=null;a.ready=!1;a.analysis=new q;a._userUnit=null;return a}n._inheritsLoose(k,p);var f=k.prototype;f.start=function(){return this.createTool()};f.clear=function(){this.removeTool()};
f.createToolParams=function(){return{toolConstructor:u}};f._findSelectableUnit=function(a,b){const l=this.unitOptions;return-1!==l.indexOf(a)?a:b?this._findSelectableUnit(b):l[0]};f._filteredOrAllUnits=function(a){if(!a)return m.measurementLengthUnits.slice();a=a.filter(b=>-1!==m.measurementLengthUnits.indexOf(b));return 0===a.length?m.measurementLengthUnits.slice():a};f.onConnectToAnalysisView=function(){g.isSome(this.view)&&this.view.ready&&(this.ready=!0)};f.onDisconnectFromAnalysisView=function(){this.ready=
!1};n._createClass(k,[{key:"state",get:function(){return this.disabled?"disabled":g.isNone(this.tool)?"ready":this.tool.state}},{key:"measurement",get:function(){if(g.isNone(this.tool))return null;const a={mode:"euclidean",directDistance:{text:null,state:"unavailable"},horizontalDistance:{text:null,state:"unavailable"},verticalDistance:{text:null,state:"unavailable"}};var b=this.tool.measurementView.analysisView;if(g.isNone(b))return a;const l=b.actualVisualizedMeasurement,h=this.tool.measurementView;
b=g.isSome(b.result)?"available":"unavailable";switch(l){case "euclidean":return{mode:"euclidean",directDistance:{text:h.directLabelText,state:b},horizontalDistance:{text:h.horizontalLabelText,state:b},verticalDistance:{text:h.verticalLabelText,state:b}};case "geodesic":return{mode:"geodesic",directDistance:{text:null,state:"unavailable"},horizontalDistance:{text:h.horizontalLabelText,state:b},verticalDistance:{text:h.verticalLabelText,state:b}};default:return a}}},{key:"unitOptions",get:function(){return this._filteredOrAllUnits(this._userUnitOptions)},
set:function(a){this._userUnitOptions=a;this._set("unitOptions",this._filteredOrAllUnits(this._userUnitOptions))}},{key:"unit",get:function(){return this._userUnit?this._userUnit=this._findSelectableUnit(this._userUnit,this.defaultUnit):this._findSelectableUnit(this.defaultUnit)},set:function(a){this._userUnit=a?this._findSelectableUnit(a,this._userUnit):null;this.analysis.unit=a}}]);return k}(v.InteractiveToolViewModel);d.__decorate([e.property()],c.prototype,"ready",void 0);d.__decorate([e.property({readOnly:!0})],
c.prototype,"state",null);d.__decorate([e.property({readOnly:!0})],c.prototype,"measurement",null);d.__decorate([e.property(t.defaultUnitPropertyMetadata)],c.prototype,"defaultUnit",void 0);d.__decorate([e.property()],c.prototype,"unitOptions",null);d.__decorate([e.property()],c.prototype,"unit",null);d.__decorate([e.property()],c.prototype,"analysis",void 0);d.__decorate([e.property()],c.prototype,"_userUnit",void 0);return c=d.__decorate([r.subclass("esri.widgets.DirectLineMeasurement3D.DirectLineMeasurement3DViewModel")],
c)});