// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/has ../../../../core/mathUtils ../../../../core/maybe ../../webgl-engine/core/material/RenderTexture ../../webgl-engine/core/shaderLibrary/shading/PhysicallyBasedRenderingParameters.glsl ../../webgl-engine/core/shaderLibrary/util/AlphaDiscard.glsl ../../webgl-engine/core/shaderLibrary/util/EllipsoidMode ../../webgl-engine/lib/Texture".split(" "),function(n,B,v,l,t,w,x,C,p){function y(a){return a.sort((b,c)=>b.encoding-c.encoding)}function u(a,b,c){if(l.isNone(a)||
0===c)return null;for(let e=0;e<a.length;e++){const d=a[e];if(l.isSome(d)&&0!==(d.usage&c))return a=b[e],l.isSome(a)?a.id:null}return null}function D(a){switch(a){case 1:return p.Texture.KTX2_ENCODING;case 2:return p.Texture.BASIS_ENCODING;case 4:return p.Texture.DDS_ENCODING;case 8:return"image/png";case 16:return"image/jpeg";case 32:return"image/ktx";default:return""}}const E={ktx2:1,basis:2,dds:4,png:8,jpg:16,"ktx-etc2":32},z={[p.Texture.KTX2_ENCODING]:2,[p.Texture.BASIS_ENCODING]:2,[p.Texture.DDS_ENCODING]:4,
"image/png":8,"image/jpg":16,"image/jpeg":16,"image/ktx":32},F={s:33071,t:33071},G={s:10497,t:10497};n.configureMaterial=function(a,b,c,e,d,g){const f=g.rendererTextureUsage;var h=b.metallicRoughness.baseColorFactor,k=v.clamp(b.metallicRoughness.baseColorFactor[3],0,1);a.baseColor=[h[0],h[1],h[2],k];a.hasParametersFromSource=!!b.hasParametersFromSource;a.usePBR=g.usePBR;a.mrrFactors=[b.metallicRoughness.metallicFactor,b.metallicRoughness.roughnessFactor,b.hasParametersFromSource?.2:.5];a.emissiveFactor=
b.emissiveFactor;a.isIntegratedMesh=g.isIntegratedMesh;a.alphaCutoff="mask"===b.alphaMode?b.alphaCutoff:x.defaultMaskAlphaCutoff;a.alphaDiscardMode="opaque"===b.alphaMode?1:"mask"===b.alphaMode?2:3;h=[];k=u(e,c,33&f);l.isSome(k)&&(a.baseColorTexture=new t.RenderTexture(d,k),h.push(a.baseColorTexture.loadPromise));k=u(e,c,2&f);l.isSome(k)&&(a.metallicRoughnessTexture=new t.RenderTexture(d,k),h.push(a.metallicRoughnessTexture.loadPromise));k=u(e,c,16&f);l.isSome(k)&&(a.emissionTexture=new t.RenderTexture(d,
k),h.push(a.emissionTexture.loadPromise));k=u(e,c,8&f);l.isSome(k)&&(a.occlusionTexture=new t.RenderTexture(d,k),h.push(a.occlusionTexture.loadPromise));c=u(e,c,4&f);l.isSome(c)&&(a.normalTexture=new t.RenderTexture(d,c),h.push(a.normalTexture.loadPromise));a.commonMaterialParameters.slicePlaneEnabled=g.slicePlaneEnabled;a.commonMaterialParameters.doubleSided=b.doubleSided;a.commonMaterialParameters.cullFace=b.cullFace;a.ellipsoidMode=C.getEllipsoidMode(g.viewSpatialReference);return Promise.all(h)};
n.createTexture=function(a,b,c,e){if(l.isNone(a)||null==a.data)return null;const d=a.data;var g=!(d instanceof HTMLImageElement)||v.isPowerOfTwo(d.width)&&v.isPowerOfTwo(d.height),f=e.renderingContext.parameters.maxMaxAnisotropy;e=c&&!e.capabilities.shaderTextureLOD?1:f;g=g&&!a.downsampled&&1<e;c=c||!b.wrapTextures?F:G;f=D(a.encoding);return new p.Texture(d,{mipmap:g,maxAnisotropy:e,encoding:f,wrap:c,components:a.usage&1?"opaque"===b.alphaMode?3:4:3,noUnpackFlip:!0})};n.getMaterialAndTextures=function(a,
b){const c=new Map,e=(m,r)=>{if(l.isNone(m))return-1;if(c.has(m.id))return m=c.get(m.id),m.usage|=r,m.id;const q=c.size;c.set(m.id,{id:q,usage:r});return q};var d=b.pbrMetallicRoughness;const g=d&&d.baseColorFactor,f=b.emissiveFactor,h=null==b.normalTexture&&null==b.emissiveTexture&&null==b.occlusionTexture&&(d?null==d.metallicRoughnessTexture&&1===d.roughnessFactor&&(1===d.metallicFactor||0===d.metallicFactor):!0),k=h?w.PBRSchematicMRRValues[0]:d?d.metallicFactor:1,H=h?w.PBRSchematicMRRValues[1]:
d?d.roughnessFactor:1;d={baseColorFactor:g?[g[0],g[1],g[2],g[3]]:[1,1,1,1],baseColorTextureId:e(d&&d.baseColorTexture,"mask"===b.alphaMode?33:1),metallicRoughnessTextureId:e(d&&d.metallicRoughnessTexture,2),metallicFactor:k,roughnessFactor:H};b={alphaMode:b.alphaMode,alphaCutoff:b.alphaCutoff,doubleSided:b.doubleSided,cullFace:"none"===b.cullFace?0:"back"===b.cullFace?2:"front"===b.cullFace?1:void 0,normalTextureId:e(b.normalTexture,4),emissiveTextureId:e(b.emissiveTexture,16),occlusionTextureId:e(b.occlusionTexture,
8),emissiveFactor:f?[f[0],f[1],f[2]]:[0,0,0],metallicRoughness:d,wrapTextures:!1,hasParametersFromSource:h};const A=[];c.forEach(({usage:m},r)=>{var q=l.isSome(a)&&a[r]&&a[r].formats;q=q?y(q.map(({name:I,format:J})=>({name:I,encoding:E[J]}))):[];A.push({id:r,usage:m,encodings:q})});return{material:b,textures:A}};n.getMaterialAndTexturesFromShared=function(a){var b=a&&a.materialDefinitions?Object.keys(a.materialDefinitions)[0]:null,c=a&&a.textureDefinitions?Object.keys(a.textureDefinitions)[0]:null;
b=b&&a.materialDefinitions[b];c=c&&a.textureDefinitions[c];a={alphaMode:"opaque",alphaCutoff:x.defaultMaskAlphaCutoff,doubleSided:!0,cullFace:0,normalTextureId:-1,emissiveTextureId:-1,occlusionTextureId:-1,emissiveFactor:[0,0,0],metallicRoughness:{baseColorFactor:[.8,.8,.8,1],baseColorTextureId:-1,metallicRoughnessTextureId:-1,metallicFactor:0,roughnessFactor:.6},wrapTextures:!1,hasParametersFromSource:!0};if(null!=b){b=b.params;b.diffuse&&(a.metallicRoughness.baseColorFactor=[b.diffuse[0],b.diffuse[1],
b.diffuse[2],1]);null!=b.doubleSided&&(a.doubleSided=b.doubleSided,a.cullFace=b.doubleSided?0:2);if("none"===b.cullFace||"front"===b.cullFace||"back"===b.cullFace)a.cullFace="none"===b.cullFace?0:"back"===b.cullFace?2:1;b.transparency&&(a.metallicRoughness.baseColorFactor[3]=v.clamp(1-b.transparency,0,1));if(b.useVertexColorAlpha||1>a.metallicRoughness.baseColorFactor[3])a.alphaMode="blend"}b=[];if(null!=c){!c.wrap||"repeat"!==c.wrap[0]&&"repeat"!==c.wrap[1]||(a.wrapTextures=!0);let e=1;"rgba"===
c.channels&&(a.alphaMode="blend",e|=32);const d=c.images[c.images.length-1],g=f=>f&&f.split("/").pop();c=Array.isArray(c.encoding)?y(c.encoding.map((f,h)=>({name:g(d.href[h]),encoding:z[f]||0}))):[{name:g(d.href),encoding:z[c.encoding]||0}];b.push({id:0,usage:e,encodings:c});a.metallicRoughness.baseColorTextureId=0}return{material:a,textures:b}};n.getSupportedEncodings=function(a){const b=!!a.compressedTextureS3TC;a=!!a.compressedTextureETC;const c=B("disable-feature:i3s-basis")?0:3;return 24|(b?
c|4:0)|(a?c:0)};n.selectEncoding=function(a,b){return a.find(c=>0!==(c.encoding&b))};Object.defineProperty(n,"__esModule",{value:!0})});