// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../geometry ../../core/has ../../core/Logger ../../core/maybe ../../core/unitUtils ../../geometry/support/aaBoundingRect ../../geometry/support/contains ../../geometry/support/webMercatorUtils ../../geometry/Point".split(" "),function(l,p,q,u,z,m,A,r,B,C,D){function v(b,f){const c=w(b,f.spatialReference);if(!c)return null;switch(b.type){case "point":b.z=m.unwrapOr(f.elevationAt(c),0);break;case "polyline":h.spatialReference=c.spatialReference;
var a=b.hasM&&!b.hasZ;for(var e=0;e<b.paths.length;e++){var d=b.paths[e],g=c.paths[e];for(let k=0;k<d.length;k++){const n=d[k],x=g[k];h.x=x[0];h.y=x[1];a&&(n[3]=n[2]);n[2]=m.unwrapOr(f.elevationAt(h),0)}}b.hasZ=!0;break;case "multipoint":h.spatialReference=c.spatialReference;a=b.hasM&&!b.hasZ;for(e=0;e<b.points.length;e++)d=b.points[e],g=c.points[e],h.x=g[0],h.y=g[1],a&&(d[3]=d[2]),d[2]=m.unwrapOr(f.elevationAt(h),0);b.hasZ=!0}return b}function w(b,f){if(m.isNone(b))return null;const c=b.spatialReference;
if(c.equals(f))return b;(b=C.project(b,f))||t.error(`Cannot project geometry spatial reference (wkid:${c.wkid}) to elevation sampler spatial reference (wkid:${f.wkid})`);return b}const t=z.getLogger("esri.layers.support.ElevationSampler");q=function(){function b(){}var f=b.prototype;f.queryElevation=function(c){return v(c.clone(),this)};f.on=function(){return E};f.projectIfRequired=function(c,a){return w(c,a)};return b}();let y=function(b){function f(a,e,d){var g=b.call(this)||this;g.tile=a;g.noDataValue=
d;g.extent=r.toExtent(a.tile.extent,e.spatialReference);d=A.getMetersPerUnitForSR(e.spatialReference);a=e.lodAt(a.tile.level).resolution*d;g.demResolution={min:a,max:a};return g}p._inheritsLoose(f,b);var c=f.prototype;c.contains=function(a){a=this.projectIfRequired(a,this.spatialReference);return B.extentContainsPoint(this.extent,a)};c.elevationAt=function(a){var e=this.projectIfRequired(a,this.spatialReference);return m.isNone(e)?null:this.contains(a)?this.tile.sample(e.x,e.y):(e=this.extent,t.warn("#elevationAt()",
`Point used to sample elevation (${a.x}, ${a.y}) is outside of the sampler extent (${`${e.xmin}, ${e.ymin}, ${e.xmax}, ${e.ymax}`})`),this.noDataValue)};p._createClass(f,[{key:"spatialReference",get:function(){return this.extent.spatialReference}}]);return f}(q);u=function(b){function f(c,a,e){var d=b.call(this)||this;let g;"number"===typeof a?(d.noDataValue=a,g=null):(g=a,d.noDataValue=e);d.samplers=g?c.map(k=>new y(k,g,d.noDataValue)):c;if(c=d.samplers[0]){d.extent=c.extent.clone();const {min:k,
max:n}=c.demResolution;d.demResolution={min:k,max:n};for(c=1;c<d.samplers.length;c++)a=d.samplers[c],d.extent.union(a.extent),d.demResolution.min=Math.min(d.demResolution.min,a.demResolution.min),d.demResolution.max=Math.max(d.demResolution.max,a.demResolution.max)}else d.extent=r.toExtent(r.create(),g.spatialReference),d.demResolution={min:0,max:0};return d}p._inheritsLoose(f,b);f.prototype.elevationAt=function(c){const a=this.projectIfRequired(c,this.spatialReference);if(!a)return null;for(const e of this.samplers)if(e.contains(a))return e.elevationAt(a);
t.warn("#elevationAt()",`Point used to sample elevation (${c.x}, ${c.y}) is outside of the sampler`);return this.noDataValue};p._createClass(f,[{key:"spatialReference",get:function(){return this.extent.spatialReference}}]);return f}(q);const h=new D,E={remove(){}};l.ElevationSamplerBase=q;l.MultiTileElevationSampler=u;l.TileElevationSampler=y;l.updateGeometryElevation=v;Object.defineProperty(l,"__esModule",{value:!0})});