// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../chunks/_rollupPluginBabelHelpers ../../core/Error ../../core/maybe ../../core/object ./domainUtils ../../support/arcadeOnDemand".split(" "),function(ea,d,g,fa,k,x,r,ha){function S(a,b,c){if(a)for(const e of a)(a=(a=x.getDeepValue(e,b))&&"function"!==typeof a&&c.get(a))&&x.setDeepValue(e,a.name,b)}function n(a,b){if(!a||!b)return[];y.clear();p(y,a,b);return Array.from(y).sort()}function p(a,b,c){var e;if(c)if(null!=b&&null!=(e=b.fields)&&e.length)if(c.includes("*"))for(const {name:f}of b.fields)a.add(f);
else for(const f of c)q(a,b,f);else if(c.includes("*"))a.clear(),a.add("*");else for(const f of c)a.add(f)}function q(a,b,c){"string"===typeof c&&(b?(b=b.get(c))&&a.add(b.name):a.add(c))}function l(a,b,c){return z.apply(this,arguments)}function z(){z=g._asyncToGenerator(function*(a,b,c){var e;if(c){var {arcadeUtils:f}=yield ha.loadArcade();c=f.extractFieldNames(c,null==b?void 0:null==(e=b.fields)?void 0:e.map(h=>h.name));for(const h of c)q(a,b,h)}});return z.apply(this,arguments)}function T(a,b,c){return A.apply(this,
arguments)}function A(){A=g._asyncToGenerator(function*(a,b,c){if(c&&"1\x3d1"!==c){c=(yield new Promise((e,f)=>ea(["../../core/sql/WhereClause"],e,f))).WhereClause.create(c,b);if(!c.isStandardized)throw new fa("fieldUtils:collectFilterFields","Where clause is not standardized");p(a,b,c.fieldNames)}});return A.apply(this,arguments)}function B(a,b){for(const c of a)if(c&&c.valueType&&c.valueType===b)return c.name;return null}function C(){C=g._asyncToGenerator(function*(a){if(!a)return[];const b=new Set;
yield U(b,a);return Array.from(b).sort()});return C.apply(this,arguments)}function U(a,b){return D.apply(this,arguments)}function D(){D=g._asyncToGenerator(function*(a,b){if(b){var c=x.getDeepValue("elevationInfo.featureExpressionInfo",b);if(c)return c.collectRequiredFields(a,b.fieldsIndex)}});return D.apply(this,arguments)}function ia(a,b,c){return E.apply(this,arguments)}function E(){E=g._asyncToGenerator(function*(a,b,c){c.outStatistic.onStatisticValueExpression?l(a,b,c.outStatistic.onStatisticValueExpression):
a.add(c.outStatistic.onStatisticField)});return E.apply(this,arguments)}function F(){F=g._asyncToGenerator(function*(a,b,c){var e,f;if(b&&c&&"cluster"===c.type){var h=[];null!=(e=c.popupTemplate)&&e.expressionInfos&&h.push(...c.popupTemplate.expressionInfos.map(m=>l(a,b.fieldsIndex,m.expression)));if(Array.isArray(null==(f=c.popupTemplate)?void 0:f.content)){e=c.popupTemplate.content;for(const m of e)"expression"===m.type&&m.expressionInfo&&h.push(l(a,b.fieldsIndex,m.expressionInfo.expression))}c.fields&&
h.push(...c.fields.map(m=>ia(a,b.fieldsIndex,m)));yield Promise.all(h)}});return F.apply(this,arguments)}function G(){G=g._asyncToGenerator(function*(a,b,c){b&&(b.timeInfo&&k.isSome(c)&&c.timeExtent&&p(a,b.fieldsIndex,[b.timeInfo.startField,b.timeInfo.endField]),b.floorInfo&&p(a,b.fieldsIndex,[b.floorInfo.floorField]),k.isSome(c)&&k.isSome(c.where)&&(yield T(a,b.fieldsIndex,c.where)))});return G.apply(this,arguments)}function H(){H=g._asyncToGenerator(function*(a,b,c){b&&c&&(yield Promise.all(c.map(e=>
ja(a,b,e))))});return H.apply(this,arguments)}function ja(a,b,c){return I.apply(this,arguments)}function I(){I=g._asyncToGenerator(function*(a,b,c){b&&c&&(c.valueExpression?yield l(a,b.fieldsIndex,c.valueExpression):c.field&&q(a,b.fieldsIndex,c.field))});return I.apply(this,arguments)}function J(){J=g._asyncToGenerator(function*(a){if(!a)return[];const b="timeInfo"in a&&a.timeInfo;return b?n(a.fieldsIndex,[a.trackIdField,b.startField,b.endField]):[]});return J.apply(this,arguments)}function K(){K=
g._asyncToGenerator(function*(a){if(!a)return[];const b=new Set;yield V(b,a);return Array.from(b).sort()});return K.apply(this,arguments)}function V(a,b){return L.apply(this,arguments)}function L(){L=g._asyncToGenerator(function*(a,b){const {labelingInfo:c,fieldsIndex:e}=b;c&&c.length&&(yield Promise.all(c.map(f=>ka(a,e,f))))});return L.apply(this,arguments)}function ka(a,b,c){return M.apply(this,arguments)}function M(){M=g._asyncToGenerator(function*(a,b,c){if(c){var e=c.getLabelExpression();c=c.where;
"arcade"===e.type?yield l(a,b,e.expression):(e=e.expression.match(/{[^}]*}/g))&&e.forEach(f=>{q(a,b,f.slice(1,-1))});yield T(a,b,c)}});return M.apply(this,arguments)}function N(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}function la(a){return null===a||N(a)}function ma(a){return null===a||t(a)}function W(a){return null!=a&&"string"===typeof a}function na(a){return null===a||W(a)}function oa(){return!0}function O(a,b){let c;switch(a.type){case "date":case "integer":case "long":case "small-integer":case "esriFieldTypeDate":case "esriFieldTypeInteger":case "esriFieldTypeLong":case "esriFieldTypeSmallInteger":c=
a.nullable?ma:t;break;case "double":case "single":case "esriFieldTypeSingle":case "esriFieldTypeDouble":c=a.nullable?la:N;break;case "string":case "esriFieldTypeString":c=a.nullable?na:W;break;default:c=oa}return 1===arguments.length?c:c(b)}function P(a){return null!=a&&pa.has(a.type)}function X(a,b){return a.nullable&&null===b?null:P(a)&&!Y(a.type,Number(b))?d.NumericRangeValidationError.OUT_OF_RANGE:O(a,b)?a.domain?r.validateDomainValue(a.domain,b):null:d.TypeValidationError.INVALID_TYPE}function Y(a,
b){return(a="string"===typeof a?Q(a):a)?a.isInteger?t(b)&&b>=a.min&&b<=a.max:b>=a.min&&b<=a.max:!1}function Q(a){switch(a){case "esriFieldTypeSmallInteger":case "small-integer":return u;case "esriFieldTypeInteger":case "integer":return v;case "esriFieldTypeSingle":case "single":return w;case "esriFieldTypeDouble":case "double":return Z}}function aa(a,b,c){if(!b||!b.attributes||!a){if(k.isSome(c))for(var e of a)c.add(e);return!0}b=b.attributes;e=!1;for(const f of a)if(!(f in b))if(e=!0,k.isSome(c))c.add(f);
else break;return e}function R(){R=g._asyncToGenerator(function*(a,b){const c=new Set;for(const e of b)yield l(c,a.fieldsIndex,e);return Array.from(c).sort()});return R.apply(this,arguments)}const ba="field field2 field3 normalizationField rotationInfo.field proportionalSymbolInfo.field proportionalSymbolInfo.normalizationField colorInfo.field colorInfo.normalizationField".split(" "),ca=["field","normalizationField"],y=new Set,t=(()=>"isInteger"in Number?Number.isInteger:a=>"number"===typeof a&&isFinite(a)&&
Math.floor(a)===a)(),da=["integer","small-integer","single","double"],pa=new Set([...da,"esriFieldTypeInteger","esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"]);d.NumericRangeValidationError=void 0;(d.NumericRangeValidationError||(d.NumericRangeValidationError={})).OUT_OF_RANGE="numeric-range-validation-error::out-of-range";d.TypeValidationError=void 0;(d.TypeValidationError||(d.TypeValidationError={})).INVALID_TYPE="type-validation-error::invalid-type";const u={min:-32768,
max:32767,isInteger:!0},v={min:-2147483648,max:2147483647,isInteger:!0},w={min:-3.4E38,max:1.2E38,isInteger:!1},Z={min:-Number.MAX_VALUE,max:Number.MAX_VALUE,isInteger:!1};d.collectArcadeFieldNames=l;d.collectElevationFields=U;d.collectFeatureReductionFields=function(a,b,c){return F.apply(this,arguments)};d.collectField=q;d.collectFields=p;d.collectFilterFields=function(a,b,c){return G.apply(this,arguments)};d.collectLabelingFields=V;d.collectOrderByInfos=function(a,b,c){return H.apply(this,arguments)};
d.doubleRange=Z;d.featureHasFields=function(a,b){return!aa(a,b,null)};d.fixFields=n;d.fixRendererFields=function(a,b){if(null!=a&&null!=b)for(const c of Array.isArray(a)?a:[a])if(S(ba,c,b),"visualVariables"in c&&c.visualVariables)for(const e of c.visualVariables)S(ca,e,b)};d.fixTimeInfoFields=function(a,b){if(null!=a&&null!=b&&b.fields.length)if("startField"in a){var c=b.get(a.startField);b=b.get(a.endField);a.startField=c&&c.name||null;a.endField=b&&b.name||null}else c=b.get(a.startTimeField),b=
b.get(a.endTimeField),a.startTimeField=c&&c.name||null,a.endTimeField=b&&b.name||null};d.getDisplayFieldName=function({displayField:a,fields:b}){if(a)return a;if(!b||!b.length)return null;if(!(a=B(b,"name-or-title")||B(b,"unique-identifier")||B(b,"type-or-category")))a:{for(const c of b)if(c&&c.name&&(b=c.name.toLowerCase(),-1<b.indexOf("name")||-1<b.indexOf("title"))){a=c.name;break a}a=null}return a};d.getElevationFields=function(a){return C.apply(this,arguments)};d.getExpressionFields=function(a,
b){return R.apply(this,arguments)};d.getFeatureEditFields=function(a){if(!a)return[];const b="editFieldsInfo"in a&&a.editFieldsInfo;return b?n(a.fieldsIndex,[b&&b.creatorField,b&&b.creationDateField,b&&b.editorField,b&&b.editDateField]):[]};d.getFeatureGeometryFields=function(a){if(!a)return[];const b=a.geometryFieldsInfo;return b?n(a.fieldsIndex,[b.shapeAreaField,b.shapeLengthField]):[]};d.getFieldDefaultValue=function(a){const b=a.defaultValue;if(void 0!==b&&O(a,b))return b;if(a.nullable)return null};
d.getFieldRange=function(a){const b=r.getDomainRange(a.domain);if(b)return b;if(P(a))return Q(a.type)};d.getLabelingFields=function(a){return K.apply(this,arguments)};d.getNumericTypeForValue=function(a){if(!N(a))return null;if(t(a)){if(a>=u.min&&a<=u.max)return"esriFieldTypeSmallInteger";if(a>=v.min&&a<=v.max)return"esriFieldTypeInteger"}return a>=w.min&&a<=w.max?"esriFieldTypeSingle":"esriFieldTypeDouble"};d.getTimeFields=function(a){return J.apply(this,arguments)};d.integerRange=v;d.isDateField=
function(a){return null!=a&&("date"===a.type||"esriFieldTypeDate"===a.type)};d.isNumberInRange=Y;d.isNumericField=P;d.isStringField=function(a){return null!=a&&("string"===a.type||"esriFieldTypeString"===a.type)};d.isValidFieldValue=function(a,b){return null===X(a,b)};d.isValueMatchingFieldType=O;d.numericTypes=da;d.packFields=function(a,b,c=1){if(!b||!a)return[];if(b.includes("*"))return["*"];b=n(a,b);return b.length/a.fields.length>=c?["*"]:b};d.populateMissingFields=aa;d.rendererFields=ba;d.sanitizeNullFieldValue=
function(a){return null==a||"number"===typeof a&&isNaN(a)?null:a};d.singleRange=w;d.smallIntegerRange=u;d.unpackFieldNames=function(a,b){return k.isNone(b)||k.isNone(a)?[]:b.includes("*")?a.fields.map(c=>c.name):b};d.validateFieldValue=X;d.validationErrorToString=function(a,b,c){switch(a){case r.DomainValidationError.INVALID_CODED_VALUE:return`Value ${c} is not in the coded domain - field: ${b.name}, domain: ${JSON.stringify(b.domain)}`;case r.DomainValidationError.VALUE_OUT_OF_RANGE:return`Value ${c} is out of the range of valid values - field: ${b.name}, domain: ${JSON.stringify(b.domain)}`;
case d.TypeValidationError.INVALID_TYPE:return`Value ${c} is not a valid value for the field type - field: ${b.name}, type: ${b.type}, nullable: ${b.nullable}`;case d.NumericRangeValidationError.OUT_OF_RANGE:{const {min:e,max:f}=Q(b.type);return`Value ${c} is out of range for the number type - field: ${b.name}, type: ${b.type}, value range is ${e} to ${f}`}}};d.visualVariableFields=ca;Object.defineProperty(d,"__esModule",{value:!0})});