// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../core/Collection ../../core/has ../../core/promiseUtils ./lazyLayerLoader ../../portal/PortalItem ../../portal/support/featureCollectionUtils ../../portal/support/portalLayers ../../renderers/support/styleUtils".split(" "),function(t,g,B,R,C,f,D,u,E,F){function v(a,b,c){return l.apply(this,arguments)}function l(){l=g._asyncToGenerator(function*(a,b,c){if(b){var d=[];for(const e of b)b=G(e,c),"GroupLayer"===e.layerType?d.push(H(b,e,c)):d.push(b);
d=yield C.eachAlways(d);for(const e of d)!e.value||c.filter&&!c.filter(e.value)||a.add(e.value)}});return l.apply(this,arguments)}function G(a,b){return m.apply(this,arguments)}function m(){m=g._asyncToGenerator(function*(a,b){const c=yield I(a,b);return J(c,a,b)});return m.apply(this,arguments)}function J(a,b,c){return n.apply(this,arguments)}function n(){n=g._asyncToGenerator(function*(a,b,c){a=new a;a.read(b,c.context);"group"===a.type&&w(b)&&(yield K(a,b,c.context));yield F.loadStyleRenderer(a,
c.context);return a});return n.apply(this,arguments)}function I(a,b){return p.apply(this,arguments)}function p(){p=g._asyncToGenerator(function*(a,b){var c=b.context;switch(c.origin){case "web-scene":switch(c.layerContainerType){case "basemap":var d=L;break;case "ground":d=M;break;default:d=N}break;default:switch(c.layerContainerType){case "basemap":d=O;break;case "tables":d=P;break;default:d=Q}}var e=d;d=a.layerType||a.type;!d&&b&&b.defaultLayerType&&(d=b.defaultLayerType);b=(b=e[d])?f.layerLookupMap[b]:
f.layerLookupMap.UnknownLayer;c=c&&c.portal;"Feature Collection"===a.type?a.itemId&&(a=new D({id:a.itemId,portal:c}),yield a.load(),a=(yield E.selectLayerClassPath(a)).className||"UnknownLayer",b=f.layerLookupMap[a]):"ArcGISFeatureLayer"===d?(yield u.isMapNotesLayer(a,c))?b=f.layerLookupMap.MapNotesLayer:(yield u.isRouteLayer(a,c))?b=f.layerLookupMap.RouteLayer:w(a)&&(b=f.layerLookupMap.GroupLayer):a.wmtsInfo&&a.wmtsInfo.url&&a.wmtsInfo.layerIdentifier?b=f.layerLookupMap.WMTSLayer:"WFS"===d&&"2.0.0"!==
a.wfsInfo.version&&(b=f.layerLookupMap.UnsupportedLayer);return b()});return p.apply(this,arguments)}function w(a){if("ArcGISFeatureLayer"!==a.layerType||"Feature Collection"===a.type)return!1;a=a.featureCollection;return!!(a&&a.layers&&1<a.layers.length)}function H(a,b,c){return q.apply(this,arguments)}function q(){q=g._asyncToGenerator(function*(a,b,c){const d=new B;b=v(d,Array.isArray(b.layers)?b.layers:[],c);a=yield a;yield b;if("group"===a.type)return a.layers.addMany(d),a});return q.apply(this,
arguments)}function K(a,b,c){return r.apply(this,arguments)}function r(){r=g._asyncToGenerator(function*(a,b,c){const d=yield(0,f.layerLookupMap.FeatureLayer)();var e=b.featureCollection;const x=e.showLegend;e=e.layers.map((h,y)=>{var z,A;const k=new d;k.read(h,c);h={...c,ignoreDefaults:!0};k.read({id:`${a.id}-sublayer-${y}`,visibility:null!=(z=null==(A=b.visibleLayers)?void 0:A.includes(y))?z:!0},h);null!=x&&k.read({showLegend:x},h);return k});a.layers.addMany(e)});return r.apply(this,arguments)}
const N={ArcGISFeatureLayer:"FeatureLayer",ArcGISImageServiceLayer:"ImageryLayer",ArcGISMapServiceLayer:"MapImageLayer",PointCloudLayer:"PointCloudLayer",ArcGISSceneServiceLayer:"SceneLayer",IntegratedMeshLayer:"IntegratedMeshLayer",OGCFeatureLayer:"OGCFeatureLayer",BuildingSceneLayer:"BuildingSceneLayer",ArcGISTiledElevationServiceLayer:"ElevationLayer",ArcGISTiledImageServiceLayer:"ImageryTileLayer",ArcGISTiledMapServiceLayer:"TileLayer",GroupLayer:"GroupLayer",GeoJSON:"GeoJSONLayer",WebTiledLayer:"WebTileLayer",
CSV:"CSVLayer",VectorTileLayer:"VectorTileLayer",WFS:"WFSLayer",WMS:"WMSLayer",DefaultTileLayer:"TileLayer",KML:"KMLLayer",RasterDataLayer:"UnsupportedLayer",Voxel:"UnsupportedLayer"},M={ArcGISTiledElevationServiceLayer:"ElevationLayer",DefaultTileLayer:"ElevationLayer",RasterDataElevationLayer:"UnsupportedLayer"},L={ArcGISTiledMapServiceLayer:"TileLayer",ArcGISTiledImageServiceLayer:"ImageryTileLayer",OpenStreetMap:"OpenStreetMapLayer",WebTiledLayer:"WebTileLayer",VectorTileLayer:"VectorTileLayer",
ArcGISImageServiceLayer:"UnsupportedLayer",WMS:"UnsupportedLayer",ArcGISMapServiceLayer:"UnsupportedLayer",DefaultTileLayer:"TileLayer"},Q={ArcGISFeatureLayer:"FeatureLayer",ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"ImageryLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISStreamLayer:"StreamLayer",ArcGISTiledImageServiceLayer:"ImageryTileLayer",ArcGISTiledMapServiceLayer:"TileLayer",BingMapsAerial:"BingMapsLayer",BingMapsRoad:"BingMapsLayer",BingMapsHybrid:"BingMapsLayer",
CSV:"CSVLayer",DefaultTileLayer:"TileLayer",GeoRSS:"GeoRSSLayer",GeoJSON:"GeoJSONLayer",GroupLayer:"GroupLayer",KML:"KMLLayer",OGCFeatureLayer:"OGCFeatureLayer",SubtypeGroupLayer:"UnsupportedLayer",VectorTileLayer:"VectorTileLayer",WFS:"WFSLayer",WMS:"WMSLayer",WebTiledLayer:"WebTileLayer"},P={ArcGISFeatureLayer:"FeatureLayer"},O={ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"ImageryLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISTiledImageServiceLayer:"ImageryTileLayer",
ArcGISTiledMapServiceLayer:"TileLayer",OpenStreetMap:"OpenStreetMapLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",BingMapsAerial:"BingMapsLayer",BingMapsRoad:"BingMapsLayer",BingMapsHybrid:"BingMapsLayer",WMS:"WMSLayer",DefaultTileLayer:"TileLayer"};t.populateOperationalLayers=v;Object.defineProperty(t,"__esModule",{value:!0})});