// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["require","exports","../../chunks/_rollupPluginBabelHelpers"],function(e,h,f){const g=a=>Object.freeze({__proto__:null,default:a}),k={BingMapsLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../BingMapsLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),BuildingSceneLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../BuildingSceneLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,
arguments)}}(),CSVLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../CSVLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ElevationLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../ElevationLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),FeatureLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../FeatureLayer"],
d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),GroupLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../GroupLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),GeoRSSLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../GeoRSSLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),GeoJSONLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,
c)=>e(["../GeoJSONLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ImageryLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../ImageryLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ImageryTileLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../ImageryTileLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),
IntegratedMeshLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../IntegratedMeshLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),KMLLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../KMLLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),MapImageLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../MapImageLayer"],
d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),MapNotesLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../MapNotesLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),OGCFeatureLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../OGCFeatureLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),OpenStreetMapLayer:function(){var a=
f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../OpenStreetMapLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),PointCloudLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../PointCloudLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),RouteLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../RouteLayer"],d=>b(g(d)),c))).default});
return function(){return a.apply(this,arguments)}}(),SceneLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../SceneLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),StreamLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../StreamLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),TileLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,
c)=>e(["../TileLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),UnknownLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../UnknownLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),UnsupportedLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../UnsupportedLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),VectorTileLayer:function(){var a=
f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../VectorTileLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),VoxelLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../VoxelLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),WebTileLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../WebTileLayer"],d=>b(g(d)),c))).default});
return function(){return a.apply(this,arguments)}}(),WFSLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../WFSLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),WMSLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../WMSLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),WMTSLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,
c)=>e(["../WMTSLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}()};h.layerLookupMap=k;Object.defineProperty(h,"__esModule",{value:!0})});