// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../core/Error ../../core/maybe ../../core/urlUtils ../../geometry/Extent ../../geometry/SpatialReference".split(" "),function(v,aa,ba,ca,D,K){function L(a){return da.some(([c,b])=>a>=c&&a<=b)}function M(a){if(0<a.spatialReferences.length)return a.spatialReferences;if(a.sublayers)for(const c of a.sublayers)if(a=M(c),0<a.length)return a;return[]}function N(a){let c=[];a.forEach(b=>{c.push(b);b.sublayers&&b.sublayers.length&&(c=c.concat(N(b.sublayers)),delete b.sublayers)});return c}
function E(a,c,b){var d;return null!=(d=c.getAttribute(a))?d:b}function m(a,c){for(let b=0;b<c.childNodes.length;b++){const d=c.childNodes[b];if(d.nodeType===Node.ELEMENT_NODE&&d.nodeName===a)return d}return null}function F(a,c){const b=[];for(let d=0;d<c.childNodes.length;d++){const e=c.childNodes[d];e.nodeType===Node.ELEMENT_NODE&&e.nodeName===a&&b.push(e)}return b}function w(a,c,b){return(a=m(a,c))?a.textContent:b}function B(a,c,b){if(!a)return null;var d=parseFloat(a.getAttribute("minx")),e=parseFloat(a.getAttribute("miny")),
g=parseFloat(a.getAttribute("maxx"));a=parseFloat(a.getAttribute("maxy"));b?(b=isNaN(e)?-Number.MAX_VALUE:e,d=isNaN(d)?-Number.MAX_VALUE:d,e=isNaN(a)?Number.MAX_VALUE:a,g=isNaN(g)?Number.MAX_VALUE:g):(b=isNaN(d)?-Number.MAX_VALUE:d,d=isNaN(e)?-Number.MAX_VALUE:e,e=isNaN(g)?Number.MAX_VALUE:g,g=isNaN(a)?Number.MAX_VALUE:a);c=new K({wkid:c});return new D({xmin:b,ymin:d,xmax:e,ymax:g,spatialReference:c})}function O(a,c){if(a=m(c,a))if(a=m("DCPType",a))if(a=m("HTTP",a))if(a=m("Get",a)){var b=a=(a=m("OnlineResource",
a))?E("xlink:href",a,null):null;if(b){b.indexOf("\x26")===b.length-1&&(b=b.substring(0,b.length-1));var d;a=["service","request"];c=[];b=ca.urlToObject(b);for(d in b.query)b.query.hasOwnProperty(d)&&-1===a.indexOf(d.toLowerCase())&&c.push(d+"\x3d"+b.query[d]);return d=b.path+(c.length?"?"+c.join("\x26"):"")}}return null}function P(a,c){const b=F("Operation",a);if(0===b.length)return a=m(c,a),F("Format",a).map(e=>e.textContent);const d=[];b.forEach(e=>{e.getAttribute("name")===c&&F("Format",e).forEach(g=>
{d.push(g.textContent)})});return d}function Q(a,c,b){a=m(c,a);if(!a)return b;({textContent:a}=a);if(null==a||""===a)return b;a=Number(a);return isNaN(a)?b:a}function G(a,c,b){var d;if(!a)return null;const e={id:b.idCounter++,fullExtents:[],parentLayerId:null,queryable:"1"===a.getAttribute("queryable"),spatialReferences:[],sublayers:null},g=m("LatLonBoundingBox",a),p=m("EX_GeographicBoundingBox",a);let q=null;g&&(q=B(g,4326));p&&(q=new D(0,0,0,0,new K({wkid:4326})),q.xmin=parseFloat(w("westBoundLongitude",
p,"0")),q.ymin=parseFloat(w("southBoundLatitude",p,"0")),q.xmax=parseFloat(w("eastBoundLongitude",p,"0")),q.ymax=parseFloat(w("northBoundLatitude",p,"0")));g||p||(q=new D(-180,-90,180,90,new K({wkid:4326})));e.minScale=Q(a,"MaxScaleDenominator",0);e.maxScale=Q(a,"MinScaleDenominator",0);const H=-1<["1.0.0","1.1.0","1.1.1"].indexOf(c)?"SRS":"CRS";Array.prototype.slice.call(a.childNodes).forEach(f=>{if("Name"===f.nodeName)e.name=f.textContent||"";else if("Title"===f.nodeName)e.title=f.textContent||
"";else if("Abstract"===f.nodeName)e.description=f.textContent||"";else if("BoundingBox"===f.nodeName){var h=f.getAttribute(H);if(h&&0===h.indexOf("EPSG:")){var r=parseInt(h.substring(5),10);0===r||isNaN(r)||q||(q="1.3.0"===c?B(f,r,L(r)):B(f,r))}(r=h&&h.indexOf(":"))&&-1<r&&(h=parseInt(h.substring(r+1,h.length),10),0===h||isNaN(h)||(h=I[h]?I[h]:h),f="1.3.0"===c?B(f,h,L(h)):B(f,h),e.fullExtents.push(f))}else if(f.nodeName===H)f.textContent.split(" ").forEach(l=>{l=l.includes(":")?parseInt(l.split(":")[1],
10):parseInt(l,10);0===l||isNaN(l)||(l=I[l]?I[l]:l,e.spatialReferences.includes(l)||e.spatialReferences.push(l))});else if("Style"!==f.nodeName||e.legendURL)"Layer"===f.nodeName&&(f=G(f,c,b))&&(f.parentLayerId=e.id,e.sublayers||(e.sublayers=[]),e.sublayers.push(f));else if(f=m("LegendURL",f))if(f=m("OnlineResource",f))e.legendURL=f.getAttribute("xlink:href")});e.extent=null==(d=q)?void 0:d.toJSON();e.dimensions=F("Dimension",a).filter(f=>f.getAttribute("name")&&f.getAttribute("units")&&f.textContent).map(f=>
{const h=f.getAttribute("name"),r=f.getAttribute("units"),l=f.textContent,k=f.getAttribute("unitSymbol"),x=f.getAttribute("default"),z="0"!==E("default",f,"0"),t="0"!==E("nearestValue",f,"0");f="0"!==E("current",f,"0");return/^time$/i.test(h)&&/^ISO8601$/i.test(r)?{name:"time",units:"ISO8601",extent:R(l),default:R(x),multipleValues:z,nearestValue:t,current:f}:/^elevation$/i.test(h)?{name:"elevation",units:r,extent:S(l),unitSymbol:k,default:S(x),multipleValues:z,nearestValue:t}:{name:h,units:r,extent:T(l),
unitSymbol:k,default:T(x),multipleValues:z,nearestValue:t}});return e}function ea(a){return Array.isArray(a)&&0<a.length&&a[0]instanceof Date}function U(a){return"time"===a.name}function S(a){if(!a)return null;const c=-1!==a.indexOf("/");a=a.split(",");return c?a.map(b=>{var d=b.split("/");if(2>d.length)return null;b=parseFloat(d[0]);const e=parseFloat(d[1]);d=3<=d.length&&"0"!==d[2]?parseFloat(d[2]):void 0;return{min:b,max:e,resolution:d}}).filter(b=>b):a.map(b=>parseFloat(b))}function T(a){if(!a)return null;
const c=-1!==a.indexOf("/");a=a.split(",");return c?a.map(b=>{b=b.split("/");return 2>b.length?null:{min:b[0],max:b[1],resolution:3<=b.length&&"0"!==b[2]?b[2]:void 0}}).filter(b=>b):a}function R(a){if(!a)return null;const c=-1!==a.indexOf("/");a=a.split(",");return c?a.map(b=>{var d=b.split("/");if(2>d.length)return null;b=new Date(d[0]);const e=new Date(d[1]);d=3<=d.length&&"0"!==d[2]?V(d[2]):void 0;return{min:b,max:e,resolution:d}}).filter(b=>b):a.map(b=>new Date(b))}function V(a){var c=a.match(/(?:p(\d+y|\d+(?:.|,)\d+y)?(\d+m|\d+(?:.|,)\d+m)?(\d+d|\d+(?:.|,)\d+d)?)?(?:t(\d+h|\d+(?:.|,)\d+h)?(\d+m|\d+(?:.|,)\d+m)?(\d+s|\d+(?:.|,)\d+s)?)?/i);
if(!c)return null;a=A(c[1]);const b=A(c[2]),d=A(c[3]),e=A(c[4]),g=A(c[5]);c=A(c[6]);return{years:a,months:b,days:d,hours:e,minutes:g,seconds:c}}function A(a){if(!a)return 0;a=a.match(/(?:\d+(?:.|,)\d+|\d+)/);if(!a)return 0;a=a[0].replace(",",".");return Number(a)}const da=[[4001,4999],[2044,2045],[2081,2083],[2085,2086],[2093,2093],[2096,2098],[2105,2132],[2169,2170],[2176,2180],[2193,2193],[2200,2200],[2206,2212],[2319,2319],[2320,2462],[2523,2549],[2551,2735],[2738,2758],[2935,2941],[2953,2953],
[3006,3030],[3034,3035],[3058,3059],[3068,3068],[3114,3118],[3126,3138],[3300,3301],[3328,3335],[3346,3346],[3350,3352],[3366,3366],[3416,3416],[20004,20032],[20064,20092],[21413,21423],[21473,21483],[21896,21899],[22171,22177],[22181,22187],[22191,22197],[25884,25884],[27205,27232],[27391,27398],[27492,27492],[28402,28432],[28462,28492],[30161,30179],[30800,30800],[31251,31259],[31275,31279],[31281,31290],[31466,31700]],I={84:4326,83:4269,27:4267},W=new Set([102100,3857,102113,900913]),fa=new Set([3395,
54004]);v.coordsReversedForWKID=L;v.fromISODuration=V;v.getPopupLayers=function(a){return a.length?a.filter(c=>c.popupEnabled&&c.name&&c.queryable).map(c=>c.name).join(","):""};v.isDimensionInterval=function(a){return void 0!==a.min&&void 0!==a.max};v.isElevationDimension=function(a){return"elevation"===a.name};v.isGenericDimension=function(a){return"time"!==a.name&&"elevation"!==a.name};v.isTimeDimension=U;v.normalizeWKID=function(a,c){let b=a.wkid;if(ba.isNone(c))return b;!c.includes(b)&&a.latestWkid&&
(b=a.latestWkid);return W.has(b)?c.find(d=>W.has(d))||c.find(d=>fa.has(d))||102100:b};v.parseCapabilities=function(a){if(!a)return null;const c={idCounter:-1};"string"===typeof a&&(a=(new DOMParser).parseFromString(a,"text/xml"));a=a.documentElement;if("ServiceExceptionReport"===a.nodeName){var b=Array.prototype.slice.call(a.childNodes).map(n=>n.textContent).join("\r\n");throw new aa("wmslayer:wms-capabilities-xml-is-not-valid","The server returned errors when the WMS capabilities were requested.",
b);}var d=m("Capability",a),e=m("Service",a),g=m("Request",d);if(!d||!e||!g)return null;var p=m("Layer",d);if(!p)return null;const q="WMS_Capabilities"===a.nodeName||"WMT_MS_Capabilities"===a.nodeName?a.getAttribute("version"):"1.3.0";a=w("Title",e,"")||w("Name",e,"");const H=w("AccessConstraints",e,""),f=w("Abstract",e,""),h=parseInt(w("MaxWidth",e,"5000"),10);e=parseInt(w("MaxHeight",e,"5000"),10);const r=P(g,"GetMap"),l=O(g,"GetMap"),k=G(p,q,c);let x=0,z;Array.prototype.slice.call(d.childNodes).forEach(n=>
{"Layer"===n.nodeName&&(0===x?z=n:(1===x&&k.name&&(k.name="",k.sublayers.push(G(z,q,c))),k.sublayers.push(G(n,q,c))),x++)});if(!k)return null;var t;d=k.fullExtents;(t=k.sublayers)||(t=[]);0===t.length&&t.push(k);p=k.extent;p||(p=new D(t[0].extent),k.extent=p.toJSON(),p=k.extent);const ha=0<k.spatialReferences.length?k.spatialReferences:M(k),X=O(g,"GetFeatureInfo");X&&(g=P(g,"GetFeatureInfo"),-1<g.indexOf("text/html")?b="text/html":-1<g.indexOf("text/plain")&&(b="text/plain"));if(!b){const n=function(u){u&&
(u.queryable=!1,u.sublayers&&u.sublayers.forEach(y=>{n(y)}))};n(k)}g=N(t);t=k.minScale||0;const ia=k.maxScale||0,Y=k.dimensions;var J=g.reduce((n,u)=>n.concat(u.dimensions),[]);J=Y.concat(J).filter(U);let Z=null;if(0<J.length){let n=Number.POSITIVE_INFINITY,u=Number.NEGATIVE_INFINITY;J.forEach(y=>{({extent:y}=y);ea(y)?y.forEach(C=>{n=Math.min(n,C.getTime());u=Math.max(u,C.getTime())}):y.forEach(C=>{n=Math.min(n,C.min.getTime());u=Math.max(u,C.max.getTime())})});Z={startTimeField:null,endTimeField:null,
trackIdField:null,timeExtent:[n,u]}}return{copyright:H,description:f,dimensions:Y,extent:p,fullExtents:d,featureInfoFormat:b,featureInfoUrl:X,mapUrl:l,maxWidth:h,maxHeight:e,maxScale:ia,minScale:t,layers:g,spatialReferences:ha,supportedImageFormatTypes:r,timeInfo:Z,title:a,version:q}};v.toISOString=function(a){return a.toISOString().replace(/\.[0-9]{3}/,"")};Object.defineProperty(v,"__esModule",{value:!0})});