// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Color ../../../core/Evented ../../../core/Handles ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../chunks/vec4f64 ../../../geometry/projection ../../../geometry/support/spatialReferenceUtils ./EnvironmentRenderer ../support/earthUtils ../support/sunUtils ../webgl-engine/lighting/Lightsources ../../../webscene/background/ColorBackground".split(" "),
function(f,r,k,E,F,G,h,x,t,l,O,P,Q,H,m,u,y,v,z,I,A,p,w,J){f.SceneViewEnvironmentManager=function(B){function q(){var a=B.call(this)||this;a._referencePointUpdateDelay=200;a._referencePointUpdateInterval=3E3;a._referencePointUpdateDistThreshold=1E6;a._referencePosUpdateQuery=null;a._referencePosMapCoordsRequested=null;a._viewHandles=new G;a._preserveAbsoluteDateTime=!1;a._trackingEnabled=!1;a._referencePosResetPreserveAbsoluteTime=!1;a._referencePosUpdateTimer=null;a._referencePosMapCoords=null;a._mainLight=
new w.MainLight;a._ambientLight=new w.AmbientLight;a._moonLight=new w.FillLight;a.disableQueries=!1;a._disableWeather=!1;a._renderer=null;a._referencePosWGS84Comparable=null;a._resetReferencePosition();return a}r._inheritsLoose(q,B);var e=q.prototype;e.destroy=function(){this.disconnectView();this._viewHandles.destroy()};e.connectView=function(a){this._renderer||(this._renderer=new I.EnvironmentRenderer({view:a}),this._viewHandles.add([a.watch("environment.lighting.date",b=>this._lightingDateHandler(b),
!0),a.watch("stationary",()=>this._interactingStationaryHandler()),a.watch(["environment.lighting.directShadowsEnabled","environment.lighting.ambientOcclusionEnabled","environment.lighting.waterReflectionEnabled","environment.background.color"],()=>this._updateRenderParamsHandler(),!0),a.watch("spatialReference",()=>this._resetReferencePosition(!0),!0),a.watch("environment.weather.type",()=>this._updateLightParams(),!0),this.watch("weatherEnabled",()=>this._updateLightParams(),!0),t.init(a,"viewingMode",
()=>this._resetReferencePosition(!0),!0),t.init(a,"environment.lighting.cameraTrackingEnabled",b=>this._updateCameraTracking(b),!0),t.init(a,"state.camera",()=>this._cameraHandler(),!0),this.watch("disableQueries",()=>this._cameraHandler())]),this._updateRenderParamsHandler(),this._updateLightParams(),this._cameraHandler(),this.notifyChange("updating"))};e.disconnectView=function(){this._viewHandles.removeAll();this._resetReferencePosition();this._renderer=h.destroyMaybe(this._renderer)};e._updateCameraTracking=
function(a){if(this._trackingEnabled=a)this._cameraHandler();else if(a=this._view.environment.lighting)a.positionTimezoneInfo.autoUpdated=!1};e._lightingDateHandler=function(a){if(a){var b=this._view.environment.lighting;if(!b.positionTimezoneInfo.autoUpdated){this._preserveAbsoluteDateTime=!0;if(!v.canProjectToWGS84ComparableLonLat(this._view.spatialReference)){var c=this._view.camera.position;if(!this._referencePosMapCoords||!this._referencePosMapCoords.equals(c)){this._requestReferencePositionUpdate(c);
return}}this._preupdateTracking(a);h.isSome(this._referencePosWGS84Comparable)&&(c=A.positionToTimezoneInfo(this._referencePosWGS84Comparable,C),h.isSome(c)&&(b.autoUpdate(null,c),this._trackingEnabled&&(b.positionTimezoneInfo.autoUpdated=!0)))}this._updateLightParams(a)}};e._preupdateTracking=function(a){!this._trackingEnabled&&this._view.environment.lighting.cameraTrackingEnabled&&this._cameraHandler(a)};e._cameraHandler=function(a=null){var b=this._view;b.ready&&(b=b.stateManager.camera)&&(this._cameraHandlerClientSide(b,
a)||this._cameraHandlerServerSide(b))};e._cameraHandlerClientSide=function(a,b){const c=z.isEarth(this._view.spatialReference);if(c&&!v.canProjectToWGS84ComparableLonLat(this._view.spatialReference))return!1;a=a.position;h.isNone(this._referencePosWGS84Comparable)&&(this._referencePosWGS84Comparable=u.create());c?v.projectPointToWGS84ComparableLonLat(a,this._referencePosWGS84Comparable):m.set(this._referencePosWGS84Comparable,a.longitude,a.latitude,a.z);this.notifyChange("referencePositionWGS84Comparable");
this._autoUpdateTimezone(this._referencePosWGS84Comparable,b)||this._updateLightParams(b);return!0};e._cameraHandlerServerSide=function(a){a=a.position;(!this._referencePosMapCoords||this._referencePosMapCoordsRequested||this._exceedsReferencePosDistThreshold(a))&&this._requestReferencePositionUpdate(a,!0);this._view.mapCoordsHelper&&this._referencePosWGS84Comparable&&(this._referencePosWGS84Comparable[2]=a.z*this._view.mapCoordsHelper.unitInMeters,this._referencePosChanged())};e._interactingStationaryHandler=
function(){this._view.stationary&&this._executePendingReferencePositionUpdate()};e._updateLightParams=function(a){var b=this._view,c=b.environment.lighting,d=a||c.date;a=b._stage;var g=this._referencePosWGS84Comparable;c=h.isSome(g)?D:K;h.isSome(g)&&p.computeColorAndIntensity(d,g,b.state.viewingMode,D,this.weatherEnabled?b.environment.weather.type:"disabled");b=this._mainLight;d=c.direct;m.scale(b.intensity,d.color,d.intensity*Math.PI);m.copy(b.direction,d.directionToLightSource);g=this._ambientLight;
m.scale(g.intensity,c.ambient.color,c.ambient.intensity);const n=this._moonLight;m.lerp(n.intensity,L,M,c.globalFactor);m.scale(n.intensity,n.intensity,(1-.5*c.globalFactor)*(1-.4*c.noonFactor*(1-c.globalFactor)));m.copy(n.direction,d.directionToLightSource);a.renderView.updateLightSources([b,g,n],1-c.noonFactor,c.globalFactor);this._updateRenderParamsHandler()};e._autoUpdateTimezone=function(a,b=null){if(!this._view.environment.lighting.cameraTrackingEnabled||h.isNone(a))return!1;const c=N;c.setTime((b||
this._view.environment.lighting.date).getTime());a=A.positionToTimezoneInfo(a,C);if(h.isNone(a))return!1;var d=this._view.environment.lighting.positionTimezoneInfo;if(!d.autoUpdated)d=a;else if(d.hours===a.hours&&d.minutes===a.minutes&&d.seconds===a.seconds)return!1;const g=c.getUTCHours()-(a.hours-d.hours),n=c.getUTCMinutes()-(a.minutes-d.minutes);d=c.getUTCSeconds()-(a.seconds-d.seconds);c.setUTCHours(g);c.setUTCMinutes(n);c.setUTCSeconds(d);return b?!1:this._view.environment.lighting.autoUpdate(c,
a)};e._updateRenderParamsHandler=function(){const a=this._view._stage;if(a){var b=h.mapOr(this._referencePosWGS84Comparable,!0,d=>p.computeShadowsEnabled(d[2],this._view.state.viewingMode)),c=this._view.environment.background;c=c instanceof J?{type:"color",color:y.fromArray(E.toUnitRGBA(c.color))}:{type:"color",color:y.fromValues(0,0,0,1)};a.renderView.setRenderParameters({shadowMap:this._view.environment.lighting.directShadowsEnabled&&b,ssao:this._view.environment.lighting.ambientOcclusionEnabled,
waterReflectionEnabled:this._view.environment.lighting.waterReflectionEnabled,background:c})}};e._resetReferencePosition=function(a=!1){this._cancelReferencePosUpdates();this._referencePosWGS84Comparable=this._referencePosResetPreserveAbsoluteTime=this._referencePosMapCoordsRequested=this._referencePosMapCoords=null;this.notifyChange("updating");a&&this._cameraHandler()};e._requestReferencePositionUpdate=function(a,b=!1){if(!this.disableQueries&&(this._referencePosMapCoordsRequested?this._referencePosMapCoordsRequested.copy(a):
this._referencePosMapCoordsRequested=a.clone(),this._referencePosResetPreserveAbsoluteTime=!!b,!this._referencePosUpdateQuery&&!this._referencePosUpdateTimer&&this._view.stationary)){const c=this._referencePosUpdateQuery=x.after(this._referencePointUpdateDelay).then(()=>{if(this._referencePosUpdateQuery===c)return this._doReferencePositionUpdateQuery(()=>this._referencePosUpdateQuery!==c)}).catch(g=>{"mapcoordshelper:missing-geometry-service"===g.name&&(this.disableQueries=!0)}).then(()=>{this._referencePosUpdateQuery===
c&&(this._referencePosUpdateQuery=null,this._referencePosUpdateTimer||this._executePendingReferencePositionUpdate(),this.notifyChange("updating"))}),d=this._referencePosUpdateTimer=x.after(this._referencePointUpdateInterval).then(()=>{this._referencePosUpdateTimer===d&&(this._referencePosUpdateTimer=null,this._referencePosUpdateQuery||this._executePendingReferencePositionUpdate())});this.notifyChange("updating")}};e._doReferencePositionUpdateQuery=function(){var a=r._asyncToGenerator(function*(b){this._referencePosResetPreserveAbsoluteTime&&
(this._preserveAbsoluteDateTime=!1);this._referencePosMapCoords?this._referencePosMapCoords.copy(this._referencePosMapCoordsRequested):this._referencePosMapCoords=this._referencePosMapCoordsRequested.clone();this._referencePosMapCoordsRequested=this._referencePosResetPreserveAbsoluteTime=null;const c=yield this._view.mapCoordsHelper.toGeographic(this._referencePosMapCoords);b()||isNaN(c[0])||isNaN(c[1])||(b=this._referencePosMapCoords.z*this._view.mapCoordsHelper.unitInMeters,this._referencePosWGS84Comparable?
(this._referencePosWGS84Comparable[0]=c[0],this._referencePosWGS84Comparable[1]=c[1],this._referencePosWGS84Comparable[2]=b):this._referencePosWGS84Comparable=[c[0],c[1],b],this._referencePosChanged())});return function(b){return a.apply(this,arguments)}}();e._executePendingReferencePositionUpdate=function(){const a=this._referencePosMapCoordsRequested;a&&this._requestReferencePositionUpdate(a,this._referencePosResetPreserveAbsoluteTime)};e._referencePosChanged=function(){this._preserveAbsoluteDateTime?
this._updateLightParams():this._autoUpdateTimezone(this._referencePosWGS84Comparable)||this._updateLightParams();this.notifyChange("referencePositionWGS84Comparable")};e._exceedsReferencePosDistThreshold=function(a){return this._referencePosMapCoords?(a=this._referencePosMapCoords.distance(a),this._view.mapCoordsHelper&&(a*=this._view.mapCoordsHelper.unitInMeters),a>this._referencePointUpdateDistThreshold):!0};e._cancelReferencePosUpdates=function(){const a=!!this._referencePosUpdateQuery;this._referencePosUpdateTimer=
this._referencePosUpdateQuery=null;return a};r._createClass(q,[{key:"_view",get:function(){var a;return null==(a=this._renderer)?void 0:a.view}},{key:"updating",get:function(){var a;return!!(!this.disableQueries&&(this._referencePosUpdateQuery||this._referencePosMapCoordsRequested)||null!=(a=this._renderer)&&a.updating)}},{key:"weatherEnabled",get:function(){var a,b,c;return(null==(a=this._view)?void 0:a.environment.atmosphereEnabled)&&!this._disableWeather&&1===(null==(b=this._view)?void 0:null==
(c=b.state)?void 0:c.viewingMode)&&z.isEarth(this._view.spatialReference)}},{key:"referencePositionWGS84Comparable",get:function(){return this._referencePosWGS84Comparable}},{key:"test",get:function(){const a=this;return{get renderer(){return a._renderer},set referencePointUpdateInterval(b){a._referencePointUpdateInterval=b},set referencePointUpdateDistThreshold(b){a._referencePointUpdateDistThreshold=b},set referencePosUpdateTimer(b){a._referencePosUpdateTimer=b},set referencePointUpdateDelay(b){a._referencePointUpdateDelay=
b},set disableWeather(b){a._disableWeather=b}}}}]);return q}(F.EventedAccessor);k.__decorate([l.property({type:Boolean,readOnly:!0})],f.SceneViewEnvironmentManager.prototype,"updating",null);k.__decorate([l.property()],f.SceneViewEnvironmentManager.prototype,"disableQueries",void 0);k.__decorate([l.property()],f.SceneViewEnvironmentManager.prototype,"_disableWeather",void 0);k.__decorate([l.property()],f.SceneViewEnvironmentManager.prototype,"weatherEnabled",null);k.__decorate([l.property()],f.SceneViewEnvironmentManager.prototype,
"referencePositionWGS84Comparable",null);k.__decorate([l.property()],f.SceneViewEnvironmentManager.prototype,"_renderer",void 0);k.__decorate([l.property()],f.SceneViewEnvironmentManager.prototype,"_referencePosWGS84Comparable",void 0);f.SceneViewEnvironmentManager=k.__decorate([H.subclass("esri.views.3d.environment.SceneViewEnvironmentManager")],f.SceneViewEnvironmentManager);const D=new p.ColorAndIntensity,K=new p.ColorAndIntensity,N=new Date,C={hours:0,minutes:0,seconds:0},L=u.fromValues(.22,.22,
.33),M=u.fromValues(.22,.22,.22);Object.defineProperty(f,"__esModule",{value:!0})});