// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../core/Logger ../../../core/mathUtils ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../chunks/mat4 ../../../chunks/mat4f64 ../../../chunks/vec2 ../../../chunks/vec2f64 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../geometry/projectionEllipsoid ../../../geometry/support/spatialReferenceUtils ../../../support/requestImageUtils ./atmosphereUtils ./SimpleAtmosphereTechnique ./resources/MarsAtmosphereTexture ./resources/SimpleAtmosphereTexture ../support/mathUtils ../support/buffer/glUtil ../support/buffer/InterleavedLayout ../webgl-engine/lib/DefaultVertexAttributeLocations ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/Util ../../webgl/BufferObject ../../webgl/Texture ../../webgl/Util ../../webgl/VertexArrayObject".split(" "),
function(D,r,v,m,w,E,F,G,H,I,h,n,J,K,L,x,q,M,N,O,P,Q,R,S,y,T,U,z,V){function A(l,k,b,c,a){const g=h.length(l),d=c*Math.sqrt(g*g-c*c)/g,f=a.silCircleV1,e=a.silCircleV2;h.scale(a.silCircleCenter,l,Math.sqrt(c*c-d*d)/g);h.cross(f,l,k);1>h.squaredLength(f)&&h.cross(f,l,b);h.scale(f,f,d/h.length(f));h.cross(e,f,l);h.scale(e,e,d/h.length(e));return d}const W=r.getLogger("esri.views.3d.environment.SimpleAtmosphere"),B=-x.innerAtmosphereDepth,X=O.makePiecewiseLinearFunction([[50,.1015625],[500,.21875],[5E3,
.51171875],[5E4,.4140625]]);r=function(){function l(b){this.view=b;this.type="simple";this._renderData={texV:I.create(),silCircleCenter:n.create(),silCircleV1:n.create(),silCircleV2:n.create(),altitudeFade:0,innerScale:0,undergroundFadeAlpha:0};this._fadeVaoCount=0;this._readyResolver=w.createResolver();this._readyController=new AbortController;this.texV1=1;this.isOnMars=K.isMars(b.spatialReference);b=J.getReferenceEllipsoid(b.spatialReference);this.planetRadius=b.radius;this.outerRimWidth=b.outerAtmosphereRimWidth;
this.innerRimFactor=(this.planetRadius+B)/this.planetRadius;this.middleRimFactor=(this.planetRadius+0)/this.planetRadius;this.outerRimFactor=(this.planetRadius+this.outerRimWidth)/this.planetRadius;this.texV0=0/this.outerRimWidth;this.texVScale=this.texV1-this.texV0}var k=l.prototype;k.destroy=function(){this._readyResolver.reject();this._cameraChangeHandle=m.removeMaybe(this._cameraChangeHandle);this._texture=m.disposeMaybe(this._texture);this._fadeVao=m.disposeMaybe(this._fadeVao);this._vao=m.disposeMaybe(this._vao);
this._readyController=m.abortMaybe(this._readyController)};k.when=function(){return this._readyResolver.promise};k.initializeRenderContext=function(b){this._shaderTechniqueRepository=b.shaderTechniqueRep;const c=b.renderContext.rctx;this._cameraChangeHandle=E.init(this.view,"state.camera",()=>b.requestRender(),!0);this._vao=this._createRibbon(c);this._vaoCount=z.vertexCount(this._vao,"geometry");this._fadeVao=S.createQuadVAO(c);this._fadeVaoCount=z.vertexCount(this._fadeVao,"geometry");L.requestImage(this.isOnMars?
M:N,{signal:this._readyController.signal}).then(a=>{this._texture=new U(c,{pixelFormat:6408,dataType:5121,wrapMode:33071,samplingMode:9729,flipped:!0},a);b.requestRender();this._readyController=null;this._readyResolver.resolve()}).catch(a=>{w.isAbortError(a)||W.error("Unable to initialize simple atmosphere: image request failed",a);this._readyResolver.reject(a)})};k.render=function(b){this._update(b.camera);const c=b.rctx;this.atmosphereConeTechnique.bindPipelineState(c);if(1>this._renderData.undergroundFadeAlpha){var a=
this.atmosphereConeTechnique.program;c.useProgram(a);a.setUniformMatrix4fv("proj",b.camera.projectionMatrix);a.setUniformMatrix4fv("view",b.camera.viewMatrix);a.setUniform3fv("silCircleCenter",this._renderData.silCircleCenter);a.setUniform3fv("silCircleV1",this._renderData.silCircleV1);a.setUniform3fv("silCircleV2",this._renderData.silCircleV2);a.setUniform2fv("texV",this._renderData.texV);a.bindTexture(this._texture,"tex");b.scenelightingData.setLightDirectionUniform(a);a.setUniform1f("altitudeFade",
this._renderData.altitudeFade);a.setUniform1f("innerScale",this._renderData.innerScale);c.bindVAO(this._vao);c.drawArrays(4,0,this._vaoCount)}0<this._renderData.undergroundFadeAlpha&&(a=this.atmosphereUndergroundTechnique.program,c.useProgram(a),a.setUniform1f("undergroundFadeAlpha",this._renderData.undergroundFadeAlpha),b.scenelightingData.setLightDirectionUniform(a),a.setUniform3fv("cameraPosition",b.camera.eye),c.bindVAO(this._fadeVao),c.drawArrays(5,0,this._fadeVaoCount));return!0};k.renderHaze=
function(){return!1};k._update=function(b){var c=n.create();const a=this.planetRadius;var g=h.length(b.eye);const d=g-a;this._renderData.undergroundFadeAlpha=0>d?Math.min(-d/5E3,1):0;var f=a+B,e=a+Math.max(50,d);this._renderData.innerScale=e*e/(Math.sqrt(e*e-a*a)*Math.sqrt(e*e-f*f)+a*f)-1;this._renderData.altitudeFade=x.computeInnerAltitudeFade(d);h.scale(c,b.eye,(a+50)/g);A(c,b.center,b.up,a,this._renderData);c=this._computeScreenRimWidth(b,c,b.up,this._renderData);g=X(d);f=this.texV0+.001953125*
this.texVScale;e=this.texV0+c*g*this.texVScale;50<d&&(A(b.eye,b.center,b.up,a,this._renderData),b=this._computeScreenRimWidth(b,b.eye,b.up,this._renderData),b=v.clamp((b-1.5)/(c-1.5),0,1),f=this.texV0+.001953125*b*this.texVScale,e=this.texV0+v.lerp(this.texV1,c*g,b)*this.texVScale);H.set(this._renderData.texV,f,e)};k._createRibbon=function(b){const c=new Float32Array(1155),a=new Uint32Array(1920);c[0]=0;c[1]=0;c[2]=-1;for(var g=0;128>g;g++){var d=9*g+3;c[d+0]=g;c[d+1]=this.innerRimFactor;c[d+2]=-1;
c[d+3]=g;c[d+4]=this.middleRimFactor;c[d+5]=0;c[d+6]=g;c[d+7]=this.outerRimFactor;c[d+8]=1;d=3*g+1;var f=127===g?1:d+3,e=15*g;a[e+0]=d;a[e+1]=d+1;a[e+2]=f+1;a[e+3]=f+1;a[e+4]=f;a[e+5]=d;a[e+6]=d+1;a[e+7]=d+2;a[e+8]=f+2;a[e+9]=f+2;a[e+10]=f+1;a[e+11]=d+1;a[e+12]=d;a[e+13]=f;a[e+14]=0}g=C.createBuffer(a.length);d=g.position;for(f=0;f<a.length;++f)e=3*a[f],d.set(f,0,c[e]),d.set(f,1,c[e+1]),d.set(f,2,c[e+2]);return new V(b,R.Default3D,{geometry:P.glLayout(C)},{geometry:T.createVertex(b,35044,g.buffer)})};
k._computeScreenRimWidth=function(b,c,a,g){h.add(p,g.silCircleCenter,g.silCircleV2);h.scale(t,p,this.outerRimFactor);F.lookAt(u,c,p,a);y.project(p,u,b.projectionMatrix,b.viewport);y.project(t,u,b.projectionMatrix,b.viewport);return h.distance(p,t)/b.height};D._createClass(l,[{key:"atmosphereConeTechnique",get:function(){if(m.isNone(this._atmosphereConeTechnique)){const b=new q.SimpleAtmosphereTechniqueConfiguration;b.geometry=0;this._atmosphereConeTechnique=this._shaderTechniqueRepository.acquire(q.SimpleAtmosphereTechnique,
b)}return this._atmosphereConeTechnique}},{key:"atmosphereUndergroundTechnique",get:function(){if(m.isNone(this._atmosphereUndergroundTechnique)){const b=new q.SimpleAtmosphereTechniqueConfiguration;b.geometry=2;this._atmosphereUndergroundTechnique=this._shaderTechniqueRepository.acquire(q.SimpleAtmosphereTechnique,b)}return this._atmosphereUndergroundTechnique}},{key:"canRender",get:function(){return null!=this._texture}}]);return l}();const u=G.create(),p=n.create(),t=n.create(),C=Q.newLayout().vec3f("position");
return r});