// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../chunks/tslib.es6 ../../../../../../core/maybe ../../../../../../chunks/mat3f64 ../../../../../../chunks/vec4f64 ../../../../../../chunks/ComponentShader.glsl ../../../core/shaderLibrary/Slice.glsl ../../../core/shaderLibrary/attributes/VertexPosition.glsl ../../../core/shaderLibrary/output/OutputHighlight.glsl ../../../core/shaderLibrary/shading/PhysicallyBasedRenderingParameters.glsl ../../../core/shaderLibrary/shading/ScreenSpaceReflections.glsl ../../../core/shaderLibrary/util/DoublePrecision.glsl ../../../core/shaderTechnique/ReloadableShaderModule ../../../core/shaderTechnique/ShaderTechnique ../../../core/shaderTechnique/ShaderTechniqueConfiguration ../../../lib/OrderIndependentTransparency ../../../lib/Program ../../../lib/StencilUtils ../../../../../webgl/renderState".split(" "),
function(y,m,r,g,l,z,A,t,B,u,C,D,E,F,e,n,f,p,G,v,q){n=function(k){function h(){return k.apply(this,arguments)||this}r._inheritsLoose(h,k);var d=h.prototype;d.bindPass=function(a){const c=this.program;u.VertexPosition.bindViewProjTransform(c,a.viewTransform);B.bindSliceUniforms(this.program,this.configuration,a.slicePlane);0===a.identifier&&(void 0!==a.ssrParams&&E.bindSSRUniforms(this.program,a.ssrParams),c.setUniformMatrix3fv("uTransformNormal_ViewFromGlobal",a.transformNormal_ViewFromGlobal),2===
a.subPass&&c.setUniform2fv("cameraNearFar",a.cameraNearFar),0===a.subPass&&a.lighting.setUniforms(this.program,a.integratedMesh));1===a.identifier&&this.program.setUniform2fv("cameraNearFar",a.cameraNearFar)};d.bindMaterial=function(a,c){this._material=a;const b=this.program;b.setUniform4fv("uBaseColor",a.baseColor);b.setUniform1f("uObjectOpacity",a.objectOpacity);b.setUniform1f("textureAlphaCutoff",a.alphaCutoff);1===a.componentParameters.type?a.componentParameters.texture.bind(b,"uComponentColorTex",
"uComponentColorTexInvDim"):(b.setUniform4fv("uExternalColor",a.componentParameters.externalColor),b.setUniform1i("uExternalColorMixMode",a.componentParameters.externalColorMixMode));l.isSome(a.baseColorTexture)&&a.baseColorTexture.bind(b,"uBaseColorTexture","uBaseColorTextureSize");if(0===this.configuration.output||7===this.configuration.output)D.bindPBRUniforms(this.program,a,this.configuration.isSchematic),l.isSome(a.metallicRoughnessTexture)&&a.metallicRoughnessTexture.bind(b,"texMetallicRoughness",
"texMetallicRoughnessSize"),l.isSome(a.emissionTexture)&&a.emissionTexture.bind(b,"texEmission","texEmissionSize"),l.isSome(a.occlusionTexture)&&a.occlusionTexture.bind(b,"texOcclusion","texOcclusionSize"),l.isSome(a.normalTexture)&&a.normalTexture.bind(b,"normalTexture","normalTextureSize");a.isIntegratedMesh&&(0===c.identifier&&0===c.subPass?(b.bindTexture(a.overlayColor,"ovColorTex"),b.bindTexture(a.overlayNormal,"ovNormalTex")):2===c.identifier&&b.bindTexture(a.overlayHighlight,"ovColorTex"),
b.setUniform1f("overlayOpacity",1));2===c.identifier&&C.bindOutputHighlight(this.program,c);0===c.identifier&&0===c.subPass&&(c.ambientOcclusionEnabled&&c.bindAmbientOcclusion(b),c.shadowsEnabled&&c.bindShadowMap(b));0!==c.identifier||0!==c.subPass&&1!==c.subPass||!c.multipassTerrainParams.multipassTerrainEnabled||(this.program.setUniform2fv("cameraNearFar",c.cameraNearFar),b.setUniform2fv("inverseViewport",c.inverseViewport),c.multipassTerrainParams.terrainLinearDepthTexture&&b.bindTexture(c.multipassTerrainParams.terrainLinearDepthTexture,
"terrainDepthTexture"))};d.bindDraw=function(a){u.VertexPosition.bindModelTransform(this.program,a);this.program.setUniformMatrix3fv("uTransformNormal_GlobalFromModel",a.transformNormal_GlobalFromModel);this.program.rebindTextures();if(l.isSome(this._material)&&this._material.isIntegratedMesh){const c=this._material.overlayTexScale,b=this._material.overlayTexOffset;this.program.setUniform4fv("overlayTexOffset",[a.toMapSpace[0]*c[0]+b[0],a.toMapSpace[1]*c[1]+b[1],a.toMapSpace[0]*c[2]+b[2],a.toMapSpace[1]*
c[3]+b[3]]);this.program.setUniform4fv("overlayTexScale",[a.toMapSpace[2]*c[0],a.toMapSpace[3]*c[1],a.toMapSpace[2]*c[2],a.toMapSpace[3]*c[3]])}};d.initializeProgram=function(a){const c=h.shader.get();var b=this.configuration;b=c.build({multipassTerrainEnabled:b.multipassTerrainEnabled,cullAboveGround:b.cullAboveGround,OITEnabled:0===b.transparencyPassType,output:b.output,normalType:0===b.integratedMeshMode?b.hasNormals?1:3:2,attributeColor:b.hasVertexColors,attributeTextureCoordinates:b.vertexTextureCoordinates,
componentData:b.componentData,alphaDiscardMode:b.alphaDiscardMode,baseColorTexture:b.baseColorTexture,doubleSidedMode:b.doubleSidedMode,receiveAmbientOcclusion:b.receiveAmbientOcclusion,receiveShadows:b.receiveShadows,slicePlaneEnabled:b.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,viewingMode:a.viewingMode,vertexDiscardMode:b.vertexDiscardMode,pbrMode:3===b.integratedMeshMode?4:b.usePBR?b.isSchematic?2:1:0,hasMetalnessAndRoughnessTexture:b.hasMetalnessAndRoughnessTexture,
hasEmissionTexture:b.hasEmissionTexture,hasOcclusionTexture:b.hasOcclusionTexture,hasNormalTexture:b.hasNormalTexture,vertexTangents:!1,supportsTextureAtlas:!0,doublePrecisionRequiresObfuscation:F.doublePrecisionRequiresObfuscation(a.rctx),overlayEnabled:2===b.integratedMeshMode||3===b.integratedMeshMode,ssrEnabled:b.ssrEnabled,highStepCount:!1,ellipsoidMode:b.ellipsoidMode});return new G.Program(a.rctx,b,c.attributeLocations)};d.setPipelineState=function(a){const c=this.configuration,b=0!==c.integratedMeshMode,
w=3===a,x=2===a;return q.makePipelineState({blending:0!==c.output&&7!==c.output||!c.blendingEnabled?null:w?p.blendingDefault:p.OITBlending(a),culling:q.cullingParams(c.cullFace),depthTest:{func:p.OITDepthTest(a)},depthWrite:w||x?q.defaultDepthWriteParams:null,colorWrite:q.defaultColorWriteParams,stencilWrite:b||c.sceneHasOcludees?v.stencilWriteMaskOn:null,stencilTest:b?v.replaceBitWhenDepthTestPasses(1):c.sceneHasOcludees?v.stencilBaseAllZerosParams:null,polygonOffset:w||x?c.polygonOffsetEnabled?
{factor:2,units:2}:null:p.OITPolygonOffset})};d.initializePipeline=function(){return this.setPipelineState(this.configuration.transparencyPassType)};return h}(n.ShaderTechnique);n.shader=new e.ReloadableShaderModule(t.ComponentShader,()=>new Promise((k,h)=>y(["./shader/ComponentShader.glsl"],k,h)));t=function(k){function h(){var d=k.apply(this,arguments)||this;d.transformNormal_GlobalFromModel=z.create();d.toMapSpace=A.create();return d}r._inheritsLoose(h,k);return h}(u.VertexPosition.ModelTransform);
e=function(k){function h(){var d=k.apply(this,arguments)||this;d.output=0;d.hasVertexColors=!1;d.hasNormals=!1;d.vertexTextureCoordinates=0;d.componentData=0;d.slicePlaneEnabled=!1;d.cullFace=2;d.baseColorTexture=!1;d.receiveAmbientOcclusion=!0;d.receiveShadows=!0;d.vertexDiscardMode=0;d.doubleSidedMode=2;d.blendingEnabled=!0;d.alphaDiscardMode=1;d.integratedMeshMode=0;d.ssrEnabled=!1;d.polygonOffsetEnabled=!1;d.usePBR=!1;d.isSchematic=!1;d.hasMetalnessAndRoughnessTexture=!1;d.hasEmissionTexture=
!1;d.hasOcclusionTexture=!1;d.hasNormalTexture=!1;d.sceneHasOcludees=!1;d.transparencyPassType=3;d.ellipsoidMode=1;d.multipassTerrainEnabled=!1;d.cullAboveGround=!1;return d}r._inheritsLoose(h,k);return h}(f.ShaderTechniqueConfiguration);g.__decorate([f.parameter({count:8})],e.prototype,"output",void 0);g.__decorate([f.parameter()],e.prototype,"hasVertexColors",void 0);g.__decorate([f.parameter()],e.prototype,"hasNormals",void 0);g.__decorate([f.parameter({count:3})],e.prototype,"vertexTextureCoordinates",
void 0);g.__decorate([f.parameter({count:2})],e.prototype,"componentData",void 0);g.__decorate([f.parameter()],e.prototype,"slicePlaneEnabled",void 0);g.__decorate([f.parameter({count:3})],e.prototype,"cullFace",void 0);g.__decorate([f.parameter()],e.prototype,"baseColorTexture",void 0);g.__decorate([f.parameter()],e.prototype,"receiveAmbientOcclusion",void 0);g.__decorate([f.parameter()],e.prototype,"receiveShadows",void 0);g.__decorate([f.parameter({count:3})],e.prototype,"vertexDiscardMode",void 0);
g.__decorate([f.parameter({count:3})],e.prototype,"doubleSidedMode",void 0);g.__decorate([f.parameter()],e.prototype,"blendingEnabled",void 0);g.__decorate([f.parameter({count:4})],e.prototype,"alphaDiscardMode",void 0);g.__decorate([f.parameter({count:4})],e.prototype,"integratedMeshMode",void 0);g.__decorate([f.parameter()],e.prototype,"ssrEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"polygonOffsetEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"usePBR",void 0);g.__decorate([f.parameter()],
e.prototype,"isSchematic",void 0);g.__decorate([f.parameter()],e.prototype,"hasMetalnessAndRoughnessTexture",void 0);g.__decorate([f.parameter()],e.prototype,"hasEmissionTexture",void 0);g.__decorate([f.parameter()],e.prototype,"hasOcclusionTexture",void 0);g.__decorate([f.parameter()],e.prototype,"hasNormalTexture",void 0);g.__decorate([f.parameter()],e.prototype,"sceneHasOcludees",void 0);g.__decorate([f.parameter({count:4})],e.prototype,"transparencyPassType",void 0);g.__decorate([f.parameter({count:4})],
e.prototype,"ellipsoidMode",void 0);g.__decorate([f.parameter()],e.prototype,"multipassTerrainEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"cullAboveGround",void 0);m.ComponentDrawParameters=t;m.ComponentTechnique=n;m.ComponentTechniqueConfiguration=e;Object.defineProperty(m,"__esModule",{value:!0})});