// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../arcade/FunctionWrapper ../arcade/ImmutableArray ../arcade/ImmutablePathArray ../arcade/ImmutablePointArray ../core/promiseUtils ../geometry/Extent ../geometry/Geometry ../geometry/Multipoint ../geometry/Point ../geometry/Polygon ../geometry/Polyline ./datetime ../core/maybe ../core/number ../geometry/support/coordsUtils ../intl/locale".split(" "),function(f,Ka,x,La,H,E,X,A,Y,I,Z,aa,J,Ma,ba,Na,Oa){function B(a,b,c){return""===b||null===b||void 0===b||b===c||b===c?a:a=a.split(b).join(c)}
function K(a){return a instanceof L||a instanceof Ka||a instanceof M}function F(a){return m(a)||p(a)||n(a)||q(a)||null===a||a===t||"number"===typeof a?!0:!1}function ca(a,b){return void 0===a?b:a}function m(a){return"string"===typeof a||a instanceof String}function q(a){return"boolean"===typeof a}function p(a){return"number"===typeof a}function da(a){return"number"===typeof a&&isFinite(a)&&Math.floor(a)===a}function u(a){return a instanceof Array}function ea(a){return!0===(a&&a.declaredRootClass&&
"esri.arcade.featureset.support.FeatureSet"===a.declaredRootClass)}function fa(a){return!0===(a&&a.declaredRootClass&&"esri.arcade.featureSetCollection"===a.declaredRootClass)}function y(a){return a instanceof x}function n(a){return a instanceof Date}function ha(a,b,c){if(a.length<b||a.length>c)throw Error("Function called with wrong number of Parameters");}function ia(a){return 0>a?-Math.round(-a):Math.round(a)}function ja(){let a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(b){const c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"===b?c:c&3|8).toString(16)})}function N(a,b){if(!1===isNaN(a)){if(void 0===b||null===b||""===b)return a.toString();b=B(b,"\u2030","");b=B(b,"\u00a4","");return ba.format(a,{pattern:b})}return a.toString()}function G(a,b){a=J.DateTime.fromJSDate(a);return void 0===b||null===b||""===b?a.toISO({suppressMilliseconds:!0}):a.toFormat(S(b),{locale:Oa.getLocale(),numberingSystem:"latn"})}function S(a){a=a.replace(/LTS|LT|LL?L?L?|l{1,4}/g,
"[$\x26]");let b="";const c=/(\[[^\[]*\])|(\\)?([Hh]mm(ss)?|Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|Qo?|N{1,5}|YYYYYY|YYYYY|YYYY|YY|y{2,4}|yo?|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|kk?|mm?|ss?|S{1,9}|x|X|zz?|ZZ?|.)/g;for(const e of a.match(c))switch(e){case "D":b+="d";break;case "DD":b+="dd";break;case "DDD":b+="o";break;case "d":b+="c";break;case "ddd":b+="ccc";break;case "dddd":b+="cccc";break;case "M":b+="L";break;case "MM":b+="LL";break;case "MMM":b+="LLL";break;case "MMMM":b+="LLLL";
break;case "YY":b+="yy";break;case "Y":case "YYYY":b+="yyyy";break;case "Q":b+="q";break;case "Z":b+="ZZ";break;case "ZZ":b+="ZZZ";break;case "S":b+="'S'";break;case "SS":b+="'SS'";break;case "SSS":b+="u";break;case "A":case "a":b+="a";break;case "m":case "mm":case "h":case "hh":case "H":case "HH":case "s":case "ss":case "X":case "x":b+=e;break;default:b=2<=e.length&&"["===e.slice(0,1)&&"]"===e.slice(-1)?b+`'${e.slice(1,-1)}'`:b+`'${e}'`}return b}function h(a,b,c){switch(c){case "\x3e":return a>b;
case "\x3c":return a<b;case "\x3e\x3d":return a>=b;case "\x3c\x3d":return a<=b}return!1}function ka(a,b,c){if(null===a){if(null===b||b===t)return h(null,null,c);if(p(b))return h(0,b,c);if(m(b)||q(b))return h(0,l(b),c);if(n(b))return h(0,b.getTime(),c)}if(a===t){if(null===b||b===t)return h(null,null,c);if(p(b))return h(0,b,c);if(m(b)||q(b))return h(0,l(b),c);if(n(b))return h(0,b.getTime(),c)}else if(p(a)){if(p(b))return h(a,b,c);if(q(b))return h(a,l(b),c);if(null===b||b===t)return h(a,0,c);if(m(b))return h(a,
l(b),c);if(n(b))return h(a,b.getTime(),c)}else if(m(a)){if(m(b))return h(w(a),w(b),c);if(n(b))return h(l(a),b.getTime(),c);if(p(b))return h(l(a),b,c);if(null===b||b===t)return h(l(a),0,c);if(q(b))return h(l(a),l(b),c)}else if(n(a)){if(n(b))return h(a,b,c);if(null===b||b===t)return h(a.getTime(),0,c);if(p(b))return h(a.getTime(),b,c);if(q(b)||m(b))return h(a.getTime(),l(b),c)}else if(q(a)){if(q(b))return h(a,b,c);if(p(b))return h(l(a),l(b),c);if(n(b))return h(l(a),b.getTime(),c);if(null===b||b===t)return h(l(a),
0,c);if(m(b))return h(l(a),l(b),c)}return!T(a,b)||"\x3c\x3d"!==c&&"\x3e\x3d"!==c?!1:!0}function T(a,b){if(a===b||null===a&&b===t||null===b&&a===t)return!0;if(n(a)&&n(b))return a.getTime()===b.getTime();if(a instanceof La||a instanceof H)return a.equalityTest(b);if(a instanceof I&&b instanceof I){const c=a.cache._arcadeCacheId,e=b.cache._arcadeCacheId;if(void 0!==c&&null!==c)return c===e}return void 0!==a&&void 0!==b&&null!==a&&null!==b&&"object"===typeof a&&"object"===typeof b&&(a._arcadeCacheId===
b._arcadeCacheId&&void 0!==a._arcadeCacheId&&null!==a._arcadeCacheId||a._underlyingGraphic===b._underlyingGraphic&&void 0!==a._underlyingGraphic&&null!==a._underlyingGraphic)?!0:!1}function w(a,b){if(m(a))return a;if(null===a)return"";if(p(a))return N(a,b);if(q(a))return a.toString();if(n(a))return G(a,b);if(a instanceof A)return JSON.stringify(a.toJSON());if(u(a)){b=[];for(var c=0;c<a.length;c++)b[c]=O(a[c]);return"["+b.join(",")+"]"}if(a instanceof x){b=[];for(c=0;c<a.length();c++)b[c]=O(a.get(c));
return"["+b.join(",")+"]"}return null!==a&&"object"===typeof a&&void 0!==a.castToText?a.castToText():K(a)?"object, Function":""}function la(a){const b=[];if(!1===u(a))return null;if(a instanceof x){for(var c=0;c<a.length();c++)b[c]=l(a.get(c));return b}for(c=0;c<a.length;c++)b[c]=l(a[c]);return b}function U(a,b){if(m(a))return a;if(null===a)return"";if(p(a))return N(a,b);if(q(a))return a.toString();if(n(a))return G(a,b);if(a instanceof A)return a instanceof X?'{"xmin":'+a.xmin.toString()+',"ymin":'+
a.ymin.toString()+","+(a.hasZ?'"zmin":'+a.zmin.toString()+",":"")+(a.hasM?'"mmin":'+a.mmin.toString()+",":"")+'"xmax":'+a.xmax.toString()+',"ymax":'+a.ymax.toString()+","+(a.hasZ?'"zmax":'+a.zmax.toString()+",":"")+(a.hasM?'"mmax":'+a.mmax.toString()+",":"")+'"spatialReference":'+P(a.spatialReference)+"}":P(a.toJSON(),(e,d)=>e.key===d.key?0:"spatialReference"===e.key?1:"spatialReference"===d.key||e.key<d.key?-1:e.key>d.key?1:0);if(u(a)){b=[];for(var c=0;c<a.length;c++)b[c]=O(a[c]);return"["+b.join(",")+
"]"}if(a instanceof x){b=[];for(c=0;c<a.length();c++)b[c]=O(a.get(c));return"["+b.join(",")+"]"}return null!==a&&"object"===typeof a&&void 0!==a.castToText?a.castToText():K(a)?"object, Function":""}function O(a){return null===a?"null":q(a)||p(a)||m(a)?JSON.stringify(a):a instanceof A||a instanceof x||a instanceof Array?U(a):a instanceof Date?JSON.stringify(G(a,"")):null!==a&&"object"===typeof a&&void 0!==a.castToText?a.castToText():"null"}function l(a,b){return p(a)?a:null===a||""===a?0:n(a)?NaN:
q(a)?a?1:0:u(a)||""===a||void 0===a?NaN:void 0!==b&&m(a)?(b=B(b,"\u2030",""),b=B(b,"\u00a4",""),ba.parse(a,{pattern:b})):a===t?0:Number(a)}function ma(a){return n(a)?a:m(a)&&(a=na(a))?a.toJSDate():null}function oa(a){return n(a)?J.DateTime.fromJSDate(a):m(a)?na(a):null}function na(a){const b=/ (\d\d)/;let c=J.DateTime.fromISO(a);return c.isValid||b.test(a)&&(a=a.replace(b,"T$1"),c=J.DateTime.fromISO(a),c.isValid)?c:null}function pa(a){return q(a)?a:m(a)?(a=a.toLowerCase(),"true"===a?!0:!1):p(a)?0===
a||isNaN(a)?!1:!0:!1}function qa(a,b){if(Ma.isNone(a))return null;if(null===a.spatialReference||void 0===a.spatialReference)a.spatialReference=b;return a}function ra(a){if(null===a)return null;if(a instanceof I)return"NaN"===a.x||null===a.x||isNaN(a.x)?null:a;if(a instanceof Z){if(0===a.rings.length)return null;for(const b of a.rings)if(0<b.length)return a;return null}if(a instanceof aa){if(0===a.paths.length)return null;for(const b of a.paths)if(0<b.length)return a;return null}return a instanceof
Y?0===a.points.length?null:a:a instanceof X?"NaN"===a.xmin||null===a.xmin||isNaN(a.xmin)?null:a:null}function sa(a,b){if(!a||!a.domain)return b;let c=null;if("string"===a.field.type||"esriFieldTypeString"===a.field.type)b=w(b);else{if(null===b||void 0===b)return null;if(""===b)return b;b=l(b)}for(let e=0;e<a.domain.codedValues.length;e++){const d=a.domain.codedValues[e];d.code===b&&(c=d)}return null===c?b:c.name}function ta(a,b){if(!a||!a.domain)return b;let c=null;b=w(b);for(let e=0;e<a.domain.codedValues.length;e++){const d=
a.domain.codedValues[e];d.name===b&&(c=d)}return null===c?b:c.code}function ua(a,b,c=null,e){if(!b||!b.fields)return null;let d=null;for(let v=0;v<b.fields.length;v++){const r=b.fields[v];r.name.toLowerCase()===a.toString().toLowerCase()&&(d=r)}if(null===d)throw Error("Field not found");let g,k;e||(e=c&&b.typeIdField&&c._field(b.typeIdField));null!=e&&b.types.some(function(v){return v.id===e?((g=v.domains&&v.domains[d.name])&&"inherited"===g.type&&(g=va(d.name,b),k=!0),!0):!1});k||g||(g=va(a,b));
return{field:d,domain:g}}function va(a,b){let c;b.fields.some(function(e){e.name.toLowerCase()===a.toLowerCase()&&(c=e.domain);return!!c});return c}function P(a,b){b||(b={});"function"===typeof b&&(b={cmp:b});const c="boolean"===typeof b.cycles?b.cycles:!1,e=b.cmp&&function(g){return function(k){return function(v,r){return g({key:v,value:k[v]},{key:r,value:k[r]})}}}(b.cmp),d=[];return function v(k){k&&k.toJSON&&"function"===typeof k.toJSON&&(k=k.toJSON());if(void 0!==k){if("number"===typeof k)return isFinite(k)?
""+k:"null";if("object"!==typeof k)return JSON.stringify(k);var r;if(Array.isArray(k)){var z="[";for(r=0;r<k.length;r++)r&&(z+=","),z+=v(k[r])||"null";return z+"]"}if(null===k)return"null";if(-1!==d.indexOf(k)){if(c)return JSON.stringify("__cycle__");throw new TypeError("Converting circular structure to JSON");}var Pa=d.push(k)-1,wa=Object.keys(k).sort(e&&e(k));z="";for(r=0;r<wa.length;r++){const xa=wa[r],ya=v(k[xa]);ya&&(z&&(z+=","),z+=JSON.stringify(xa)+":"+ya)}d.splice(Pa,1);return"{"+z+"}"}}(a)}
function za(a){if(null===a)return null;const b=[];for(const c of a)c&&(c.declaredClass&&"esri.arcade.Feature"===c.declaredClass||"FeatureSetReader"===c.type)?b.push(c.geometry()):b.push(c);return b}function C(a,b){if(b instanceof I)a.push(b.hasZ?b.hasM?[b.x,b.y,b.z,b.m]:[b.x,b.y,b.z]:[b.x,b.y]);else throw Error("Invalid Argument");}function Aa(a,b){if(u(a)||y(a)){let c=!1,e=!1,d=[];if(u(a)){for(const g of a)C(d,g);0<d.length&&(b=a[0].spatialReference,c=a[0].hasZ,e=a[0].hasM)}else if(a instanceof H)d=
a._elements,0<d.length&&(c=a._hasZ,e=a._hasM,b=a.get(0).spatialReference);else if(y(a)){for(const g of a.toArray())C(d,g);0<d.length&&(b=a.get(0).spatialReference,c=!0===a.get(0).hasZ,e=!0===a.get(0).hasM)}else throw Error("Invalid Argument");if(0===d.length)return null;!1===Na.isClockwise(d,e,c)&&(d=d.slice(0).reverse());return new Z({rings:[d],spatialReference:b,hasZ:c,hasM:e})}return a}function Ba(a,b){if(u(a)||y(a)){let c=!1,e=!1,d=[];if(u(a)){for(const g of a)C(d,g);0<d.length&&(b=a[0].spatialReference,
c=!0===a[0].hasZ,e=!0===a[0].hasM)}else if(a instanceof H)d=a._elements,0<d.length&&(c=a._hasZ,e=a._hasM,b=a.get(0).spatialReference);else if(y(a)){for(const g of a.toArray())C(d,g);0<d.length&&(b=a.get(0).spatialReference,c=!0===a.get(0).hasZ,e=!0===a.get(0).hasM)}return 0===d.length?null:new aa({paths:[d],spatialReference:b,hasZ:c,hasM:e})}return a}function Ca(a,b){if(u(a)||y(a)){let c=!1,e=!1,d=[];if(u(a)){for(const g of a)C(d,g);0<d.length&&(b=a[0].spatialReference,c=!0===a[0].hasZ,e=!0===a[0].hasM)}else if(a instanceof
H)d=a._elements,0<d.length&&(c=a._hasZ,e=a._hasM,b=a.get(0).spatialReference);else if(y(a)){for(const g of a.toArray())C(d,g);0<d.length&&(b=a.get(0).spatialReference,c=!0===a.get(0).hasZ,e=!0===a.get(0).hasM)}return 0===d.length?null:new Y({points:d,spatialReference:b,hasZ:c,hasM:e})}return a}function Da(a,b=!1){const c=[];if(null===a)return c;if(!0===u(a)){for(var e=0;e<a.length;e++){var d=w(a[e]);""===d&&!0!==b||c.push(d)}return c}if(a instanceof x){for(e=0;e<a.length();e++)d=w(a.get(e)),""===
d&&!0!==b||c.push(d);return c}return F(a)?(a=w(a),""===a&&!0!==b||c.push(a),c):[]}function Ea(a){V++;return 0===V%100?(V=0,E.create(b=>{setTimeout(()=>{b(a)},0)})):a}function Fa(a,b,c){switch(c){case "\x26":return a&b;case "|":return a|b;case "^":return a^b;case "\x3c\x3c":return a<<b;case "\x3e\x3e":return a>>b;case "\x3e\x3e\x3e":return a>>>b}}function D(a,b=null){if(null!=a){if(q(a)||p(a)||m(a))return a;if(a instanceof A)return!0===(null==b?void 0:b.keepGeometryType)?a:a.toJSON();if(a instanceof
x)return a.toArray().map(c=>D(c,b));if(a instanceof Array)return a.map(c=>D(c,b));if(a instanceof Date)return a;if(null!==a&&"object"===typeof a&&void 0!==a.castAsJson)return a.castAsJson(b)}return null}function Qa(a,b,c,e,d){return W(a,b,c).then(g=>{d[e]=g})}function W(a,b=null,c=null){a instanceof x&&(a=a.toArray());if(null!=a){if(F(a)||a instanceof A||a instanceof Date)return E.resolve(D(a,c));if(a instanceof Array){const e=[],d=[];for(const g of a)null===g||F(g)||g instanceof A||g instanceof Date?
d.push(D(g,c)):(d.push(null),e.push(Qa(g,b,c,d.length-1,d)));return 0<e.length?E.all(e).then(()=>d):E.resolve(d)}if(null!==a&&"object"===typeof a&&void 0!==a.castAsJsonAsync)return a.castAsJsonAsync(b,c)}return E.resolve(null)}let Q=function(a){this.value=a},R=function(a){this.value=a},L=function(a){this.fn=a},M=function(a,b){this.paramCount=b;this.fn=a};const Ga=L,Ha=M,t={type:"VOID"},Ia={type:"BREAK"},Ja={type:"CONTINUE"};let V=0;const Ra=Object.freeze({__proto__:null,ReturnResultE:Q,ImplicitResultE:R,
NativeFunctionE:L,SizzleFunctionE:M,NativeFunction:Ga,ImplicitResult:R,ReturnResult:Q,SizzleFunction:Ha,voidOperation:t,breakResult:Ia,continueResult:Ja,multiReplace:B,isFunctionParameter:K,isSimpleType:F,defaultUndefined:ca,isString:m,isBoolean:q,isNumber:p,isInteger:da,isArray:u,isFeatureSet:ea,isFeatureSetCollection:fa,isImmutableArray:y,isDate:n,pcCheck:ha,absRound:ia,generateUUID:ja,formatNumber:N,formatDate:G,standardiseDateFormat:S,greaterThanLessThan:ka,equalityTest:T,toString:w,toNumberArray:la,
toStringExplicit:U,toNumber:l,toDate:ma,toDateTime:oa,toBoolean:pa,fixSpatialReference:qa,fixNullGeometry:ra,getDomainValue:sa,getDomainCode:ta,getDomain:ua,stableStringify:P,autoCastFeatureToGeometry:za,autoCastArrayOfPointsToPolygon:Aa,autoCastArrayOfPointsToPolyline:Ba,autoCastArrayOfPointsToMultiPoint:Ca,toStringArray:Da,tick:Ea,binaryOperator:Fa,castAsJson:D,castAsJsonAsync:W});f.ImplicitResult=R;f.ImplicitResultE=R;f.NativeFunction=Ga;f.NativeFunctionE=L;f.ReturnResult=Q;f.ReturnResultE=Q;f.SizzleFunction=
Ha;f.SizzleFunctionE=M;f.absRound=ia;f.autoCastArrayOfPointsToMultiPoint=Ca;f.autoCastArrayOfPointsToPolygon=Aa;f.autoCastArrayOfPointsToPolyline=Ba;f.autoCastFeatureToGeometry=za;f.binaryOperator=Fa;f.breakResult=Ia;f.castAsJson=D;f.castAsJsonAsync=W;f.continueResult=Ja;f.defaultUndefined=ca;f.equalityTest=T;f.fixNullGeometry=ra;f.fixSpatialReference=qa;f.formatDate=G;f.formatNumber=N;f.generateUUID=ja;f.getDomain=ua;f.getDomainCode=ta;f.getDomainValue=sa;f.greaterThanLessThan=ka;f.isArray=u;f.isBoolean=
q;f.isDate=n;f.isFeatureSet=ea;f.isFeatureSetCollection=fa;f.isFunctionParameter=K;f.isImmutableArray=y;f.isInteger=da;f.isNumber=p;f.isSimpleType=F;f.isString=m;f.lc=Ra;f.multiReplace=B;f.pcCheck=ha;f.stableStringify=P;f.standardiseDateFormat=S;f.tick=Ea;f.toBoolean=pa;f.toDate=ma;f.toDateTime=oa;f.toNumber=l;f.toNumberArray=la;f.toString=w;f.toStringArray=Da;f.toStringExplicit=U;f.voidOperation=t});