// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","./dom"],function(S,wa){function B(a){return a?(a.nodeName||"").toLowerCase():null}function y(a){return null==a?window:"[object Window]"!==a.toString()?(a=a.ownerDocument)?a.defaultView||window:window:a}function N(a){var b=y(a).Element;return a instanceof b||a instanceof Element}function w(a){var b=y(a).HTMLElement;return a instanceof b||a instanceof HTMLElement}function ea(a){if("undefined"===typeof ShadowRoot)return!1;var b=y(a).ShadowRoot;return a instanceof b||a instanceof ShadowRoot}
function C(a){return a.split("-")[0]}function K(a,b){a=a.getBoundingClientRect();return{width:a.width/1,height:a.height/1,top:a.top/1,right:a.right/1,bottom:a.bottom/1,left:a.left/1,x:a.left/1,y:a.top/1}}function X(a){var b=K(a),c=a.offsetWidth,d=a.offsetHeight;1>=Math.abs(b.width-c)&&(c=b.width);1>=Math.abs(b.height-d)&&(d=b.height);return{x:a.offsetLeft,y:a.offsetTop,width:c,height:d}}function fa(a,b){var c=b.getRootNode&&b.getRootNode();if(a.contains(b))return!0;if(c&&ea(c)){do{if(b&&a.isSameNode(b))return!0;
b=b.parentNode||b.host}while(b)}return!1}function E(a){return y(a).getComputedStyle(a)}function F(a){return((N(a)?a.ownerDocument:a.document)||window.document).documentElement}function T(a){return"html"===B(a)?a:a.assignedSlot||a.parentNode||(ea(a)?a.host:null)||F(a)}function ha(a){return w(a)&&"fixed"!==E(a).position?a.offsetParent:null}function O(a){for(var b=y(a),c=ha(a);c&&0<=["table","td","th"].indexOf(B(c))&&"static"===E(c).position;)c=ha(c);if(c&&("html"===B(c)||"body"===B(c)&&"static"===E(c).position))return b;
if(!c)a:{c=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");if(-1===navigator.userAgent.indexOf("Trident")||!w(a)||"fixed"!==E(a).position)for(a=T(a);w(a)&&0>["html","body"].indexOf(B(a));){var d=E(a);if("none"!==d.transform||"none"!==d.perspective||"paint"===d.contain||-1!==["transform","perspective"].indexOf(d.willChange)||c&&"filter"===d.willChange||c&&d.filter&&"none"!==d.filter){c=a;break a}else a=a.parentNode}c=null}return c||b}function Y(a){return 0<=["top","bottom"].indexOf(a)?"x":
"y"}function ia(a){return Object.assign({},{top:0,right:0,bottom:0,left:0},a)}function ja(a,b){return b.reduce(function(c,d){c[d]=a;return c},{})}function L(a){return a.split("-")[1]}function ka(a){var b,c=a.popper,d=a.popperRect,e=a.placement,f=a.variation,g=a.offsets,l=a.position,p=a.gpuAcceleration,m=a.adaptive;a=a.roundOffsets;if(!0===a){a=g.y;var h=window.devicePixelRatio||1;a={x:U(U(g.x*h)/h)||0,y:U(U(a*h)/h)||0}}else a="function"===typeof a?a(g):g;h=a;a=h.x;a=void 0===a?0:a;h=h.y;h=void 0===
h?0:h;var n=g.hasOwnProperty("x");g=g.hasOwnProperty("y");var r="left",k="top",t=window;if(m){var q=O(c),v="clientHeight",u="clientWidth";q===y(c)&&(q=F(c),"static"!==E(q).position&&"absolute"===l&&(v="scrollHeight",u="scrollWidth"));if("top"===e||("left"===e||"right"===e)&&"end"===f)k="bottom",h-=q[v]-d.height,h*=p?1:-1;if("left"===e||("top"===e||"bottom"===e)&&"end"===f)r="right",a-=q[u]-d.width,a*=p?1:-1}c=Object.assign({position:l},m&&xa);if(p){var z;return Object.assign({},c,(z={},z[k]=g?"0":
"",z[r]=n?"0":"",z.transform=1>=(t.devicePixelRatio||1)?"translate("+a+"px, "+h+"px)":"translate3d("+a+"px, "+h+"px, 0)",z))}return Object.assign({},c,(b={},b[k]=g?h+"px":"",b[r]=n?a+"px":"",b.transform="",b))}function V(a){return a.replace(/left|right|bottom|top/g,function(b){return ya[b]})}function la(a){return a.replace(/start|end/g,function(b){return za[b]})}function Z(a){a=y(a);return{scrollLeft:a.pageXOffset,scrollTop:a.pageYOffset}}function aa(a){return K(F(a)).left+Z(a).scrollLeft}function ba(a){a=
E(a);return/auto|scroll|overlay|hidden/.test(a.overflow+a.overflowY+a.overflowX)}function ma(a){return 0<=["html","body","#document"].indexOf(B(a))?a.ownerDocument.body:w(a)&&ba(a)?a:ma(T(a))}function P(a,b){var c;void 0===b&&(b=[]);var d=ma(a);a=d===(null==(c=a.ownerDocument)?void 0:c.body);c=y(d);d=a?[c].concat(c.visualViewport||[],ba(d)?d:[]):d;b=b.concat(d);return a?b:b.concat(P(T(d)))}function ca(a){return Object.assign({},a,{left:a.x,top:a.y,right:a.x+a.width,bottom:a.y+a.height})}function na(a,
b){if("viewport"===b){b=y(a);var c=F(a);b=b.visualViewport;var d=c.clientWidth;c=c.clientHeight;var e=0,f=0;b&&(d=b.width,c=b.height,/^((?!chrome|android).)*safari/i.test(navigator.userAgent)||(e=b.offsetLeft,f=b.offsetTop));a={width:d,height:c,x:e+aa(a),y:f};a=ca(a)}else w(b)?(a=K(b),a.top+=b.clientTop,a.left+=b.clientLeft,a.bottom=a.top+b.clientHeight,a.right=a.left+b.clientWidth,a.width=b.clientWidth,a.height=b.clientHeight,a.x=a.left,a.y=a.top):(f=F(a),a=F(f),d=Z(f),b=null==(c=f.ownerDocument)?
void 0:c.body,c=A(a.scrollWidth,a.clientWidth,b?b.scrollWidth:0,b?b.clientWidth:0),e=A(a.scrollHeight,a.clientHeight,b?b.scrollHeight:0,b?b.clientHeight:0),f=-d.scrollLeft+aa(f),d=-d.scrollTop,"rtl"===E(b||a).direction&&(f+=A(a.clientWidth,b?b.clientWidth:0)-c),a=ca({width:c,height:e,x:f,y:d}));return a}function Aa(a){var b=P(T(a)),c=0<=["absolute","fixed"].indexOf(E(a).position)&&w(a)?O(a):a;return N(c)?b.filter(function(d){return N(d)&&fa(d,c)&&"body"!==B(d)}):[]}function Ba(a,b,c){b="clippingParents"===
b?Aa(a):[].concat(b);c=[].concat(b,[c]);c=c.reduce(function(d,e){e=na(a,e);d.top=A(e.top,d.top);d.right=G(e.right,d.right);d.bottom=G(e.bottom,d.bottom);d.left=A(e.left,d.left);return d},na(a,c[0]));c.width=c.right-c.left;c.height=c.bottom-c.top;c.x=c.left;c.y=c.top;return c}function oa(a){var b=a.reference,c=a.element,d=(a=a.placement)?C(a):null;a=a?L(a):null;var e=b.x+b.width/2-c.width/2,f=b.y+b.height/2-c.height/2;switch(d){case "top":e={x:e,y:b.y-c.height};break;case "bottom":e={x:e,y:b.y+b.height};
break;case "right":e={x:b.x+b.width,y:f};break;case "left":e={x:b.x-c.width,y:f};break;default:e={x:b.x,y:b.y}}d=d?Y(d):null;if(null!=d)switch(f="y"===d?"height":"width",a){case "start":e[d]-=b[f]/2-c[f]/2;break;case "end":e[d]+=b[f]/2-c[f]/2}return e}function Q(a,b){void 0===b&&(b={});var c=b;b=c.placement;b=void 0===b?a.placement:b;var d=c.boundary,e=void 0===d?"clippingParents":d;d=c.rootBoundary;var f=void 0===d?"viewport":d;d=c.elementContext;d=void 0===d?"popper":d;var g=c.altBoundary,l=void 0===
g?!1:g;c=c.padding;c=void 0===c?0:c;c=ia("number"!==typeof c?c:ja(c,R));g=a.rects.popper;l=a.elements[l?"popper"===d?"reference":"popper":d];e=Ba(N(l)?l:l.contextElement||F(a.elements.popper),e,f);f=K(a.elements.reference);l=oa({reference:f,element:g,strategy:"absolute",placement:b});g=ca(Object.assign({},g,l));f="popper"===d?g:f;var p={top:e.top-f.top+c.top,bottom:f.bottom-e.bottom+c.bottom,left:e.left-f.left+c.left,right:f.right-e.right+c.right};a=a.modifiersData.offset;if("popper"===d&&a){var m=
a[b];Object.keys(p).forEach(function(h){var n=0<=["right","bottom"].indexOf(h)?1:-1,r=0<=["top","bottom"].indexOf(h)?"y":"x";p[h]+=m[r]*n})}return p}function Ca(a,b){void 0===b&&(b={});var c=b.boundary,d=b.rootBoundary,e=b.padding,f=b.flipVariations,g=b.allowedAutoPlacements,l=void 0===g?pa:g,p=L(b.placement);b=p?f?qa:qa.filter(function(h){return L(h)===p}):R;f=b.filter(function(h){return 0<=l.indexOf(h)});0===f.length&&(f=b);var m=f.reduce(function(h,n){h[n]=Q(a,{placement:n,boundary:c,rootBoundary:d,
padding:e})[C(n)];return h},{});return Object.keys(m).sort(function(h,n){return m[h]-m[n]})}function Da(a){if("auto"===C(a))return[];var b=V(a);return[la(a),b,la(b)]}function ra(a,b,c){void 0===c&&(c={x:0,y:0});return{top:a.top-b.height-c.y,right:a.right-b.width+c.x,bottom:a.bottom-b.height+c.y,left:a.left-b.width-c.x}}function sa(a){return["top","right","bottom","left"].some(function(b){return 0<=a[b]})}function Ea(a,b,c){void 0===c&&(c=!1);var d=w(b);w(b)&&b.getBoundingClientRect();var e=F(b);a=
K(a);var f={scrollLeft:0,scrollTop:0},g={x:0,y:0};if(d||!d&&!c){if("body"!==B(b)||ba(e))f=b!==y(b)&&w(b)?{scrollLeft:b.scrollLeft,scrollTop:b.scrollTop}:Z(b);w(b)?(g=K(b),g.x+=b.clientLeft,g.y+=b.clientTop):e&&(g.x=aa(e))}return{x:a.left+f.scrollLeft-g.x,y:a.top+f.scrollTop-g.y,width:a.width,height:a.height}}function Fa(a){function b(f){d.add(f.name);[].concat(f.requires||[],f.requiresIfExists||[]).forEach(function(g){d.has(g)||(g=c.get(g))&&b(g)});e.push(f)}var c=new Map,d=new Set,e=[];a.forEach(function(f){c.set(f.name,
f)});a.forEach(function(f){d.has(f.name)||b(f)});return e}function Ga(a){var b=Fa(a);return Ha.reduce(function(c,d){return c.concat(b.filter(function(e){return e.phase===d}))},[])}function Ia(a){var b;return function(){b||(b=new Promise(function(c){Promise.resolve().then(function(){b=void 0;c(a())})}));return b}}function Ja(a){var b=a.reduce(function(c,d){var e=c[d.name];c[d.name]=e?Object.assign({},e,d,{options:Object.assign({},e.options,d.options),data:Object.assign({},e.data,d.data)}):d;return c},
{});return Object.keys(b).map(function(c){return b[c]})}function ta(){for(var a=arguments.length,b=Array(a),c=0;c<a;c++)b[c]=arguments[c];return!b.some(function(d){return!(d&&"function"===typeof d.getBoundingClientRect)})}function ua(a,b){const c=["left","right"],d=["start","end"];"rtl"===wa.getElementDir(a)&&(c.reverse(),d.reverse());return b.replace(/-leading/gi,`-${d[0]}`).replace(/-trailing/gi,`-${d[1]}`).replace(/leading/gi,c[0]).replace(/trailing/gi,c[1])}var R=["top","bottom","right","left"],
qa=R.reduce(function(a,b){return a.concat([b+"-start",b+"-end"])},[]),pa=[].concat(R,["auto"]).reduce(function(a,b){return a.concat([b,b+"-start",b+"-end"])},[]),Ha="beforeRead read afterRead beforeMain main afterMain beforeWrite write afterWrite".split(" "),A=Math.max,G=Math.min,U=Math.round,xa={top:"auto",right:"auto",bottom:"auto",left:"auto"},W={passive:!0},ya={left:"right",right:"left",bottom:"top",top:"bottom"},za={start:"end",end:"start"},va={placement:"bottom",modifiers:[],strategy:"absolute"},
La=function(a){void 0===a&&(a={});var b=a.defaultModifiers,c=void 0===b?[]:b;a=a.defaultOptions;var d=void 0===a?va:a;return function(e,f,g){function l(){m.orderedModifiers.forEach(function(k){var t=k.name,q=k.options;q=void 0===q?{}:q;k=k.effect;"function"===typeof k&&(t=k({state:m,name:t,instance:r,options:q}),h.push(t||function(){}))})}function p(){h.forEach(function(k){return k()});h=[]}void 0===g&&(g=d);var m={placement:"bottom",orderedModifiers:[],options:Object.assign({},va,d),modifiersData:{},
elements:{reference:e,popper:f},attributes:{},styles:{}},h=[],n=!1,r={state:m,setOptions:function(k){k="function"===typeof k?k(m.options):k;p();m.options=Object.assign({},d,m.options,k);m.scrollParents={reference:N(e)?P(e):e.contextElement?P(e.contextElement):[],popper:P(f)};k=Ga(Ja([].concat(c,m.options.modifiers)));m.orderedModifiers=k.filter(function(t){return t.enabled});l();return r.update()},forceUpdate:function(){if(!n){var k=m.elements,t=k.reference;k=k.popper;if(ta(t,k))for(m.rects={reference:Ea(t,
O(k),"fixed"===m.options.strategy),popper:X(k)},m.reset=!1,m.placement=m.options.placement,m.orderedModifiers.forEach(function(u){return m.modifiersData[u.name]=Object.assign({},u.data)}),t=0;t<m.orderedModifiers.length;t++)if(!0===m.reset)m.reset=!1,t=-1;else{var q=m.orderedModifiers[t];k=q.fn;var v=q.options;v=void 0===v?{}:v;q=q.name;"function"===typeof k&&(m=k({state:m,options:v,name:q,instance:r})||m)}}},update:Ia(function(){return new Promise(function(k){r.forceUpdate();k(m)})}),destroy:function(){p();
n=!0}};if(!ta(e,f))return r;r.setOptions(g).then(function(k){if(!n&&g.onFirstUpdate)g.onFirstUpdate(k)});return r}}({defaultModifiers:[{name:"eventListeners",enabled:!0,phase:"write",fn:function(){},effect:function(a){var b=a.state,c=a.instance;a=a.options;var d=a.scroll,e=void 0===d?!0:d;a=a.resize;var f=void 0===a?!0:a,g=y(b.elements.popper),l=[].concat(b.scrollParents.reference,b.scrollParents.popper);e&&l.forEach(function(p){p.addEventListener("scroll",c.update,W)});f&&g.addEventListener("resize",
c.update,W);return function(){e&&l.forEach(function(p){p.removeEventListener("scroll",c.update,W)});f&&g.removeEventListener("resize",c.update,W)}},data:{}},{name:"popperOffsets",enabled:!0,phase:"read",fn:function(a){var b=a.state;b.modifiersData[a.name]=oa({reference:b.rects.reference,element:b.rects.popper,strategy:"absolute",placement:b.placement})},data:{}},{name:"computeStyles",enabled:!0,phase:"beforeWrite",fn:function(a){var b=a.state,c=a.options;a=c.gpuAcceleration;a=void 0===a?!0:a;var d=
c.adaptive;d=void 0===d?!0:d;c=c.roundOffsets;c=void 0===c?!0:c;a={placement:C(b.placement),variation:L(b.placement),popper:b.elements.popper,popperRect:b.rects.popper,gpuAcceleration:a};null!=b.modifiersData.popperOffsets&&(b.styles.popper=Object.assign({},b.styles.popper,ka(Object.assign({},a,{offsets:b.modifiersData.popperOffsets,position:b.options.strategy,adaptive:d,roundOffsets:c}))));null!=b.modifiersData.arrow&&(b.styles.arrow=Object.assign({},b.styles.arrow,ka(Object.assign({},a,{offsets:b.modifiersData.arrow,
position:"absolute",adaptive:!1,roundOffsets:c}))));b.attributes.popper=Object.assign({},b.attributes.popper,{"data-popper-placement":b.placement})},data:{}},{name:"applyStyles",enabled:!0,phase:"write",fn:function(a){var b=a.state;Object.keys(b.elements).forEach(function(c){var d=b.styles[c]||{},e=b.attributes[c]||{},f=b.elements[c];w(f)&&B(f)&&(Object.assign(f.style,d),Object.keys(e).forEach(function(g){var l=e[g];!1===l?f.removeAttribute(g):f.setAttribute(g,!0===l?"":l)}))})},effect:function(a){var b=
a.state,c={popper:{position:b.options.strategy,left:"0",top:"0",margin:"0"},arrow:{position:"absolute"},reference:{}};Object.assign(b.elements.popper.style,c.popper);b.styles=c;b.elements.arrow&&Object.assign(b.elements.arrow.style,c.arrow);return function(){Object.keys(b.elements).forEach(function(d){var e=b.elements[d],f=b.attributes[d]||{};d=Object.keys(b.styles.hasOwnProperty(d)?b.styles[d]:c[d]).reduce(function(g,l){g[l]="";return g},{});w(e)&&B(e)&&(Object.assign(e.style,d),Object.keys(f).forEach(function(g){e.removeAttribute(g)}))})}},
requires:["computeStyles"]},{name:"offset",enabled:!0,phase:"main",requires:["popperOffsets"],fn:function(a){var b=a.state,c=a.name;a=a.options.offset;var d=void 0===a?[0,0]:a;a=pa.reduce(function(g,l){var p=b.rects;var m=C(l);var h=0<=["left","top"].indexOf(m)?-1:1,n="function"===typeof d?d(Object.assign({},p,{placement:l})):d;p=n[0];n=n[1];p=p||0;n=(n||0)*h;m=0<=["left","right"].indexOf(m)?{x:n,y:p}:{x:p,y:n};g[l]=m;return g},{});var e=a[b.placement],f=e.x;e=e.y;null!=b.modifiersData.popperOffsets&&
(b.modifiersData.popperOffsets.x+=f,b.modifiersData.popperOffsets.y+=e);b.modifiersData[c]=a}},{name:"flip",enabled:!0,phase:"main",fn:function(a){var b=a.state,c=a.options;a=a.name;if(!b.modifiersData[a]._skip){var d=c.mainAxis;d=void 0===d?!0:d;var e=c.altAxis;e=void 0===e?!0:e;var f=c.fallbackPlacements,g=c.padding,l=c.boundary,p=c.rootBoundary,m=c.altBoundary,h=c.flipVariations,n=void 0===h?!0:h,r=c.allowedAutoPlacements;c=b.options.placement;h=C(c);f=f||(h!==c&&n?Da(c):[V(c)]);var k=[c].concat(f).reduce(function(H,
M){return H.concat("auto"===C(M)?Ca(b,{placement:M,boundary:l,rootBoundary:p,padding:g,flipVariations:n,allowedAutoPlacements:r}):M)},[]);c=b.rects.reference;f=b.rects.popper;var t=new Map;h=!0;for(var q=k[0],v=0;v<k.length;v++){var u=k[v],z=C(u),D="start"===L(u),x=0<=["top","bottom"].indexOf(z),I=x?"width":"height",J=Q(b,{placement:u,boundary:l,rootBoundary:p,altBoundary:m,padding:g});D=x?D?"right":"left":D?"bottom":"top";c[I]>f[I]&&(D=V(D));I=V(D);x=[];d&&x.push(0>=J[z]);e&&x.push(0>=J[D],0>=J[I]);
if(x.every(function(H){return H})){q=u;h=!1;break}t.set(u,x)}if(h)for(d=function(H){var M=k.find(function(da){if(da=t.get(da))return da.slice(0,H).every(function(Ka){return Ka})});if(M)return q=M,"break"},e=n?3:1;0<e&&"break"!==d(e);e--);b.placement!==q&&(b.modifiersData[a]._skip=!0,b.placement=q,b.reset=!0)}},requiresIfExists:["offset"],data:{_skip:!1}},{name:"preventOverflow",enabled:!0,phase:"main",fn:function(a){var b=a.state,c=a.options;a=a.name;var d=c.mainAxis,e=void 0===d?!0:d;d=c.altAxis;
var f=void 0===d?!1:d;d=c.tether;d=void 0===d?!0:d;var g=c.tetherOffset,l=void 0===g?0:g,p=Q(b,{boundary:c.boundary,rootBoundary:c.rootBoundary,padding:c.padding,altBoundary:c.altBoundary});c=C(b.placement);var m=L(b.placement),h=!m,n=Y(c);c="x"===n?"y":"x";g=b.modifiersData.popperOffsets;var r=b.rects.reference,k=b.rects.popper,t="function"===typeof l?l(Object.assign({},b.rects,{placement:b.placement})):l;l={x:0,y:0};if(g){if(e||f){var q="y"===n?"top":"left",v="y"===n?"bottom":"right",u="y"===n?
"height":"width",z=g[n],D=g[n]+p[q],x=g[n]-p[v],I=d?-k[u]/2:0,J="start"===m?r[u]:k[u];m="start"===m?-k[u]:-r[u];k=b.elements.arrow;k=d&&k?X(k):{width:0,height:0};var H=b.modifiersData["arrow#persistent"]?b.modifiersData["arrow#persistent"].padding:{top:0,right:0,bottom:0,left:0};q=H[q];v=H[v];k=A(0,G(r[u],k[u]));J=h?r[u]/2-I-k-q-t:J-k-q-t;r=h?-r[u]/2+I+k+v+t:m+k+v+t;h=b.elements.arrow&&O(b.elements.arrow);t=b.modifiersData.offset?b.modifiersData.offset[b.placement][n]:0;h=g[n]+J-t-(h?"y"===n?h.clientTop||
0:h.clientLeft||0:0);r=g[n]+r-t;e&&(e=d?G(D,h):D,x=d?A(x,r):x,e=A(e,G(z,x)),g[n]=e,l[n]=e-z);f&&(f=g[c],e=f+p["x"===n?"top":"left"],p=f-p["x"===n?"bottom":"right"],e=d?G(e,h):e,d=d?A(p,r):p,d=A(e,G(f,d)),g[c]=d,l[c]=d-f)}b.modifiersData[a]=l}},requiresIfExists:["offset"]},{name:"arrow",enabled:!0,phase:"main",fn:function(a){var b,c=a.state,d=a.name,e=a.options,f=c.elements.arrow,g=c.modifiersData.popperOffsets,l=C(c.placement);a=Y(l);l=0<=["left","right"].indexOf(l)?"height":"width";if(f&&g){e=e.padding;
e="function"===typeof e?e(Object.assign({},c.rects,{placement:c.placement})):e;e=ia("number"!==typeof e?e:ja(e,R));var p=X(f),m="y"===a?"top":"left",h="y"===a?"bottom":"right",n=c.rects.reference[l]+c.rects.reference[a]-g[a]-c.rects.popper[l];g=g[a]-c.rects.reference[a];f=(f=O(f))?"y"===a?f.clientHeight||0:f.clientWidth||0:0;g=f/2-p[l]/2+(n/2-g/2);l=A(e[m],G(g,f-p[l]-e[h]));c.modifiersData[d]=(b={},b[a]=l,b.centerOffset=l-g,b)}},effect:function(a){var b=a.state;a=a.options.element;a=void 0===a?"[data-popper-arrow]":
a;if(null!=a){if("string"===typeof a&&(a=b.elements.popper.querySelector(a),!a))return;fa(b.elements.popper,a)&&(b.elements.arrow=a)}},requires:["popperOffsets"],requiresIfExists:["preventOverflow"]},{name:"hide",enabled:!0,phase:"main",requiresIfExists:["preventOverflow"],fn:function(a){var b=a.state;a=a.name;var c=b.rects.reference,d=b.rects.popper,e=b.modifiersData.preventOverflow,f=Q(b,{elementContext:"reference"}),g=Q(b,{altBoundary:!0});c=ra(f,c);d=ra(g,d,e);e=sa(c);g=sa(d);b.modifiersData[a]=
{referenceClippingOffsets:c,popperEscapeOffsets:d,isReferenceHidden:e,hasPopperEscaped:g};b.attributes.popper=Object.assign({},b.attributes.popper,{"data-popper-reference-hidden":e,"data-popper-escaped":g})}}]});const Ma=Math.ceil(Math.sqrt(Math.pow(4,2)+Math.pow(4,2)));S.CSS={animation:"calcite-popper-anim",animationActive:"calcite-popper-anim--active"};S.createPopper=function({referenceEl:a,el:b,placement:c,overlayPositioning:d="absolute",modifiers:e}){return a?La(a,b,{strategy:d,placement:ua(b,
c),modifiers:e}):null};S.defaultOffsetDistance=Ma;S.updatePopper=async function({el:a,modifiers:b,placement:c,popper:d}){a=ua(a,c);await d.setOptions({modifiers:b,placement:a})}});