// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../intl ../../../core/Error ../../../core/lang ../../../core/Logger ../../../core/maybe ../../../core/unitUtils ../../../geometry/Polygon ./geometryUtils ../../../intl/substitute ../../../intl/date".split(" "),function(G,Q,ja,v,R,S,T,U,V,J,W,X){function K(a,c){const {filter:b,withinViewEnabled:e}=a;a=c&&c.extent;return b&&b.geometry||(e&&a?a:void 0)}function L(a){return H.apply(this,arguments)}function H(){H=Q._asyncToGenerator(function*(a){a&&
(yield a.load())});return H.apply(this,arguments)}function M(a){var c,b,e;return null!=(c=null==a?void 0:null==(b=a.capabilities)?void 0:null==(e=b.query)?void 0:e.supportsPagination)?c:!1}function N(a){var c,b,e,h;return null!=(c=null==a?void 0:null==(b=a.fieldsIndex)?void 0:null==(e=b.fields)?void 0:null==(h=e.find(m=>"string"===m.type))?void 0:h.name)?c:""}function C(a,c){return a&&c?c.every(b=>!!a.getField(b)):!1}function Y(a,c,b){let e=null;({codedValues:a}=a);a&&a.some(h=>{var m=h.name;m=b?
m:m.toLowerCase();return(b?c:c.toLowerCase())===m?(e=h.code.toString(),!0):!1});return e}function D(a,c){return(c=c&&c.where)?`(${a}) AND (${c})`:a}function Z({currentTerm:a,field:c,filter:b,exactMatch:e,url:h,type:m}){var d=c.type;c=c.name;if("string"===d||"date"===d||"global-id"===d){if(d=h=aa.test(h))a:{for(d=0;d<a.length;d++)if(255<a.charCodeAt(d)){d=!0;break a}d=!1}d=d?"N":"";if(e&&"search"===m)return D(`${c} = ${d}'${a}'`,b);m=h?c:`UPPER(${c})`;a=h?a:a.toUpperCase();return D(`${m} LIKE ${d}${e?
`'${a}%'`:`'%${a}%'`}`,b)}return"oid"===d||"small-integer"===d||"integer"===d||"single"===d||"double"===d?(e=Number(a),isNaN(e)?null:D(`${c} = ${e}`,b)):D(`${c} = ${a}`,b)}function O({searchTerm:a,layer:c,searchFields:b,filter:e,exactMatch:h,type:m}){const {definitionExpression:d,url:p}=c;let n="";a&&b&&b.forEach(f=>{var g=c.getField(f);f=((f="function"===typeof c.getFieldDomain&&c.getFieldDomain(f))&&"coded-value"===f.type?Y(f,a,h):null)||a||null;null!==f&&(g=Z({currentTerm:f,field:g,filter:e,exactMatch:h,
url:p,type:m}))&&(n+=n?` OR (${g})`:`(${g})`)});return d?`(${d}) AND (${n})`:n}function ba(a,c){let b=null;({codedValues:a}=a);a&&a.length&&a.some(e=>e.code===c?(b=e.name,!0):!1);return b}function ca(a,c){return a[Object.keys(a).find(b=>b.toLowerCase()===c.toLowerCase())]}function P(a,c,b){const e=a.sourceLayer,{attributes:h}=a;a="function"===typeof e.getFieldDomain&&e.getFieldDomain(b);return c?W.substitute(c,h):b&&h?(c=e.getField(b),b=ca(h,b),null==b?"":a&&"coded-value"===a.type?ba(a,b):"date"===
(null==c?void 0:c.type)?X.formatDate(new Date(b)):"number"===typeof b?b.toString():"string"!==typeof b?"":b.trim()):""}function da(a,c,b,e){return a.features.map(h=>{var m=h.sourceLayer,{attributes:d}=h;({objectIdField:m}=m);d=d[m];return h={text:P(h,c.suggestionTemplate,e),key:d,sourceIndex:b}})}function ea(a,c,b,e,h,m,d){return a.features.map(p=>{{var n=p.clone();var f=p.sourceLayer;f=(f=f&&f.objectIdField)&&p.attributes[f];const A=P(p,b.searchTemplate,h);var g=J.createExtentFromGeometry(n.geometry,
c,m);g="number"===typeof d?J.scaleExtent(R.clone(g),c,d):g;p=p.clone();T.isSome(g)&&(p.geometry=V.fromExtent(g));n={extent:g,target:p,feature:n,key:f,name:A,sourceIndex:e}}return n})}const aa=/https?:\/\/services.*\.arcgis\.com/i,fa=/(?:\{([^}]+)\})/g,w=S.getLogger("esri.widgets.Search.support.layerSearchUtils");G.getResults=function(a,c){const {exactMatch:b=!1,location:e,maxResults:h,spatialReference:m,source:d,sourceIndex:p,suggestResult:n,view:f}=a,{layer:g,filter:A,zoomScale:E}=d,x=f&&f.scale,
u=K(d,f),q=c&&c.signal;return L(g).then(()=>{const l=g.popupTemplate;return l?l.getRequiredFields(g.fieldsIndex):null}).then(l=>{var k,r,y;const {objectIdField:F,returnZ:B}=g,z=d.displayField||d.layer.displayField||N(d.layer);if(!g.getField(z))throw w.error("invalid-field: displayField is invalid."),new v("getResults():invalid-field","displayField is invalid.");l=l&&l.length?l:[z];var t=(l=d.outFields||l)&&-1!==l.indexOf("*");-1!==l.indexOf(F)||t||l.push(F);null!=(k=g.floorInfo)&&k.floorField&&l.push(g.floorInfo.floorField);
if(!t&&!C(g,l))throw w.error("invalid-field: outField is invalid."),new v("getResults():invalid-field","outField is invalid.");k=g.createQuery();({orderByFields:t}=d);t&&(k.orderByFields=t);m&&(k.outSpatialReference=m,t=1/U.getMetersPerUnitForSR(m))&&(k.maxAllowableOffset=t);t="mesh"===g.geometryType||"multipatch"===g.geometryType;const ha=(null==(r=g.capabilities)?void 0:null==(y=r.data)?void 0:y.supportsZ)&&!t;k.returnZ=ha&&!1!==B;k.returnGeometry=!0;k.multipatchOption=t?"xyFootprint":null;l&&(k.outFields=
l);if(e)k.geometry=e;else if(n.key)k.objectIds=[n.key];else{r=d.searchFields||[z];if(!C(g,r))throw w.error("invalid-field: search field is invalid."),new v("getResults():invalid-field","search field is invalid.");M(g)&&(k.num=h);u&&(k.geometry=u);if(!n.text.trim())return[];const {prefix:I="",suffix:ia=""}=d;y=`${I}${n.text}${ia}`.replace(/'/g,"''");r=O({searchTerm:y,layer:g,searchFields:r,filter:A,exactMatch:b,type:"search"});if(!r)return[];k.where=r}return g.queryFeatures(k,{signal:q}).then(I=>ea(I,
f,d,p,z,x,E))})};G.getSuggestions=function(a,c){const {source:b,spatialReference:e,view:h,suggestTerm:m,maxSuggestions:d,sourceIndex:p,exactMatch:n}=a,{layer:f,filter:g}=b,A=c&&c.signal,E=K(b,h);return L(f).then(()=>{if(!M(f))return[];const x=b.displayField||b.layer.displayField||N(b.layer);var u=b.searchFields||[x];const q=[];b.suggestionTemplate?b.suggestionTemplate.replace(fa,(B,z)=>{q.push(z);return B}):q.push(x);var l=q&&-1!==q.indexOf("*");-1!==q.indexOf(f.objectIdField)||l||q.push(f.objectIdField);
var k=!!f.getField(x);l=l||C(f,q);const r=C(f,u);if(!k)throw w.error("invalid-field: displayField is invalid."),new v("getSuggestions():invalid-field","displayField is invalid.");if(!l)throw w.error("invalid-field: outField is invalid."),new v("getSuggestions():invalid-field","outField is invalid.");if(!r)throw w.error("invalid-field: search field is invalid."),new v("getSuggestions():invalid-field","search field is invalid.");k=f.createQuery();({orderByFields:l}=b);l&&(k.orderByFields=l);k.outSpatialReference=
e;k.returnGeometry=!1;k.num=d;k.outFields=q;E&&(k.geometry=E);if(!m.trim())return[];const {prefix:y="",suffix:F=""}=b;l=`${y}${m}${F}`.replace(/'/g,"''");u=O({searchTerm:l,layer:f,searchFields:u,filter:g,exactMatch:n,type:"suggest"});if(!u)return[];k.where=u;return f.queryFeatures(k,{signal:A}).then(B=>da(B,b,p,x))})};Object.defineProperty(G,"__esModule",{value:!0})});