// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../geometry ../../request ../../core/Error ../../core/iteratorUtils ../../core/maybe ../../core/promiseUtils ../../core/urlUtils ../../geometry/projection ../../geometry/support/spatialReferenceUtils ../../geometry/support/typeUtils ../graphics/sources/geojson/geojson ./dateUtils ./xmlUtils ../support/Field ../../geometry/SpatialReference ../../geometry/Extent".split(" "),function(m,n,ma,u,l,A,v,V,w,L,x,W,X,Y,p,t,M,Z){function B(){B=n._asyncToGenerator(function*(a,
b){b=yield u(a,{responseType:"text",query:{SERVICE:"WFS",REQUEST:"GetCapabilities",VERSION:"2.0.0",...null==b?void 0:b.customParameters},signal:null==b?void 0:b.signal});b=N(b.data);w.isHTTPSProtocol(a)&&(w.hasSameOrigin(a,b.operations.DescribeFeatureType.url,!0)&&(b.operations.DescribeFeatureType.url=w.toHTTPS(b.operations.DescribeFeatureType.url)),w.hasSameOrigin(a,b.operations.GetFeature.url,!0)&&(b.operations.GetFeature.url=w.toHTTPS(b.operations.GetFeature.url)));return b});return B.apply(this,
arguments)}function N(a){a=C(a);aa(a);D(a);a=a.firstElementChild;const b=A.cache(ba(a));return{operations:ca(a),get featureTypes(){return Array.from(b())},readFeatureTypes:b}}function ca(a){let b=!1;const c={GetCapabilities:{url:""},DescribeFeatureType:{url:""},GetFeature:{url:"",outputFormat:null,supportsPagination:!1}};p.visitXML(a,{OperationsMetadata:{Operation:e=>{switch(e.getAttribute("name")){case "GetCapabilities":return{DCP:{HTTP:{Get:d=>{c.GetCapabilities.url=d.getAttribute("xlink:href")}}}};
case "DescribeFeatureType":return{DCP:{HTTP:{Get:d=>{c.DescribeFeatureType.url=d.getAttribute("xlink:href")}}}};case "GetFeature":return{DCP:{HTTP:{Get:d=>{c.GetFeature.url=d.getAttribute("xlink:href")}}},Parameter:d=>{if("outputFormat"===d.getAttribute("name"))return{AllowedValues:{Value:f=>{f=f.textContent;da.has(f.toLowerCase())&&(c.GetFeature.outputFormat=f)}}}}}}},Constraint:e=>{switch(e.getAttribute("name")){case "KVPEncoding":return{DefaultValue:d=>{b="true"===d.textContent.toLowerCase()}};
case "ImplementsResultPaging":return{DefaultValue:d=>{c.GetFeature.supportsPagination="true"===d.textContent.toLowerCase()}}}}}});if(!b)throw new l("wfs-layer:kvp-encoding-not-supported","WFS service doesn't support key/value pair (KVP) encoding");if(v.isNone(c.GetFeature.outputFormat))throw new l("wfs-layer:geojson-not-supported","WFS service doesn't support GeoJSON output format");return c}function ba(a){return p.iterateXML(a,{FeatureTypeList:{FeatureType:b=>{const c={typeName:"undefined:undefined",
name:"",title:"",description:"",extent:null,namespacePrefix:"",namespaceUri:"",supportedSpatialReferences:[]},e=new Set([4326]),d=f=>{var g,h;f=parseInt(null==(g=f.textContent.match(/(?<wkid>\d+$)/i))?void 0:null==(h=g.groups)?void 0:h.wkid,10);Number.isNaN(f)||e.add(f)};p.visitXML(b,{Name:f=>{const {name:g,prefix:h}=y(f.textContent);c.typeName=`${h}:${g}`;c.name=g;c.namespacePrefix=h;c.namespaceUri=f.lookupNamespaceURI(h)},Abstract:f=>{c.description=f.textContent},Title:f=>{c.title=f.textContent},
WGS84BoundingBox:f=>{c.extent=ea(f)},DefaultSRS:d,DefaultCRS:d,OtherSRS:d,OtherCRS:d});c.title||(c.title=c.name);c.supportedSpatialReferences.push(...e);return c}}})}function ea(a){let b,c,e,d;for(const f of a.children)switch(f.localName){case "LowerCorner":[b,c]=f.textContent.split(" ").map(g=>Number.parseFloat(g));break;case "UpperCorner":[e,d]=f.textContent.split(" ").map(g=>Number.parseFloat(g))}return{xmin:b,ymin:c,xmax:e,ymax:d,spatialReference:x.WGS84}}function O(a,b,c){return A.find(a,e=>
c?e.name===b&&e.namespaceUri===c:e.typeName===b||e.name===b)}function E(){E=n._asyncToGenerator(function*(a,b,c,e={}){var d;const {featureType:f,extent:g}=yield P(a,b,c,e),{fields:h,geometryType:k,swapXY:z,objectIdField:r,geometryField:q}=yield fa(a,f.typeName,e);return{url:a.operations.GetCapabilities.url,name:f.name,namespaceUri:f.namespaceUri,fields:h,geometryField:q,geometryType:k,objectIdField:r,spatialReference:null!=(d=e.spatialReference)?d:M.WGS84,extent:g,swapXY:z,wfsCapabilities:a,customParameters:e.customParameters}});
return E.apply(this,arguments)}function P(a,b,c){return F.apply(this,arguments)}function F(){F=n._asyncToGenerator(function*(a,b,c,e={}){const {spatialReference:d=M.WGS84}=e;a=a.readFeatureTypes();c=b?O(a,b,c):a.next().value;if(v.isNone(c)){if(b)throw new l("wfs-layer:feature-type-not-found",`The type '${b}' could not be found in the service`);throw new l("wfs-layer:empty-service","The service is empty");}b=new Z({...c.extent,spatialReference:d});if(!x.equals(d,x.WGS84))try{yield L.initializeProjection(x.WGS84,
d,void 0,e),b=L.project(b,x.WGS84)}catch{throw new l("wfs-layer:unsupported-spatial-reference","Projection not supported");}return{extent:b,spatialReference:d,featureType:c}});return F.apply(this,arguments)}function fa(a,b){return G.apply(this,arguments)}function G(){G=n._asyncToGenerator(function*(a,b,c={}){const [e,d]=yield V.eachAlways([Q(a.operations.DescribeFeatureType.url,b,c),ha(a,b,c)]);if(e.error||d.error)throw new l("wfs-layer:getWFSLayerTypeInfo-error",`An error occurred while getting info about the feature type '${b}'`,
{error:e.error||d.error});const {fields:f,errors:g}=e.value;a=e.value.geometryType||d.value.geometryType;c=d.value.swapXY;if(v.isNone(a))throw new l("wfs-layer:unknown-geometry-type",`The geometry type could not be determined for type '${b}`,{typeName:b,geometryType:a,fields:f,errors:g});return{...R(f),geometryType:a,swapXY:c}});return G.apply(this,arguments)}function R(a){var b;const c=a.find(d=>"geometry"===d.type);let e=a.find(d=>"oid"===d.type);a=a.filter(d=>"geometry"!==d.type);e||(e=new t({name:"__esri_wfs_id__",
type:"oid",alias:"__esri_wfs_id__"}),a.unshift(e));return{geometryField:null!=(b=null==c?void 0:c.name)?b:null,objectIdField:e.name,fields:a}}function ha(a,b){return H.apply(this,arguments)}function H(){H=n._asyncToGenerator(function*(a,b,c={}){var e;let d,f=!1;const [g,h]=yield Promise.all([S(a.operations.GetFeature.url,b,a.operations.GetFeature.outputFormat,{...c,count:1}),u(a.operations.GetFeature.url,{responseType:"text",query:T(b,void 0,{...c,count:1}),signal:null==c?void 0:c.signal})]);if(a=
"FeatureCollection"===g.type&&(null==(e=g.features[0])?void 0:e.geometry)){d=W.featureGeometryTypeKebabDictionary.fromJSON(X.getGeometryType(a.type));switch(a.type){case "Point":var k=a.coordinates;break;case "LineString":case "MultiPoint":k=a.coordinates[0];break;case "MultiLineString":case "Polygon":k=a.coordinates[0][0];break;case "MultiPolygon":k=a.coordinates[0][0][0]}if(a=/<[^>]*pos[^>]*> *(-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?)/.exec(h.data))e=k[0].toFixed(3),k=k[1].toFixed(3),b=parseFloat(a[1]).toFixed(3),
a=parseFloat(a[2]).toFixed(3),e===a&&k===b&&(f=!0)}return{geometryType:d,swapXY:f}});return H.apply(this,arguments)}function Q(a,b,c){return I.apply(this,arguments)}function I(){I=n._asyncToGenerator(function*(a,b,c){a=yield u(a,{responseType:"text",query:{SERVICE:"WFS",REQUEST:"DescribeFeatureType",VERSION:"2.0.0",TYPENAME:b,...null==c?void 0:c.customParameters},signal:null==c?void 0:c.signal});return U(b,a.data)});return I.apply(this,arguments)}function U(a,b){const {name:c}=y(a);b=C(b);D(b);const e=
A.find(p.iterateXML(b.firstElementChild,{element:d=>({name:d.getAttribute("name"),typeName:y(d.getAttribute("type")).name})}),({name:d})=>d===c);if(v.isSome(e)){const d=A.find(p.iterateXML(b.firstElementChild,{complexType:f=>f}),f=>f.getAttribute("name")===e.typeName);if(v.isSome(d))return ia(d)}throw new l("wfs-layer:feature-type-not-found",`Type '${a}' not found in document`,{document:(new XMLSerializer).serializeToString(b)});}function ia(a){var b,c;const e=[],d=[];let f;var g=p.iterateXML(a,{complexContent:{extension:{sequence:{element:h=>
h}}}});for(const h of g){g=h.getAttribute("name");if(!g)continue;let k,z;h.hasAttribute("type")?k=y(h.getAttribute("type")).name:p.visitXML(h,{simpleType:{restriction:ja=>{k=y(ja.getAttribute("base")).name;return{maxLength:ka=>{z=+ka.getAttribute("value")}}}}});if(!k)continue;const r="true"===h.getAttribute("nillable");let q=!1;switch(k.toLowerCase()){case "integer":case "nonpositiveinteger":case "negativeinteger":case "long":case "int":case "short":case "byte":case "nonnegativeinteger":case "unsignedlong":case "unsignedint":case "unsignedshort":case "unsignedbyte":case "positiveinteger":d.push(new t({name:g,
alias:g,type:"integer",nullable:r}));break;case "float":case "double":case "decimal":d.push(new t({name:g,alias:g,type:"double",nullable:r}));break;case "boolean":case "string":case "gyearmonth":case "gyear":case "gmonthday":case "gday":case "gmonth":case "anyuri":case "qname":case "notation":case "normalizedstring":case "token":case "language":case "idrefs":case "entities":case "nmtoken":case "nmtokens":case "name":case "ncname":case "id":case "idref":case "entity":case "duration":case "time":d.push(new t({name:g,
alias:g,type:"string",nullable:r,length:null!=(b=z)?b:255}));break;case "datetime":case "date":d.push(new t({name:g,alias:g,type:"date",nullable:r,length:null!=(c=z)?c:36}));break;case "pointpropertytype":f="point";q=!0;break;case "multipointpropertytype":f="multipoint";q=!0;break;case "curvepropertytype":case "multicurvepropertytype":case "multilinestringpropertytype":f="polyline";q=!0;break;case "surfacepropertytype":case "multisurfacepropertytype":case "multipolygonpropertytype":f="polygon";q=
!0;break;case "geometrypropertytype":case "multigeometrypropertytype":q=!0;e.push(new l("wfs-layer:unknown-geometry-type",`geometry type '${k}' is not supported`,{type:(new XMLSerializer).serializeToString(a)}));break;default:e.push(new l("wfs-layer:unknown-field-type",`Unknown field type '${k}'`,{type:(new XMLSerializer).serializeToString(a)}))}q&&d.push(new t({name:g,alias:g,type:"geometry",nullable:r}))}for(const h of d)if("integer"===h.type&&!h.nullable&&la.has(h.name.toLowerCase())){h.type="oid";
break}return{geometryType:f,fields:d,errors:e}}function S(a,b,c,e){return J.apply(this,arguments)}function J(){J=n._asyncToGenerator(function*(a,b,c,e){({data:a}=yield u(a,{responseType:"text",query:T(b,c,e),signal:null==e?void 0:e.signal}));a=a.replace(/": +(-?\d+),(\d+)(,)?/g,'": $1.$2$3');try{var d;if(null!=e&&null!=(d=e.dateFields)&&d.length){const f=new Set(e.dateFields);return JSON.parse(a,(g,h)=>f.has(g)?Y.parseDate(h):h)}return JSON.parse(a)}catch(f){throw new l("wfs-layer:malformed-json",
"Error while parsing the\u00a0response",{response:a,error:f});}});return J.apply(this,arguments)}function T(a,b,c){return{SERVICE:"WFS",REQUEST:"GetFeature",VERSION:"2.0.0",TYPENAMES:a,OUTPUTFORMAT:b,SRSNAME:"EPSG:4326",STARTINDEX:null==c?void 0:c.startIndex,COUNT:null==c?void 0:c.count,...null==c?void 0:c.customParameters}}function K(){K=n._asyncToGenerator(function*(a,b,c){a=yield u(a,{responseType:"text",query:{SERVICE:"WFS",REQUEST:"GetFeature",VERSION:"2.0.0",TYPENAMES:b,RESULTTYPE:"hits",...null==
c?void 0:c.customParameters},signal:null==c?void 0:c.signal});a=C(a.data);D(a);a=Number.parseFloat(a.firstElementChild.getAttribute("numberMatched"));return Number.isNaN(a)?0:a});return K.apply(this,arguments)}function C(a){return(new DOMParser).parseFromString(a.trim(),"text/xml")}function y(a){const [b,c]=a.split(":");return{prefix:c?b:"",name:null!=c?c:b}}function aa(a){if((a=a.firstElementChild.getAttribute("version"))&&"2.0.0"!==a)throw new l("wfs-layer:unsupported-wfs-version",`Unsupported WFS version ${a}. Supported version: ${"2.0.0"}`);
}function D(a){let b,c;p.visitXML(a.firstElementChild,{Exception:e=>{b=e.getAttribute("exceptionCode");return{ExceptionText:d=>{c=d.textContent}}}});if(b)throw new l(`wfs-layer:${b}`,c);}const da=new Set(["json","application/json","geojson","application/json; subtype\x3dgeojson"]),la=new Set(["objectid","fid"]);m.WFS_OID_FIELD_NAME="__esri_wfs_id__";m.describeFeatureType=Q;m.findFeatureType=O;m.getCapabilities=function(a,b){return B.apply(this,arguments)};m.getFeature=S;m.getFeatureCount=function(a,
b,c){return K.apply(this,arguments)};m.getFeatureTypeInfo=P;m.getWFSLayerInfo=function(a,b,c){return E.apply(this,arguments)};m.parseDescribeFeatureTypeResponse=U;m.parseGetCapabilitiesResponse=N;m.prepareWFSLayerFields=R;Object.defineProperty(m,"__esModule",{value:!0})});