// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../request ../../../core/maybe ../../../core/urlUtils ../../../geometry/support/jsonUtils ../../../geometry/support/normalizeUtils ../../../layers/support/arcgisLayerUrl ./pbfQueryUtils ./queryZScale ../../../tasks/operations/urlUtils".split(" "),function(h,r,x,g,t,y,z,A,B,C,D){function u(c,b,e=!1){const d=c.geometry,a=c.toJSON(),m=c.outSpatialReference;let f,v;if(g.isSome(d)){f=d.spatialReference;v=d.spatialReference.wkid||JSON.stringify(d.spatialReference);
a.geometryType=y.getJsonType(d);if("extent"===d.type)a.geometry=`${d.xmin},${d.ymin},${d.xmax},${d.ymax}`;else if("point"===d.type)a.geometry=`${d.x},${d.y}`;else{const k=d.toJSON();delete k.spatialReference;a.geometry=JSON.stringify(k)}a.inSR=v}f||(f=m);a.groupByFieldsForStatistics&&(a.groupByFieldsForStatistics=a.groupByFieldsForStatistics.join(","));a.objectIds&&(a.objectIds=a.objectIds.join(","));a.orderByFields&&(a.orderByFields=a.orderByFields.join(","));!a.outFields||!a.returnDistinctValues&&
(null!=b&&b.returnCountOnly||null!=b&&b.returnExtentOnly||null!=b&&b.returnIdsOnly)?delete a.outFields:-1!==a.outFields.indexOf("*")?a.outFields="*":a.outFields=a.outFields.join(",");a.outSR?a.outSR=a.outSR.wkid||JSON.stringify(a.outSR):d&&(a.returnGeometry||a.returnCentroid)&&(a.outSR=a.inSR);a.returnGeometry&&delete a.returnGeometry;a.outStatistics&&(a.outStatistics=JSON.stringify(a.outStatistics));a.pixelSize&&(a.pixelSize=JSON.stringify(a.pixelSize));a.quantizationParameters&&(e&&g.isSome(f)&&
g.isSome(c.quantizationParameters)&&g.isSome(c.quantizationParameters.extent)&&f.equals(c.quantizationParameters.extent.spatialReference)&&delete a.quantizationParameters.extent.spatialReference,a.quantizationParameters=JSON.stringify(a.quantizationParameters));a.parameterValues&&(a.parameterValues=JSON.stringify(a.parameterValues));a.rangeValues&&(a.rangeValues=JSON.stringify(a.rangeValues));a.dynamicDataSource&&(a.layer=JSON.stringify({source:a.dynamicDataSource}),delete a.dynamicDataSource);if(a.timeExtent){const {start:k,
end:n}=a.timeExtent;if(null!=k||null!=n)a.time=k===n?k:`${null==k?"null":k},${null==n?"null":n}`;delete a.timeExtent}return a}function p(){p=r._asyncToGenerator(function*(c,b,e,d){c=g.isSome(b.timeExtent)&&b.timeExtent.isEmpty?{data:{features:[]}}:yield l(c,b,"json",d);C.applyFeatureSetZUnitScaling(b,e,c.data);return c});return p.apply(this,arguments)}function q(){q=r._asyncToGenerator(function*(c,b,e,d){if(g.isSome(b.timeExtent)&&b.timeExtent.isEmpty)return Promise.resolve({data:e.createFeatureResult()});
c=yield w(c,b,d);c.data=B.parsePBFFeatureQuery(c.data,e);return c});return q.apply(this,arguments)}function w(c,b,e){return l(c,b,"pbf",e)}function l(c,b,e,d={},a={}){const m="string"===typeof c?t.urlToObject(c):c;c=b.geometry?[b.geometry]:[];d.responseType="pbf"===e?"array-buffer":"json";return z.normalizeCentralMeridian(c,null,d).then(f=>{f=f&&f[0];g.isSome(f)&&(b=b.clone(),b.geometry=f);f=A.isHostedAgolService(m.path);f=D.mapParameters({...m.query,f:e,...a,...u(b,a,f)});return x(t.join(m.path,
"query"),{...d,query:{...f,...d.query}})})}h.executeQuery=function(c,b,e,d){return p.apply(this,arguments)};h.executeQueryForCount=function(c,b,e){return g.isSome(b.timeExtent)&&b.timeExtent.isEmpty?Promise.resolve({data:{count:0}}):l(c,b,"json",e,{returnIdsOnly:!0,returnCountOnly:!0})};h.executeQueryForExtent=function(c,b,e){return g.isSome(b.timeExtent)&&b.timeExtent.isEmpty?Promise.resolve({data:{count:0,extent:null}}):l(c,b,"json",e,{returnExtentOnly:!0,returnCountOnly:!0}).then(d=>{const a=d.data;
if(a.hasOwnProperty("extent"))return d;if(a.features)throw Error("Layer does not support extent calculation.");if(a.hasOwnProperty("count"))throw Error("Layer does not support extent calculation.");return d})};h.executeQueryForIds=function(c,b,e){return g.isSome(b.timeExtent)&&b.timeExtent.isEmpty?Promise.resolve({data:{objectIds:[]}}):l(c,b,"json",e,{returnIdsOnly:!0})};h.executeQueryPBF=function(c,b,e,d){return q.apply(this,arguments)};h.executeQueryPBFBuffer=w;h.queryToQueryStringParameters=u;
h.runQuery=l;Object.defineProperty(h,"__esModule",{value:!0})});