// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/deprecate ../../core/Error ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../layers/support/commonProperties ../../layers/support/FeatureEffect ../../layers/support/FeatureFilter ../../layers/support/fieldUtils ../../rest/support/Query ../../support/arcadeOnDemand ./support/popupUtils ../support/floorFilterUtils".split(" "),
function(A,u,n,E,B,w,p,F,C,r,N,O,P,H,I,J,K,e,L,M,x,G){const y=w.getLogger("esri.views.layers.FeatureLayerView");w=g=>{g=function(D){function z(...b){b=D.call(this,...b)||this;b._updatingRequiredFieldsPromise=null;b.filter=null;b.timeExtent=null;b.layer=null;b.requiredFields=[];b.view=null;return b}u._inheritsLoose(z,D);var k=z.prototype;k.initialize=function(){C.init(this,"layer.renderer layer.labelingInfo layer.elevationInfo.featureExpressionInfo layer.displayField filter featureEffect layer.timeInfo layer.floorInfo timeExtent".split(" "),
()=>this._handleRequiredFieldsChange(),!0);C.on(this,"view.floors","change",()=>this._handleRequiredFieldsChange());C.on(this,"layer.sublayer","change",()=>this._handleRequiredFieldsChange())};k.highlight=function(b){throw Error("missing implementation");};k.createQuery=function(){var b={outFields:["*"],returnGeometry:!0,outSpatialReference:this.view.spatialReference};b=p.isSome(this.filter)?this.filter.createQuery(b):new L(b);if("feature"===this.layer.type){const c=G.getFloorFilterClause(this);p.isSome(c)&&
(b.where=b.where?`(${b.where}) AND (${c})`:c)}p.isSome(this.timeExtent)&&(b.timeExtent=p.isSome(b.timeExtent)?b.timeExtent.intersection(this.timeExtent):this.timeExtent.clone());return b};k.queryFeatures=function(b,c){throw Error("missing implementation");};k.queryObjectIds=function(b,c){throw Error("missing implementation");};k.queryFeatureCount=function(b,c){throw Error("missing implementation");};k.queryExtent=function(b,c){throw Error("missing implementation");};k.fetchPopupFeatures=function(){var b=
u._asyncToGenerator(function*(c,a){if(c=this.validateFetchPopupFeatures(a))throw c;return this.fetchClientPopupFeatures(a)});return function(c,a){return b.apply(this,arguments)}}();k._loadArcadeModules=function(b){if(b.get("expressionInfos.length")||Array.isArray(b.content)&&b.content.some(c=>"expression"===c.type))return M.loadArcade()};k._handleRequiredFieldsChange=function(){const b=this._updateRequiredFields();this._set("_updatingRequiredFieldsPromise",b);b.then(()=>{this._updatingRequiredFieldsPromise===
b&&this._set("_updatingRequiredFieldsPromise",null)})};k._updateRequiredFields=function(){var b=u._asyncToGenerator(function*(){if(this.layer&&this.view){var c="3d"===this.view.type,{layer:a,layer:{fieldsIndex:m,objectIdField:l}}=this,f="renderer"in a&&a.renderer,h="orderBy"in a&&a.orderBy,q=a.featureReduction,d=new Set;f=yield F.eachAlways([f?f.collectRequiredFields(d,m):null,e.collectLabelingFields(d,a),c?e.collectElevationFields(d,a):null,p.isSome(this.filter)?e.collectFilterFields(d,a,this.filter):
null,p.isSome(this.featureEffect)?e.collectFilterFields(d,a,this.featureEffect.filter):null,q?e.collectFeatureReductionFields(d,a,q):null,h?e.collectOrderByInfos(d,a,h):null]);a.timeInfo&&this.timeExtent&&e.collectFields(d,a.fieldsIndex,[a.timeInfo.startField,a.timeInfo.endField]);"feature"===a.type&&a.floorInfo&&e.collectFields(d,a.fieldsIndex,[a.floorInfo.floorField]);"subtype-group"===a.type&&(e.collectField(d,m,a.subtypeField),h=a.sublayers.map(t=>{var v;return Promise.all([null==(v=t.renderer)?
void 0:v.collectRequiredFields(d,m),e.collectLabelingFields(d,t)])}),yield F.eachAlways(h));for(const t of f)t.error&&y.error(t.error);e.collectField(d,m,l);c&&"displayField"in a&&a.displayField&&e.collectField(d,m,a.displayField);c=Array.from(d).sort();this._set("requiredFields",c)}});return function(){return b.apply(this,arguments)}}();k.validateFetchPopupFeatures=function(b){if(p.isNone(b))return null;for(const c of b.clientGraphics){const a=c.layer;if("popupEnabled"in a&&!a.popupEnabled)return new B("featurelayerview:fetchPopupFeatures",
"Popups are disabled",{layer:a});if("popupTemplate"in a&&!x.getFetchPopupTemplate(a,b))return new B("featurelayerview:fetchPopupFeatures","Layer does not define a popup template",{layer:a});if(c.isAggregate&&!(a.featureReduction&&"popupTemplate"in a.featureReduction&&a.featureReduction.popupEnabled&&a.featureReduction.popupTemplate))return new B("featurelayerview:fetchPopupFeatures","Popups are disabled",{layer:a})}};k.fetchClientPopupFeatures=function(){var b=u._asyncToGenerator(function*(c){const a=
p.isSome(c)?c.clientGraphics:null;if(!a||0===a.length)return[];const m=Array(a.length),l=new Map,f=yield this.createPopupQuery(c);for(let q=0;q<a.length;q++){const d=a[q];if(d.isAggregate){m[q]=d;continue}var {layer:h}=d;if(!("popupEnabled"in h))continue;const t=e.unpackFieldNames(this.layer.fieldsIndex,f.outFields);h=x.getFetchPopupTemplate(h,c);if(!p.isSome(h))continue;const v=yield this._loadArcadeModules(h);v&&v.arcadeUtils.hasGeometryOperations(h)||!e.featureHasFields(t,d)?l.set(d.getObjectId(),
q):m[q]=d}if("stream"===this.layer.type||0===l.size)return m.filter(Boolean);f.objectIds=Array.from(l.keys());try{const q=yield this.layer.queryFeatures(f);for(const d of q.features){const t=l.get(d.getObjectId());m[t]=d}}catch{}return m.filter(Boolean)});return function(c){return b.apply(this,arguments)}}();k.createPopupQuery=function(){var b=u._asyncToGenerator(function*(c){const a=this.layer.createQuery(),m=new Set;var l=!1,f=p.isSome(c)&&c.clientGraphics?c.clientGraphics.map(h=>h.layer):[this.layer];
for(const h of f)if("popupEnabled"in h&&(f=x.getFetchPopupTemplate(h,c),p.isSome(f))){l=(l=yield this._loadArcadeModules(f))&&l.arcadeUtils.hasGeometryOperations(f);l=!("point"!==this.layer.geometryType&&!l);f=yield x.getRequiredFields(this.layer,f);for(const q of f)m.add(q)}a.returnGeometry=l;a.returnZ=l;a.returnM=l;a.outFields=Array.from(m);a.outSpatialReference=this.view.spatialReference;"feature"===this.layer.type&&(c=G.getFloorFilterClause(this),p.isSome(c)&&(a.where=a.where?`(${a.where}) AND (${c})`:
c));return a});return function(c){return b.apply(this,arguments)}}();k.canResume=function(){return!D.prototype.canResume.call(this)||p.isSome(this.timeExtent)&&this.timeExtent.isEmpty?!1:!0};u._createClass(z,[{key:"availableFields",get:function(){const {layer:b,layer:{fieldsIndex:c},requiredFields:a}=this;return"outFields"in b&&b.outFields?e.fixFields(c,[...e.unpackFieldNames(c,b.outFields),...a]):e.fixFields(c,a)}},{key:"effect",get:function(){E.deprecatedProperty(y,"effect",{replacement:"featureEffect",
version:"4.22"});return this.featureEffect},set:function(b){E.deprecatedProperty(y,"effect",{replacement:"featureEffect",version:"4.22"});this.featureEffect=b}},{key:"featureEffect",get:function(){return this.layer&&"featureEffect"in this.layer?this.layer.featureEffect:null},set:function(b){void 0===b?this._clearOverride("featureEffect"):this._override("featureEffect",b)}},{key:"maximumNumberOfFeatures",get:function(){return 0},set:function(b){y.error("#maximumNumberOfFeatures\x3d","Setting maximum number of features is not supported")}},
{key:"maximumNumberOfFeaturesExceeded",get:function(){return!1}}]);return z}(g);n.__decorate([r.property()],g.prototype,"_updatingRequiredFieldsPromise",void 0);n.__decorate([r.property({readOnly:!0})],g.prototype,"availableFields",null);n.__decorate([r.property()],g.prototype,"effect",null);n.__decorate([r.property({type:J})],g.prototype,"featureEffect",null);n.__decorate([r.property({type:K})],g.prototype,"filter",void 0);n.__decorate([r.property(I.combinedViewLayerTimeExtentProperty)],g.prototype,
"timeExtent",void 0);n.__decorate([r.property()],g.prototype,"layer",void 0);n.__decorate([r.property({type:Number})],g.prototype,"maximumNumberOfFeatures",null);n.__decorate([r.property({readOnly:!0,type:Boolean})],g.prototype,"maximumNumberOfFeaturesExceeded",null);n.__decorate([r.property({readOnly:!0})],g.prototype,"requiredFields",void 0);n.__decorate([r.property()],g.prototype,"suspended",void 0);n.__decorate([r.property()],g.prototype,"view",void 0);return g=n.__decorate([H.subclass("esri.views.layers.FeatureLayerView")],
g)};A.FeatureLayerView=w;A.default=w;Object.defineProperty(A,"__esModule",{value:!0})});