// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/has ../../../../../core/mathUtils ../../../../../core/screenUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/arrayUtils ../../../../../core/accessorSupport/ensureType ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec2 ../../../../../chunks/vec2f64 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../geometry/projectionEllipsoid ../../../../../geometry/support/axisAngle ../../../../../chunks/sphere ../../../camera/constraintUtils ../InteractiveController ../../utils/navigationUtils ../../../support/geometryUtils/ray ../../../camera/constraintUtils/surfaceCollision".split(" "),
function(h,n,p,q,x,y,z,H,I,A,B,r,d,g,C,t,D,u,E,e,F,G){h.ZoomController=function(v){function k(a){a=v.call(this,a)||this;a.view=null;a.pickPoint=g.create();a.tmpP0=r.create();a.panAxisAngle=t.create();a.tmpRayDir=g.create();a.targetOnSphere=g.create();a.tmpRay={origin:g.create(),direction:g.create()};a.dragBeginPoint=y.createScreenPointArray();a.normalizedAnchorPoint=r.create();a.constraintOptions={selection:7,interactionType:1,interactionFactor:0,interactionStartCamera:null,interactionDirection:null,
tiltMode:0};a.sphere=D.create();a.hasPickPoint=!1;return a}n._inheritsLoose(k,v);var m=k.prototype;m.begin=function(a){if(this.active){B.copy(this.dragBeginPoint,a);e.normalizeCoordinate(this.startCamera,a,this.normalizedAnchorPoint);var b=C.getReferenceEllipsoid(this.view.spatialReference),f=e.pickPointAndInitSphere(this.intersectionHelper,this.startCamera,a,!1,b);this.navMode=e.decideNavigationMode(this.startCamera,a,f.hasGeometryIntersection,b);if(this.navMode===e.NavigationMode.Horizontal||q("disable-feature:context-navigation"))this.hasPickPoint=
!!f.scenePickPoint,this.pickPoint=f.scenePickPoint,this.sphere=f.sphere;else{F.fromScreenAtEye(this.startCamera,a,this.tmpRay);d.normalize(this.tmpRay.direction,this.tmpRay.direction);let c;this.view.camera.position.hasZ&&(c=Math.abs(this.view.camera.position.z));b=x.clamp(e.PIVOT_DISTANCE_MODIFIER*c,e.DISTANCE_CLAMP_VALUES[0],e.DISTANCE_CLAMP_VALUES[1]);a=this.view._stage.renderView.getMinimalDepthForArea(null,a[0],a[1],this.view.state.camera,e.SCREEN_PIXEL_AREA);b=b>a?a:b;this.hasPickPoint=!0;d.scale(this.tmpRay.direction,
this.tmpRay.direction,b);d.add(this.pickPoint,this.tmpRay.origin,this.tmpRay.direction)}this.constraintOptions.interactionStartCamera=this.startCamera}};m.update=function(a){if(this.active){this.currentCamera.eye=this.startCamera.eye;this.currentCamera.center=this.startCamera.center;this.currentCamera.up=this.startCamera.up;if(this.navMode===e.NavigationMode.Horizontal||q("disable-feature:context-navigation")){d.subtract(this.tmpRayDir,this.currentCamera.center,this.currentCamera.eye);var b=d.length(this.tmpRayDir);
e.normalizeCoordinate(this.currentCamera,a,this.tmpP0);var f=12*(this.normalizedAnchorPoint[1]-this.tmpP0[1]),c=b*2**f;const w=this.view.state.constraints.minimumPoiDistance;0>f&&c<w&&(c=w);if(1E-6>Math.abs(b-c))return;this.hasPickPoint&&c<b&&(f=1-(1-c/b)*(1-this.sphere[3]/d.length(this.currentCamera.center)),this.currentCamera.center=d.scale(l,this.currentCamera.center,f));d.scale(this.tmpRayDir,this.tmpRayDir,-c/b);this.currentCamera.eye=d.add(l,this.currentCamera.center,this.tmpRayDir);this.constraintOptions.interactionFactor=
u.pixelDistanceToInteractionFactor(this.dragBeginPoint,a);u.applyAll(this.view,this.currentCamera,this.constraintOptions);this.hasPickPoint&&(e.sphereOrPlanePointFromScreenPoint(this.sphere,this.currentCamera,this.dragBeginPoint,this.targetOnSphere),t.fromPoints(this.pickPoint,this.targetOnSphere,this.panAxisAngle),e.applyRotation(this.currentCamera,this.sphere,this.panAxisAngle))}else{b=d.length(this.tmpRay.direction);e.normalizeCoordinate(this.currentCamera,a,this.tmpP0);a=12*(this.normalizedAnchorPoint[1]-
this.tmpP0[1]);c=b*2**a;f=this.view.state.constraints.minimumPoiDistance;0>a&&c<f&&(c=f);if(1E-6>Math.abs(b-c))return;d.scale(this.tmpRayDir,this.tmpRay.direction,1-c/b);this.currentCamera.eye=d.add(l,this.currentCamera.eye,this.tmpRayDir);this.currentCamera.center=d.add(l,this.currentCamera.center,this.tmpRayDir)}G.applySurfaceCollisionConstraint(this.view,this.currentCamera)}};m.end=function(){this.active&&this.finishController()};n._createClass(k,[{key:"intersectionHelper",get:function(){return this.view.sceneIntersectionHelper}}]);
return k}(E.InteractiveController);p.__decorate([z.property({constructOnly:!0})],h.ZoomController.prototype,"view",void 0);h.ZoomController=p.__decorate([A.subclass("esri.views.3d.state.controllers.global.ZoomController")],h.ZoomController);const l=g.create();Object.defineProperty(h,"__esModule",{value:!0})});