// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/has ../../../../../core/time ../../../../../core/Logger ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/set ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../geometry/projectionEllipsoid ../../../../../chunks/sphere ../../../camera/constraintUtils ../PointToPointAnimationController ../../utils/navigationUtils ../../../support/geometryUtils/ray ../../../support/geometryUtils/sphere ../../../webgl-engine/lib/Camera ../../../webgl-engine/lib/Intersector ../../../../animation/easing ../../../camera/constraintUtils/surfaceCollision".split(" "),
function(l,u,v,w,x,I,J,K,L,y,d,k,z,A,B,C,p,D,E,r,F,G,H){l.ZoomStepController=function(t){function q(){var a=t.apply(this,arguments)||this;a.zoomLocation=k.create();a.tmpCamera=new r;a.tmpViewDir=k.create();a.tmpRayDir={origin:k.create(),direction:k.create()};a.targetOnSphere=k.create();a.tmpCenter=k.create();a.constraintOptions={selection:7,interactionType:1,interactionFactor:null,interactionStartCamera:new r,interactionDirection:null,tiltMode:0};a.sphere=A.create();return a}u._inheritsLoose(q,t);
var m=q.prototype;m.initialize=function(){this.intersector=F.newIntersector(this.view.state.viewingMode)};m.zoomStep=function(a,e){if(this.active){var f=this.view.state,{interactionStartCamera:b}=this.constraintOptions;this.animation.finished?b.copyFrom(f.camera):this.animation.cameraAt(1,b);var c=b=!1;this.intersectionHelper.intersectScreen(e,this.zoomLocation)&&(b=0<a?!0:!1,c=!0);this.tmpCamera.copyFrom(f.camera);b?this.intersectionHelper.intersectRay(this.tmpCamera.ray,this.intersector,this.tmpCenter)&&
(this.tmpCamera.center=this.tmpCenter):this.intersectionHelper.intersectRay(this.tmpCamera.ray,this.intersector,this.zoomLocation)?this.tmpCamera.center=this.zoomLocation:d.copy(this.zoomLocation,this.tmpCamera.center);this.updateCamera(this.tmpCamera,a,this.zoomLocation,e,c);this.begin(this.tmpCamera)}};m.animationSettings=function(){return{apex:null,duration:x.Milliseconds(600),easing:G.outExpo}};m.updateCamera=function(a,e,f,b,c){var h=z.getReferenceEllipsoid(this.view.spatialReference);if(p.decideNavigationMode(a,
b,c,h)===p.NavigationMode.Horizontal||w("disable-feature:context-navigation")){e=.6**e;this.sphere[3]=d.length(f);d.subtract(this.tmpViewDir,a.center,a.eye);c=d.length(this.tmpViewDir);h=c*e;1>=e&&4>h&&(h=4,e=h/c);if(1E-6>Math.abs(c-h))return;c=d.length(a.center);this.sphere[3]!==c&&(a.center=d.scale(n,a.center,(this.sphere[3]+e*(c-this.sphere[3]))/c));d.scale(this.tmpViewDir,this.tmpViewDir,-e);a.eye=d.add(n,a.center,this.tmpViewDir);B.applyAll(this.view,a,this.constraintOptions);1E-12<d.squaredDistance(f,
a.center)&&E.intersectScreen(this.sphere,a,b,this.targetOnSphere)&&p.panToPosition(this.sphere,a,f,this.targetOnSphere,this.view.camera.heading,this.view.camera.tilt,!0)}else{c=.6**Math.abs(e);h=0<e?1:-1;D.fromScreenAtEye(a,b,this.tmpRayDir);d.normalize(this.tmpRayDir.direction,this.tmpRayDir.direction);var g;this.view.camera.position.hasZ&&(g=Math.abs(this.view.camera.position.z));g=Math.max(12*g,20);b=this.view._stage.renderView.getMinimalDepthForArea(null,b[0],b[1],this.view.state.camera,60);g=
g>b?b:g;d.scale(this.tmpRayDir.direction,this.tmpRayDir.direction,g);d.add(f,this.tmpRayDir.origin,this.tmpRayDir.direction);f=g*c;b=Math.max(4,1.01*a.nearFar[0]);0<e&&f<b&&(f=b,c=f/g);if(1E-6>Math.abs(g-f))return;d.scale(this.tmpRayDir.direction,this.tmpRayDir.direction,h*(1-c));a.eye=d.add(n,a.eye,this.tmpRayDir.direction);a.center=d.add(n,a.center,this.tmpRayDir.direction)}H.applySurfaceCollisionConstraint(this.view,a)};return q}(C.PointToPointAnimationController);l.ZoomStepController=v.__decorate([y.subclass("esri.views.3d.state.controllers.global.ZoomStepController")],
l.ZoomStepController);const n=k.create();Object.defineProperty(l,"__esModule",{value:!0})});