// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../geometry ../../../../core/Accessor ../../../../core/Evented ../../../../core/Handles ../../../../core/handleUtils ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/projection ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/ray ./LineOfSightAnalysis ./LineOfSightRayIntersector ./LineOfSightResult ../../support/ElevationProvider ../../webgl-engine/lib/intersectorUtilsConversions ../../../support/Scheduler ../../../support/WatchUpdatingTracking ../../../../geometry/Point".split(" "),
function(l,F,n,da,S,T,I,u,f,J,h,p,ea,fa,ha,U,g,x,V,K,L,W,X,Y,Z,M,A,aa,ba){function N(y,r,d){if(f.isNone(d))return!1;V.projectBoundingRect(y,r,O,d.spatialReference);return K.containsPointObject(O,d)}function P(y,r){return f.isNone(r)||f.isSome(y)&&y.equals(r.point)}l.LineOfSightController=function(y){function r(a){a=y.call(this,a)||this;a._updatingHandles=new aa.WatchUpdatingTracking;a._frameTask=A.ImmediateTask;a._handles=new I;a._analysisHandles=new I;return a}F._inheritsLoose(r,y);var d=r.prototype;
d.initialize=function(){var a;const b=null==(a=this.view.resourceController)?void 0:a.scheduler;b&&(this._frameTask=b.registerTask(A.TaskPriority.LINE_OF_SIGHT_TOOL));this._handles.add([this._connectObserver(),this._connectAnalyses(),this._connectTargets()]);this._intersector=new X.LineOfSightRayIntersector({view:this.view})};d.destroy=function(){this._handles.destroy();this._analysisHandles.destroy();this._analyses.removeAll();this._updatingHandles.destroy()};d.getLineOfSightComputationDependencies=
function(a){({inputPoints:a}=a);return{inputPoints:a}};d.computeAnalysis=function(a){const b=a.analysis,{inputPoints:c,computationResult:e}=b,{observerAdjusted:q,targetAdjusted:k}=c,{start:m,end:t}=e;g.copy(m,q);g.copy(t,k);this._canComputeAnalysis(b)?this._computeAnalysisIntersection(a):this._interpolateAnalysisIntersection(a);b.updateComputationResults();this.emit("result-changed",{target:a.analysis.target,result:b.result})};d._adjustStartEndPositions=function(a){var b=this._screenPixelSize;const c=
this.view;({inputPoints:a}=a);const {observer:e,observerSurfaceNormal:q,target:k,targetSurfaceNormal:m,observerAdjusted:t,targetAdjusted:v}=a;a=D;f.isSome(q)?g.copy(a,q):g.subtract(a,k,e);g.normalize(a,a);g.scale(a,a,Math.min(b,1));g.add(t,e,a);f.isSome(m)?g.copy(a,m):g.subtract(a,e,k);b=c.state.camera.computeScreenPixelSizeAt(k);g.normalize(a,a);g.scale(a,a,Math.min(b,1));g.add(v,k,a)};d._computeAnalysisIntersection=function({analysis:a,interpolationInfo:b}){const {view:c}=this,{sceneIntersectionHelper:e,
renderCoordsHelper:q}=c;if(!f.isNone(e)){var k=this._intersector.intersector,{computationResult:m,inputPoints:t}=a,{observer:v,target:z}=t,{start:G,end:H}=m,B=L.fromPoints(G,H,ca);e.intersectToolIntersectorRay(B,k);var E=m.intersection,Q=D;B=k.results.min.getIntersectionPoint(E);var w=!0;B&&(g.copy(b.originalIntersection,E),g.copy(b.originalObserver,G),g.copy(b.originalTarget,H),q.fromRenderCoords(E,Q,c.spatialReference),b=1-g.dist(H,z)/g.dist(G,z),w=g.dist(v,E)>=b*g.dist(v,z));b=new ba(Q,c.spatialReference);
{const {result:C,target:R}=a;f.isSome(C)?(C.target=R,C.intersectedGraphic=w?null:M.toGraphic(k.results.min,c),C.intersectedLocation=w?null:b,C.visible=B?w:!1):a.result=new Y.LineOfSightResult({target:R,elevationAlignedTargetLocation:a.elevationAlignedTargetLocation,intersectedGraphic:w?null:M.toGraphic(k.results.min,c),intersectedLocation:w?null:b,visible:B?w:!1})}m.isValid=t.isValid=!0;m.isTargetVisible=w}};d._interpolateAnalysisIntersection=function({analysis:a,interpolationInfo:b}){const {computationResult:c,
inputPoints:e}=a,{start:q,end:k,intersection:m}=c,{originalIntersection:t,originalObserver:v,originalTarget:z}=b;g.copy(m,t);e.isValid?(a=D,b=g.dist(v,t)/g.dist(v,z),g.sub(a,q,v),g.scale(a,a,1-b),g.add(m,m,a),g.sub(a,k,z),g.scale(a,a,b),g.add(m,m,a),c.isValid=!0):(a.result=null,c.isValid=!1,c.isTargetVisible=!1)};d._canComputeAnalysis=function(a){var b=this.view.frustum;if(f.isNone(this.analysisViewData.elevationAlignedObserver)||f.isNone(a.target)||f.isNone(b))return!1;const {observerAdjusted:c,
targetAdjusted:e}=a.inputPoints;a=b.intersectsPoint(c);b=b.intersectsPoint(e);return a&&b};d._onObserverChange=function(a,b){f.isNone(a)?(this.analysis.targets.removeAll(),this.analysisViewData.elevationAlignedObserver=null):(this.analysisViewData.elevationAlignedObserver=this._applyElevationAlignment(a,b),a=x.create(),this.view.renderCoordsHelper.toRenderCoords(this.analysisViewData.elevationAlignedObserver,a),this._observerEngineLocation=a,this.priority=A.TaskPriority.LINE_OF_SIGHT_TOOL_INTERACTIVE)};
d._applyElevationAlignment=function(a,b){if(a.hasZ&&(f.isNone(b)||0===b.type))return a;a=a.clone();a.z=f.unwrapOr(Z.getElevationAtPoint(this.view.elevationProvider,a),0);return a};d._onObserverChangeForAnalysis=function(a){a.inputPoints.isValid=!1};d._onObserverEngineForAnalysis=function(a,b,c){const {inputPoints:e}=a;g.copy(e.observer,b);f.isSome(c)?(b=this._intersector.updateFromIntersectionResult(c),f.isSome(b)&&this.view.renderCoordsHelper.toRenderCoords(b,e.observer),e.observerSurfaceNormal=
x.clone(c.normal)):e.observerSurfaceNormal=null;this._adjustStartEndPositions(a);a.updateInputPoints();this.priority=A.TaskPriority.LINE_OF_SIGHT_TOOL_INTERACTIVE};d._onTargetLocationChange=function(a,b,c){const e=a.inputPoints;e.isValid=!1;f.isSome(b)&&(a.elevationAlignedTargetLocation=this._applyElevationAlignment(b,c),this.view.renderCoordsHelper.toRenderCoords(a.elevationAlignedTargetLocation,e.target),f.isSome(c)?(b=this._intersector.updateFromIntersectionResult(c),f.isSome(b)&&this.view.renderCoordsHelper.toRenderCoords(b,
e.target),e.targetSurfaceNormal=x.clone(c.normal)):e.targetSurfaceNormal=null,this._adjustStartEndPositions(a),a.updateInputPoints());this.priority=A.TaskPriority.LINE_OF_SIGHT_TOOL_INTERACTIVE};d._connectAnalysisToTarget=function(a){return u.handlesGroup([h.react(()=>a.target.location,b=>{P(b,a.target.intersection)||(a.target.intersection=null)},h.initial),h.react(()=>({analysis:a,targetLocation:a.target.location,targetIntersection:a.target.intersection}),({analysis:b,targetLocation:c,targetIntersection:e})=>
{f.isSome(c)&&this._onTargetLocationChange(b,c,e)},h.syncAndInitial)])};d._connectAnalysisToObserver=function(a){return h.react(()=>({analysis:a,observer:this.analysisViewData.elevationAlignedObserver}),({analysis:b})=>{this._onObserverChangeForAnalysis(b)},h.syncAndInitial)};d._connectAnalysisToObserverEngine=function(a){return h.react(()=>({analysis:a,observer:this._observerEngineLocation,observerIntersection:this.analysis.intersection}),({analysis:b,observer:c,observerIntersection:e})=>{this._onObserverEngineForAnalysis(b,
c,e)},h.syncAndInitial)};d._connectAnalysisToCamera=function(a){return h.react(()=>({camera:this.view.state.camera,isDirty:this._isCameraDirty}),({isDirty:b})=>{a.inputPoints.isValid&&!b||a.updateInputPoints()},h.sync)};d._connectAnalysisToElevation=function(a){return this.view.elevationProvider.on("elevation-change",b=>{if(this._canComputeAnalysis(a)){var c=this.analysis.observer;N(b.extent,b.spatialReference,c)&&this._onObserverChange(c,this.analysis.intersection);c=a.target;if(f.isSome(c)&&N(b.extent,
b.spatialReference,c.location))a.onElevationChange()}})};d._connectAnalysisForCompute=function(a){var b=this;let c=f.none;const e={analysis:a,interpolationInfo:{originalIntersection:x.create(),originalObserver:x.create(),originalTarget:x.create()}};return u.handlesGroup([h.react(()=>this.getLineOfSightComputationDependencies(a),()=>{c=f.abortMaybe(c);c=J.createTask(function(){var q=F._asyncToGenerator(function*(k){yield J.ignoreAbortErrors(b._frameTask.schedule(()=>b.computeAnalysis(e),k))});return function(k){return q.apply(this,
arguments)}}())},h.syncAndInitial),u.makeHandle(()=>c=f.abortMaybe(c))])};d._connectAnalysis=function(a){const b=this._analysisHandles;b.has(a)||b.add([this._connectAnalysisToTarget(a),this._connectAnalysisToObserver(a),this._connectAnalysisToObserverEngine(a),this._connectAnalysisToCamera(a),this._connectAnalysisToElevation(a),this._connectAnalysisForCompute(a)],a)};d._disconnectAnalysis=function(a){this._analysisHandles.remove(a)};d._onAnalysesCollectionChange=function(a){a.added.forEach(b=>this._connectAnalysis(b));
a.removed.forEach(b=>this._disconnectAnalysis(b))};d._onTargetsChange=function(){this._analyses.removeAll();this.analysis.targets.forEach(a=>this._addTarget(a));return this._updatingHandles.addOnCollectionPropertyChange(this.analysis,"targets",a=>this._onTargetCollectionChange(a))};d._onTargetCollectionChange=function(a){a.added.forEach(b=>this._addTarget(b));a.removed.forEach(b=>this._removeTarget(b))};d._onCursorTargetChange=function(a,b){f.isSome(b)&&this._removeTarget(b);f.isSome(a)&&this._addTarget(a)};
d._addTarget=function(a){this._analyses.some(b=>b.target===a)||this._analyses.add(new W.LineOfSightAnalysis({target:a}))};d._removeTarget=function(a){const b=this._analyses.find(c=>c.target===a);this._analyses.remove(b)};d._connectObserver=function(){return u.handlesGroup([h.react(()=>this.analysis.observer,a=>{P(a,this.analysis.intersection)||(this.analysis.intersection=null)},h.initial),h.react(()=>({observer:this.analysis.observer,intersection:this.analysis.intersection}),({observer:a,intersection:b})=>
this._onObserverChange(a,b),h.syncAndInitial)])};d._connectAnalyses=function(){let a=null;return u.handlesGroup([h.react(()=>this._analyses,()=>{f.removeMaybe(a);a=this._updatingHandles.addOnCollectionPropertyChange(this,"_analyses",b=>this._onAnalysesCollectionChange(b));this._analyses.forEach(b=>this._connectAnalysis(b))},h.syncAndInitial),u.makeHandle(()=>a=f.removeMaybe(a))])};d._connectTargets=function(){let a=null;return u.handlesGroup([h.react(()=>this.analysis.targets,()=>{a=f.removeMaybe(a);
a=this._onTargetsChange()},h.syncAndInitial),h.react(()=>this.analysisViewData.cursorTarget,(b,c)=>{this._onCursorTargetChange(b,c)}),u.makeHandle(()=>{a=f.removeMaybe(a)})])};F._createClass(r,[{key:"updating",get:function(){return this._frameTask.updating||this._updatingHandles.updating}},{key:"priority",get:function(){return this._frameTask.priority},set:function(a){this._frameTask.priority=a}},{key:"_analyses",get:function(){return this.analysisViewData.analyses}},{key:"_observerEngineLocation",
get:function(){return this.analysisViewData.observerEngineLocation},set:function(a){this.analysisViewData.observerEngineLocation=a}},{key:"_screenPixelSize",get:function(){return this.view.state.camera.computeScreenPixelSizeAt(this._observerEngineLocation)}},{key:"_isCameraDirty",get:function(){var a=this.analysisViewData.elevationAlignedObserver;const {view:b}=this,{renderCoordsHelper:c}=b;if(f.isNone(a)||f.isNone(c))return!1;const e=D;c.toRenderCoords(a,e);a=b.state.camera.computeScreenPixelSizeAt(e);
return.1<Math.abs((a-this._screenPixelSize)/this._screenPixelSize)}}]);return r}(T.EventedMixin(S));n.__decorate([p.property({constructOnly:!0})],l.LineOfSightController.prototype,"analysis",void 0);n.__decorate([p.property({constructOnly:!0})],l.LineOfSightController.prototype,"analysisViewData",void 0);n.__decorate([p.property({constructOnly:!0})],l.LineOfSightController.prototype,"view",void 0);n.__decorate([p.property()],l.LineOfSightController.prototype,"updating",null);n.__decorate([p.property()],
l.LineOfSightController.prototype,"priority",null);n.__decorate([p.property()],l.LineOfSightController.prototype,"_analyses",null);n.__decorate([p.property()],l.LineOfSightController.prototype,"_observerEngineLocation",null);n.__decorate([p.property()],l.LineOfSightController.prototype,"_screenPixelSize",null);n.__decorate([p.property({readOnly:!0})],l.LineOfSightController.prototype,"_updatingHandles",void 0);n.__decorate([p.property()],l.LineOfSightController.prototype,"_frameTask",void 0);n.__decorate([p.property()],
l.LineOfSightController.prototype,"_isCameraDirty",null);l.LineOfSightController=n.__decorate([U.subclass("esri.views.3d.analysis.LineOfSight.LineOfSightController")],l.LineOfSightController);const D=x.create(),ca=L.create(),O=K.empty();Object.defineProperty(l,"__esModule",{value:!0})});