// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/Evented ../../../core/Handles ../../../core/Logger ../../../core/MapUtils ../../../core/maybe ../../../core/PooledArray ../../../core/SetUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../chunks/mat4 ../../../chunks/vec2f64 ../../../chunks/vec3f64 ../../../chunks/mat4f64 ../support/debugFlags ./Overlay ./OverlayFramebufferObject ./OverlayRenderTarget ../webgl-engine/core/shaderTechnique/ShaderTechniqueRepository ../webgl-engine/lib/AutoDisposable ../webgl-engine/lib/Camera ../webgl-engine/lib/GLMaterialRepository ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/GridLocalOriginFactory ../webgl-engine/lib/Intersector ../webgl-engine/lib/RenderContext ../webgl-engine/lib/SortedRenderGeometryRenderer ../webgl-engine/lib/TextureTechnique ../webgl-engine/lighting/Lightsources ../webgl-engine/lighting/SceneLighting ../webgl-engine/materials/StippleTextureRepository ../../support/Scheduler ../../webgl/Texture ../../webgl/Util".split(" "),
function(l,A,n,O,P,Q,R,u,f,S,T,B,v,pa,qa,ra,U,C,V,D,W,H,I,X,Y,Z,E,aa,ba,J,ca,da,ea,fa,K,ha,ia,ja,F,ka,la){function ma(p,m,e,a,b,c,d){const g={layerUid:c,graphicUid:d,triangleNr:m};m=h=>{h.set(3,g,p.dist,p.normal,p.transformation,e,a)};(null==b.results.min.drapedLayerOrder||e>=b.results.min.drapedLayerOrder)&&(null==b.results.min.dist||b.results.ground.dist<=b.results.min.dist)&&m(b.results.min);0!==b.options.store&&(null==b.results.max.drapedLayerOrder||e<b.results.max.drapedLayerOrder)&&(null==b.results.max.dist||
b.results.ground.dist>b.results.max.dist)&&m(b.results.max);2===b.options.store&&(c=da.newIntersectorResult(b.ray),m(c),b.results.all.push(c))}const L=R.getLogger("esri.views.3d.webgl-engine.lib.OverlayRenderer");l.OverlayRenderer=function(p){function m(a){a=p.call(this,a)||this;a._overlays=null;a._overlayRenderTarget=null;a._hasHighlights=!1;a._rendersOccluded=!1;a._hasWater=!1;a._lighting=new ia.SceneLighting;a._handles=new Q;a._frameTask=F.ImmediateTask;a._layerRenderers=new Map;a._sortedLayerRenderersDirty=
!1;a._sortedLayerRenderers=new S;a._geometries=new Map;a.worldToPCSRatio=1;a.events=new P;a.longitudeCyclical=null;return a}A._inheritsLoose(m,p);var e=m.prototype;e.initialize=function(){const a=this.view._stage.renderView;this._rctx=a.renderingContext;this._renderContext=new ea.OverlayRenderContext(this._rctx);const b=a.waterTextureRepository;this._stippleTextureRepository=new ja.StippleTextureRepository(a.renderingContext);this._shaderTechniqueRepository=new Z.ShaderTechniqueRepository({rctx:this._rctx,
viewingMode:2,stippleTextureRepository:this._stippleTextureRepository,waterTextureRepository:b});this._handles.add([B.init(b,"loadingState",()=>this.events.emit("content-changed")),B.init(this,"spatialReference",c=>this._localOrigins=new ca.GridLocalOriginFactory(c))]);this._materialRepository=new ba.GLMaterialRepository(a.textureRepository,this._shaderTechniqueRepository,c=>{0<(c.renderOccluded&4)!==this._rendersOccluded&&this.updateRendersOccluded();this.events.emit("content-changed");this.notifyChange("updating")},
()=>this.events.emit("content-changed"));this._lighting.groundLightingFactor=1;this._lighting.globalFactor=0;this._lighting.set([new ha.AmbientLight(D.fromValues(1,1,1))]);this._bindParameters={slot:20,highlightDepthTexture:J.createEmptyDepthTexture(this._rctx),camera:r,inverseViewport:V.create(),origin:null,screenToWorldRatio:null,screenToPCSRatio:null,shadowMappingEnabled:!1,slicePlane:null,ssaoEnabled:!1,hasOccludees:!1,linearDepthTexture:null,lastFrameColorTexture:null,reprojectionMatrix:W.IDENTITY,
ssrEnabled:!1,lighting:this._lighting,transparencyPassType:3,terrainLinearDepthTexture:null,geometryLinearDepthTexture:null,multipassTerrainEnabled:!1,cullAboveGround:!1,multipassGeometryEnabled:!1,highlightColorTexture:null};this._frameTask=this.view.resourceController.scheduler.registerTask(F.TaskPriority.STAGE,this);this._handles.add(this._frameTask)};e.dispose=function(){this._handles.destroy();this._layerRenderers.forEach(a=>a.dispose());this._layerRenderers.clear();this._debugTextureTechnique=
f.releaseMaybe(this._debugTextureTechnique);this._debugPatternTexture=f.disposeMaybe(this._debugPatternTexture);this._bindParameters.highlightDepthTexture=f.disposeMaybe(this._bindParameters.highlightDepthTexture);this._shaderTechniqueRepository=f.disposeMaybe(this._shaderTechniqueRepository);this._temporaryFBO=f.disposeMaybe(this._temporaryFBO);this._quadVAO=f.disposeMaybe(this._quadVAO);this.disposeOverlays()};e.collectUnusedRenderTargetMemory=function(a){let b=!1;if(f.isSome(this._overlayRenderTarget))for(const c of this._overlayRenderTarget.renderTargets)b=
this._overlayRenderTarget.validateUsageForTarget(this.overlays[0].validTargets[c.type]||!this.overlays[1].validTargets[c.type],c,a)||b;return b};e.ensureDrapeTargets=function(a){f.isSome(this._overlays)&&this._overlays.forEach(b=>{b.hasTargetWithoutRasterImage=T.someSet(a,c=>1===c.drapeTargetType)})};e.ensureDrapeSources=function(a){f.isSome(this._overlays)&&this._overlays.forEach(b=>{b.hasDrapedFeatureSource=u.someMap(a,(c,d)=>1===d.drapeSourceType);b.hasDrapedRasterSource=u.someMap(a,(c,d)=>0===
d.drapeSourceType)})};e.ensureOverlays=function(a,b){f.isNone(this._overlays)&&(this._overlayRenderTarget=new Y.OverlayRenderTarget(this._rctx),this._overlays=[new I.Overlay(0,this._overlayRenderTarget),new I.Overlay(1,this._overlayRenderTarget)]);this.ensureDrapeTargets(a);this.ensureDrapeSources(b)};e.disposeOverlays=function(){this._overlays=null;this._overlayRenderTarget=f.disposeMaybe(this._overlayRenderTarget);this.events.emit("textures-disposed")};e.runTask=function(a,b=()=>!0){this._frameTask.processQueue(a);
a.done||this._processLayers(a,b)};e._processLayers=function(a,b){let c=!1;for(const [d,g]of this._layerRenderers){if(a.done)break;if(d.destroyed||b(d))g.commitChanges()&&(c=!0,a.madeProgress()),g.isEmpty&&(this._sortedLayerRenderersDirty=c=!0,this._layerRenderers.delete(d),this._handles.remove(d))}this.updateSortedLayerRenderers();c&&(f.isSome(this._overlays)&&0===this._layerRenderers.size&&this.disposeOverlays(),this.notifyChange("updating"),this.events.emit("content-changed"),this.updateHasHighlights(),
this.updateRendersOccluded(),this.updateHasWater())};e.processSyncLayers=function(){this._processLayers(F.noBudget,a=>1===a.updatePolicy)};e.addGeometries=function(a,b,c){for(const d of a)f.isNone(d.origin)&&(d.origin=this._localOrigins.getOrigin(d.boundingSphere)),this._geometries.set(d.id,d);this.ensureLayerRenderer(b).add(a);2===c&&this.notifyGraphicGeometryChanged(a,b)};e.removeGeometries=function(a,b,c){for(var d of a)this._geometries.delete(f.unwrap(d.id));if(d=this._layerRenderers.get(b))d.remove(a),
2===c&&this.notifyGraphicGeometryChanged(a,b)};e.updateGeometries=function(a,b,c){const d=this._layerRenderers.get(b);if(d)switch(d.modify(a,c),c){case 4:case 2:return this.notifyGraphicGeometryChanged(a,b);case 1:return this.notifyGraphicVisibilityChanged(a,b)}else L.warn("Attempted to update geometry for nonexistent layer")};e.notifyGraphicGeometryChanged=function(a,b){if(!f.isNone(b.notifyGraphicGeometryChanged))for(const d of a)if(a=d.graphicUid,f.isSome(a)&&a!==c){b.notifyGraphicGeometryChanged(a);
var c=a}};e.notifyGraphicVisibilityChanged=function(a,b){if(!f.isNone(b.notifyGraphicVisibilityChanged))for(const d of a)if(a=d.graphicUid,f.isSome(a)&&a!==c){b.notifyGraphicVisibilityChanged(a);var c=a}};e.updateHighlights=function(a,b){(b=this._layerRenderers.get(b))?b.modify(a,8):L.warn("Attempted to update highlights for nonexistent layer")};e.isEmpty=function(){return 0===this._geometries.size&&!H.OVERLAY_DRAW_DEBUG_TEXTURE};e.updateLogic=function(a){let b=!1;this._layerRenderers.forEach(c=>
b=c.updateLogic(a)||b);return b};e.updateLayerOrder=function(){this._sortedLayerRenderersDirty=!0};e.drawTarget=function(a,b,c){const d=a.canvasGeometries;if(0===d.numViews)return!1;this._screenToWorldRatio=c*a.mapUnitsPerPixel;const g=b.renderPass;if(this.isEmpty()||5===g&&!this.hasHighlights||3===g&&!this.hasWater||!a.hasSomeSizedView())return!1;const h=b.fbo;if(!h.isValid())return!1;const k=2*a.resolution,q=a.resolution;h.resize(k,q);const t=this._rctx;r.pixelRatio=a.pixelRatio*c;this._renderContext.pass=
g;this._bindParameters.screenToWorldRatio=this._screenToWorldRatio;this._bindParameters.screenToPCSRatio=this._screenToWorldRatio*this.worldToPCSRatio;this._bindParameters.slot=3===g?21:20;a.applyViewport(this._rctx);h.bind(t);0===a.index&&(t.setClearColor(0,0,0,0),t.clearSafe(16384));const x=1===b.type?2:4===b.type?1:0;1===x&&(this._renderContext.renderOccludedMask=4);if(H.OVERLAY_DRAW_DEBUG_TEXTURE&&1!==x)for(b=0;b<d.numViews;b++)this.setViewParameters(d.extents[b],a,r),this.drawDebugTexture(a.resolution,
na[a.index]);0<this._layerRenderers.size&&this._sortedLayerRenderers.forAll(({layerView:w,renderer:oa})=>{if(2!==x||!f.isSome(w)||0!==w.drapeSourceType){var M=f.isSome(w)&&f.isSome(w.fullOpacity)&&1>w.fullOpacity&&0===g;M&&(this.bindTemporaryFramebuffer(this._rctx,k,q),t.clearSafe(16384));for(let G=0;G<d.numViews;G++)this.setViewParameters(d.extents[G],a,r),oa.render(this._renderContext,this._bindParameters);M&&f.isSome(this._temporaryFBO)&&(h.bind(t),this.view._stage.renderView.compositingHelper.composite(this._temporaryFBO.getTexture(),
2,f.unwrap(f.unwrap(w).fullOpacity),3,a.index))}});t.bindFramebuffer(null);h.generateMipMap();this._renderContext.resetRenderOccludedMask();return!0};e.bindTemporaryFramebuffer=function(a,b,c){f.isNone(this._temporaryFBO)&&(this._temporaryFBO=new X.OverlayFramebufferObject(a,!1));this._temporaryFBO.resize(b,c);this._temporaryFBO.bind(a)};e.reloadShaders=function(){var a=A._asyncToGenerator(function*(){yield this._shaderTechniqueRepository.reloadAll()});return function(){return a.apply(this,arguments)}}();
e.intersect=function(a,b,c,d){let g=0;this._geometries.forEach(h=>{if(!d||d(h)){this._intersectRenderGeometry(h,c,b,0,a,g);var k=this.longitudeCyclical;k&&(h.boundingSphere[0]-h.boundingSphere[3]<k.min&&this._intersectRenderGeometry(h,c,b,k.range,a,g),h.boundingSphere[0]+h.boundingSphere[3]>k.max&&this._intersectRenderGeometry(h,c,b,-k.range,a,g));g++}})};e._intersectRenderGeometry=function(a,b,c,d,g,h){if(a.instanceParameters.visible){var k=0;f.isSome(a.transformation)&&(d+=a.transformation[12],
k=a.transformation[13]);y[0]=c[0]-d;y[1]=c[1]-k;y[2]=1;z[0]=c[0]-d;z[1]=c[1]-k;z[2]=0;a.screenToWorldRatio=this._screenToWorldRatio;a.material.intersect(a,null,a.getShaderTransformation(),g,y,z,(q,t,x)=>{ma(b,x,a.material.renderPriority,h,g,a.layerUid,a.graphicUid)},a.calculateShaderTransformation,b)}};e.ensureLayerRenderer=function(a){let b=this._layerRenderers.get(a);b||(b=new fa.SortedRenderGeometryRenderer({rctx:this._rctx,materialRepository:this._materialRepository}),this._layerRenderers.set(a,
b),this._sortedLayerRenderersDirty=!0,"fullOpacity"in a&&this._handles.add(a.watch("fullOpacity",()=>this.events.emit("content-changed")),a),this._handles.add(B.init(b,"updating",()=>this.notifyChange("updating")),a));return b};e.updateSortedLayerRenderers=function(){if(this._sortedLayerRenderersDirty&&(this._sortedLayerRenderersDirty=!1,this._sortedLayerRenderers.clear(),0!==this._layerRenderers.size)){var a=new Set(this._layerRenderers.values());this.view.allLayerViews.forEach(b=>{const c=this._layerRenderers.get(b);
c&&(this._sortedLayerRenderers.push(new N(b,c)),a.delete(c))});a.forEach(b=>this._sortedLayerRenderers.push(new N(null,b)))}};e.setViewParameters=function(a,b,c){c.viewport[0]=c.viewport[1]=0;c.viewport[2]=c.viewport[3]=b.resolution;C.ortho(c.projectionMatrix,0,a[2]-a[0],0,a[3]-a[1],c.near,c.far);C.identity(c.viewMatrix);C.translate(c.viewMatrix,c.viewMatrix,[-a[0],-a[1],0]);this._renderContext.camera=c;this._bindParameters.camera=c;this._bindParameters.inverseViewport[0]=1/c.fullViewport[2];this._bindParameters.inverseViewport[1]=
1/c.fullViewport[3]};e.updateHasWater=function(){const a=u.someMap(this._layerRenderers,b=>b.hasWater);a!==this._hasWater&&(this._hasWater=a,this.events.emit("has-water",a))};e.updateHasHighlights=function(){const a=u.someMap(this._layerRenderers,b=>b.hasHighlights);a!==this._hasHighlights&&(this._hasHighlights=a,this.events.emit("has-highlights",a))};e.updateRendersOccluded=function(){const a=u.someMap(this._layerRenderers,b=>b.rendersOccluded);a!==this._rendersOccluded&&(this._rendersOccluded=a,
this.events.emit("renders-occluded",a))};e.drawDebugTexture=function(a,b){const c=this._rctx;this.ensureDebugPatternResources(a,a);a=this._debugTextureTechnique.program;c.useProgram(a);this._debugTextureTechnique.bindPipelineState(c);a.setUniform4f("color",b[0],b[1],b[2],1);a.bindTexture(this._debugPatternTexture,"tex");c.bindVAO(this._quadVAO);c.drawArrays(5,0,la.vertexCount(this._quadVAO,"geometry"))};e.ensureDebugPatternResources=function(a,b){if(!this._debugPatternTexture){var c=new Uint8Array(a*
b*4),d=0;for(let g=0;g<b;g++)for(let h=0;h<a;h++){const k=Math.floor(h/10),q=Math.floor(g/10);2>k||2>q||10*k>a-20||10*q>b-20?(c[d++]=255,c[d++]=255,c[d++]=255,c[d++]=255):(c[d++]=255,c[d++]=255,c[d++]=255,k&1&&q&1?c[d++]=h&1^g&1?0:255:c[d++]=k&1^q&1?0:128)}this._debugPatternTexture=new ka(this._rctx,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:a,height:b},c);a=new K.TextureTechniqueConfiguration;a.hasAlpha=!0;this._debugTextureTechnique=this._shaderTechniqueRepository.acquire(K.TextureTechnique,
a);this._quadVAO=J.createQuadVAO(this._rctx)}};A._createClass(m,[{key:"updating",get:function(){return this._sortedLayerRenderersDirty||this._frameTask.updating||u.someMap(this._layerRenderers,a=>a.updating)}},{key:"hasOverlays",get:function(){return f.isSome(this._overlays)&&f.isSome(this._overlayRenderTarget)}},{key:"gpuMemoryUsage",get:function(){return f.isSome(this._overlayRenderTarget)?this._overlayRenderTarget.gpuMemoryUsage:0}},{key:"overlays",get:function(){return f.unwrapOr(this._overlays,
[])}},{key:"running",get:function(){return this.updating}},{key:"hasHighlights",get:function(){return this._hasHighlights}},{key:"hasWater",get:function(){return this._hasWater}},{key:"rendersOccluded",get:function(){return this._rendersOccluded}},{key:"test",get:function(){return{layerRenderers:this._layerRenderers}}}]);return m}(E.AutoDisposableMixin(O));n.__decorate([v.property()],l.OverlayRenderer.prototype,"_frameTask",void 0);n.__decorate([v.property()],l.OverlayRenderer.prototype,"_sortedLayerRenderersDirty",
void 0);n.__decorate([E.autoDispose()],l.OverlayRenderer.prototype,"_shaderTechniqueRepository",void 0);n.__decorate([E.autoDispose()],l.OverlayRenderer.prototype,"_stippleTextureRepository",void 0);n.__decorate([v.property({constructOnly:!0})],l.OverlayRenderer.prototype,"view",void 0);n.__decorate([v.property()],l.OverlayRenderer.prototype,"worldToPCSRatio",void 0);n.__decorate([v.property()],l.OverlayRenderer.prototype,"spatialReference",void 0);n.__decorate([v.property({type:Boolean,readOnly:!0})],
l.OverlayRenderer.prototype,"updating",null);l.OverlayRenderer=n.__decorate([U.subclass("esri.views.3d.terrain.OverlayRenderer")],l.OverlayRenderer);let N=function(p,m){this.layerView=p;this.renderer=m};const na=[[1,.5,.5],[.5,.5,1]],r=new aa;r.near=1;r.far=1E4;r.relativeElevation=null;const y=D.create(),z=D.create();l.DRAPED_Z=-2;l.overlayRenderOccludedFlag=4;Object.defineProperty(l,"__esModule",{value:!0})});