// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../core/mathUtils ../../../core/maybe ../../../chunks/vec3f64 ../../../chunks/vec4 ../../../chunks/vec4f64 ../../../geometry/support/aaBoundingBox ../../../geometry/support/buffer/BufferPool ../support/buffer/InterleavedLayout ./ElevationData ./TerrainConst ../webgl-engine/materials/internal/MaterialUtil".split(" "),function(L,fa,M,ha,V,ia,R,ja,ka,W,N,X){function Y(d,e,l,h){const B=0<(l&2),D=e+(h?1024:0)+(B?2048:0);var n=S.get(D);if(!n){{n=e-1;const r=e-1,E=e*e;var c=2*n+2*r;
let x=n*r*6,F=6*c,C=6*(2*n+r-1);h&&(x*=2,F*=2,C*=2);c=65536<E+c?new Uint32Array(x+F):new Uint16Array(x+F);let k=0,a=0,b=x,f,g;let w=0;for(let p=0;p<=r;p++){B&&(w=0===p?C:p===r?-C:0);b+=w;for(let q=0;q<=n;q++){var t=T(q,p,n,r);if(-1<t){var m=0===p&&q!==n?1:q===n&&p!==r?n+1:p===r&&0!==q?-1:0===q&&0!==p?-(n+1):0;0!==m&&(f=k,g=E+t,t=E+(0===q&&1===p?0:t+1),m=k+m,h?(c[b+0]=f,c[b+1]=g,c[b+2]=g,c[b+3]=t,c[b+4]=t,c[b+5]=f,c[b+6]=t,c[b+7]=m,c[b+8]=m,c[b+9]=f,c[b+10]=f,c[b+11]=t,b+=12):(c[b+0]=f,c[b+1]=g,c[b+
2]=t,c[b+3]=t,c[b+4]=m,c[b+5]=f,b+=6))}++k;q<n&&p<r&&(f=p*(n+1)+q,g=f+1,t=g+(n+1),m=t-1,h?(c[a+0]=f,c[a+1]=g,c[a+2]=g,c[a+3]=t,c[a+4]=t,c[a+5]=f,c[a+6]=t,c[a+7]=m,c[a+8]=m,c[a+9]=f,c[a+10]=f,c[a+11]=t,a+=12):(c[a+0]=f,c[a+1]=g,c[a+2]=t,c[a+3]=t,c[a+4]=m,c[a+5]=f,a+=6))}b-=w}n=new la(c,x,F)}S.set(D,n)}d.indices=n.values;d.numSurfaceIndices=n.numSurfaceIndices;d.numSkirtIndices=n.numSkirtIndices;d.numWithoutSkirtIndices=d.numSurfaceIndices+(l?6*(e-1)*(h?2:1):0)}function U(d,e,l,h){d<h[0]&&(h[0]=d);
d>h[3]&&(h[3]=d);e<h[1]&&(h[1]=e);e>h[4]&&(h[4]=e);l<h[2]&&(h[2]=l);l>h[5]&&(h[5]=l)}function Z(d,e){const l=e>d?1:0;return 2+4*l+(1-2*l)*(d+e)}function T(d,e,l,h){return 0===e?d:d===l?l+e:e===h?l+h+(l-d):0===d&&0<e?2*l+h+(h-e):-1}const ma=ka.newLayout().vec3f("position").vec2f("uv0"),Q=new ja.BufferPool(d=>ma.createBuffer(d),d=>d.count);let la=function(d,e,l){this.values=d;this.numSurfaceIndices=e;this.numSkirtIndices=l};const S=new Map,aa=Array(N.MAX_PATCH_TESSELATION+1),ba=Array(N.MAX_PATCH_TESSELATION+
1),ca=Array(N.MAX_PATCH_TESSELATION+1),da=Array(N.MAX_PATCH_TESSELATION+1),ea=ha.create();L.PatchGeometry=function(){this.vertexAttributes=this.indices=null;this.boundingBox=R.empty();this.skirtLength=this.numVertsPerRow=this.numWithoutSkirtIndices=this.numSkirtIndices=this.numSurfaceIndices=0;this.uvOffsetAndScale=ia.create()};L.clearCaches=function(){Q.clear();S.clear()};L.createPlanarGlobePatch=function(d,e,l,h,B){const D=e[0],n=e[1],c=e[2]-D,t=e[3]-n,m=d.clippingArea,r=M.isSome(m)?Math.max(0,
(m[0]-e[0])/c):0,E=M.isSome(m)?Math.max(0,(m[1]-e[1])/t):0,x=M.isSome(m)?Math.min(1,(m[2]-e[0])/c):1;e=M.isSome(m)?Math.min(1,(m[3]-e[1])/t):1;const F=x>r?1/(x-r):1,C=e>E?1/(e-E):1,k=-r*F,a=-E*C,b=c*h*.1,f=d.numVertsPerRow-1,g=d.numVertsPerRow-1,w=d.numVertsPerRow*d.numVertsPerRow,p=Q.acquire(w+(2*f+2*g)),q=p.position.typedBuffer,u=p.uv0.typedBuffer,y=B.geometryInfo.boundingBox;R.empty(y);let G=0;for(let I=0;I<=g;I++){var z=I/g;let O=a+z*C;z=n+z*t;M.isSome(m)&&(z<m[1]?(z=m[1],O=0):z>m[3]&&(z=m[3],
O=1));for(let J=0;J<=f;J++){var v=J/f;let P=k+v*F;v=D+v*c;M.isSome(m)&&(v<m[0]?(v=m[0],P=0):v>m[2]&&(v=m[2],P=1));var H=d.samplerData?W.ElevationData.sample(v,z,d.samplerData)||0:0;v=v*h-l[0];const K=z*h-l[1];H-=l[2];U(v,K,H,y);var A=N.GEOMETRY_VERTEX_STRIDE*G;q[A+0]=v;q[A+1]=K;q[A+2]=H;u[A+0]=P;u[A+1]=O;A=T(J,I,f,f);-1<A&&(A=N.GEOMETRY_VERTEX_STRIDE*(w+A),q[A+0]=v,q[A+1]=K,q[A+2]=H,u[A+0]=Z(P,O),u[A+1]=b);++G}}B.geometryInfo.numVertsPerRow=d.numVertsPerRow;B.geometryInfo.vertexAttributes=p;B.geometryInfo.skirtLength=
b;V.set(B.geometryInfo.uvOffsetAndScale,r,E,x-r,e-E);Y(B.geometryInfo,d.numVertsPerRow,0,d.wireframe);B.intersectionData=null;B.skirtIntersectionData=null};L.createSphericalGlobePatch=function(d,e,l,h,B,D,n,c){var t=B[0];const m=B[1];var r=B[2];B=B[3];const E=.1*n.radius*(B-m),x=d.numVertsPerRow-1,F=d.numVertsPerRow-1,C=d.numVertsPerRow*d.numVertsPerRow,k=Q.acquire(C+(2*x+2*F)),a=k.position.typedBuffer,b=k.uv0.typedBuffer,f=h.geometryInfo.boundingBox;R.empty(f);var g=e[2]-e[0];const w=e[3]-e[1];var p=
r-t;r=l[0];const q=l[1];l=l[2];for(var u=0;u<=x;u++){var y=u/x,G=t+y*p;aa[u]=Math.sin(G);ba[u]=Math.cos(G);ca[u]=y;da[u]=e[0]+y*g}t=D&&!!(c&1);g=D&&!!(c&2);p=0;for(u=0;u<=F;u++){y=u/F;var z=fa.lerp(m,B,y);G=Math.cos(z);const O=Math.sin(z);D?(z=n.halfSemiMajorAxis*Math.log((1+O)/(1-O)),y=(z-e[1])/w):z=180*z/Math.PI;for(let J=0;J<=x;J++){const P=ca[J];var v=aa[J],H=ba[J],A=n.radius;d.samplerData&&(A+=W.ElevationData.sample(da[J],z,d.samplerData)||0);H=H*G*A-r;v=v*G*A-q;A=O*A-l;U(H,v,A,f);var I=N.GEOMETRY_VERTEX_STRIDE*
p;a[I+0]=H;a[I+1]=v;a[I+2]=A;b[I+0]=P;b[I+1]=y;I=T(J,u,x,F);if(-1<I){I=N.GEOMETRY_VERTEX_STRIDE*(C+I);const K=t&&0===u?-1:g&&u===F?1:0;H=0===K?H:-r;v=0===K?v:-q;A=0===K?A:n.radius*K-l;a[I+0]=H;a[I+1]=v;a[I+2]=A;b[I+0]=0===K?Z(P,y):P;b[I+1]=0===K?E:y;0!==K&&U(H,v,A,f)}++p}}h.geometryInfo.numVertsPerRow=d.numVertsPerRow;h.geometryInfo.vertexAttributes=k;h.geometryInfo.skirtLength=E;V.set(h.geometryInfo.uvOffsetAndScale,0,0,1,1);Y(h.geometryInfo,d.numVertsPerRow,D?c:0,d.wireframe);h.intersectionData=
null;h.skirtIntersectionData=null};L.getGlobalSkirtGeometry=function(d,e,l,h,B,D){const n=h.position,c=h.uv0;h=new Map;e*=3;l=3*l-e;const t=new Uint32Array(l);let m=0;for(let E=0;E<l;++E){const x=d[E+e];if(h.has(x))t[E]=h.get(x);else{const F=m++;h.set(x,F);t[E]=F}}const r=new Float64Array(3*m);h.forEach((E,x)=>{let F=n.get(x,0),C=n.get(x,1),k=n.get(x,2);if(2<=c.get(x,0)){x=F+D[0];const a=C+D[1],b=k+D[2],f=B/Math.sqrt(x*x+a*a+b*b);F+=x*f;C+=a*f;k+=b*f}r[3*E]=F;r[3*E+1]=C;r[3*E+2]=k});return{vertices:r,
indices:t}};L.intersectSkirtsGlobal=function(d,e,l,h,B,D,n,c,t,m){const r=D.position;D=D.uv0;const E=d[0],x=d[1];d=d[2];const F=e[0]-E,C=e[1]-x;e=e[2]-d;l*=3;for(h*=3;l<h;l+=3){var k=B[l],a=B[l+1],b=B[l+2],f=r.get(k,0),g=r.get(k,1),w=r.get(k,2),p=r.get(a,0),q=r.get(a,1),u=r.get(a,2),y=r.get(b,0),G=r.get(b,1),z=r.get(b,2);if(2<=D.get(k,0)){k=f+c[0];var v=g+c[1],H=w+c[2];const A=n/Math.sqrt(k*k+v*v+H*H);f+=k*A;g+=v*A;w+=H*A}2<=D.get(a,0)&&(a=p+c[0],k=q+c[1],v=u+c[2],H=n/Math.sqrt(a*a+k*k+v*v),p+=a*
H,q+=k*H,u+=v*H);2<=D.get(b,0)&&(b=y+c[0],a=G+c[1],k=z+c[2],v=n/Math.sqrt(b*b+a*a+k*k),y+=b*v,G+=a*v,z+=k*v);M.isSome(t)&&([f,g,w]=t.applyToVertex(f,g,w),[p,q,u]=t.applyToVertex(p,q,u),[y,G,z]=t.applyToVertex(y,G,z));p-=f;q-=g;u-=w;y-=f;G-=g;z-=w;a=C*z-G*e;k=e*y-z*F;v=F*G-y*C;b=p*a+q*k+u*v;if(!(Math.abs(b)<=Number.EPSILON)){f=E-f;g=x-g;w=d-w;a=f*a+g*k+w*v;if(0<b){if(0>a||a>b)continue}else if(0<a||a<b)continue;k=g*u-q*w;w=w*p-u*f;g=f*q-p*g;f=F*k+C*w+e*g;if(0<b){if(0>f||a+f>b)continue}else if(0<f||
a+f<b)continue;w=(y*k+G*w+z*g)/b;0<=w&&(g=X.computeNormal(p,q,u,y,G,z,ea),m(w,g))}}};L.intersectSkirtsLocal=function(d,e,l,h,B,D,n,c,t){const m=D.position;D=D.uv0;const r=d[0],E=d[1];d=d[2];const x=e[0]-r,F=e[1]-E;e=e[2]-d;l*=3;for(h*=3;l<h;l+=3){var C=B[l],k=B[l+1],a=B[l+2],b=m.get(C,0),f=m.get(C,1),g=m.get(C,2),w=m.get(k,0),p=m.get(k,1),q=m.get(k,2),u=m.get(a,0),y=m.get(a,1),G=m.get(a,2);2<=D.get(C,0)&&(g+=n);2<=D.get(k,0)&&(q+=n);2<=D.get(a,0)&&(G+=n);M.isSome(c)&&([b,f,g]=c.applyToVertex(b,f,
g),[w,p,q]=c.applyToVertex(w,p,q),[u,y,G]=c.applyToVertex(u,y,G));C=w-b;p-=f;q-=g;u-=b;y-=f;G-=g;a=F*G-y*e;w=e*u-G*x;const z=x*y-u*F;k=C*a+p*w+q*z;if(!(Math.abs(k)<=Number.EPSILON)){b=r-b;f=E-f;g=d-g;a=b*a+f*w+g*z;if(0<k){if(0>a||a>k)continue}else if(0<a||a<k)continue;w=f*q-p*g;g=g*C-q*b;f=b*p-C*f;b=x*w+F*g+e*f;if(0<k){if(0>b||a+b>k)continue}else if(0<b||a+b<k)continue;g=(u*w+y*g+G*f)/k;0<=g&&(C=X.computeNormal(C,p,q,u,y,G,ea),t(g,C))}}};L.releaseGeometry=function(d){Q.release(d.vertexAttributes);
d.vertexAttributes=null;d.indices=null};Object.defineProperty(L,"__esModule",{value:!0})});