// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Color ../../../core/Accessor ../../../core/maybe ../../../core/ObjectPool ../../../core/PooledArray ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../chunks/mat4 ../../../chunks/mat4f64 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../chunks/vec4 ../../../chunks/vec4f64 ../../../geometry/support/aaBoundingBox ../../../geometry/support/buffer/BufferView ../../../support/requestImageUtils ./OverlayRenderer ./PatchGeometryFactory ./PatchRenderData ./ScaleRangeQueries ./TerrainConst ./TileRenderer ./tileUtils ../webgl-engine/collections/Component/ComponentIntersectionData ../webgl-engine/core/shaderLibrary/Slice.glsl ../webgl-engine/core/shaderLibrary/shading/ScreenSpaceReflections.glsl ../webgl-engine/core/shaderLibrary/util/View.glsl ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/Intersector ../webgl-engine/lib/screenSizePerspectiveUtils ../webgl-engine/lib/verticalOffsetUtils ../webgl-engine/materials/internal/MaterialUtil ../webgl-engine/shaders/TerrainTechnique".split(" "),
function(aa,p,la,n,k,ma,ba,u,Ga,Ha,Ia,na,oa,ca,I,C,pa,da,X,qa,ra,ea,S,sa,ta,ua,va,Y,T,wa,xa,ya,za,Aa,Ba,fa,Z,ha){function ia(E,w,e){pa.set(e,E[0]*w[2]+w[0],E[1]*w[3]+w[1],E[2]*w[2],E[3]*w[3])}const U=X.create(),V=da.create();n=function(E){function w(a){a=E.call(this,a)||this;a.type=2;a.isGround=!0;a.tileSize=256;a.rctx=null;a._isTransparent=!1;a._scaleRangeQueries=new ta.ScaleRangeQueries;a.renderDataPool=new ma(sa.PatchRenderData);a._patchGroups=new ba({allocator:b=>b||{root:null,origin:null,patches:new ba},
deallocator:b=>{b.root=null;b.origin=null;b.patches.clear();return b}});a.patchGroupsDirty=!0;a.patchGroupsMap=new Map;a.tileIterator=new Y.IteratorPreorder;a.highestVisibleLODTile=null;a.visible=!0;a._opaque=!0;a._skirtScale=1;a._velvetOverground=!0;a.castShadows=!0;a._ssrEnabled=!1;a.emptyTex=null;a.tileRenderer=null;a.tileBackgroundInitialized=!1;a.tileBackgroundUpdating=!1;a.stencilEnabledLayerExtents=[];a.numTrianglesRendered=0;a.numTilesRendered=0;a.numTilesCulled=0;a.numOriginsRendered=0;a.overlayOpacity=
1;a.needsHighlight=!1;a.renderOccludedFlags=1;return a}aa._inheritsLoose(w,E);var e=w.prototype;e.initialize=function(){this.stage.addRenderPlugin([1,6,8],this)};e.destroy=function(){this.stage.removeRenderPlugin(this);S.clearCaches()};e.setDebugScreenSizePerspective=function(a){this.shaderTechniqueConfig.screenSizePerspective!==a&&(this.shaderTechniqueConfig.screenSizePerspective=a,this.setNeedsRender())};e.setRootTiles=function(a){this._rootTiles=a;this.setNeedsRender()};e.setNeedsHighlight=function(a){this.needsHighlight=
a;this.setNeedsRender()};e.setRenderOccludedOverlay=function(a){this.renderOccludedFlags=a?ea.overlayRenderOccludedFlag:1;this.setNeedsRender()};e.setStencilEnabledLayerExtents=function(a){this.stencilEnabledLayerExtents=a;this.setNeedsRender()};e.setTileSize=function(a){this.tileSize=a;this.tileRenderer&&(this.tileRenderer.tileSize=a);this.setNeedsRender()};e.loadTile=function(a){a.renderData||(a.renderData=this.renderDataPool.acquire(),a.renderData.init(a),a.renderData.localOrigin=this._getLocalOriginOfTile(a));
this.updateTileGeometry(a);this.updateTileTexture(a,128)};e.queryVisibleLevelRange=function(a,b,c,d){this._scaleRangeQueries.queryVisibleLevelRange(a,b,c,d);this.setNeedsRender()};e.updateTileTexture=function(a,b){this.tileRenderer&&this.tileBackgroundInitialized&&(this.tileRenderer.updateTileTexture(a,128===b?0:2),this.setNeedsRender(),a.resetPendingUpdate(b))};e.updateTileGeometry=function(a){for(const b of a.layerInfo[0])b.pendingUpdates&=-33;a.resetPendingUpdate(32);a.renderData.updateGeometry(this.rctx,
this.wireframe)&&this.setNeedsRender()};e.unloadTile=function(a){a.renderData&&(a.renderData.releaseGeometry()&&this.setNeedsRender(),this.renderDataPool.release(a.renderData),a.renderData.clear(),a.renderData=null,a.setMemoryDirty(),this.setNeedsRender())};e._getLocalOriginOfTile=function(a){const b=Math.max(0,7*Math.floor((a.level-3)/7));if(this.isGlobal&&0===b)return C.ZEROS;for(;a.parent&&a.level>b;)a=a.parent;return a.centerAtSeaLevel};e.setVisibility=function(a){this.visible=a;this.setNeedsRender()};
e.getStats=function(){return{numTilesRendered:this.numTilesRendered,numTilesCulled:this.numTilesCulled,numTrianglesRendered:this.numTrianglesRendered,numOriginsRendered:this.numOriginsRendered}};e.setNeedsRender=function(a=1){this.patchGroupsDirty=!0;this.context.requestRender(a)};e.setTileBackground=function(a){this.tileBackground=a;this._updateTileBackground()};e.initializeRenderContext=function(a){this.context=a;this.rctx=a.renderContext.rctx;this.shaderTechniques=a.shaderTechniqueRep;this.shaderTechniqueConfig=
new ha.TerrainTechniqueConfiguration;this.tileRenderer=new va.TileRenderer(this.rctx,this.tileSize,this.shaderTechniques);this.tileBackground&&this._updateTileBackground();this.emptyTex=za.createEmptyTexture(this.rctx)};e.uninitializeRenderContext=function(){null!=this.emptyTex&&(this.emptyTex.dispose(),this.emptyTex=null);this.tileRenderer&&(this.tileRenderer.dispose(),this.tileRenderer=null)};e.intersect=function(a,b,c,d){if(this._rootTiles&&(!a.options.selectOpaqueTerrainOnly||!a.options.selectionMode||
this._opaque)){var f=Ca,h=Da;I.subtract(f,d,c);I.set(h,1/f[0],1/f[1],1/f[2]);var g=a.results.min,v=a.results.max,F=a.results.ground,J=0===a.options.store,x=!!a.results.ground.target,q=fa.getVerticalOffsetTerrain(a.verticalOffset),K=this._skirtScale,O=a.tolerance,r,G=J&&k.isSome(g.dist)?g.dist:Infinity,N=y=>{var t=y.renderData;if(null!=t){var l=t.geometryInfo;X.set(U,l.boundingBox);t=t.localOrigin;k.isSome(q)&&(q.localOrigin=t,q.applyToAabb(U));var D=-K*l.skirtLength;if(0!==D){var z=y.up;X.expandWithOffset(U,
D*z[0],D*z[1],D*z[2])}A[0]=c[0]-t[0];A[1]=c[1]-t[1];A[2]=c[2]-t[2];if(Z.intersectAabbInvDirBefore(U,A,h,O,G)){var P=(m,B,Ea)=>{m.set(this.type,y,B,Ea,ca.IDENTITY);G=J&&k.isSome(g.dist)?g.dist:Infinity};z=(m,B)=>{k.isSome(B)&&0<=m&&(a.options.backfacesTerrain||0>I.dot(B,f))&&(a.options.invisibleTerrain||!a.options.selectionMode||null==b||b(c,d,m))&&((null==F.dist||m<F.dist)&&P(F,m,B),a.options.isFiltered||(2===a.options.store&&(k.isNone(r)?(r=Aa.newIntersectorResult(a.ray),P(r,m,B),a.results.all.push(r)):
m<r.dist&&P(r,m,B)),(null==g.dist||m<g.dist)&&P(g,m,B),0!==a.options.store&&(null==v.dist||m>v.dist)&&P(v,m,B)))};var L=Fa;I.subtract(L,d,t);var M=l.indices,Q=l.vertexAttributes,R={data:Q.getField("position",qa.BufferViewVec3f).typedBuffer,size:3,stride:Q.stride/4};l=l.numWithoutSkirtIndices/3;if(!k.isSome(q)&&l>T.componentMinimalSizeForIntersectionData){var H=y.renderData;k.isSome(H.intersectionData)||(H.intersectionData=new T.ComponentIntersectionData(M,0,l,R));H.intersectionData.intersectRay({r0:A,
r1:L},z)}else Z.intersectTriangles(A,L,0,l,M,R,null,q,z);if(0!==D){const m=M.length/3;this.isGlobal?(R=m-l,!k.isSome(q)&&R>T.componentMinimalSizeForIntersectionData?(H=y.renderData,k.isSome(H.skirtIntersectionData)||(t=S.getGlobalSkirtGeometry(M,l,m,Q,D,t),H.skirtIntersectionData=new T.ComponentIntersectionData(t.indices,0,R,{data:t.vertices,stride:3})),H.skirtIntersectionData.intersectRay({r0:A,r1:L},z)):S.intersectSkirtsGlobal(A,L,l,m,M,Q,D,t,q,z)):S.intersectSkirtsLocal(A,L,l,m,M,Q,D,q,z)}}}},
ja=this._rootTiles;k.isSome(ja)&&(()=>{const y=this.tileIterator;y.reset(ja);const t=a.options.invisibleTerrain;for(;!y.done;){const l=y.next();!(l.visible||t&&l.intersectsClippingArea)||!k.isSome(q)&&!l.intersectsRay(c,f,O,G,K)||x&&this._useStencilForTile(l)?y.skipSubtree():N(l)}})()}};e.render=function(a){if(8===a.slot){if(0===(a.renderOccludedMask&ea.overlayRenderOccludedFlag))return!1}else if(a.slot!==(this.opaque?1:6))return!1;var b=a.pass;const c=1===a.scenelightingData.globalFactor,d=this._updatePatchGroups();
let f=!1;switch(b){case 0:b=a.shadowMap&&a.shadowMap.enabled;this.shaderTechniqueConfig.receiveShadows!==b&&(this.shaderTechniqueConfig.receiveShadows=b);b=this.overlayRenderer.isEmpty()?0:this.overlayRenderer.hasWater?2:1;this.shaderTechniqueConfig.overlayMode!==b&&(this.shaderTechniqueConfig.overlayMode=b);this._renderMaterialPass(a,0,d,8===a.slot?3:1);f=!0;break;case 4:case 6:this.castShadows&&c&&(this._renderAuxiliaryPass(a,3,d,0),f=!0);break;case 2:this.isTransparent&&this.overlayRenderer.isEmpty()||
(this._renderAuxiliaryPass(a,1,d,0),f=!0);break;case 3:this._renderAuxiliaryPass(a,2,d,0);f=!0;break;case 5:this.needsHighlight&&(this._renderAuxiliaryPass(a,4,d,2),a.rctx.clearSafe(256),f=!0)}this._scaleRangeQueries.hasPendingQueries()&&this.setNeedsRender();return f};e._renderMaterialPass=function(a,b,c,d){const {rctx:f,camera:h}=a;this._ssrEnabled=a.ssrParams.ssrEnabled;this._setTerrainTechnique(b,3===d);const g=this._shaderTechnique.program;f.useProgram(g);0!==this.shaderTechniqueConfig.overlayMode&&
1===d&&a.ssrParams&&xa.bindSSRUniforms(g,a.ssrParams);a.shadowMap.bind(g);a.ssaoHelper.bind(g,a.camera);this._bindOverlayData(g,d);g.setUniformMatrix4fv("viewNormal",h.viewInverseTransposeMatrix);ya.bindProjectionMatrix(g,h.projectionMatrix);a.scenelightingData.setUniforms(g,!0);b=h.viewMatrix;I.set(W,b[12],b[13],b[14]);I.normalize(W,W);g.setUniform3fv("viewDirection",W);this.numOriginsRendered=this.numTrianglesRendered=this.numTilesCulled=this.numTilesRendered=0;this._scaleRangeQueries.prepareQueries();
this.opaque?this._renderPatchGroups(a,g,c,d):a.offscreenRenderingHelper.renderToTargets(()=>this._renderPatchGroups(a,g,c,d),a.offscreenRenderingHelper.tmpColor,a.offscreenRenderingHelper.mainDepth,[0,0,0,0]);this._scaleRangeQueries.processQueries()};e._renderAuxiliaryPass=function(a,b,c,d){this._setTerrainTechnique(b,3===d);b=this._shaderTechnique.program;a.rctx.useProgram(b);if(5===a.pass){const f=a.offscreenRenderingHelper;b.bindTexture(f.depthTexture,"depthTex");b.setUniform4f("highlightViewportPixelSz",
0,0,1/f.width,1/f.height)}else b.setUniformMatrix4fv("viewNormal",a.camera.viewInverseTransposeMatrix),2!==a.pass&&4!==a.pass&&6!==a.pass||b.setUniform2fv("nearFar",a.camera.nearFar);this._renderPatchGroupsAuxiliary(a,b,c,d)};e._updateTileBackground=function(){if(this.tileRenderer){this.tileBackgroundUpdating=!0;var a=()=>{this.tileBackgroundInitialized=!0;this.tileBackgroundUpdating=!1;this.shaderTechniqueConfig.useGrid=this.tileRenderer.backgroundIsGrid;this.shaderTechniqueConfig.hasBackgroundColor=
!this.tileRenderer.backgroundIsGrid&&!!k.isSome(this.tileRenderer.backgroundColor);this.allTiles.forAll(b=>this.tileRenderer.updateTileTexture(b,0));this.setNeedsRender()};if("string"===typeof this.tileBackground){const b=this.tileBackground;ra.requestImage(b).then(c=>{b===this.tileBackground&&this.tileRenderer&&(this.tileRenderer.setBackground(c,this.tileBackground===ua.DEFAULT_TILE_BACKGROUND),a())})}else{const b=this.tileBackground?la.toUnitRGBA(this.tileBackground):[0,0,0,0];this.tileRenderer.setBackground(b,
!1);a()}}};e._updatePatchGroups=function(){const a=this._patchGroups;if(!this.patchGroupsDirty)return a;this.highestVisibleLODTile=null;this._renderCollectOrigins(a);if(0!==this.renderOrder){for(let b=0;b<a.length;b++)Y.sortTiles(this.renderOrder,a.data[b].patches);a.sort((b,c)=>{var d=this.renderOrder;b=0===b.patches.length?-d:0===c.patches.length?d:Y.compareTiles(b.patches.data[0],c.patches.data[0],d);return b})}this.patchGroupsDirty=!1;return a};e._renderCollectOrigins=function(a){var b=this._rootTiles;
if(!k.isNone(b)){var c=this.isGlobal;a.clear();for(const d of b)b=a.pushNew(),b.root=d,b.origin=c?C.ZEROS:d.centerAtSeaLevel,b.patches.clear(),this._renderCollectOriginsForRoot(a,b);a.filterInPlace(d=>0<d.patches.length)}};e._renderCollectOriginsForRoot=function(a,b){const c=this.tileIterator;c.resetOne(b.root);const d=this.patchGroupsMap;d.clear();for(d.set(b.origin,b);!c.done;){b=c.next();var f=b.renderData;if(f&&!b.visible)this.numTilesCulled++,c.skipSubtree();else{if(0===b.level%7){const h=a.pushNew();
h.root=b;h.origin=b.centerAtSeaLevel;d.set(b.centerAtSeaLevel,h);h.patches.clear()}if(!b.rendered)this.numTilesCulled++;else if(f){(f=d.get(f.localOrigin))&&f.patches.push(b);if(!this.highestVisibleLODTile||b.vlevel>this.highestVisibleLODTile.vlevel)this.highestVisibleLODTile=b;c.skipSubtree()}}}};e._useStencilForTile=function(a){for(const b of this.stencilEnabledLayerExtents)if(a.intersectsExtent(b))return!0;return!1};e._renderPatchGroupsAuxiliary=function(a,b,c,d){var f=a.rctx;this._shaderTechnique.useStencil=
!1;this._shaderTechnique.bindPipelineState(f,a.slot);f=0<this.stencilEnabledLayerExtents.length;b.setUniformMatrix4fv("proj",a.camera.projectionMatrix);b.setUniform1f("skirtScale",this._skirtScale);0!==d&&this._bindOverlayData(b,d);for(let h=0;h<c.length;h++){const g=c.data[h];this._bindPatchGroupData(b,g,a.camera.eye,a.camera.viewMatrix);for(let v=0;v<g.patches.length;v++)this._renderPatch(a,b,g.patches.data[v],4,f,d)}a.rctx.bindVAO(null)};e._renderPatchGroups=function(a,b,c,d){const f=a.rctx,h=
a.camera,g=h.viewMatrix;this._shaderTechnique.useStencil=!1;this._shaderTechnique.bindPipelineState(f,a.slot);if(this.shaderTechniqueConfig.screenSizePerspective&&this.pointsOfInterest){var v=Ba.getSettings(this.stage.viewingMode,this.ellipsoidRadius);v.update({distance:this.pointsOfInterest.centerOnSurfaceFrequent.distance,fovY:h.fovY});Z.bindScreenSizePerspective(v,b,"screenSizePerspective")}v=0<this.stencilEnabledLayerExtents.length;const F=3===d;F&&(b.bindTexture(this.emptyTex,"tex"),b.setUniform1f("blend",
1),b.setUniform4fv("texOffsetAndScale",da.ZEROS));var J=k.isSome(this.tileRenderer.backgroundColor)?this.tileRenderer.backgroundColor:C.ZEROS;this.shaderTechniqueConfig.hasBackgroundColor&&b.setUniform3fv("backgroundColor",J);b.setUniform1f("skirtScale",F?0:this._skirtScale);J=this.wireframe?1:4;this.shaderTechniqueConfig.textureFadingEnabled&&b.bindTexture(this.emptyTex,"texNext");for(let K=0;K<c.length;K++){var x=c.data[K];const O=x.patches;this._bindPatchGroupData(b,x,h.eye,g);wa.bindSliceUniforms(b,
this._shaderTechnique.configuration,a.sliceHelper&&a.sliceHelper.plane,x.origin);a.shadowMap&&a.shadowMap.bindView(b,x.origin);this.numOriginsRendered++;for(x=0;x<O.length;x++){const r=O.data[x];var q=r.renderData.textureReference;if(!k.isNone(q)){if(!F){this._scaleRangeQueries.scaleQueriesForTile(r);ia(r.renderData.geometryInfo.uvOffsetAndScale,q.offsetAndScale,V);b.setUniform4fv("texOffsetAndScale",V);b.bindTexture(q.texture.texture,"tex");const G=r.renderData.textureFadeFactor,N=1>G?r.renderData.nextTextureReference:
null;this.shaderTechniqueConfig.textureFadingEnabled&&k.isSome(N)&&1>G?(ia(r.renderData.geometryInfo.uvOffsetAndScale,N.offsetAndScale,V),b.setUniform1f("fadeFactor",G),b.setUniform4fv("nextTexOffsetAndScale",V),b.setUniform3fv("nextTexOpacities",N.opacities),b.bindTexture(N.texture.texture,"texNext")):b.setUniform1f("fadeFactor",1);r.renderData.textureIsFading&&this.setNeedsRender();b.setUniform3fv("textureOpacities",q.opacities)}q=this._renderPatch(a,b,r,J,v,d);r.renderOrder=this.numTilesRendered;
this.numTilesRendered++;this.numTrianglesRendered+=q/3}}}f.bindVAO(null)};e._renderPatch=function(a,b,c,d,f,h){if(k.isNone(c.renderData.vao.indexBuffer))return 0;0!==h&&this._bindOverlayPatchData(b,c.renderData.overlay);f&&(this._shaderTechnique.useStencil=this._useStencilForTile(c),this._shaderTechnique.bindPipelineState(a.rctx,a.slot));f=0===this._skirtScale?c.renderData.geometryInfo.numWithoutSkirtIndices:c.renderData.vao.indexBuffer.size;a.rctx.bindVAO(c.renderData.vao);b.assertCompatibleVertexAttributeLocations(c.renderData.vao);
a.rctx.drawElements(d,f,c.renderData.vao.indexBuffer.indexType,0);return f};e._bindPatchGroupData=function(a,b,c,d){a.setUniform3fv("origin",b.origin);oa.translate(ka,d,b.origin);a.setUniformMatrix4fv("view",ka);a.setUniform3f("camPos",c[0]-b.origin[0],c[1]-b.origin[1],c[2]-b.origin[2])};e._bindOverlayData=function(a,b){if(0!==this.shaderTechniqueConfig.overlayMode){a.setUniform1f("overlayOpacity",this.overlayOpacity);var c=this.overlayRenderer.overlays;if(0<c.length){c=c[0];const d=c.getColorTexture(b);
a.bindTexture(k.isSome(d)?d:this.emptyTex,"ovColorTex");2===this.shaderTechniqueConfig.overlayMode&&(b=c.getNormalTexture(b),a.bindTexture(k.isSome(b)?b:this.emptyTex,"ovWaterTex"))}}};e._bindOverlayPatchData=function(a,b){a.setUniform4fv("overlayTexOffset",b.offsets);a.setUniform4fv("overlayTexScale",b.scales)};e._setTerrainTechnique=function(a,b){this.shaderTechniqueConfig.output=a;0===a&&(this.shaderTechniqueConfig.atmosphere=this.isGlobal&&this._velvetOverground,this.shaderTechniqueConfig.ssrEnabled=
this._ssrEnabled);this.shaderTechniqueConfig.renderOccluded=b;this.shaderTechniqueConfig.stencilEnabled=!1;this._shaderTechnique=this.shaderTechniques.releaseAndAcquire(ha.TerrainTechnique,this.shaderTechniqueConfig,this._shaderTechnique)};aa._createClass(w,[{key:"isGlobal",get:function(){return 1===this.stage.viewingMode}},{key:"updating",get:function(){return!this.tileBackgroundInitialized||this.tileBackgroundUpdating}},{key:"canRender",get:function(){return this.visible&&!!this._rootTiles&&this.tileBackgroundInitialized&&
!this.renderingDisabled}},{key:"renderingDisabled",set:function(a){this._set("renderingDisabled",!!a);this.setNeedsRender()}},{key:"opaque",get:function(){return this._opaque&&!this.shaderTechniqueConfig.slicePlaneEnabled},set:function(a){this._opaque!==a&&(this._opaque=a,this.setNeedsRender())}},{key:"needsLinearDepth",get:function(){return this.overlayRenderer.hasWater}},{key:"isTransparent",get:function(){return this._isTransparent},set:function(a){this._isTransparent!==a&&(this._isTransparent=
a,this.setNeedsRender())}},{key:"skirtScale",get:function(){return this._skirtScale},set:function(a){a!==this._skirtScale&&(this._skirtScale=a,this.setNeedsRender())}},{key:"renderPatchBorders",get:function(){return!!this.shaderTechniqueConfig.tileBorders},set:function(a){this.shaderTechniqueConfig.tileBorders!==a&&(this.shaderTechniqueConfig.tileBorders=a,this.setNeedsRender(),this.notifyChange("renderPatchBorders"))}},{key:"cullBackFaces",get:function(){return this.shaderTechniqueConfig.backfaceCullingEnabled},
set:function(a){this.shaderTechniqueConfig.backfaceCullingEnabled!==a&&(this.shaderTechniqueConfig.backfaceCullingEnabled=a,this.notifyChange("cullBackFaces"),this.setNeedsRender())}},{key:"renderOrder",set:function(a){this._set("renderOrder",a);this.setNeedsRender()}},{key:"velvetOverground",set:function(a){this._velvetOverground!==a&&(this._velvetOverground=a,this.setNeedsRender())}},{key:"layerUid",get:function(){return fa.TERRAIN_ID}},{key:"slicePlaneEnabled",get:function(){return this.shaderTechniqueConfig.slicePlaneEnabled},
set:function(a){this.shaderTechniqueConfig.slicePlaneEnabled!==a&&(this.shaderTechniqueConfig.slicePlaneEnabled=a,this.setNeedsRender())}},{key:"textureFadingEnabled",set:function(a){this.shaderTechniqueConfig.textureFadingEnabled!==a&&(this.shaderTechniqueConfig.textureFadingEnabled=a,this.setNeedsRender())}},{key:"wireframe",set:function(a){this._get("wireframe")!==a&&(this._set("wireframe",a),this.allTiles.forAll(b=>{var c;return null==(c=b.renderData)?void 0:c.updateGeometry(this.rctx,a)}),this.setNeedsRender())}},
{key:"test",get:function(){return{tileRenderer:this.tileRenderer}}}]);return w}(n);p.__decorate([u.property()],n.prototype,"tileBackgroundInitialized",void 0);p.__decorate([u.property()],n.prototype,"tileBackgroundUpdating",void 0);p.__decorate([u.property({constructOnly:!0})],n.prototype,"overlayRenderer",void 0);p.__decorate([u.property({constructOnly:!0})],n.prototype,"stage",void 0);p.__decorate([u.property({readOnly:!0})],n.prototype,"isGlobal",null);p.__decorate([u.property({constructOnly:!0})],
n.prototype,"allTiles",void 0);p.__decorate([u.property({constructOnly:!0})],n.prototype,"ellipsoidRadius",void 0);p.__decorate([u.property({readOnly:!0})],n.prototype,"updating",null);p.__decorate([u.property({value:!1})],n.prototype,"renderingDisabled",null);p.__decorate([u.property()],n.prototype,"renderPatchBorders",null);p.__decorate([u.property()],n.prototype,"cullBackFaces",null);p.__decorate([u.property({value:1})],n.prototype,"renderOrder",null);p.__decorate([u.property()],n.prototype,"wireframe",
null);p=n=p.__decorate([na.subclass("esri.views.3d.terrain.TerrainRenderer")],n);const ka=ca.create(),W=C.create(),Ca=C.create(),Da=C.create(),A=C.create(),Fa=C.create();return p});