// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/mathUtils ../../../core/maybe ../../../core/ObjectPool ../../../chunks/vec2 ../../../chunks/vec2f64 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../geometry/projectionEllipsoid ../../../geometry/support/aaBoundingRect ../../../chunks/sphere ../../2d/engine/vectorTiles/VectorTile ../support/StreamDataLoader ./ElevationBounds ./ElevationTileAgent ./LayerClass ./MapTileAgent ./RasterTile ./TerrainConst ./terrainUtils ./TileAgent ./TilePerLayerInfo ./TileTexture ./tileUtils ../../webgl/Util".split(" "),
function(A,S,T,r,J,B,U,g,q,V,C,W,K,L,M,N,t,O,P,y,w,n,D,Q,E,F){function z(p){p.dispose();p instanceof N?G.release(p):p instanceof O&&H.release(p)}const I=q.create(),u=q.create(),l=q.create();let Y=function(){function p(){this.lij=[0,0,0];this._children=[null,null,null,null];this._pendingUpdates=0;this._dirty=!0;this._previouslyRendered=!1;this.extent=C.create();this._elevationBounds=U.create();this.layerInfo=[[],[]];this.extentInRadians=C.create();this.centerAtSeaLevel=q.create();this._center=[q.create(),
W.create(),q.create()];this.up=q.unitZ();this._intersectsClippingArea=this._isWithinClippingArea=!0;this._maxTesselation=0;this._usedMemory=-1;this._curvatureHeight=this._edgeLen2=this._edgeLen=this.renderOrder=this._screenDepth=this._mapDataRefCount=this._mapTileMemory=0}p.prune=function(){H.prune(0);G.prune(0);D.TilePerLayerInfo.prune()};var e=p.prototype;e.updateVisibilityNow=function(){this._dirty=!1;const a=this._intersectsClippingArea&&this._isVisible(this.surface.frustum);a!==this._visible&&
(this._visible=a,this._surface.emit("tiles-visibility-changed"),this._surface.renderer.setNeedsRender(),this.updateAgentSuspension());return this._visible};e.init=function(a,b,c){this.lij[0]=a[0];this.lij[1]=a[1];this.lij[2]=a[2];this.ellipsoid=V.getReferenceEllipsoid(c.tilingScheme.spatialReference);c.tilingScheme.getExtent(a[0],a[1],a[2],this.extent);c.tilingScheme.convertExtentToRadians(this.extent,this.extentInRadians);this._intersectsClippingArea=this._isWithinClippingArea=!0;this._clippingArea=
null;this._mapDataRefCount=0;c.upsampleMapCache.pop(this.key);this._edgeLen2=this._edgeLen=0;this._center[1][3]=0;this.vlevel=a?a[0]:0;b&&b.elevationBounds?B.copy(this._elevationBounds,b.elevationBounds):B.set(this._elevationBounds,0,0);this._pendingUpdates=0;this.renderData=null;this._screenDepth=0;this._previouslyRendered=this._visible=!1;this._parent=b;this.unsetChildren();this._surface=c;this.updateVisibility();for(const d of t.LayerClasses){a=c.numLayers(d);b=this.layerInfo[d];for(const f of b)f.release();
b.length=a;for(let f=0;f<a;f++)b[f]=D.TilePerLayerInfo.acquire(this._surface.upsampleInfoPool),0===d&&this.findElevationBoundsForLayer(f,-1)}this.computeElevationBounds();this._maxTesselation=Math.min(c.tilingScheme.pixelSize,y.MAX_PATCH_TESSELATION)};e.release=function(){w.weakAssert(!this.renderData,"tile.renderData was not unloaded");this._surface.upsampleMapCache.pop(this.key);for(const a of t.LayerClasses){for(const b of this.layerInfo[a])b.release();this.layerInfo[a].length=0}this._surface=
this._parent=null;this._usedMemory=-1};e.refMapData=function(){++this._mapDataRefCount;this.isCached||this._surface.upsampleMapCache.pop(this.key)};e.unrefMapData=function(){--this._mapDataRefCount;if(this.isCached){const a=this.cachedMemory;0<a&&(this._surface.upsampleMapCache.put(this.key,this,a),this.setMemoryDirty())}};e.setMemoryDirty=function(){this._usedMemory=-1};e._updateMemoryUsed=function(){this._mapTileMemory=this._usedMemory=0;const a=this.cpuImageMemorySize;for(const {data:b}of this.layerInfo[1])b instanceof
Q?this._mapTileMemory+=F.getGpuMemoryUsage(b.texture):b instanceof HTMLImageElement||b instanceof L.ImageWithType?this._mapTileMemory+=a:b instanceof P&&(this._mapTileMemory+=b.memoryUsage);for(const b of this.layerInfo[0])this._usedMemory+=b.data?a:0;this.renderData&&(this._usedMemory+=this.renderData.estimatedGeometryMemoryUsage,this._mapTileMemory+=F.getGpuMemoryUsage(this.renderData.textureDescriptor));this.isCached&&this._surface.upsampleMapCache.updateSize(this.key,this,this.cachedMemory)};
e.getUsedMemoryForLayer=function(a,b){b=this.layerInfo[a][b];if(!b||!b.data)return 0;if(1===a&&!this.isCached){a=b.data;if(a instanceof Q)return F.getGpuMemoryUsage(a.texture);if(a instanceof HTMLImageElement||a instanceof L.ImageWithType)return this.cpuImageMemorySize;if(a instanceof K.VectorTile||a instanceof P)return a.memoryUsage}else if(0===a)return this.cpuImageMemorySize;return 0};e.updateScreenDepth=function(a){var b=this._center[1];const c=b[0],d=b[1];b=b[2];const f=a[2]*c+a[6]*d+a[10]*b+
a[14];this._screenDepth=0>f?0:f/(a[3]*c+a[7]*d+a[11]*b+a[15])};e.shouldSplit=function(a,b,c){if(r.isSome(a.frustum)&&(!this._intersectsClippingArea||!this._isVisible(a.frustum)))return 0;const d=this.level;g.subtract(I,this._center[1],b);var f=g.squaredLength(I);let m=1;g.subtract(u,this._center[0],b);var h=g.squaredLength(u);h<f&&(f=h,m=0);g.subtract(u,this._center[2],b);h=g.squaredLength(u);h<f&&(f=h,m=2);if(this._edgeLen2>f&&d<a.maxLod)return 2;f=Math.sqrt(f);const k=this._edgeLen/(a.fovX*f*2);
h=()=>{const R=d+Math.ceil(-Math.log2(a.relativeWidthLimit/k));return R!==this.vlevel?(this.vlevel=R,4):1};if(1===c&&1===this._surface.snapLevel-d)return d>=a.maxLod?h():2;const v=g.dot(this.up,I);c=this._elevationBounds[1]-this._elevationBounds[0];const x=c/this.edgeLen;return a.aboveGround&&0<v&&.001>x&&0<v/f-Math.sin(this._curvatureHeight/(this.edgeLen*Math.SQRT1_2)*Math.PI)-x?0:k<a.relativeWidthLimit?this.vlevel!==this.level?(this.vlevel=this.level,4):0:d>=a.maxLod?h():6<d&&(g.subtract(u,this._center[m],
b),g.scale(l,this.up,v),g.subtract(l,l,u),h=g.squaredLength(l),h>this.radius*this.radius&&(g.scale(l,l,this.radius/Math.sqrt(h)),g.add(l,l,this._center[m]),g.subtract(l,b,l),Math.min(1,(Math.abs(g.dot(l,this.up))+.5*c+this._curvatureHeight)/g.length(l))*(this._edgeLen/(a.fovY*f*2))<.1/a.angledSplitBias*a.relativeHeightLimit))?0:2};e.setChildren=function(a,b,c,d){w.weakAssert(!!(a&&b&&c&&d),"Null child passed");this._children[0]=a;this._children[1]=b;this._children[2]=c;this._children[3]=d};e.unsetChildren=
function(){this._children[0]=null;this._children[1]=null;this._children[2]=null;this._children[3]=null};e.load=function(a){this.refMapData();for(const b of t.LayerClasses)this._createOrUpdateAgents(0,b);a.loadTile(this)};e.unload=function(a){a.unloadTile(this);for(const b of t.LayerClasses){a=this.layerInfo[b];for(const c of a)c.loadingAgent&&c.loadingAgent!==n.TILE_AGENT_DONE&&(z(c.loadingAgent),c.loadingAgent=null),c.pendingUpdates=0}this.resetPendingUpdate(32);this.resetPendingUpdate(64);this.resetPendingUpdate(128);
this.unrefMapData()};e.unloadMapData=function(){const a=this.layerInfo[1];for(const b of a)b.loadingAgent&&b.loadingAgent!==n.TILE_AGENT_DONE&&(z(b.loadingAgent),b.loadingAgent=null),b.pendingUpdates=0;this.renderData&&this.renderData.releaseTexture();this.setMemoryDirty()};e.updateClippingStatus=function(a){if(C.equals(a,this._clippingArea))return!1;var b=this._intersectsClippingArea;const c=this._isWithinClippingArea;r.isSome(a)?(this._intersectsClippingArea=this.intersectsExtent(a),this._isWithinClippingArea=
this._isWithinExtent(a)):this._isWithinClippingArea=this._intersectsClippingArea=!0;this._clippingArea=a;this.updateVisibility();a=c&&this._isWithinClippingArea;b=!c&&!b&&!this._isWithinClippingArea&&!this._intersectsClippingArea;!this.renderData||a||b||this.setPendingUpdate(32);return!0};e.updateVisibility=function(){this._dirty=!0;this._surface.setTileTreeDirty()};e.getLayerInfo=function(a,b){return this.layerInfo[b][a]};e.hasLayerData=function(a,b){a=this.layerInfo[b][a];return!(!a||!a.data||a.dataInvalidated)};
e.isSuspended=function(a){return this.hasPendingUpdate(2)?!0:0===a?!1:!this.loadable};e.hasPendingUpdate=function(a){return(this._pendingUpdates&a)===a};e.setPendingUpdate=function(a){this._pendingUpdates|=a;2===a||8===a?this._surface.setTileTreeDirty():this._surface.requestUpdate()};e.resetPendingUpdate=function(a){return this.hasPendingUpdate(a)?(this._pendingUpdates&=~a,!0):!1};e.requestLayerData=function(a,b,c){const d=this.layerInfo[b][a];if(d.waitingAgents.has(c))return console.warn("agent already requested this piece of map data (tile %s, agent tile %s, layer: %d/%d)",
this.lij.toString(),c.tile.lij.toString(),b,a),!0;d.waitingAgents.push(c);if(d.data&&!d.dataInvalidated)return console.warn("agent requested existing data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),c.tile.lij.toString(),b,a),c.dataArrived(this),!0;if(d.requestPromise)return!0;r.abortMaybe(d.requestAbort);d.requestAbort=new AbortController;const f=this._surface.requestTileData(this,a,b,d.requestAbort);if(!f)return d.requestAbort=null,!1;a=()=>{d.requestPromise===f&&(d.requestPromise=
null,d.requestAbort=null)};d.requestPromise=f;f.then(a,a);return!0};e.hasLij=function(a){return this.lij[0]===a[0]&&this.lij[1]===a[1]&&this.lij[2]===a[2]};e.findByLij=function(a){return this.hasLij(a)?this:this.isLeaf?null:(a=this._children[0].findByLij(a)||this._children[1].findByLij(a)||this._children[2].findByLij(a)||this._children[3].findByLij(a))?a:null};e.distanceToSquared=function(a){return g.squaredLength(g.subtract(l,this._center[1],a))};e.containsPoint=function(a){const b=this.extent;return a[0]>=
b[0]&&a[1]>=b[1]&&a[0]<=b[2]&&a[1]<=b[3]};e.unrequestLayerData=function(a,b,c){a=this.layerInfo[b][a];b=a.waitingAgents;c=null!=b.removeUnordered(c);w.weakAssert(c,"agent has not requested this piece of map data");1>b.length&&(a.abortRequest(),this._updateMemoryUsed())};e.dataArrived=function(a,b,c){a=this.layerInfo[b][a];a.data=c;a.dataInvalidated=!1;a.waitingAgents.forAll(d=>d.dataArrived(this));a.waitingAgents.clear();this._updateMemoryUsed()};e.dataMissing=function(a,b,c){c.notInTilemap||console.error(`Tile ${this.lij.toString()} layer ${b}/${a} error ${c}`);
a=this.layerInfo[b][a];a.dataMissing=!0;a.waitingAgents.forAll(d=>d.dataMissing());a.waitingAgents.clear();this._updateMemoryUsed()};e.updateRenderData=function(a,b){switch(a){case 1:return this.updateTexture(b);case 0:return this.updateGeometry()}};e.updateTexture=function(a){this.renderData&&(this.resetPendingUpdate(0===a?64:128),this.setPendingUpdate(0===a?128:64))};e.updateGeometry=function(){this.setPendingUpdate(32);for(const a of this.layerInfo[0])a.pendingUpdates|=32};e.invalidateLayerData=
function(a,b){this.layerInfo[b][a].invalidateSourceData();this.restartAgents(b)};e.computeElevationBounds=function(){B.set(this._elevationBounds,Number.MAX_VALUE,-Number.MAX_VALUE);const a=this.layerInfo[0];let b=!0;for(const c of a)r.isSome(c.elevationBounds)&&(this._elevationBounds[0]=Math.min(this._elevationBounds[0],c.elevationBounds.min),this._elevationBounds[1]=Math.max(this._elevationBounds[1],c.elevationBounds.max),c.elevationBounds.hasNoDataValues||(b=!1));b&&(this._elevationBounds[0]=Math.min(this._elevationBounds[0],
0),this._elevationBounds[1]=Math.max(this._elevationBounds[1],0));this.updateRadiusAndCenter();this._surface.setTileTreeDirty()};e._updateCenter=function(){g.scale(l,this.up,.5*(this._elevationBounds[0]+this._elevationBounds[1]));g.add(this._center[1],this.centerAtSeaLevel,l);g.scale(l,this.up,this._elevationBounds[0]);g.add(this._center[0],this.centerAtSeaLevel,l);g.scale(l,this.up,this._elevationBounds[1]);g.add(this._center[2],this.centerAtSeaLevel,l)};e.findElevationBoundsForLayer=function(a,
b){const c=this.layerInfo[0][a];if(!(r.isSome(c.elevationBounds)&&c.elevationBounds.level>=b)&&(b=this._surface.layerViewByIndex(a,0),b=w.getLayerWithExtentRange(b),E.fallsWithinLayer(this,b,!1))){b=X;var d=!1;if(c.data)a=c.data,b.min=a.bounds[0],b.max=a.bounds[1],b.hasNoDataValues=a.hasNoDataValues,b.level=this.lij[0],d=!0;else{let f=0,m,h;for(let k=this._parent;k&&(!h||f<y.getElevationDesiredResolutionLevel(this.level))&&!(f=this.vlevel-k.level,m=h||m,h=k.layerInfo[0][a].data,!h&&m&&f>=y.getElevationDesiredResolutionLevel(this.level));k=
k.parent);if(h=h||m)h.computeMinMaxValue(this.lij[0],this.lij[1],this.lij[2],b),Infinity!==b.min&&(b.level=h.level,d=!0)}d&&(r.isNone(c.elevationBounds)&&(c.elevationBounds=new M.ElevationBounds),c.elevationBounds.copyFrom(b))}};e.modifyLayers=function(a,b,c){c=this.layerInfo[c];for(var d of c)d.loadingAgent&&d.loadingAgent!==n.TILE_AGENT_DONE&&(z(d.loadingAgent),d.loadingAgent=null),d.waitingAgents.clear();for(d=0;d<c.length;++d)void 0===a[d]&&c[d].release();a=Array(...c);d=b.length;c.length=d;for(let f=
0;f<d;f++){const m=b[f];c[f]=-1<m?a[m]:D.TilePerLayerInfo.acquire(this._surface.upsampleInfoPool)}this._updateMemoryUsed()};e.restartAgents=function(a){this.renderData&&(this._createOrUpdateAgents(0,a),this.updateRenderData(a,0))};e.updateAgents=function(a){if(this.renderData){const b=this.layerInfo[a];for(const c of b)c.loadingAgent===n.TILE_AGENT_DONE&&(c.loadingAgent=null);this._createOrUpdateAgents(0,a)}};e.updateAgentSuspension=function(){for(const a of t.LayerClasses){const b=this.isSuspended(a);
for(const c of this.layerInfo[a])c.loadingAgent&&c.loadingAgent!==n.TILE_AGENT_DONE&&(c.loadingAgent.setSuspension(b),c.loadingAgent===n.TILE_AGENT_DONE&&this.updateRenderData(a,0))}};e.removeLayerAgent=function(a,b){a=this.layerInfo[b][a];a.loadingAgent&&a.loadingAgent!==n.TILE_AGENT_DONE&&a.loadingAgent.dispose();a.loadingAgent=null};e.agentDone=function(a,b){const c=this.layerInfo[b][a];c.loadingAgent=n.TILE_AGENT_DONE;c.data||c.upsampleInfo||this._createOrUpdateAgents(a+1,b)};e._createOrUpdateAgents=
function(a,b){const c=this.isSuspended(b),d=this.layerInfo[b];for(;a<d.length;++a){const k=d[a];var f=!1;const v=this._surface.layerViewByIndex(a,b);var m=w.getLayerWithExtentRange(v);if(k.loadingAgent)E.fallsWithinLayer(this,m,!1)?(k.loadingAgent!==n.TILE_AGENT_DONE&&k.loadingAgent.setSuspension(c),k.loadingAgent!==n.TILE_AGENT_DONE&&(f=k.loadingAgent.update())):k.dispose();else if(E.fallsWithinLayer(this,m,!1)){{f=a;m=b;var h=c;const x=0===m?G.acquire():H.acquire();x.init(this,f,m,h);f=x}k.loadingAgent=
f;(f=k.loadingAgent.startLoading())?k.loadingAgent===n.TILE_AGENT_DONE&&this.setPendingUpdate(32):(z(k.loadingAgent),k.loadingAgent=n.TILE_AGENT_DONE)}k.loadingAgent===n.TILE_AGENT_DONE&&this.updateRenderData(b,0);if(f&&v.isOpaque)break}};e._isWithinExtent=function(a){const b=this.extent;return b[0]>=a[0]&&a[2]>=b[2]&&b[1]>=a[1]&&a[3]>=b[3]};e.intersectsExtent=function(a){const b=this.extent;return b[2]>=a[0]&&a[2]>=b[0]&&b[3]>=a[1]&&a[3]>=b[1]};e.getElevationBasedVerticesPerRow=function(a){const b=
this.vlevel-this.level;a=Math.max(this.level-a,y.getElevationDesiredResolutionLevel(this.level)-b);return T.clamp((this.maxTesselation>>a)+1,2,this.maxTesselation+1)};S._createClass(p,[{key:"usedMemory",get:function(){-1===this._usedMemory&&this._updateMemoryUsed();return this._usedMemory+(this.isCached?0:this.mapTileMemory)}},{key:"cachedMemory",get:function(){return this.isCached?this.mapTileMemory:0}},{key:"mapTileMemory",get:function(){-1===this._usedMemory&&this._updateMemoryUsed();let a=this._mapTileMemory;
for(const {data:b}of this.layerInfo[1])b instanceof K.VectorTile&&(a+=b.memoryUsage);return a}},{key:"isCached",get:function(){return!this.shouldLoad&&0>=this._mapDataRefCount}},{key:"maxTesselation",get:function(){return this._maxTesselation}},{key:"isWithinClippingArea",get:function(){return this._isWithinClippingArea}},{key:"intersectsClippingArea",get:function(){return this._intersectsClippingArea}},{key:"clippingArea",get:function(){return this._clippingArea}},{key:"parent",get:function(){return this._parent}},
{key:"children",get:function(){return this._children}},{key:"surface",get:function(){return this._surface}},{key:"elevationBounds",get:function(){return this._elevationBounds}},{key:"level",get:function(){return this.lij[0]}},{key:"key",get:function(){return`${this.lij[0]}/${this.lij[1]}/${this.lij[2]}`}},{key:"edgeLen",get:function(){return this._edgeLen}},{key:"radius",get:function(){return this._center[1][3]}},{key:"screenDepth",get:function(){return this._screenDepth}},{key:"visible",get:function(){this._dirty&&
this.updateVisibilityNow();return this._visible}},{key:"loadable",get:function(){return this.visible||this._surface.view.state.fixedContentCamera}},{key:"rendered",get:function(){const a=!!this.renderData;a!==this._previouslyRendered&&(this._surface.emit("tiles-visibility-changed"),this._previouslyRendered=a,this._surface.renderer.setNeedsRender());return a}},{key:"shouldLoad",get:function(){if(!this.loadable)return!1;if(1===this._surface.lodSnapping){const a=this.level-this._surface.snapLevel;if(0===
a)return!0;if(1===a)return!1}return this.isLeaf}},{key:"cpuImageMemorySize",get:function(){const a=this._surface.tilingScheme.pixelSize;return a*a*4}},{key:"updating",get:function(){if(this.hasPendingUpdates)return!0;for(const a of t.LayerClasses){const b=this.layerInfo[a];for(const c of b)if(c.loadingAgent&&c.loadingAgent!==n.TILE_AGENT_DONE&&c.loadingAgent.updating)return!0}return!1}},{key:"hasPendingUpdates",get:function(){return 0!==this._pendingUpdates}},{key:"isLeaf",get:function(){return null==
this._children[0]}},{key:"test",get:function(){return{cachedMemory:this.cachedMemory}}}]);return p}();const H=new J(O),G=new J(N),X=new M.ElevationBounds;A.SplitLimits=function(){this.angledSplitBias=this.maxLod=this.relativeHeightLimit=this.relativeWidthLimit=this.fovY=this.fovX=0;this.aboveGround=!0};A.Tile=Y;Object.defineProperty(A,"__esModule",{value:!0})});