// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/events ../../core/watchUtils ../../core/accessorSupport/decorators/aliasOf ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/property ../../core/accessorSupport/decorators/subclass ../Widget ./FeatureMedia/FeatureMediaViewModel ./support/FeatureElementInfo ./support/featureUtils ../support/chartUtils ../support/widgetUtils ../support/decorators/messageBundle ../../core/Logger ../support/jsxFactory".split(" "),
function(r,n,B,w,q,m,J,K,x,C,D,y,E,F,z,t,G,L,p){m=function(A){function u(a,b){var c=A.call(this,a,b)||this;c._refreshTimer=null;c._refreshIntervalInfo=null;c._featureElementInfo=null;c.attributes=null;c.activeMediaInfoIndex=null;c.description=null;c.fieldInfoMap=null;c.layer=null;c.mediaInfos=null;c.popupTemplate=null;c.relatedInfos=null;c.title=null;c.viewModel=new y;c.messages=null;c._getChartDependencies=function(){var k=r._asyncToGenerator(function*(f){const g=yield z.loadChartsModule();var {viewModel:e}=
r._assertThisInitialized(c);e&&({activeMediaInfo:e}=e,c._renderChart({chartDiv:f,mediaInfo:e,chartsModule:g}))});return function(f){return k.apply(this,arguments)}}();return c}r._inheritsLoose(u,A);var h=u.prototype;h.initialize=function(){this._featureElementInfo=new E;this.own(w.init(this,["viewModel.activeMediaInfo","viewModel.activeMediaInfoIndex"],()=>this._setupMediaRefreshTimer()),w.init(this,["viewModel.description","viewModel.title"],()=>this._setupFeatureElementInfo()))};h.destroy=function(){this._clearMediaRefreshTimer();
this._featureElementInfo.destroy()};h.render=function(){var a;return p.tsx("div",{bind:this,class:"esri-feature-media",onkeyup:this._handleMediaKeyup},null==(a=this._featureElementInfo)?void 0:a.render(),this.renderMedia())};h.renderMedia=function(){const {formattedMediaInfoCount:a}=this.viewModel;return a?p.tsx("div",{key:"media-element-container",class:"esri-feature-media__container"},this.renderMediaPageButton("previous"),this.renderMediaInfo(),this.renderMediaPageButton("next")):null};h.renderImageMediaInfo=
function(a){var {_refreshIntervalInfo:b}=this;const {activeMediaInfoIndex:c,formattedMediaInfoCount:k}=this.viewModel,{value:f,refreshInterval:g,altText:e,title:d,type:l}=a,{sourceURL:H,linkURL:v}=f;a=F.shouldOpenInNewTab(v)?"_blank":"_self";const I="_blank"===a?"noreferrer":"";b=g?b:null;b=p.tsx("img",{alt:e||d,key:`media-${l}-${c}-${k}-${b?b.timestamp:0}`,src:b?b.sourceURL:H});return(a=v?p.tsx("a",{title:d,href:v,rel:I,target:a},b):null)?a:b};h.renderChartMediaInfo=function(a){const {activeMediaInfoIndex:b,
formattedMediaInfoCount:c}=this.viewModel;return p.tsx("div",{key:`media-${a.type}-${b}-${c}`,bind:this,class:"esri-feature-media__chart",afterCreate:this._getChartDependencies})};h.renderMediaInfoType=function(){const {activeMediaInfo:a}=this.viewModel;return a?"image"===a.type?this.renderImageMediaInfo(a):-1!==a.type.indexOf("chart")?this.renderChartMediaInfo(a):null:null};h.renderMediaInfo=function(){var {activeMediaInfo:a}=this.viewModel;if(!a)return null;const b=a.title?p.tsx("div",{key:"media-title",
class:"esri-feature-media__item-title",innerHTML:a.title}):null;a=a.caption?p.tsx("div",{key:"media-caption",class:"esri-feature-media__item-caption",innerHTML:a.caption}):null;return p.tsx("div",{key:"media-container",class:"esri-feature-media__item-container"},p.tsx("div",{key:"media-item-container",class:"esri-feature-media__item"},this.renderMediaInfoType()),b,a)};h.renderMediaPageButton=function(a){if(2>this.viewModel.formattedMediaInfoCount)return null;const b=(a="previous"===a)?this.messages.previous:
this.messages.next,c=a?this.classes("esri-feature-media__button","esri-feature-media__previous"):this.classes("esri-feature-media__button","esri-feature-media__next"),k=a?this.classes("esri-feature-media__icon","esri-feature-media__previous-icon","esri-icon-left-triangle-arrow"):this.classes("esri-feature-media__icon","esri-feature-media__next-icon","esri-icon-right-triangle-arrow"),f=a?this.classes("esri-feature-media__icon","esri-feature-media__previous-icon--rtl","esri-icon-right-triangle-arrow"):
this.classes("esri-feature-media__icon","esri-feature-media__next-icon--rtl","esri-icon-left-triangle-arrow");return p.tsx("button",{type:"button",key:a?"media-previous":"media-next",title:b,"aria-label":b,tabIndex:0,class:c,bind:this,onclick:a?this._previous:this._next},p.tsx("span",{"aria-hidden":"true",class:k}),p.tsx("span",{"aria-hidden":"true",class:f}))};h._setupFeatureElementInfo=function(){const {description:a,title:b}=this;this._featureElementInfo.set({description:a,title:b})};h._next=function(){this.viewModel.next()};
h._previous=function(){this.viewModel.previous()};h._handleMediaKeyup=function(a){const b=B.eventKey(a);"ArrowLeft"===b&&(a.stopPropagation(),this.viewModel.previous());"ArrowRight"===b&&(a.stopPropagation(),this.viewModel.next())};h._renderChart=function(a){const {chartsModule:b,chartDiv:c,mediaInfo:k}=a,{value:f,type:g}=k,{am4core:e}=b,d=z.getColorSet(e);t.isDarkTheme()&&e.useTheme(b.am4themes_dark);e.useTheme(b.am4themes_animated);e.useTheme(function(l){l instanceof e.ColorSet&&d&&(l.list=d)});
a="pie-chart"===g?this._createPieChart(a):this._createXYChart(a);c.setAttribute("aria-label",k.altText||k.title);a.data=f.series.map(l=>({tooltip:l.tooltip,value:l.value})).filter(l=>"pie-chart"===g?0<l.value:!0)};h._customizeChartTooltip=function(a,b){a.label.wrap=!0;a.label.maxWidth=200;a.autoTextColor=!1;a.getFillFromObject=!1;a.label.fill=b.color("#ffffff");a.background.fill=b.color({r:0,g:0,b:0,a:.7})};h._createPieChart=function(a){const {chartDiv:b,chartsModule:c}=a,{am4core:k,am4charts:f}=
c;a=k.create(b,f.PieChart);a.rtl=t.isRTL(this.container);const g=a.series.push(new f.PieSeries);g.labels.template.disabled=!0;g.ticks.template.disabled=!0;g.dataFields.value="value";g.dataFields.category="tooltip";this._customizeChartTooltip(g.tooltip,k);return a};h._getMinSeriesValue=function(a){let b=0;a.forEach(c=>b=Math.min(c.value,b));return b};h._createColumnChart=function(a,b){const {chartsModule:c,mediaInfo:k}=b;({value:b}=k);const {am4core:f,am4charts:g}=c,e=a.xAxes.push(new g.CategoryAxis);
e.dataFields.category="tooltip";e.renderer.labels.template.disabled=!0;this._customizeChartTooltip(e.tooltip,f);e.tooltip.events.on("sizechanged",()=>{e.tooltip.dy=-e.tooltip.contentHeight});var d=a.yAxes.push(new g.ValueAxis);const l=d.renderer.labels.template;d.renderer.minLabelPosition=.05;d.renderer.maxLabelPosition=.95;d.min=this._getMinSeriesValue(b.series);this._customizeChartTooltip(d.tooltip,f);l.wrap=!0;d=a.series.push(new g.ColumnSeries);d.dataFields.valueY="value";d.dataFields.categoryX=
"tooltip";a.cursor=new g.XYCursor;15<b.series.length&&(a.scrollbarX=new f.Scrollbar)};h._createBarChart=function(a,b){const {chartsModule:c,mediaInfo:k}=b;({value:b}=k);const {am4core:f,am4charts:g}=c,e=a.yAxes.push(new g.CategoryAxis);e.dataFields.category="tooltip";e.renderer.inversed=!0;e.renderer.labels.template.disabled=!0;this._customizeChartTooltip(e.tooltip,f);e.tooltip.events.on("sizechanged",()=>{e.tooltip.dx=e.tooltip.contentWidth});var d=a.xAxes.push(new g.ValueAxis);const l=d.renderer.labels.template;
d.renderer.minLabelPosition=.05;d.renderer.maxLabelPosition=.95;d.min=this._getMinSeriesValue(b.series);this._customizeChartTooltip(d.tooltip,f);l.wrap=!0;d=a.series.push(new g.ColumnSeries);d.dataFields.valueX="value";d.dataFields.categoryY="tooltip";a.cursor=new g.XYCursor;15<b.series.length&&(a.scrollbarY=new f.Scrollbar)};h._createLineChart=function(a,b){const {chartsModule:c,mediaInfo:k}=b;({value:b}=k);const {am4core:f,am4charts:g}=c,e=a.xAxes.push(new g.CategoryAxis);e.dataFields.category=
"tooltip";e.renderer.labels.template.disabled=!0;this._customizeChartTooltip(e.tooltip,f);e.tooltip.events.on("sizechanged",()=>{e.tooltip.dy=-e.tooltip.contentHeight});var d=a.yAxes.push(new g.ValueAxis);const l=d.renderer.labels.template;d.renderer.minLabelPosition=.05;d.renderer.maxLabelPosition=.95;d.min=this._getMinSeriesValue(b.series);this._customizeChartTooltip(d.tooltip,f);l.wrap=!0;d=a.series.push(new g.LineSeries);d.dataFields.categoryX="tooltip";d.dataFields.valueY="value";a.cursor=new g.XYCursor;
15<b.series.length&&(a.scrollbarX=new f.Scrollbar)};h._createXYChart=function(a){const {chartDiv:b,chartsModule:c,mediaInfo:k}=a,{type:f}=k,{am4core:g,am4charts:e}=c,d=g.create(b,e.XYChart);d.rtl=t.isRTL(this.container);"column-chart"===f&&this._createColumnChart(d,a);"bar-chart"===f&&this._createBarChart(d,a);"line-chart"===f&&this._createLineChart(d,a);return d};h._clearMediaRefreshTimer=function(){const {_refreshTimer:a}=this;a&&(clearTimeout(a),this._refreshTimer=null)};h._updateMediaInfoTimestamp=
function(a){const b=Date.now();this._refreshIntervalInfo={timestamp:b,sourceURL:this._getImageSource(a,b)};this.scheduleRender()};h._setupMediaRefreshTimer=function(){this._clearMediaRefreshTimer();const {activeMediaInfo:a}=this.viewModel;a&&"image"===a.type&&a.refreshInterval&&this._setRefreshTimeout(a)};h._setRefreshTimeout=function(a){const {refreshInterval:b,value:c}=a;b&&(a=6E4*b,this._updateMediaInfoTimestamp(c.sourceURL),this._refreshTimer=setInterval(()=>{this._updateMediaInfoTimestamp(c.sourceURL)},
a))};h._getImageSource=function(a,b){const c=-1!==a.indexOf("?")?"\x26":"?",[k,f=""]=a.split("#");return`${k}${c}timestamp=${b}${f?"#":""}${f}`};return u}(D);n.__decorate([q.aliasOf("viewModel.attributes")],m.prototype,"attributes",void 0);n.__decorate([q.aliasOf("viewModel.activeMediaInfoIndex")],m.prototype,"activeMediaInfoIndex",void 0);n.__decorate([q.aliasOf("viewModel.description")],m.prototype,"description",void 0);n.__decorate([q.aliasOf("viewModel.fieldInfoMap")],m.prototype,"fieldInfoMap",
void 0);n.__decorate([q.aliasOf("viewModel.layer")],m.prototype,"layer",void 0);n.__decorate([q.aliasOf("viewModel.mediaInfos")],m.prototype,"mediaInfos",void 0);n.__decorate([q.aliasOf("viewModel.popupTemplate")],m.prototype,"popupTemplate",void 0);n.__decorate([q.aliasOf("viewModel.relatedInfos")],m.prototype,"relatedInfos",void 0);n.__decorate([q.aliasOf("viewModel.title")],m.prototype,"title",void 0);n.__decorate([x.property({type:y})],m.prototype,"viewModel",void 0);n.__decorate([x.property(),
G.messageBundle("esri/widgets/Feature/t9n/Feature")],m.prototype,"messages",void 0);return m=n.__decorate([C.subclass("esri.widgets.Feature.FeatureMedia")],m)});