// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","../../../geometry","./xmlUtilities","../rasterTransforms/PolynomialTransform","../../../geometry/SpatialReference"],function(p,B,e,x,g){function t(a,d){if(!a||!d)return null;const b=[];for(let c=0;c<a.length;c++)b.push(a[c]),b.push(d[c]);return b}function y(a){var d,b=e.getElement(a,"GeodataXform");a=e.getElementNumericValue(b,"SpatialReference/WKID")||e.getElementValue(b,"SpatialReference/WKT");a=q(a);if("typens:PolynomialXform"!==b.getAttribute("xsi:type"))return{spatialReference:a,
transform:null};var c=null!=(d=e.getElementNumericValue(b,"PolynomialOrder"))?d:1,f=e.getElementNumericValues(b,"CoeffX/Double");const h=e.getElementNumericValues(b,"CoeffY/Double");d=e.getElementNumericValues(b,"InverseCoeffX/Double");b=e.getElementNumericValues(b,"InverseCoeffY/Double");f=t(f,h);b=t(d,b);c=new x({spatialReference:a,polynomialOrder:c,forwardCoefficients:f,inverseCoefficients:b});return{spatialReference:a,transform:c}}function z(a){var d;const b=e.getElementNumericValue(a,"NoDataValue");
var c=e.getElement(a,"Histograms/HistItem");const f=e.getElementNumericValue(c,"HistMin"),h=e.getElementNumericValue(c,"HistMax"),A=e.getElementNumericValue(c,"BucketCount");c=null==(d=e.getElementValue(c,"HistCounts"))?void 0:d.split("|").map(k=>Number(k));let l,m,u,v;e.getElements(a,"Metadata/MDI").forEach(k=>{var w;const n=Number(null!=(w=k.textContent)?w:k.nodeValue);switch(k.getAttribute("key").toUpperCase()){case "STATISTICS_MINIMUM":l=n;break;case "STATISTICS_MAXIMUM":m=n;break;case "STATISTICS_MEAN":u=
n;break;case "STATISTICS_STDDEV":v=n}});a=e.getElementNumericValue(a,"Metadata/SourceBandIndex");return{noDataValue:b,histogram:null!=c&&c.length&&null!=l&&null!=m?{min:f,max:h,size:A||c.length,counts:c}:null,sourceBandIndex:a,statistics:null!=l&&null!=m?{min:l,max:m,avg:u,stddev:v}:null}}function q(a){if(!a)return null;var d=Number(a);if(!isNaN(d)&&0!==d)return new g({wkid:d});a=String(a);if(a.startsWith("COMPD_CS")){if(!a.includes("VERTCS")||!a.includes("GEOGCS")&&!a.startsWith("PROJCS"))return null;
d=a.indexOf("VERTCS");var b=a.indexOf("PROJCS");b=-1<b?b:a.indexOf("GEOGCS");if(-1===b)return null;b=a.slice(b,a.lastIndexOf("]",d)+1).trim();a=a.slice(d,a.lastIndexOf("]")).trim();d=(d=r(b))?new g({wkid:d}):new g({wkt:b});if(a=r(a))d.vcsWkid=a;return d}if(!a.startsWith("GEOGCS")&&!a.startsWith("PROJCS"))return null;d=r(a);return 0!==d?new g({wkid:d}):new g({wkt:a})}function r(a){var d,b=a.replace(/\]/g,"[").replace(/"/g,"").split("[").map(f=>f.trim()).filter(f=>""!==f);b=b[b.length-1].split(",");
const c=null==(d=b[0])?void 0:d.toLowerCase();return"epsg"!==c&&"esri"!==c||!a.endsWith('"]]')||(a=Number(b[1]),isNaN(a)||0===a)?0:a}p.parsePAMInfo=function(a){var d;if("pamdataset"!==(null==a?void 0:null==(d=a.documentElement.tagName)?void 0:d.toLowerCase()))return{};const b={spatialReference:null,transform:null,metadata:{},rasterBands:[],statistics:null,histograms:null};a.documentElement.childNodes.forEach(c=>{if(1===c.nodeType)if(e.isSameTagIgnoreNS(c,"SRS"))b.spatialReference||(c=e.getElementValue(c),
b.spatialReference=q(c));else if(e.isSameTagIgnoreNS(c,"Metadata"))if("xml:ESRI"===c.getAttribute("domain")){const {spatialReference:f,transform:h}=y(c);b.transform=h;b.spatialReference||(b.spatialReference=f)}else e.getElements(c,"MDI").forEach(f=>b.metadata[f.getAttribute("key")]=e.getElementValue(f));else e.isSameTagIgnoreNS(c,"PAMRasterBand")&&(c=z(c),null!=c.sourceBandIndex&&null==b.rasterBands[c.sourceBandIndex]?b.rasterBands[c.sourceBandIndex]=c:b.rasterBands.push(c))});if(a=b.rasterBands)b.statistics=
a[0].statistics?a.map(c=>c.statistics):null,b.histograms=a[0].histogram?a.map(c=>c.histogram):null;return b};p.parseSpatialReference=q;Object.defineProperty(p,"__esModule",{value:!0})});