// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../request ../core/Logger ../core/maybe ../core/promiseUtils ../core/reactiveUtils ../libs/vxl/VxlModule".split(" "),function(v,w,x,m,y,n,z){const p=x.getLogger("esri.layers.VoxelWasmPerScene");return function(){function r(a){this._havePreparedWithAllLayers=this._halfIntTexturesAvailable=!1;this._vxl=this._renderPluginContext=null;this._moreToLoad=this._pluginIsActive=!1;this._viewportHeight=this._viewportWidth=-1;this._newLayers=[];this._layers=new Map;
this._renderPass=0;this._renderSlot=22;this._renderTargetToRestore=this._rctx=null;this._lastFrameWasStationary=!1;this._wasmMemBlockSizes=[512,1024,2048,4096,8192,16384,32768,65536];this._wasmMemBlocks=new Map;this._dbgFlags=new Set;this._view=a;this.initialize()}var e=r.prototype;e.dbg=function(a,b){this._dbgFlags.has(a)&&(4===a?p.error(b):p.warn(b))};e.removeRenderPlugin=function(){this._pluginIsActive&&this._view._stage&&(this.dbg(1,"--removeRenderPlugin--"),this._view._stage.removeRenderPlugin(this));
this._pluginIsActive=!1};e.initialize=function(){this.dbg(1,"--initialize--");for(const a of this._wasmMemBlockSizes)this._wasmMemBlocks.set(a,0);this._readyWatchHandle=n.react(()=>this._view.ready,a=>{a&&"local"===this._view.viewingMode?(this.dbg(1,"view ready status changed to ready on a local view, calling addRenderPlugin"),this._view._stage.addRenderPlugin([this._renderSlot],this),this._pluginIsActive=!0):(this.dbg(1,"view ready status changed, not ready or not a local view!"),this.removeRenderPlugin())},
{initial:!0});this._qualityWatchHandle=n.react(()=>{var a;return null==(a=this._view)?void 0:a.qualityProfile},a=>{this.dbg(3,"qualityProfile changed to "+a);this._vxl&&this._vxl.set_quality(this.toWasmQuality(a))},{initial:!0});this._timeExtentWatchHandle=n.react(()=>{var a;return null==(a=this._view)?void 0:a.timeExtent},()=>{if(this._vxl){var a;const b=this._getTimeArgs(null==(a=this._view)?void 0:a.timeExtent);this.dbg(3,"sceneView timeExtent changed to useTime\x3d"+b.useTime+" st\x3d"+b.startTime+
" et\x3d"+b.endTime);this._vxl.set_scene_time_extent(b.startTime,b.endTime,b.useTime);this._renderPluginContext.requestRender()}},{initial:!0});this._stationaryWatchHandle=n.react(()=>{var a;return null==(a=this._view)?void 0:a.stationary},a=>{this._vxl&&a&&!this._lastFrameWasStationary&&this._renderPluginContext.requestRender()})};e.initializeRenderContext=function(a){this.dbg(1,"--initializeRenderContext--");const b=a.renderContext.rctx;"webgl2"===b.webglVersion?(this._renderPluginContext=a,this._rctx=
a.renderContext.rctx,this._halfIntTexturesAvailable=!!this._rctx.capabilities.textureNorm16,this.initializeWasm(b.gl)):this.dbg(4,"WebGL 1 context only!")};e.uninitializeRenderContext=function(){this._rctx=this._renderPluginContext=null;this.dbg(1,"--uninitializeRenderContext--")};e.restoreFramebuffer=function(){if(this._renderTargetToRestore){var a=this._renderTargetToRestore.fbo;this._rctx?(this._rctx.bindFramebuffer(a,!0),a=this._renderTargetToRestore.viewport,this._rctx.setViewport(a.x,a.y,a.width,
a.height)):this.dbg(4,"no context in restoreFramebuffer!")}};e.bindPreviousDepthToSlot=function(a,b){var c=!!this._renderTargetToRestore;if(!this._rctx||!c)return 0;c=this._renderTargetToRestore.fbo.depthStencilTexture;if(!c)return this.dbg(4,"no depth/stencil texture exists!"),0;0===b?this._rctx.bindTexture(null,a,!0):this._rctx.bindTexture(c,a,!0);return 1};e.setBlendState=function(a,b,c,d){this._rctx?(this._rctx.setBlendingEnabled(1===a),this._rctx.setBlendFunction(b,c),this._rctx.setBlendEquation(d)):
this.dbg(4,"setBlendState callback has no rendering context!")};e.setFrontFace=function(a){this._rctx?this._rctx.setFrontFace(a):this.dbg(4,"setFrontFace callback has no rendering context!")};e.setDepthStencilStateFunction=function(a,b,c){this._rctx?(this._rctx.setDepthFunction(c),this._rctx.setDepthTestEnabled(1===a),this._rctx.setDepthWriteEnabled(1===b),this._rctx.setStencilTestEnabled(!1),this._rctx.setStencilFunction(519,0,255),this._rctx.setStencilOpSeparate(1028,7680,7682,7680),this._rctx.setStencilOpSeparate(1029,
7680,7683,7680)):this.dbg(4,"setDepthStencilStateFunction callback has no rendering context!")};e.setRasterizerState=function(a){if(this._rctx)switch(a){case 1:this._rctx.setFaceCullingEnabled(!1);break;case 3:this._rctx.setCullFace(1029);this._rctx.setFaceCullingEnabled(!0);break;case 2:this._rctx.setCullFace(1028),this._rctx.setFaceCullingEnabled(!0)}else this.dbg(4,"setRasterizerState callback has no rendering context!")};e.setViewport=function(a,b,c,d){this._rctx?this._rctx.setViewport(a,b,c,
d):this.dbg(4,"setViewport callback has no rendering context!")};e._syncRequestsResponses=function(){this._layers.forEach((a,b)=>{const c=[];a.responses.forEach((g,k)=>{c.push(k);this.dbg(2,"responding for requestID:"+k+" size:"+g.size);this._vxl.respond(b,k,g)});const d=a.responses;for(var f of c)d.delete(f);f=this._vxl.get_new_requests(b);const h=a.abortController.signal;for(const g in f){a.outstandingRequestCount+=1;1===a.outstandingRequestCount&&a.layerView.updatingFlagChanged();const k=f[g],
t={responseType:"array-buffer",signal:h};this.dbg(2,"making requestID:"+g+" url:"+k.url);w(k.url,t).then(l=>{--a.outstandingRequestCount;0===a.outstandingRequestCount&&a.layerView.updatingFlagChanged();this.dbg(2,"have response for requestID:"+g);let u=0;if(0<l.data.byteLength){u=this._vxl._malloc(l.data.byteLength);const A=new Uint8Array(this._vxl.HEAPU8.buffer,u,l.data.byteLength),B=new Uint8Array(l.data);for(let q=0;q<l.data.byteLength;++q)A[q]=B[q]}d.set(+g,{type:k.type,ptr:u,size:l.data.byteLength,
success:!0})}).catch(l=>{--a.outstandingRequestCount;0===a.outstandingRequestCount&&a.layerView.updatingFlagChanged();y.isAbortError(l)||(this.dbg(4,`requestID:${g} failed, error=${l.toString()}`),d.set(+g,{type:k.type,ptr:0,size:0,success:!1}))})}})};e.updateWasmCamera=function(a){this._vxl.set_projection_matrix.apply(this._vxl,a.projectionMatrix);this._vxl.set_view_matrix.apply(this._vxl,a.viewMatrix);this._vxl.set_near_far(a.near,a.far)};e.isUpdating=function(a){return!this._vxl&&this._vxlPromise?
!0:this._layers.has(a)?0<this._layers.get(a).outstandingRequestCount:!1};e.setEnabled=function(a,b){this._layers.forEach((c,d)=>{c.layerView===a&&(this._vxl.set_enabled(d,b),this._renderPluginContext.requestRender())})};e.setSlices=function(a,b){return this._doMaskedUIUpdate(a,{mask:2,slices:{planes:b,currentEditPlane:-1}},!0)};e.setDynamicSections=function(a,b){return this._doMaskedUIUpdate(a,{mask:4,dynamicSections:{planes:b,currentEditPlane:-1}},!0)};e.setStaticSections=function(a,b){return this._doMaskedUIUpdate(a,
{mask:1,staticSections:b},!0)};e.setCurrentVariable=function(a,b){return this._doMaskedUIUpdate(a,{mask:1024,currentVariable:b},!0)};e.setRenderMode=function(a,b){return this._doMaskedUIUpdate(a,{mask:8192,renderMode:b},!0)};e._doMaskedUIUpdate=function(a,b,c){if(!this._vxl)return!1;let d=!1;this._layers.forEach((f,h)=>{f.layerView===a&&(f={str:JSON.stringify(b),byteCount:0,ptr:0,isReusable:!1},this._AllocateBlock(f)&&(d=1===this._vxl.handle_masked_ui_update(h,f.ptr,f.byteCount)?!0:!1,f.isReusable||
this._vxl._free(f.ptr)))});d&&c&&this._renderPluginContext.requestRender();return d};e.addVoxelLayer=function(a){if(!this._vxl){const b={layerView:a,resolveCallback:null,rejectCallback:null};a=new Promise((c,d)=>{b.resolveCallback=c;b.rejectCallback=d});this._newLayers.push(b);return a}a=this._addVoxelLayer(a);return 0>a?Promise.reject(-1):Promise.resolve(a)};e.removeVoxelLayer=function(a){if(!this._vxl){var b=this._newLayers.findIndex(d=>a===d.layerView);0<=b&&(this._newLayers[b].resolveCallback(-1),
this._newLayers.splice(b,1));b=this._newLayers.length;0===b&&(this.dbg(1," no voxel layers left after removing a layer, removing RenderPlugin and destroying"),this.destroy());return b}let c=-1;this._layers.forEach((d,f)=>{d.layerView===a&&(c=f,d.abortController.abort(),this._vxl.remove_layer(c))});0<=c&&this._layers.delete(c);b=this._layers.size;0===b&&(this.dbg(1," no voxel layers left after removing a layer, removing RenderPlugin and destroying"),this.destroy());return b};e._getBlockSize=function(a){for(const b of this._wasmMemBlockSizes)if(a<
b)return b;return-1};e._AllocateBlock=function(a){a.byteCount=this._vxl.lengthBytesUTF8(a.str)+1;const b=this._getBlockSize(a.byteCount);0>b?(a.isReusable=!1,a.ptr=this._vxl._malloc(a.byteCount)):(a.isReusable=!0,a.ptr=this._wasmMemBlocks.get(b),0===a.ptr&&(a.ptr=this._vxl._malloc(b),this._wasmMemBlocks.set(b,a.ptr)));return 0!==a.ptr?(this._vxl.stringToUTF8(a.str,a.ptr,a.byteCount),!0):!1};e._getTimeArgs=function(a){let b=-Number.MAX_VALUE,c=Number.MAX_VALUE,d=!1;m.isSome(a)&&(a.isAllTime?d=!0:(m.isSome(a.start)&&
(d=!0,b=a.start.getTime()/1E3),m.isSome(a.end)&&(d=!0,c=a.end.getTime()/1E3)));return{startTime:b,endTime:c,useTime:d}};e._addVoxelLayer=function(a){var b,c=a.layer,d=-1;d=c.getConfiguration();if(1>d.length)return-1;const f={str:d,byteCount:0,ptr:0,isReusable:!1};if(!this._AllocateBlock(f))return-1;d=this._getTimeArgs(null==(b=this._view)?void 0:b.timeExtent);b=this._view.spatialReference.isWGS84&&c.spatialReference.isWGS84?111319.49079327357:1;d=this._vxl.add_layer(c.serviceRoot,f.ptr,f.byteCount,
b,b,d.startTime,d.endTime,d.useTime,this.toWasmQuality(this._view.qualityProfile));f.isReusable||this._vxl._free(f.ptr);if(0<=d){c=new AbortController;this._layers.set(d,{layerView:a,responses:new Map,outstandingRequestCount:0,abortController:c});if(!this._halfIntTexturesAvailable){c=[];b="";for(const h of a.layer.variables)if("Int16"===h.renderingFormat.type||"UInt16"===h.renderingFormat.type)c.push(h.name),h.id===a.layer.style.currentVariableId&&(b=h.name);""!==b&&p.error("#addVoxelLayer_error()",
a.layer,`The voxel layer '${a.layer.title}' cannot render the current variable '${b}' in this browser`);0<c.length&&p.warn("#addVoxelLayer_warning()",a.layer,`The voxel layer '${a.layer.title}' cannot render the variables '${c.toString()}' in this browser`)}return d}return-1};e.prepareRender=function(a){if(this._vxl){var b=a.viewForward;a=a.eye;this._vxl.update_camera_pos_and_direction(a[0],a[1],a[2],b[0],b[1],b[2]);b=this._vxl.cull();this.dbg(2,"missingResourceCount\x3d"+b);this._moreToLoad=0<b;
this._havePreparedWithAllLayers=0===this._newLayers.length}};e.render=function(a){if(!this._vxl||a.pass!==this._renderPass||a.slot!==this._renderSlot)return!1;for(var b of this._newLayers){const c=this._addVoxelLayer(b.layerView);-1===c?b.rejectCallback(-1):b.resolveCallback(c)}this._newLayers=[];if(0===this._layers.size)return this.dbg(4,"No voxel layers but RenderPlugin instance is being asked to render!"),!1;this._renderTargetToRestore={fbo:this._rctx.getBoundFramebufferObject(),viewport:this._rctx.getViewport()};
this._syncRequestsResponses();this._lastFrameWasStationary=this._view.stationary;this._vxl.begin_color_frame(!this._view.stationary||this._moreToLoad,a.scenelightingData.lightingMainDirection[0],a.scenelightingData.lightingMainDirection[1],a.scenelightingData.lightingMainDirection[2]);b=this._renderTargetToRestore.viewport;if(b.width!==this._viewportWidth||b.height!==this._viewportHeight)this._viewportWidth=b.width,this._viewportHeight=b.height,this._vxl.set_viewport(b.width,b.height);0===b.x&&0===
b.y||this.dbg(4,"Unsupported viewport parameters detected!");this.updateWasmCamera(a.camera);this._vxl.draw();this._renderTargetToRestore.fbo=null;a.rctx.externalTextureUnitUpdate(this._vxl.get_texture_units_bound_in_frame(),this._vxl.get_active_texture_unit());a.rctx.externalVertexArrayObjectUpdate();a.rctx.externalVertexBufferUpdate();this._rctx.externalProgramUpdate();(this._moreToLoad||!this._havePreparedWithAllLayers&&0<this._layers.size)&&this._renderPluginContext.requestRender();return!0};
e.destroy=function(){this.dbg(1,"--destroy--");this.removeRenderPlugin();this._readyWatchHandle=m.removeMaybe(this._readyWatchHandle);this._qualityWatchHandle=m.removeMaybe(this._qualityWatchHandle);this._timeExtentWatchHandle=m.removeMaybe(this._timeExtentWatchHandle);this._stationaryWatchHandle=m.removeMaybe(this._stationaryWatchHandle);this._vxl&&(this._layers.forEach(a=>{a.abortController.abort()}),this._wasmMemBlocks.forEach(a=>{0!==a&&this._vxl._free(a)}),this._vxl.uninitialize_voxel_wasm(),
this._vxl=null)};e.initializeWasm=function(a){if(this._vxl)return Promise.resolve();this._vxlPromise||(this._vxlPromise=z.loadVoxelWASM(a).then(b=>{var c;this._vxl=b;this._vxlPromise=null;if(0>=this._newLayers.length)this.dbg(1," no voxel layers left after WASM downloaded, removing RenderPlugin and destroying"),this.destroy();else{b=this._getTimeArgs(null==(c=this._view)?void 0:c.timeExtent);c=this._vxl.addFunction(this.restoreFramebuffer.bind(this),"v");var d=this._vxl.addFunction(this.setBlendState.bind(this),
"viiii"),f=this._vxl.addFunction(this.setFrontFace.bind(this),"vi"),h=this._vxl.addFunction(this.setRasterizerState.bind(this),"vi"),g=this._vxl.addFunction(this.setDepthStencilStateFunction.bind(this),"viii"),k=this._vxl.addFunction(this.setViewport.bind(this),"viiii"),t=this._vxl.addFunction(this.bindPreviousDepthToSlot.bind(this),"iii");this._vxl.initialize_voxel_wasm(c,d,f,h,g,k,t,b.startTime,b.endTime,b.useTime);this._renderPluginContext&&this._renderPluginContext.requestRender()}}).catch(()=>
{for(const b of this._newLayers)b.rejectCallback(-2);this.dbg(4," WASM failed to download, removing RenderPlugin and destroying");this.destroy()}));return this._vxlPromise};e.pickDepth=function(a,b,c){if(!this._vxl||!this._rctx||0===this._layers.size)return null;const d=c.viewport[3]-b;if(0>a||a>c.viewport[2]||0>b||b>c.viewport[3])return this.dbg(4,`pickDepth: outOfRange, screenXY=[${a}, ${d}], vp=[${c.viewport.toString()}]`),null;this._renderTargetToRestore={fbo:this._rctx.getBoundFramebufferObject(),
viewport:this._rctx.getViewport()};b=c.viewForward;const f=c.eye;this._vxl.update_camera_pos_and_direction(f[0],f[1],f[2],b[0],b[1],b[2]);this.updateWasmCamera(c);this._vxl.begin_frame();a=this._vxl.pick_depth(a,d);this._renderTargetToRestore.fbo=null;this._rctx.externalTextureUnitUpdate(this._vxl.get_texture_units_bound_in_frame(),this._vxl.get_active_texture_unit());this._rctx.externalVertexArrayObjectUpdate();this._rctx.externalVertexBufferUpdate();this._rctx.externalProgramUpdate();return a.success?
a.distanceToCamera:null};e.toWasmQuality=function(a){switch(a){case "low":return 0;case "medium":return 1;case "high":return 2}};v._createClass(r,[{key:"canRender",get:function(){return!!this._vxl&&"local"===this._view.viewingMode}}]);return r}()});