// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Collection ../core/Handles ../core/Logger ../core/maybe ../core/MultiOriginJSONSupport ../core/promiseUtils ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/has ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/reader ../core/accessorSupport/decorators/subclass ../chunks/vec3 ../chunks/vec3f64 ./Layer ./VoxelWasmManager ./mixins/APIKeyMixin ./mixins/ArcGISService ./mixins/OperationalLayer ./mixins/PortalLayer ./mixins/ScaleRangeLayer ./mixins/SceneService ./support/arcgisLayerUrl ./support/commonProperties ./support/VoxelDynamicSection ./support/VoxelSection ./support/VoxelSlice ./support/VoxelStyle ./support/VoxelVariable ./support/VoxelVolume ./support/VoxelVolumeIndex".split(" "),
function(u,f,l,z,c,k,A,B,m,g,S,T,U,C,D,E,F,G,n,H,I,J,K,L,M,N,q,v,w,x,O,P,Q,R){const r=c.getLogger(" esri.layers.VoxelLayer");c=function(t){function p(a){a=t.call(this,a)||this;a.serviceRoot="";a.popupEnabled=!0;a.operationalLayerType="Voxel";a.legendEnabled=!0;a.title=null;a.sections=new l;a.style=null;a.opacity=1;a.variables=new l;a.volumes=new l;a.index=null;a.minScale=0;a.maxScale=0;a.type="voxel";a._dbgFlags=new Set;a._handles=new z;a.version={major:Number.NaN,minor:Number.NaN,versionString:""};
return a}u._inheritsLoose(p,t);var d=p.prototype;d.destroy=function(){this._handles=k.destroyMaybe(this._handles)};d.dbg=function(a,b){this._dbgFlags.has(a)&&(3===a?r.error(b):r.warn(b))};d.load=function(a){const b=k.isSome(a)?a.signal:null;a=this.loadFromPortal({supportedTypes:["Scene Service"]},a).catch(B.throwIfAbortError).then(()=>this._fetchService(b)).then(()=>this.serviceRoot=this.url);this.addResolvingPromise(a);return Promise.resolve(this)};d.getConfiguration=function(){this._handles.add([m.react(()=>
this._getRenderMode(),b=>this._pushRenderModeToWasm(b)),m.react(()=>this._getCurrentVariableId(),b=>this._pushCurrentVariableIdToWasm(b)),m.react(()=>this._getDynamicSections(),b=>this._pushDynamicSectionsToWasm(b)),m.react(()=>this._getSlices(),b=>this._pushSlicesToWasm(b)),m.react(()=>this._getSections(),b=>this._pushSectionsToWasm(b))]);const a={layerType:this.operationalLayerType,version:this.version.versionString,name:this.title,spatialReference:this.spatialReference,fullExtent:this.fullExtent,
volumes:this.volumes.toJSON(),variables:this.variables.toJSON(),index:this.index.toJSON(),sections:this.sections.toJSON(),style:this.style};return a.index&&this.index.isValid()?JSON.stringify(a):""};d.readVersion=function(a,b){return t.prototype.parseVersionString.call(this,a)};d._getSections=function(){const a=[];for(const b of this.sections)a.push(new w({enabled:b.enabled,href:b.href,id:b.id,label:b.label,normal:b.normal,point:b.point,sizeInPixel:b.sizeInPixel,slices:b.slices,timeId:b.timeId,variableId:b.variableId}));
return a};d._pushSectionsToWasm=function(a){this.dbg(2,"VoxelLayer._pushSectionsToWasm() called");n.getInstance().setLayerStaticSections(this,a)||this.dbg(3,"VoxelLayer._pushSectionsToWasm() failed!")};d._isPlaneValid=function(a,b,h){if(!(a.point&&Array.isArray(a.point)&&3===a.point.length&&a.normal&&Array.isArray(a.normal)&&3===a.normal.length))return!1;for(let e=0;3>e;++e){const y=a.point[e];if(0>y||y>=h[b[e]].size)return!1}b=F.fromValues(a.normal[0],a.normal[1],a.normal[2]);E.normalize(b,b);if(1E-6>
Math.abs(b[0])+Math.abs(b[1])+Math.abs(b[2]))return!1;a.normal[0]=b[0];a.normal[1]=b[1];a.normal[2]=b[2];return!0};d.getVariableStyle=function(a){let b=-1;b=k.isSome(a)?a:this._getCurrentVariableId();if(null==this||!this.style.variableStyles||-1===b)return null;a=this.style.variableStyles.findIndex(h=>h.variableId===b);return 0>a?null:this.style.variableStyles.getItemAt(a)};d.getVariable=function(a){let b=-1;b=k.isSome(a)?a:this._getCurrentVariableId();if(!this.variables||-1===b)return null;a=this.variables.findIndex(h=>
h.id===b);return 0>a?null:this.variables.getItemAt(a)};d._getVolume=function(a){const b=this.getVariable(a);return k.isSome(b)?this.volumes.find(({id:h})=>h===b.volumeId):null};d._getVolumeStyle=function(a){const b=this.getVariable(a);return k.isSome(b)?this.style.volumeStyles.find(({volumeId:h})=>h===b.volumeId):null};d._getSlices=function(){const a=[],b=this._getVolume(null);if(!k.isSome(b)||!b.isVolumeValid())return a;const h=this._getVolumeStyle(null);if(!k.isSome(h))return a;for(const e of h.slices)this._isPlaneValid(e,
[0,1,b.getZDimension()],b.dimensions)?a.push(new x({enabled:e.enabled,label:e.label,point:e.point,normal:e.normal})):a.push(new x({enabled:!1,label:"invalid",point:e.point,normal:e.normal}));return a};d._pushSlicesToWasm=function(a){this.dbg(2,"VoxelLayer._pushSlicesToWasm() called!");n.getInstance().setLayerSlices(this,a)||this.dbg(3,"VoxelLayer._pushSlicesToWasm() failed!")};d._getDynamicSections=function(){const a=[],b=this._getVolume(null);if(!k.isSome(b)||!b.isVolumeValid())return a;const h=
this._getVolumeStyle(null);if(!k.isSome(h))return a;for(const e of h.dynamicSections)this._isPlaneValid(e,[0,1,b.getZDimension()],b.dimensions)?a.push(new v({enabled:e.enabled,label:e.label,point:e.point,normal:e.normal})):a.push(new v({enabled:!1,label:"invalid",point:e.point,normal:e.normal}));return a};d._pushDynamicSectionsToWasm=function(a){this.dbg(2,"VoxelLayer._pushDynamicSectionsToWasm() called!");n.getInstance().setLayerDynamicSections(this,a)||this.dbg(3,"VoxelLayer._updateDynamicSections() failed!")};
d._getCurrentVariableId=function(){return this.style?this.style.currentVariableId:-1};d._pushCurrentVariableIdToWasm=function(a){this.dbg(2,"VoxelLayer._pushCurrentVariableIdToWasm() called!");n.getInstance().setLayerCurrentVariable(this,a)||this.dbg(3,"VoxelLayer._pushCurrentVariableIdToWasm() failed!")};d._getRenderMode=function(){return this.style?this.style.renderMode:"volume"};d._pushRenderModeToWasm=function(a){this.dbg(2,"VoxelLayer._pushRenderModeToWasm() called!");n.getInstance().setLayerRenderMode(this,
a)||this.dbg(3,"VoxelLayer.setLayerRenderMode() failed!")};u._createClass(p,[{key:"url",set:function(a){this._set("url",N.sanitizeUrl(a,r))}}]);return p}(M.SceneService(I.ArcGISService(J.OperationalLayer(K.PortalLayer(L.ScaleRangeLayer(A.MultiOriginJSONMixin(H.APIKeyMixin(G))))))));f.__decorate([g.property(q.popupEnabled)],c.prototype,"popupEnabled",void 0);f.__decorate([g.property({type:["Voxel"]})],c.prototype,"operationalLayerType",void 0);f.__decorate([g.property(q.legendEnabled)],c.prototype,
"legendEnabled",void 0);f.__decorate([g.property({json:{write:!0}})],c.prototype,"title",void 0);f.__decorate([g.property(q.url)],c.prototype,"url",null);f.__decorate([g.property({type:l.ofType(w),json:{write:!0,origins:{"web-scene":{name:"layerDefinition.sections",write:!0},service:{write:!1}}}})],c.prototype,"sections",void 0);f.__decorate([g.property({type:O,json:{write:!0,origins:{"web-scene":{name:"layerDefinition.style",write:!0},service:{write:!1}}}})],c.prototype,"style",void 0);f.__decorate([g.property({type:["show",
"hide"]})],c.prototype,"listMode",void 0);f.__decorate([g.property({type:Number,range:{min:0,max:1},nonNullable:!0,json:{read:!1,write:!1,origins:{"web-scene":{read:!1,write:!1},"portal-item":{read:!1,write:!1}}}})],c.prototype,"opacity",void 0);f.__decorate([g.property({type:l.ofType(P)})],c.prototype,"variables",void 0);f.__decorate([g.property({type:l.ofType(Q)})],c.prototype,"volumes",void 0);f.__decorate([g.property({type:R})],c.prototype,"index",void 0);f.__decorate([g.property({type:Number,
json:{name:"layerDefinition.minScale",read:!1,write:!1,origins:{service:{read:!1,write:!1}}}})],c.prototype,"minScale",void 0);f.__decorate([g.property({type:Number,json:{name:"layerDefinition.maxScale",read:!1,write:!1,origins:{service:{read:!1,write:!1}}}})],c.prototype,"maxScale",void 0);f.__decorate([g.property({json:{read:!1},readOnly:!0})],c.prototype,"type",void 0);f.__decorate([g.property({readOnly:!0,json:{name:"serviceVersion"}})],c.prototype,"version",void 0);f.__decorate([C.reader("service",
"version")],c.prototype,"readVersion",null);return c=f.__decorate([D.subclass("esri.layers.VoxelLayer")],c)});