// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../request ../core/Collection ../core/Error ../core/Handles ../core/lang ../core/MultiOriginJSONSupport ../core/object ../core/promiseUtils ../core/urlUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/reader ../core/accessorSupport/decorators/subclass ../core/accessorSupport/decorators/writer ../geometry/Extent ./Layer ./WebTileLayer ./mixins/BlendLayer ./mixins/OperationalLayer ./mixins/PortalLayer ./mixins/RefreshableLayer ./mixins/ScaleRangeLayer ./support/TileInfo ./support/TileInfoTilemapCache ./support/WMTSLayerInfo ./support/WMTSSublayer ./support/wmtsUtils".split(" "),
function(l,f,v,B,w,x,y,e,C,z,u,h,S,n,D,E,F,G,H,I,J,K,L,M,N,O,P,p,r){function Q(t,m){return t.map(g=>{const a=new p;a.read(g,m);return a})}const A={"image/png":".png","image/png8":".png","image/png24":".png","image/png32":".png","image/jpg":".jpg","image/jpeg":".jpeg","image/gif":".gif","image/bmp":".bmp","image/tiff":".tif","image/jpgpng":"","image/jpegpng":"","image/unknown":""},R=new Set("version service request layer style format tilematrixset tilematrix tilerow tilecol".split(" "));e=function(t){function m(...a){var b=
t.call(this,...a)||this;b._sublayersHandles=new x;b.copyright="";b.customParameters=null;b.customLayerParameters=null;b.fullExtent=null;b.operationalLayerType="WebTiledLayer";b.resourceInfo=null;b.serviceMode="RESTful";b.sublayers=null;b.type="wmts";b.version="1.0.0";b.watch("activeLayer",(c,d)=>{d&&(d.layer=null);c&&(c.layer=l._assertThisInitialized(b))},!0);b.watch("sublayers",(c,d)=>{d&&(d.forEach(k=>{k.layer=null}),b._sublayersHandles.removeAll(),b._sublayersHandles=null);c&&(c.forEach(k=>{k.layer=
l._assertThisInitialized(b)}),b._sublayersHandles||(b._sublayersHandles=new x),b._sublayersHandles.add([c.on("after-add",({item:k})=>{k.layer=l._assertThisInitialized(b)}),c.on("after-remove",({item:k})=>{k.layer=null})]))},!0);return b}l._inheritsLoose(m,t);var g=m.prototype;g.normalizeCtorArgs=function(a,b){return"string"===typeof a?{url:a,...b}:a};g.load=function(a){if("KVP"!==this.serviceMode&&"RESTful"!==this.serviceMode)console.error("WMTS mode could only be 'KVP' or 'RESTful'");else return this.addResolvingPromise(this.loadFromPortal({supportedTypes:["WMTS"]},
a).catch(z.throwIfAbortError).then(()=>this._fetchService(a)).catch(b=>{z.throwIfAbortError(b);throw new w("wmtslayer:unsupported-service-data","Invalid response from the WMTS service.",{error:b});})),Promise.resolve(this)};g.readActiveLayerFromService=function(a,b,c){this.activeLayer||(this.activeLayer=new p);(a=b.layers.find(d=>d.id===this.activeLayer.id))||(a=b.layers[0]);this.activeLayer.read(a,c);return this.activeLayer};g.readActiveLayerFromItemOrWebDoc=function(a,b){const {templateUrl:c,wmtsInfo:d}=
b;a=c?this._getLowerCasedUrlParams(c):null;b=null==d?void 0:d.layerIdentifier;let k=null;const q=null==d?void 0:d.tileMatrixSet;q&&(Array.isArray(q)?q.length&&(k=q[0]):k=q);return new p({id:b,imageFormat:null==a?void 0:a.format,styleId:null==a?void 0:a.style,tileMatrixSetId:k})};g.writeActiveLayer=function(a,b,c,d){a=this.activeLayer;b.templateUrl=this.getUrlTemplate(a.id,a.tileMatrixSetId,a.imageFormat,a.styleId);c=C.getDeepValue("tileMatrixSet.tileInfo",a);b.tileInfo=c?c.toJSON(d):null;b.wmtsInfo=
{...b.wmtsInfo,layerIdentifier:a.id,tileMatrixSet:a.tileMatrixSetId}};g.readCustomParameters=function(a,b){return(a=b.wmtsInfo)?this._mergeParams(a.customParameters,a.url):null};g.readServiceMode=function(a,b){return-1<b.templateUrl.indexOf("?")?"KVP":"RESTful"};g.readSublayersFromService=function(a,b,c){return Q(b.layers,c)};g.createWebTileLayer=function(a){const b=this.getUrlTemplate(this.activeLayer.id,this.activeLayer.tileMatrixSetId,this.activeLayer.imageFormat,this.activeLayer.styleId),c=this._getTileMatrixSetById(a.tileMatrixSetId).tileInfo,
d=a.fullExtent;a=new P.default({layerIdentifier:a.id,tileMatrixSet:a.tileMatrixSetId,url:this.url});this.customLayerParameters&&(a.customLayerParameters=this.customLayerParameters);this.customParameters&&(a.customParameters=this.customParameters);return new H({fullExtent:d,urlTemplate:b,tileInfo:c,wmtsInfo:a})};g.fetchTile=function(a,b,c){a=this.getTileUrl(a,b,c);return v(a,{responseType:"image"}).then(d=>d.data)};g.findSublayerById=function(a){return this.sublayers.find(b=>b.id===a)};g.getTileUrl=
function(a,b,c){var d=this._getTileMatrixSetById(this.activeLayer.tileMatrixSetId).tileInfo.lods[a];a=d?d.levelValue?d.levelValue:`${d.level}`:`${a}`;(d=this.resourceInfo?"":r.getTileUrlFromResourceUrls({dimensionMap:this.dimensionMap,layerMap:this.layerMap},this.activeLayer.id,this.activeLayer.tileMatrixSetId,this.activeLayer.imageFormat,this.activeLayer.styleId,a,b,c))||(d=this.getUrlTemplate(this.activeLayer.id,this.activeLayer.tileMatrixSetId,this.activeLayer.imageFormat,this.activeLayer.styleId).replace(/\{level\}/gi,
a).replace(/\{row\}/gi,`${b}`).replace(/\{col\}/gi,`${c}`));return d=this._appendCustomLayerParameters(d)};g.getUrlTemplate=function(a,b,c,d){if(!this.resourceInfo){var k=r.getTileUrlTemplateFromResourceUrls({dimensionMap:this.dimensionMap,layerMap:this.layerMap},a,b,d);if(k)return k}return"KVP"===this.serviceMode?this.url+"?SERVICE\x3dWMTS\x26VERSION\x3d"+this.version+"\x26REQUEST\x3dGetTile\x26LAYER\x3d"+a+"\x26STYLE\x3d"+d+"\x26FORMAT\x3d"+c+"\x26TILEMATRIXSET\x3d"+b+"\x26TILEMATRIX\x3d{level}\x26TILEROW\x3d{row}\x26TILECOL\x3d{col}":
"RESTful"===this.serviceMode?(k="",A[c.toLowerCase()]&&(k=A[c.toLowerCase()]),this.url+a+"/"+d+"/"+b+"/{level}/{row}/{col}"+k):""};g._fetchService=function(){var a=l._asyncToGenerator(function*(b){let c;if(this.resourceInfo)"KVP"===this.resourceInfo.serviceMode&&(this.url+=-1<this.url.indexOf("?")?"":"?"),c={ssl:!1,data:this.resourceInfo};else try{c=yield this._getCapabilities(this.serviceMode,b)}catch{const d="KVP"===this.serviceMode?"RESTful":"KVP";try{c=yield this._getCapabilities(d,b),this.serviceMode=
d}catch(k){throw new w("wmtslayer:unsupported-service-data","Services does not support RESTful or KVP service modes.",{error:k});}}c.data=this.resourceInfo?r.parseResourceInfo(c.data):r.parseCapabilities(c.data,{serviceMode:this.serviceMode,url:this.url});c.data&&this.read(c.data,{origin:"service"})});return function(b){return a.apply(this,arguments)}}();g._getCapabilities=function(){var a=l._asyncToGenerator(function*(b,c){b=this._getCapabilitiesUrl(b);return yield v(b,{...c,responseType:"text"})});
return function(b,c){return a.apply(this,arguments)}}();g._getTileMatrixSetById=function(a){return this.findSublayerById(this.activeLayer.id).tileMatrixSets.find(b=>b.id===a)};g._appendCustomParameters=function(a){return this._appendParameters(a,this.customParameters)};g._appendCustomLayerParameters=function(a){return this._appendParameters(a,{...y.clone(this.customParameters),...this.customLayerParameters})};g._appendParameters=function(a,b){a=u.urlToObject(a);b=u.objectToQuery({...a.query,...b});
return""===b?a.path:`${a.path}?${b}`};g._getCapabilitiesUrl=function(a){let b;this.url=this.url.split("?")[0];"KVP"===a?b=this.url+"?request\x3dGetCapabilities\x26service\x3dWMTS\x26version\x3d"+this.version:"RESTful"===a&&(b=this.url+"/"+this.version+"/WMTSCapabilities.xml");return b=this._appendCustomParameters(b)};g._getLowerCasedUrlParams=function(a){if(!a)return null;const b=u.urlToObject(a).query;if(!b)return null;const c={};Object.keys(b).forEach(d=>{c[d.toLowerCase()]=b[d]});return c};g._mergeParams=
function(a,b){const c=this._getLowerCasedUrlParams(b);c&&(b=Object.keys(c),b.length&&(a=a?y.clone(a):{},b.forEach(d=>{a.hasOwnProperty(d)||R.has(d)||(a[d]=c[d])})));return a};l._createClass(m,[{key:"activeLayer",get:function(){return this._get("activeLayer")},set:function(a){this._set("activeLayer",a)}},{key:"fullExtents",get:function(){return this.activeLayer.fullExtents}},{key:"supportedSpatialReferences",get:function(){return this.activeLayer.tileMatrixSets.map(a=>a.tileInfo.spatialReference).toArray()}},
{key:"tilemapCache",get:function(){var a,b;const c=null==(a=this.activeLayer)?void 0:null==(b=a.tileMatrixSet)?void 0:b.tileInfo;return new O(c)}},{key:"title",get:function(){var a,b;return null!=(a=null==(b=this.activeLayer)?void 0:b.title)?a:"Layer"},set:function(a){a?this._override("title",a):this._clearOverride("title")}},{key:"url",get:function(){return this._get("url")},set:function(a){a&&"/"===a.substr(-1)?this._set("url",a.slice(0,-1)):this._set("url",a)}}]);return m}(I.BlendLayer(L.RefreshableLayer(M.ScaleRangeLayer(J.OperationalLayer(K.PortalLayer(e.MultiOriginJSONMixin(G)))))));
f.__decorate([h.property()],e.prototype,"dimensionMap",void 0);f.__decorate([h.property()],e.prototype,"layerMap",void 0);f.__decorate([h.property({type:p,json:{origins:{"web-document":{write:{ignoreOrigin:!0}}}}})],e.prototype,"activeLayer",null);f.__decorate([n.reader("service","activeLayer",["layers"])],e.prototype,"readActiveLayerFromService",null);f.__decorate([n.reader(["web-document","portal-item"],"activeLayer",["wmtsInfo"])],e.prototype,"readActiveLayerFromItemOrWebDoc",null);f.__decorate([E.writer(["web-document",
"portal-item"],"activeLayer",{templateUrl:{type:String},tileInfo:{type:N},"wmtsInfo.layerIdentifier":{type:String},"wmtsInfo.tileMatrixSet":{type:String}})],e.prototype,"writeActiveLayer",null);f.__decorate([h.property({type:String,value:"",json:{write:!0}})],e.prototype,"copyright",void 0);f.__decorate([h.property({type:["show","hide"]})],e.prototype,"listMode",void 0);f.__decorate([h.property({json:{origins:{"web-document":{read:{source:["wmtsInfo.customParameters","wmtsInfo.url"]},write:{target:"wmtsInfo.customParameters"}},
"portal-item":{read:{source:["wmtsInfo.customParameters","wmtsInfo.url"]},write:{target:"wmtsInfo.customParameters"}}}}})],e.prototype,"customParameters",void 0);f.__decorate([n.reader(["portal-item","web-document"],"customParameters")],e.prototype,"readCustomParameters",null);f.__decorate([h.property({json:{origins:{"web-document":{read:{source:"wmtsInfo.customLayerParameters"},write:{target:"wmtsInfo.customLayerParameters"}},"portal-item":{read:{source:"wmtsInfo.customLayerParameters"},write:{target:"wmtsInfo.customLayerParameters"}}}}})],
e.prototype,"customLayerParameters",void 0);f.__decorate([h.property({type:F,json:{write:{ignoreOrigin:!0},origins:{"web-document":{read:{source:"fullExtent"}},"portal-item":{read:{source:"fullExtent"}}}}})],e.prototype,"fullExtent",void 0);f.__decorate([h.property({readOnly:!0})],e.prototype,"fullExtents",null);f.__decorate([h.property({type:["WebTiledLayer"]})],e.prototype,"operationalLayerType",void 0);f.__decorate([h.property()],e.prototype,"resourceInfo",void 0);f.__decorate([h.property()],e.prototype,
"serviceMode",void 0);f.__decorate([n.reader(["portal-item","web-document"],"serviceMode",["templateUrl"])],e.prototype,"readServiceMode",null);f.__decorate([h.property({type:B.ofType(p)})],e.prototype,"sublayers",void 0);f.__decorate([n.reader("service","sublayers",["layers"])],e.prototype,"readSublayersFromService",null);f.__decorate([h.property({readOnly:!0})],e.prototype,"supportedSpatialReferences",null);f.__decorate([h.property({readOnly:!0})],e.prototype,"tilemapCache",null);f.__decorate([h.property({json:{read:{source:"title"}}})],
e.prototype,"title",null);f.__decorate([h.property({json:{read:!1},readOnly:!0,value:"wmts"})],e.prototype,"type",void 0);f.__decorate([h.property({json:{origins:{service:{read:{source:"tileUrl"}},"web-document":{read:{source:"wmtsInfo.url"},write:{target:"wmtsInfo.url"}},"portal-item":{read:{source:"wmtsInfo.url"},write:{target:"wmtsInfo.url"}}}}})],e.prototype,"url",null);f.__decorate([h.property()],e.prototype,"version",void 0);return e=f.__decorate([D.subclass("esri.layers.WMTSLayer")],e)});