// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass".split(" "),function(m,b,d,c,q,r,t,n){let g=function(e){function f(){var a=e.apply(this,arguments)||this;a.minTotalNumberOfFeatures=2E3;a.maxTotalNumberOfFeatures=5E4;a.maxTotalNumberOfPrimitives=17E5;a.snapshotAvailable=
!0;a.polygonLodFactor=1;a.polylineLodFactor=1;return a}m._inheritsLoose(f,e);return f}(d);b.__decorate([c.property()],g.prototype,"minTotalNumberOfFeatures",void 0);b.__decorate([c.property()],g.prototype,"maxTotalNumberOfFeatures",void 0);b.__decorate([c.property()],g.prototype,"maxTotalNumberOfPrimitives",void 0);b.__decorate([c.property()],g.prototype,"snapshotAvailable",void 0);b.__decorate([c.property()],g.prototype,"polygonLodFactor",void 0);b.__decorate([c.property()],g.prototype,"polylineLodFactor",
void 0);g=b.__decorate([n.subclass("esri.views.3d.support.QualitySettings.Graphics3DSettings")],g);let h=function(e){function f(){var a=e.apply(this,arguments)||this;a.lodFactor=1;return a}m._inheritsLoose(f,e);return f}(d);b.__decorate([c.property()],h.prototype,"lodFactor",void 0);h=b.__decorate([n.subclass("esri.views.3d.support.QualitySettings.LoDFactorSettings")],h);let p=function(e){function f(){var a=e.apply(this,arguments)||this;a.lodCrossfadeinDuration=0;a.lodCrossfadeoutDuration=0;a.lodCrossfadeUncoveredDuration=
0;return a}m._inheritsLoose(f,e);return f}(h);p=b.__decorate([n.subclass("esri.views.3d.support.QualitySettings.LoDFactor3DObjectSettings")],p);let k=function(e){function f(){var a=e.apply(this,arguments)||this;a["3dObject"]=new p;a.point=new h;a.integratedMesh=new h;a.pointCloud=new h;a.uncompressedTextureDownsamplingEnabled=!1;return a}m._inheritsLoose(f,e);return f}(d);b.__decorate([c.property({type:p})],k.prototype,"3dObject",void 0);b.__decorate([c.property({type:h})],k.prototype,"point",void 0);
b.__decorate([c.property({type:h})],k.prototype,"integratedMesh",void 0);b.__decorate([c.property({type:h})],k.prototype,"pointCloud",void 0);b.__decorate([c.property()],k.prototype,"uncompressedTextureDownsamplingEnabled",void 0);k=b.__decorate([n.subclass("esri.views.3d.support.QualitySettings.SceneServiceSettings")],k);let l=function(e){function f(){var a=e.apply(this,arguments)||this;a.lodBias=0;a.angledSplitBias=1;a.reduceTileLevelDifferences=!0;a.textureFadeDuration=500;return a}m._inheritsLoose(f,
e);return f}(d);b.__decorate([c.property()],l.prototype,"lodBias",void 0);b.__decorate([c.property()],l.prototype,"angledSplitBias",void 0);b.__decorate([c.property()],l.prototype,"reduceTileLevelDifferences",void 0);b.__decorate([c.property()],l.prototype,"textureFadeDuration",void 0);l=b.__decorate([n.subclass("esri.views.3d.support.QualitySettings.TiledSurfaceSettings")],l);d=function(e){function f(){var a=e.apply(this,arguments)||this;a.graphics3D=new g;a.sceneService=new k;a.tiledSurface=new l;
a.antialiasingEnabled=!0;a.physicallyBasedRenderingEnabled=!1;a.highQualityTransparency=!0;return a}m._inheritsLoose(f,e);return f}(d);b.__decorate([c.property({type:g})],d.prototype,"graphics3D",void 0);b.__decorate([c.property({type:k})],d.prototype,"sceneService",void 0);b.__decorate([c.property({type:l})],d.prototype,"tiledSurface",void 0);b.__decorate([c.property()],d.prototype,"antialiasingEnabled",void 0);b.__decorate([c.property()],d.prototype,"physicallyBasedRenderingEnabled",void 0);b.__decorate([c.property()],
d.prototype,"highQualityTransparency",void 0);b.__decorate([c.property()],d.prototype,"memoryLimit",void 0);b.__decorate([c.property()],d.prototype,"additionalCacheMemory",void 0);b.__decorate([c.property()],d.prototype,"frameRate",void 0);b.__decorate([c.property()],d.prototype,"maximumRenderResolution",void 0);b.__decorate([c.property()],d.prototype,"maximumPixelRatio",void 0);return d=b.__decorate([n.subclass("esri.views.3d.support.QualitySettings.QualitySettings")],d)});