// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../core/mathUtils ../../../chunks/mat4 ../../../chunks/mat4f64 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../chunks/SunCalc".split(" "),function(C,D,E,S,y,z,A){function N(h,k,m,f){const d=T,a=E.identity(U);if(1===m)A.SunCalc.getPosition(h,0,0,d),y.set(f,0,0,-1),E.rotateX(a,a,-d.azimuth),E.rotateY(a,a,-d.altitude);else{var c=w.planarDirection;m=c.globalAngles;c=(Math.abs(k[2])-c.localAltitude)/(c.globalAltitude-c.localAltitude);c=D.clamp(c,0,1);1>c?(A.SunCalc.getPosition(h,
k[1],k[0],d),d.azimuth=(1-c)*d.azimuth+c*m.azimuth,d.altitude=(1-c)*d.altitude+c*m.altitude):(d.azimuth=m.azimuth,d.altitude=m.altitude);y.set(f,0,-1,0);E.rotateZ(a,a,-d.azimuth);E.rotateX(a,a,-d.altitude)}y.transformMat4(f,f,a)}function V(h){switch(h){case "disabled":case "sunny":return{direct:1,ambient:1};case "cloudy":return{direct:.8,ambient:1.1};case "rainy":return{direct:.4,ambient:1};case "foggy":return{direct:.3,ambient:1.6}}}function l(h,k,m,f){const d=[];for(let a=0;a<m.length;a++)d[a]=
(f[a]-m[a])*h/k+m[a];return d}const w={local:{altitude:1500,ambientAtNight:.1,ambientAtNoon:.45,ambientAtTwilight:.2,directAtNoon:.65,directAtTwilight:.7},global:{altitude:8E5,ambient:.015,direct:.75},planarDirection:{localAltitude:1E4,globalAltitude:1E6,globalAngles:{azimuth:1.3*Math.PI,altitude:.6*Math.PI}}},W=z.fromValues(.5773502691896258,-.5773502691896258,.5773502691896258),U=S.create(),T={azimuth:0,altitude:0},O=new Date(0);C.ColorAndIntensity=function(){this.ambient={color:z.fromValues(1,
1,1),intensity:.55};this.direct={color:z.fromValues(1,1,1),intensity:.55,directionToLightSource:z.clone(W)};this.noonFactor=.5;this.globalFactor=0};C.computeColorAndIntensity=function(h,k,m,f,d){var a=k[2];y.set(f.ambient.color,1,1,1);f.ambient.intensity=w.global.ambient;y.set(f.direct.color,1,1,1);f.direct.intensity=w.global.direct;var c=D.clamp((Math.abs(a)-w.local.altitude)/(w.global.altitude-w.local.altitude),0,1);f.globalFactor=c;a=A.SunCalc.getTimes(h,k[1],k[0]);if(1>c){{var b=h.valueOf();if(a.polarException===
A.SunCalc.POLAR_EXCEPTION.MIDNIGHT_SUN){var n=b-36E5*(h.getHours()+48)-6E4*h.getMinutes();var g=n+432E6}else a.polarException===A.SunCalc.POLAR_EXCEPTION.POLAR_NIGHT?(n=b-2,g=b-1):(n=a.sunrise.valueOf(),g=a.sunset.valueOf());var u=g-n;var q=n+u/2;var v=u/4;var p=q-v;v=q+v;var x=.06*u;u=n-x/2;n+=x/2;const B=g-x/2;var e=g+x/2;g=w.local;x=[.01,g.ambientAtNight];const L=[.8,.8,1],M=[.01,.01,.01],F=[g.directAtTwilight,g.ambientAtTwilight],G=[1,.6,.5],H=[.8,.8,1],I=[.9*g.directAtNoon,g.ambientAtNoon],J=
[1,.98,.98],K=[.98,.98,1],P=[g.directAtNoon,g.ambientAtNoon],Q=[1,1,1],R=[1,1,1];g=[0,0];let r=[0,0,0],t=[0,0,0];b<u||b>e?(g=x,r=M,t=L):b<n?(e=n-u,g=l(b-u,e,x,F),r=l(b-u,e,M,G),t=l(b-u,e,L,H)):b<p?(e=p-n,g=l(b-n,e,F,I),r=l(b-n,e,G,J),t=l(b-n,e,H,K)):b<q?(e=q-p,g=l(b-p,e,I,P),r=l(b-p,e,J,Q),t=l(b-p,e,K,R)):b<v?(e=v-q,g=l(b-q,e,P,I),r=l(b-q,e,Q,J),t=l(b-q,e,R,K)):b<B?(e=B-v,g=l(b-v,e,I,F),r=l(b-v,e,J,G),t=l(b-v,e,K,H)):b<e&&(e-=B,g=l(b-B,e,F,x),r=l(b-B,e,G,M),t=l(b-B,e,H,L));q=z.fromValues(r[0],r[1],
r[2]);b=z.fromValues(t[0],t[1],t[2]);p=V(d);d=g[0]*p.direct;p=g[1]*p.ambient}y.lerp(f.ambient.color,b,f.ambient.color,c);f.ambient.intensity=D.lerp(p,f.ambient.intensity,c);y.lerp(f.direct.color,q,f.direct.color,c);f.direct.intensity=D.lerp(d,f.direct.intensity,c)}c=h.valueOf();a.polarException===A.SunCalc.POLAR_EXCEPTION.MIDNIGHT_SUN?(d=c-36E5*(h.getHours()+48)-6E4*h.getMinutes(),a=d+432E6):a.polarException===A.SunCalc.POLAR_EXCEPTION.POLAR_NIGHT?(d=c-2,a=c-1):(d=a.sunrise.valueOf(),a=a.sunset.valueOf());
a=1-D.clamp(Math.abs(c-(d+(a-d)/2))/432E5,0,1);f.noonFactor=a;N(h,k,m,f.direct.directionToLightSource)};C.computeDirectionsOverTime=function(h,k,m,f,d){h=h.getTime();k=k.getTime()-h;k=Math.floor(k/m)+1;const a=Array(k);for(let c=0;c<k;++c)O.setTime(h+m*c),a[c]=z.create(),N(O,f,d,a[c]);return a};C.computeShadowsEnabled=function(h,k){return 1===k?!0:Math.abs(h)<w.planarDirection.localAltitude};Object.defineProperty(C,"__esModule",{value:!0})});