// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Collection ../../core/Error ../../core/Evented ../../core/HandleOwner ../../core/Logger ../../core/maybe ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../geometry/Point ../../networks/support/utils ../../rest/networks/trace ../../rest/networks/support/TraceLocation ../../rest/networks/support/TraceParameters ./support/GeometryHandler ./support/GraphicHandler".split(" "),
function(l,p,x,y,m,z,A,B,C,q,K,L,M,D,E,u,F,v,G,H,I){const J=A.getLogger("esri.widgets.UtilityNetworkTrace.UtilityNetworkTraceViewModel");m=function(w){function t(a){a=w.call(this,a)||this;a._activeProgress=!1;a._clickHandler=null;a._defaultGraphicColor={color:[255,255,0,.6],haloOpacity:.9,fillOpacity:.2,hex:"#FFFF00"};a._flags=[];a._geometryHandler=null;a._graphicHandler=null;a._highlightHandler=[];a._traces=[];a._traceResults=[];a._unObject=null;a.flags=[];a.gdbVersion="sde.DEFAULT";a.selectedTraces=
[];a.selectOnComplete=!0;a.showGraphicsOnComplete=!0;a.showSelectionAttributes=!0;return a}l._inheritsLoose(t,w);var f=t.prototype;f.initialize=function(){this._geometryHandler=new H.GeometryHandler;this._graphicHandler=new I.GraphicHandler};f.destroy=function(){this.view=null};f.addFlagByHit=function(a){return new Promise((b,c)=>{this.view.popup.autoOpenEnabled=!1;this._clickHandler&&this._clickHandler.remove();this._clickHandler=this.view.on("click",d=>{this.queryFlagByHitTest(d,a).then(e=>{this.view.popup.autoOpenEnabled=
!0;this._clickHandler.remove();b(e)}).catch(e=>{this.view.popup.autoOpenEnabled=!0;this._clickHandler.remove();c(e)})})})};f.addFlagsOnLoad=function(){var a=this;return new Promise(function(){var b=l._asyncToGenerator(function*(c){const d=[];yield a.view.when();const e=C.whenFalse(a.view,"updating",l._asyncToGenerator(function*(){yield Promise.all(a.flags.map(function(){var g=l._asyncToGenerator(function*(h){if(h.mapPoint){var k=new E({x:h.mapPoint.x,y:h.mapPoint.y,spatialReference:h.mapPoint.spatialReference.wkid});
k={screenPoint:a.view.toScreen(k),mapPoint:k};(yield a.queryFlagByHitTest(k,h.type))||("barrier"===h.type?d.push("barrier"):d.push("starting-point"))}});return function(h){return g.apply(this,arguments)}}()));e.remove();c(d)}))});return function(c){return b.apply(this,arguments)}}())};f.addResultGraphicToView=function(){var a=l._asyncToGenerator(function*(b,c){for(const e in b.results.aggregatedGeometry)if(-1<"line,multipoint,polygon".indexOf(e)&&null!==b.results.aggregatedGeometry[e]){b.results.aggregatedGeometry[e].spatialReference=
this._unObject.spatialReference;b.graphicEnabled=!0;var d=yield this._geometryHandler.projectGeometry(b.results.aggregatedGeometry[e],this.view.spatialReference);const g={globalid:b.trace.globalId};null!==d&&(d=this._graphicHandler.makeGraphic(d,c.color,g,this.view.spatialReference),this.view.graphics.add(d))}});return function(b,c){return a.apply(this,arguments)}}();f.addTerminal=function(a,b){const c=[...this._flags];c.forEach(d=>{d.globalId===b.globalId&&-1===b.selectedTerminals.indexOf(parseInt(a,
10))&&d.selectedTerminals.push(parseInt(a,10))});this._flags=c};f.callTrace=function(){var a=this;return new Promise(function(){var b=l._asyncToGenerator(function*(c){const d=a._traces.filter(e=>e.selected);0<d.length&&(0<a._traceResults.length&&a._traceResults.forEach(e=>{a.removeResultGraphicFromView(e)}),a._traceResults=[],a.removeSelection(),yield Promise.all(d.map(function(){var e=l._asyncToGenerator(function*(g,h){const k=new G({gdbVersion:a.gdbVersion,moment:null,traceType:g.traceType,traceLocations:a._flags,
namedTraceConfigurationGlobalId:g.globalId,traceConfiguration:null,outSpatialReference:null,resultTypes:null});yield a.executeTrace(g,a._unObject.networkServiceUrl,k).then(n=>{if(n.hasOwnProperty("results")){var r=[...a._traceResults];r.splice(h,0,n);a._traceResults=r;null!==n.results&&(a.selectOnComplete&&a.mergeSelection(!0,n.trace),a.showGraphicsOnComplete&&a.addResultGraphicToView(n,n.graphicColor));a._activeProgress=!1}else a._activeProgress=!1,r=[...a._traceResults],r.splice(h,0,n),a._traceResults=
r}).catch(n=>{a._activeProgress=!1;throw n;})});return function(g,h){return e.apply(this,arguments)}}())),c(!0))});return function(c){return b.apply(this,arguments)}}())};f.changeResultGraphicColor=function(a,b){const c=[...this._traceResults];0<c.length&&c.forEach(d=>{d.trace.globalId===b.trace.globalId&&(d.graphicColor=a,d.graphicEnabled=!0)});this._traceResults=c;this.removeResultGraphicFromView(b);this.addResultGraphicToView(b,a)};f.checkCanTrace=function(){const a={status:!0,issues:[]};let b=
[];this._flags.some(c=>"starting-point"===c.type)?(b=this._traces.filter(c=>c.selected),0>=b.length&&(a.status=!1,a.issues=["noTrace"])):(b=this._traces.filter(c=>!0===c.selected),0<b.length?(a.status=!1,a.issues=["noStart"]):(a.status=!1,a.issues=["noStart","noTrace"]));return a};f.checkSelectionExist=function(){let a=!1;this._highlightHandler.some(b=>{b&&(a=!0)});return a};f.clearResult=function(a){let b=this._traceResults;if(0<b.length){const c=b.filter(d=>d.trace.globalId===a.globalId);0<c.length&&
this.removeResultGraphicFromView(c[0]);b=b.filter(d=>d.trace.globalId!==a.globalId)}this._traceResults=b;0===b.length?this.removeSelection():this.mergeSelection(!1,a)};f.executeTrace=function(a,b,c){const d=this._processFlags(c.traceLocations);c.traceLocations=d;return F.trace(b,c).then(e=>({trace:a,results:e,selectionEnabled:!1,graphicEnabled:!1,graphicColor:this._defaultGraphicColor,status:"success"})).catch(e=>({trace:a,results:null,selectionEnabled:!1,graphicEnabled:!1,graphicColor:this._defaultGraphicColor,
status:e.message}))};f.getValidSources=function(){let a=[];const b=this._unObject.dataElement.domainNetworks;for(const c of b)a=a.concat(c.junctionSources),a=a.concat(c.edgeSources);return a};f.loadUtilityNetwork=function(){var a=l._asyncToGenerator(function*(){var b;yield this.view.when();const c=this.view.map;if(null!=(b=c.utilityNetworks)&&b.length){b=c.utilityNetworks.getItemAt(0);yield b.load();this._unObject=b;try{yield c.loadAll(),this._populateOutfields()}catch(d){this._populateOutfields()}return b}return null});
return function(){return a.apply(this,arguments)}}();f.manageFilterBarrier=function(a,b){const c=[...this._flags];c.forEach(d=>{d.globalId===b.globalId&&"barrier"===b.type&&d.id===b.id&&(d.isFilterBarrier=a)});this._flags=c};f.mergeSelection=function(a,b){let c=[];const d=[...this._traceResults],e=b.globalId;d.forEach(g=>{e===g.trace.globalId&&(g.selectionEnabled=a);g.selectionEnabled&&null!==g.results.elements&&(c=c.concat(g.results.elements))});this.selectResults([...new Set(c)])};f.queryFeaturesById=
function(a){var b=this;return new Promise(function(){var c=l._asyncToGenerator(function*(d){const e=u.getObjectIdsFromElements(b._unObject,a);var g=b._getUniqueMapLayerViews(b.view);const h={layerUrl:e[0].layerUrl,objectIds:e[0].objectIds,outFields:["*"]};g=g.filter(k=>k.layer.parsedUrl.path===e[0].layerUrl);0<g.length?(g=(yield Promise.all(g.map(function(){var k=l._asyncToGenerator(function*(n){const r=new x;r.add(n.layer);return(yield u.getFeaturesFromLayers({layers:r,layerInfos:[h],returnGeometry:!0,
outSpatialReference:b.view.spatialReference}))[0]});return function(n){return k.apply(this,arguments)}}()))).filter(k=>0<k.featureSet.features.length),0<g.length?d(g[0]):d(null)):d(null)});return function(d){return c.apply(this,arguments)}}())};f.queryFlagByHitTest=function(a,b){return this._lookupFlagByHit(a).then(c=>{if(0<c.length){const d=[...this._flags];c.forEach(e=>{e=e.graphic;const g=e.attributes.hasOwnProperty("GLOBALID")?e.attributes.GLOBALID:e.attributes.globalid;if(0>=d.filter(k=>k.globalId===
g).length){var h=this._graphicHandler.getFlagGraphic(e.mapPoint,b,e);this.view.graphics.add(h);d.push({...e,type:b,globalId:e.attributes.globalid?e.attributes.globalid:e.attributes.GLOBALID,details:e,mapGraphic:h,id:d.length+1})}else null!==e.percentAlong&&(h=this._graphicHandler.getFlagGraphic(e.mapPoint,b,e),this.view.graphics.add(h),d.push({...e,type:b,globalId:e.attributes.globalid?e.attributes.globalid:e.attributes.GLOBALID,details:e,mapGraphic:h,id:d.length+1}))});this._flags=d;return!0}return!1})};
f.removeResultGraphicFromView=function(a){const b=this.view.graphics;a.graphicEnabled=!1;b.filter(c=>c.attributes[c.attributes.hasOwnProperty("GLOBALID")?"GLOBALID":"globalid"]===a.trace.globalId).forEach(c=>{this.view.graphics.remove(c)})};f.removeFlag=function(a){const b=this._flags.filter(c=>{if(c.id!==a.id)return c});this._removeGraphic(a);this._flags=b};f.removeSelection=function(){this._highlightHandler.forEach(a=>{a&&a.remove()});this._highlightHandler=[]};f.removeTerminal=function(a,b){const c=
[...this._flags];c.forEach(d=>{if(d.globalId===b.globalId&&-1<b.selectedTerminals.indexOf(parseInt(a,10))){const e=b.selectedTerminals.indexOf(parseInt(a,10));d.selectedTerminals.splice(e,1)}});this._flags=c};f.reset=function(){this._flags=[];this._traceResults=[];const a=[...this._traces];a.forEach(b=>{b.selected=!1});this._traces=a;this.view.graphics.removeAll();this.removeSelection()};f.selectFeaturesById=function(a){const b=u.getObjectIdsFromElements(this._unObject,a);this._getUniqueMapLayerViews(this.view).forEach(c=>
{c.layer.parsedUrl.path===b[0].layerUrl&&this._highlightHandler.push(c.highlight(b[0].objectIds))})};f.selectResults=function(a){if(0<a.length){this.removeSelection();a=this._groupResultsByNetworkSource(a);for(const b in a)this.selectFeaturesById(a[b])}else this.removeSelection()};f.selectTraces=function(a,b){const c=[...this._traces];c.forEach(d=>{b===d.globalId&&(d.selected=a)});this._traces=c};f.selectTracesOnLoad=function(){this._unObject.hasOwnProperty("sharedNamedTraceConfigurations")&&(this._traces=
[...this._unObject.sharedNamedTraceConfigurations],this._traces.forEach(a=>{a.selected=!1;-1!==this.selectedTraces.indexOf(a.globalId)&&(a.selected=!0)}))};f.zoomToAsset=function(a){this.view.goTo(a).catch(b=>{console.error(b)})};f._getUniqueMapLayerViews=function(a){const b=[];a.layerViews.filter(c=>"feature"===c.layer.type||"group"===c.layer.type).forEach(c=>{"group"===c.type?c.layerViews.forEach(d=>{b.push(d)}):b.find(d=>d.layer.layerId===c.layer.layerId)||b.push(c)});return b};f._processFlags=
function(a){const b=[];a.forEach(c=>{if(null!==c.selectedTerminals&&0<c.selectedTerminals.length)c.selectedTerminals.forEach(d=>{d=new v({globalId:c.globalId,percentAlong:c.percentAlong,terminalId:d,type:c.type,isFilterBarrier:c.isFilterBarrier});b.push(d)});else{const d=new v({globalId:c.globalId,percentAlong:c.percentAlong,terminalId:null,type:c.type,isFilterBarrier:c.isFilterBarrier});b.push(d)}});return b};f._getDisplayField=function(a){const b=a.layer;let c=b.displayField;var d="";for(const e in a.attributes){const g=
e.toLowerCase();g===c.toLowerCase()&&(d=a.attributes[e],"assetgroup"===g||"assettype"===g?((d=a.attributes[b.typeIdField.toUpperCase()])||(d=a.attributes[b.typeIdField.toLowerCase()]),c=b.typeIdField,d=this._checkSubtype(b,d)):d=this._checkDomain(b.fields,e,d))}return{field:c,value:d}};f._checkSubtype=function(a,b){let c=b;null!==a.types&&0<a.types.length&&(a=a.types.filter(d=>d.id===b),0<a.length&&(c=a[0].name));return c};f._checkDomain=function(a,b,c){let d=c;a=a.filter(e=>e.name.toLowerCase()===
b.toLowerCase());0<a.length&&null!==a[0].domain&&(a=a[0].domain.codedValues.filter(e=>e.code===c),0<a.length&&(d=a[0].name));return d};f._groupBy=function(a,b){return a.reduce(function(c,d){(c[d[b]]=c[d[b]]||[]).push(d);return c},{})};f._groupResultsByNetworkSource=function(a){return 0<a.length?a[0].hasOwnProperty("results")?this._groupBy(a[0].results.elements,"networkSourceId"):this._groupBy(a,"networkSourceId"):a.hasOwnProperty("results")?this._groupBy(a.results.elements,"networkSourceId"):[]};
f._lookupFlagByHit=function(a){return this.view.hitTest(a.screenPoint,{exclude:this.view.graphics}).then(b=>{const c=[];if(0<b.results.length&&(b=b.results[0],b.graphic&&B.isSome(b.graphic.geometry)))if("polyline"===b.graphic.geometry.type){var d=this._geometryHandler.getPercentageAlong(b.graphic.geometry,a.mapPoint,b.graphic.geometry.spatialReference),e=this._getDisplayField(b.graphic);b.graphic.terminalId=null;b.graphic.isFilterBarrier=!1;b.graphic.allTerminals=null;b.graphic.selectedTerminals=
null;b.graphic.percentAlong=d;b.graphic.displayValue=e;b.graphic.mapPoint=b.mapPoint;c.push(b)}else"point"!==b.graphic.geometry.type&&"polygon"!==b.graphic.geometry.type||null===this._unObject||(d=this._unObject.getTerminalConfiguration(b.graphic),e=this._getDisplayField(b.graphic),b.graphic.terminalId=d?d.terminals[0].id?d.terminals[0].id:null:1,b.graphic.isFilterBarrier=!1,b.graphic.allTerminals=d?d:null,b.graphic.selectedTerminals=[d?d.terminals[0].id?d.terminals[0].id:null:1],b.graphic.percentAlong=
null,b.graphic.displayValue=e,b.graphic.mapPoint=b.mapPoint,c.push(b));return c})};f._populateOutfields=function(){var a=l._asyncToGenerator(function*(){const b=this.view.map,c=this.getValidSources();b.layers.forEach(d=>{"group"===d.type?d.layers.forEach(e=>{c.some(g=>g.layerId===e.layerId)&&e.fields.some(g=>"assetgroup"===g.name.toLowerCase())&&(e.outFields=["assetgroup","assettype","globalid","objectid"])}):c.some(e=>e.layerId===d.layerId)&&d.fields.some(e=>"assetgroup"===e.name.toLowerCase())&&
(d.outFields=["assetgroup","assettype","globalid","objectid"])})});return function(){return a.apply(this,arguments)}}();f._removeGraphic=function(a){this.view.graphics.remove(a.mapGraphic)};l._createClass(t,[{key:"state",get:function(){var a;return null!=(a=this.view)&&a.ready?"ready":"loading"}},{key:"view",get:function(){return this._get("view")},set:function(a){a&&"2d"!==a.type&&J.error(new y("view:invalid-view","SceneView is not supported",{view:a}));this._set("view",a)}}]);return t}(z.HandleOwnerMixin(m.EventedAccessor));
p.__decorate([q.property()],m.prototype,"flags",void 0);p.__decorate([q.property()],m.prototype,"gdbVersion",void 0);p.__decorate([q.property()],m.prototype,"selectedTraces",void 0);p.__decorate([q.property()],m.prototype,"selectOnComplete",void 0);p.__decorate([q.property()],m.prototype,"showGraphicsOnComplete",void 0);p.__decorate([q.property()],m.prototype,"showSelectionAttributes",void 0);p.__decorate([q.property({readOnly:!0})],m.prototype,"state",null);p.__decorate([q.property({value:null})],
m.prototype,"view",null);return m=p.__decorate([D.subclass("esri.widgets.UtilityNetworkTrace.UtilityNetworkTraceViewModel")],m)});