// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/maybe ../../../../../core/promiseUtils ../../../../../chunks/mat4f64 ../../../../../chunks/vec2f64 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../chunks/vec4f64 ../../../support/debugFlags ../../../support/buffer/glUtil ../../core/shaderLibrary/output/OutputHighlight.glsl ../Camera ../DefaultVertexAttributeLocations ../Util ./InstanceData ./InstanceOctree ./LevelSelector ./LodLevel ./RenderInstanceData ../../materials/DefaultMaterial ../../materials/internal/MaterialUtil ../../materials/renderers/utils ../../../../webgl/Util".split(" "),
function(x,y,O,z,A,P,t,v,Q,B,R,S,T,C,u,m,U,V,W,D,X,Y,Z,E){function F(l,k,a){const b=l.allocateHead();l=l.view;Z.encodeDoubleVec3(k.modelOrigin,a,l.modelOriginHi,l.modelOriginLo,b);l.model.copyFrom(b,k.model,a);l.modelNormal.copyFrom(b,k.modelNormal,a);k.color&&l.color&&l.color.copyFrom(b,k.color,a);k.featureAttribute&&l.featureAttribute&&l.featureAttribute.copyFrom(b,k.featureAttribute,a)}let G=function(l){const k=l.baseBoundingSphere.radius;l=l.levels.map(a=>a.minScreenSpaceRadius);return new V.LevelSelector(k,
l)},ba=function(){function l(a,b,c,e){this.type=6;this.isGround=!1;this._inverseViewport=P.create();this._levels=[];this._defaultRenderInstanceData=[];this._highlightRenderInstanceData=[];this._instanceIndex=0;this._slicePlane=!1;this._enableLevelSelection=!0;this._lastCamera=new T;this._updateCyclesWithStaticCamera=-1;this._needFullCycle=!1;this.canRender=!0;this._symbol=a;this._optionalFields=b;this._metadata=c;this._instanceBufferLayout=X.getInstanceBufferLayout({instancedDoublePrecision:!0,instanced:b});
this._glInstanceBufferLayout=R.glLayout(this._instanceBufferLayout,1);this._instanceData=new m.InstanceData(this._optionalFields,e);this._instanceData.on("instance-added",()=>this.requestUpdateCycle());this._instanceData.on("instance-removed",()=>this.requestUpdateCycle());this._instanceData.on("instance-transform-changed",f=>{this.requestUpdateCycle();this._metadata.notifyGraphicGeometryChanged(f.index)});this._instanceData.on("instance-visibility-changed",f=>{this.requestUpdateCycle(!0);this._metadata.notifyGraphicVisibilityChanged(f.index)});
this._instanceData.on("instance-highlight-changed",()=>this.requestUpdateCycle(!0));this._enableLevelSelection=1<this._symbol.levels.length}var k=l.prototype;k.initializeRenderContext=function(){var a=y._asyncToGenerator(function*(b,c){this._context=b;const e=b.renderContext.rctx,f=yield Promise.allSettled(this._symbol.levels.map(d=>{this._defaultRenderInstanceData.push(new D.RenderInstanceData(e,this._instanceBufferLayout));this._highlightRenderInstanceData.push(new D.RenderInstanceData(e,this._instanceBufferLayout));
return W.LodLevel.create(b,d,c)})),h=f.map(d=>"fulfilled"===d.status?d.value:null).filter(d=>d);if(z.isAborted(c)||h.length!==f.length){h.forEach(d=>d.destroy());z.throwIfAborted(c);for(const d of f)if("rejected"===d.status)throw d.reason;}this._levels=h;this._levelSelector=G(this)});return function(b,c){return a.apply(this,arguments)}}();k.uninitializeRenderContext=function(){this.invalidateOctree();this._levels.forEach(a=>a.destroy());this._defaultRenderInstanceData.forEach(a=>a.destroy());this._highlightRenderInstanceData.forEach(a=>
a.destroy())};k.prepareRender=function(a,b){B.LOD_INSTANCE_RENDERER_DISABLE_UPDATES||(this._enableLevelSelection&&(a=b.equals(this._lastCamera),this._lastCamera.copyFrom(b),a||this.requestUpdateCycle()),a=this._needFullCycle?this._instanceData.size:2E3,this._needFullCycle=!1,this.updateInstances(b,a),this.needsUpdates&&this._context.requestRender())};k.render=function(a){var b,c;const e=3===a.slot?2:5===a.slot?4:null;if(!e||!this.baseMaterial.isVisible()||!this.baseMaterial.isVisibleInPass(a.pass))return!1;
var f=a.camera;this._inverseViewport[0]=1/f.fullViewport[2];this._inverseViewport[1]=1/f.fullViewport[3];f={slot:e,origin:[0,0,0],camera:f,inverseViewport:this._inverseViewport,shadowMap:a.shadowMap,shadowMappingEnabled:a.shadowMap.enabled,ssaoHelper:a.ssaoHelper,ssaoEnabled:a.ssaoHelper.enabled,screenToWorldRatio:null,screenToPCSRatio:null,slicePlane:a.sliceHelper&&a.sliceHelper.plane,hudVisibilityTexture:a.offscreenRenderingHelper?a.offscreenRenderingHelper.hudVisibilityTexture:null,highlightDepthTexture:null!=
(b=null==(c=a.offscreenRenderingHelper)?void 0:c.depthTexture)?b:null,hasOccludees:!1,linearDepthTexture:null,lastFrameColorTexture:null,reprojectionMatrix:A.IDENTITY,ssrEnabled:!1,lighting:a.scenelightingData,transparencyPassType:a.transparencyPassType,terrainLinearDepthTexture:a.multipassTerrainParams.terrainLinearDepthTexture,geometryLinearDepthTexture:a.multipassGeometryParams.geometryLinearDepthTexture,multipassTerrainEnabled:a.multipassTerrainParams.multipassTerrainEnabled,cullAboveGround:a.multipassTerrainParams.cullAboveGround,
multipassGeometryEnabled:a.multipassGeometryParams.multipassGeometryEnabled,highlightColorTexture:null};a.rctx.bindVAO();b=5!==a.pass&&7!==a.pass;c=6!==a.pass;b&&this._renderComponents(a,e,f,this._defaultRenderInstanceData);c&&this._renderComponents(a,e,f,this._highlightRenderInstanceData);return b||c};k.intersect=function(a,b,c,e){if(this.baseMaterial.isVisible()){var f=v.create();t.subtract(f,e,c);var h=d=>{this._instanceData.getCombinedModelTransform(d,H);a.transform.set(H);t.transformMat4(I,c,
a.transform.inverse);t.transformMat4(J,e,a.transform.inverse);const p=this._instanceData.getState(d),g=this._instanceData.getLodLevel(d);u.assert(p&m.StateFlags.ACTIVE,"invalid instance state");u.assert(0<=g&&g<this._levels.length,"invaid lod level");this._levels[g].intersect(a,b,I,J,d,this._metadata)};this.baseMaterial.parameters.verticalOffset?this.octree.forEach(h):this.octree.forEachAlongRay(c,f,h)}};k.queryDepthRange=function(a){return this.queryDepthRangeOctree(a)};k.notifyShaderTransformationChanged=
function(){this.invalidateOctree()};k.requestUpdateCycle=function(a=!1){this._updateCyclesWithStaticCamera=-1;a&&(this._needFullCycle=!0);this.needsUpdates&&this._context.requestRender()};k.invalidateOctree=function(){this._octree&&(this._octree.destroy(),this._octree=null)};k.buildOctree=function(){const a=new U.InstanceOctree(this._instanceData,this.baseBoundingSphere);var b=this._instanceData;b=b.view?b.view.state:null;for(let c=0;c<this._instanceData.capacity;++c)b.get(c)&m.StateFlags.ACTIVE&&
a.addInstance(c);return a};k.queryDepthRangeOctree=function(a){var b=a.eye;const c=a.viewForward;var e=this.octree.findClosest(c,1,a.frustum);const f=this.octree.findClosest(c,-1,a.frustum);return null!=e&&null!=f?(this._instanceData.view.boundingSphere.getVec(e,r),t.subtract(r,r,b),e=t.dot(r,c)-r[3],this._instanceData.view.boundingSphere.getVec(f,r),t.subtract(r,r,b),b=t.dot(r,c)+r[3],{near:Math.max(a.near,e),far:Math.min(a.far,b)}):{near:Infinity,far:-Infinity}};k.startUpdateCycle=function(){this._updateCyclesWithStaticCamera++;
this._defaultRenderInstanceData.forEach(a=>{a.startUpdateCylce()});this._highlightRenderInstanceData.forEach(a=>{a.startUpdateCylce()});this.needsUpdates&&this._context.requestRender()};k.updateInstances=function(a,b){const c=this._enableLevelSelection,e=this._levelSelector;e.updateCamera(a);this._defaultRenderInstanceData.forEach(q=>{q.beginUpdate()});this._highlightRenderInstanceData.forEach(q=>{q.beginUpdate()});a=this._instanceData;const f=this._instanceData.view,h=a.capacity;let d=this._instanceIndex;
b=Math.min(a.size,b);for(let q=0;q<b;++q){0===d&&this.startUpdateCycle();const n=f.state.get(d);var p=0;if(n&m.StateFlags.ALLOCATED){var g=f.lodLevel.get(d);n&m.StateFlags.DEFAULT_ACTIVE&&this._defaultRenderInstanceData[g].freeTail();n&m.StateFlags.HIGHLIGHT_ACTIVE&&this._highlightRenderInstanceData[g].freeTail();n&m.StateFlags.REMOVE?a.freeInstance(d):n&m.StateFlags.VISIBLE?(g=0,c&&(f.modelOrigin.getVec(d,K),g=e.selectLevel(K,a.getCombinedMedianScaleFactor(d))),p=n&~(m.StateFlags.ACTIVE|m.StateFlags.TRANSFORM_CHANGED),
0<=g&&(n&m.StateFlags.HIGHLIGHT?(F(this._highlightRenderInstanceData[g],f,d),p|=m.StateFlags.HIGHLIGHT_ACTIVE):(F(this._defaultRenderInstanceData[g],f,d),p|=m.StateFlags.DEFAULT_ACTIVE)),f.state.set(d,p),f.lodLevel.set(d,g)):(p=n&~(m.StateFlags.ACTIVE|m.StateFlags.TRANSFORM_CHANGED),f.state.set(d,p));this._octree&&(g=!!(n&m.StateFlags.ACTIVE),p=!!(p&m.StateFlags.ACTIVE),!g&&p?this._octree.addInstance(d):g&&!p?this._octree.removeInstance(d):g&&p&&n&m.StateFlags.TRANSFORM_CHANGED&&(this._octree.removeInstance(d),
this._octree.addInstance(d)));d=(d+1)%h}else d=(d+1)%h,b++}this._instanceIndex=d;this._defaultRenderInstanceData.forEach(q=>{q.endUpdate()});this._highlightRenderInstanceData.forEach(q=>{q.endUpdate()})};k._renderComponents=function(a,b,c,e){this.levels.forEach((f,h)=>{f.components.forEach(d=>{this._renderComponent(a,b,c,e[h],d,h)})})};k._renderComponent=function(a,b,c,e,f,h){if(0!==e.size&&f.material.requiresSlot(b)){var {rctx:d,pass:p}=a,g=f.glMaterials.load(d,p);if(!O.isNone(g)){var q=d.capabilities.instancing,
n=g.beginSlot(c),w=n.program;n.bindPipelineState(d,b);d.useProgram(w);g.bind(c,n);d.bindVAO(f.vao);n.ensureAttributeLocations(f.vao);a.isHighlightPass&&S.bindOutputHighlight(w,c);n.bindDraw(c);B.LOD_INSTANCE_RENDERER_COLORIZE_BY_LEVEL&&0===a.pass&&(w.setUniform4fv("externalColor",L[Math.min(h,L.length-1)]),w.setUniform1i("colorMixMode",Y.colorMixModes.replace));a=e.capacity;b=e.headIndex;c=e.tailIndex;h=e.firstIndex;var M=this._glInstanceBufferLayout;g=(N,aa)=>{E.bindVertexBufferLayout(d,C.Default3D,
e.buffer,M,N);q.drawArraysInstanced(n.primitiveType,0,f.vertexCount,aa-N);E.unbindVertexBufferLayout(d,C.Default3D,e.buffer,M)};f.material.parameters.transparent&&null!=h?b>c?(u.assert(h>=c&&h<=b,"invalid firstIndex"),g(h,b),g(c,h)):b<c&&(h<=b?(u.assert(0<=h&&h<=b,"invalid firstIndex"),g(h,b),g(c,a),g(0,h)):(u.assert(h>=c&&h<=a,"invalid firstIndex"),g(h,a),g(0,b),g(c,h))):b>c?g(c,b):b<c&&(g(0,b),g(c,a));d.bindVAO(null)}}};y._createClass(l,[{key:"levels",get:function(){return this._levels}},{key:"baseBoundingBox",
get:function(){return this._levels[this._levels.length-1].boundingBox}},{key:"baseBoundingSphere",get:function(){return this._levels[this._levels.length-1].boundingSphere}},{key:"baseMaterial",get:function(){return this._levels[this._levels.length-1].components[0].material}},{key:"slicePlaneEnabled",get:function(){return this._slicePlane},set:function(a){this._slicePlane=a}},{key:"layerUid",get:function(){return this._metadata.layerUid}},{key:"instanceData",get:function(){return this._instanceData}},
{key:"memoryUsage",get:function(){const a={cpu:0,gpu:0};this._defaultRenderInstanceData.forEach(b=>{b=b.memoryUsage;a.cpu+=b.cpu;a.gpu+=b.gpu});this._highlightRenderInstanceData.forEach(b=>{b=b.memoryUsage;a.cpu+=b.cpu;a.gpu+=b.gpu});return a}},{key:"renderStats",get:function(){const a=this._instanceData.size,b=[];this._levels.forEach((c,e)=>{e=this._defaultRenderInstanceData[e].size+this._highlightRenderInstanceData[e].size;c=c.triangleCount;b.push({renderedInstances:e,renderedTriangles:e*c,trianglesPerInstance:c})});
return{totalInstances:a,renderedInstances:b.reduce((c,e)=>c+e.renderedInstances,0),renderedTriangles:b.reduce((c,e)=>c+e.renderedTriangles,0),levels:b}}},{key:"slots",get:function(){return[3,5]}},{key:"needsHighlight",get:function(){return 0<this._highlightRenderInstanceData.reduce((a,b)=>a+b.size,0)}},{key:"needsUpdates",get:function(){return 0<this._instanceData.size&&1>this._updateCyclesWithStaticCamera}},{key:"octree",get:function(){this._octree||(this._octree=this.buildOctree());return this._octree}}]);
return l}();const K=v.create(),r=Q.create(),H=A.create(),I=v.create(),J=v.create(),L=[[1,0,1,1],[0,0,1,1],[0,1,0,1],[1,1,0,1],[1,0,0,1]];x.LodRenderer=ba;x.setLevelSelectorFactory=function(l){G=l};Object.defineProperty(x,"__esModule",{value:!0})});