// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/2d/layers/BitmapTileLayerView2D":function(){define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Logger ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/set ../../../core/accessorSupport/decorators/subclass ../engine/BitmapTileContainer".split(" "),function(l,m,c,e,a,b,g,n,f,p){l.BitmapTileLayerView2D=d=>{d=function(q){function u(){return q.apply(this,arguments)||
this}m._inheritsLoose(u,q);var w=u.prototype;w.attach=function(){this.view.timeline.record(`${this.layer.title} (BitmapTileLayer) Attach`);this._bitmapView=new p.BitmapTileContainer(this._tileInfoView);this.container.addChild(this._bitmapView)};w.detach=function(){var v;this.container.removeChild(this._bitmapView);null==(v=this._bitmapView)?void 0:v.removeAllChildren()};return u}(d);return d=c.__decorate([f.subclass("esri.views.2d.layers.BitmapTileLayerView2D")],d)};Object.defineProperty(l,"__esModule",
{value:!0})})},"esri/views/2d/layers/LayerView2D":function(){define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Collection ../../../core/collectionUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../engine/Container ../../layers/support/ClipArea ../../layers/support/ClipRect ../../layers/support/Geometry ../../layers/support/Path".split(" "),
function(l,m,c,e,a,b,g,n,f,p,d,q,u,w,v,C){const D=e.ofType({key:"type",base:u,typeMap:{rect:w,path:C,geometry:v}});l.LayerView2DMixin=y=>{y=function(G){function E(){var t=G.apply(this,arguments)||this;t.clips=new D;t.moving=!1;t.attached=!1;t.lastUpdateId=-1;t.updateRequested=!1;return t}m._inheritsLoose(E,G);var B=E.prototype;B.initialize=function(){var t;this.container||(this.container=new q.Container);this.container.fadeTransitionEnabled=!0;this.container.opacity=0;this.container.clips=this.clips;
this.handles.add([b.init(this,"suspended",r=>{this.container&&(this.container.visible=!r);this.view&&!r&&this.updateRequested&&this.view.requestUpdate()},!0),b.init(this,["layer.opacity","container"],()=>{if(this.container){var r,x;this.container.opacity=null!=(r=null==(x=this.layer)?void 0:x.opacity)?r:1}},!0),b.init(this,["layer.blendMode"],r=>{this.container&&(this.container.blendMode=r)},!0),b.init(this,["layer.effect"],r=>{this.container&&(this.container.effect=r)},!0),this.clips.on("change",
()=>{this.container.clips=this.clips;this.notifyChange("clips")})]);null!=(t=this.view)&&t.whenLayerView?this.view.whenLayerView(this.layer).then(r=>{r!==this||this.attached||this.destroyed||(this.attach(),this.requestUpdate(),this.attached=!0)},()=>{}):this.when().then(()=>{this.attached||this.destroyed||(this.attach(),this.requestUpdate(),this.attached=!0)},()=>{})};B.destroy=function(){this.attached&&(this.detach(),this.attached=!1);this.handles.remove("initialize");this.updateRequested=!1};B.isVisibleAtScale=
function(t){var r=!0,x=this.layer;const F=x.minScale;x=x.maxScale;if(null!=F&&null!=x){r=!F;let z=!x;!r&&t<=F&&(r=!0);!z&&t>=x&&(z=!0);r=r&&z}return r};B.requestUpdate=function(){this.destroyed||this.updateRequested||(this.updateRequested=!0,this.suspended||this.view.requestUpdate())};B.processUpdate=function(t){this.isFulfilled()&&!this.isResolved()?this.updateRequested=!1:(this._set("updateParameters",t),this.updateRequested&&!this.suspended&&(this.updateRequested=!1,this.update(t)))};B.hitTest=
function(t,r){return Promise.resolve(null)};B.isUpdating=function(){return!1};B.isRendering=function(){return!1};B.canResume=function(){return G.prototype.canResume.call(this)?this.isVisibleAtScale(this.view.scale):!1};m._createClass(E,[{key:"updating",get:function(){return!this.attached||!this.suspended&&(this.updateRequested||this.isUpdating())||!(!this.updatingHandles||!this.updatingHandles.updating)}}]);return E}(y);c.__decorate([g.property({type:D,set(G){G=a.referenceSetter(G,this._get("clips"),
D);this._set("clips",G)}})],y.prototype,"clips",void 0);c.__decorate([g.property()],y.prototype,"moving",void 0);c.__decorate([g.property()],y.prototype,"attached",void 0);c.__decorate([g.property()],y.prototype,"container",void 0);c.__decorate([g.property()],y.prototype,"suspended",void 0);c.__decorate([g.property({readOnly:!0})],y.prototype,"updateParameters",void 0);c.__decorate([g.property()],y.prototype,"updateRequested",void 0);c.__decorate([g.property()],y.prototype,"updating",null);c.__decorate([g.property()],
y.prototype,"view",void 0);return y=c.__decorate([d.subclass("esri.views.2d.layers.LayerView2D")],y)};Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/layers/support/ClipArea":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/JSONSupport ../../../core/Logger ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/set ../../../core/accessorSupport/decorators/subclass".split(" "),
function(l,m,c,e,a,b,g,n,f){c=function(p){function d(){return p.apply(this,arguments)||this}l._inheritsLoose(d,p);return d}(c.JSONSupport);return c=m.__decorate([f.subclass("esri.views.layers.support.ClipArea")],c)})},"esri/views/layers/support/ClipRect":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ./ClipArea".split(" "),
function(l,m,c,e,a,b,g,n){var f;e=f=function(p){function d(){var q=p.apply(this,arguments)||this;q.type="rect";q.left=null;q.right=null;q.top=null;q.bottom=null;return q}l._inheritsLoose(d,p);d.prototype.clone=function(){return new f({left:this.left,right:this.right,top:this.top,bottom:this.bottom})};l._createClass(d,[{key:"version",get:function(){return(this._get("version")||0)+1}}]);return d}(n);m.__decorate([c.property({type:[Number,String],json:{write:!0}})],e.prototype,"left",void 0);m.__decorate([c.property({type:[Number,
String],json:{write:!0}})],e.prototype,"right",void 0);m.__decorate([c.property({type:[Number,String],json:{write:!0}})],e.prototype,"top",void 0);m.__decorate([c.property({type:[Number,String],json:{write:!0}})],e.prototype,"bottom",void 0);m.__decorate([c.property({readOnly:!0})],e.prototype,"version",null);return e=f=m.__decorate([g.subclass("esri.views.layers.support.ClipRect")],e)})},"esri/views/layers/support/Geometry":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../geometry ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../geometry/Geometry ../../../geometry/support/jsonUtils ./ClipArea ../../../geometry/Extent ../../../geometry/Polygon".split(" "),
function(l,m,c,e,a,b,g,n,f,p,d,q,u){var w;c={base:f,key:"type",typeMap:{extent:q,polygon:u}};d=w=function(v){function C(){var D=v.apply(this,arguments)||this;D.type="geometry";D.geometry=null;return D}l._inheritsLoose(C,v);C.prototype.clone=function(){return new w({geometry:this.geometry.clone()})};l._createClass(C,[{key:"version",get:function(){return(this._get("version")||0)+1}}]);return C}(d);m.__decorate([e.property({types:c,json:{read:p.fromJSON,write:!0}})],d.prototype,"geometry",void 0);m.__decorate([e.property({readOnly:!0})],
d.prototype,"version",null);return d=w=m.__decorate([n.subclass("esri.views.layers.support.Geometry")],d)})},"esri/views/layers/support/Path":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ./ClipArea".split(" "),function(l,m,c,e,a,b,g,n){e=function(f){function p(){var d=f.apply(this,
arguments)||this;d.type="path";d.path=[];return d}l._inheritsLoose(p,f);l._createClass(p,[{key:"version",get:function(){return(this._get("version")||0)+1}}]);return p}(n);m.__decorate([c.property({type:[[[Number]]],json:{write:!0}})],e.prototype,"path",void 0);m.__decorate([c.property({readOnly:!0})],e.prototype,"version",null);return e=m.__decorate([g.subclass("esri.views.layers.support.Path")],e)})},"esri/views/2d/layers/support/imageUtils":function(){define(["exports"],function(l){function m(c){const e=
document.createElement("canvas");[e.width,e.height]=c;return e}l.createBlankImage=m;l.resampleImage=function(c,e,a,b){if(a.level===b.level)return e;const g=c.tileInfo.size;var n=c.getTileResolution(a.level),f=c.getTileResolution(b.level),p=c.getLODInfoAt(b.level),d=p.getXForColumn(b.col);b=p.getYForRow(b.row);p=c.getLODInfoAt(a.level);c=p.getXForColumn(a.col);const q=p.getYForRow(a.row);p=(e instanceof HTMLImageElement?e.naturalWidth:e.width)/g[0];a=(e instanceof HTMLImageElement?e.naturalHeight:
e.height)/g[1];d=Math.round((d-c)/n*p);b=Math.round(-(b-q)/n*a);c=Math.round(f/n*g[0]*p);n=Math.round(f/n*g[1]*a);f=m(g);f.getContext("2d").drawImage(e,d,b,c,n,0,0,g[0],g[1]);return f};Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/layers/RefreshableLayerView":function(){define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Logger ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass".split(" "),
function(l,m,c,e,a,b,g,n,f,p,d){n=q=>{q=function(u){function w(){return u.apply(this,arguments)||this}m._inheritsLoose(w,u);w.prototype.initialize=function(){this.handles.add(b.on(this,"layer","refresh",v=>{this.doRefresh(v.dataChanged).catch(C=>{a.isAbortError(C)||e.getLogger(this.declaredClass).error(C)})}),"RefreshableLayerView")};return w}(q);c.__decorate([g.property()],q.prototype,"layer",void 0);return q=c.__decorate([d.subclass("esri.layers.mixins.RefreshableLayerView")],q)};l.RefreshableLayerView=
n;l.default=n;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/layers/TileLayerView":function(){define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Error ../../core/maybe ../../core/promiseUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../renderers/support/clickToleranceUtils".split(" "),function(l,m,c,e,a,b,g,n,f,p,
d,q){n=u=>{u=function(w){function v(){return w.apply(this,arguments)||this}m._inheritsLoose(v,w);v.prototype.fetchPopupFeatures=function(){var C=m._asyncToGenerator(function*(D,y){var G=this,{layer:E}=this;if(!D)return Promise.reject(new e("tilelayerview:fetchPopupFeatures","Nothing to fetch without area",{layer:E}));if("tile"!==E.type)return Promise.reject(new e("tilelayerview:fetchPopupFeatures","Layer type should be 'tile'",{type:E.type}));const B=this.get("view.scale");E=E.allSublayers.toArray().filter(t=>
{const r=0===t.minScale||B<=t.minScale,x=0===t.maxScale||B>=t.maxScale;return t.popupTemplate&&t.popupEnabled&&t.visible&&r&&x});return b.eachAlways(E.map(function(){var t=m._asyncToGenerator(function*(r){const x=r.createQuery();var F=a.isSome(y)?y.event:null;F=q.calculateTolerance({renderer:r.renderer,event:F});x.geometry=G.createFetchPopupFeaturesQueryGeometry(D,F);x.outFields=yield r.popupTemplate.getRequiredFields();return(yield r.queryFeatures(x)).features});return function(r){return t.apply(this,
arguments)}}())).then(t=>[].concat(...t.map(r=>r.value).filter(Boolean)))});return function(D,y){return C.apply(this,arguments)}}();return v}(u);c.__decorate([g.property()],u.prototype,"layer",void 0);return u=c.__decorate([d.subclass("esri.layers.mixins.TileLayerView")],u)};l.TileLayerView=n;l.default=n;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/renderers/support/clickToleranceUtils":function(){define(["exports"],function(l){function m(a,b){return b?"xoffset"in b&&b.xoffset?Math.max(a,
Math.abs(b.xoffset)):"yoffset"in b&&b.yoffset?Math.max(a,Math.abs(b.yoffset||0)):a:a}function c(a,b){if("number"===typeof a)return a;if(a&&a.stops&&a.stops.length){{a=a.stops;let g=b=0;for(let n=0;n<a.length;n++){const f=a[n].size;"number"===typeof f&&(b+=f,g++)}a=b/g}return a}return b}function e(a,b){if(!b)return a;b=b.filter(f=>"size"===f.type).map(f=>{const {maxSize:p,minSize:d}=f;return(c(p,a)+c(d,a))/2});let g=0;const n=b.length;if(0===n)return a;for(let f=0;f<n;f++)g+=b[f];return Math.max(Math.floor(g/
n),a)}l.calculateTolerance=function(a){const b=a&&a.renderer;a="touch"===(a&&a.event&&a.event.pointerType)?9:6;if(!b)return a;a="visualVariables"in b?e(a,b.visualVariables):a;if("simple"===b.type)return m(a,b.symbol);if("unique-value"===b.type){let g=a;b.uniqueValueInfos.forEach(n=>{g=m(g,n.symbol)});return g}if("class-breaks"===b.type){let g=a;b.classBreakInfos.forEach(n=>{g=m(g,n.symbol)});return g}return a};Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/support/drapedUtils":function(){define("exports ../../geometry ../../core/maybe ../../core/unitUtils ../../renderers/support/clickToleranceUtils ../../geometry/Extent".split(" "),
function(l,m,c,e,a,b){function g(f,p,d,q=new b){let u;if("2d"===d.type)u=p*d.resolution;else if("3d"===d.type){var w=d.overlayPixelSizeInMapUnits(f),v=d.basemapSpatialReference;u=c.isSome(v)&&!v.equals(d.spatialReference)?e.getMetersPerUnitForSR(v)/e.getMetersPerUnitForSR(d.spatialReference):p*w}p=f.x-u;w=f.y-u;v=f.x+u;f=f.y+u;({spatialReference:d}=d);q.xmin=Math.min(p,v);q.ymin=Math.min(w,f);q.xmax=Math.max(p,v);q.ymax=Math.max(w,f);q.spatialReference=d;return q}const n=new b;l.createQueryGeometry=
g;l.intersectsDrapedGeometry=function(f,p,d){f=d.toMap(f);if(c.isNone(f))return!1;const q=a.calculateTolerance();return g(f,q,d,n).intersects(p)};Object.defineProperty(l,"__esModule",{value:!0})})},"*noref":1}});
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Error ../../../core/Logger ../../../core/promiseUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ./BitmapTileLayerView2D ./LayerView2D ./support/imageUtils ../tiling/TileInfoView ../tiling/TileKey ../tiling/TileQueue ../tiling/TileStrategy ../../layers/LayerView ../../layers/RefreshableLayerView ../../layers/TileLayerView ../../support/drapedUtils".split(" "),function(l,
m,c,e,a,b,g,n,f,p,d,q,u,w,v,C,D,y,G,E,B){const t=e.getLogger("esri.views.2d.layers.TileLayerView2D"),r=[0,0];e=function(x){function F(){var k=x.apply(this,arguments)||this;k._tileStrategy=null;k._fetchQueue=null;k.layer=null;return k}l._inheritsLoose(F,x);var z=F.prototype;z.initialize=function(){var k=this.layer.tileInfo;k=k&&k.spatialReference;let h;k||(h=new c("layerview:tiling-information-missing","The layer doesn't provide tiling information",{layer:this.layer}));k.equals(this.view.spatialReference)||
(h=new c("layerview:spatial-reference-incompatible","The spatial reference of this layer does not meet the requirements of the view",{layer:this.layer}));this.watch("resampling",()=>{this.doRefresh()});h&&this.addResolvingPromise(Promise.reject(h))};z.update=function(k){this._fetchQueue.pause();this._fetchQueue.state=k.state;this._tileStrategy.update(k);this._fetchQueue.resume();this.notifyChange("updating")};z.attach=function(){const k="tileServers"in this.layer?this.layer.tileServers:null;this._tileInfoView=
new w(this.layer.tileInfo,this.layer.fullExtent);this._fetchQueue=new C({tileInfoView:this._tileInfoView,concurrency:k&&10*k.length||10,process:(h,A)=>this.fetchTile(h,A)});this._tileStrategy=new D({cachePolicy:"keep",resampling:this.resampling,acquireTile:h=>this.acquireTile(h),releaseTile:h=>this.releaseTile(h),tileInfoView:this._tileInfoView});this.requestUpdate();this.container.requestRender();x.prototype.attach.call(this)};z.detach=function(){x.prototype.detach.call(this);this._tileStrategy.destroy();
this._fetchQueue.clear();this.container.removeAllChildren();this._fetchQueue=this._tileStrategy=this._tileInfoView=null};z.moveStart=function(){this.requestUpdate()};z.viewChange=function(){this.requestUpdate()};z.moveEnd=function(){this.requestUpdate()};z.createFetchPopupFeaturesQueryGeometry=function(k,h){return B.createQueryGeometry(k,h,this.view)};z.doRefresh=function(){var k=l._asyncToGenerator(function*(){this.updateRequested||this.suspended||(this._fetchQueue.reset(),this._tileStrategy.tiles.forEach(h=>
this._enqueueTileFetch(h)),this.notifyChange("updating"))});return function(){return k.apply(this,arguments)}}();z.isUpdating=function(){var k;return 0<(null==(k=this._fetchQueue)?void 0:k.length)};z.acquireTile=function(k){k=this._bitmapView.createTile(k);const h=k.bitmap;[h.x,h.y]=this._tileInfoView.getTileCoords(r,k.key);h.resolution=this._tileInfoView.getTileResolution(k.key);[h.width,h.height]=this._tileInfoView.tileInfo.size;this._enqueueTileFetch(k);this._bitmapView.addChild(k);this.requestUpdate();
return k};z.releaseTile=function(k){this._fetchQueue.abort(k.key.id);this._bitmapView.removeChild(k);k.once("detach",()=>k.destroy());this.requestUpdate()};z.fetchTile=function(){var k=l._asyncToGenerator(function*(h,A={}){var H="tilemapCache"in this.layer?this.layer.tilemapCache:null;const {signal:J,resamplingLevel:L=0}=A;if(!H)try{return yield this._fetchImage(h,J)}catch(I){if(!a.isAbortError(I)&&!this.resampling)return u.createBlankImage(this._tileInfoView.tileInfo.size);if(3>L&&(H=this._tileInfoView.getTileParentId(h.id)))return H=
new v(H),A=yield this.fetchTile(H,{...A,resamplingLevel:L+1}),u.resampleImage(this._tileInfoView,A,H,h);throw I;}A=new v(0,0,0,0);let K;try{yield H.fetchAvailabilityUpsample(h.level,h.row,h.col,A,{signal:J});if(A.level!==h.level&&!this.resampling)return u.createBlankImage(this._tileInfoView.tileInfo.size);K=yield this._fetchImage(A,J)}catch(I){if(a.isAbortError(I))throw I;K=yield this._fetchImage(h,J)}return this.resampling?u.resampleImage(this._tileInfoView,K,A,h):K});return function(h){return k.apply(this,
arguments)}}();z._enqueueTileFetch=function(){var k=l._asyncToGenerator(function*(h){if(!this._fetchQueue.has(h.key.id)){try{const A=yield this._fetchQueue.push(h.key);h.bitmap.source=A;h.bitmap.width=this._tileInfoView.tileInfo.size[0];h.bitmap.height=this._tileInfoView.tileInfo.size[1];h.once("attach",()=>this.requestUpdate())}catch(A){a.isAbortError(A)||t.error(A)}this.requestUpdate()}});return function(h){return k.apply(this,arguments)}}();z._fetchImage=function(){var k=l._asyncToGenerator(function*(h,
A){return this.layer.fetchTile(h.level,h.row,h.col,{signal:A})});return function(h,A){return k.apply(this,arguments)}}();l._createClass(F,[{key:"resampling",get:function(){return!("resampling"in this.layer)||!1!==this.layer.resampling}}]);return F}(E.TileLayerView(G.RefreshableLayerView(d.BitmapTileLayerView2D(q.LayerView2DMixin(y)))));m.__decorate([b.property()],e.prototype,"resampling",null);return e=m.__decorate([p.subclass("esri.views.2d.layers.TileLayerView2D")],e)});