// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Error ../core/unitFormatUtils ../core/watchUtils ../core/accessorSupport/decorators/aliasOf ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/cast ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/subclass ./Widget ./Attachments/AttachmentsViewModel ./Attachments/support/attachmentUtils ./support/widgetUtils ./support/decorators/messageBundle ../core/Logger ./support/jsxFactory".split(" "),
function(z,h,v,H,A,B,f,O,I,m,J,K,C,D,q,E,P,b){const F={addButton:!0,addSubmitButton:!0,cancelAddButton:!0,cancelUpdateButton:!0,deleteButton:!0,errorMessage:!0,progressBar:!0,updateButton:!0},w=window.CSS;f=function(G){function t(a,c){a=G.call(this,a,c)||this;a.abilities=null;a.displayType="auto";a.graphic=null;a.label=void 0;a.messages=null;a.messagesUnits=null;a.selectedFile=null;a.submitting=!1;a.viewModel=new C;a.visibleElements={...F};a._supportsImageOrientation=w&&w.supports&&w.supports("image-orientation",
"from-image");a._addAttachmentForm=null;a._updateAttachmentForm=null;return a}z._inheritsLoose(t,G);var e=t.prototype;e.initialize=function(){this.own(A.on(this,"viewModel.attachmentInfos","change",()=>this.scheduleRender()),A.init(this,"viewModel.mode",()=>this._modeChanged()))};e.castVisibleElements=function(a){return{...F,...a}};e.addAttachment=function(){const {_addAttachmentForm:a,viewModel:c}=this;this._set("submitting",!0);this._set("error",null);return c.addAttachment(a).then(d=>{this._set("submitting",
!1);this._set("error",null);c.mode="view";return d}).catch(d=>{this._set("submitting",!1);this._set("error",new v("attachments:add-attachment",this.messages.addErrorMessage,d));throw d;})};e.deleteAttachment=function(a){const {viewModel:c}=this;this._set("submitting",!0);this._set("error",null);return c.deleteAttachment(a).then(d=>{this._set("submitting",!1);this._set("error",null);c.mode="view";return d}).catch(d=>{this._set("submitting",!1);this._set("error",new v("attachments:delete-attachment",
this.messages.deleteErrorMessage,d));throw d;})};e.updateAttachment=function(){const {viewModel:a}=this,{_updateAttachmentForm:c}=this;this._set("submitting",!0);this._set("error",null);return a.updateAttachment(c).then(d=>{this._set("submitting",!1);this._set("error",null);a.mode="view";return d}).catch(d=>{this._set("submitting",!1);this._set("error",new v("attachments:update-attachment",this.messages.updateErrorMessage,d));throw d;})};e.render=function(){const {submitting:a,viewModel:c}=this,{state:d}=
c;return b.tsx("div",{class:this.classes("esri-attachments","esri-widget")},a?this.renderProgressBar():null,"loading"===d?this.renderLoading():this.renderAttachments(),this.renderErrorMessage())};e.renderErrorMessage=function(){const {error:a,visibleElements:c}=this;return a&&c.errorMessage?b.tsx("div",{key:"error-message",class:"esri-attachments__error-message"},a.message):null};e.renderAttachments=function(){const {mode:a,activeAttachmentInfo:c}=this.viewModel;return"add"===a?this.renderAddForm():
"edit"===a?this.renderDetailsForm(c):this.renderAttachmentContainer()};e.renderLoading=function(){return b.tsx("div",{class:"esri-attachments__loader-container",key:"loader"},b.tsx("div",{class:"esri-attachments__loader"}))};e.renderProgressBar=function(){return this.visibleElements.progressBar?b.tsx("div",{class:"esri-attachments__progress-bar",key:"progress-bar"}):null};e.renderAddForm=function(){const {submitting:a,selectedFile:c}=this;var d=a||!c,g=this.visibleElements.cancelAddButton?b.tsx("button",
{type:"button",bind:this,disabled:a,onclick:this._cancelForm,class:this.classes("esri-button","esri-button--tertiary","esri-button--small","esri-button--half",a&&"esri-button--disabled")},this.messages.cancel):null;d=this.visibleElements.addSubmitButton?b.tsx("button",{type:"submit",disabled:d,class:this.classes("esri-button","esri-button--secondary","esri-button--small","esri-button--half",{["esri-button--disabled"]:d})},this.messages.add):null;const k=c?b.tsx("span",{key:"file-name",class:"esri-attachments__file-name"},
c.name):null;g=b.tsx("form",{bind:this,afterCreate:q.storeNode,afterRemoved:q.discardNode,"data-node-ref":"_addAttachmentForm",onsubmit:this._submitAddAttachment},b.tsx("fieldset",{class:"esri-attachments__file-fieldset"},k,b.tsx("label",{class:this.classes("esri-attachments__file-label","esri-button","esri-button--secondary")},c?this.messages.changeFile:this.messages.selectFile,b.tsx("input",{class:"esri-attachments__file-input",type:"file",name:"attachment",bind:this,onchange:this._handleFileInputChange}))),
d,g);return b.tsx("div",{key:"add-form-container",class:"esri-attachments__form-node"},g)};e.renderDetailsForm=function(a){const {visibleElements:c,viewModel:d,selectedFile:g,submitting:k}=this,{contentType:l,size:p,url:r}=a;var {abilities:n}=d,u=k||!g,x=n.editing&&n.operations.delete&&c.deleteButton?b.tsx("button",{key:"delete-button",type:"button",disabled:k,bind:this,onclick:L=>this._submitDeleteAttachment(L,a),class:this.classes("esri-button","esri-button--small","esri-button--tertiary","esri-attachments__delete-button",
{["esri-button--disabled"]:k})},this.messages.delete):null;u=n.editing&&n.operations.update&&c.updateButton?b.tsx("button",{disabled:u,key:"update-button",type:"submit",class:this.classes("esri-button","esri-button--small","esri-button--third",{["esri-button--disabled"]:u})},this.messages.update):null;const M=this.visibleElements.cancelUpdateButton?b.tsx("button",{disabled:k,key:"cancel-button",type:"button",bind:this,onclick:this._cancelForm,class:this.classes("esri-button","esri-button--small",
"esri-button--tertiary","esri-button--third",{["esri-button--disabled"]:k})},this.messages.cancel):null;var y=g?b.tsx("span",{key:"file-name",class:"esri-attachments__file-name"},g.name):null;n=n.editing&&n.operations.update?b.tsx("fieldset",{key:"file",class:"esri-attachments__file-fieldset"},y,b.tsx("label",{class:this.classes("esri-attachments__file-label","esri-button","esri-button--secondary")},this.messages.changeFile,b.tsx("input",{class:"esri-attachments__file-input",type:"file",name:"attachment",
bind:this,onchange:this._handleFileInputChange}))):null;y=b.tsx("fieldset",{key:"size",class:"esri-attachments__metadata-fieldset"},b.tsx("label",null,H.formatFileSize(this.messagesUnits,p)));const N=b.tsx("fieldset",{key:"content-type",class:"esri-attachments__metadata-fieldset"},b.tsx("label",null,l));x=b.tsx("form",{bind:this,afterCreate:q.storeNode,afterRemoved:q.discardNode,"data-node-ref":"_updateAttachmentForm",onsubmit:this._submitUpdateAttachment},b.tsx("div",{class:"esri-attachments__metadata"},
y,N),n,b.tsx("div",{class:"esri-attachments__actions"},x,M,u));return b.tsx("div",{key:"edit-form-container",class:"esri-attachments__form-node"},b.tsx("a",{class:"esri-attachments__item-link",href:r,rel:"noreferrer",target:"_blank"},this.renderImageMask({attachmentInfo:a,size:400}),b.tsx("div",{class:"esri-attachments__item-link-overlay"},b.tsx("span",{class:"esri-attachments__item-link-overlay-icon"},b.tsx("svg",{xmlns:"http://www.w3.org/2000/svg",width:"32",height:"32",viewBox:"0 0 32 32"},b.tsx("path",
{d:"M28 13h1v16H3V3h16v1H4v24h24zm-5-9h4.293L15.646 15.638l.707.707L28 4.707V9h1V3h-6z"}),b.tsx("path",{fill:"none",d:"M0 0h32v32H0z"}))))),x)};e.renderImageMask=function({attachmentInfo:a,size:c}){var {supportsResizeAttachments:d}=this.viewModel;const {contentType:g,name:k,url:l}=a,p=d&&D.isSupportedImage(g);a=(a=this._getCSSTransform(a,p))?{transform:a,"image-orientation":"none"}:{};const r=-1===l.indexOf("?")?"?":"\x26";c=p?`${l}${r}w=${c}`:D.getIconPath(g);d={["esri-attachments__image--resizable"]:d};
return b.tsx("div",{class:this.classes({["esri-attachments__item-mask--icon"]:!p},"esri-attachments__item-mask")},b.tsx("img",{styles:a,alt:k,src:c,class:this.classes(d,"esri-attachments__image")}))};e.renderAttachmentInfo=function({attachmentInfo:a,displayType:c}){var {viewModel:d}=this;({abilities:d}=d);const {name:g,url:k}=a;c=this.renderImageMask({attachmentInfo:a,size:"list"===c?48:400});var l=d.editing?b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-attachments__item-chevron-icon",
q.isRTL(this.container)?"esri-icon-left":"esri-icon-right")}):null;l=b.tsx("label",{class:"esri-attachments__label"},b.tsx("span",{class:"esri-attachments__filename"},g||this.messages.noTitle),l);c=[c,l];d=d.editing?b.tsx("button",{key:"details-button",bind:this,class:"esri-attachments__item-button",title:this.messages.attachmentDetails,"aria-label":this.messages.attachmentDetails,"data-attachment-info-id":a.id,onclick:()=>this._startEditAttachment(a),type:"button"},c):b.tsx("a",{key:"details-link",
class:"esri-attachments__item-button",href:k,target:"_blank"},c);return b.tsx("li",{class:"esri-attachments__item",key:a},d)};e.renderAttachmentContainer=function(){const {effectiveDisplayType:a,viewModel:c,visibleElements:d}=this,{attachmentInfos:g,abilities:k}=c;var l=g&&g.length;const p={["esri-attachments__container--list"]:"preview"!==a,["esri-attachments__container--preview"]:"preview"===a},r=k.editing&&k.operations.add&&d.addButton?b.tsx("button",{bind:this,onclick:()=>this._startAddAttachment(),
class:this.classes("esri-button","esri-button--tertiary","esri-attachments__add-attachment-button"),type:"button"},b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-attachments__item-add-icon","esri-icon-plus")}),this.messages.add):null;l=l?b.tsx("ul",{class:"esri-attachments__items"},g.toArray().map(n=>this.renderAttachmentInfo({attachmentInfo:n,displayType:a}))):b.tsx("div",{class:"esri-widget__content--empty"},this.messages.noAttachments);return b.tsx("div",{key:"attachments-container",
class:this.classes("esri-attachments__container",p)},l,r)};e._modeChanged=function(){this._set("error",null);this._set("selectedFile",null)};e._handleFileInputChange=function(a){a=(a=a.target)&&a.files&&a.files.item(0);this._set("selectedFile",a)};e._submitDeleteAttachment=function(a,c){a.preventDefault();this.deleteAttachment(c)};e._submitAddAttachment=function(a){a.preventDefault();this.addAttachment()};e._submitUpdateAttachment=function(a){a.preventDefault();this.updateAttachment()};e._startEditAttachment=
function(a){const {viewModel:c}=this;c.activeAttachmentInfo=a;c.mode="edit"};e._startAddAttachment=function(){this.viewModel.mode="add"};e._cancelForm=function(a){a.preventDefault();this.viewModel.mode="view"};e._getCSSTransform=function(a,c){({orientationInfo:a}=a);return!this._supportsImageOrientation&&c&&a?[a.rotation?`rotate(${a.rotation}deg)`:"",a.mirrored?"scaleX(-1)":""].join(" "):""};z._createClass(t,[{key:"effectiveDisplayType",get:function(){return"auto"===this.displayType?this.viewModel.supportsResizeAttachments?
"preview":"list":this.displayType}}]);return t}(K);h.__decorate([B.aliasOf("viewModel.abilities")],f.prototype,"abilities",void 0);h.__decorate([m.property()],f.prototype,"displayType",void 0);h.__decorate([m.property({readOnly:!0})],f.prototype,"effectiveDisplayType",null);h.__decorate([B.aliasOf("viewModel.graphic")],f.prototype,"graphic",void 0);h.__decorate([m.property({aliasOf:{source:"messages.widgetLabel",overridable:!0}})],f.prototype,"label",void 0);h.__decorate([m.property(),E.messageBundle("esri/widgets/Attachments/t9n/Attachments")],
f.prototype,"messages",void 0);h.__decorate([m.property(),E.messageBundle("esri/core/t9n/Units")],f.prototype,"messagesUnits",void 0);h.__decorate([m.property({readOnly:!0})],f.prototype,"selectedFile",void 0);h.__decorate([m.property({readOnly:!0})],f.prototype,"submitting",void 0);h.__decorate([m.property({readOnly:!0})],f.prototype,"error",void 0);h.__decorate([m.property({type:C})],f.prototype,"viewModel",void 0);h.__decorate([m.property()],f.prototype,"visibleElements",void 0);h.__decorate([I.cast("visibleElements")],
f.prototype,"castVisibleElements",null);return f=h.__decorate([J.subclass("esri.widgets.Attachments")],f)});