// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/watchUtils ../core/accessorSupport/decorators/aliasOf ../core/arrayUtils ../core/has ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/subclass ./Widget ./Attribution/AttributionViewModel ./support/decorators/accessibleHandler ./support/decorators/messageBundle ../core/Logger ./support/jsxFactory ./support/widgetUtils".split(" "),function(n,c,r,t,b,z,A,e,u,v,p,w,
x,B,g,C){b=function(q){function h(a,d){a=q.call(this,a,d)||this;a._isOpen=!1;a._attributionTextOverflowed=!1;a._prevSourceNodeHeight=0;a.iconClass="esri-icon-description";a.itemDelimiter=" | ";a.label=void 0;a.messages=null;a.view=null;a.viewModel=new p;return a}n._inheritsLoose(h,q);var f=h.prototype;f.initialize=function(){this.own(r.on(this,"viewModel.items","change",()=>this.scheduleRender()))};f.render=function(){return g.tsx("div",{bind:this,class:this.classes("esri-attribution esri-widget",
{["esri-attribution--open"]:this._isOpen}),onclick:this._toggleState,onkeydown:this._toggleState},this.renderSourcesNode(),this.renderPoweredBy())};f.renderPoweredBy=function(){return g.tsx("div",{class:"esri-attribution__powered-by"},"Powered by"," ",g.tsx("a",{class:"esri-attribution__link",href:"http://www.esri.com/",target:"_blank",rel:"noreferrer"},"Esri"))};f.renderSourcesNode=function(){const a=this._isOpen,d=this._isInteractive,k=d?0:-1,{attributionText:l}=this,m=d?"button":void 0;return g.tsx("div",
{afterCreate:this._afterSourcesNodeCreate,afterUpdate:this._afterSourcesNodeUpdate,bind:this,class:this.classes("esri-attribution__sources",{["esri-attribution__sources--open"]:a,["esri-interactive"]:d}),innerHTML:l,role:m,tabIndex:k})};f._afterSourcesNodeCreate=function(a){this._prevSourceNodeHeight=a.clientWidth};f._afterSourcesNodeUpdate=function(a){let d=!1;const {clientHeight:k,clientWidth:l,scrollWidth:m}=a;a=m>=l;const y=this._attributionTextOverflowed!==a;this._attributionTextOverflowed=a;
y&&(d=!0);this._isOpen&&(a=k<this._prevSourceNodeHeight,this._prevSourceNodeHeight=k,a&&(this._isOpen=!1,d=!0));d&&this.scheduleRender()};f._toggleState=function(){this._isInteractive&&(this._isOpen=!this._isOpen)};n._createClass(h,[{key:"_isInteractive",get:function(){return this._isOpen||this._attributionTextOverflowed}},{key:"attributionText",get:function(){return this.viewModel.items.reduce((a,d)=>{-1===a.indexOf(d.text)&&a.push(d.text);return a},[]).join(this.itemDelimiter)}}]);return h}(v);
c.__decorate([e.property()],b.prototype,"_isOpen",void 0);c.__decorate([e.property()],b.prototype,"_isInteractive",null);c.__decorate([e.property()],b.prototype,"_attributionTextOverflowed",void 0);c.__decorate([e.property()],b.prototype,"_prevSourceNodeHeight",void 0);c.__decorate([e.property({readOnly:!0,dependsOn:["viewModel.items.length","itemDelimiter"]})],b.prototype,"attributionText",null);c.__decorate([e.property()],b.prototype,"iconClass",void 0);c.__decorate([e.property()],b.prototype,"itemDelimiter",
void 0);c.__decorate([e.property({aliasOf:{source:"messages.widgetLabel",overridable:!0}})],b.prototype,"label",void 0);c.__decorate([e.property(),x.messageBundle("esri/widgets/Attribution/t9n/Attribution")],b.prototype,"messages",void 0);c.__decorate([t.aliasOf("viewModel.view")],b.prototype,"view",void 0);c.__decorate([e.property({type:p})],b.prototype,"viewModel",void 0);c.__decorate([w.accessibleHandler()],b.prototype,"_toggleState",null);return b=c.__decorate([u.subclass("esri.widgets.Attribution")],
b)});