// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Collection ../core/events ../core/lang ../core/Logger ../core/urlUtils ../core/watchUtils ../core/accessorSupport/decorators/aliasOf ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/subclass ./Widget ./Print/FileLink ./Print/PrintViewModel ./Print/TemplateOptions ./support/Heading ./support/Popover ./support/widgetUtils ./support/decorators/messageBundle ../core/has ./support/jsxFactory".split(" "),
function(H,m,l,M,U,V,N,B,w,aa,y,W,X,O,P,Q,R,Y,I,S,ba,b){function D(C){return"MAP_ONLY"===(null==C?void 0:C.toUpperCase())}const T=l.ofType(O),E=V.getLogger("esri.widgets.Print");l=function(C){function J(c,d){var a=C.call(this,c,d)||this;a._activeTabFocusRequested=!1;a._advancedOptionsVisibleForLayout=!1;a._advancedOptionsVisibleForMapOnly=!1;a._awaitingServerResponse=!1;a._exportedFileNameMap={};a._focusedTemplateIndex=0;a._layoutTabSelected=!0;a._pendingExportScroll=!1;a._rootNode=null;a._selectTemplateNode=
null;a._templateListPopover=new Y({owner:H._assertThisInitialized(a),placement:"top",offset:[0,-100],anchorElement:()=>a._selectTemplateNode,renderContentFunction:a.renderTemplateList});a.allowedFormats=null;a.allowedLayouts=null;a.exportedLinks=new T;a.extraParameters=null;a.headingLevel=3;a.iconClass="esri-icon-printer";a.includeDefaultTemplates=null;a.label=void 0;a.portal=null;a.printServiceUrl=null;a.templateCustomTextElements=null;a.templateOptions=new Q;a.view=null;a.viewModel=new P;a.handleTemplateListCreation=
e=>e.focus();a.handleTemplateChildBlur=e=>{var f;(null==(f=e.relatedTarget)?0:f.closest(".esri-print__template-list"))||a.handleCloseTemplateSelection()};a.handleCloseTemplateSelection=()=>{a._focusedTemplateIndex=0;a._templateListPopover.open=!1;a._selectTemplateNode.focus()};a.handleSelectTemplateClick=()=>{a._focusedTemplateIndex=0;a._templateListPopover.open=!0};a.handleTemplateListClick=e=>{a.applyTemplate(e.target["data-template"])};a.handleTemplateListKeyDown=e=>{if(I.isActivationKey(e.key))a.applyTemplate(a.viewModel.defaultTemplates.getItemAt(a._focusedTemplateIndex)),
e.preventDefault();else{if("ArrowDown"===e.key||"ArrowUp"===e.key){var {defaultTemplates:f}=a.viewModel;const g=(a._focusedTemplateIndex+("ArrowDown"===e.key?1:-1))%f.length;a._focusedTemplateIndex=0>g?f.length-1:g;f=e.currentTarget;I.keepMenuItemWithinView(f.querySelectorAll(".esri-menu__list-item")[a._focusedTemplateIndex],f.parentElement);e.preventDefault()}"Escape"===e.key&&a.handleCloseTemplateSelection()}};a._removeLink=e=>{(e=e.currentTarget["data-item"])&&"error"===e.state&&a.exportedLinks.remove(e)};
a._focusOnTabChange=a._focusOnTabChange.bind(H._assertThisInitialized(a));return a}H._inheritsLoose(J,C);var k=J.prototype;k.initialize=function(){this.own([B.init(this,"viewModel.templatesInfo",e=>{const {format:f,layout:g}=this.templateOptions;if(e){const n=g===e.layout.defaultValue||D(g)||e.layout.choiceList&&-1<e.layout.choiceList.indexOf(g),q=f===e.format.defaultValue||e.format.choiceList&&-1<e.format.choiceList.indexOf(f);n||(g&&E.warn("User sets an invalid layout, resetting it to the default valid one..."),
this.templateOptions.layout=e.layout.defaultValue);q||(f&&E.warn("User sets an invalid format, resetting it to the default valid one..."),this.templateOptions.format=e.format.defaultValue);D(g)&&(this._layoutTabSelected=!1)}}),B.init(this,"templateOptions.format",e=>{const {viewModel:{templatesInfo:f}}=this;if(f&&e){let g=!1;f.format.choiceList&&f.format.choiceList.forEach(n=>{n.toUpperCase()===e.toUpperCase()&&(this.templateOptions.format=n,g=!0)});g||(this.templateOptions.format=f.format.defaultValue,
E.warn("User sets an invalid format, resetting it to the default valid one..."));this.scheduleRender()}}),B.init(this,"templateOptions.layout",e=>{var {viewModel:{templatesInfo:f}}=this;if(f&&e){this._layoutTabSelected=!D(e);let g=!this._layoutTabSelected;g||f.layout.choiceList&&f.layout.choiceList.forEach(n=>{n.toUpperCase()===e.toUpperCase()&&(this.templateOptions.layout=n,g=!0)});g||(this.templateOptions.layout=f.layout.defaultValue,E.warn("User sets an invalid layout, resetting it to the default valid one..."));
f=this.viewModel.effectiveTemplateCustomTextElements[this.templateOptions.layout];this.templateOptions.customTextElements=f?U.clone(f):null;this.scheduleRender()}}),B.init(this,"templateOptions.dpi",e=>{0>=e?this.templateOptions.dpi=1:this.scheduleRender()}),B.init(this,"viewModel.view.scale",e=>{const {scale:f,scaleEnabled:g}=this.templateOptions;g&&f||(this.templateOptions.scale=e)})]);const {height:c,width:d}=this.templateOptions;this.templateOptions.width=d||800;this.templateOptions.height=c||
1100;const a=setTimeout(()=>{this._awaitingServerResponse=!0;this.scheduleRender()},500);this.viewModel.load().then(()=>clearTimeout(a))};k.render=function(){const {attributionEnabled:c,author:d,copyright:a,dpi:e,format:f,height:g,layout:n,legendEnabled:q,scaleEnabled:r,scale:t,width:K}=this.templateOptions;var p="ready"!==this.get("viewModel.state"),u=this.renderTitleOrFileNameSection();const {includeDefaultTemplates:L,messages:h,viewModel:Z}=this;var x=this.get("viewModel.templatesInfo.format.choiceList")||
[];x=0<x.length?x.map(v=>b.tsx("option",{key:v,selected:v===f,value:v},v.toUpperCase())):b.tsx("option",{key:"format-default-option"},h.formatDefaultOption);x=b.tsx("div",{class:"esri-print__form-section-container"},b.tsx("label",null,h.fileFormatTitle,b.tsx("select",{class:"esri-select",onchange:this._updateFromOption,"data-target-property":"format",bind:this},x)));var z=this.get("viewModel.templatesInfo.layout.choiceList")||[];z=0<z.length?z.map(v=>b.tsx("option",{key:v,selected:v===n,value:v},
h[v]||v)):b.tsx("option",{key:"layout-default-option"},h.layoutDefaultOption);z=b.tsx("div",{class:"esri-print__form-section-container"},b.tsx("label",null,h.layoutTitle,b.tsx("select",{class:"esri-select",onchange:this._updateFromOption,"data-target-property":"layout",bind:this},z)));var A=b.tsx("div",{class:"esri-print__form-section-container"},b.tsx("label",null,h.dpi,b.tsx("input",{type:"number",class:this.classes("esri-print__input-text","esri-input"),"data-input-name":"dpi",onchange:this._handleDPIChange,
value:`${e}`,min:"1",tabIndex:0,bind:this}))),F=b.tsx("div",{class:this.classes("esri-print__scale-info-container","esri-print__form-section-container")},b.tsx("label",null,b.tsx("input",{"data-option-name":"scaleEnabled",checked:r,type:"checkbox",tabIndex:0,onchange:this._toggleInputValue,bind:this}),h.scale),b.tsx("div",{class:"esri-print__scale-input-container"},b.tsx("input",{"aria-label":h.scaleLabel,"aria-valuenow":`${t}`,role:"spinbutton",type:"number",class:this.classes("esri-print__input-text",
"esri-input","esri-print__scale-input"),tabIndex:0,"data-input-name":"scale",onchange:this._updateInputValue,disabled:!r,value:`${t}`,bind:this}),b.tsx("button",{type:"button","aria-label":h.reset,class:this.classes("esri-widget--button","esri-print__refresh-button","esri-icon-refresh"),tabIndex:0,onclick:this._resetToCurrentScale,bind:this}))),G=this._advancedOptionsVisibleForLayout?b.tsx("div",{"aria-labelledby":`${this.id}__advancedOptionsForLayout`,class:"esri-print__advanced-options-container"},
F,b.tsx("div",{class:this.classes("esri-print__author-info-container","esri-print__form-section-container")},b.tsx("label",null,h.author,b.tsx("input",{type:"text",value:d,class:this.classes("esri-print__input-text","esri-input"),tabIndex:0,"data-input-name":"author",onchange:this._updateInputValue,bind:this}))),b.tsx("div",{class:this.classes("esri-print__copyright-info-container","esri-print__form-section-container")},b.tsx("label",null,h.copyright,b.tsx("input",{type:"text",class:this.classes("esri-print__input-text",
"esri-input"),tabIndex:0,value:a,"data-input-name":"copyright",onchange:this._updateInputValue,bind:this}))),A,b.tsx("div",{class:this.classes("esri-print__legend-info-container","esri-print__form-section-container")},b.tsx("label",null,b.tsx("input",{type:"checkbox","data-option-name":"legendEnabled",tabIndex:0,checked:q,onchange:this._toggleInputValue,bind:this}),h.legend)),this.renderCustomTextElementSection()):null;A=this._advancedOptionsVisibleForMapOnly?b.tsx("div",{"aria-labelledby":`${this.id}__advancedOptionsForMapOnly`,
class:"esri-print__advanced-options-container"},F,A,b.tsx("div",{class:"esri-print__form-section-container"},b.tsx("label",null,b.tsx("input",{"data-option-name":"attributionEnabled",type:"checkbox",onchange:this._toggleInputValue,tabIndex:0,checked:c,bind:this}),h.attribution)),this.renderCustomTextElementSection()):null;z=this._layoutTabSelected?b.tsx("section",{key:"esri-print__layoutContent",id:`${this.id}__layoutContent`,"aria-labelledby":`${this.id}__layoutTab`,class:"esri-print__layout-section",
role:"tabpanel","aria-selected":this._layoutTabSelected.toString()},b.tsx("div",{class:"esri-print__panel-container"},u,z,this._layoutTabSelected?x:null),b.tsx("div",{class:this.classes("esri-print__panel-container","esri-print__advanced-options-section")},b.tsx("button",{"aria-label":h.advancedOptions,"aria-expanded":this._advancedOptionsVisibleForLayout?"true":"false",class:"esri-print__advanced-options-button",onclick:this._showAdvancedOptions,bind:this,type:"button"},b.tsx("div",{class:"esri-print__advanced-options-button-container"},
b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-icon-right-triangle-arrow","esri-print__advanced-options-button-icon--closed")}),b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-icon-left-triangle-arrow","esri-print__advanced-options-button-icon--closed-rtl")}),b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-icon-down-arrow","esri-print__advanced-options-button-icon--opened")}),b.tsx("span",{class:"esri-print__advanced-options-button-title"},h.advancedOptions))),
G)):b.tsx("section",{key:"esri-print__mapOnlyContent",id:`${this.id}__mapOnlyContent`,"aria-selected":(!this._layoutTabSelected).toString(),"aria-labelledby":`${this.id}__mapOnlyTab`,class:"esri-print__map-only-section",role:"tabpanel"},b.tsx("div",{class:"esri-print__panel-container"},u,this._layoutTabSelected?null:x,b.tsx("div",{class:this.classes("esri-print__size-container","esri-print__form-section-container")},b.tsx("div",{class:"esri-print__width-container"},b.tsx("label",null,h.width,b.tsx("input",
{type:"number",class:this.classes("esri-print__input-text","esri-input"),"data-input-name":"width",onchange:this._updateInputValue,value:`${K}`,tabIndex:0,bind:this}))),b.tsx("div",{class:"esri-print__height-container"},b.tsx("label",null,h.height,b.tsx("input",{type:"number",class:this.classes("esri-print__input-text","esri-input"),"data-input-name":"height",onchange:this._updateInputValue,value:`${g}`,tabIndex:0,bind:this}))),b.tsx("button",{type:"button","aria-label":h.swap,class:this.classes("esri-widget--button",
"esri-print__swap-button","esri-icon-swap"),onclick:this._switchInput,tabIndex:0,bind:this})),b.tsx("div",{class:this.classes("esri-print__panel-container","esri-print__advanced-options-section")},b.tsx("button",{"aria-label":h.advancedOptions,"aria-expanded":this._advancedOptionsVisibleForMapOnly?"true":"false",type:"button",class:"esri-print__advanced-options-button",onclick:this._showAdvancedOptions,bind:this},b.tsx("div",{class:"esri-print__advanced-options-button-container"},b.tsx("span",{"aria-hidden":"true",
class:this.classes("esri-icon-right-triangle-arrow","esri-print__advanced-options-button-icon--closed")}),b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-icon-left-triangle-arrow","esri-print__advanced-options-button-icon--closed-rtl")}),b.tsx("span",{"aria-hidden":"true",class:this.classes("esri-icon-down-arrow","esri-print__advanced-options-button-icon--opened")}),b.tsx("span",{class:"esri-print__advanced-options-button-title"},h.advancedOptions))),A)));G=this.exportedLinks.toArray();
A=this._renderExportedLink(G);F={["esri-button--disabled"]:p||!n&&!f};u=null!=this.get("view")&&"2d"!==this.get("view.type");x=b.tsx("div",{class:"esri-print__panel--error"},u?h.sceneViewError:h.serviceError);p=b.tsx("div",null,b.tsx("ul",{class:"esri-print__layout-tab-list",role:"tablist",onclick:this._toggleLayoutPanel,onkeydown:this._handleLayoutPanelKeyDown,bind:this},b.tsx("li",{afterCreate:this._focusOnTabChange,afterUpdate:this._focusOnTabChange,id:`${this.id}__layoutTab`,"data-tab-id":"layoutTab",
class:"esri-print__layout-tab",role:"tab",tabIndex:0,"aria-selected":`${this._layoutTabSelected}`},h.layoutTab),b.tsx("li",{afterCreate:this._focusOnTabChange,afterUpdate:this._focusOnTabChange,id:`${this.id}__mapOnlyTab`,"data-tab-id":"mapOnlyTab",class:"esri-print__layout-tab",role:"tab",tabIndex:0,"aria-selected":`${!this._layoutTabSelected}`},h.mapOnlyTab)),z,b.tsx("button",{"aria-label":h.exportDescription,type:"button",class:this.classes("esri-print__export-button","esri-button",F),disabled:p,
tabIndex:0,onclick:this._handlePrintMap,bind:this},h.export),L&&0<Z.defaultTemplates.length?this.renderTemplateSectionTrigger():null,b.tsx("div",{class:"esri-print__export-panel-container",afterUpdate:this._scrollExportIntoView,bind:this},b.tsx(R.Heading,{class:"esri-print__export-title",level:this.headingLevel},h.exportText),0<G.length?null:b.tsx("div",null,b.tsx("div",null,h.exportHint)),A));p=b.tsx("div",{class:"esri-print__container"},b.tsx("header",{class:"esri-print__header-title"},h.export),
this.error||u||!this.view?x:p);p="initializing"===this.get("viewModel.state")?this._renderLoader():p;return b.tsx("div",{afterCreate:this._handleRootAfterCreate,bind:this,class:this.classes("esri-print","esri-widget","esri-widget--panel")},p)};k.renderTemplateSectionTrigger=function(){const {messages:c,_templateListPopover:d}=this,a=d.open;return b.tsx("button",{afterCreate:e=>this._selectTemplateNode=e,"aria-controls":a?`${this.id}__template-selection`:"","aria-label":c.selectTemplateDescription,
"aria-pressed":a.toString(),class:this.classes("esri-button","esri-button--tertiary","esri-print__template-button"),onclick:this.handleSelectTemplateClick,title:c.selectTemplateDescription},c.selectTemplate)};k.renderCustomTextElementSection=function(){const {templateOptions:{customTextElements:c}}=this;return c?b.tsx("div",{class:"esri-print__form-section-container",key:"custom-text-elements"},c.map(d=>{const [a,e]=Object.entries(d)[0];return"date"===a?null:b.tsx("label",{key:a},a,b.tsx("input",
{bind:this,class:this.classes("esri-print__input-text","esri-input"),"data-input-custom":!0,"data-input-name":a,onchange:this._updateInputValue,type:"text",value:e}))})):null};k.renderTemplateList=function(){const {messages:c,messagesCommon:d,viewModel:a}=this,{defaultTemplates:e}=a,f=c.selectTemplateDescription,g=`${this.id}__template-selection`;return b.tsx("div",{class:this.classes("esri-print__template-list","esri-widget","esri-widget--panel"),id:g},b.tsx(R.Heading,{class:"esri-menu__header",
level:this.headingLevel},c.selectTemplate),b.tsx("div",{class:"esri-print__template-list-scroller"},b.tsx("ul",{afterCreate:this.handleTemplateListCreation,"aria-activedescendant":`${this.id}__template-item--${this._focusedTemplateIndex}`,"aria-label":f,class:"esri-menu__list",key:"templates",onblur:this.handleTemplateChildBlur,onclick:this.handleTemplateListClick,onkeydown:this.handleTemplateListKeyDown,role:"listbox",tabIndex:0,title:f},e.toArray().map((n,q)=>{const {description:r}=n,t=n.label;
return b.tsx("li",{"aria-label":r,class:this.classes("esri-menu__list-item",{["esri-menu__list-item--focus"]:q===this._focusedTemplateIndex}),"data-template":n,id:`${this.id}__template-item--${q}`,key:t,title:r},D(t)?c.mapOnlyTab:t)}))),b.tsx("div",{class:"esri-print__template-list-footer"},b.tsx("button",{type:"button",class:this.classes("esri-button","esri-button--secondary"),onblur:this.handleTemplateChildBlur,onclick:this.handleCloseTemplateSelection},d.done)))};k.applyTemplate=function(c){var d;
const {format:a,layout:e,layoutOptions:f}=c;({templateOptions:c}=this);this._templateListPopover.open=!1;this._toggleTab("map-only"===e?"mapOnlyTab":"layoutTab",!1);a&&(c.format=a);e&&(c.layout=e);this._focusedTemplateIndex=null;c.legendEnabled=null!=(d=null==f?void 0:f.legend)?d:c.legendEnabled;this.handleCloseTemplateSelection()};k.renderTitleOrFileNameSection=function(){const {templateOptions:c,messages:d}=this;let a,e,f,g;this._layoutTabSelected?(a=d.title,e=d.titlePlaceHolder,f=c.title,g="title"):
(a=d.fileName,e=d.fileNamePlaceHolder,f=c.fileName,g="fileName");return b.tsx("div",{class:"esri-print__form-section-container",key:g},b.tsx("label",null,a,b.tsx("input",{type:"text",tabIndex:0,placeholder:e,class:this.classes("esri-print__input-text","esri-input"),value:f,"data-input-name":g,onchange:this._updateInputValue,bind:this})))};k._handleRootAfterCreate=function(c){this._rootNode=c;this.own(M.on(c,"scroll",()=>{this._templateListPopover.open&&this.handleCloseTemplateSelection()}))};k._focusOnTabChange=
function(c){if(this._activeTabFocusRequested){var d=c.getAttribute("data-tab-id");if("layoutTab"===d&&this._layoutTabSelected||"mapOnlyTab"===d&&!this._layoutTabSelected)c.focus(),this._activeTabFocusRequested=!1}};k._renderLoader=function(){return b.tsx("div",{class:this.classes({["esri-print__loader"]:this._awaitingServerResponse}),key:"loader"})};k._createFileLink=function(c,d){d=d||this.messages.untitled;c=c.format.toLowerCase();c=-1<c.indexOf("png")?"png":c;const a=d+c;void 0!==this._exportedFileNameMap[a]?
this._exportedFileNameMap[a]++:this._exportedFileNameMap[a]=0;return new O({name:d,extension:c,count:this._exportedFileNameMap[a]})};k._resetToCurrentScale=function(){this.templateOptions.scale=this.viewModel.view.scale};k._updateCustomTextElementValue=function(c,d,a){c.find(e=>{[e]=Object.entries(e)[0];return e===d})[d]=a};k._updateInputValue=function(c){var d=c.target;c=d.getAttribute("data-input-name");var a=!!d["data-input-custom"];const {templateOptions:e}=this;if(a)this._updateCustomTextElementValue(e.customTextElements,
c,d.value);else{if("number"===d.type){a=d.valueAsNumber;if(isNaN(a)||!(0<a)){d.value=`${e[c]}`;return}d=d.valueAsNumber}else d=d.value;e[c]=d}};k._handleDPIChange=function(c){this._updateInputValue(c);c=c.currentTarget.valueAsNumber;const {height:d,width:a}={width:Math.round(8.3333*c),height:Math.round(11.4583*c)};({templateOptions:c}=this);c.height=d;c.width=a};k._handlePrintMap=function(){this._pendingExportScroll=!0;const {templateOptions:c}=this,d=this.viewModel.toPrintTemplate(c),a=this._createFileLink(d,
this._layoutTabSelected?d.layoutOptions.titleText:c.fileName);this.exportedLinks.add(a);this.emit("submit",{link:a});this.viewModel.print(d).then(e=>{a.set({url:e&&e.url,state:"ready"})}).catch(e=>{a.set({error:e,state:"error"})}).then(()=>{this.emit("complete",{link:a});this.scheduleRender()})};k._updateFromOption=function(c){var d=c.target;c=d.selectedOptions?d.selectedOptions.item(0).value:d.options[d.selectedIndex].value;d=d.getAttribute("data-target-property");this.templateOptions[d]=c};k._switchInput=
function(){[this.templateOptions.width,this.templateOptions.height]=[this.templateOptions.height,this.templateOptions.width]};k._showAdvancedOptions=function(){this._layoutTabSelected?this._advancedOptionsVisibleForLayout=!this._advancedOptionsVisibleForLayout:this._advancedOptionsVisibleForMapOnly=!this._advancedOptionsVisibleForMapOnly};k._scrollExportIntoView=function(){if(this._pendingExportScroll){this._pendingExportScroll=!1;const {_rootNode:c,_rootNode:{clientHeight:d,scrollHeight:a}}=this,
e=a-d;0<e&&(c.scrollTop=e)}};k._toggleInputValue=function(c){c=c.target;const d=c.getAttribute("data-option-name");this.templateOptions[d]=c.checked;"scaleEnabled"===d&&(this.templateOptions[d]||this._resetToCurrentScale())};k._renderExportedLink=function(c){const d=this.messages;return c.map(a=>{const {error:e,url:f,formattedName:g,state:n}=a,q="error"===n,r="pending"===n,t="ready"===n,K={["esri-widget__anchor--disabled"]:r||q};let p=f||null;p&&(p=N.addProxy(p));var u=N.hasSameOrigin(f,location.href);
u={["esri-icon-loading-indicator"]:r,["esri-rotating"]:r,["esri-icon-download"]:u&&t,["esri-icon-launch-link-external"]:!u&&t,["esri-icon-error"]:q,["esri-print__exported-file--error"]:q};const L={["esri-print__exported-file--error"]:q};return b.tsx("div",{"aria-label":r?d.pending:t?d.ready:d.errorMessage,class:"esri-print__exported-file","data-item":a,key:g,onclick:this._removeLink,title:q?"print-task:cim-symbol-unsupported"===e.name?d.exportWebMapCIMError:d.exportWebMapError:""},b.tsx("a",{"aria-label":`${g}. ${d.linkReady}`,
download:g,href:p,rel:"noreferrer",tabIndex:0,target:"_blank",class:this.classes("esri-widget__anchor esri-print__exported-file-link",K)},b.tsx("span",{class:this.classes(u)}),b.tsx("span",{class:this.classes("esri-print__exported-file-link-title",L)},g)))})};k._toggleLayoutPanel=function(c){this._toggleTab(c.target.getAttribute("data-tab-id"))};k._toggleTab=function(c,d=!0){(this._layoutTabSelected="layoutTab"===c)?(c=this.get("viewModel.templatesInfo.layout.choiceList"),this.templateOptions.layout=
c&&c[0]):this.templateOptions.layout="MAP_ONLY";d&&(this._activeTabFocusRequested=!0)};k._handleLayoutPanelKeyDown=function(c){const d=M.eventKey(c),a=c.target.getAttribute("data-tab-id");if(I.isActivationKey(d))this._toggleTab(a),c.preventDefault(),c.stopPropagation();else if("ArrowLeft"===d||"ArrowRight"===d)this._toggleTab("layoutTab"===a?"mapOnlyTab":"layoutTab"),c.preventDefault(),c.stopPropagation()};return J}(X);m.__decorate([w.aliasOf("viewModel.allowedFormats")],l.prototype,"allowedFormats",
void 0);m.__decorate([w.aliasOf("viewModel.allowedLayouts")],l.prototype,"allowedLayouts",void 0);m.__decorate([w.aliasOf("viewModel.error")],l.prototype,"error",void 0);m.__decorate([y.property({type:T})],l.prototype,"exportedLinks",void 0);m.__decorate([w.aliasOf("viewModel.extraParameters")],l.prototype,"extraParameters",void 0);m.__decorate([y.property()],l.prototype,"headingLevel",void 0);m.__decorate([y.property()],l.prototype,"iconClass",void 0);m.__decorate([w.aliasOf("viewModel.includeDefaultTemplates")],
l.prototype,"includeDefaultTemplates",void 0);m.__decorate([y.property({aliasOf:{source:"messages.widgetLabel",overridable:!0}})],l.prototype,"label",void 0);m.__decorate([y.property(),S.messageBundle("esri/widgets/Print/t9n/Print")],l.prototype,"messages",void 0);m.__decorate([y.property(),S.messageBundle("esri/t9n/common")],l.prototype,"messagesCommon",void 0);m.__decorate([w.aliasOf("viewModel.portal")],l.prototype,"portal",void 0);m.__decorate([w.aliasOf("viewModel.printServiceUrl")],l.prototype,
"printServiceUrl",void 0);m.__decorate([w.aliasOf("viewModel.templateCustomTextElements")],l.prototype,"templateCustomTextElements",void 0);m.__decorate([y.property({type:Q})],l.prototype,"templateOptions",void 0);m.__decorate([w.aliasOf("viewModel.view")],l.prototype,"view",void 0);m.__decorate([y.property({type:P})],l.prototype,"viewModel",void 0);return l=m.__decorate([W.subclass("esri.widgets.Print")],l)});