// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../intl ../core/deprecate ../core/domUtils ../core/Evented ../core/Handles ../core/has ../core/lang ../core/Logger ../core/maybe ../core/Promise ../core/promiseUtils ../core/uuid ../core/watchUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/accessorSupport/decorators/subclass ../core/accessorSupport/tracking ../core/accessorSupport/tracking/SimpleTrackingTarget ../libs/maquette-advanced-projector/projector ../chunks/componentsUtils ./support/jsxWidgetSupport ./support/widgetUtils ../intl/locale ../intl/messages".split(" "),
function(l,f,d,H,I,J,K,aa,L,M,C,N,w,O,D,g,P,Q,R,S,T,U,z,E,V,W){function F(m,e){for(const c in e)null!=m[c]&&("object"===typeof m[c]&&"object"===typeof e[c]?F(m[c],e[c]):m[c]=e[c]);return m}const G=M.getLogger("esri.widgets.Widget");let X=0;const v=new Map,Y=T.createAdvancedProjector({postProcessProjectionOptions(m){const e=m.eventHandlerInterceptor,c=/capture$/i;m.eventHandlerInterceptor=(b,n,a,k)=>{const q=e(b,n,a,k),t=c.test(b);b=b.replace(c,"");if(!(b.toLowerCase()in a)||t){const p=b[2].toLowerCase()+
b.slice(3),r=u=>q.call(a,u);a.addEventListener(p,r,t);const h=k.afterRemoved;k.afterRemoved=u=>{null==h?void 0:h(u);a.removeEventListener(p,r,t)}}return q}},handleInterceptedEvent(m,e,c,b){const {eventPhase:n,type:a}=b,k=n===Event.CAPTURING_PHASE;let q=`on${a}${k?"capture":""}`;e=e.properties;if(!(q in e||(q=`on${a[0].toUpperCase()}${a.slice(1)}${k?"Capture":""}`,q in e)))return;v.clear();m.scheduleRender();e[q].call(e.bind||c,b)}});let A=!1;d=function(m){function e(b,n){var a=m.call(this,b,n)||this;
a._attached=!1;a._internalHandles=new K;a._projector=Y;a._readyForTrueRender=!1;a.domNode=null;a.iconClass="esri-icon-checkbox-unchecked";a.label=a.declaredClass.split(".").pop();a.visible=!0;a.key=l._assertThisInitialized(a);a._loadLocale=w.debounce(l._asyncToGenerator(function*(){if(a._messageBundleProps&&a._messageBundleProps.length){const p=yield w.eachAlways(a._messageBundleProps.map(function(){var r=l._asyncToGenerator(function*({bundlePath:h,propertyName:u}){h=yield W.fetchMessageBundle(h);
a.uiStrings&&Object.keys(a.uiStrings)&&(h=F(L.clone(h),a.uiStrings));a[u]=h});return function(h){return r.apply(this,arguments)}}()));for(const r of p)r.error&&G.error("widget-intl:locale-error",a.declaredClass,r.error)}yield a.loadLocale()}));U.commitAssetPath();b=E.getThemeName()||"light";["light","dark"].includes(b)||H.deprecated(G,"The following themes are deprecated: light-blue, dark-blue, light-green, dark-green, light-purple, dark-purple, light-red, and dark-red.",{version:"4.19",warnOnce:!0,
see:"https://developers.arcgis.com/javascript/latest/styling/"});const k="esri-widget-uid-"+O.generateUUID(),q=a.render.bind(l._assertThisInitialized(a));a._trackingTarget=new S.SimpleTrackingTarget(()=>a.scheduleRender());const t=()=>{var p;if(!a._readyForTrueRender||a.destroyed)return null;if(!a.visible)return{vnodeSelector:"div",properties:{key:k,class:"",styles:{display:"none"}},domNode:void 0,children:void 0,text:void 0};const r=q();let {properties:h}=r;h||(r.properties=h={});let {key:u,styles:x}=
h;u||(h.key=k);x||(h.styles=x={});x.display||(x.display="");let Z=0;null==(p=r.children)?void 0:p.forEach(B=>{if(!z.isWidgetConstructor(B.vnodeSelector)){var {properties:y}=B;y||(B.properties=y={});y.key||(y.key=`${a.id}--${Z++}`)}});return z.processWidgets(l._assertThisInitialized(a),r)};a.render=()=>{if(A)return t();let p=v.get(l._assertThisInitialized(a));if(p)return p;a._trackingTarget.clear();A=!0;try{p=R.runTracked(a._trackingTarget,t)}finally{A=!1}v.set(l._assertThisInitialized(a),p);return p};
a.addResolvingPromise(a._resourcesFetch=a.beforeFirstRender().then(()=>{a._readyForTrueRender=!0;a._postInitialize()}));return a}l._inheritsLoose(e,m);var c=e.prototype;c.normalizeCtorArgs=function(b,n){b={...b};n&&(b.container=n);return b};c.postInitialize=function(){};c.beforeFirstRender=function(){return Promise.all([this.loadDependencies(),this._loadLocale()]).then(()=>{}).catch(w.throwIfNotAbortError)};c.loadDependencies=function(){var b=l._asyncToGenerator(function*(){});return function(){return b.apply(this,
arguments)}}();c.loadLocale=function(){var b=l._asyncToGenerator(function*(){});return function(){return b.apply(this,arguments)}}();c.destroy=function(){this.destroyed||(this._trackingTarget=C.destroyMaybe(this._trackingTarget),this.viewModel=C.destroyMaybe(this.viewModel),this._detach(this.container),this._set("container",null),this._internalHandles.destroy(),this._emitter.clear(),this.render=()=>null,this._projector=null,v.delete(this))};c.castContainer=function(b){return I.byId(b)};c.render=function(){throw Error("not implemented");
};c.scheduleRender=function(){this.destroyed||(v.delete(this),this._projector.scheduleRender())};c.classes=function(...b){return E.classes.apply(this,b)};c.own=function(b){1<arguments.length&&(b=Array.prototype.slice.call(arguments));this._internalHandles.add(b)};c.renderNow=function(){v.delete(this);this._projector.renderNow()};c._postInitialize=function(){var b,n=this;this.destroyed||(this.scheduleRender(),null!=(b=this._delegatedEventNames)&&b.length&&this._internalHandles.add(D.init(this,"viewModel",
(a,k)=>{k&&this._internalHandles.remove("delegated-events");a&&this._internalHandles.add(this._delegatedEventNames.map(q=>a.on(q,t=>{this.emit(q,t)})),"delegated-events")})),this.postInitialize(),b=function(){var a=l._asyncToGenerator(function*(){yield n._loadLocale().catch(w.throwIfNotAbortError);n.scheduleRender()});return function(){return a.apply(this,arguments)}}(),this._internalHandles.add([V.onLocaleChange(b),this.watch("uiStrings",b),D.whenOnce(this,"container",function(){var a=l._asyncToGenerator(function*(k){n.destroyed||
n._attach(k)});return function(k){return a.apply(this,arguments)}}())]))};c._attach=function(b){b&&(this._projector.merge(b,this.render),this._attached=!0)};c._detach=function(b){b&&this._attached&&(this._projector.detach(this.render),b.parentNode&&b.parentNode.removeChild(b),this._attached=!1)};l._createClass(e,[{key:"container",set:function(b){this._get("container")||this._set("container",b)}},{key:"id",get:function(){return this._get("id")||this.get("container.id")||Date.now().toString(16)+"-widget-"+
X++},set:function(b){b&&this._set("id",b)}},{key:"renderable",get:function(){return this._resourcesFetch}},{key:"test",get:function(){return{projector:this._projector,handles:this._internalHandles}}}]);return e}(N.EsriPromiseMixin(J.EventedAccessor));d[z.WIDGET_SYMBOL]=!0;f.__decorate([g.property()],d.prototype,"_readyForTrueRender",void 0);f.__decorate([g.property({value:null})],d.prototype,"container",null);f.__decorate([P.cast("container")],d.prototype,"castContainer",null);f.__decorate([g.property({aliasOf:"container"})],
d.prototype,"domNode",void 0);f.__decorate([g.property()],d.prototype,"iconClass",void 0);f.__decorate([g.property()],d.prototype,"id",null);f.__decorate([g.property()],d.prototype,"label",void 0);f.__decorate([g.property()],d.prototype,"renderable",null);f.__decorate([g.property()],d.prototype,"uiStrings",void 0);f.__decorate([g.property()],d.prototype,"viewModel",void 0);f.__decorate([g.property()],d.prototype,"visible",void 0);f.__decorate([g.property()],d.prototype,"key",void 0);f.__decorate([g.property()],
d.prototype,"children",void 0);f.__decorate([g.property()],d.prototype,"afterCreate",void 0);f.__decorate([g.property()],d.prototype,"afterUpdate",void 0);f.__decorate([g.property()],d.prototype,"afterRemoved",void 0);return d=f.__decorate([Q.subclass("esri.widgets.Widget")],d)});