// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../intl ../../../../core/Accessor ../../../../core/Handles ../../../../core/mathUtils ../../../../core/maybe ../../../../core/quantityFormatUtils ../../../../core/reactiveUtils ../../../../core/screenUtils ../../../../core/unitUtils ../../../../core/watchUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/vec2 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4f32 ../../../../geometry/projectionEllipsoid ../support/viewUtils ../../interactive/visualElements/LabelVisualElement ../../interactive/visualElements/LineVisualElement ../../interactive/visualElements/MeasurementArrowVisualElement ../../interactive/visualElements/RightAngleQuadVisualElement ../../interactive/visualElements/support/Segment ../../webgl-engine/materials/lineStippleUtils ../../../../intl/locale ../../../../intl/messages".split(" "),
function(k,A,m,da,N,O,G,f,q,u,x,H,I,n,ea,fa,ha,P,J,K,y,Q,R,E,z,B,S,T,w,F,U,V){k.DirectLineMeasurementVisualization=function(L){function C(a){a=L.call(this,a)||this;a._params={...W};a._handles=new O;a._segmentVisualElement=null;a._triangleVisualElement=null;a._rightAngleQuad=null;a._projectedGeodesicLine=null;a._geodesicStartHint=null;a._geodesicEndHint=null;a._segmentLabel=null;a._verticalLabel=null;a._horizontalLabel=null;a._startPosition=y.create();a._endPosition=y.create();a._cornerPosition=y.create();
a._startPositionAtSeaLevel=y.create();a._endPositionAtSeaLevel=y.create();a._state=0;a._triangleOrientationOverride=null;a.messages=null;a.loadingMessages=!0;a.visualElementOrientation=0;a.triangleCollapseRatioThreshold=.03;return a}A._inheritsLoose(C,L);var r=C.prototype;r.initialize=function(){this._handles.add(I.whenOnce(this.view,"ready",()=>this._initialize(),!0))};r._initialize=function(){var a=this;switch(this._state){case 1:throw Error("invalid state");case 2:return}const b=this._params,c=
{attached:!0,view:this.view};this._segmentVisualElement=new S.MeasurementArrowVisualElement({...c,geometry:null,renderOccluded:4});this._triangleVisualElement=new B.LineVisualElement({...c,width:b.triangleLineWidth,color:b.triangleColor,renderOccluded:4});this._rightAngleQuad=new T.RightAngleQuadVisualElement({...c,color:D,renderOccluded:4});const e={...c,polygonOffset:!0,renderOccluded:4};this._projectedGeodesicLine=new B.LineVisualElement({...e,width:b.geodesicProjectionLineWidth,color:b.geodesicProjectionLineColor,
stipplePattern:F.createStipplePatternSimple(b.guideStippleLengthPixels)});this._geodesicStartHint=new B.LineVisualElement({...e,width:b.guideLineWidth,color:b.geodesicProjectionLineColor,stipplePattern:F.createStipplePatternSimple(b.guideStippleLengthPixels)});this._geodesicEndHint=new B.LineVisualElement({...e,width:b.guideLineWidth,color:b.geodesicProjectionLineColor,stipplePattern:F.createStipplePatternSimple(b.guideStippleLengthPixels)});this._segmentLabel=new z.LabelVisualElement({...c,fontSize:b.direcLabelFontSize});
this._verticalLabel=new z.LabelVisualElement({...c,fontSize:b.verticalLabelFontSize});this._horizontalLabel=new z.LabelVisualElement({...c,fontSize:b.horizontalLabelFontSize});this._handles.add([u.react(()=>{const {elevationAlignedStartPoint:d,elevationAlignedEndPoint:h}=this.analysisView,p=this.view;return{view:p,camera:p.state.camera,viewMode:this.viewMode,elevationAlignedStartPoint:d,elevationAlignedEndPoint:h,orientation:this._actualVisualElementsOrientation,visualizedMeasurement:this.actualVisualizedMeasurement,
stripeLength:this._measurementArrowStripeLength}},d=>this._updateGeometryAndViewMode(d),u.syncAndInitial),u.react(()=>({visible:this.visible,viewMode:this.viewMode}),d=>this._updateVisualElementVisibility(d),u.syncAndInitial),u.react(()=>({text:this._labelsText,visualizedMeasurement:this.actualVisualizedMeasurement}),d=>this._updateLabelText(d),u.syncAndInitial),u.react(()=>({visible:this.visible,viewMode:this.viewMode,state:this._state}),d=>this._updateLabelVisibility(d),u.syncAndInitial),u.react(()=>
this._measurementArrowStripeLength,d=>this._updateSegmentStripeLength(d),u.syncAndInitial),U.onLocaleChange(A._asyncToGenerator(function*(){return a._updateMessageBundle()}))]);this._state=1;this._updateMessageBundle()};r.destroy=function(){2!==this._state&&(this._handles=f.destroyMaybe(this._handles),this._segmentVisualElement=f.destroyMaybe(this._segmentVisualElement),this._triangleVisualElement=f.destroyMaybe(this._triangleVisualElement),this._rightAngleQuad=f.destroyMaybe(this._rightAngleQuad),
this._projectedGeodesicLine=f.destroyMaybe(this._projectedGeodesicLine),this._geodesicStartHint=f.destroyMaybe(this._geodesicStartHint),this._geodesicEndHint=f.destroyMaybe(this._geodesicEndHint),this._segmentLabel=f.destroyMaybe(this._segmentLabel),this._verticalLabel=f.destroyMaybe(this._verticalLabel),this._horizontalLabel=f.destroyMaybe(this._horizontalLabel),this.set("view",null),this._state=2)};r.whenReady=function(){var a=A._asyncToGenerator(function*(){yield I.whenOnce(this,"ready")});return function(){return a.apply(this,
arguments)}}();r._updateVisualElementVisibility=function({visible:a,viewMode:b}){this._segmentVisualElement.visible=!1;this._triangleVisualElement.visible=!1;this._rightAngleQuad.visible=!1;this._projectedGeodesicLine.visible=!1;this._geodesicStartHint.visible=!1;this._geodesicEndHint.visible=!1;if(a)switch(b){case 1:this._segmentVisualElement.visible=!0;break;case 2:this._segmentVisualElement.visible=!0;this._triangleVisualElement.visible=!0;this._rightAngleQuad.visible=!0;break;case 3:this._segmentVisualElement.visible=
!0,this._projectedGeodesicLine.visible=!0,this._geodesicStartHint.visible=!0,this._geodesicEndHint.visible=!0}};r._updateGeometryAndViewMode=function({view:a,camera:b,viewMode:c,elevationAlignedStartPoint:e,elevationAlignedEndPoint:d,orientation:h,visualizedMeasurement:p,stripeLength:g}){const l=a.renderCoordsHelper;if(!(f.isNone(e)||f.isNone(d)||e.equals(d))){var t=this._startPosition,v=this._endPosition;l.toRenderCoords(e,t);l.toRenderCoords(d,v);e=1===h?1:-1;d=l.getAltitude(v);var X=l.getAltitude(t);
d=e*(d-X);0>d&&(t=this._endPosition,v=this._startPosition);p="geodesic"===p?new w.GeodesicSegment(this._startPosition,this._endPosition,l.spatialReference):new w.EuclideanSegment(this._startPosition,this._endPosition);this._segmentVisualElement.geometry=p;this._updateSegmentStripeLength(g);switch(c){case 1:this._updateSegment(p,h);break;case 2:this._updateSegmentAndTriangle({view:a,camera:b,segment:p,orientation:h,startPosition:t,endPosition:v,deltaSign:e,altitudeDelta:d});break;case 3:this._updateSegmentAndProjection({view:a,
orientation:h,startPosition:t,endPosition:v})}}};r._updateSegment=function(a,b){this._segmentLabel.anchor=1===b?"top":"bottom";this._segmentLabel.geometry={type:"segment",segment:a,sampleLocation:"center"}};r._updateSegmentAndTriangle=function({view:{renderCoordsHelper:a},camera:b,segment:c,orientation:e,startPosition:d,endPosition:h,deltaSign:p,altitudeDelta:g}){const l=this._cornerPosition;a.worldUpAtPosition(d,l);K.scale(l,l,p*Math.abs(g));K.add(l,l,d);this._triangleVisualElement.geometry=[[[d[0],
d[1],d[2]],[l[0],l[1],l[2]],[h[0],h[1],h[2]]]];this._rightAngleQuad.geometry={previous:d,center:l,next:h};a=new w.EuclideanSegment(d,l);p=new w.EuclideanSegment(l,h);g=Y;var t=Z;b.projectToRenderScreen(l,g);b.projectToRenderScreen(h,t);g={segment:"bottom",horizontal:"top",vertical:g[0]<t[0]?"left":"right"};{const v=aa;t=ba;E.screenSpaceTangent(d,l,v,b);E.screenSpaceTangent(d,h,t,b);J.dot(v,t)>=M?g.segment=Math.sign(v[1])===Math.sign(t[1])?z.mirrorPosition(g.vertical):g.vertical:(d=ca,E.screenSpaceTangent(l,
h,d,b),J.dot(d,t)>=M&&(g.segment=Math.sign(d[0])===Math.sign(t[0])?z.mirrorPosition(g.horizontal):g.horizontal))}2===e&&(g.segment="top"===g.segment?"bottom":"top",g.horizontal="top"===g.horizontal?"bottom":"top",g.vertical="top"===g.vertical?"bottom":"top");b=g;this._segmentLabel.anchor=b.segment;this._segmentLabel.geometry={type:"segment",segment:c,sampleLocation:"center"};this._verticalLabel.geometry={type:"segment",segment:a,sampleLocation:"center"};this._verticalLabel.anchor=b.vertical;this._horizontalLabel.geometry=
{type:"segment",segment:p,sampleLocation:"center"};this._horizontalLabel.anchor=b.horizontal};r._updateSegmentAndProjection=function({view:{renderCoordsHelper:a},orientation:b,startPosition:c,endPosition:e}){a.setAltitude(this._startPositionAtSeaLevel,0,c);a.setAltitude(this._endPositionAtSeaLevel,0,e);a=new w.GeodesicSegment(this._startPositionAtSeaLevel,this._endPositionAtSeaLevel,a.spatialReference);this._projectedGeodesicLine.setGeometryFromSegment(a);this._geodesicStartHint.setGeometryFromSegment(new w.EuclideanSegment(this._startPositionAtSeaLevel,
c));this._geodesicEndHint.setGeometryFromSegment(new w.EuclideanSegment(this._endPositionAtSeaLevel,e));this._segmentLabel.geometry={type:"segment",segment:a,sampleLocation:"center"};this._segmentLabel.anchor=1===b?"top":"bottom"};r._updateLabelText=function({text:a,visualizedMeasurement:b}){f.isSome(a)?(this._segmentLabel.text="euclidean"===b?a.euclideanDistance:a.geodesicDistance,this._horizontalLabel.text=a.horizontalDistance,this._verticalLabel.text=a.verticalDistance):(this._segmentLabel.text=
null,this._horizontalLabel.text=null,this._verticalLabel.text=null);this.notifyChange("labels")};r._updateLabelVisibility=function({state:a,visible:b,viewMode:c}){if(1===a){a=this._segmentLabel;var e=this._horizontalLabel,d=this._verticalLabel;a.visible=!1;e.visible=!1;d.visible=!1;if(b)switch(c){case 1:a.visible=!0;break;case 2:a.visible=!0;e.visible=!0;d.visible=!0;break;case 3:a.visible=!0}}};r._updateSegmentStripeLength=function(a){const b=this._segmentVisualElement;f.isSome(a)?(b.stripeLength=
a,b.stripesEnabled=!0):b.stripesEnabled=!1};r._requiresGeodesicGuideAt=function(a){var b=this.view;if(null==b||!b.state)return!1;const c=b.renderCoordsHelper;b=b.state.camera.computeScreenPixelSizeAt(a);return 10<=c.getAltitude(a)/b};r._updateMessageBundle=function(){this.loadingMessages=!0;V.fetchMessageBundle("esri/core/t9n/Units").then(a=>{this.messages=a}).finally(()=>{this.loadingMessages=!1})};A._createClass(C,[{key:"ready",get:function(){return 1===this._state}},{key:"visible",get:function(){return this.analysisView.visible}},
{key:"viewMode",get:function(){const {elevationAlignedStartPoint:a,elevationAlignedEndPoint:b}=this.analysisView;if(f.isNone(a)||f.isNone(b)||a.equals(b))return 0;var c=this.analysisView.result;if(f.isNone(c))return 1;if("geodesic"===c.mode)return this._requiresGeodesicGuideAt(this._startPosition)||this._requiresGeodesicGuideAt(this._endPosition)?3:1;const {verticalDistance:e,horizontalDistance:d}=c;c=e.value;const h=d.value;return Math.min(c/h,h/c)<this.triangleCollapseRatioThreshold?1:2}},{key:"actualVisualizedMeasurement",
get:function(){if(f.isNone(this.analysisView.result))switch(this.analysisView.measurementMode){default:return"euclidean";case 2:return"geodesic"}return this.analysisView.result.mode}},{key:"allowVisualElementsOrientationChange",get:function(){return f.isNone(this._triangleOrientationOverride)},set:function(a){f.isNone(this._triangleOrientationOverride)!==a&&(f.isNone(this._triangleOrientationOverride)?this._triangleOrientationOverride=this._actualVisualElementsOrientation:this._triangleOrientationOverride=
null)}},{key:"labels",get:function(){return{direct:this._segmentLabel,horizontal:"geodesic"===this.actualVisualizedMeasurement?this._segmentLabel:this._horizontalLabel,vertical:this._verticalLabel}}},{key:"testData",get:function(){var a;return{labels:this.labels,stripeLength:null==(a=this._segmentVisualElement)?void 0:a.stripeLength}}},{key:"_labelsText",get:function(){if(1!==this._state)return null;var a=this.messages,b=this.analysisView.result;if(f.isNone(b)||f.isNone(a))return null;const {directDistance:c,
horizontalDistance:e,verticalDistance:d,geodesicDistance:h,geodesicAngle:p}=b,g=this.analysisView.unit;b=l=>({euclideanDistance:"",geodesicDistance:"",horizontalDistance:"",verticalDistance:"",...l});switch(g){case "metric":return b({euclideanDistance:c&&q.formatMetricLength(a,c),geodesicDistance:h&&q.formatMetricLength(a,h),horizontalDistance:e&&q.formatMetricLength(a,e),verticalDistance:d&&q.formatMetricVerticalLength(a,d)});case "imperial":return b({euclideanDistance:c&&q.formatImperialLength(a,
c),geodesicDistance:h&&q.formatImperialLength(a,h),horizontalDistance:e&&q.formatImperialLength(a,e),verticalDistance:d&&q.formatImperialVerticalLength(a,d)});case "degrees":return a=p&&q.formatDecimal(a,p,"degrees"),b({euclideanDistance:a,geodesicDistance:a,horizontalDistance:a});case "degrees-minutes-seconds":return b({horizontalDistance:p&&q.formatDMS(p)});default:return b({euclideanDistance:c&&q.formatDecimal(a,c,g),geodesicDistance:h&&q.formatDecimal(a,h,g),horizontalDistance:e&&q.formatDecimal(a,
e,g),verticalDistance:d&&q.formatDecimal(a,d,g)})}}},{key:"_actualVisualElementsOrientation",get:function(){if(f.isSome(this._triangleOrientationOverride))return this._triangleOrientationOverride;const a=this.visualElementOrientation;return 0===a?this.view.state.camera.aboveGround?1:2:a}},{key:"_measurementArrowStripeLength",get:function(){const {result:a,unit:b}=this.analysisView;if(f.isNone(a))return null;var c=null;c=a.directDistance;switch(b){case "metric":c=c&&c.toUnit("meters");break;case "imperial":c=
c&&c.toUnit(H.preferredImperialLengthUnit(c.value,c.unit));break;case "degrees":case "degrees-minutes-seconds":c=(c=a.geodesicAngle)&&c.toUnit("degrees");break;default:c=c&&c.toUnit(b)}return f.isNone(c)?null:G.nextHighestPowerOfTen(c.value/30)*("degrees"===c.unit?R.getReferenceEllipsoid(this.view.spatialReference).metersPerDegree:H.convertUnit(1,c.unit,"meters"))}}]);return C}(N);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"_state",void 0);m.__decorate([n.property()],
k.DirectLineMeasurementVisualization.prototype,"_triangleOrientationOverride",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"messages",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"view",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"analysis",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"analysisView",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,
"ready",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"loadingMessages",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"visible",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"viewMode",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"actualVisualizedMeasurement",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"visualElementOrientation",
void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"triangleCollapseRatioThreshold",void 0);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"allowVisualElementsOrientationChange",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"labels",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"testData",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,
"_labelsText",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"_actualVisualElementsOrientation",null);m.__decorate([n.property()],k.DirectLineMeasurementVisualization.prototype,"_measurementArrowStripeLength",null);k.DirectLineMeasurementVisualization=m.__decorate([P.subclass("esri.views.3d.analysis.DirectLineMeasurement.DirectLineMeasurementVisualization")],k.DirectLineMeasurementVisualization);const D=Q.fromValues(1,.5,0,.75),W={laserLineGlowColor:[1,.5,0],laserLineGlowWidth:8,
laserLineGlowFalloff:8,laserLineInnerColor:[1,1,1],laserLineInnerWidth:.75,laserLineGlobalAlpha:.75,laserLineEnabled:!0,handleColor:[1,.5,0],handleOpacity:.5,handleRadius:5,triangleColor:D,triangleLineWidth:3,triangleCornerSize:32,triangleSubdivisions:128,arrowWidth:16,arrowOutlineColor:[1,.5,0,1],arrowOutlineWidth:.2,arrowStripeEvenColor:[1,1,1,1],arrowStripeOddColor:[1,.5,0,1],arrowStripeLength:16,arrowSubdivisions:128,geodesicProjectionLineWidth:2,geodesicProjectionLineColor:D,guideLineWidth:2,
guideLineColor:D,guideStippleLengthPixels:6,labelDistance:25,direcLabelFontSize:16,horizontalLabelFontSize:12,verticalLabelFontSize:12},M=Math.cos(G.deg2rad(12)),Y=x.createRenderScreenPointArray3(),Z=x.createRenderScreenPointArray3(),aa=x.createRenderScreenPointArray(),ba=x.createRenderScreenPointArray(),ca=x.createRenderScreenPointArray();Object.defineProperty(k,"__esModule",{value:!0})});