// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Accessor ../../core/Collection ../../core/collectionUtils ../../core/Handles ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/reactiveUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../layers/BuildingSceneLayer ../../layers/support/BuildingFilter ./BuildingDisciplinesViewModel ./BuildingLevel ./BuildingPhase ./support/buildingLayerUtils ./support/filterUtils ./support/layerUtils".split(" "),
function(k,c,b,n,w,x,y,p,z,A,l,e,H,I,J,B,C,D,q,r,t,E,g,F){const G=y.getLogger("esri.widgets.BuildingExplorer.BuildingExplorerViewModel");b=function(u){function h(a){a=u.call(this,a)||this;a.view=null;a.state="disabled";a.level=new r;a.phase=new t;a.disciplines=new q;a._handles=new x;a._loadLayers=F.createLoadLayersFunction();a.layers=new n;return a}k._inheritsLoose(h,u);var m=h.prototype;m.initialize=function(){this._handles.add([this.layers.on("change",()=>this._onLayersChange()),A.react(()=>({filter:this._filter,
state:this.state}),({filter:a,state:d})=>{"ready"===d&&g.setFilterOnLayers(this.layers,a)},{initial:!0})]);this._onLayersChange()};m.destroy=function(){this._handles.destroy();this.level.destroyed||this.level.destroy();this.phase.destroyed||this.phase.destroy();this.disciplines.destroyed||this.disciplines.destroy()};m._onLayersChange=function(){var a=k._asyncToGenerator(function*(){this.level.layers=this.layers;this.phase.layers=this.layers;this.disciplines.layers=this.layers;if(0===this.layers.length)this._set("state",
"disabled");else{this._set("state","loading");try{yield this._loadLayers(this.layers),yield Promise.all([l.whenEqualOnce(this.level,"state","ready"),l.whenEqualOnce(this.phase,"state","ready"),l.whenEqualOnce(this.disciplines,"state","ready")]),this.layers.forEach(E.showFullModel),this._set("state","ready")}catch(d){z.isAbortError(d)||this._set("state","failed")}}});return function(){return a.apply(this,arguments)}}();k._createClass(h,[{key:"isSupported",get:function(){var a;return"3d"===(null==(a=
this.view)?void 0:a.type)}},{key:"layers",set:function(a){const d=a.filter(f=>f instanceof C);d.length!==a.length&&G.error("Some layers are not BuildingSceneLayers but only BuildingSceneLayers can be passed to the widget.");this._set("layers",w.referenceSetter(d,this._get("layers")))}},{key:"_filter",get:function(){var a=this.level.filterExpressions;const d=this.phase.filterExpressions,f=[],v=g.getFilterBlockSolid([a.solid,d.solid]);p.isSome(v)&&f.push(v);a=g.getFilterBlockXRay([a.xRay,d.xRay]);p.isSome(a)&&
f.push(a);return 0===f.length?null:new D({id:g.generateFilterId(),name:"Building Explorer Filter",filterBlocks:f})}}]);return h}(b);c.__decorate([e.property({value:null})],b.prototype,"view",void 0);c.__decorate([e.property()],b.prototype,"isSupported",null);c.__decorate([e.property({type:n,nonNullable:!0})],b.prototype,"layers",null);c.__decorate([e.property({readOnly:!0})],b.prototype,"state",void 0);c.__decorate([e.property({readOnly:!0,type:r})],b.prototype,"level",void 0);c.__decorate([e.property({readOnly:!0,
type:t})],b.prototype,"phase",void 0);c.__decorate([e.property({readOnly:!0,type:q})],b.prototype,"disciplines",void 0);c.__decorate([e.property({readOnly:!0})],b.prototype,"_filter",null);return b=c.__decorate([B.subclass("esri.widgets.BuildingExplorer.BuildingExplorerViewModel")],b)});