// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Handles ../../../../core/Logger ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/watchUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/boundedPlane ../../../../layers/Layer ../../../../layers/buildingSublayers/BuildingComponentSublayer ../support/loggerUtils ../../interactive/analysisTools/slice/sliceToolUtils ../../../../widgets/Slice/SlicePlane".split(" "),
function(f,r,k,x,y,z,c,l,A,m,H,I,J,B,C,v,D,E,q,F){function G(n,p){h.has(n)||h.set(n,{all:[],activeController:null});h.get(n).all.push(p)}const t=z.getLogger("esri.views.3d.analysis.Slice.SliceController");f.SliceController=function(n){function p(a){a=n.call(this,a)||this;a._handles=new y;a._internalChange=!1;a._currentSlicePlane=null;a.state="pending";return a}r._inheritsLoose(p,n);var g=p.prototype;g.initialize=function(){this._handles.add(this.analysis.excludedLayers.on("before-add",a=>{const b=
a.item;null!=b&&(b instanceof v||b instanceof D)?b instanceof v&&q.isAlwaysDrapedLayer(b)?(t.error("excludedLayers",`Layer '${b.title}, id:${b.id}' of type '${b.type}' can not be individually excluded from slicing. Use 'excludeGroundSurface' instead.`),a.preventDefault()):this.analysis.excludedLayers.includes(b)&&a.preventDefault():(t.error("excludedLayers","Invalid layer type, layer must derive from Layer or BuildingComponentSublayer"),a.preventDefault())}));this._handles.add(l.reactTruthy(()=>this.view.ready&&
c.isSome(this.view.renderCoordsHelper),()=>this._initialize(),{sync:!0,initial:!0,once:!0}))};g._initialize=function(){"destroyed"!==this.state&&"ready"!==this.state&&(G(this.view,this),this._handles.add([l.react(()=>this.analysisView.analysisViewData.plane,()=>{this._internalChange||this._updateSlicePlaneFromBoundedPlane();this._updateLayerViews()},{sync:!0}),l.react(()=>this.analysis.excludeGroundSurface,()=>this._updateLayerViews(),{sync:!0}),this.analysis.excludedLayers.on("change",()=>this._updateLayerViews()),
l.react(()=>[this.analysisView.active,this.analysisView.visible],()=>{this._updateActiveController();this._updateViewSlicePlane()},{sync:!0}),l.react(()=>this._allLayerAndSubLayerViews,()=>this._updateLayerViews())]),this._handles.add([l.react(()=>this.analysis.shape,()=>{this._internalChange||(this._updateBoundedPlaneFromSlicePlane(),this._updateViewSlicePlane())},{sync:!0})],"analysis"),this._set("state","ready"),this._updateActiveController(),this._updateBoundedPlaneFromSlicePlane(),this._updateViewSlicePlane())};
g.destroy=function(){if("destroyed"!==this.state&&"pending"!==this.state){this.analysisView.active=!1;{var a=this.view;if(!h.has(a))throw Error("view expected in global slice register");const b=h.get(a),e=b.all.lastIndexOf(this);if(-1===e)throw Error("controller expected in global slice register");b.all.splice(e,1);0===b.all.length&&h.delete(a)}this._handles.destroy();this.view.slicePlane=null;this.set("view",null);this._set("state","destroyed")}};g.whenReady=function(){var a=r._asyncToGenerator(function*(){yield A.whenOnce(this,
"ready");return this});return function(){return a.apply(this,arguments)}}();g._updateBoundedPlaneFromSlicePlane=function(){const a=this.analysis.shape;var b=this._currentSlicePlane;if(!(c.isNone(b)&&c.isNone(a)||c.isSome(b)&&c.isSome(a)&&a.equals(b))){var e=null;b=null;if(c.isSome(a)&&c.isSome(a.position)){e=a.position.spatialReference;const d=q.projectShape(a,this.view.spatialReference);c.isNone(d)&&E.logFailedGeometryProjectionError(this.analysis,e,t);e=q.projectedShapeToPlane(d,this.view,{tiltEnabled:this.analysis.tiltEnabled},
C.create());c.isSome(e)&&(b={heading:a.heading,tilt:a.tilt,position:a.position,width:a.width,height:a.height})}this._currentSlicePlane=b;this._internalChange=!0;this.analysisView.analysisViewData.plane=e;this._internalChange=!1}};g._updateSlicePlaneFromBoundedPlane=function(){const a=q.planeToShape(this.analysisView.analysisViewData.plane,this.view,this.view.spatialReference,new F);let b=null;c.isSome(a)&&(b={heading:a.heading,tilt:a.tilt,position:a.position,width:a.width,height:a.height});this._currentSlicePlane=
b;this._internalChange=!0;this.analysis.shape=a;this._internalChange=!1;this._updateViewSlicePlane()};g._updateActiveController=function(){if(!u){var a=h.get(this.view);this.analysisView.active?(c.isSome(a.activeController)&&a.activeController!==this?(u=!0,u=a.activeController.analysisView.active=!1):c.isSome(a.activeController),this._updateLayerViews(),a.activeController=this):c.isSome(a.activeController)&&a.activeController!==this||!c.isSome(a.activeController)||a.activeController!==this||(a.activeController=
null,this._updateLayerViews())}};g._updateViewSlicePlane=function(){if("ready"===this.state){{var a=this.view;const b=h.get(a).activeController;c.isSome(b)&&c.isSome(b.analysisView.analysisViewData.plane)&&b.analysisView.visible?a.slicePlane=b.analysisView.analysisViewData.plane:a.slicePlane=null}}};g._updateLayerViews=function(){const a=c.isSome(this.analysisView.analysisViewData.plane)&&this.analysisView.visible&&this.analysisView.active,b=[],e=d=>{"layers"in d?d.layers.forEach(e):b.push(d)};this.analysis.excludedLayers.forEach(e);
this.view.allLayerViews.forEach(d=>{d.destroyed||("slicePlaneEnabled"in d&&(d.slicePlaneEnabled=a&&0>b.indexOf(d.layer)),"sublayerViews"in d&&d.sublayerViews.forEach(w=>{w.slicePlaneEnabled=a&&0>b.indexOf(w.sublayer)}))});null!=this.view.basemapTerrain&&(this.view.basemapTerrain.slicePlaneEnabled=a&&!this.analysis.excludeGroundSurface)};r._createClass(p,[{key:"ready",get:function(){return"ready"===this.state}},{key:"_allLayerAndSubLayerViews",get:function(){const a=this.view.allLayerViews.items;return a.concat(a.filter(q.isIBuildingSceneLayerView3D).flatMap(({sublayerViews:b})=>
b.items))}}]);return p}(x);k.__decorate([m.property({readOnly:!0})],f.SliceController.prototype,"state",void 0);k.__decorate([m.property()],f.SliceController.prototype,"view",void 0);k.__decorate([m.property()],f.SliceController.prototype,"analysis",void 0);k.__decorate([m.property()],f.SliceController.prototype,"analysisView",void 0);k.__decorate([m.property()],f.SliceController.prototype,"ready",null);k.__decorate([m.property()],f.SliceController.prototype,"_allLayerAndSubLayerViews",null);f.SliceController=
k.__decorate([B.subclass("esri.views.3d.analysis.Slice.SliceController")],f.SliceController);const h=new Map;let u=!1;Object.defineProperty(f,"__esModule",{value:!0})});