// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Handles ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/watchUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/mat4 ../../../../chunks/vec3 ../../../../geometry/support/vectorStacks ../../interactive/analysisTools/slice/sliceToolConfig ../../interactive/analysisTools/slice/sliceToolUtils ../../webgl-engine/materials/lineStippleUtils".split(" "),
function(c,l,d,w,x,g,m,t,e,B,C,D,y,u,p,q,h,r,z){c.SliceVisualization=function(v){function n(a){a=v.call(this,a)||this;a._handles=new x;a._gridVisualElement=null;a._outlineVisualElement=null;a.state="pending";a.showGrid=!1;a.editable=!0;return a}l._inheritsLoose(n,v);var f=n.prototype;f.initialize=function(){this._initialize()};f._initialize=function(){var a=l._asyncToGenerator(function*(){if("destroyed"!==this.state&&"ready"!==this.state){yield t.whenOnce(this.view,"ready",!0);var b=this.analysisView.analysisViewData;
if(g.isNone(b))throw Error("expected internal object to be valid");this._gridVisualElement=r.createGridVisualElement(this.view);this._outlineVisualElement=r.createOutlineVisualElement(this.view);this._handles.add([m.react(()=>({visible:g.isSome(b.plane)&&this.analysisView.visible,active:this.analysisView.active,editable:this.editable,showGrid:this.showGrid}),k=>this._updateMaterials(k),m.syncAndInitial),m.react(()=>b.plane,k=>this._updatePlane(k),m.syncAndInitial)],"internal");this._set("state","ready")}});
return function(){return a.apply(this,arguments)}}();f.destroy=function(){"destroyed"!==this.state&&"pending"!==this.state&&(this._handles.destroy(),this._gridVisualElement=g.destroyMaybe(this._gridVisualElement),this._outlineVisualElement=g.destroyMaybe(this._outlineVisualElement),this.set("view",null),this._set("state","destroyed"))};f.whenReady=function(){var a=l._asyncToGenerator(function*(){yield t.whenOnce(this,"ready");return this});return function(){return a.apply(this,arguments)}}();f._updatePlane=
function(a){if(!g.isNone(a)){var b=p.set(q.sv3d.get(),p.length(a.basis1),p.length(a.basis2),1);b=u.fromScaling(q.sm4d.get(),b);a=r.calculateBoundedPlaneTranslateRotate(a,q.sm4d.get());a=u.multiply(b,a,b);this._outlineVisualElement.transform=a;this._gridVisualElement.transform=a}};f._updateMaterials=function({visible:a,active:b,editable:k,showGrid:A}){this._outlineVisualElement.color=h.PLANE_OUTLINE_COLOR;this._outlineVisualElement.width=k?h.PLANE_OUTLINE_WIDTH:h.PLANE_PREVIEW_OUTLINE_WIDTH;this._outlineVisualElement.stipplePattern=
b?null:z.createStipplePatternSimple(5);b=A?h.GRID_COLOR:[0,0,0,0];this._gridVisualElement.backgroundColor=h.PLANE_BACKGROUND_COLOR;this._gridVisualElement.gridColor=b;this._gridVisualElement.visible=a;this._outlineVisualElement.visible=a};l._createClass(n,[{key:"ready",get:function(){return"ready"===this.state}}]);return n}(w);d.__decorate([e.property({readOnly:!0})],c.SliceVisualization.prototype,"state",void 0);d.__decorate([e.property()],c.SliceVisualization.prototype,"view",void 0);d.__decorate([e.property()],
c.SliceVisualization.prototype,"analysis",void 0);d.__decorate([e.property()],c.SliceVisualization.prototype,"analysisView",void 0);d.__decorate([e.property()],c.SliceVisualization.prototype,"ready",null);d.__decorate([e.property()],c.SliceVisualization.prototype,"showGrid",void 0);d.__decorate([e.property()],c.SliceVisualization.prototype,"editable",void 0);c.SliceVisualization=d.__decorate([y.subclass("esri.views.3d.analysis.Slice.SliceVisualization")],c.SliceVisualization);Object.defineProperty(c,
"__esModule",{value:!0})});