// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ./clock ./Error ./events ./Logger ./maybe".split(" "),function(g,G,v,C,H,k){function D(a){return new Promise((b,c)=>{try{a(b,c)}catch(d){Promise.resolve().then(()=>c(d))}})}function m(a="Aborted"){return new v("AbortError",a)}function w(a,b="Aborted"){if(E(a))throw m(b);}function t(a){return k.isSome(a)?"aborted"in a?a:a.signal:a}function E(a){a=t(a);return k.isSome(a)&&a.aborted}function q(a,b){a=t(a);if(!k.isNone(a))if(a.aborted)b();else return C.once(a,"abort",()=>b())}function r(a){return a&&
"AbortError"===a.name}function x(){let a=null;const b=new Promise((c,d)=>{a={promise:void 0,resolve:c,reject:d}});a.promise=b;return a}function y(a){if(a){if("function"!==typeof a.forEach){const b=Object.keys(a),c=b.map(d=>a[d]);return y(c).then(d=>{const e={};b.forEach((f,h)=>e[f]=d[h]);return e})}return D(b=>{const c=[];let d=a.length;0===d&&b(c);a.forEach(e=>{const f={promise:e||Promise.resolve(e)};c.push(f);f.promise.then(h=>{f.value=h}).catch(h=>{f.error=h}).then(()=>{--d;0===d&&b(c)})})})}}
function z(a,b,c){const d=new AbortController;q(c,()=>d.abort());return new Promise((e,f)=>{let h=setTimeout(()=>{h=0;e(b)},a);q(d,()=>{h&&(clearTimeout(h),f(m()))})})}function A(a){return F(a)?a:Promise.resolve(a)}function F(a){return a&&"object"===typeof a&&"then"in a&&"function"===typeof a.then}g.after=z;g.all=function(a){return Promise.all(a)};g.always=function(a,b){return a.then(b,b)};g.create=D;g.createAbortError=m;g.createDeferred=x;g.createResolver=function(){let a,b;const c=new Promise((e,
f)=>{a=e;b=f}),d=e=>{a(e)};d.resolve=e=>a(e);d.reject=e=>b(e);d.timeout=(e,f)=>G.default.setTimeout(()=>d.reject(f),e);d.promise=c;return d};g.createTask=function(a,b){let c=new AbortController,d;a=a(c.signal);let e={promise:a,finished:!1,abort:()=>{c&&(c.abort(),c=null)}};const f=()=>{e&&(e.finished=!0,e=null);k.isSome(d)&&(d.remove(),d=null);c=null};a.then(f,f);d=q(b,()=>{k.isSome(e)&&e.abort()});return e};g.debounce=function(a,b=-1){let c,d,e,f,h=null;const p=(...l)=>{if(c){d=l;f&&f.reject(m());
f=x();l=k.assumeNonNull(f.promise);if(h){var u=h;h=null;u.abort()}return l}e=f||x();f=null;if(0<b){const n=new AbortController,I=c=A(a(...l,n.signal));z(b).then(()=>{c===I&&(f?n.abort():h=n)})}else c=1,c=A(a(...l));l=()=>{const n=d;d=e=c=h=null;null!=n&&p(...n)};u=c;const B=e;u.then(l,l);u.then(B.resolve,B.reject);return k.assumeNonNull(B.promise)};return p};g.eachAlways=y;g.eachAlwaysValues=function(a){return y(a).then(b=>b.filter(c=>!!c.value).map(c=>c.value))};g.filter=function(a,b){const c=a.slice();
return Promise.all(a.map((d,e)=>b(d,e))).then(d=>c.filter((e,f)=>d[f]))};g.ignoreAbortErrors=function(a){return a.catch(b=>{if(!r(b))throw b;})};g.isAbortError=r;g.isAborted=E;g.isPromise=F;g.isPromiseLike=function(a){return a&&"function"===typeof a.then};g.logOnError=function(a,b=H.getLogger("esri")){return a.catch(c=>{r(c)||b.error(c)})};g.onAbort=q;g.onAbortOrThrow=function(a,b){a=t(a);if(!k.isNone(a))return w(a),C.once(a,"abort",()=>b(m()))};g.reject=function(a){return Promise.reject(a)};g.resolve=
function(a){return Promise.resolve(a)};g.throwIfAbortError=function(a){if(r(a))throw a;};g.throwIfAborted=w;g.throwIfNotAbortError=function(a){if(!r(a))throw a;};g.timeout=function(a,b,c,d){const e=c&&"abort"in c?c:null;null!=d||e||(d=c);let f=setTimeout(()=>{f=0;e&&e.abort()},b);const h=()=>d||new v("promiseUtils:timeout","The wrapped promise did not resolve within "+b+" ms");return a.then(p=>{if(0===f)throw h();clearTimeout(f);return p},p=>{clearTimeout(f);throw 0===f?h():p;})};g.waitTick=function(a){return Promise.resolve().then(()=>
{w(a)})};g.when=A;g.whenOrAbort=function(a,b){const c=t(b);return k.isNone(c)?a:new Promise((d,e)=>{let f=q(b,()=>e(m()));const h=()=>f=k.removeMaybe(f);a.then(h,h);a.then(d,e)})};g.whenOrTimeout=function(a,b){return Promise.race([a,z(b).then(()=>{throw new v("timeout",`Did not resolve within ${b} milliseconds`);})])};Object.defineProperty(g,"__esModule",{value:!0})});