// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/mathUtils ../../../../../core/screenUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/arrayUtils ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/vec2 ../../../../../chunks/vec2f64 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../geometry/support/plane ../../../camera/constraintUtils ../InteractiveController ../../utils/navigationUtils".split(" "),
function(g,n,p,x,y,z,C,D,E,A,q,r,b,d,t,u,B,e){g.ZoomController=function(v){function k(a){a=v.call(this,a)||this;a.view=null;a.tmpP=d.create();a.tmpDir=d.create();a.tmpN=d.create();a.tmpP0=r.create();a.tmpPoi=d.create();a.tmpRayDir=d.create();a.dragBeginPoint=y.createScreenPointArray();a.normalizedAnchorPoint=r.create();a.constraintOptions={selection:15,interactionType:1,interactionFactor:0,interactionStartCamera:null,interactionDirection:d.create(),tiltMode:0};a.plane=t.create();return a}n._inheritsLoose(k,
v);var m=k.prototype;m.begin=function(a){if(this.active){q.copy(this.dragBeginPoint,a);e.normalizeCoordinate(this.startCamera,a,this.normalizedAnchorPoint);this.intersectionHelper.intersectScreenFreePointFallback(a,this.tmpP);b.subtract(this.tmpDir,this.tmpP,this.startCamera.eye);b.normalize(this.tmpDir,this.tmpDir);var c;this.view.camera.position.hasZ&&(c=Math.abs(this.view.camera.position.z));c=x.clamp(e.PIVOT_DISTANCE_MODIFIER*c,e.DISTANCE_CLAMP_VALUES[0],e.DISTANCE_CLAMP_VALUES[1]);a=this.view._stage.renderView.getMinimalDepthForArea(this.view.getVoxelWasmPerSceneView(),
a[0],a[1],this.view.state.camera,e.SCREEN_PIXEL_AREA);b.scale(this.tmpDir,this.tmpDir,c>a?a:c);b.add(this.tmpP,this.startCamera.eye,this.tmpDir);b.subtract(this.tmpN,this.startCamera.eye,this.startCamera.center);b.normalize(this.tmpN,this.tmpN);0>this.tmpN[1]&&b.negate(this.tmpN,this.tmpN);t.fromPositionAndNormal(this.tmpP,this.tmpN,this.plane);this.constraintOptions.interactionStartCamera=this.startCamera}};m.update=function(a){if(this.active){e.intersectPlaneFromScreenPoint(this.plane,this.currentCamera,
this.dragBeginPoint,this.tmpPoi)||b.copy(this.tmpPoi,this.currentCamera.center);e.normalizeCoordinate(this.currentCamera,a,this.tmpP0);var c=4*(this.tmpP0[1]-this.normalizedAnchorPoint[1]);q.copy(this.normalizedAnchorPoint,this.tmpP0);b.subtract(this.tmpRayDir,this.tmpPoi,this.currentCamera.eye);var h=b.length(this.tmpRayDir),l=h*(1-c);b.copy(this.constraintOptions.interactionDirection,this.tmpRayDir);b.scale(this.constraintOptions.interactionDirection,this.constraintOptions.interactionDirection,
Math.sign(c)/h);var w=this.view.state.constraints.minimumPoiDistance;0<=c&&l<w&&(l=w,c=-(l-h)/h);1E-6>Math.abs(h-l)||(b.scale(this.tmpRayDir,this.tmpRayDir,c),this.currentCamera.eye=b.add(f,this.currentCamera.eye,this.tmpRayDir),b.lerp(f,this.currentCamera.center,this.tmpPoi,c),f[2]=this.tmpPoi[2]>this.startCamera.center[2]?Math.max(this.startCamera.center[2],f[2]):Math.min(this.startCamera.center[2],f[2]),this.currentCamera.center=f,this.constraintOptions.interactionFactor=u.pixelDistanceToInteractionFactor(this.dragBeginPoint,
a),u.applyAll(this.view,this.currentCamera,this.constraintOptions))}};m.end=function(){this.active&&this.finishController()};n._createClass(k,[{key:"intersectionHelper",get:function(){return this.view.sceneIntersectionHelper}}]);return k}(B.InteractiveController);p.__decorate([z.property({constructOnly:!0})],g.ZoomController.prototype,"view",void 0);g.ZoomController=p.__decorate([A.subclass("esri.views.3d.state.controllers.local.ZoomController")],g.ZoomController);const f=d.create();Object.defineProperty(g,
"__esModule",{value:!0})});