// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../chunks/_rollupPluginBabelHelpers ../core/Error ../core/mathUtils ../core/maybe ../core/promiseUtils ../core/unitUtils ../chunks/mat4 ../chunks/vec3 ../chunks/vec3f64 ./Extent ./Multipoint ../chunks/pe ./Point ./Polygon ./Polyline ./projectionEllipsoid ./support/aaBoundingRect ./support/Ellipsoid ./support/geodesicConstants ./support/GeographicTransformation ./support/spatialReferenceUtils ./support/zscale".split(" "),function(ta,l,ua,Ua,R,h,Va,Wa,S,P,Q,Xa,Ya,da,va,Za,$a,
T,ab,u,bb,U,w,cb){function wa(){return!!A&&da.isLoaded()}function ea(b){h.isNone(V)&&(V=Promise.all([da.load(),(new Promise((c,a)=>ta(["../chunks/geometryEngineBase"],c,a))).then(c=>c.geometryEngineBase),new Promise((c,a)=>ta(["./geometryAdapters/hydrated"],c,a))]));return V.then(([,c,{hydratedAdapter:a}])=>{Va.throwIfAborted(b);N=a;A=c.default;A._enableProjection(da.pe)})}function xa(b,c,a=null){return Array.isArray(b)?0===b.length?[]:fa(N,b,b[0].spatialReference,c,a):fa(N,[b],b.spatialReference,
c,a)[0]}function fa(b,c,a,d,e=null){if(h.isNone(a)||h.isNone(d))return c;if(W(a,d,e))return c.map(f=>h.unwrap(ya(f,a,d)));if(h.isNone(e)){const f=U.cacheKey(a,d);void 0!==X[f]?e=X[f]:(e=za(a,d,null),h.isNone(e)&&(e=new U),X[f]=e)}if(h.isNone(A))throw new Y;return A._project(b,c,a,d,e)}function za(b,c,a=null){if(h.isNone(A))throw new Y;if(h.isNone(b)||h.isNone(c))return null;b=A._getTransformation(N,b,c,a,null==a?void 0:a.spatialReference);return null!==b?U.fromGE(b):null}function W(b,c,a){return a?
!1:w.equals(b,c)?!0:w.isValid(b)&&w.isValid(c)&&!!ha(b,c,ia)}function ja(){ja=ua._asyncToGenerator(function*(b,c,a,d){if(!wa())if(Array.isArray(b))for(const {source:e,dest:f,geographicTransformation:g}of b){if(!W(e,f,g))return ea(d)}else if(!W(b,c,a))return ea(d)});return ja.apply(this,arguments)}function ya(b,c,a){return b?"x"in b?Aa(b,c,new va,a,0):"xmin"in b?Ba(b,c,new Xa,a,0):"rings"in b?Ca(b,c,new Za,a,0):"paths"in b?Da(b,c,new $a,a,0):"points"in b?Ea(b,c,new Ya,a,0):null:null}function Aa(b,
c,a,d,e){m[0]=b.x;m[1]=b.y;const f=b.z;m[2]=void 0!==f?f:e;if(!x(m,c,0,m,d,0,1))return null;a.x=m[0];a.y=m[1];a.spatialReference=d;void 0===f?(a.z=void 0,a.hasZ=!1):(a.z=m[2],a.hasZ=!0);void 0===b.m?(a.m=void 0,a.hasM=!1):(a.m=b.m,a.hasM=!0);return a}function Ea(b,c,a,d,e){const {points:f,hasZ:g,hasM:k}=b;b=[];const t=f.length,r=[];for(var q of f)r.push(q[0],q[1],g?q[2]:e);if(!x(r,c,0,r,d,0,t))return null;for(c=0;c<t;++c){e=3*c;q=r[e];const v=r[e+1];g&&k?b.push([q,v,r[e+2],f[c][3]]):g?b.push([q,v,
r[e+2]]):k?b.push([q,v,f[c][2]]):b.push([q,v])}a.points=b;a.spatialReference=d;a.hasZ=g;a.hasM=k;return a}function Da(b,c,a,d,e){const {paths:f,hasZ:g,hasM:k}=b;b=[];if(!Fa(f,g,k,c,b,d,e))return null;a.paths=b;a.spatialReference=d;a.hasZ=g;a.hasM=k;return a}function Ca(b,c,a,d,e){const {rings:f,hasZ:g,hasM:k}=b;b=[];if(!Fa(f,g,k,c,b,d,e))return null;a.rings=b;a.spatialReference=d;a.hasZ=g;a.hasM=k;return a}function Ba(b,c,a,d,e){const {xmin:f,ymin:g,xmax:k,ymax:t,hasZ:r,hasM:q}=b;if(!ka(f,g,r?b.zmin:
e,c,m,d))return null;a.xmin=m[0];a.ymin=m[1];r&&(a.zmin=m[2]);if(!ka(k,t,r?b.zmax:e,c,m,d))return null;a.xmax=m[0];a.ymax=m[1];r&&(a.zmax=m[2]);q&&(a.mmin=b.mmin,a.mmax=b.mmax);a.spatialReference=d;return a}function ka(b,c,a,d,e,f){p[0]=b;p[1]=c;p[2]=a;return x(p,d,0,e,f,0,1)}function la(b,c,a,d){if(h.isNone(c)||h.isNone(d)||2>b.length)return!1;2===b.length&&(p[0]=b[0],p[1]=b[1],p[2]=0,b=p);return x(b,c,0,a,d,0,1)}function Ga(b,c,a){if(h.isNone(c))return!1;c=D(c,Z);c=B[c][6];if(h.isNone(c))return!1;
c(b,0,p,0);a!==p&&(a[0]=p[0],a[1]=p[1],2<a.length&&(a[2]=p[2]));return!0}function x(b,c,a,d,e,f,g=1){c=ha(c,e,ia);if(h.isNone(c))return!1;if(c===n){if(b===d&&a===f)return!0;g=a+3*g;for(let k=a,t=f;k<g;k++,t++)d[t]=b[k];return!0}g=a+3*g;for(let k=a,t=f;k<g;k+=3,t+=3)c(b,k,d,t);return!0}function Fa(b,c,a,d,e,f,g=0){const k=[];for(const t of b)for(const r of t)k.push(r[0],r[1],c?r[2]:g);if(!x(k,d,0,k,f,0,k.length/3))return!1;d=0;e.length=0;for(const t of b){b=[];for(const r of t)c&&a?b.push([k[d++],
k[d++],k[d++],r[3]]):c?b.push([k[d++],k[d++],k[d++]]):(a?b.push([k[d++],k[d++],r[2]]):b.push([k[d++],k[d++]]),d++);e.push(b)}return!0}function Ha(b,c,a,d){b=Math.abs(y*b)+Math.asin(a/(d+c));return b>=Math.PI/2?Number.MAX_VALUE:a/Math.cos(b)}function ma(b,c,a){const d=Math.sin(b);b=Math.cos(b);const e=Math.sin(c);c=Math.cos(c);a[0]=-d;a[4]=-e*b;a[8]=c*b;a[12]=0;a[1]=b;a[5]=-e*d;a[9]=c*d;a[13]=0;a[2]=0;a[6]=c;a[10]=e;a[14]=0;a[3]=0;a[7]=0;a[11]=0;a[15]=1;return a}function Ia(b,c,a){ma(b,c,a);S.transpose(a,
a);return a}function D(b,c){if(c.spatialReference===b)return c.spatialReferenceId;c.spatialReference=b;"metersPerUnit"in c&&(c.metersPerUnit=Wa.getMetersPerUnitForSR(b,1));return b.wkt===T.SphericalECEFSpatialReference.wkt?c.spatialReferenceId=1:w.isWGS84(b)?c.spatialReferenceId=2:w.isWebMercator(b)?c.spatialReferenceId=3:w.isPlateCarree(b)?c.spatialReferenceId=12:b.wkt===T.WGS84ECEFSpatialReference.wkt?c.spatialReferenceId=4:4490===b.wkid?c.spatialReferenceId=5:b.wkt===T.SphericalPCPFMars.wkt?c.spatialReferenceId=
7:b.wkt===T.SphericalPCPFMoon.wkt?c.spatialReferenceId=9:w.isMars(b)?c.spatialReferenceId=8:w.isMoon(b)?c.spatialReferenceId=10:c.spatialReferenceId=0}function n(b,c,a,d){b!==a&&(a[d++]=b[c++],a[d++]=b[c++],a[d]=b[c])}function K(b,c,a,d){a[d++]=O*(b[c++]/u.earth.radius);a[d++]=O*(Math.PI/2-2*Math.atan(Math.exp(-b[c++]/u.earth.radius)));a[d]=b[c]}function Ja(b,c,a,d){K(b,c,a,d);E(a,d,a,d)}function Ka(b,c,a,d){K(b,c,a,d);F(a,d,a,d)}function La(b,c,a,d,e){var f=.4999999*Math.PI;f=R.clamp(y*b[c+1],-f,
f);f=Math.sin(f);a[d++]=y*b[c]*e.radius;a[d++]=e.halfSemiMajorAxis*Math.log((1+f)/(1-f));a[d]=b[c+2]}function L(b,c,a,d){La(b,c,a,d,u.earth)}function G(b,c,a,d){a[d]=b[c]*Ma;a[d+1]=b[c+1]*Ma;a[d+2]=b[c+2]}function M(b,c,a,d){a[d]=b[c]*aa;a[d+1]=b[c+1]*aa;a[d+2]=b[c+2]}function Na(b,c,a,d){K(b,c,a,d);G(a,d,a,d)}function na(b,c,a,d,e){e+=b[c+2];const f=y*b[c+1];b=y*b[c];c=Math.cos(f);a[d++]=Math.cos(b)*c*e;a[d++]=Math.sin(b)*c*e;a[d]=Math.sin(f)*e}function oa(b,c,a,d){na(b,c,a,d,u.moon.radius)}function pa(b,
c,a,d){na(b,c,a,d,u.mars.radius)}function E(b,c,a,d){na(b,c,a,d,u.earth.radius)}function ba(b,c,a,d,e){var f=b[c];const g=b[c+1];c=b[c+2];b=Math.sqrt(f*f+g*g+c*c);c=R.asinClamped(c/(0===b?1:b));f=Math.atan2(g,f);a[d++]=O*f;a[d++]=O*c;a[d]=b-e}function qa(b,c,a,d){ba(b,c,a,d,u.moon.radius)}function ra(b,c,a,d){ba(b,c,a,d,u.mars.radius)}function H(b,c,a,d){ba(b,c,a,d,u.earth.radius)}function Oa(b,c,a,d){H(b,c,a,d);L(a,d,a,d)}function Pa(b,c,a,d){H(b,c,a,d);F(a,d,a,d)}function F(b,c,a,d){{var e=u.earth;
const g=y*b[c];var f=y*b[c+1];b=b[c+2];c=Math.sin(f);f=Math.cos(f);const k=e.radius/Math.sqrt(1-e.eccentricitySquared*c*c);a[d++]=(k+b)*f*Math.cos(g);a[d++]=(k+b)*f*Math.sin(g);a[d++]=(k*(1-e.eccentricitySquared)+b)*c}}function I(b,c,a,d){var e=bb.earthEllipsoidConstants,f=b[c],g=b[c+1];b=b[c+2];let k;c=Math.abs(b);var t=f*f+g*g;var r=Math.sqrt(t);var q=t+b*b;var v=Math.sqrt(q);f=Math.atan2(g,f);var C=b*b/q;q=t/q;g=e.a2/v;t=e.a3-e.a4/v;.3<q?(C=c/v*(1+q*(e.a1+g+C*t)/v),v=Math.asin(C),g=C*C,q=Math.sqrt(1-
g)):(q=r/v*(1-C*(e.a5-g-q*t)/v),v=Math.acos(q),g=1-q*q,C=Math.sqrt(g));k=1-u.earth.eccentricitySquared*g;g=u.earth.radius/Math.sqrt(k);e=e.a6*g;g=r-g*q;t=c-e*C;c=q*g+C*t;r=q*t-C*g;e=r/(e/k+c);v+=e;0>b&&(v=-v);a[d++]=O*f;a[d++]=O*v;a[d]=c+r*e/2}function Qa(b,c,a,d){I(b,c,a,d);E(a,d,a,d)}function Ra(b,c,a,d){I(b,c,a,d);L(a,d,a,d)}function ha(b,c,a=sa()){return h.isNone(b)||h.isNone(c)?null:Sa(b,c,a).projector}function Sa(b,c,a){if(h.isNone(b)||h.isNone(c)||a.source.spatialReference===b&&a.dest.spatialReference===
c)return a;const d=D(b,a.source),e=D(c,a.dest);0===d&&0===e?w.equals(b,c)?a.projector=n:a.projector=null:a.projector=B[d][e];return a}function sa(){return{source:{spatialReference:null,spatialReferenceId:0,metersPerUnit:1},dest:{spatialReference:null,spatialReferenceId:0,metersPerUnit:1},projector:n}}let A=null,N=null,V=null,X={},Y=function(b){function c(){return b.call(this,"projection:not-loaded","projection engine not fully loaded yet, please call load()")||this}ua._inheritsLoose(c,b);return c}(Ua);
const Ma=u.earth.radius*Math.PI/180,aa=180/(u.earth.radius*Math.PI),B={[2]:{[5]:null,[8]:null,[10]:null,[11]:n,[6]:n,[1]:E,[7]:null,[9]:null,[0]:null,[3]:L,[12]:G,[2]:n,[4]:F},[5]:{[5]:n,[8]:null,[10]:null,[11]:n,[6]:n,[1]:E,[7]:null,[9]:null,[0]:null,[3]:null,[12]:G,[2]:null,[4]:F},[8]:{[5]:null,[8]:n,[10]:null,[11]:n,[6]:null,[1]:null,[7]:pa,[9]:null,[0]:null,[3]:null,[12]:null,[2]:null,[4]:null},[10]:{[5]:null,[8]:null,[10]:n,[11]:n,[6]:null,[1]:null,[7]:null,[9]:oa,[0]:null,[3]:null,[12]:null,
[2]:null,[4]:null},[3]:{[5]:null,[8]:null,[10]:null,[11]:K,[6]:K,[1]:Ja,[7]:null,[9]:null,[0]:null,[3]:n,[12]:Na,[2]:K,[4]:Ka},[4]:{[5]:I,[8]:null,[10]:null,[11]:I,[6]:I,[1]:Qa,[7]:null,[9]:null,[0]:null,[3]:Ra,[12]:function(b,c,a,d){I(b,c,a,d);G(a,d,a,d)},[2]:I,[4]:n},[1]:{[5]:H,[8]:null,[10]:null,[11]:H,[6]:H,[1]:n,[7]:null,[9]:null,[0]:null,[3]:Oa,[12]:function(b,c,a,d){H(b,c,a,d);G(a,d,a,d)},[2]:H,[4]:Pa},[7]:{[5]:null,[8]:ra,[10]:null,[11]:ra,[6]:null,[1]:null,[7]:n,[9]:null,[0]:null,[3]:null,
[12]:null,[2]:null,[4]:null},[9]:{[5]:null,[8]:null,[10]:qa,[11]:qa,[6]:null,[1]:null,[7]:null,[9]:n,[0]:null,[3]:null,[12]:null,[2]:null,[4]:null},[0]:{[5]:null,[8]:null,[10]:null,[11]:null,[6]:null,[1]:null,[7]:null,[9]:null,[0]:n,[3]:null,[12]:null,[2]:null,[4]:null},[11]:{[5]:n,[8]:n,[10]:n,[11]:n,[6]:n,[1]:E,[7]:pa,[9]:oa,[0]:null,[3]:L,[12]:G,[2]:n,[4]:F},[6]:{[5]:null,[8]:null,[10]:null,[11]:n,[6]:n,[1]:E,[7]:null,[9]:null,[0]:null,[3]:null,[12]:G,[2]:n,[4]:F},[12]:{[5]:M,[8]:null,[10]:null,
[11]:M,[6]:M,[1]:function(b,c,a,d){M(b,c,a,d);E(a,d,a,d)},[7]:null,[9]:null,[0]:null,[3]:function(b,c,a,d){M(b,c,a,d);L(a,d,a,d)},[12]:n,[2]:M,[4]:function(b,c,a,d){M(b,c,a,d);F(a,d,a,d)}}},Z={spatialReference:null,spatialReferenceId:0},Ta={spatialReference:null,spatialReferenceId:0},ia=sa(),db=sa(),y=R.deg2rad(1),O=R.rad2deg(1),p=Q.create(),z=Q.create(),J=Q.create(),m=Q.create(),ca=Q.create();l.canProjectToWGS84ComparableLonLat=function(b){if(h.isNone(b))return!1;b=D(b,Z);return!!B[b][6]};l.canProjectWithoutEngine=
W;l.computeENUToSphericalPCPFLocalRotation=ma;l.computeSphericalPCPFToENULocalRotation=Ia;l.computeTranslationToOriginAndRotation=function(b,c,a,d){if(h.isNone(b)||h.isNone(d))return!1;var e=D(b,Z),f=D(d,Ta);if(e===f&&1!==f&&7!==f&&9!==f&&(0!==e||w.equals(b,d)))return S.identity(a),S.translate(a,a,c),!0;if(1===f||7===f||9===f){e=B[e][11];f=B[11][f];if(h.isNone(e)||h.isNone(f))return!1;e(c,0,z,0);f(z,0,J,0);ma(y*z[0],y*z[1],a);a[12]=J[0];a[13]=J[1];a[14]=J[2];return!0}if(!(3!==f&&12!==f||2!==e&&1!==
e&&3!==e)){b=B[e][11];f=B[11][f];if(h.isNone(b)||h.isNone(f))return!1;b(c,0,z,0);f(z,0,J,0);1===e?Ia(y*z[0],y*z[1],a):S.identity(a);a[12]=J[0];a[13]=J[1];a[14]=J[2];return!0}return!1};l.getProjectorName=function(b,c){switch(ha(b,c,ia)){case n:return"copy3";case E:return"wgs84ToSphericalECEF";case L:return"wgs84ToWebMercator";case G:return"wgs84ToPlateCarree";case F:return"wgs84ToWGS84ECEF";case K:return"webMercatorToWGS84";case Ja:return"webMercatorToSphericalECEF";case Ka:return"webMercatorToWGS84ECEF";
case Na:return"webMercatorToPlateCarree";case I:return"wgs84ECEFToWGS84";case Qa:return"wgs84ECEFToSphericalECEF";case Ra:return"wgs84ECEFToWebMercator";case H:return"sphericalECEFToWGS84";case Oa:return"sphericalECEFToWebMercator";case ra:return"sphericalMarsPCPFToMars2000";case qa:return"sphericalMoonPCPFToMoon2000";case Pa:return"sphericalECEFToWGS84ECEF";case pa:return"mars2000ToSphericalPCPF";case oa:return"moon2000ToSphericalPCPF";default:return null}};l.getTransformation=za;l.getTransformations=
function(b,c,a=null){if(h.isNone(A))throw new Y;b=A._getTransformationBySuitability(N,b,c,a,null==a?void 0:a.spatialReference);if(null!==b){c=[];for(const d of b)c.push(U.fromGE(d));return c}return[]};l.initializeProjection=function(b,c,a,d){return ja.apply(this,arguments)};l.isLoaded=wa;l.load=ea;l.localLinearScaleFactors=function(b,c,a,d){if(h.isNone(c)||h.isNone(d))return!1;const e=D(c,Z);var f=D(d,Ta);if(e===f&&0!==e||w.equals(c,d))return a[0]=1,a[1]=1,a[2]=1,!0;if(1===e){c=P.length(b);b=c/Math.sqrt(b[0]*
b[0]+b[1]*b[1]);c/=u.earth.radius;if(3===f)return a[0]=b*c,a[1]=b*c,a[2]=1,!0;if(2===f||5===f)return f=180/(u.earth.radius*Math.PI),a[0]=f*b*c,a[1]=f*c,a[2]=1,!0}else if(12===e&&(2===f||5===f))return a[0]=aa,a[1]=aa,a[2]=1,!0;return!1};l.lonLatToSphericalPCPF=function(b,c,a,d,e=0){d+=e;e=Math.cos(a);b[0]=Math.cos(c)*e*d;b[1]=Math.sin(c)*e*d;b[2]=Math.sin(a)*d};l.lonLatToWebMercatorComparable=La;l.project=xa;l.projectBoundingRect=function(b,c,a,d){if(null==b)return!1;if(w.equals(c,d))return ab.copy(a,
b),!0;p[0]=b[0];p[1]=b[1];p[2]=0;if(!x(p,c,0,p,d,0,1))return!1;a[0]=p[0];a[1]=p[1];p[0]=b[2];p[1]=b[3];p[2]=0;if(!x(p,c,0,p,d,0,1))return!1;a[2]=p[0];a[3]=p[1];return!0};l.projectBoundingSphere=function(b,c,a,d){if(h.isNone(c)||h.isNone(d))return!1;c=Sa(c,d,db);if(c.projector===n)return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],!0;if(h.isNone(c.projector))return!1;const {source:e,dest:f}=c;if(3===f.spatialReferenceId){c=B[e.spatialReferenceId][2];if(h.isNone(c))return!1;c(b,0,z,0);L(z,0,a,0);a[3]=Ha(z[1],
b[2],b[3],u.earth.radius);return!0}if(2!==e.spatialReferenceId&&5!==e.spatialReferenceId||12!==f.spatialReferenceId)c.projector(b,0,a,0),a[3]=b[3]*e.metersPerUnit/f.metersPerUnit;else{d=B[1][12];let g=b[3];h.isSome(B[e.spatialReferenceId][1])&&h.isSome(d)&&(g=Ha(b[1],b[2],b[3],u.earth.radius));c.projector(b,0,a,0);a[3]=g}return!0};l.projectBuffer=x;l.projectDirection=function(b,c,a,d,e){P.copy(m,b);P.add(ca,b,c);la(m,a,m,e);la(ca,a,ca,e);P.subtract(d,ca,m);P.normalize(d,d)};l.projectExtent=function(b,
c,a=c.spatialReference,d=0){return h.isSome(a)&&h.isSome(Ba(b,b.spatialReference,c,a,d))};l.projectMany=fa;l.projectMultipoint=function(b,c,a=c.spatialReference,d=0){return h.isNone(a)?!1:h.isSome(Ea(b,b.spatialReference,c,a,d))};l.projectPoint=function(b,c,a=c.spatialReference,d=0){return h.isNone(a)?!1:h.isSome(Aa(b,b.spatialReference,c,a,d))};l.projectPointToVector=function(b,c,a,d=0){m[0]=b.x;m[1]=b.y;const e=b.z;m[2]=void 0!==e?e:d;return x(m,b.spatialReference,0,c,a,0,1)};l.projectPointToWGS84ComparableLonLat=
function(b,c){m[0]=b.x;m[1]=b.y;const a=b.z;m[2]=void 0!==a?a:0;return Ga(m,b.spatialReference,c)};l.projectPolygon=function(b,c,a=c.spatialReference,d=0){return h.isSome(a)&&h.isSome(Ca(b,b.spatialReference,c,a,d))};l.projectPolyline=function(b,c,a=c.spatialReference,d=0){return h.isSome(a)&&h.isSome(Da(b,b.spatialReference,c,a,d))};l.projectVectorToDehydratedPoint=function(b,c,a){return x(b,c,0,m,a.spatialReference,0,1)?(a.x=m[0],a.y=m[1],a.z=m[2],a):null};l.projectVectorToPoint=function(b,c,a){if(h.isNone(c)||
h.isNone(a))return null;const d=new va({spatialReference:a});return x(b,c,0,m,a,0,1)?(d.x=m[0],d.y=m[1],d.z=m[2],d):null};l.projectVectorToVector=la;l.projectVectorToWGS84ComparableLonLat=function(b,c,a){return Ga(b,c,a)};l.projectWithoutEngine=ya;l.projectXYZToVector=ka;l.sphericalPCPFtoLonLatElevation=ba;l.tryProjectWithZConversion=function(b,c){try{const a=xa(b,c);if(null==a)return null;"xmin"in b&&"xmin"in a&&(a.zmin=b.zmin,a.zmax=b.zmax);const d=cb.getGeometryZScaler(a.type,b.spatialReference,
c);h.isSome(d)&&d(a);return a}catch(a){if(!(a instanceof Y))throw a;return null}};l.unload=function(){V=N=A=null;X={}};Object.defineProperty(l,"__esModule",{value:!0})});